### PR TITLE
ISPN-14509 JdbcStringBasedStore bulk operations don't work when more …

### PR DESCRIPTION
**Pull request by wburns**
…than 128 segments worth of values are provided

https://issues.redhat.com/browse/ISPN-14509

### CODE REVIEW

**Comment by wburns** [comment]
So the test failure found with this PR is caused by a different bug that is just exposed because the test class is a bit stricter now
https://issues.redhat.com/browse/ISPN-14533

I am not sure the fix here as @ryanemerson is the marshalling master :D I think it might be a bug that we are wrapping a String value with a MarshallableUserObject myself. Looking more closely none of the basic types seem to be supported (Integer, Long, Double etc)

**Comment by wburns** [comment]
I pushed a commit to just skip the test failures in https://issues.redhat.com/browse/ISPN-14533 for now.

**Comment by jabolina** [comment]
CI stopped, replaying it.

**Comment by jabolina** [comment]
Merged, thanks @wburns

**Pull request merged**
