### PR TITLE
Ispn 13703

### PR DESCRIPTION
**Pull request by tomdearman**
Test and possible fix for [ISPN-13703](https://issues.redhat.com/browse/ISPN-13703). This is branched from 13.0.x, since there are some test fails already on this branch (at least when I run it) I can't be sure it doesn't create other test breaks but it certainly fixes the test that is submitted with this fix.

### CODE REVIEW

**Comment by pruivo** [comment]
@tomdearman there is something wrong with your PR. it is bringing the 13.0.x branch and it shouldn't.

**Comment by tomdearman** [comment]
As I clearly state in the comments I mistakenly select my PR into main 
at first, couldn't delete it but created a new PR (also in the ticket) 
which states it is for 13.0.x.

**Comment by wburns** [comment]
Replaced with https://github.com/infinispan/infinispan/pull/9887

**Comment by pruivo** [comment]
@wburns yeah, that is for 13.0.x.
@tomdearman we need a PR for main branch too.

**Pull request closed without merging**
