### PR TITLE
ISPN-7648 Implement Analyzer and Field.analyzer annotations for protobuf

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-7648

### CODE REVIEW

**Comment by gustavonalle** [comment]
There's one test failure:
org.infinispan.all (1)
embeddedquery.QueryDslConditionsTest

And I see there's a commit related to https://github.com/infinispan/infinispan/pull/5028, should that other one be integrated first?

**Comment by anistor** [comment]
@gustavonalle The failure in embeddedquery.QueryDslConditionsTest should be fixed now.

Yes, this needs https://github.com/infinispan/infinispan/pull/5028 first, so I'll start addressing the comments in that one right now.

**Comment by anistor** [comment]
I see the fix was not run by CI yet; let's wait a bit.

**Comment by gustavonalle** [comment]
I have plenty of failures in the HR client tests, but queries related tests passed, integrating...

**Comment by gustavonalle** [comment]
Integrated on master, thanks @anistor !

**Pull request merged**
