### PR TITLE
ISPN-13248 Allow different Intelligence for cluster failover

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.redhat.com/browse/ISPN-13248

- [x] Backport to new client
- [x] Documentation

### CODE REVIEW

**Comment by pruivo** [comment]
@tristantarrant we have an `AtomicInteger` to update the topology id. I can do the same for the client intelligence.

**Comment by pruivo** [comment]
changes:
* Created `ClientTopology` which contains the topology id and client intelligence since they are closely related
* HeaderParams contains an `AtomicReference<ClientTopology>`. Cluster switch changes the reference in all ongoing operations.

**Comment by pruivo** [comment]
Changes
* Backported to the new client (no testing)
* Added docs

**Comment by pruivo** [comment]
@dvagnero could you check the docs changes and see if they make sense and are clear? thanks!

**Comment by dvagnero** [comment]
Hey @pruivo yes I'll take a look. Sorry, I might have removed the other reviewers

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
