### PR TITLE
[11.0.x] ISPN-12162 Fix the Marshaller configuration

### PR DESCRIPTION
**Pull request by karesti**
https://issues.redhat.com/browse/ISPN-12162

### CODE REVIEW

**Comment by anistor** [comment]
This is a trivial and safe fix. Can we merge this in 11 now @tristantarrant ?

**Comment by anistor** [comment]
This was changed sligtly, based on review, Need to get the changes from this upstream commit: https://github.com/infinispan/infinispan/commit/91cc6c78ac67e0277594c16ef09c4ca0f38ba67a

**Comment by karesti** [comment]
@anistor some tests are broken I need to fix them. But IMO is the test that is wrong

**Comment by karesti** [comment]
@anistor I think it's ok now

**Comment by anistor** [comment]
GlobalMarshaller is sacred. Let's not touch it, not event in tests like these. I'd suggest using anything else, like IdentityMarshaller. Also please rebase the fix agains master because I already merged the initial form of your PR + my fix @karesti

**Comment by karesti** [comment]
@anistor I don't know what I should be doing here now

**Comment by karesti** [comment]
@anistor I changed to identity marshaller

**Comment by anistor** [comment]
Ok, the 2 tests are fine now. What still remains is to make ConfigurationBuilder look like in 91cc6c78ac67e0277594c16ef09c4ca0f38ba67a from master (not from your branch)

**Comment by karesti** [comment]
@anistor done

**Comment by anistor** [comment]
LGTM. Waiting for 11 branch unfreeze

**Comment by karesti** [comment]
@pruivo can this be merged then ?

**Comment by pruivo** [comment]
@karesti if CI is OK, yes. I retriggered the CI yesterday because of the number of failures.

**Comment by karesti** [comment]
@pruivo seems ok

**Pull request merged**
