### PR TITLE
ISPN-9409 ISPN-9424 CCE on scripts/filters/converters for older Hot Rod clients

### PR DESCRIPTION
**Pull request by gustavonalle**
…lder clients

https://issues.jboss.org/browse/ISPN-9409
https://issues.jboss.org/browse/ISPN-9424

### CODE REVIEW

**Comment by galderz** [comment]
Trying it out...

**Comment by galderz** [comment]
This particular issue might be fixed, but one of the Node.js client tests fails with NPE when executing a distributed script, looking if it's related...

**Comment by galderz** [comment]
The issue is [ISPN-9426](https://issues.jboss.org/browse/ISPN-9426). I don't think it's necessarily related to this one.

**Comment by gustavonalle** [comment]
Removed deprecated methods

**Comment by galderz** [comment]
Looks good, integrating

**Comment by gustavonalle** [comment]
@galderz it was preview, there was a failure on HotRodMergeTest

**Comment by gustavonalle** [comment]
Anyway, I'll send another PR to fix it

**Comment by galderz** [comment]
Oh my bad, sorry.

**Comment by gustavonalle** [comment]
np!

**Pull request merged**
