### PR TITLE
[9.1.x] ISPN-9217 If interrupted throw a HotRodClientException

### PR DESCRIPTION
**Pull request by galderz**
* HotRodClientException wraps InterruptedException

### CODE REVIEW

**Comment by rvansa** [comment]
@galderz Have we dropped CI for 9.1.x? Will we ever do a 9.1 release in upstream?

**Comment by galderz** [comment]
@rvansa CI [seems to be running](https://ci.infinispan.org/job/Infinispan/job/PR-6027/1/). I don't know if we'll do a 9.1 release but it's base of prod.

**Comment by danberindei** [comment]
@galderz build fails with `java.io.IOException: Invalid secret key format`

**Comment by galderz** [comment]
@danberindei No idea but doubt it's related to this change. @tristantarrant ?

**Comment by tristantarrant** [comment]
It's a problem introduced by JDK 8u171
https://access.redhat.com/solutions/3419621
https://github.com/jboss-modules/jboss-modules/pull/192
I wouldn't bother with 9.1.x

**Pull request closed without merging**
