### PR TITLE
ISPN-9247 Upgrade to Wildfly 13.0.0.Final

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-9247

### CODE REVIEW

**Comment by tristantarrant** [comment]
78 failures...

**Comment by tristantarrant** [comment]
62 failures...

**Comment by tristantarrant** [comment]
Down to 20

**Comment by ryanemerson** [comment]
Closing in favour of https://github.com/infinispan/infinispan/pull/6081

**Pull request closed without merging**
