### PR TITLE
ISPN-14176 Protostream 4.5.0.Final

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14176

### CODE REVIEW

**Comment by ryanemerson** [comment]
The testsuite needs updating to reflect the changes  introduced by https://github.com/infinispan/protostream/pull/172

**Comment by tristantarrant** [comment]
Yes, I was waiting for CI to discover all the places this was tested.

**Comment by tristantarrant** [comment]
@ryanemerson CI looks good now

**Comment by ryanemerson** [comment]
Thanks @tristantarrant. The test strings are much more sane now :smile:

**Pull request merged**
