### PR TITLE
ISPN-7872 Emit warning when an interceptor does not handle functional commands

### PR DESCRIPTION
**Pull request by rvansa**
https://issues.jboss.org/browse/ISPN-7872

I've also fixed couple of interceptors where the fix was trivial.
Eventually all warnings should be fixed and we'll make the checkstyle warning an error. I hope this will warning will push for fixes better than open JIRAs (actually I've started with filing https://issues.jboss.org/browse/ISPN-7871 and then I thought there'll be other places that need attention).

### CODE REVIEW

**Comment by rvansa** [comment]
@slaskawi I've requested your review as you're the one who's the most into checkstyle.

**Comment by galderz** [comment]
@slaskawi Can you look into this?

**Comment by danberindei** [comment]
Integrated, thanks Radim!

**Comment by danberindei** [comment]
Looks good, let's see if anyone actually watches the warnings report in CI :)

http://ci.infinispan.org/job/Infinispan/job/PR-5167/32/checkstyleResult/new/

**Pull request closed without merging**
