### PR TITLE
Updated KUBE_PING version

### PR DESCRIPTION
**Pull request by slaskawi**

### CODE REVIEW

**Comment by slaskawi** [comment]
You know what... Infinispan works very stable on `0.9.1`, let's not change it just before GA. It's asking for troubles...

**Comment by rhusar** [comment]
I thought you guys are doing a component upgrade Jiras for this kind of stuff?

**Comment by slaskawi** [comment]
Sometimes we do and sometimes we just bump versions up :) But I agree with
you, I'll do a JIRA.

**Comment by slaskawi** [comment]
There will be another upgrade... I discovered some compatibility problems...

**Comment by rhusar** [comment]
Plus don't forget a component Jira :-)

**Pull request closed without merging**
