### PR TITLE
ISPN-9021 Remote query: add option to disable default/legacy indexing per schema file

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-9021

This should improve performance for types that do not need indexing and thus are not annotated for indexing.

### CODE REVIEW

**Comment by anistor** [comment]
retest this please

**Comment by anistor** [comment]
Add ```option enable_legacy_indexing=false;``` to your protobuf schema files and types without indexing annotations no longer get indexed sparing you from having to add ```@Indexed(false)``` all of them to obtain the same effect. Are we on the right track @gustavonalle ?

**Comment by gustavonalle** [comment]
@anistor I find this new config a bit confusing: 

```option named 'enable_legacy_indexing', which when absent is considered to default to true```. 

The property is about 'enabling' something which by default is 'true' and needs to be set to 'false' in order to increase performance, and furthermore it carries 'legacy' in the name which is not actually legacy at the moment.

What about calling it ```fields_indexed_by_default``` or ```index_non_annotated_fields``` ?

**Comment by anistor** [comment]
Yes, the name is giving me dizziness too. I think I find  ```indexed_by_default``` more clear and concise.

**Comment by gustavonalle** [comment]
LGTM, could you update the documentation? Section ```11.3.3. Indexing of Protobuf encoded entries``` is outdated with this change

**Comment by anistor** [comment]
Yes, of course

**Comment by gustavonalle** [comment]
Hi @anistor, shall we get this guy in?

**Comment by anistor** [comment]
Let me rebase it first.

**Comment by anistor** [comment]
Rebased. Should be ready now.

**Comment by anistor** [comment]
Rebased again

**Comment by anistor** [comment]
Rebased again

**Comment by anistor** [comment]
retest this please

**Comment by anistor** [comment]
@gustavonalle This should be ready. I started a new CI run because the last one did not have any test results. It may have died abruptly.

**Comment by gustavonalle** [comment]
Merged, thanks!

**Pull request merged**
