### PR TITLE
ISPN-7337 Configure near cache via configuration properties

### PR DESCRIPTION
**Pull request by galderz**
https://issues.jboss.org/browse/ISPN-7337

### CODE REVIEW

**Comment by galderz** [comment]
Could be a duplicate of #6156

**Comment by pruivo** [comment]
@galderz checkstyle is failing. 
is it worth to review this PR instead of Tristan's PR? (in case you need it for Beta1)

**Comment by karesti** [comment]
@galderz needs rebase

**Comment by tristantarrant** [comment]
@galderz my PR contains a number of additional items:
* a regex to match cache names
* tests for spring
* documentation
also the PR has additional commits for a clean up of the properties javadoc, some more tests around near-cache and TTL and other bits. I'm therefore closing this one (hope that doesn't make you sad :) And yes, I apologize for duplicating a Jira...

**Pull request closed without merging**
