### PR TITLE
ISPN-10364 Persistence (Blocking) thread pool should have a queue

### PR DESCRIPTION
**Pull request by wburns**
https://issues.jboss.org/browse/ISPN-10364

### CODE REVIEW

**Comment by danberindei** [comment]
We need to add something like this for the persistence thread pool, to reduce the number of threads used by tests and to not depend on the number of cpus:

https://github.com/infinispan/infinispan/blob/95e237b4fe0f891715fdea928324b14b76504c5d/core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java#L436

And 5000 seems kind of high to me, since we don't use AbortPolicy I think 1000 is enough.

**Comment by wburns** [comment]
This will actually increase the thread pool size on CI boxes with only 1 core :) I can change it though as it runs more locally.

The queue size of only 5K still seems more than sufficient to me. It is more important to not be executing possibly blocking code on the CPU thread if possible.

**Comment by wburns** [comment]
Created https://github.com/infinispan/infinispan/pull/7106 to  handle the test config

**Comment by danberindei** [comment]
@wburns we haven't had CI boxes with only 1 core for a really long time, the agents are up to 4 cores now :)

For the queue size, I just like all the executors having the same queue size, because it doesn't matter if a thread blocks submitting a task to the persistence executor or to the async executor, and the remote commands executor still has so many more threads than the persistence executor that a slightly bigger queue won't make a difference. The only way to not block is to make the queue ridiculously large, like ForkJoinPool or UFC_NB/MFC_NB, but we need a way to dial down applications that do `putAsync` in a loop.

**Comment by wburns** [comment]
Oh okay that is what you told me just a few weeks ago. Didn't realize we changed them.

In regards to all the same size. All the queues/executors will eventually be wrapped up into 2 total, so the sizes won't matter much then. And I personally feel that having a larger queue for the blocking thread pool is more important than the CPU thread pool. We don't want to be spending CPU threads running blocking tasks, which would lower the overall CPU utilization. However if a blocking thread pool was running a CPU task it wouldn't affect performance as much as it would just cause additional context switching and related tasks.

**Comment by danberindei** [comment]
> However if a blocking thread pool was running a CPU task it wouldn't affect performance as much as it would just cause additional context switching and related tasks.

Not true: https://issues.jboss.org/browse/ISPN-10368

**Comment by wburns** [comment]
What isn't true? This is just for tests, not a live system. And that check will be gone when passivation is non blocking https://issues.jboss.org/browse/ISPN-9723

**Comment by danberindei** [comment]
Assertions could (and IMO should) be enabled in production as well, no need for artificial differences between production and tests.

**Comment by wburns** [comment]
That is fine.

Either way as I mentioned that issue will never happen in 10.0 Final when non blocking passivation is added as it should be. I have and always will be talking about the final product not necessarily the current state. Just add some vision :)

**Comment by danberindei** [comment]
Sorry, I understand the high-level the vision is to do (almost) everything blocking on the persistence thread, but I don't see the connection between non-blocking passivation and removing the assertions in `PersistenceManagerImpl`. I trust you they will be removed though :)

**Comment by wburns** [comment]
Actually sorry this issue in particular isn't about non blocking activation. That specific issue will be fixed with non blocking store SPI, which I am hoping 🤞 to get into 10.1 since it produces elements from the store faster than it can produce them (in memory store that isn't blocking). It is compounded by the fact that we only allow 20 tasks in the processor queue, which imo is way too low and should probably be increased.

**Comment by wburns** [comment]
20 should have been enough for this test however - and I am guessing there is some other sort of leakage going on that is filling up the queue with worthless tasks.

**Pull request merged**
