### PR TITLE
ISPN-9637 Cleanup dependency injection in Ickle filters and their indexing providers

### PR DESCRIPTION
**Pull request by anistor**
…iders
https://issues.jboss.org/browse/ISPN-9636
https://issues.jboss.org/browse/ISPN-9637

### CODE REVIEW

**Comment by danberindei** [comment]
Should this remove anything other than `@SuppressWarnings` annotations?

**Comment by anistor** [comment]
Yes, @danberindei . cleanup is not just about removing stuff :)

**Comment by anistor** [comment]
Rebased. I've also created jiras for these refactorings and updated commit comments.

**Comment by danberindei** [comment]
Integrated, thanks Adrian!

**Pull request merged**
