### PR TITLE
ISPN-8344 DSL queries filtering only on type are always executed with…

### PR DESCRIPTION
**Pull request by anistor**
…out index

https://issues.jboss.org/browse/ISPN-8344

### CODE REVIEW

**Comment by gustavonalle** [comment]
Needs rebase to be able to run CI

**Comment by gustavonalle** [comment]
44 failures, lots of BindException(...) due to port conflicts, they don't seem related, running one more build

**Comment by gustavonalle** [comment]
Now 39 failures, some of them in query

**Comment by gustavonalle** [comment]
@anistor, looks like the 8.2.x branch is kind of broken

**Comment by anistor** [comment]
This, or 8.2.x without these commits?

**Comment by gustavonalle** [comment]
@anistor It seems the failures in this PR are already in ```8.2.x```, I can integrate this, but would not release 8.2.9.Final before sorting out those failures

**Comment by gustavonalle** [comment]
merged, thanks @anistor !

**Comment by anistor** [comment]
Thanks @gustavonalle ! Will postpone 82x then.

**Pull request merged**
