### PR TITLE
[9.4.x] ISPN-10272 RocskDbStore BatchWrite org.rocksdb.RocksDBException: unkn…

### PR DESCRIPTION
**Pull request by wburns**
…own WriteBatch tag

https://issues.jboss.org/browse/ISPN-10272

### CODE REVIEW

**Comment by tristantarrant** [comment]
Trivial... but there is a NPE in a RocksDB test...

**Comment by ryanemerson** [comment]
The NPE is on `9.4.x` branch already :cry:

**Comment by wburns** [comment]
The NPE is unrelated to the change - seems to be inconsistent failure as I can't reproduce it easily on my box.

**Comment by danberindei** [comment]
@ryanemerson the latest build has a ClassCastException:
https://ci.infinispan.org/job/Infinispan/job/PR-7018/2/testReport/junit/org.infinispan.all.embedded/EmbeddedAllTest/testAllEmbeddedFileStore/

**Comment by wburns** [comment]
That is unrelated to this PR as well: but oddly I couldn't reproduce it either in my local environment (the entire EmbeddedAllTest kept passing.

**Comment by danberindei** [comment]
Integrated, thanks Ryan!

I created https://issues.jboss.org/browse/ISPN-10305 for the `EmbeddedAllTest` random failures.

**Pull request merged**
