### PR TITLE
Use io.smallrye:jandex

### PR DESCRIPTION
**Pull request by tristantarrant**

### CODE REVIEW

**Review by ryanemerson — CHANGES_REQUESTED** [review]
It seems we have duplicate jandex jars now. The server is failing to start with:

```
[2023-07-07T09:51:16.438Z] 05:51:15,721 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#0] STDERR: Exception in thread "main" java.lang.IllegalArgumentException: Duplicate JARs:
[2023-07-07T09:51:16.438Z] 05:51:15,722 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#0] STDERR: /opt/infinispan/lib/jandex-2.4.2.Final.jar
[2023-07-07T09:51:16.438Z] 05:51:15,722 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#0] STDERR: file:/opt/infinispan/lib/jandex-3.1.2.jar
[2023-07-07T09:51:16.438Z] 05:51:15,722 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#0] STDERR: 	at org.infinispan.server.loader.Loader$1.visitFile(Loader.java:130)
[2023-07-07T09:51:16.438Z] 05:51:15,723 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#0] STDERR: 	at org.infinispan.server.loader.Loader$1.visitFile(Loader.java:118)
[2023-07-07T09:51:16.438Z] 05:51:15,723 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#0] STDERR: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
[2023-07-07T09:51:16.438Z] 05:51:15,723 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#0] STDERR: 	at org.infinispan.server.loader.Loader.classLoaderFromPath(Loader.java:118)
[2023-07-07T09:51:16.438Z] 05:51:15,723 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#0] STDERR: 	at org.infinispan.server.loader.Loader.run(Loader.java:85)
[2023-07-07T09:51:16.438Z] 05:51:15,723 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#0] STDERR: 	at org.infinispan.server.loader.Loader.main(Loader.java:49)
[2023-07-07T09:51:16.438Z] 05:51:15,834 INFO  [o.i.CONTAINER] [o.i.s.c.CliIT#1] STDOUT: 
[2023-07-07T09:51:16.438Z] 05:51:15,849 INFO  [t.l.i.s.c.cliit:latest] Container localhost/infinispan/server-o.i.s.c.cliit:latest started in PT0.341329336S
[2023-07-07T09:51:16.438Z] 05:51:15,849 INFO  [o.i.s.t.c.ContainerInfinispanServerDriver] Started container 1
[2023-07-07T09:51:16.438Z] 05:51:16,138 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#1] STDERR: Exception in thread "main" java.lang.IllegalArgumentException: Duplicate JARs:
[2023-07-07T09:51:16.438Z] 05:51:16,138 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#1] STDERR: /opt/infinispan/lib/jandex-2.4.2.Final.jar
[2023-07-07T09:51:16.438Z] 05:51:16,138 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#1] STDERR: file:/opt/infinispan/lib/jandex-3.1.2.jar
[2023-07-07T09:51:16.438Z] 05:51:16,139 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#1] STDERR: 	at org.infinispan.server.loader.Loader$1.visitFile(Loader.java:130)
[2023-07-07T09:51:16.438Z] 05:51:16,139 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#1] STDERR: 	at org.infinispan.server.loader.Loader$1.visitFile(Loader.java:118)
[2023-07-07T09:51:16.438Z] 05:51:16,139 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#1] STDERR: 	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
[2023-07-07T09:51:16.438Z] 05:51:16,139 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#1] STDERR: 	at org.infinispan.server.loader.Loader.classLoaderFromPath(Loader.java:118)
[2023-07-07T09:51:16.438Z] 05:51:16,139 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#1] STDERR: 	at org.infinispan.server.loader.Loader.run(Loader.java:85)
[2023-07-07T09:51:16.438Z] 05:51:16,140 ERROR [o.i.CONTAINER] [o.i.s.c.CliIT#1] STDERR: 	at org.infinispan.server.loader.Loader.main(Loader.java:49)
```

**Comment by tristantarrant** [comment]
Probably we need an exclusion

**Comment by tristantarrant** [comment]
At any rate, the duplicate jar detection was a stroke of genius :)

**Comment by tristantarrant** [comment]
```
[INFO] |  +- org.infinispan:infinispan-query:jar:15.0.0-SNAPSHOT:compile
[INFO] |  |  +- org.infinispan:infinispan-clustered-lock:jar:15.0.0-SNAPSHOT:compile
[INFO] |  |  +- org.hibernate.search:hibernate-search-v5migrationhelper-engine:jar:6.2.0.CR1:compile
[INFO] |  |  |  \- org.hibernate.search:hibernate-search-engine:jar:6.2.0.CR1:compile
[INFO] |  |  |     \- org.hibernate.search:hibernate-search-util-common:jar:6.2.0.CR1:compile
[INFO] |  |  |        \- org.jboss:jandex:jar:2.4.2.Final:compile
```

**Pull request closed without merging**
