### PR TITLE
ISPN-14158 Add --enable-preview when running on JDK 19

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14158

### CODE REVIEW

**Comment by tristantarrant** [comment]
@pruivo are you using `common.sh` for the gossip router launcher ?

**Comment by pruivo** [comment]
no, I'm not.

**Review by wburns — APPROVED** [review]
LGTM, confirmed the version was properly set to the variable when doing it in my shell.

However, CI seems to have died horribly. Rerunning it to see if it was a fluke.

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
