### PR TITLE
ISPN-12524 Utilise quay.io for test images

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-12524
~~https://issues.redhat.com/browse/ISPN-12525~~

### CODE REVIEW

**Comment by tristantarrant** [comment]
Maybe change server/tests/src/test/java/org/infinispan/server/persistence/PersistenceIT to test on mariadb by default instead of mysql

**Comment by ryanemerson** [comment]
Added for `master`, but I have omitted this on the backport PR.

**Comment by tristantarrant** [comment]
PerssitenceIT is failing for me with
Could not build image: unauthorized: access to the requested resource is not authorized

**Comment by ryanemerson** [comment]
Damn, that was because I missed the `sql` in `quay.io/bitnami/postgresql` and quay.io returns a 403 for `quay.io/bitnami/postgres`

**Comment by ryanemerson** [comment]
The mariadb switch has thrown up some unexpected sql errors, I have split this into a separate PR so we can get this merged ASAP for CI

https://github.com/infinispan/infinispan/pull/8892

**Pull request merged**
