### PR TITLE
ISPN-12638 Make NonBlockingStore.delete() return value optional

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-12638

Skip the previous lookup in RocksDBStore and RemoteStore

### CODE REVIEW

**Comment by wburns** [comment]
We should probably reevaluate whether it is even optionally needed later. But this is a good step.

**Comment by wburns** [comment]
There are quite a few test failures though, that need to be fixed to make it optional there as well.

**Comment by danberindei** [comment]
@wburns not sure how I was able to miss it, but I was trying to convert a `CompletableFuture(null)` to a rxjava `Single` and it was throwing a NPE.

I added a `thenApply` to avoid the NPE for now, but I will get rid of the extra lambda when I rebase https://github.com/infinispan/infinispan/pull/9408.

I also remembered to return `null` instead of `TRUE` in `AsyncNonBlockingStore.delete()`.

**Comment by wburns** [comment]
Integrated into main, thanks @danberindei !

**Pull request merged**
