### PR TITLE
ISPN-9871 ProtobufMetadataManagementInterceptor ClassCastException

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9871

StateConsumerImpl uses PutKeyValueCommands with InternalCacheEntry
values in order to preserve timestamps, so read the value from the
context

### CODE REVIEW

**Comment by anistor** [comment]
QueryInterceptor could be affected too. A quick glance indicates it accesses the value from context rather than the command, so maybe not an issue.

**Comment by danberindei** [comment]
@anistor yeah, I checked `QueryInterceptor` and it doesn't seem affected. Plus I'm sure query has some tests with state transfer ;)

**Comment by anistor** [comment]
Some tests indeed. Not sure those can cover the infinite oddities that can result from apparently minor changes in our interceptor stack. Which makes me think we need to hide that from users for good, and the commands too.

**Comment by anistor** [comment]
Integrated in master. Thanks @danberindei !

**Pull request closed without merging**
