### PR TITLE
 ISPN-8693 Improve ControlledRpcManager and BlockingLocalTopologyManager

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-8693

It should help fix random failures in RemoteGetDuringStateTransferTest (ISPN-8644) and WriteSkewDuringStateTransferTest (ISPN-8711).

Also fixes https://issues.jboss.org/browse/ISPN-8616

### CODE REVIEW

**Comment by rvansa** [comment]
@pruivo Would you like to take a look as well or should I merge this?

**Comment by pruivo** [comment]
@rvansa I trust in your review and in @danberindei code :+1:

**Comment by danberindei** [comment]
@rvansa I may have made some changes to the test logic as well, because it wasn't always clear to me what the test was trying to do. I hope with the expectations visible in the test method itself it will be clearer for whoever works on those tests next, but I can always add some comments where it's not clear enough.

**Comment by gustavonalle** [comment]
@danberindei I'm not 100% sure due to the limited failure tracking capabilities of the CI, but this PR might have caused some failures:

```
org.infinispan.stats.logic.OptimisticLockingTxClusterExtendedStatisticLogicTest.testLockingTimeoutOnOwnerWithRemoteTx
org.infinispan.stats.logic.OptimisticLockingTxClusterExtendedStatisticLogicTest.testLockingTimeoutOnNonOwnerWithRemoteTx
org.infinispan.stats.logic.OptimisticLockingTxClusterExtendedStatisticLogicTest.testLockingTimeoutOnOwnerWithLocalTx
org.infinispan.stats.logic.OptimisticLockingTxClusterExtendedStatisticLogicTest.testLockingTimeoutOnNonOwnerWithLocalTx
```

**Comment by gustavonalle** [comment]
Nevermind, just saw you're fixing them on https://github.com/infinispan/infinispan/pull/5705

**Pull request merged**
