### PR TITLE
ISPN-5641, ISPN-5640, ISPN-5639 replicated write performance

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-5639
https://issues.jboss.org/browse/ISPN-5640
https://issues.jboss.org/browse/ISPN-5641

### CODE REVIEW

**Comment by danberindei** [comment]
@wburns I removed `timeout()`.

**Comment by pruivo** [comment]
@danberindei looks good to me :)

**Comment by wburns** [comment]
Looks good, pulling...

**Comment by wburns** [comment]
Integrated into master, thanks @danberindei !

**Pull request closed without merging**
