### PR TITLE
ISPN-6522 Cannot use @DateBridge with WildFly modules

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-6522
https://issues.jboss.org/browse/ISPN-6699

### CODE REVIEW

**Comment by anistor** [comment]
I get a compile error.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project infinispan-query: Compilation failure: Compilation failure:
[ERROR] /home/adrian/work/infinispan22222/infinispan/query/src/main/java/org/infinispan/query/affinity/ShardIndexManager.java:[40,7] cannot find symbol
[ERROR] symbol:   method flushAndReleaseResources()
[ERROR] location: class org.infinispan.query.affinity.ShardIndexManager
[ERROR] /home/adrian/work/infinispan22222/infinispan/query/src/main/java/org/infinispan/query/affinity/ShardIndexManager.java:[62,13] cannot find symbol
[ERROR] symbol:   method flushAndReleaseResources()
[ERROR] location: class org.infinispan.query.affinity.ShardIndexManager.TopologyChangeListener
[ERROR] /home/adrian/work/infinispan22222/infinispan/query/src/main/java/org/infinispan/query/indexmanager/InfinispanBackendQueueProcessor.java:[32,7] org.infinispan.query.indexmanager.InfinispanBackendQueueProcessor is not abstract and does not override abstract method closeIndexWriter() in org.hibernate.search.backend.spi.BackendQueueProcessor
[ERROR] /home/adrian/work/infinispan22222/infinispan/query/src/main/java/org/infinispan/query/indexmanager/InfinispanBackendQueueProcessor.java:[107,4] method does not override or implement a method from a supertype
[ERROR] /home/adrian/work/infinispan22222/infinispan/query/src/main/java/org/infinispan/query/impl/ProjectionLoader.java:[34,59] cannot find symbol
[ERROR] symbol:   variable ENTITY_PLACEHOLDER
[ERROR] location: interface org.hibernate.search.query.engine.spi.EntityInfo

**Comment by gustavonalle** [comment]
@anistor please ignore it for now, it needs a hibernate search release

**Comment by anistor** [comment]
right. I've built the hsearch snapshot and it looks good now.

**Comment by gustavonalle** [comment]
@anistor it should compile fine now as Hibernate Search published snapshots regularly

**Comment by gustavonalle** [comment]
Updated with the Hibernate Search ugrade to ```5.6.0.Beta1```

**Comment by anistor** [comment]
Looking ....

**Comment by gustavonalle** [comment]
ops forgot the Lucene minor update

**Comment by anistor** [comment]
I'll wait then. CI also seems to be taking a break ... :)

**Comment by gustavonalle** [comment]
Updated with  Lucene ```5.5.0``` =>  ```5.5.1```

**Comment by anistor** [comment]
LGTM, but I'll wait for CI.

**Comment by anistor** [comment]
Pulling ...

**Comment by anistor** [comment]
Integrated in master. Thanks @gustavonalle !

**Pull request closed without merging**
