### PR TITLE
ISPN-5147 Wrap all attribute/resources in RestartParent*Handlers so that changes to a cache do not require a server reload

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5147

Store/loader properties modifications still mark the server as "reload-required". Everything else works

### CODE REVIEW

**Comment by galderz** [comment]
Are there any tests to verify this?

**Comment by galderz** [comment]
Could you explain a bit how this works too? Ta :)

**Comment by galderz** [comment]
To be more precise, there's a lot of refactoring in this code so it'd be good to get a summary of how it all works or what to focus on.

**Comment by tristantarrant** [comment]
Currently there are two failing tests, working on those

**Comment by tristantarrant** [comment]
Quick explanation: the original code attached a ReloadRequiredWriteAttributeHandler to every attribute and a standard operation handler which set context.reloadRequired(); everywhere.
What I've done is to replace all those with a RestartCacheWriteAttributeHandler for attributes and RestartCacheResourceAdd/RestartCacheResourceRemove for op handlers. When an attribute is modified or a cache sub-element is added/removed (e.g. eviction, expiration, cache-store, etc) the cache is restarted. To perform multiple mods at the same time, they need to be batched. The current testsuite actually already performs modifications, but I'll add tests to check that the server is not in reload-required state at the end.

**Comment by tristantarrant** [comment]
Modified the test to check that the server is in "running" state after applying cache changes. Cache-container changes still (correctly) result in a "reload-required" state.
https://github.com/infinispan/infinispan/pull/3368/files#diff-db40cfbe4e6f9193ecd1825d2ddf028aR98

**Comment by galderz** [comment]
Nice, thanks @tristantarrant, integrating...

**Comment by galderz** [comment]
Integrated, thx!

**Pull request closed without merging**
