### PR TITLE
ISPN-5100 Java Hot Rod client now checks for any failover listeners

### PR DESCRIPTION
**Pull request by galderz**
https://issues.jboss.org/browse/ISPN-5100

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8202/galderz:t_5100](http://ci.infinispan.org/viewLog.html?buildId=22565&buildTypeId=bt9&guest=1) for 71647343a29b947055aeebf07ed4e6e726bee494
Tests: 11215, 3 failed (3 new), 23 ignored. Build time: 02:11:16

Failed tests detected
* (new) TestSuite: org.infinispan.statetransfer.StateTransferReplicationQueueTest.testStateTransferWithNodeRestartedAndBusyNonTx


* (new) TestSuite: org.infinispan.statetransfer.ClusterTopologyManagerTest.testAbruptLeaveAfterGetStatus2


* (new) TestSuite: org.infinispan.distexec.mapreduce.DistributedSharedCacheTwoNodesMapReduceTest.testInvokeMapReduceOnAllKeys

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8209/galderz:t_5100](http://ci.infinispan.org/viewLog.html?buildId=22576&buildTypeId=bt9&guest=1) for 71647343a29b947055aeebf07ed4e6e726bee494
Tests: 11215, 2 failed (2 new), 23 ignored. Build time: 02:44:55

Failed tests detected
* (new) TestSuite: org.infinispan.atomic.DistWriteSkewAtomicMapAPITest.testConcurrentWritesAndIteration


* (new) TestSuite: org.infinispan.client.hotrod.DistTopologyChangeUnderLoadTest.testPutsSucceedWhileTopologyChanges



Error message is logged

Build duration (secs) is too large: 9848

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8252/galderz:t_5100](http://ci.infinispan.org/viewLog.html?buildId=22673&buildTypeId=bt9&guest=1) for bff04547aeb6e277512ad7b99119e0c7d519aca8
Tests: 10993, 2 failed (2 new), 23 ignored. Build time: 02:29:30

Failed tests detected
* (new) TestSuite: org.infinispan.partitionhandling.EntryRetrieverReplPartitionHandlingTest.testRetrievalWhenPartitionIsDegrated


* (new) org.infinispan.server.test.query.ManualIndexingIT.testManualIndexing



Error message is logged

Process exited with code 1

Build duration (secs) is too large: 8955

**Comment by galderz** [comment]
Actually, this is fine, no rebasing needed.

**Comment by tristantarrant** [comment]
After the latest integrations, client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientClusterEventsTest.java is failing to merge

**Comment by galderz** [comment]
Hmmm, weird... looking

**Comment by galderz** [comment]
Sorted @tristantarrant, sorry about that

**Comment by danberindei** [comment]
@galderz Are the EagerNearCacheTest failures related?

http://ci.infinispan.org/viewLog.html?buildId=22924&buildTypeId=bt9&guest=1

**Comment by galderz** [comment]
Could be, looking...

**Comment by galderz** [comment]
The test fails elsewhere, the failures is not related to this PR.

**Comment by danberindei** [comment]
Integrated, thanks Galder!

**Pull request closed without merging**
