### PR TITLE
ISPN-9787 Integration tests fail on the 8.2.x branch

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9787

### CODE REVIEW

**Comment by danberindei** [comment]
Looks good, only 60 failures now :smile: 

@tristantarrant there's an "Invalid secret key format" error here, which immediately made me think that maybe a JDK upgrade broke the ssl tests:

https://ci.infinispan.org/job/Infinispan/job/PR-6492/1/testReport/junit/org.infinispan.server.test.client.hotrod.security/HotRodPlainAuthLdapOverSslIT/Main_tests___testAdmin/

Unfortunately that's far from the only failure, but I think all but the OSGi failure might be all caused by a leaked server, so fixing the keystores might fix them as well:

https://ci.infinispan.org/job/Infinispan/job/PR-6492/1/testReport/junit/org.infinispan.it.compatibility/DistL1EmbeddedHotRodTest/X_Site_tests___setup/
https://ci.infinispan.org/job/Infinispan/job/PR-6492/1/testReport/junit/org.infinispan.test.integration.security.embedded/NodeAuthPropertiesHandlerIT/Main_tests___testReadItemOnJoiningNode/
https://ci.infinispan.org/job/Infinispan/job/PR-6492/1/testReport/junit/org.infinispan.server.test.client.hotrod/ScriptExecIT(localmode-udp)/X_Site_tests___testSimpleScriptExecutionWithParams/

The osgi failure is probably https://issues.jboss.org/projects/JBMAR/issues/JBMAR-188

**Comment by wburns** [comment]
@danberindei so this should be able to be integrated and the other failures should be handled in a different PR right?

**Comment by wburns** [comment]
Integrated into 8.2.x so we can get those additional tests fixed :)

**Comment by danberindei** [comment]
Yeah @wburns, this PR only fixes `JAVA_HOME`

**Pull request merged**
