### PR TITLE
ISPN-5541 Add provided scope to javax api dependencies

### PR DESCRIPTION
**Pull request by dmstahl**
https://issues.jboss.org/browse/ISPN-5541

### CODE REVIEW

**Comment by galderz** [comment]
If you're making javax.cache-api provided in ```jcache/remote```, shouldn't you make the same change in ```jcache/embedded``` ?

**Comment by dmstahl** [comment]
The build fails if the change is made in jcache/embedded.  It looks like the problem is related to the       <module.skipComponentMetaDataProcessing>false</module.skipComponentMetaDataProcessing> property being set.  I'm not real sure what the best way to proceed is - either remove that property or leave javax.cache-api as a compile dependency?

**Comment by dmstahl** [comment]
Updated

**Comment by galderz** [comment]
Integrated, thanks @dmstahl

**Pull request closed without merging**
