### PR TITLE
ISPN-11726 BlockingLocalTopologyManager is blocking - ignore in Block…

### PR DESCRIPTION
**Pull request by wburns**
…Hound

https://issues.redhat.com/browse/ISPN-11726

### CODE REVIEW

**Comment by karesti** [comment]
needs rebase @wburns

**Comment by wburns** [comment]
Updated

**Comment by karesti** [comment]
could this be related ?
org.infinispan.client.hotrod.DistTopologyChangeUnderLoadSingleOwnerTest.testRestartServerWhilePutting

**Comment by wburns** [comment]
No, that is unrelated. Guessing something with cache startup that wasn't quite fixed yet that @danberindei and @ryanemerson  uncovered.

**Pull request merged**
