### PR TITLE
ISPN-8719 KeySet.(iterator|spliterator|stream) not compatible with

### PR DESCRIPTION
**Pull request by wburns**
versions before 9.2

* Added iterator methods to Codecs
* Put appropriate methods on each Codec version

https://issues.jboss.org/browse/ISPN-8719

### CODE REVIEW

**Comment by wburns** [comment]
I have added tests and they all seem to work except for ProtocolVersion.2.3 where for some reason the result is getting jumbled and the messageId is found to be 0 causing a NPE. I am not sure where the bug is as the server side seems to be sending the correct bytes back. I need to look into it further still.

**Comment by wburns** [comment]
So the cause with version 2.3 is due to the fact that the retrieveEntries in newer clients always uses the 2.4 protocol even when 2.3 is set. Also newer clients can't communicate to any server of version 2.2 or older in general. So that means no client since 8.1 could ever talk to any version older than that.

**Comment by wburns** [comment]
Also fixed a 2.5+ client talking to 2.4 since it was always passing meta but that is not returned in 2.4. This would make reading entries return incorrect values and/or possibly hang.

**Comment by tristantarrant** [comment]
This looks great. We will eventually need some integration tests for testing against combinations of servers/clients.

**Pull request merged**
