### PR TITLE
ISPN-8427 Support for non-String keys in the rest server

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-8427

### Highlights

* The REST server no longer assumes keys are ```java.lang.String```
* Server storage is now byte[] by default
* The current master behaviour (of String keys) can be restored with:
```xml
<local-cache>
  <encoding>
    <key media-type="application/x-java-object;type=java.lang.String"/>
   </encoding>
<local-cache>
```
* A new HTTP header ```Key-Content-Type``` was introduced. This will describe the format of the key
when doing REST requests

* At request time, it's possible to represent bytes with hex notation, so to get a value from a cache whose key is ```byte[]{0x1,0x2,0x3}```:

```sh
curl -H "Key-Content-Type:application/octet-stream;encoding=hex"  http://host/rest/cache/0x010203
```

### Review suggestion

The most import test is ```org.infinispan.it.compatibility.EndpointInteroperabilityTest```, it demonstrates how to interact with HotRod and REST without using compatbility mode for several data types (primitives, byte[], String)

### CODE REVIEW

**Comment by gustavonalle** [comment]
Rebasing...

**Comment by gustavonalle** [comment]
run performance tests please
cs-rest

**Comment by tristantarrant** [comment]
@gustavonalle looks good, although I'd like to see some docs (can happen after CR2)

**Comment by gustavonalle** [comment]
@tristantarrant yes, docs are very much need for the rest server changes, including encoding, query, json canonical mapping and now this. The plan is to write them for the final.

**Comment by gustavonalle** [comment]
run performance tests please
cs-rest

**Comment by gustavonalle** [comment]
@tristantarrant https://issues.jboss.org/browse/ISPN-8725

**Comment by gustavonalle** [comment]
Rebased

**Comment by gustavonalle** [comment]
run performance tests please
cs-rest

**Comment by gustavonalle** [comment]
Perf tests are OK

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by tristantarrant** [comment]
@vblagoje @gustavonalle we need to add key/value types configuration to the console

**Pull request merged**
