### PR TITLE
ISPN-6007 Cache.get(...) using Flag.FORCE_WRITE_LOCK should retry

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-6007

Can be cherry-picked to 8.1.x

### CODE REVIEW

**Comment by danberindei** [comment]
@pferraro Could you try this?

**Comment by wburns** [comment]
This seems fine to me. Want to just have me pull it in or wait for @pferraro ?

**Comment by pferraro** [comment]
@danberindei I'll give it a shot now.

**Comment by pferraro** [comment]
@danberindei @wburns OK - this looks good.  Can we get this into the 8.1.x branch too?

**Comment by tristantarrant** [comment]
Pushed to both master and 8.1.x

**Pull request closed without merging**
