### PR TITLE
ISPN-9561 GlobalConfiguration should keep strong reference to classloader

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9561
https://issues.jboss.org/browse/ISPN-9563

Fixes random server startup NPEs

### CODE REVIEW

**Comment by anistor** [comment]
Episode IX? :))

**Comment by gustavonalle** [comment]
The force is strong in this PR :)

**Comment by danberindei** [comment]
Hmmm, I think I've missed some weak references in `GlobalComponentRegistry`

**Comment by gustavonalle** [comment]
WeakReferences are everywhere that involves a Classloader actually.

**Comment by danberindei** [comment]
Updated to remove `WeakReference` from `GlobalComponentRegistry` and `ComponentRegistry`

**Comment by galderz** [comment]
This is odd... GC has had a weak reference to Classloader for years and we've never had an issue before

**Comment by galderz** [comment]
5 years to be precise

**Comment by danberindei** [comment]
@galderz the NPE has been happening on server startup for a long time now, it's just that we never realized it was connected to the weak reference

**Comment by danberindei** [comment]
The remaining failure is unrelated.

I fixed a few failures by moving back the cast cast inside the `try...catch` block in `ServiceFinder.addServices()`:

https://ci.infinispan.org/job/Infinispan/job/PR-6291/4/testReport/

@Tristan the fact that we ignore `ClassCastException` for classes from different classloaders here makes me a little worried about how we deal with resources from a different Infinispan versions.
I don't think there's a way to deterministically load resources from the deployment but not from the container, so I'd consider rethrowing the exception there to get the user to exclude the container's Infinispan version explicitly.

**Comment by gustavonalle** [comment]
@tristantarrant any comments on above?

**Comment by tristantarrant** [comment]
I don't understand which cast you are referring to.

**Comment by danberindei** [comment]
Sorry @tristantarrant, I meant the `next()` call - internally it does a cast:

```
Caused by: java.util.ServiceConfigurationError: org.infinispan.configuration.parsing.ConfigurationParser: Provider org.infinispan.configuration.parsing.Parser not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.infinispan.commons.util.ServiceFinder.addServices(ServiceFinder.java:59)
	at org.infinispan.commons.util.ServiceFinder.load(ServiceFinder.java:43)
	at org.infinispan.configuration.parsing.ParserRegistry.<init>(ParserRegistry.java:73)
	at org.infinispan.configuration.parsing.ParserRegistry.<init>(ParserRegistry.java:67)
	at org.infinispan.configuration.parsing.ParserRegistry.<init>(ParserRegistry.java:63)
	at org.infinispan.globalstate.impl.GlobalConfigurationManagerImpl.start(GlobalConfigurationManagerImpl.java:72)
```
[full stack trace here](https://ci.infinispan.org/job/Infinispan/job/PR-6291/4/testReport/junit/org.infinispan.test.integration.as.jms.infinispan/SearchNewEntityJmsMasterSlaveUsingInfinispanAndModulesIT/org_infinispan_test_integration_as_jms_infinispan_SearchNewEntityJmsMasterSlaveUsingInfinispanAndModulesIT/)

Anyway, whether we ignore incompatible services isn't really relevant to this PR, I accidentally discovered it when IntelliJ suggested that I simplify the `while` loop in `ServiceFinder.addServices()`.

**Comment by tristantarrant** [comment]
You mean it is finding "Parser" from another classloader ? (which is probably throwing some kind of VerifyError internally) ?

**Comment by danberindei** [comment]
Yeah, it's from another classloader so it implements a different `ConfigurationParser`. There's no error, `ServiceLoader` just checks if the implementation implements the right interface and throws the `ServiceConfigurationError` otherwise. But obviously there's no such check for resources, so we could be mixing resources (e.g. features) from different classloaders.

**Comment by gustavonalle** [comment]
All good @tristantarrant ? Can I push the button?

**Comment by tristantarrant** [comment]
Go ahead

**Comment by gustavonalle** [comment]
Merged, thanks @danberindei

**Pull request merged**
