### PR TITLE
ISPN-11863 Deprecate ClusterLoader, LocalOnlyCacheLoader and HotRod L…

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-11863

### CODE REVIEW

**Comment by wburns** [comment]
I assume https://ci.infinispan.org/job/Infinispan/job/PR-8347/2/#showFailuresLink is not related? I just haven't seen failures like that on CI.

**Comment by ryanemerson** [comment]
> I assume https://ci.infinispan.org/job/Infinispan/job/PR-8347/2/#showFailuresLink is not related? I just haven't seen failures like that on CI.

I'm pretty certain the changes shouldn't have caused any new failures as I have just deprecated things. Lets see what CI says no I have rebased.

**Comment by ryanemerson** [comment]
Failures aren't related

**Comment by wburns** [comment]
Integrated into master, thanks @ryanemerson !

**Pull request merged**
