### PR TITLE
ISPN-9406 Update to Hibernate 5.3.4.Final

### PR DESCRIPTION
**Pull request by galderz**
https://issues.jboss.org/browse/ISPN-9406

### CODE REVIEW

**Comment by galderz** [comment]
OSGI errors, do not integrate for now.

**Comment by Sanne** [comment]
@galderz ORM 5.3.4.Final is being released right now...

**Comment by galderz** [comment]
@Sanne Saw that... I'll rework PR for that release.

**Comment by galderz** [comment]
Updated, let's see what CI says... 😴

**Comment by galderz** [comment]
This looks good and CI looks good too, can someone integrate this ASAP?

**Comment by Sanne** [comment]
thanks for letting me know. Building ...

**Comment by galderz** [comment]
@Sanne building what?

**Comment by galderz** [comment]
CI has already passed...

**Comment by Sanne** [comment]
I don't merge PRs unless they pass locally.

**Comment by galderz** [comment]
> I don't merge PRs unless they pass locally.

Pass locally what?

**Comment by Sanne** [comment]
all tests. What else?

**Comment by pruivo** [comment]
@Sanne I'm going to do the Beta1 release today. when can I push the button?

**Comment by Sanne** [comment]
@pruivo I'm having several failures. They seem bad, but they seem unrelated.

This PR looks good to merge, but I can't do it - probably something wrong with my system.

could you merge it?

**Comment by pruivo** [comment]
@Sanne yes I can :) thank you!

**Comment by pruivo** [comment]
integrated! thanks @galderz !

**Comment by Sanne** [comment]
thanks @galderz && @pruivo ! :+1:

**Pull request merged**
