### PR TITLE
ISPN-6150 Removed Spring 3 support

### PR DESCRIPTION
**Pull request by slaskawi**
Removed Spring 3 support: https://issues.jboss.org/browse/ISPN-6150

I'm not sure how to flag proper branches for this - 9.0 and 8.3. Could you please give me a hand?

### CODE REVIEW

**Comment by slaskawi** [comment]
Rebased

**Comment by slaskawi** [comment]
Rebased

**Comment by slaskawi** [comment]
Rebased

**Comment by tristantarrant** [comment]
Pulling

**Comment by tristantarrant** [comment]
Pushed, thanks

**Pull request closed without merging**
