### PR TITLE
ISPN-13757 Tweak valid auth mechanisms based on LDAP configuration

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-13757

### CODE REVIEW

**Comment by ryanemerson** [comment]
@tristantarrant Compilation failure :slightly_frowning_face: 
```
Maven failure: org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project infinispan-client-hotrod: Compilation failure
```

**Review by ryanemerson — APPROVED** [review]
LGTM, but needs a rebase due to a log conflict

**Comment by tristantarrant** [comment]
Rebased

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
