### PR TITLE
ISPN-9164 ClassNotFoundException thrown by the REST server when using JSON

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-9164

### CODE REVIEW

**Comment by vblagoje** [comment]
I've tried these changes while diagnosing this issue with @gustavonalle  
Approved. Please integrate @slaskawi

**Comment by slaskawi** [comment]
@vblagoje Just waiting for CI... do you need it right away? Or in 2-3 hours would be fine?

**Comment by ryanemerson** [comment]
@slaskawi @gustavonalle Are these failures not related?

```
org.infinispan.server.test.query.RemoteNonIndexedQueryIT.testQueryViaRest
org.infinispan.server.test.query.RemoteQueryIspnDirIT.testQueryViaRest
org.infinispan.server.test.query.RemoteQueryOffHeapIT.testQueryViaRest
```

**Comment by gustavonalle** [comment]
Yes, they are, I will send another PR to fix

**Comment by gustavonalle** [comment]
https://github.com/infinispan/infinispan/pull/5984

Haven't run the full suite locally, let's wait for CI

**Pull request merged**
