### PR TITLE
ISPN-15005 Quarkus 3.1.3.Final

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-15005
https://issues.redhat.com/browse/ISPN-15012
https://issues.redhat.com/browse/ISPN-15013
https://issues.redhat.com/browse/ISPN-15014
https://issues.redhat.com/browse/ISPN-15015

### CODE REVIEW

**Review by karesti — COMMENTED** [review]
does not look good... ? Infinispan Quarkus :: CLI .......................... FAILURE [01:29 min]

**Comment by ryanemerson** [comment]
> does not look good... ?

Definitely not good! Looking into it

**Comment by ryanemerson** [comment]
@tristantarrant This is looking like it's going to be a real pain with the manual version alignment. I think we need to go back to importing the quarkus bom.

**Comment by ryanemerson** [comment]
Requires https://github.com/infinispan/infinispan/pull/11081

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
