### PR TITLE
ISPN-6313 Update the Java requirement in the docs to 8.

### PR DESCRIPTION
**Pull request by tristantarrant**
Pull to master, 8.1.x and 8.0.x please

https://issues.jboss.org/browse/ISPN-6313

### CODE REVIEW

**Comment by anistor** [comment]
Pulling ...

**Comment by anistor** [comment]
@tristantarrant Java SE 7 is still mentioned in the docs. ```Infinispan is developed and primarily tested against Oracle's Java SE 7.
It should work with most Java SE 7 implementations, including those from IBM, HP, Apple, Oracle, and OpenJDK.
We also build/test against JDK 8.```

**Comment by tristantarrant** [comment]
@anistor addressed all issues

**Comment by anistor** [comment]
Integrated in master and 8.1.x. Thanks @tristantarrant !

**Comment by anistor** [comment]
Integrated in 8.0.x also.

**Pull request merged**
