### PR TITLE
ISPN-16612 Elytron 2.6.0

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-16612

### CODE REVIEW

**Comment by tristantarrant** [comment]
Failures on GH actions are irrelevant.
Jenkins is failing because of the flaky test reporter

**Comment by ryanemerson** [comment]
@tristantarrant Please rebase on `main`. The flaky test reporter failed, but the tests also timed out.

**Comment by tristantarrant** [comment]
Rebased

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
