### PR TITLE
ISPN-6513 Updated repositories to public-jboss

### PR DESCRIPTION
**Pull request by slaskawi**
This is an additional fix to https://github.com/infinispan/infinispan/pull/4251

Some of the artifacts (like [1]) are present only in `public-jboss` repository.

[1] https://repository.jboss.org/nexus/content/groups/public-jboss/com/thoughtworks/xstream/xstream/1.4.9/

### CODE REVIEW

**Comment by slaskawi** [comment]
BTW I have updated CI agents to use `public-jboss` to unblock builds

**Comment by danberindei** [comment]
@slaskawi Couldn't we remove the dependency on xstream instead? :D

**Comment by danberindei** [comment]
Integrated, thanks Sebastian!

**Comment by mgencur** [comment]
Hey, did you know that the Creaper dependency is only in the "public" repository?

**Comment by danberindei** [comment]
@slaskawi @mgencur I cleaned up my local repository and I was able to build everything with the "public" repository, so I think it's safe to revert this. xstream is definitely present in Maven Central, so we don't need an additional repository for that one. Speaking of which, didn't Maven Central have a rule that all dependencies of artifacts uploaded there (e.g. infinispan) must not depend on artifacts that are not in Maven Central?

**Pull request closed without merging**
