### PR TITLE
ISPN-16017 Drop OpenSSL

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-16017

### CODE REVIEW

**Comment by pruivo** [comment]
@tristantarrant do you want to deprecate `org.infinispan.client.hotrod.configuration.SslConfigurationBuilder#provider`and the property name?

**Comment by tristantarrant** [comment]
No, provider is needed for PKCS11 FIPS support

**Review by pruivo — APPROVED** [review]
LGTM

**Comment by tristantarrant** [comment]
It's green!

**Comment by pruivo** [comment]
merged! thanks @tristantarrant !

**Pull request merged**
