### PR TITLE
ISPN-12623 Move CDI tests to integrationtests/server-integration/server-integration-commons project

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.redhat.com/browse/ISPN-12623

### CODE REVIEW

**Comment by diegolovison** [comment]
This PR will show two issues
* https://issues.redhat.com/browse/ISPN-12712
* https://issues.redhat.com/browse/ISPN-12713

**Comment by ryanemerson** [comment]
@diegolovison I'm not sre it's a good idea to merge deliberately failing tests. I think we need to initially merge the code with the tests ignored so that they can be renabled when somebody is able to work on the underlying  issue(s).

**Comment by diegolovison** [comment]
```
merge the code with the tests ignored
```
could we keep the PR open until someone fixes those JIRAs?

Can we change the label from `Changes Suggested` to `On Hold`

**Comment by ryanemerson** [comment]
> could we keep the PR open until someone fixes those JIRAs?

We can do, but then the empthasis is on you to rebase and update the PR over time. If the PR is merged you don't need to worry about rebasing and compilation issues as the PR branch and `master` diverge.

**Comment by diegolovison** [comment]
@ryanemerson I have added the `@Ignore` with the respective JIRA.

**Comment by ryanemerson** [comment]
Thanks @diegolovison

**Comment by ryanemerson** [comment]
> This PR will show two issues
> 
> * https://issues.redhat.com/browse/ISPN-12712
> * https://issues.redhat.com/browse/ISPN-12713

I've added a comment to each of the Jiras so it's clear that the tests should no longer be ignored once a fix is ready.

**Pull request merged**
