### PR TITLE
ISPN-11377 Change default flow control back to UFC/MFC

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-11377

Increase max_credits to 4MB to compensate for the queue.

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please

**Comment by diegolovison** [comment]
We will need to fix RadarGun
```
13:25:39,930 ERROR [org.radargun.Slave] (sc-main) Unexpected error in scenario
java.lang.NoSuchMethodError: org.infinispan.configuration.global.GlobalConfiguration.globalJmxStatistics()Lorg/infinispan/configuration/global/GlobalJmxStatisticsConfiguration;
	at org.radargun.service.EmbeddedConfigurationProvider.getNormalizedConfigs(EmbeddedConfigurationProvider.java:27) ~[plugin-infinispan52-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.stages.lifecycle.ServiceStartStage.executeOnSlave(ServiceStartStage.java:92) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.SlaveBase.scenarioLoop(SlaveBase.java:102) ~[radargun-core-3.0.0-SNAPSHOT.jar:?]
	at org.radargun.SlaveBase$ScenarioRunner.run(SlaveBase.java:203) [radargun-core-3.0.0-SNAPSHOT.jar:?]
java.lang.NoSuchMethodError: org.infinispan.configuration.global.GlobalConfiguration.globalJmxStatistics()Lorg/infinispan/configuration/global/GlobalJmxStatisticsConfiguration;
	at org.radargun.service.EmbeddedConfigurationProvider.getNormalizedConfigs(EmbeddedConfigurationProvider.java:27)
	at org.radargun.stages.lifecycle.ServiceStartStage.executeOnSlave(ServiceStartStage.java:92)
	at org.radargun.SlaveBase.scenarioLoop(SlaveBase.java:102)
	at org.radargun.SlaveBase$ScenarioRunner.run(SlaveBase.java:203)
13:25:39,945 INFO  [org.radargun.ShutDownHook] (Thread-0) Slave process is being shutdown
```

**Comment by danberindei** [comment]
I complained about this change to @anistor, but he ignored me :)

@diegolovison it should be enough if you recompile RadarGun, but AFAICT the jmx domain isn't really used, so you could remove the reference to `globalJmxStatistics()`.

**Comment by anistor** [comment]
> I complained about this change to @anistor, but he ignored me :)
> 
> @diegolovison it should be enough if you recompile RadarGun, but AFAICT the jmx domain isn't really used, so you could remove the reference to `globalJmxStatistics()`.
> 
> Update: I was actually worried about something else, I forgot that changing the return type of a method is also not binary compatible.

I did update the code to take into account binary compat of those changes and did the interface vs class adjustements. But this is indeed something else. I'm tempted to not do anything more about it. It's probably better for radargun to just be updated for DG8 anyway sooner or later and avoid using the deprecated config api. Why not do it now?

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
@danberindei I think that the huge improvement comes from another PR.
I am going to run first the from master and then I am going to rerun for this PR.
Hold on

**Comment by danberindei** [comment]
No need to re-run @diegolovison, it's obvious this PR can't influence replicated reads.
I've triggered a run on the backport #7947 (actually 2, because I forgot the default was to run only the embedded benchmark).

**Comment by pruivo** [comment]
integrated! thanks @danberindei

**Pull request merged**
