### PR TITLE
ISPN-8148 Use X-Forwarded-For header as source IP if available

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-8148

### CODE REVIEW

**Comment by tristantarrant** [comment]
Temporarily closing because of CI overload

**Comment by tristantarrant** [comment]
Thanks @johnou, I'll see what I can do.

**Comment by johnou** [comment]
@tristantarrant something like this..

```java
String forwardedFor = request.headers().getAsString(X_FORWARDED_FOR);
String remoteAddr = ctx.channel().remoteAddress().toString();
if (trustedProxyIpMatcher.matches(remoteAddr) && forwardedFor != null) {
    // if there are multiple addresses in the header, return the last in the list which is not trusted address
    if (forwardedFor.contains(",")) {
        String[] forwardedIPs = StringUtils.tokenizeToStringArray(forwardedFor, ",", /* trimTokens */ true, /* ignoreEmptyTokens */ true)
        for (int index = forwardedIPs.length - 1; index >= 0; index--) {
            forwardedFor = forwardedIPs[index];
            if (!trustedProxyIpMatcher.matches(forwardedFor)) {
                break;
            }
        }
    }
    return forwardedFor;
}
```

**Comment by slaskawi** [comment]
I'm having doubts if `X-Forwarded-For` functionality works in current implementation. We don't interpret this header at all, [neither do Netty](https://github.com/netty/netty/search?utf8=%E2%9C%93&q=X-Forwarded-For&type=). So this leads to a question - does it magically work out-of-the-box and if not (that's my assumption), is there any reason for fixing audit logs?

**Comment by tristantarrant** [comment]
The fact that netty doesn't implicitly include the header doesn't matter: it's just a named header.

**Comment by johnou** [comment]
@slaskawi unfortunately that's not the case, it doesn't work out of the box, essentially the application needs to know if the remote peer is trusted eg. a load balancer.

**Comment by tristantarrant** [comment]
If we want to prevent header spoofing, it is not something that should be done within a logger that can be disabled. We should instead add something like ip access control to the HTTP endpoint (like https://access.redhat.com/solutions/18412 )

**Comment by tristantarrant** [comment]
The source IP whitelisting issue https://issues.jboss.org/browse/ISPN-8327

**Comment by tristantarrant** [comment]
I'll reopen this when I have an implementation of ISPN-8327 to go with it.

**Pull request closed without merging**
