### PR TITLE
ISPN-6435 Protect REST delete from throwing error

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.jboss.org/browse/ISPN-6435

### CODE REVIEW

**Comment by vjuranek** [comment]
Mostly white space changes, see https://github.com/infinispan/infinispan/pull/4179/files?w=1

**Comment by slaskawi** [comment]
Looks good to me!

**Comment by slaskawi** [comment]
Pulling

**Comment by slaskawi** [comment]
Integrated into `master` branch. Please create another PR for `8.2.x` if you'd like.

**Pull request closed without merging**
