### PR TITLE
ISPN-13222 Update Netty to 4.1.69.Final

### PR DESCRIPTION
**Pull request by pruivo**
Going through the commit history of `ApplicationProtocolNegotiationHandler` I found the commit [1] added a buffer to the handler. 

Our `ALPNHandler` is marked as `shareable` and my theory is that the "new buffer" does not like it (since the recycle exception is coming from there).

I've changed `ALPNHandler` to be "non-shareable" and removed `SinglePortUpgradeHandler` since the class end up empty :) 

Let's see what CI says :crossed_fingers: 

edit: https://issues.redhat.com/browse/ISPN-13222

[1] https://github.com/netty/netty/commit/750d23583c187b4e8dafdfea3f4fbeaf1d9be7cd

### CODE REVIEW

**Comment by pruivo** [comment]
ps. I'll change the commit message if it works...

**Comment by tristantarrant** [comment]
It looks good @pruivo

**Comment by pruivo** [comment]
rebased and added the following commit message:

    OKHTTP updated to 3.14.9
    
    Netty introduced a message buffer in
    ApplicationProtocolNegotiationHandler and this buffer cannot be used by
    multiple pipelines concurrently.
    
    Changed our ALPNHandler class and removed the Shareable annotation.

**Comment by pruivo** [comment]
and hijacked https://issues.redhat.com/browse/ISPN-13222 :)

**Comment by tristantarrant** [comment]
Thanks @pruivo

**Pull request merged**
