### PR TITLE
[9.4] ISPN-10066 (addendum) ClusteredStatsFailureTest now uses awaitStrict

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-10066

### CODE REVIEW

**Comment by danberindei** [comment]
Probably unrelated, but

```
[ERROR] Test org.infinispan.partitionhandling.ScatteredCrashInSequenceTest.clearContent has been running for more than 300 seconds. Interrupting the test thread and dumping threads of the test suite process and its children.
Dumping thread stacks of process 18161 to /home/infinispan/workspace/Infinispan_PR-6949/core/threaddump-org_infinispan_partitionhandling_ScatteredCrashInSequenceTest_clearContent-2019-05-22-18161.log
```

**Comment by ryanemerson** [comment]
Passed on the 2nd run

**Comment by danberindei** [comment]
https://ci.infinispan.org/job/Infinispan/job/PR-6949/2/ still hanged in `ScatteredCrashInSequenceTest.clearContent`

**Comment by danberindei** [comment]
I had a quick look and the failures are not related, so I integrated it. Thanks Ryan!

**Comment by danberindei** [comment]
The failure was caused by https://issues.jboss.org/browse/ISPN-9291

**Comment by ryanemerson** [comment]
@danberindei Should ISPN-9291 be backported then?

**Pull request merged**
