### PR TITLE
ISPN-6771 HotRod Client - TcpTransportFactory - update topology issue with multiple caches

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-6771

### CODE REVIEW

**Comment by slaskawi** [comment]
Those failures look a bit suspicious to me: http://ci.infinispan.org/viewLog.html?buildId=40651&buildTypeId=bt9&guest=1

Retriggering CI

**Comment by danberindei** [comment]
`ClusterCacheAuth*` tests still failing.

**Comment by gustavonalle** [comment]
Something is broken, will check

**Comment by gustavonalle** [comment]
@danberindei @slaskawi Tests should be fixed now.

**Comment by slaskawi** [comment]
Pulling

**Comment by slaskawi** [comment]
Integrated thanks!

**Pull request closed without merging**
