### PR TITLE
ISPN-10970 Deprecate Infinispan Directory

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.redhat.com/browse/ISPN-10970

### CODE REVIEW

**Comment by anistor** [comment]
LGTM

**Comment by anistor** [comment]
Do we have some package-infos where we could also add the deprecation tag and text @gustavonalle ?

**Comment by gustavonalle** [comment]
let me look

**Comment by anistor** [comment]
I've added the note tp package infos and merged. Thanks @gustavonalle !

**Pull request closed without merging**
