### PR TITLE
[14.0.x]  ISPN-15151 Unable to upgrade if a backup has been restored on the older server

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-15151

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#3](https://ci.infinispan.org/job/Infinispan/job/PR-11267/3/):
```
quay.io/infinispan-test/server:PR-11267
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#4](https://ci.infinispan.org/job/Infinispan/job/PR-11267/4/):
```
quay.io/infinispan-test/server:PR-11267
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#5](https://ci.infinispan.org/job/Infinispan/job/PR-11267/5/):
```
quay.io/infinispan-test/server:PR-11267
```

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
