### PR TITLE
Move multiple top-level classes in a single RemoteCacheManager.java s…

### PR DESCRIPTION
**Pull request by rhusar**
…ource file as static inner classes

Spring cleaning! Looks like an oversight.

### CODE REVIEW

**Comment by danberindei** [comment]
As long as they don't need to be public, top-level seems fine to me...

**Comment by rvansa** [comment]
@danberindei I think that placing multiple top-level classes into one file is a discouraged practice.

**Comment by rhusar** [comment]
@rvansa is right. This practice is called "mess" officially. :-)

**Comment by danberindei** [comment]
@rhusar That's just Jon Skeet, give me a more credible reference :P

**Comment by rhusar** [comment]
@danberindei  ROFL I see you found my sources :)  Anyway, the way I stumbled upon this is that in IntelliJ IDEA (2017.1) double-clicking on the class file does not open the file itself but rather opens another menu listing out the top level classes defined in that file (what a PITA).

**Comment by danberindei** [comment]
@rhusar That sounds annoying indeed... Ok, just make the classes private, and I'll integrate it.

**Comment by rhusar** [comment]
Oops, fixed.

**Comment by danberindei** [comment]
Integrated, thanks Rado!

**Pull request closed without merging**
