### PR TITLE
Ispn 7572 backport

### PR DESCRIPTION
**Pull request by Sanne**
Contains some more backports, necessary to make it all work.

Specifically ISPN-7625  is not applied on master yet, I will do that shortly (not sure if it's needed actually but it's needed here)

 - https://issues.jboss.org/browse/ISPN-7571
 - https://issues.jboss.org/browse/ISPN-7572
 - https://issues.jboss.org/browse/ISPN-7621
 - https://issues.jboss.org/browse/ISPN-7625

### CODE REVIEW

**Comment by gustavonalle** [comment]
CI build was cancelled, I scheduled it again

**Comment by gustavonalle** [comment]
@Sanne Either this PR is hanging the build, or CI is indisposed, can you run the suite in your environment?

**Comment by Sanne** [comment]
yes it "works" fine here.

**Comment by Sanne** [comment]
@gustavonalle did you create a new issue for this one?

**Comment by gustavonalle** [comment]
@Sanne Nope, I fixed the deadlock issue in the 8.2.x build, testing your changes before merging

**Comment by Sanne** [comment]
great! thanks.

Which fix is that for the deadlock?

**Comment by gustavonalle** [comment]
https://github.com/infinispan/infinispan/commit/c693043566643e4b3c74b47c9b88dcdbf96637d4

Btw, I have no idea what CI is doing to test this PR, so I'll run it manually

**Comment by gustavonalle** [comment]
merged, thanks

**Pull request merged**
