### PR TITLE
ISPN-6025 Fix error when deploying project with infinispan-embedded without cache-api

### PR DESCRIPTION
**Pull request by VaclavDedik**
https://issues.jboss.org/browse/ISPN-6025

### CODE REVIEW

**Comment by slaskawi** [comment]
:+1: Looks good to me

**Comment by danberindei** [comment]
Can we test this with an integration test?

**Comment by slaskawi** [comment]
@mgencur @Holmistr - Please correct me if I'm wrong, but we are going to use uber jars with out integration tests soon, right? If I'm correct - we will be testing this and even more after the switch.

**Comment by VaclavDedik** [comment]
Modified the PR a bit to include https://github.com/infinispan/jdg/commit/fa477d4f0a713b554d22f3380f3a0d72d030957d

**Comment by VaclavDedik** [comment]
Can we integrate this PR? This issue causes a bug in JDG 7 (that has been fixed in JDG 6):
https://issues.jboss.org/browse/JDG-6

**Comment by VaclavDedik** [comment]
I have created a ticket in jira for the integration test:
https://issues.jboss.org/browse/ISPN-6223

Going to work on it soon hopefully.

**Comment by tristantarrant** [comment]
Thanks @VaclavDedik , it's in.

**Pull request closed without merging**
