### PR TITLE
Revert ISPN-3391 and go back to jboss-marshalling 1.4.11.Final

### PR DESCRIPTION
**Pull request by danberindei**
jboss-marshalling 2.0.0.Beta3 doesn't work with OSGi.

### CODE REVIEW

**Comment by tristantarrant** [comment]
Actually, if we can have https://github.com/jboss-remoting/jboss-marshalling/pull/53 merged into JBMAR and a new release, we could upgrade to that instead.

**Comment by pferraro** [comment]
@tristantarrant :+1:

**Comment by danberindei** [comment]
@tristantarrant The Karaf tests are still hanging after the rollback, so I'm closing this.

http://ci.infinispan.org/viewLog.html?buildId=49403&buildTypeId=bt9&tab=buildResultsDiv

**Comment by slaskawi** [comment]
@danberindei I believe this PR is still valid. Could you please reopen it?

**Comment by pferraro** [comment]
@slaskawi Downstream projects/products are already using JBM2 with the 8.2.x branch.  I don't think rolling this back on master is a good idea.

**Comment by danberindei** [comment]
@pferraro I didn't realize we released 8.2.6.Final with jboss-marshalling 2.0.0.Beta3, upgrading to a new major version in a micro version (and especially a non-final one) doesn't seem like such a great idea.

But anyway, what's done is done, and I already force-pushed the branch so I can't reopen the PR anyway @slaskawi.

**Comment by slaskawi** [comment]
The thing is that we need OSGi headers in JBoss Marshalling (tracked by [JBMAR-188](https://issues.jboss.org/browse/JBMAR-188) and [JBMAR-190](https://issues.jboss.org/browse/JBMAR-190)). It broke our tests long time ago and it's about time to clean it up.

So whatever you decide has `+1` from me as long as the JBoss Marshalling artifact contains proper OSGi headers.

**Pull request closed without merging**
