### PR TITLE
[JBEAP-10583] : Addition of MANUAL eviction strategy.

### PR DESCRIPTION
**Pull request by panossot**
[JBEAP-10583] : https://issues.jboss.org/browse/JBEAP-10583

Needed for JBEAP-10583. Already included upstream.

### CODE REVIEW

**Comment by wburns** [comment]
There seem to be some changes missing from https://github.com/infinispan/infinispan/commit/8dbbdd13b219ba20ebb2cf553df1fedbb4375e40#diff-18c189868392c9152eadc5172bee6fcf . Specifically the schema updates. @tristantarrant do we also want the log message I assume?

**Comment by galderz** [comment]
@wburns Can we help @panossot fix the missing pieces in the PR?

> @tristantarrant do we also want the log message I assume?

^ What log message?

**Comment by wburns** [comment]
@galderz I was talking about https://github.com/infinispan/infinispan/commit/8dbbdd13b219ba20ebb2cf553df1fedbb4375e40#diff-9b63fc521d77aa81f1b2500dca6f63ffR736

**Comment by wburns** [comment]
Oh thanks @panossot, I didn't realize you had updated this :) I will try to run the suite manually in core at least and then integrate if everything seems okay.

**Comment by wburns** [comment]
Integrated into 8.1.x, thanks @panossot !

**Pull request closed without merging**
