### PR TITLE
ISPN-7366 and ISPN-7369: Trace information + PutMapCommand bug fix.

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.jboss.org/browse/ISPN-7366
https://issues.jboss.org/browse/ISPN-7369

### CODE REVIEW

**Comment by galderz** [comment]
Looking into this... I'll re-run some tests locally first.

**Comment by galderz** [comment]
I can confirm the tests pass :)

**Comment by galderz** [comment]
In the JIRA it says:

> When numOnwer > 2...

But the configuration I'm using in the JS client is numOwners=2...

Anyway, the fix looks good to me, but I'm slightly worried there's no unit tests inside core to replicate this issue? @pruivo can we do something about that?

**Comment by pruivo** [comment]
@galderz I was wrong about "numOwners > 2". 
the ```PutMapCommandNonTxTest``` catches this bug. I don't think it will need a new test.

**Pull request merged**
