### PR TITLE
ISPN-10114 Server managed transactional cache configuration cannot be persisted to global state

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/ISPN-10114

Needs backporting to 9.4.x.

### CODE REVIEW

**Comment by pferraro** [comment]
@tristantarrant Please review.

**Comment by tristantarrant** [comment]
One related failure related to the protobuf cache. @anistor can you check please ?

**Comment by pferraro** [comment]
@anistor Did you have a chance to look at this failure?

**Comment by pferraro** [comment]
@tristantarrant @anistor Has someone had a chance to look into this CI failure?

**Comment by galderz** [comment]
@pferraro Having a look but these failures do not seem related to your PR. You're only touching server integration code and the failures are before any of that comes into play. I'll have a last look and integrate if it all looks good

**Comment by galderz** [comment]
@pferraro 9.4.x PR is #6933

**Pull request merged**
