### PR TITLE
 ISPN-9149 Some TestNG tests do not have any group 

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9149

* Check that all tests have a group and a testName
* Improve the inherited @Factory/factory() checks
* Add missing `@Test` annotations, fix groups and testName where necessary

### CODE REVIEW

**Comment by danberindei** [comment]
@rvansa `FunctionalEncodingTypeTest.testDistReturnViewFromReadWriteEvalOnNonOwner` is always failing. I fixed an obvious mistake (`UserType2Encoder` was setting type 1), but it's still failing because the remote command returns a non-serializable `EntryViews$EntryBackedReadWriteView`.

**Comment by danberindei** [comment]
@galderz `JCacheCreateCachePredefinedTest.testCreateCachePredefinedUntouched` always fails:

https://ci.infinispan.org/job/Infinispan/job/PR-6018/4/testReport/junit/org.infinispan.jcache.remote/JCacheCreateCachePredefinedTest/testCreateCachePredefinedUntouched_remote_/

**Comment by danberindei** [comment]
@tristantarrant `InfinispanRemoteSessionRepositoryTest.testExtractingPrincipal` always fails:

https://ci.infinispan.org/job/Infinispan/job/PR-6018/4/testReport/junit/org.infinispan.spring.session/InfinispanRemoteSessionRepositoryTest/testExtractingPrincipal/

**Comment by tristantarrant** [comment]
@slaskawi can you review my commit here ?

**Comment by danberindei** [comment]
@tristantarrant what kind of magic is this? :)

**Comment by tristantarrant** [comment]
Black sorcery !
But you should really read the little line above the "Review requested" block :)

**Comment by tristantarrant** [comment]
@galderz @danberindei I have disabled testCreateCachePredefinedUntouched and created https://issues.jboss.org/browse/ISPN-9237

**Comment by danberindei** [comment]
@rvansa should I put these in the untable group?

org.infinispan.functional.FunctionalEncodingTypeTest.testDistReturnViewFromReadWriteEvalOnNonOwner[tx=true]
org.infinispan.functional.FunctionalEncodingTypeTest.testDistReturnViewFromReadWriteEvalOnOwner[tx=true]

**Comment by rvansa** [comment]
@danberindei I've fixed the test.

**Comment by danberindei** [comment]
Thanks Radim! I rebased and fixed the conflict if anyone wants to integrate it :)

**Comment by tristantarrant** [comment]
Fired off a new CI build

**Comment by tristantarrant** [comment]
Some tests are not running. master has 26,537 tests, this has 22,680 tests

**Comment by danberindei** [comment]
@tristantarrant yes, `EpollAvailabilityTest` doesn't have any group:

```
org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process

Method public void org.infinispan.client.hotrod.impl.transport.netty.EpollAvailabilityTest.testEpollNotAvailable() throws java.lang.Exception and/or its class don't have any required group.
Required groups are [unstable, stress, unit, functional, profiling, manual, arquillian, xsite]
```

Fortunately the error is very obvious when running tests from the IDE, so it should be pretty hard to write a new test that doesn't have any group after this is integrated.

I added the functional group to `EpollAvailabilityTest`, but now it fails every time on my machine:

```
18:41:30,142 ERROR (testng-Test) [TestSuiteProgress] Test failed: org.infinispan.client.hotrod.impl.transport.netty.EpollAvailabilityTest.testEpollNotAvailable
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_171]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_171]
	at java.util.Collections$SynchronizedList.get(Collections.java:2417) ~[?:1.8.0_171]
	at org.infinispan.commons.test.skip.StringLogAppender.getLog(StringLogAppender.java:67) ~[classes/:?]
	at org.infinispan.client.hotrod.impl.transport.netty.EpollAvailabilityTest.testEpollNotAvailable(EpollAvailabilityTest.java:30) ~[test-classes/:?]
```

**Comment by tristantarrant** [comment]
My local runs and CI disagree with you: 
[INFO] Running org.infinispan.client.hotrod.impl.transport.netty.EpollAvailabilityTest
[OK:     0, KO:     0, SKIP:     0] Test starting: org.infinispan.client.hotrod.impl.transport.netty.EpollAvailabilityTest.testEpollNotAvailable
[OK:     1, KO:     0, SKIP:     0] Test succeeded: org.infinispan.client.hotrod.impl.transport.netty.EpollAvailabilityTest.testEpollNotAvailable
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.642 s - in org.infinispan.client.hotrod.impl.transport.netty.EpollAvailabilityTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

**Comment by danberindei** [comment]
@tristantarrant I found the problem: I was running the test in the IDE with `-Dtest.infinispan.shortTestName=true`, and the `StringLogAppender` filter wanted the thread name to include the test name. I changed the filter to `t == Thread.currentThread()` and now it passes.

**Comment by tristantarrant** [comment]
You should change it to Thread testThread = Thread.currentThread();
      StringLogAppender logAppender = new StringLogAppender(TRANSPORT_HELPER_CLASS,
            Level.TRACE,
            t -> t == testThread,
            PatternLayout.newBuilder().withPattern(LOG_FORMAT).build());

**Comment by tristantarrant** [comment]
Ci reported https://ci.infinispan.org/job/Infinispan/job/PR-6018/20/testReport/org.infinispan.eviction.impl/ExceptionEvictionTest/clearContent/

**Comment by danberindei** [comment]
Fixed the predicate, sorry about that :)

`ExceptionEvictionTest` has been failing randomly for a while, e.g. 

https://ci.infinispan.org/job/Infinispan/job/master/676/#showFailuresLink

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
