### PR TITLE
ISPN-7388 Upgrade to JGroups 4.0.0.CR2

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-7388

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please
library

**Comment by Holmistr** [comment]
run performance tests please
library

**Comment by danberindei** [comment]
run performance tests please
library

**Comment by danberindei** [comment]
run performance tests please
library

**Comment by danberindei** [comment]
run performance tests please
library

**Comment by danberindei** [comment]
run performance tests please
library dist

**Comment by pruivo** [comment]
@danberindei maybe you can remove the ```NO_FC``` and we can integrate the JGroups upgrade :)

**Comment by danberindei** [comment]
@pruivo Sorry, I was supposed to change the version to CR2 and run the tests again... doing that now.

**Comment by danberindei** [comment]
run performance tests please
library

**Comment by tristantarrant** [comment]
No FRAG3?

**Pull request merged**
