### PR TITLE
[8.2] ISPN-3702 Too many threads for cleaning up infinispan transactions

### PR DESCRIPTION
**Pull request by pruivo**
* use timeout executor to cleanup

https://issues.jboss.org/browse/ISPN-3702

### CODE REVIEW

**Comment by tristantarrant** [comment]
30 failures in CI

**Comment by slaskawi** [comment]
Rerunning CI

**Comment by danberindei** [comment]
Integrated, thanks Pedro!

**Comment by baranowb** [comment]
Commit: cc1ed183796f575a79cfbdd886fd1d25c2a06267

**Pull request closed without merging**
