### PR TITLE
ISPN-5103 Inefficient index updates cause high cost merges and increase ...

### PR DESCRIPTION
**Pull request by gustavonalle**
...overall latency

https://issues.jboss.org/browse/ISPN-5103

[DO NOT INTEGRATE YET]
With a single entity, efficient indexing is used since ```isIndexMetadataComplete``` is being enforced
After a new entity type is indexed, the search engine falls back to ```'safe'``` indexing.

Depends on https://hibernate.atlassian.net/browse/HSEARCH-1767

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8262/gustavonalle:ISPN-5103](http://ci.infinispan.org/viewLog.html?buildId=22694&buildTypeId=bt9&guest=1) for acbb818c8ed6bbfa6a3d0286f263ee262bce6432
Tests: 11231, 0 failed (0 new), 23 ignored. Build time: 02:10:05

Error message is logged

Build duration (secs) is too large: 8179

**Comment by gustavonalle** [comment]
PR updated, including the Hibernate Search update that unleashes the performance optimization

**Comment by Sanne** [comment]
looking

**Comment by gustavonalle** [comment]
Updated again

**Comment by Sanne** [comment]
merged!

**Pull request closed without merging**
