### PR TITLE
ISPN-9259 Feature-packs should utilise modules/system/add-ons dir

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-9259

@Sanne @fax4ever FYI after becoming aware of the following [guidelines](https://developer.jboss.org/wiki%20/LayeredDistributionsAndModulePathOrganization) we're moving the wildfly-modules to `modules/system/add-ons/ispn`. Let me know if you know of any issues etc.

### CODE REVIEW

**Comment by alanfx** [comment]
@wfink you should probably look at this too, since it is going to affect patching of the server

**Comment by fax4ever** [comment]
@ryanemerson thank you for concern, there are no problems on our side. It's all about the way wildfly-feature-pack maven plugin find dependent modules, and it will able to found them in both cases. I followed the topic on Zulip, I agree that it is better to avoid to install static modules on default (no package) or base layer.

**Comment by Sanne** [comment]
@alanfx I'm not aware about "patching" capabilities of the feature packs? We use the feature packs to build the (custom) server.

Would love to know more about patching capabilities as we had questions about that on the Hibernate forums.

**Comment by Sanne** [comment]
@ryanemerson I see no problems with the move, however I don't think the guidelines have been updated when we moved to feature packs.

As I asked also to the WildFly team, IMO which "layer" it is going to be written into should be something that the provisioning tool to control - e.g. I might want to take you pack and include it into another custom layer, give it a different name.

**Comment by ryanemerson** [comment]
@Sanne I agree that it would be much nicer if we could control the destination layer as part of the provisioning.

**Comment by alanfx** [comment]
@Sanne the product uses patching for micro releases. I just wanted to make Wolf aware so he can build patches if the modules are moved to the `modules/system/add-ons/ispn` dir.

**Comment by Sanne** [comment]
@alanfx ah, so you just care about the path. Got it, thanks.

**Comment by tristantarrant** [comment]
According to the guidelines, add-ons can be patched in the same ways:
`/modules/system/add-ons/abc/patches/patch-abc-1
/modules/system/add-ons/abc`

**Comment by alanfx** [comment]
Thanks, @tristantarrant! @wfink, hope this works for you.

**Comment by ryanemerson** [comment]
@tristantarrant This PR is good to go. The failures in [build #2](https://ci.infinispan.org/job/Infinispan/job/PR-6040/2/) have happened elsewhere and are not caused by these changes.

**Comment by tristantarrant** [comment]
@ryanemerson can you add a note to the upgrading guide ?

**Comment by ryanemerson** [comment]
@tristantarrant I noticed a slight problem with the dir layout whilst writing the docs, so lets wait for a full CI run before merging.

**Comment by ryanemerson** [comment]
Failures not related

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
