### PR TITLE
ISPN-9289 Ignore TransactionSynchronizationRegistry

### PR DESCRIPTION
**Pull request by pruivo**
* Fix test

### CODE REVIEW

**Comment by rvansa** [comment]
Could you explain what was wrong?

**Comment by pruivo** [comment]
@rvansa you can't use the word `default` in the caches names :)

**Comment by danberindei** [comment]
@pruivo where does that restriction come from?

**Comment by tristantarrant** [comment]
I believe it is a problem with the infinispan arquillian machinery which is matching by prefix

**Comment by pruivo** [comment]
it is caused by https://github.com/infinispan/infinispan-arquillian-container/blob/master/infinispan-impl/src/main/java/org/infinispan/arquillian/utils/MBeanUtils.java#L118
It tries to find all the MBeans with cache's name `default` in its name. That includes the `default` cache name and the transactional caches I did create.

**Pull request merged**
