### PR TITLE
ISPN-8738 InfinispanExtensionIT fails due to xpp3 ModuleLoadException

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-8738

### CODE REVIEW

**Comment by gustavonalle** [comment]
Should fix 
org.infinispan.test.integration.as.InfinispanExtensionIT.testDep1
org.infinispan.test.integration.as.InfinispanExtensionIT.testDep2

**Comment by ryanemerson** [comment]
@gustavonalle LGTM, lets wait on CI

**Comment by gustavonalle** [comment]
Tests fixed

**Comment by ryanemerson** [comment]
Merged, thanks @gustavonalle

**Pull request merged**
