### PR TITLE
ISPN-10194 Store Migrator tests should pass when segmentation is disa…

### PR DESCRIPTION
**Pull request by wburns**
…bled

https://issues.jboss.org/browse/ISPN-10194

### CODE REVIEW

**Comment by tristantarrant** [comment]
Only half of the testsuite was run

**Comment by wburns** [comment]
@tristantarrant sorry, I have been out for a while, I don't understand your comment.

**Comment by tristantarrant** [comment]
https://ci.infinispan.org/job/Infinispan/job/PR-6914/1/testReport/: 11664 tests, but master has > 23000

**Comment by wburns** [comment]
I don't see how the changes here could have changed that though.. it only skips 3 tests when I ran it locally. I can look into it a bit more though.

**Comment by tristantarrant** [comment]
Maybe just trigger a new build

**Comment by wburns** [comment]
> Maybe just trigger a new build

Yeah, just did that. Was looking at log to see if anything stuck out though.

**Comment by wburns** [comment]
It appears the results from the core module aren't included in the report.

**Comment by wburns** [comment]
I also noticed that this error isn't reported either:

19:38:50  19:38:45.782 [ERROR] Failures: 
19:38:50  19:38:45.783 [ERROR]   CollectionRegionAccessStrategyTest>AbstractRegionAccessStrategyTest.testRemoveAll:449->AbstractRegionAccessStrategyTest.evictOrRemoveAllTest:543 expected:<VALUE1/1> but was:<null>
19:38:50  19:38:45.783 [INFO] 
19:38:50  19:38:45.783 [ERROR] Tests run: 874, Failures: 1, Errors: 0, Skipped: 42

**Comment by wburns** [comment]
The core tests weren't reported due to the `org.infinispan.statetransfer.ClusterTopologyManagerTest` test hanging.
<details>
<summary>Log file contents</summary>
<span class="timestamp"><b>14:17:23</b> </span><span style="display: none">[2019-05-14T18:17:23.740Z]</span> [OK: 11599, KO:     0, SKIP:    97] Test starting: org.infinispan.statetransfer.ClusterTopologyManagerTest.testClusterRecoveryWithRebalance[SCATTERED_SYNC, tx=false]
<span class="timestamp"><b>14:17:31</b> </span><span style="display: none">[2019-05-14T18:17:31.803Z]</span> [ERROR] Test org.infinispan.xsite.statetransfer.LocalCacheStateTransferTest.testStateTransferWithClusterIdle has been running for more than 300 seconds. Interrupting the test thread and dumping threads of the test suite process and its children.
<span class="timestamp"><b>14:17:31</b> </span><span style="display: none">[2019-05-14T18:17:31.803Z]</span> Dumping thread stacks of process 28303 to /home/infinispan/workspace/Infinispan_PR-6914/core/threaddump-org_infinispan_xsite_statetransfer_LocalCacheStateTransferTest_testStateTransferWithClusterIdle-2019-05-14-28303.log
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> Interrupted thread testng-LocalCacheStateTransferTest (17).
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> [OK: 11599, KO:     1, SKIP:    97] Test failed: org.infinispan.xsite.statetransfer.LocalCacheStateTransferTest.testStateTransferWithClusterIdle
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> java.lang.AssertionError: expected:&lt;ok&gt; but was:&lt;Unable to pushState to 'NYC'. org.infinispan.remoting.transport.jgroups.SuspectException: ISPN000400: Node null was suspected&gt;
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.infinispan.xsite.statetransfer.LocalCacheStateTransferTest.startStateTransfer(LocalCacheStateTransferTest.java:100)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.infinispan.xsite.statetransfer.LocalCacheStateTransferTest.testStateTransferWithClusterIdle(LocalCacheStateTransferTest.java:54)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.TestRunner.run(TestRunner.java:505)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
<span class="timestamp"><b>14:17:32</b> </span><span style="display: none">[2019-05-14T18:17:32.372Z]</span> 	at java.base/java.lang.Thread.run(Thread.java:834)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> Killed processes 28303
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 18:17:29.255 [INFO] 
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 18:17:29.255 [INFO] Results:
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 18:17:29.255 [INFO] 
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 18:17:29.257 [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 18:17:29.257 [INFO] 
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 18:17:29.262 [ERROR] There are test failures.
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> Please refer to /home/infinispan/workspace/Infinispan_PR-6914/core/target/surefire-reports for the individual test results.
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> Command was /bin/sh -c cd /home/infinispan/workspace/Infinispan_PR-6914/core &amp;&amp; /opt/jdks/jdk-11/bin/java -Xmx1G -XX:+UseG1GC -XX:-TieredCompilation -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/infinispan/workspace/Infinispan_PR-6914 -Djboss.modules.settings.xml.url=<a href='file:///home/infinispan/.m2/settings.xml'>file:///home/infinispan/.m2/settings.xml</a> -Djdk.attach.allowAttachSelf=true -jar /home/infinispan/workspace/Infinispan_PR-6914/core/target/surefire/surefirebooter12745829354541945735.jar /home/infinispan/workspace/Infinispan_PR-6914/core/target/surefire 2019-05-14T18-06-18_803-jvmRun1 surefire6587804489321631918tmp surefire_01219122169267721645tmp
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> Error occurred in starting fork, check output in log
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> Process Exit Code: 143
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> Crashed tests:
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> org.infinispan.statetransfer.ClusterTopologyManagerTest
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> Command was /bin/sh -c cd /home/infinispan/workspace/Infinispan_PR-6914/core &amp;&amp; /opt/jdks/jdk-11/bin/java -Xmx1G -XX:+UseG1GC -XX:-TieredCompilation -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/infinispan/workspace/Infinispan_PR-6914 -Djboss.modules.settings.xml.url=<a href='file:///home/infinispan/.m2/settings.xml'>file:///home/infinispan/.m2/settings.xml</a> -Djdk.attach.allowAttachSelf=true -jar /home/infinispan/workspace/Infinispan_PR-6914/core/target/surefire/surefirebooter12745829354541945735.jar /home/infinispan/workspace/Infinispan_PR-6914/core/target/surefire 2019-05-14T18-06-18_803-jvmRun1 surefire6587804489321631918tmp surefire_01219122169267721645tmp
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> Error occurred in starting fork, check output in log
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> Process Exit Code: 143
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> Crashed tests:
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> org.infinispan.statetransfer.ClusterTopologyManagerTest
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:670)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1161)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1002)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:848)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 
<span class="timestamp"><b>14:17:33</b> </span><span style="display: none">[2019-05-14T18:17:33.558Z]</span> 18:17:29.269 [INFO] 
</details>

**Comment by galderz** [comment]
@wburns This is not the only case, a similar thing is happening in [master#1178](https://ci.infinispan.org/job/Infinispan/job/master/1178/testReport/), where there's a Hibernate failure:

```
[2019-05-20T11:10:00.519Z] 11:09:53.685 [ERROR] Failures: 
[2019-05-20T11:10:00.519Z] 11:09:53.685 [ERROR]   PartialFutureUpdateTest>AbstractPartialUpdateTest.testPartialUpdate:77->AbstractPartialUpdateTest.waitForRemotePut:109
[2019-05-20T11:10:00.519Z] 11:09:53.685 [INFO] 
[2019-05-20T11:10:00.519Z] 11:09:53.685 [ERROR] Tests run: 876, Failures: 1, Errors: 0, Skipped: 42
```

I'll create JIRA for these random failures, and also see why they're not reported...

**Comment by galderz** [comment]
Created [ISPN-10208](https://issues.jboss.org/browse/ISPN-10208) for the missing Hibernate Cache test results. I've created separate jiras for the test errors.

**Comment by galderz** [comment]
As far as this PR is concerned, it's fine.

**Pull request merged**
