### PR TITLE
ISPN-12481 lock-free SyncProcessingQueue

### PR DESCRIPTION
**Pull request by franz1981**
https://issues.redhat.com/browse/ISPN-12481

### CODE REVIEW

**Comment by franz1981** [comment]
Some preliminary numbers

master
```
Benchmark                                  (consumerDelay)  (producerDelay)   Mode  Cnt       Score      Error  Units
SyncProcessingQueueBenchmark.pushAndWait2                0                0  thrpt   16  195281.813 ± 2161.177  ops/s
SyncProcessingQueueBenchmark.pushAndWait2                0               10  thrpt   16  197914.959 ± 2506.130  ops/s
SyncProcessingQueueBenchmark.pushAndWait2                0              100  thrpt   16  187467.698 ± 1885.793  ops/s
SyncProcessingQueueBenchmark.pushAndWait2               10                0  thrpt   16  197724.733 ± 3139.547  ops/s
SyncProcessingQueueBenchmark.pushAndWait2               10               10  thrpt   16  197446.585 ± 3106.995  ops/s
SyncProcessingQueueBenchmark.pushAndWait2               10              100  thrpt   16  189787.057 ± 3239.134  ops/s
SyncProcessingQueueBenchmark.pushAndWait2              100                0  thrpt   16  193570.843 ± 2456.758  ops/s
SyncProcessingQueueBenchmark.pushAndWait2              100               10  thrpt   16  189653.444 ± 2551.090  ops/s
SyncProcessingQueueBenchmark.pushAndWait2              100              100  thrpt   16  183585.022 ± 4243.454  ops/s
```
This pr:
```
Benchmark                                  (consumerDelay)  (producerDelay)   Mode  Cnt        Score        Error  Units
SyncProcessingQueueBenchmark.pushAndWait2                0                0  thrpt   16  1995885.544 ±  55103.406  ops/s
SyncProcessingQueueBenchmark.pushAndWait2                0               10  thrpt   16  2104246.160 ±  77654.840  ops/s
SyncProcessingQueueBenchmark.pushAndWait2                0              100  thrpt   16  2041778.864 ± 190395.636  ops/s
SyncProcessingQueueBenchmark.pushAndWait2               10                0  thrpt   16  2046269.439 ±  60839.916  ops/s
SyncProcessingQueueBenchmark.pushAndWait2               10               10  thrpt   16  1969678.808 ±  39858.488  ops/s
SyncProcessingQueueBenchmark.pushAndWait2               10              100  thrpt   16  1945230.866 ± 228512.231  ops/s
SyncProcessingQueueBenchmark.pushAndWait2              100                0  thrpt   16  1397323.381 ±  19609.587  ops/s
SyncProcessingQueueBenchmark.pushAndWait2              100               10  thrpt   16  1372057.392 ±  27760.970  ops/s
SyncProcessingQueueBenchmark.pushAndWait2              100              100  thrpt   16  1060660.459 ± 241542.295  ops/s
```
Would be interesting to see how this queue behave with a proper super fast pmem disk instead, but I don't have any ;)

The main difference with the original queue is that this one is a bit more memory hungry (but we can blame RxJava mpsc linked q for that, https://github.com/JCTools/JCTools has few gc-free alternatives nudge nudge), but I'm sure this could be improve if necessary.

**Comment by ryanemerson** [comment]
> Would be interesting to see how this queue behave with a proper super fast pmem disk instead, but I don't have any ;)

@jhalliday Might be able to help!

**Comment by franz1981** [comment]
Thanks @ryanemerson I have already spoken with @jhalliday about it but I don't know if we would have any chance to try this on a real hw, @jhalliday wdyt? It's feasible to have a round of bench with this in?

**Comment by danberindei** [comment]
@franz1981 I still haven't managed to delve into this yet, but I have a question.

We also use a `SynchronousQueue` for executors, e.g. in JGroups' [TP.init()](https://github.com/belaban/JGroups/blob/master/src/org/jgroups/protocols/TP.java#L983) and for our expiration executor (the only one that still has 0 queue length). Should we look into changing all of them to a better queue impl?

**Comment by franz1981** [comment]
@danberindei consider that this queue isn't a full fat blocking queue as synchronous queue nor allow (yet) to fire and and forget tasks as a thread pool impl need.
In general I would say "yes" about having better queue impls (disclaimer: I am one of the devs of https://github.com/JCTools/JCTools) especially if used on AOT given that bad reputation of the jdk ones related to garbage produced.
In term of pure performance, it means of the underlying tasks is expensive in term of time or not, because it means that enqueue/dequeue time start to became a factor.

**Comment by wburns** [comment]
Integrated into master, thanks @franz1981 !

**Comment by franz1981** [comment]
Thanks @wburns !
@jhalliday 
Let me know if you got any chance to test it with both a slow and super fast storage so I can provide some sane default (or adaptive, even better) for spin/yield configurations.
On user code instead I believe batching writes before fdatasync/fsynx is a must-have with FileChannels (while pmem won't benefit from it) and should give a nice boost amortizing both syscall pwrite/write and sync cost.

**Pull request merged**
