### PR TITLE
ISPN-11318 Netty 4.1.45.Final

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-11318

### CODE REVIEW

**Comment by tristantarrant** [comment]
org.infinispan.rest.Http2Test.shouldUseHTTP1WithALPN is related

**Comment by pruivo** [comment]
is the test fixed magically? I don't see any new changes :/

**Comment by tristantarrant** [comment]
I relaunched a build. It was a temporary timeout failure.

**Comment by pruivo** [comment]
integrated! thanks @tristantarrant !

**Pull request merged**
