### PR TITLE
[9.1.x] Encoding backport

### PR DESCRIPTION
**Pull request by gustavonalle**
Backport of encoding related issues from master

https://issues.jboss.org/browse/ISPN-8004
https://issues.jboss.org/browse/ISPN-8349
https://issues.jboss.org/browse/ISPN-8350
https://issues.jboss.org/browse/ISPN-8368

### CODE REVIEW

**Comment by gustavonalle** [comment]
The failures are not related (elastic search failure happened on master), triggering another build

**Comment by anistor** [comment]
Could you rebase this please? Btw, CI crashed again.

**Comment by gustavonalle** [comment]
rebased

**Comment by gustavonalle** [comment]
Build is fine apparently, it crashed in the osgi fork:
```Unable to load category: stress```
Is this something fixed on master @danberindei ?

**Comment by danberindei** [comment]
@gustavonalle yes, Tristan fixed it on master with https://github.com/infinispan/infinispan/pull/5472/files, cherry-picking to 9.1.x

**Comment by danberindei** [comment]
@gustavonalle please rebase

**Comment by gustavonalle** [comment]
@danberindei there's nothing to rebase

**Comment by danberindei** [comment]
@anistor actually since all the other modules seem fine I think it can be integrated as is, unless you have more comments.

**Comment by anistor** [comment]
This is merged in 9.1.x. Thanks @gustavonalle and @danberindei !

**Comment by gustavonalle** [comment]
@anistor Is it integrated? Can't see the commits https://github.com/infinispan/infinispan/commits/9.1.x

**Comment by anistor** [comment]
I think I forgot to push it :) It's in now!

**Pull request closed without merging**
