### PR TITLE
ISPN-5246 Re-enable the queue for the JGroups internal thread pool in th...

### PR DESCRIPTION
**Pull request by danberindei**
...e default configuration

https://issues.jboss.org/browse/ISPN-5246

### CODE REVIEW

**Comment by galderz** [comment]
As @rvansa pointed out in the JIRA, can you explain why you're doing this?

**Comment by danberindei** [comment]
@galderz I've added a comment in JIRA.

**Comment by galderz** [comment]
Ok, thanks for the explanation :)

**Comment by galderz** [comment]
Integrated

**Pull request closed without merging**
