### PR TITLE
[11.0.x] ISPN-15239 HotRod client repeatedly retries iteration operation against failed server after removal from topology

### PR DESCRIPTION
**Pull request by gaol**
Issue: https://issues.redhat.com/browse/ISPN-15239

This is a backport of : https://github.com/infinispan/infinispan/pull/11422 to `11.0.x` branch for EAP 7.4.z

### CODE REVIEW

**Comment by gaol** [comment]
this is a backport to 11.0.x branch, @pferraro @jabolina may I ask any of you to review ?

**Comment by jabolina** [comment]
Thanks for opening it. It seems the new test is failing. I'll check if it needs something more.

**Comment by jabolina** [comment]
Added a new commit with the fixes. There are just some changes on the test side.

**Comment by gaol** [comment]
The UnifiedXmlFileParsingTest test failures may have something to do with https://github.com/infinispan/infinispan/pull/11325, which specified a fixed thread group name instead of using the `threadGroupName` argument.

**Review by jabolina — APPROVED** [review]

**Comment by jabolina** [comment]
Thanks, @gaol! Integrated into 11.0.x.

**Comment by gaol** [comment]
@jabolina Impeccable timing ! Thanks :smile:

**Pull request merged**
