### PR TITLE
ISPN-9426 Distributed script execution returning null results in Null…

### PR DESCRIPTION
**Pull request by gustavonalle**
…PointerException

https://issues.jboss.org/browse/ISPN-9426

### CODE REVIEW

**Comment by gustavonalle** [comment]
The script output is dictated by the media type set in the header when executing it. So differentiating between ```null``` and ```""``` seems more correct when the script output is a textual format. It'd allow to differentiate between:
* non existent values  ```null```, e.g. ```cache.get('inexistent-key')```
* empty strings  ```""```, e.g. ```cache.get('key-with-empty-value')```
* null string ```"null"```, e.g.  ```cache.get('key-with-string-value')```

**Comment by gustavonalle** [comment]
Also, in JSON terms,  both ```["",""]```  and ```[null, null]``` are valid and mean different things

**Comment by gustavonalle** [comment]
For java clients running scripts without any particular result format specified (the default), we currently erroneously map ```null``` to ```""```, this should be fixed in another JIRA

**Comment by galderz** [comment]
> Also, in JSON terms, both ["",""] and [null, null] are valid and mean different things

I'm fine with both, but looking at the code, aren't you returning `["null", "null"]` ?

**Comment by galderz** [comment]
https://github.com/infinispan/infinispan/pull/6215/files#diff-d030c6ace7871c24c274b7ae3728e904R72

**Comment by gustavonalle** [comment]
It is returning ```[null,null]``` (without quotes):  https://github.com/infinispan/infinispan/pull/6215/files#diff-c94e51670c5b2358c05a2ac4c4406e4fR115

**Comment by galderz** [comment]
@gustavonalle Worked fine, thanks!

**Pull request merged**
