### PR TITLE
ISPN-16129 Periodic failures on Backup Restore

### PR DESCRIPTION
**Pull request by jabolina**
https://issues.redhat.com/browse/ISPN-16129

### CODE REVIEW

**Comment by jabolina** [comment]
Yes, it is just for debugging atm. I'll check the log files next.

**Comment by jabolina** [comment]
A stack trace I haven't seen before:

```java
19:51:26,899 INFO  (main) [org.jgroups.protocols.FD_SOCK2] server listening on *.57800
java.lang.NullPointerException: Cannot invoke "org.jgroups.stack.IpAddress.getIpAddress()" because "pa" is null
	at org.jgroups.protocols.FD_SOCK2.getPhysicalAddresses(FD_SOCK2.java:445)
	at org.jgroups.protocols.FD_SOCK2.connectTo(FD_SOCK2.java:395)
	at org.jgroups.protocols.FD_SOCK2.connectToNextPingDest(FD_SOCK2.java:376)
	at org.jgroups.protocols.FD_SOCK2.handle(FD_SOCK2.java:347)
	at org.jgroups.protocols.FD_SOCK2.handle(FD_SOCK2.java:31)
	at org.jgroups.util.ProcessingQueue.process(ProcessingQueue.java:55)
	at org.jgroups.util.ProcessingQueue.add(ProcessingQueue.java:35)
	at org.jgroups.protocols.FD_SOCK2.handleView(FD_SOCK2.java:364)
	at org.jgroups.protocols.FD_SOCK2.down(FD_SOCK2.java:227)
	at org.jgroups.protocols.FailureDetection.down(FailureDetection.java:149)
	at org.jgroups.protocols.VERIFY_SUSPECT2.down(VERIFY_SUSPECT2.java:84)
	at org.jgroups.protocols.pbcast.NAKACK2.down(NAKACK2.java:619)
	at org.jgroups.protocols.UNICAST3.down(UNICAST3.java:611)
	at org.jgroups.protocols.pbcast.STABLE.down(STABLE.java:260)
	at org.jgroups.protocols.pbcast.GMS.installView(GMS.java:676)
	at org.jgroups.protocols.pbcast.ClientGmsImpl.installView(ClientGmsImpl.java:212)
	at org.jgroups.protocols.pbcast.ClientGmsImpl.installViewIfValidJoinRsp(ClientGmsImpl.java:152)
	at org.jgroups.protocols.pbcast.ClientGmsImpl.joinInternal(ClientGmsImpl.java:107)
	at org.jgroups.protocols.pbcast.ClientGmsImpl.join(ClientGmsImpl.java:37)
	at org.jgroups.protocols.pbcast.GMS.down(GMS.java:897)
	at org.jgroups.protocols.FlowControl.down(FlowControl.java:201)
	at org.jgroups.protocols.FlowControl.down(FlowControl.java:201)
	at org.jgroups.stack.Protocol.down(Protocol.java:283)
	at org.jgroups.protocols.FRAG2.down(FRAG2.java:102)
	at org.jgroups.stack.ProtocolStack.down(ProtocolStack.java:929)
	at org.jgroups.JChannel.down(JChannel.java:608)
	at org.jgroups.JChannel._connect(JChannel.java:808)
	at org.jgroups.JChannel.connect(JChannel.java:325)
	at org.jgroups.JChannel.connect(JChannel.java:316)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.startJGroupsChannelIfNeeded(JGroupsTransport.java:621)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:490)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
	at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
	at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:78)
	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
	at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:616)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:607)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:576)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:379)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:252)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:775)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:743)
	at org.infinispan.server.SecurityActions.lambda$startCacheManager$1(SecurityActions.java:68)
	at org.infinispan.security.Security.doPrivileged(Security.java:56)
	at org.infinispan.server.SecurityActions.doPrivileged(SecurityActions.java:40)
	at org.infinispan.server.SecurityActions.startCacheManager(SecurityActions.java:71)
	at org.infinispan.server.Server.run(Server.java:408)
	at org.infinispan.server.Bootstrap.runInternal(Bootstrap.java:173)
	at org.infinispan.server.tool.Main.run(Main.java:98)
	at org.infinispan.server.Bootstrap.main(Bootstrap.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.infinispan.server.loader.Loader.run(Loader.java:106)
	at org.infinispan.server.loader.Loader.main(Loader.java:51)
```

**Comment by tristantarrant** [comment]
@belaban when can the error above happen ?

**Comment by jabolina** [comment]
I can run the GH actions on my fork. I'll close this one

**Pull request closed without merging**
