### PR TITLE
REST corrections

### PR DESCRIPTION
**Pull request by karesti**
Eviction instead of expiration: https://issues.jboss.org/browse/ISPN-10897
Detail cache: https://issues.jboss.org/browse/ISPN-10971
Display indexing in progress: https://issues.jboss.org/browse/ISPN-10884
Caches are retrieved in order: https://issues.jboss.org/browse/ISPN-10972

### CODE REVIEW

**Comment by karesti** [comment]
4 simple corrections, 4 JIRAs

**Comment by gustavonalle** [comment]
@karesti Compilation errors!

**Comment by karesti** [comment]
@gustavonalle fixed

**Comment by gustavonalle** [comment]
Merged, thanks @karesti !

**Pull request merged**
