### PR TITLE
ISPN-9415 HotRod Client takes 60 seconds for each operation after a split

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9415

* Send a complete topology to the client when degraded
* Enhance HotRodMergeTest to test with DENY_READ_WRITES
* Add lots of toString() methods for debugging

### CODE REVIEW

**Comment by danberindei** [comment]
Ok, I did work a little bit today, because HotRodMergeTest was using the same port as some other test and I didn't understand why... turns out I had forgotten ALLOW_READ_WRITES has ordinal 2, and the 2nd server had exactly the same port number as the next thread's first server. That's it from me this week :)

**Comment by tristantarrant** [comment]
Ci failures:
    org.infinispan.server.hotrod.HotRodMergeTest.testNewTopologySentAfterOverlappingMerge[DIST_SYNC, ALLOW_READ_WRITES]
    org.infinispan.server.hotrod.HotRodMergeTest.testNewTopologySentAfterCleanMerge[DIST_SYNC, ALLOW_READ_WRITES]
    org.infinispan.server.hotrod.HotRodMergeTest.testNewTopologySentAfterOverlappingMerge[DIST_SYNC, DENY_READ_WRITES]
    org.infinispan.server.hotrod.HotRodMergeTest.testNewTopologySentAfterCleanMerge[DIST_SYNC, DENY_READ_WRITES]

**Comment by danberindei** [comment]
`HotRodMergeTest` didn't fail in the last build, but when I run the test suite locally I do see some test failures (almost always including AuthenticationTest, which also fails on master for me) that seem to be caused by the client not receiving the last message from the server before the server closes the connection.

```
17:25:42,733 TRACE (testng-Test:[]) [Codec21] [] Wrote header for messageId=73548 to PooledUnsafeDirectByteBuf(ridx: 0, widx: 14, cap: 24). Operation code: 0x01(PUT_REQUEST). Flags: 0x6. Topology id: -1
17:25:42,733 TRACE (testng-Test:[]) [ChannelFactory] Releasing channel [id: 0x10d49ca2, L:/127.0.0.1:35480 - R:127.0.0.1/127.0.0.1:12631]
17:25:45,737 ERROR (testng-Test:[]) [TestSuiteProgress] Test failed: org.infinispan.client.hotrod.AuthenticationTest.testAuthenticationFailNoAuth
org.infinispan.client.hotrod.exceptions.TransportException: java.net.SocketTimeoutException: PutOperation{(default), key=[B0x033E0161, value=[B0x033E0161, flags=6} timed out after 3000 ms
```

So maybe hold this a bit until we find more about the failures...

**Comment by tristantarrant** [comment]
Merged. Thanks

**Pull request merged**
