### PR TITLE
ISPN-10451 & ISPN-10452 Remove AsElementAttributeSerializer/JDBC store serialization fixes

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-10451
https://issues.jboss.org/browse/ISPN-10452

### CODE REVIEW

**Comment by tristantarrant** [comment]
Half of the testsuite didn't run. Can you look at it ?

**Comment by gustavonalle** [comment]
Where can I see it? Shouldn't CI be red?

**Comment by gustavonalle** [comment]
Weird, I can only see
```
08:09:55  Killed processes 23001
```

While running the core tests...

**Comment by gustavonalle** [comment]
Retriggering...

**Comment by gustavonalle** [comment]
The last run went "fine", with 20k+ test. The previous one had lots of failures: crashed on core, server-ng, jcache...Yet the status was green. Is this a known issue on CI?

**Pull request merged**
