### PR TITLE
ISPN-14401 Protostream 4.6.0.Final

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14401

### CODE REVIEW

**Comment by pruivo** [comment]
@tristantarrant there are a lot of failures in IT tests: `java.lang.NoSuchMethodError: 'java.lang.Class javassist.CtClass.toClass(java.lang.Class)'` and `java.lang.NoClassDefFoundError: com/squareup/protoparser/ProtoParser`

**Comment by tristantarrant** [comment]
Yeah, I've pushed some changes

**Comment by tristantarrant** [comment]
I wasn't able to reproduce this locally, but then I noticed that the tests don't run at all with JDK 17...

**Comment by pruivo** [comment]
merged! thanks @tristantarrant !

**Pull request merged**
