### PR TITLE
ISPN-9500 ConcurrentSmallIntSet.clear() does not always set size to 0

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9500

Fix the handling of negative values in clear() and several other
methods:
* toIntArray()
* forEach(IntConsumer)
* removeIf(IntPredicate)

### CODE REVIEW

**Comment by wburns** [comment]
Good catch, not sure why I didn't think of this when working on it. I even used unsigned bit shift in a few other places. May have been one of those things where you implement something one way and then mess it up when changing it to another way. Anyways, nice! 👍

**Comment by wburns** [comment]
Also this should be cherry-picked to 9.3.x, which should be conflict free. Putting as a reminder.

**Comment by danberindei** [comment]
Thanks for remembering 9.3.x :)

**Comment by tristantarrant** [comment]
CI is green

**Comment by wburns** [comment]
Integrated into master, thanks @danberindei !

**Comment by wburns** [comment]
Also cherry-picked to 9.3.x

**Pull request merged**
