### PR TITLE
[14.0] ISPN-15368 Prevent repetitive ThreadGroup creation

### PR DESCRIPTION
**Pull request by TomasHofman**
https://issues.redhat.com/browse/ISPN-15368
Upstream PR: https://github.com/infinispan/infinispan/pull/11553

This is a follow-up PR to https://github.com/infinispan/infinispan/pull/11277 handling couple more places where ThreadGroups leak.

### CODE REVIEW

**Comment by TomasHofman** [comment]
I will open the main one a moment.

**Comment by TomasHofman** [comment]
Upstream PR is https://github.com/infinispan/infinispan/pull/11553

**Comment by TomasHofman** [comment]
I'm not sure about the "continuous-integration" job, it fails on the "Archive JUnit" step, without giving information why. How do I find if any tests failed and which?

**Comment by wburns** [comment]
Integrated into 14.0.x, thanks @TomasHofman !

**Pull request merged**
