### PR TITLE
ISPN-8895 TestResourceTracker integrated with Spring's TestExecutionL…

### PR DESCRIPTION
**Pull request by tristantarrant**
…istener

https://issues.jboss.org/browse/ISPN-8895

Fixes two tests:
org.infinispan.spring.support.embedded.InfinispanDefaultCacheFactoryBeanContextTest.springTestContextPrepareTestInstance
org.infinispan.spring.provider.sample.SampleRemoteCacheTest.springTestContextPrepareTestInstance

### CODE REVIEW

**Comment by danberindei** [comment]
@tristantarrant what's the difference between the two approaches?

**Comment by tristantarrant** [comment]
Patched another test in the meantime.
When using the spring context tests, it initializes the spring context in the superclass's BeforeClass, thus causing the TestResourceTracker to barf with test name not set. Using a Spring TestExecutionListener, be bind into their lifecycle.

**Comment by danberindei** [comment]
I see, so I broke it when I changed `@BeforeTest` to `@BeforeClass` with ISPN-8850. Could you add this as a comment in `InfinispanTestExecutionListener` as well?

**Comment by tristantarrant** [comment]
Yep. Added a comment.

**Comment by danberindei** [comment]
Integrated, thanks Tristan!

**Pull request merged**
