### PR TITLE
ISPN-9329 Fix NPE during cache start due to circular component dependencies

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/ISPN-9329

### CODE REVIEW

**Comment by danberindei** [comment]
@pferraro I was chatting with @wburns about this, I think the dependency cycle should be broken in `GroupManagerImpl`. Will volunteered to make the change, but feel free to update your PR instead ;)

**Comment by pferraro** [comment]
@danberindei I'll just update this PR.

**Comment by wburns** [comment]
I should have a PR here in a few minutes, so many distractions this morning :)

**Comment by pferraro** [comment]
@wburns OK - will let you handle it. :)

**Pull request closed without merging**
