### PR TITLE
[9.3.x] ISPN-10029 Invalidation locking is not clustered 

### PR DESCRIPTION
**Pull request by danberindei**
Backport of #6887

### CODE REVIEW

**Comment by ryanemerson** [comment]
@danberindei @tristantarrant CI is failing because there is no JDK 10 anymore. `ERROR: No tool named JDK 10 found`. Do we just build `9.3.x` for JDK8? Or Upgrade to 11.

**Comment by tristantarrant** [comment]
I'll do it the easy way: create a "JDK 10" on Jenkins which points to 11 :)

**Comment by tristantarrant** [comment]
It's building now

**Comment by danberindei** [comment]
Thanks Tristan!

**Comment by alanfx** [comment]
@tristantarrant just don't let this hack bite you in the ass at some point in the future!

**Comment by danberindei** [comment]
I think the build looks good @tristantarrant

**Comment by tristantarrant** [comment]
@alanfx well, JDK 10 is EOL anyway :)

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by alanfx** [comment]
True enough, @tristantarrant!

**Pull request merged**
