### PR TITLE
ISPN-5934 ContinuousQuery must benefit from DSL based filter indexing

### PR DESCRIPTION
**Pull request by anistor**
This PR depends on https://github.com/infinispan/infinispan/pull/3832 to be integrated first.

jira: https://issues.jboss.org/browse/ISPN-5934
     https://issues.jboss.org/browse/ISPN-5985

### CODE REVIEW

**Comment by tristantarrant** [comment]
Pushed, thanks

**Comment by gustavonalle** [comment]
It seems this PR had 36 failures on OSGI, integration was too aggressive  :smile:

**Comment by anistor** [comment]
The PR was perfectly fine before the hibernate-search/core upgrade :)

**Comment by anistor** [comment]
And the search upgrade was not fine at all. I could never get a clean build: http://ci.infinispan.org/viewLog.html?buildId=32568&tab=buildResultsDiv&buildTypeId=bt9

**Comment by tristantarrant** [comment]
That was a resolution problem with certain artifacts. I've cleared the agent maven repos to solve that

**Pull request closed without merging**
