### PR TITLE
ISPN-6526 Transaction doesn't rollback on throwable

### PR DESCRIPTION
**Pull request by d0k1**
https://issues.jboss.org/browse/ISPN-6526

### CODE REVIEW

**Comment by slaskawi** [comment]
Hey @d0k1! Could you tell me when and how did you encounter for this problem? And of course what `Throwable` got through this try/catch statement?

**Comment by d0k1** [comment]
Hi @slaskawi, thanks for reply.
So, about my problem. Sometimes thread can get a `java.lang.ThreadDeath` or `java.lang.OutOfMemoryError`. And once upon a time, one thread got such throwable and left object in cache locked until JVM was restarted. So, I thought it might be not bad to handle such case. 
I suppose when IS rollbacks current tx, it would release any lock it holds. Is that correct?

**Comment by slaskawi** [comment]
@d0k1 That makes sense to me. Let's also ask @pruivo for opinion.

**Comment by pruivo** [comment]
@slaskawi looks good to me.
@d0k1 do you mind to open a JIRA (https://issues.jboss.org/secure/Dashboard.jspa) and update the commit message?

**Comment by d0k1** [comment]
@pruivo I've made an JIRA issue (https://issues.jboss.org/browse/ISPN-6526), modified commit message, made a rebase. And modified commit's code a little, to get it more readable (just import `java.lang.Throwable`).
Is there anything else to do?

**Comment by slaskawi** [comment]
Pulling

**Comment by slaskawi** [comment]
Integrated thanks!

**Pull request closed without merging**
