### PR TITLE
ISPN-15043 REST/CLI describe role

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-15043

### CODE REVIEW

**Comment by ryanemerson** [comment]
The REST API docs need updating to include the new endpoints.

**Comment by tristantarrant** [comment]
Added docs

**Comment by tristantarrant** [comment]
@ryanemerson I've changed the test to only attempt role manipulation when possible

**Comment by tristantarrant** [comment]
@ryanemerson fixed issues

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
