### PR TITLE
[9.4] ISPN-9373 Upgrade testng to 6.14.3

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-9373

### CODE REVIEW

**Comment by tristantarrant** [comment]
@diegolovison I created a backport. Let's wait for CI

**Comment by danberindei** [comment]
@tristantarrant please cherry-pick https://github.com/infinispan/infinispan/pull/6733 and rebase for the scripting fix

**Comment by tristantarrant** [comment]
Done @danberindei

**Comment by danberindei** [comment]
Integrated, thanks Tristan!

**Pull request merged**
