### PR TITLE
[13.0] ISPN-14135 Protostream 4.4.4.Final

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14135

### CODE REVIEW

**Comment by ryanemerson** [comment]
There's a lot of security related test failures on the 3 runs.

**Comment by tristantarrant** [comment]
I only see 1 run with a known security-related bug (which is totally unrelated)

**Comment by ryanemerson** [comment]
Sorry I commented on the wrong PR, I must have had too many tabs open!

Here's the correct one: https://github.com/infinispan/infinispan/pull/10322#issuecomment-1250722891

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
