### PR TITLE
ISPN-7484 Upgrade to Apache Lucene 5.5.4

### PR DESCRIPTION
**Pull request by Sanne**
https://issues.jboss.org/browse/ISPN-7484

### CODE REVIEW

**Comment by tristantarrant** [comment]
org.infinispan.test.integration.as (1)
query.ElasticsearchIndexManagerIT  	
java.lang.AssertionError: Version must be upgraded to [5.5.4] is still set to [5.5.2]
    at org.elasticsearch.Version.<clinit>(Version.java:316)
    at org.infinispan.query.test.elasticsearch.ElasticSearchCluster$TestNode.<init>(ElasticSearchCluster.java:59)
    at org.infinispan.query.test.elasticsearch.ElasticSearchCluster$ElasticSearchClusterBuilder.buildNode(ElasticSearchCluster.java:123)
    at org.infinispan.query.test.elasticsearch.ElasticSearchCluster$ElasticSearchClusterBuilder$$Lambda$37/1073051173.apply(Unknown Source)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
    at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
    at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at org.infinispan.query.test.elasticsearch.ElasticSearchCluster$ElasticSearchClusterBuilder.build(ElasticSearchCluster.java:127)
    at org.infinispan.test.integration.as.query.ElasticsearchIndexManagerIT.startElastic(ElasticsearchIndexManagerIT.java:68)

**Comment by gustavonalle** [comment]
As we discussed previously, the Lucene version should follow the Hibernate Search version on Infinispan, so it should not be upgraded independently, so it should stay in ```5.5.2```

WRT the Elasticsearch issue, it needed to be adressed separately https://issues.jboss.org/browse/ISPN-7506

**Comment by gustavonalle** [comment]
Ok, I missed the other PR for Search which is ```5.5.4``` compliant, let me sort out the elasticsearch issue then...

**Comment by Sanne** [comment]
> As we discussed previously, the Lucene version should follow the Hibernate Search version on Infinispan, so it should not be upgraded independently, so it should stay in 5.5.2

Does that apply for micro versions as well? 5.5.4 just contains micro bugfixes, they should be fully interchangeable.

The big thing is 5.5.4 backported the Java 9 compatibility fixes.

**Comment by Sanne** [comment]
BTW 5.5.3 had no changes at all, as it was released only for Solr bugfixing, so the changes are really minimal.

**Comment by gustavonalle** [comment]
@Sanne In theory, micro version should not cause issues, but in practice chances are the user will endup with 2 lucene versions in the classpath. If we consider the modules, not sure what it could happen: maybe there'd mixed versions under the 5.5 slot. So it's better to keep them aligned for piece of mind :)

**Comment by Sanne** [comment]
+1 to try to keep them aligned, but bear in mind that our Lucene module slot name intentionally uses _major.minor_ pattern (no micro), so we have a bit of flexibility.

**Comment by Sanne** [comment]
I've rebased and added a commit to upgrade Elasticsearch.

It still needs a test tools refactoring from @gustavonalle first, as the new ES version still uses the older Lucene version as well.

**Comment by gustavonalle** [comment]
Closing, the Lucene upgrade is Included in #4882

**Pull request closed without merging**
