### PR TITLE
ISPN-6911 Add MANUAL eviction strategy

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-6911

### CODE REVIEW

**Comment by tristantarrant** [comment]
@rhusar see if this works for your purposes

**Comment by rvansa** [comment]
Almost sounds like manual eviction with NONE set as strategy should emit a warning, to have the behviour symmetric.

**Comment by rhusar** [comment]
@tristantarrant thanks Tristan, this indeed does solve the problem. 

Although feels like an overkill to introduce a new strategy only equivalent to NONE just to suppress a warning, yet I don't have other elegant solution (apart from adding another attribute and doing something along the lines EvictionConfigurationBuilder#supressPassivationWithoutEvictionWarningMessage(true));)

**Comment by tristantarrant** [comment]
@rvansa I've added a warning for this now

**Comment by galderz** [comment]
Looks good, integrating

**Comment by galderz** [comment]
Integrated, thx @tristantarrant

**Pull request closed without merging**
