### PR TITLE
ISPN-11795 Entity mapping deprecations

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.redhat.com/browse/ISPN-11795

### CODE REVIEW

**Comment by gustavonalle** [comment]
The tests didn't like that I removed the field uninverting, I will have to sort out the tests :)

**Comment by gustavonalle** [comment]
@anistor this should be good to go, any comments?

**Comment by anistor** [comment]
LGTM. we'll sort the sorting later :)

**Comment by anistor** [comment]
Merged. Thanks @gustavonalle !

**Pull request merged**
