### PR TITLE
ISPN-11172 Remap container uid/gid to fix permissions with mounted vo…

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-11172

### CODE REVIEW

**Comment by tristantarrant** [comment]
This reverts the change in https://github.com/infinispan/infinispan/pull/7684

**Comment by tristantarrant** [comment]
Failures are unrelated

**Comment by tristantarrant** [comment]
This will need to be backported

**Comment by danberindei** [comment]
Merged in master and 10.1.x, thanks Tristan!

**Pull request merged**
