### PR TITLE
ISPN-11909 Better error reporting when querying a cache with non-quer…

### PR DESCRIPTION
**Pull request by wburns**
…yable storage

* Fix test thread leak

https://issues.redhat.com/browse/ISPN-11909

### CODE REVIEW

**Comment by gustavonalle** [comment]
Wy there are test failures with ThreadLeaks?

**Comment by danberindei** [comment]
@wburns @gustavonalle I hijacked the PR to use the `SingleHotRodServerTest` extension methods.

The leak is because the test was creating a HotRodServer instance and not stopping it, if I understood your question correctly.

**Comment by gustavonalle** [comment]
@danberindei Got it, I was wondering why the PR was still failing with a tread leak when it was supposed to fix it

**Comment by wburns** [comment]
Changes look good to me @danberindei I think I would have preferred a separate PR, since I can't now approve this one :D Just waiting on CI before I press the button, last build exploded.

**Comment by wburns** [comment]
Integrated into master, thanks @danberindei !

**Pull request merged**
