### PR TITLE
 ISPN-9541 Module initialization is not thread-safe

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9541
https://issues.jboss.org/browse/ISPN-10186

### CODE REVIEW

**Comment by tristantarrant** [comment]
[2019-08-28T21:12:03.753Z] 21:11:36.606 [ERROR] COMPILATION ERROR : 
23:12:03  21:11:36.606 [INFO] -------------------------------------------------------------
23:12:03  21:11:36.607 [ERROR] /home/infinispan/workspace/Infinispan_PR-7239/core/src/main/java/org/infinispan/factories/ComponentRegistry.java:[237,19] preStop() in org.infinispan.factories.ComponentRegistry cannot override preStop() in org.infinispan.factories.AbstractComponentRegistry
23:12:03    attempting to assign weaker access privileges; was public
23:12:03  21:11:36.607 [ERROR] /home/infinispan/workspace/Infinispan_PR-7239/core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java:[307,19] preStop() in org.infinispan.factories.GlobalComponentRegistry cannot override preStop() in org.infinispan.factories.AbstractComponentRegistry
23:12:03    attempting to assign weaker access privileges; was public
23:12:03  21:11:36.608 [ERROR] /home/infinispan/workspace/Infinispan_PR-7239/core/src/main/java/org/infinispan/factories/InternalCacheFactory.java:[507,4] preStop() in org.infinispan.factories.ComponentRegistry cannot override preStop() in org.infinispan.factories.AbstractComponentRegistry
23:12:03    attempting to assign weaker access privileges; was public

**Comment by ryanemerson** [comment]
@danberindei It's not compiling :fearful: 

```
14:48:23  13:47:50.707 [ERROR] /home/infinispan/workspace/Infinispan_PR-7239/core/src/main/java/org/infinispan/factories/ComponentRegistry.java:[237,19] preStop() in org.infinispan.factories.ComponentRegistry cannot override preStop() in org.infinispan.factories.AbstractComponentRegistry
14:48:23    attempting to assign weaker access privileges; was public
14:48:23  13:47:50.707 [ERROR] /home/infinispan/workspace/Infinispan_PR-7239/core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java:[311,19] preStop() in org.infinispan.factories.GlobalComponentRegistry cannot override preStop() in org.infinispan.factories.AbstractComponentRegistry
14:48:23    attempting to assign weaker access privileges; was public
14:48:23  13:47:50.708 [ERROR] /home/infinispan/workspace/Infinispan_PR-7239/core/src/main/java/org/infinispan/factories/InternalCacheFactory.java:[507,4] preStop() in org.infinispan.factories.ComponentRegistry cannot override preStop() in org.infinispan.factories.AbstractComponentRegistry
14:48:23    attempting to assign weaker access privileges; was public
```

**Comment by danberindei** [comment]
Whoops, I don't know how that `public` got in...

**Comment by ryanemerson** [comment]
`Test Result (1,178 failures / +1102)` :fearful:

**Comment by danberindei** [comment]
@ryanemerson don't worry, just click the button :))

When fixing the compilation error I thought I'd found a clever way to allow the `EventLogManager.getEventLogger()` to initialize the server event logger module automatically, but I just added a dependency cycle instead, so I'm going back to the old way and requiring that the manager is already running.

**Comment by pruivo** [comment]
@danberindei needs rebase

**Comment by ryanemerson** [comment]
Thanks @danberindei

**Pull request merged**
