### PR TITLE
[PERF] Marshall Experiment

### PR DESCRIPTION
**Pull request by pruivo**
just some experiment in which we send the externalizer id in the rpc manager.

### CODE REVIEW

**Comment by pruivo** [comment]
run performance tests please
library

**Comment by Holmistr** [comment]
@pruivo PerfAck failed because of compilation issue, here is a stacktrace:
`/home_local/workspace/regression-build-infinispan/infinispan/persistence/remote/src/main/java/org/infinispan/persistence/remote/wrapper/HotRodEntryMarshaller.java:[17,8] org.infinispan.persistence.remote.wrapper.HotRodEntryMarshaller is not abstract and does not override abstract method objectToBufferWithExternalizer(java.lang.Object,int) in org.infinispan.commons.marshall.Marshaller`

**Comment by pruivo** [comment]
run performance tests please
library

**Comment by pruivo** [comment]
thanks @Holmistr

**Comment by Holmistr** [comment]
@pruivo The job got stuck before creating the report for some reason, but the tests run successfully. Link to the results [here](http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/4773).

**Pull request closed without merging**
