### PR TITLE
ISPN-8486 Support home relative file store paths

### PR DESCRIPTION
**Pull request by galderz**
https://issues.jboss.org/browse/ISPN-8486

### CODE REVIEW

**Comment by danberindei** [comment]
Could you also mention this in the javadoc/user guide?

Personally I think this is too specific, I'd rather have the option of using system properties in the path.

**Comment by tristantarrant** [comment]
This should also work for all paths (other stores, global state, etc)

**Comment by danberindei** [comment]
@tristantarrant I meant this patch allows paths relative to the user home, but I'm not sure how common that use case is vs. making the path relative to a system property/environment variable.

**Comment by tristantarrant** [comment]
We should include this https://github.com/infinispan/infinispan/blob/d46c658a872b9add4040badee80368c97475dbfd/commons/src/main/java/org/infinispan/commons/util/StringPropertyReplacer.java#L52 in the documentation explaining how property replacement works. Tilde expansion is also a nice addition, but to be perfect it must only expand it when it is followed by /. We cannot easily support full ~username expansion without some horrible trickery

**Comment by galderz** [comment]
> Personally I think this is too specific, I'd rather have the option of using system properties in the path.

True, that'd be a better option indeed.

**Comment by galderz** [comment]
> This should also work for all paths (other stores, global state, etc)

What global state path? I understand paths in other stores, but not sure I understand it in the context of global state.

**Comment by tristantarrant** [comment]
Global state has two paths: a persistent one and a temporary one, so it would make sense to support tilde expansion there.

**Comment by galderz** [comment]
Very good points made, I'll close for now and revisit once I have the opportunity to look into this again.

**Pull request closed without merging**
