### PR TITLE
ISPN-13630 Do not send cross-site requests to local site

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.redhat.com/browse/ISPN-13630

### CODE REVIEW

**Comment by wburns** [comment]
Looks like there are some CI failures now, but otherwise seems fine to me.

**Comment by pruivo** [comment]
let's see. I think those tests are failing randomly in the main branch.

**Comment by wburns** [comment]
There was just quite a lot of xsite related ones, so I was thinking it wasn't random. Looks like the latest run was fine though.

**Comment by wburns** [comment]
Integrated into main, thanks @pruivo !

**Pull request merged**
