### PR TITLE
ISPN-14169 Correctly handle empty YAML elements

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14169

### CODE REVIEW

**Comment by ryanemerson** [comment]
Thanks @tristantarrant, I know how much you hate the yaml parser :smile:

**Comment by tristantarrant** [comment]
My issue is with YAML, not with the parser :)
https://github.com/infinispan/infinispan/blob/main/commons/all/src/test/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReaderTest.java#L114

**Review by jabolina — APPROVED** [review]
LGTM

**Comment by jabolina** [comment]
Merged, thanks @tristantarrant

**Pull request merged**
