### PR TITLE
ISPN-9261 Hot Rod Lightweight Transaction (recovery)

### PR DESCRIPTION
**Pull request by pruivo**
* Server initial changes

This is a very "raw" PR but I need to get this in before Beta1. 
It is missing the javadoc, documentation and the client (I'll do a PR for it tomorrow)
All the missing bits should be ready for CR1/Final.

https://issues.jboss.org/browse/ISPN-9261

Don't close the JIRA since I'll attach the client PR as well.

### CODE REVIEW

**Comment by gustavonalle** [comment]
I suppose you should increase the Hot Rod version to 2.9?

**Comment by pruivo** [comment]
@gustavonalle I don't think.
2.8 was introduced in 9.4 Alpha1. Do I need to change in the same minor?

**Comment by gustavonalle** [comment]
@pruivo http://infinispan.org/docs/stable/user_guide/user_guide.html#hot_rod_protocol_2_8

**Comment by pruivo** [comment]
updated!

**Comment by pruivo** [comment]
@gustavonalle yes. 2.8 introduce new parameters in the header, but the test HotRodClient wasn't updated. I'm still using 2.7 in my tests and 2.9 in the client-hotrod tests.

**Pull request closed without merging**
