### PR TITLE
ISPN-10108 - Query Project - Store the test results using TestNG

### PR DESCRIPTION
**Pull request by diegolovison**
Query Project - Store the test results using TestNG

We will have:

- query / target / surefire-reports / testng-junit-results / TEST-org.infinispan.query.dsl.embedded.impl.xml
- query / target / surefire-reports / testng-native-results / TEST-infinispan-query.xml

### CODE REVIEW

**Comment by danberindei** [comment]
@diegolovison I don't see the connection between the JIRA and this change...

**Comment by diegolovison** [comment]
@danberindei yeah, it was my first impression but I saw that we are mixing and this is allowed. I am waiting the test results and I will change it.

**Comment by diegolovison** [comment]
@danberindei ready for review. Please let me know what do you think about the JIRA description

**Comment by danberindei** [comment]
I don't see any change in the JIRA description, only in the PR description, and no link to the JIRA ;)

Question: Are the directories in the PR description created all the time when a Maven project/module uses both JUnit and TestNG, or does that depend on `<disableXmlReport>`?

If the directory structure is not what we expect when archiving artifacts, I assume the `junit` step also needs to change to include those XMLs.

https://github.com/infinispan/infinispan/blob/cc897652cf879d1390dee7d7f501e46c91d98639/Jenkinsfile#L62

**Comment by diegolovison** [comment]
> I don't see any change in the JIRA description
I mean, Jira title.

> does that depend on <disableXmlReport>?
Yes

@danberindei ready for another review.

**Comment by danberindei** [comment]
Integrated, thanks Diego!

For future reference, when a module uses both TestNG and JUnit Surefire runs all the tests with TestNG, in 2 separate ITestSuites, so `PolarionJUnitXMLReporter` writes one report for the TestNG tests and one report for the JUnit tests.

**Pull request merged**
