### PR TITLE
[9.4.x] ISPN-10618 Expiration creation/lastUsed timestamp are lost when prelo…

### PR DESCRIPTION
**Pull request by wburns**
…ading from store

https://issues.jboss.org/browse/ISPN-10618

### CODE REVIEW

**Comment by pruivo** [comment]
@wburns is this updated?

**Comment by wburns** [comment]
@pruivo it is now :)

**Comment by pruivo** [comment]
@wburns ok thanks! I'll integrate this when 9.4.x is open for business xD

**Comment by pruivo** [comment]
integrated! thanks @wburns !

**Pull request merged**
