### PR TITLE
[PREVIEW] ISPN-6494 BlockingBundler

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-6494

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please

[TCP]
[UDP]

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Comment by danberindei** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Comment by danberindei** [comment]
run performance tests please

**Comment by danberindei** [comment]
run performance tests please

**Comment by belaban** [comment]
A 196% increase in performance? If it's too good to be true... :-)
It would be interesting to have a run comparing a selected number of *bundlers* against each other, e.g. transfer-queue, ring-buffer, no-bundler and yours...

**Comment by danberindei** [comment]
@belaban that 196% increase in performance is actually a regression in master vs. 9.4.x caused by the histograms. The results of this PR are just the last column.

For comparison, the `BlockingBundler` numbers are here in the last column here:
http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/18068

**Comment by wburns** [comment]
Closing for now, @danberindei you can reopen if needed later.

**Pull request closed without merging**
