### PR TITLE
ISPN-6972 NonTxDistributionInterceptor doesn't always change the matcher for retry

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-6792
https://issues.jboss.org/browse/ISPN-6451

### CODE REVIEW

**Comment by slaskawi** [comment]
There is one failure that looks suspicious to me: http://ci.infinispan.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=40460#_focus=114414

I'm retriggering CI to check it.

**Comment by danberindei** [comment]
@slaskawi The failure doesn't seem related, all tests passed in the latest run.

**Comment by wburns** [comment]
Pulling..

**Comment by wburns** [comment]
Integrated into master, thanks @danberindei !

**Pull request closed without merging**
