### PR TITLE
ISPN-7814 Remove protected cache security check

### PR DESCRIPTION
**Pull request by galderz**
https://issues.jboss.org/browse/ISPN-7814

* This check has proven to be not very effective.
* Instead, a more comprehensive default security configuration is needed
  which is being worked on.

### CODE REVIEW

**Comment by tristantarrant** [comment]
testNonLoopbackPutOnProtectedCache(org.infinispan.server.hotrod.HotRodSingleClusteredNonLoopbackTest)  Time elapsed: 0.009 sec  <<< FAILURE!
java.lang.ClassCastException: org.infinispan.server.hotrod.test.TestResponse cannot be cast to org.infinispan.server.hotrod.test.TestErrorResponse
	at org.infinispan.server.hotrod.HotRodSingleClusteredNonLoopbackTest.testNonLoopbackPutOnProtectedCache(HotRodSingleClusteredNonLoopbackTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by galderz** [comment]
Checking...

**Comment by galderz** [comment]
@tristantarrant Should be fixed now

**Comment by tristantarrant** [comment]
Pushed to 9.0.x too

**Pull request merged**
