### PR TITLE
ISPN-11131 server-runtime should use log4j2

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-11131

### CODE REVIEW

**Comment by tristantarrant** [comment]
Starting the server with this I get:
`./bin/server.sh 
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
`

**Comment by anistor** [comment]
Does json output still work as before @danberindei ?

**Comment by danberindei** [comment]
@anistor it's not exactly as before, because log4j's `JsonLayout` isn't very configurable, just like jboss-logmanager's JSON formatter. 

I thought anyone processing JSON logs should have the ability to change field names in the config so I didn't try very hard to keep the same field names, the only concession I made was to add a `time` field with the formatted timestamp.

However, Log4j's `PatternLayout` supports JSON encoding, e.g. `%enc{%m}{JSON}`, so we could use it to generate pretty much any JSON format we need. Ok, maybe not the structured exception stack trace :)

**Comment by danberindei** [comment]
@tristantarrant should be working now. I guess I was too focused on getting the JSON log working and I forgot to test the actual server :)

**Comment by danberindei** [comment]
@tristantarrant I know it's not a popular option, but I use a light theme in the terminal (`Solarized Light`) and white doesn't look great there. How about I change it to

      <PatternLayout pattern="%highlight{%d{HH:mm:ss,SSS} %-5p (%t) [%c{1}] %m%throwable}{INFO=normal, DEBUG=normal, TRACE=normal}%n"/>

**Comment by tristantarrant** [comment]
Ok

**Comment by danberindei** [comment]
Updated

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by tristantarrant** [comment]
@danberindei the CLI needs to have its logging configured properly. After this was merged:
`./bin/cli.sh 
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
[disconnected]> 
`

**Pull request merged**
