### PR TITLE
ISPN-10022 Tx compute command updates are not written to stores

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-10022

### CODE REVIEW

**Comment by ryanemerson** [comment]
Retesting as the spring tests barfed

**Comment by alanfx** [comment]
Isn't this expected at this point @tristantarrant? (I mean the Spring tests barfing!)

**Comment by tristantarrant** [comment]
@alanfx Spring Boot has the problem, not Spring

**Comment by tristantarrant** [comment]
Actually this is caused by infinispan.org moving to https

**Comment by tristantarrant** [comment]
I removed enforcement of https on the infinispan.org site and triggered a new build

**Pull request merged**
