### PR TITLE
ISPN-9201 Do not forget to apply Hot Rod flags to the cache before pe…

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-9201

### CODE REVIEW

**Comment by tristantarrant** [comment]
@gustavonalle this was introduced by https://github.com/infinispan/infinispan/pull/5951

**Comment by gustavonalle** [comment]
> @gustavonalle this was introduced by #5951 

ok, strange though that if it was applying the client flags, it affect only 1 test in the whole suite?

**Comment by tristantarrant** [comment]
Indeed. Apparently we do not have tests that verify flags on the first op
on a cache.

**Comment by gustavonalle** [comment]
@tristantarrant right, makes sense, I though it was never applying the flags :)

**Comment by gustavonalle** [comment]
Integrated, thanks @tristantarrant

**Pull request merged**
