### PR TITLE
ISPN-7406 Update Hibernate Search to 5.6.0.Final

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-7406

### CODE REVIEW

**Comment by gustavonalle** [comment]
The tests work for me. The build is broken on CI because it cannot reach the JBoss repo

```
Failed to execute goal on project infinispan-server-feature-pack: Could not resolve
 dependencies for project org.infinispan.server:infinispan-server-feature-pack:pom:9.0.0-SNAPSHOT: 
Failure to find org.infinispan:infinispan-management-console:jar:9.0.0.Beta2 in 
http://maven.repository.redhat.com/earlyaccess/all/ was cached in the local repository, resolution will not be reattempted until the update interval of redhat-earlyaccess-repository-group has elapsed or updates are forced
```

**Comment by gustavonalle** [comment]
Updated

**Comment by anistor** [comment]
Tests looks good on my machine except this failure in ReplFailOverRemoteIteratorTest, which might not be related  :)
```
Tests run: 1597, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 256.41 sec <<< FAILURE! - in TestSuite
createBeforeClass(org.infinispan.client.hotrod.impl.iteration.ReplFailOverRemoteIteratorTest)  Time elapsed: 0.667 sec  <<< FAILURE!
org.infinispan.jmx.JmxDomainConflictException: ISPN000034: There's already a JMX MBean instance type=Server,name=HotRod already registered under 'infinispan-c3718907-a724-4e03-a8fa-97e29f76b53e' JMX domain. If you want to allow multiple instances configured with same JMX domain enable 'allowDuplicateDomains' attribute in 'globalJmxStatistics' config element
	at org.infinispan.jmx.JmxUtil.buildJmxDomain(JmxUtil.java:53)
	at org.infinispan.server.core.AbstractProtocolServer.registerTransportMBean(AbstractProtocolServer.java:102)
	at org.infinispan.server.core.AbstractProtocolServer.startTransport(AbstractProtocolServer.java:93)
	at org.infinispan.server.hotrod.HotRodServer.startTransport(HotRodServer.java:229)
	at org.infinispan.server.core.AbstractProtocolServer.startInternal(AbstractProtocolServer.java:73)
	at org.infinispan.server.hotrod.HotRodServer.startInternal(HotRodServer.java:159)
	at org.infinispan.server.hotrod.HotRodServer.startInternal(HotRodServer.java:84)
	at org.infinispan.server.core.AbstractProtocolServer.start(AbstractProtocolServer.java:80)
	at org.infinispan.server.hotrod.test.HotRodTestingUtil$.startHotRodServer(HotRodTestingUtil.scala:152)
	at org.infinispan.server.hotrod.test.HotRodTestingUtil$.startHotRodServer(HotRodTestingUtil.scala:85)
	at org.infinispan.server.hotrod.test.HotRodTestingUtil.startHotRodServer(HotRodTestingUtil.scala)
	at org.infinispan.client.hotrod.test.HotRodClientTestingUtil.startHotRodServer(HotRodClientTestingUtil.java:77)
	at org.infinispan.client.hotrod.test.HotRodClientTestingUtil.startHotRodServer(HotRodClientTestingUtil.java:55)
	at org.infinispan.client.hotrod.test.HotRodClientTestingUtil.startHotRodServer(HotRodClientTestingUtil.java:103)
	at org.infinispan.client.hotrod.test.MultiHotRodServersTest.addHotRodServer(MultiHotRodServersTest.java:89)
	at org.infinispan.client.hotrod.test.MultiHotRodServersTest.createHotRodServers(MultiHotRodServersTest.java:35)
	at org.infinispan.client.hotrod.impl.iteration.BaseIterationFailOverTest.createCacheManagers(BaseIterationFailOverTest.java:29)
	at org.infinispan.test.MultipleCacheManagersTest.callCreateCacheManagers(MultipleCacheManagersTest.java:109)
	at org.infinispan.test.MultipleCacheManagersTest.createBeforeClass(MultipleCacheManagersTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by gustavonalle** [comment]
Triggering CI one more time...

**Pull request merged**
