### PR TITLE
[14.0.x] ISPN-15824 Collect tls endpoing from protocol servers

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/JDG-6897
https://issues.redhat.com/browse/JDG-6898

Backport of https://github.com/infinispan/infinispan/pull/12089

### CODE REVIEW

**Comment by tristantarrant** [comment]
One related failure https://ci.infinispan.org/job/Infinispan/job/PR-12090/4/testReport/junit/org.infinispan.server.security/TLSWithoutAuthenticationIT/overviewReport/

**Comment by fax4ever** [comment]
> One related failure https://ci.infinispan.org/job/Infinispan/job/PR-12090/4/testReport/junit/org.infinispan.server.security/TLSWithoutAuthenticationIT/overviewReport/

The test looks exactly the same of the one that works on the main branch.
Unfortunately I have no idea why it fails on this branch.
@tristantarrant can you help me with that?

**Comment by fax4ever** [comment]
> > One related failure https://ci.infinispan.org/job/Infinispan/job/PR-12090/4/testReport/junit/org.infinispan.server.security/TLSWithoutAuthenticationIT/overviewReport/
> 
> The test looks exactly the same of the one that works on the main branch. Unfortunately I have no idea why it fails on this branch. @tristantarrant can you help me with that?

I found the way to fix it. I'm pushing it

**Comment by fax4ever** [comment]
According to the CI the test seems to be fixed => https://ci.infinispan.org/job/Infinispan/job/PR-12090/5/testReport/

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
