### PR TITLE
ISPN-16720 Allow supplying a connected JChannel from external source

### PR DESCRIPTION
**Pull request by cfredri4**
https://issues.redhat.com/browse/ISPN-16720

### CODE REVIEW

**Comment by pruivo** [comment]
-1 from me except if you provide me a good reason. 

My reasons for rejecting are

* We drop support for connected (and forkchannel) channels in ISPN11
* Metrics won't be registered because the channel-connected event is not received
* Topology info because Infinispan cannot inject the address generator
* Infinispan elects the coordinator based on the view and we can't ensure all members in the view have a running cache manager. I'm pretty sure the cluster won't work without the coordinator
* Lacks of testing
* Lacks of testing in this PR
* Personal reason, users will misuse this and fill my backlog with painful reports
* Users can extend the class and overwrite the constructor to their needs without us officially supporting it :) 

Let me know your thoughts.

**Comment by cfredri4** [comment]
Many reasons for not doing this. I will close this. 👍

> We drop support for connected (and forkchannel) channels in ISPN11

Do you mean official support for ForkChannel? Because they [are](https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java#L575) [referenced](https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java#L595) [in](https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java#L770) [many](https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java#L779) [places ](https://github.com/infinispan/infinispan/blob/main/core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java#L865) in JGroupsTransport

**Comment by pruivo** [comment]
@cfredri4 We deprecated the way to inject the fork channel. https://github.com/infinispan/infinispan/blob/7aac6121eb7b6d2c7909eb55bc648e0d7cc826d1/core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsChannelLookup.java#L16

**Comment by pruivo** [comment]
@cfredri4 if you move forward by extending the JGroupsTransport to accept a connected channel, my suggestion are

* Set the `connectChannel` to false and the other fields as you need.
https://github.com/infinispan/infinispan/blob/cea9ef6ac5b50c9a8d5f3f95a3e9a9a432f5ffcf/core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java#L193

* Make sure the JGroups coordinator has the `DefaultCacheManager` started. The Infinispan coordinator is the first member of the view
https://github.com/infinispan/infinispan/blob/f25f6c3bf2050adc40d898ecb3f305e437b691b1/core/src/main/java/org/infinispan/remoting/transport/jgroups/ClusterView.java#L30

* Infinispan nodes contact the coordinator during startup to get the state of the cluster. If the above is not guaranteed, I'm unsure if it is failing or you will get a corrupt cluster-wide state.

**Pull request closed without merging**
