### PR TITLE
ISPN-8448 Retried prepare times out while partition is in degraded mode (8.2.x)

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-8448

Throw an AvailabilityException if the cache is in degraded mode
before sending the prepare command remotely.

Please also cherry-pick to 8.1.x

### CODE REVIEW

**Comment by pruivo** [comment]
@danberindei there are a bunch of failures in CI...

**Comment by danberindei** [comment]
@pruivo unfortunately the 8.2.x already has lots of failures even without this PR, I don't think any of the failures are related:

http://ci.infinispan.org/job/Infinispan/job/8.2.x/16/

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by tristantarrant** [comment]
Cherry-picked to 8.1.x as well

**Pull request merged**
