### PR TITLE
ISPN-13839 Remove internal templates from server

### PR DESCRIPTION
**Pull request by pruivo**
* Temporary add templates to REST server for the CLI

https://issues.redhat.com/browse/ISPN-13839

### CODE REVIEW

**Comment by pruivo** [comment]
For CI testing

**Comment by tristantarrant** [comment]
The template removal PR was definitely incomplete. Here are some other related failures:

```
RestOperations.testSSECluster:121 Unexpected error code 400: ISPN000374: No such template 'org.infinispan.DIST_SYNC' when declaring 'caching-listen'
CliIT.testInteractiveCache:The --template=org.infinispan.DIST_SYNC dcached output did not contain expected string after timeout expected:<[//containers/default/caches/dcache]>]> but was:<[create cac 
Error: ISPN000374: No such template 'org.infinispan.DIST_SYNC' when declaring 'dcache'
```

**Comment by tristantarrant** [comment]
```
o.i.s.f.HotRodCompCacheOperationsIT: ISPN004005: Error received from the server: org.infinispan.commons.CacheConfigurationException: org.infinispan.commons.configuration.io.ConfigurationReaderException: org.infinispan.commons.configuration.io.xml.XmlPullParserException: only whitespace content allowed before start tag and not { (position: START_DOCUMENT seen {... @1:1) 
org.infinispan.commons.configuration.io.ConfigurationReaderException: org.infinispan.commons.configuration.io.xml.XmlPullParserException: only whitespace content allowed before start tag and not { (position: START_DOCUMENT seen {... @1:1) 
org.infinispan.commons.configuration.io.xml.XmlPullParserException: only whitespace content allowed before start tag and not { (position: START_DOCUMENT seen {... @1:1) 
```
is also related

**Comment by tristantarrant** [comment]
Moved commits to https://github.com/infinispan/infinispan/pull/12871
Thanks @pruivo

**Pull request closed without merging**
