### PR TITLE
ISPN-12097 Invalidation Cache with a shared store doesn't work proper…

### PR DESCRIPTION
**Pull request by wburns**
…ly after new SPI changes

https://issues.redhat.com/browse/ISPN-12097

### CODE REVIEW

**Comment by pferraro** [comment]
Can we also backport this to 11.0.x?

**Comment by wburns** [comment]
@pferraro That was the hope, were you able to confirm this fixed the issue for you?

**Comment by pferraro** [comment]
@wburns It does indeed fix my issue, and cherry-picks cleanly to boot.

**Comment by ryanemerson** [comment]
Thanks @wburns

**Pull request merged**
