### PR TITLE
ISPN-6732 - XML serializer does not serialize properly async, l1 and site tags

### PR DESCRIPTION
**Pull request by andyuk1986**
https://issues.jboss.org/browse/ISPN-6732
https://issues.jboss.org/browse/ISPN-6733

### CODE REVIEW

**Comment by danberindei** [comment]
@andyuk1986 Could you add a test as well?

**Comment by danberindei** [comment]
@andyuk1986 I see the test was included in https://github.com/infinispan/infinispan/pull/4389, please update this PR to uncomment the attributes fixed here.

**Comment by andyuk1986** [comment]
@danberindei Thanks a lot for review. I have uncommented the test. The pull request is ready for review.

**Comment by danberindei** [comment]
Integrated, thanks Anna!

**Pull request closed without merging**
