### PR TITLE
ISPN-7922 OffHeap stream causes too many entries in memory at once

### PR DESCRIPTION
**Pull request by wburns**
* Make sure that we only have 1 flatMap

https://issues.jboss.org/browse/ISPN-7922

### CODE REVIEW

**Comment by wburns** [comment]
This should cherry pick cleanly into 9.x as well.

**Comment by wburns** [comment]
Updated to use `map.flatMap` idiom to prevent autoboxing. Thanks @danberindei

**Comment by slaskawi** [comment]
retriggering CI

**Comment by danberindei** [comment]
Looks good Will, waiting for CI.

**Comment by wburns** [comment]
Removed redundant while loop as well.

**Comment by wburns** [comment]
Tests have passed.

**Comment by danberindei** [comment]
Integrated, thanks Will!

**Pull request closed without merging**
