### PR TITLE
ISPN-5483 Using multiple FORK channels with JGroupsTransport never acccepts the view, results in NPE

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/ISPN-5483

### CODE REVIEW

**Comment by danberindei** [comment]
@rhusar Please include the commit from the other PR as well, it seems sensible to me.

Also, I don't think the 2nd commit message is accurate, you could say that `waitForChannelToConnect(0)` never waits.

**Comment by rhusar** [comment]
Thanks Dan, cherry picked and reworded. I am mostly worried about overlooking some other implications that this might have but hopefully I am just fixing the parts where the transport didn't take fork channels into account properly.

**Comment by danberindei** [comment]
@rhusar Having second thoughts about this: if `JChannelLookup.shouldConnect()` is `true`, then it doesn't really make sense to have `channel.isConnected()` also `true`.

**Comment by danberindei** [comment]
I integrated the waitForChannelToConnect and logging fixes.

**Comment by rhusar** [comment]
Thanks Dan, looks good!

**Pull request closed without merging**
