### PR TITLE
ISPN-8344 DSL queries filtering only on type are always executed with…

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-8344

### CODE REVIEW

**Comment by gustavonalle** [comment]
Needs backport of https://github.com/infinispan/infinispan/pull/5498 to fix test failures

**Comment by gustavonalle** [comment]
Test failure is fixed by https://github.com/infinispan/infinispan/pull/5502

**Comment by anistor** [comment]
Rebased.

**Comment by anistor** [comment]
The last remaining failure (RemoteQueryCompatModeIT) should be gone now.

**Comment by gustavonalle** [comment]
Merged, thanks

**Pull request merged**
