### PR TITLE
ISPN-3702 Too many threads for cleaning up infinispan transactions

### PR DESCRIPTION
**Pull request by pruivo**
* use timeout executor to cleanup

https://issues.jboss.org/browse/ISPN-3702

### CODE REVIEW

**Comment by tristantarrant** [comment]
A PR for 8.2.x would be nice too please

**Comment by pruivo** [comment]
@tristantarrant done => https://github.com/infinispan/infinispan/pull/4310

**Comment by slaskawi** [comment]
Looks good, pulling

**Comment by slaskawi** [comment]
Pushed into master. Thanks!

**Pull request closed without merging**
