### PR TITLE
ISPN-5271 Usage of filter composition in DistributedEntryRetriever.sendRequest prevents dependency injection to filter and converter

### PR DESCRIPTION
**Pull request by anistor**
Jira: https://issues.jboss.org/browse/ISPN-5271

### CODE REVIEW

**Comment by wburns** [comment]
Whoops I added the comments to the individual commits.

**Comment by wburns** [comment]
@anistor Looks good to me besides these minor things.

**Comment by anistor** [comment]
@wburns I have addressed the comments except this one: https://github.com/anistor/infinispan/commit/0801a3a705e03ae569f3e492c271a0b0227007a2#commitcomment-10058131

**Comment by anistor** [comment]
The CI failures are not related.

**Comment by wburns** [comment]
Pulling..

**Comment by wburns** [comment]
Integrated into master, thanks @anistor !

**Pull request closed without merging**
