### PR TITLE
ISPN-12255 spring-boot-starter tests do not run

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-12255

Make the Spring Boot tests use log4j2

### CODE REVIEW

**Comment by danberindei** [comment]
Updated to remove the logback dependency and configuration file from all the spring-boot modules.

**Review by karesti — APPROVED** [review]

**Comment by karesti** [comment]
the RemoteCacheMetricBinderTest are failing now with the infinispan server extension 
but I made it work in my intellij ... hm

**Comment by danberindei** [comment]
@karesti oh, I created ISPN-12263 for RemoteCacheMetricBinderTest

**Comment by danberindei** [comment]
I have another PR for RemoteCacheMetricBinderTest, #8655

**Pull request merged**
