### PR TITLE
ISPN-7944 Encoders should not handle null references

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-7944

### CODE REVIEW

**Comment by gustavonalle** [comment]
There are failures in the compute commands, looking...

**Comment by gustavonalle** [comment]
Fixed test failures in on compute commands.

**Comment by gustavonalle** [comment]
CI looks OK

**Comment by anistor** [comment]
Looking ...

**Comment by anistor** [comment]
Integrated in master. Thanks @gustavonalle !

**Pull request closed without merging**
