### PR TITLE
ISPN-5826 ISPN-5827 ISPN-5834 Query test suite errors and verbosiness

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-5826
https://issues.jboss.org/browse/ISPN-5827
https://issues.jboss.org/browse/ISPN-5834

### CODE REVIEW

**Comment by gustavonalle** [comment]
Updated with another JIRA

**Comment by Sanne** [comment]
It's all looking nice and I was about to apply it, but one thing puzzles me:
it's now taking almost 50% more time to run all tests ?!
Any idea? I'll try to bisect among your patches..

**Comment by gustavonalle** [comment]
@Sanne updated. Removed the prefix from the version property. 
With relation to the time, is it always the case? To me sometimes it is slower, some other times faster

**Comment by gustavonalle** [comment]
I run it 3 times here: took 2min02s, 47s and 1min47s

**Comment by Sanne** [comment]
you're right, it's just very variable.

**Comment by Sanne** [comment]
merged! thanks

**Pull request closed without merging**
