### PR TITLE
ISPN-12823 Reduce UNICAST3 and NAKACK2 xmit_interval back to 100ms

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-12823

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/19146

**Comment by danberindei** [comment]
Performance is better when reverting the `max_xmit_req_size` change as well (https://github.com/infinispan/infinispan/pull/9271)

**Pull request closed without merging**
