### PR TITLE
ISPN-9748 Default transport for the test suite should be same

### PR DESCRIPTION
**Pull request by diegolovison**
Default transport for the test suite should be the same except if it was activated by another profile

### CODE REVIEW

**Comment by danberindei** [comment]
@diegolovison the udp protocol didn't really work in core (with parallel tests). I pushed another commit to your branch that fixes the udp handling. There are still some failures in `FunctionalTxTest`, but I can't see how the test could be affected by the switch from tcp to udp so we may need @rvansa's help.

**Comment by diegolovison** [comment]
I just synchronized this branch with `master`. Let's wait for CI. 
The JGRP-2305 was fixed so we don't need to be worrying about that on Mac.

**Comment by diegolovison** [comment]
@danberindei do you believe that the failures are related to our change?

**Comment by danberindei** [comment]
All the thread leak failures are unrelated, please rebase.

**Comment by diegolovison** [comment]
@danberindei rebased. let's wait for ci

**Comment by diegolovison** [comment]
@danberindei any other comment? tks

**Comment by danberindei** [comment]
Please rebase :)

**Comment by danberindei** [comment]
I rebased and I also got the `FunctionalTxTest` failures, including the thread leaks.

**Comment by danberindei** [comment]
@diegolovison I created https://issues.jboss.org/browse/ISPN-10070 for the thread leaks. In the meantime you can avoid the error by wrapping the start in `TestingUtil.addClusterEnabledManager():231`

```
      try {
         cm.start();
         return cm;
      } catch (Throwable t) {
         cm.stop();
         throw t;
      }
```

However, I don't understand why the manager startup fails in the first place, and we might need @belaban's help to figure it out. I am able to replicate the failure by running `FunctionalTxTest#testDoubleIncrementAfterTopology` from the IDE, and UDP trace logs show that NodeD is only receiving unicast messages, no multicasts:

```
17:10:46,137 TRACE (remote-thread-Test-NodeA-p2-t2:[org.infinispan.CONFIG]) [UDP] Test-NodeA-12140: sending msg to null, src=Test-NodeA-12140, headers are NAKACK2: [MSG, seqno=27], TP: [cluster_name=ISPN]
17:10:46,137 TRACE (jgroups-5,Test-NodeC-9166:[]) [UDP] Test-NodeC-9166: received [dest: null sender: Test-NodeA-12140 (2 headers), size=2433 bytes, flags=OOB|NO_TOTAL_ORDER|NO_RELAY], headers are NAKACK2: [MSG, seqno=27], TP: [cluster_name=ISPN]
17:10:46,137 TRACE (jgroups-4,Test-NodeB-36236:[]) [UDP] Test-NodeB-36236: received [dest: null sender: Test-NodeA-12140 (2 headers), size=2433 bytes, flags=OOB|NO_TOTAL_ORDER|NO_RELAY], headers are NAKACK2: [MSG, seqno=27], TP: [cluster_name=ISPN]
17:10:46,138 TRACE (remote-thread-Test-NodeA-p2-t2:[org.infinispan.CONFIG]) [MFC] Test-NodeA-12140 used 2433 credits, 1975605 remaining
17:10:46,140 TRACE (remote-thread-Test-NodeA-p2-t2:[]) [UDP] Test-NodeA-12140: sending msg to Test-NodeD-61612, src=Test-NodeA-12140, headers are RequestCorrelator: corr_id=0, type=RSP, req_id=2, rsp_expected=true, UNICAST3: DATA, seqno=3, conn_id=2, TP: [cluster_name=ISPN]
17:10:46,141 TRACE (jgroups-6,Test-NodeD-61612:[]) [UDP] Test-NodeD-61612: received [dest: Test-NodeD-61612 sender: Test-NodeA-12140 (3 headers), size=2378 bytes, flags=OOB|NO_FC|NO_TOTAL_ORDER], headers are RequestCorrelator: corr_id=0, type=RSP, req_id=2, rsp_expected=true, UNICAST3: DATA, seqno=3, conn_id=2, TP: [cluster_name=ISPN]
```

**Comment by danberindei** [comment]
@diegolovison I think I have a workaround for the FunctionalTxTest failure: replace the `fork()` call with

```
      addClusterEnabledCacheManager(cb);
      Future<?> future = fork(() -> {
         cache(3);
      });
```

For some reason NodeD cannot receive multicast messages from NodeA when it's started in a different thread, but works fine when it's started from the main thread.

**Comment by diegolovison** [comment]
Done. Let's wait for CI

**Comment by danberindei** [comment]
The 2 failures also happen on master, integrating.

**Comment by belaban** [comment]
@danberindei Hmm, the snippet you posted above does show that multicast message sent by A is indeed received by B and C! Are you saying the message should at this time also be received by D?

**Comment by danberindei** [comment]
Yes, at that time D was already a member.

**Pull request merged**
