### PR TITLE
ISPN-7362 Use no-bundler in the default UDP configuration

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-7362

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please

**Comment by danberindei** [comment]
run performance tests please

**Comment by Holmistr** [comment]
run performance tests please

**Comment by danberindei** [comment]
run performance tests please

**Comment by Holmistr** [comment]
@danberindei Results were successfully generated, just ignore the C/S part: Link to the report [here](http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tablecomparisonreport/4719)

**Comment by danberindei** [comment]
Results with no-bundler look good. Keeping transfer-queue and re-adding DONT_BUNDLE didn't improve anything.

**Comment by pruivo** [comment]
@danberindei which results are you looking at? in the latest results, there is no improvement (actually, it is worse)

**Comment by danberindei** [comment]
@pruivo I reused the PR to test the transfer-queue bundler with the DONT_BUNDLE flag, and that's what the latest results show. The only run with no-bundler is http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/4716

**Comment by tristantarrant** [comment]
Pushed, thanks

**Pull request merged**
