### PR TITLE
[11.0.x] ISPN-12250 Add exponential back-off for cross-site network failures

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.redhat.com/browse/ISPN-12250

master PR: https://github.com/infinispan/infinispan/pull/8672

### CODE REVIEW

**Comment by pruivo** [comment]
outdated! needs to fetch the updates from master PR.

**Comment by pruivo** [comment]
updated.

**Comment by karesti** [comment]
@pruivo needs rebase

**Review by karesti — CHANGES_REQUESTED** [review]
needs rebase

**Review by karesti — APPROVED** [review]

**Pull request merged**
