### PR TITLE
ISPN-8835 Enjoy query light! The zero calories query that is good for you

### PR DESCRIPTION
**Pull request by anistor**
Now we have 3 entry points to search functionality. 

* org.infinispan.query.~~light~~core.Search  (non-indexex Ickle) **NEW**
* org.infinispan.query.Search  (non-indexex + indexed Ickle, Hibernate Search query, direct Lucene query)
* org.infinispan.client.hotrod.Search  (non-indexex + indexed Ickle)

https://issues.jboss.org/browse/ISPN-8835

### CODE REVIEW

**Comment by anistor** [comment]
All CI failures look 'normal' except for org.infinispan.test.integration.as.InfinispanExtensionIT. I'll investigate ...

**Comment by gustavonalle** [comment]
I'd prefer to not call it ```light```. It gives the impression of a faster, leaner, better query, when in reality it's a much slower query and with less features.  :smile:

Also having both ```org.infinispan.query.XYZ.Search``` and ```org.infinispan.query.Search``` could be confusing. Would it be possible to have just one package, and if lucene+search is in the classpath it will use it, otherwise it will default to only non-indexed queries? Is it doable?

**Comment by anistor** [comment]
> I'd prefer to not call it light. It gives the impression of a faster, leaner, better query, when in reality it's a much slower query and with less features. smile

It is 'light' because it has less baggage. Does not imply it's faster or better. An electric scooter (though very very light) is never faster than a Ducati Streetfighter. The International System of Units also clearly states that speed and mass are independent units :)))

I'm open to naming suggestions. query-zero? or even query-zer0 :)))

> Anyway, regadless of naming, having both org.infinispan.query.XYZ.Search and org.infinispan.query.Search could be confusing. Would it be possible to have just one package, and if lucene+search is in the classpath it will use it, otherwise it will default to only non-indexed queries? Is it doable? This is the same "strategy" adopted by the server to provide either JBossMarshalling (quarkys foe) or Protostream marshalling (quarkus friend)

Unfortunately we can't have a single package because it would have to be  org.infinispan.query.Search and that's already in query, not query-light, and we want to enable people to use just query-light without query if they need to. There's also a similar Search class in hot-rod client, that's why I thought adding a third would not do more harm :) They are basically equivalent, method by method. People just need to choose the right package for their context.  This subject falls into the new API category, which I doubt we'll nail fully even for ispn 11. So I'd like to get something here regardless of new API. And tag it experimental, of course, which I forgot to do in this PR.

**Comment by tristantarrant** [comment]
I think "light" (or "lite") is fine.

**Comment by gustavonalle** [comment]
> Unfortunately we can't have a single package because it would have to be org.infinispan.query.Search and that's already in query

What I meant is to leave this in query, mark Lucene and friends as optional deps, and ```query``` today becomes 'light-er'. All the indexing aspects could be hidden behind interfaces loaded via ServiceLoader or something equivalent conditioned to the presence of an eventual "indexing query provider" in the classpath.

**Comment by anistor** [comment]
Just making optional some dependencies does not solve anything for the long term. My mischievous and not openly declared mission in this PR is to make the first step in deprecating all query.jar at some point and move (slowly or faster, remains to be decided) to query-light all the new clean search related APIs and SPIs, including providing pluggable support for indexing, and also a wrapper for native queries (if anybody needs to pass in directly a lucene query object or HSQuery). So far the only api is Ickle. And then query module dies or just remains as an SPI implementor of the indexing provider, but should no longer offer a public API. Query module is a 10 years old experiment that never had a proper api, instead it leaked all sorts of lucene and hibernate search things.

**Comment by gustavonalle** [comment]
> It is 'light' because it has less baggage. Does not imply it's faster or better

The PR title says otherwise :smile:

> Just making optional some dependencies does not solve anything for the long term

Agreed, but that's not what I wrote. It needs to be combined with some refactor to make indexing pluggable

> and move (slowly or faster, remains to be decided) to query-light all the new clean search related APIs and SPIs

Call it ```query-api``` or ```query-core```, since it will host the API and the default implementation which is slow but has less deps?

**Comment by anistor** [comment]
so far it is neither a query-api nor a query-core. just a new experimental home for future query. this does not need to happen in 10.1 btw, but would not hurt.

**Comment by gustavonalle** [comment]
> so far it is neither a query-api nor a query-core.

So why not calling it ```query-core.jar``` (```org.infinispan.query.core.Search```) ?
It does not involve any cognitive hability to realize what it is right away (as opposed to query-light) and in the future a query-api can be extracted from it  :smile:

**Comment by anistor** [comment]
I'm starting to like ```query-core``` although ```query-core-light``` sounds a bit better :grinning:

**Comment by anistor** [comment]
I've just made the query-light -> query-core rename @gustavonalle , @tristantarrant .  I'll wait for CI to see nothing slipped through the cracks (of my sanity) and then will squash some commits and should be ready to merge.

**Comment by anistor** [comment]
Fixed some failures caused by the rename, let's see CI again...

**Comment by tristantarrant** [comment]
Merged, thanks !

**Pull request merged**
