### PR TITLE
ISPN-11179 Ignore OkHttp thread leaks and close our responses

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-11179

### CODE REVIEW

**Comment by wburns** [comment]
Why so many changes about log4j in this? Are they really related to OkHttp?

**Comment by danberindei** [comment]
It's because of https://issues.redhat.com/browse/ISPN-11179?focusedCommentId=13955131&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13955131

In order to apply the log4j configuration to OkHttpClient and to make it log the allocation stack trace, I had to add the `log4j-jul` test dependency and the `java.util.logging.manager` system property to all the modules. I took the opportunity to also add `log4j2.contextSelector` to avoid creating multiple log4j contexts, and to group the logging system properties together in the POMs.

I would have liked to go even further and move some of the failsafe configuration from all the integration test modules in the parent POM, but I thought I had to stop at some point :)

**Comment by wburns** [comment]
It looks like some spring tests are now failing due to the logging changes? https://ci.infinispan.org/job/Infinispan/job/PR-7784/1/

**Comment by tristantarrant** [comment]
@danberindei we need a backport to 10.1.x

**Pull request merged**
