### PR TITLE
ISPN-15396 Netty 4.1.104.Final

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-15396

### CODE REVIEW

**Comment by tristantarrant** [comment]
Supersedes https://github.com/infinispan/infinispan/pull/11588 and https://github.com/infinispan/infinispan/pull/11589

**Review by wburns — APPROVED** [review]
Changes look good, but CI was having issues, restarting.

**Comment by tristantarrant** [comment]
failures are unrelated

**Comment by wburns** [comment]
Integrated into main, thanks @tristantarrant !

**Pull request merged**
