### PR TITLE
ISPN-11784 Combine netty and non blocking thread pools

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-11784
https://issues.redhat.com/browse/ISPN-12569

Note, please do not close ISPN-12569 as this just marks the method as blocking, but doesn't actually fix it.

### CODE REVIEW

**Comment by wburns** [comment]
Created to see what errors are still around with this.

Last checked there was some non blocking code that actually blocked waiting on the blocking manager that then submitted to the same event loop. The only way to really fix that is to prevent the non blocking code from performing that operation, so this should find it.

**Comment by wburns** [comment]
run performance tests please
cs-hotrod

**Comment by wburns** [comment]
The current test that is running will not be a good indicator as it has a hard coded value of only 2 netty event loops. Adding a new commit to revert so we can get a good perf test run.

**Comment by wburns** [comment]
run performance tests please
cs-hotrod

**Comment by wburns** [comment]
run performance tests please
cs-hotrod

**Comment by wburns** [comment]
run performance tests please
cs-hotrod

**Comment by wburns** [comment]
There are a few more places in `ProtobufMetadataManagerInterceptor` I need to clean up, but should be ready tomorrow hopefully.

**Comment by diegolovison** [comment]
run performance tests please
cs-hotrod

**Comment by diegolovison** [comment]
run performance tests please
cs-hotrod

**Comment by wburns** [comment]
I am hoping CI is okay now. The last run is on master as well https://ci.infinispan.org/job/Infinispan/job/master/2510/#showFailuresLink so I am hoping it is just an existing issue. Will keep checking.

**Comment by wburns** [comment]
CI didn't fail this time https://ci.infinispan.org/job/Infinispan/job/PR-8885/26/

Also I noticed that master sometimes has the same failure I seem to be getting a lot in this PR, so I think it is somewhat unrelated, but I will try a bit more to reproduce. (e.g. https://ci.infinispan.org/view/Infinispan/job/Infinispan/job/master/2510/#showFailuresLink)

**Comment by wburns** [comment]
Well nothing shows up as an issue in the thread dumps for some reason...

**Comment by wburns** [comment]
This PR relies upon https://github.com/infinispan/infinispan/pull/8944 now so it can be integrated separately.

**Comment by wburns** [comment]
Found out the near cache tests would fail randomly depending upon when the get command as invoked and if the near cache listener was yet installed. The test should not be deterministic in that it waits for the listener to complete failover before asserting events.

**Comment by tristantarrant** [comment]
@wburns aside from the rebase, what's the status ehre ?

**Comment by wburns** [comment]
I am waiting until we branch so master is only 13.0 before going with this. It is a bit too high risk to put in a minor patch imo.

**Comment by wburns** [comment]
Closed for now

**Pull request closed without merging**
