### PR TITLE
ISPN-7756 Rename all pseudo-JPA filtering classes to Ickle

### PR DESCRIPTION
**Pull request by anistor**
Don't be scared by the large number of modified files. These are just renamed classes.

https://issues.jboss.org/browse/ISPN-7756

### CODE REVIEW

**Comment by anistor** [comment]
The CI failures are "OK" :)

**Comment by slaskawi** [comment]
hmmmm I'm not sure about this PR. It seems to change user-facing APIs. Since we are releasing a minor version I guess we are not allowed to do it (but we can deprecate old APIs and ask users to migrate to the new ones).

**Comment by anistor** [comment]
These are all implementation details of query/continuous query. No API involved.

**Comment by tristantarrant** [comment]
In it goes. Thanks @anistor

**Pull request merged**
