### PR TITLE
ISPN-12927 Intermittent error ISPN000287 when triggering rolling upgrades

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.redhat.com/browse/ISPN-12927

### CODE REVIEW

**Comment by tristantarrant** [comment]
I think shutting down the elytron scheduled executor like that is harming a lot of tests

**Comment by gustavonalle** [comment]
Indeed @tristantarrant

**Comment by gustavonalle** [comment]
Tests are fixed @tristantarrant

**Review by wburns — APPROVED** [review]
Changes look okay to me. Haven't seen those test failures before, maybe they are random as well :(

Needs to be rebased now.

**Comment by gustavonalle** [comment]
Rebased

**Comment by pruivo** [comment]
@wburns @tristantarrant  can I merge it?

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
