### PR TITLE
Undeploy jars properly after test suite termination

### PR DESCRIPTION
**Pull request by anistor**

### CODE REVIEW

**Comment by gustavonalle** [comment]
We should add the same undeploy logic for \*CustomMarshaller\*IT

**Comment by danberindei** [comment]
@anistor couldn't Arquillian delete the jars?

**Comment by anistor** [comment]
I initially started cleaning up stuff that was NOT deployed using Arquillian. These obviously needed explicit cleaning. Then I continued with some Arquillian managed stuff. Seems it is not cleaned up, and not sure if it should be expected to be cleaned up by design.

**Comment by anistor** [comment]
Closing this. These commits are now included in https://github.com/infinispan/infinispan/pull/5604 ,  https://github.com/infinispan/infinispan/pull/5605 and https://github.com/infinispan/infinispan/pull/5623

**Pull request closed without merging**
