### PR TITLE
[9.4]  ISPN-9822 BasicComponentRegistryImpl fails with security manager

### PR DESCRIPTION
**Pull request by rhusar**
Jira
https://issues.jboss.org/browse/ISPN-9822

Also should be merged to master.

### CODE REVIEW

**Comment by rhusar** [comment]
@danberindei Since this is your code, could you please review? Thanks! cc @tristantarrant

**Comment by rhusar** [comment]
@danberindei Ok, refactored according to you preferences (more LOC to manage, extra class, finicky class visibility...) :-)

**Comment by danberindei** [comment]
And that's why we love it :)

Thanks Rado, integrated!

**Comment by rhusar** [comment]
Thanks Dan.

**Pull request merged**
