### PR TITLE
ISPN-11245 Show full category (class) names for logging

### PR DESCRIPTION
**Pull request by wfink**
https://issues.redhat.com/browse/ISPN-11245

### CODE REVIEW

**Comment by ryanemerson** [comment]
Thanks @wfink

**Comment by ryanemerson** [comment]
@wfink Do we want this in 10.1.x as well?

**Comment by tristantarrant** [comment]
Yes, It needs to be in 10.1

**Comment by ryanemerson** [comment]
https://github.com/infinispan/infinispan/pull/7845

**Pull request merged**
