### PR TITLE
ISPN-5806 Add transaction support for functional API

### PR DESCRIPTION
**Pull request by rvansa**
This depends on #4564 , only the last commit is specific to this PR.

### CODE REVIEW

**Comment by rvansa** [comment]
Just realized that read-after write does not work as it should...

**Comment by rvansa** [comment]
The problem was solved by sending TxReadOnlyKeyCommand and TxReadOnlyManyCommand that replay all the modifications on the node before applying the functional read.

**Comment by galderz** [comment]
@rvansa The functional transactional part looks good. Once #4564 is in, we can go ahead and integrate this particular commit.

**Comment by galderz** [comment]
Needs rebase

**Comment by rvansa** [comment]
@danberindei @pruivo Rebased!

**Comment by galderz** [comment]
Integrated, thx @rvansa

**Pull request closed without merging**
