### PR TITLE
[8.1.x][ISPN-7535] Cache creation requires specific permissions when using s…

### PR DESCRIPTION
**Pull request by gaol**
…ecurity manager

Move Util.getClassLoaders() and ReflectionUtil.invokeAccessibly() to doPrivileged() when security manager is enabled

Jira: https://issues.jboss.org/browse/ISPN-7535

PR to 8.2.x branch: https://github.com/infinispan/infinispan/pull/4918

### CODE REVIEW

**Comment by tristantarrant** [comment]
Requires the same changes as https://github.com/infinispan/infinispan/pull/4920

**Comment by slaskawi** [comment]
Closing. Please address all comments in https://github.com/infinispan/infinispan/pull/4920 and then reopen.

**Comment by gaol** [comment]
@slaskawi would you please reopen this PR? The #4920 has been merged, and this has the same fix with #4920, but to 8.1.x branch

**Comment by tristantarrant** [comment]
No need to. I'm reverifying locally

**Pull request closed without merging**
