### PR TITLE
ISPN-9469 query timeout reloaded

### PR DESCRIPTION
**Pull request by anistor**
These are some small glitches I missed in initial review of @gustavonalle 's PR

https://issues.redhat.com/browse/ISPN-9469

https://issues.redhat.com/browse/ISPN-11976

https://issues.redhat.com/browse/ISPN-11977

https://issues.redhat.com/browse/ISPN-11917

### CODE REVIEW

**Comment by anistor** [comment]
I expect some trivial class cast exceptions caused by my changes. I'll fix them once I have the ful picture from CI

**Comment by anistor** [comment]
Updated. All failures should be gone now @gustavonalle

**Comment by gustavonalle** [comment]
Waiting for CI to merge

**Comment by anistor** [comment]
I've just rebased it. But did not add anything new. So if any CI run is fine, it's good, don't have to wait for the last run to complete @gustavonalle

**Comment by gustavonalle** [comment]
I see a successful run this morning, then CI is tripping over itself until now. I will risk merge, at least there is a bigger change that master will end-up running it 😄

**Comment by gustavonalle** [comment]
Merged in master

**Pull request merged**
