### PR TITLE
Revert "ISPN-12823 JGroups retransmission requests are too frequent a…

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-12823_revert_12.1.x

### CODE REVIEW

**Comment by tristantarrant** [comment]
run performance tests please

**Comment by diegolovison** [comment]
http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/19148

**Comment by danberindei** [comment]
Merged, thanks Tristan!

**Comment by danberindei** [comment]
Cherry-picked on master as well.

**Pull request merged**
