### PR TITLE
ISPN-9376 Enhance RemoteStore to support segmentation

### PR DESCRIPTION
**Pull request by wburns**
* Added in segment based bulk operations

https://issues.jboss.org/browse/ISPN-9376

### CODE REVIEW

**Comment by wburns** [comment]
Have some test failures to look at. Not sure why they are complaining about segmentation.. those tests shouldn't have it enabled.

**Comment by wburns** [comment]
The test failures are unrelated.

**Comment by pruivo** [comment]
@wburns looks good to me. I'm gonna trigger another CI run.

**Comment by wburns** [comment]
Afaik those tests fail on master as well, so I mostly ignored them. There shouldn't be any changes there tbh.

**Comment by pruivo** [comment]
integrated! thanks @wburns

**Pull request merged**
