### PR TITLE
ISPN-8349 More tests for off-heap query

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-8349

Added some more tests but no fix yet. 

* RemoteOffHeapQueryDslConditionsTest and RemoteQueryOffHeapIT are failing while RemoteOffHeapNonIndexedQueryDslConditionsTest is working

### CODE REVIEW

**Comment by anistor** [comment]
@gustavonalle Maybe you have some clue regarding this failure:
```
[ERROR] Tests run: 411, Failures: 1, Errors: 0, Skipped: 410, Time elapsed: 4.071 s <<< FAILURE! - in org.infinispan.client.hotrod.query.RemoteOffHeapQueryDslConditionsTest
[ERROR] populateCache(org.infinispan.client.hotrod.query.RemoteOffHeapQueryDslConditionsTest)  Time elapsed: 2.731 s  <<< FAILURE!
org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=7 returned server error (status=0x85): java.io.IOException: Unknown type: 74
	at org.infinispan.client.hotrod.impl.protocol.Codec20.checkForErrorsInResponseStatus(Codec20.java:363)
	at org.infinispan.client.hotrod.impl.protocol.Codec20.readPartialHeader(Codec20.java:152)
	at org.infinispan.client.hotrod.impl.protocol.Codec20.readHeader(Codec20.java:138)
	at org.infinispan.client.hotrod.impl.operations.HotRodOperation.readHeaderAndValidate(HotRodOperation.java:60)
	at org.infinispan.client.hotrod.impl.operations.AbstractKeyValueOperation.sendPutOperation(AbstractKeyValueOperation.java:58)
	at org.infinispan.client.hotrod.impl.operations.PutOperation.executeOperation(PutOperation.java:34)
	at org.infinispan.client.hotrod.impl.operations.RetryOnFailureOperation.execute(RetryOnFailureOperation.java:56)
	at org.infinispan.client.hotrod.impl.RemoteCacheImpl.put(RemoteCacheImpl.java:268)
	at org.infinispan.client.hotrod.impl.RemoteCacheSupport.put(RemoteCacheSupport.java:77)
	at org.infinispan.query.dsl.embedded.QueryDslConditionsTest.populateCache(QueryDslConditionsTest.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by gustavonalle** [comment]
@anistor It looks like an encoding conflict between offheap and remote query, looking...

**Comment by gustavonalle** [comment]
Migrated the tests to https://github.com/infinispan/infinispan/pull/5498, closing...

**Comment by anistor** [comment]
Thanks @gustavonalle !

**Pull request closed without merging**
