### PR TITLE
ISPN-13917 Protostream 4.5.0.Dev02

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-13917

### CODE REVIEW

**Review by wburns — APPROVED** [review]
LGTM, just waiting on CI confirmation.

**Comment by pferraro** [comment]
Is there a particular reason why 4.5.0.Dev02 has no tag?

**Comment by tristantarrant** [comment]
Because I forgot to push it. https://github.com/infinispan/protostream/tree/4.5.0.Dev02

**Comment by tristantarrant** [comment]
Fixed the JSON test failures

**Comment by tristantarrant** [comment]
Hm, some other failures

**Review by pruivo — APPROVED** [review]

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
