### PR TITLE
ISPN-6767 Update the Hibernate ORM version in the parent pom.xml as well

### PR DESCRIPTION
**Pull request by Sanne**
previous PR #4518 was apparently missing a change!

Marking urgent as we already marked the JIRA as resolved: would be nice to merge this soon as the other related commit is the last on master, so they can stay together.

### CODE REVIEW

**Comment by anistor** [comment]
I knew it! I searched for 5.0.9.Final in all pom.xml files and was surprised not to find any occurrence :)

**Comment by anistor** [comment]
My local run looks good. Pulling.

**Comment by anistor** [comment]
Integrated. Thanks @Sanne !

**Comment by Sanne** [comment]
thanks @anistor !

**Comment by gustavonalle** [comment]
This PR broke OSGI JPA tests

**Comment by anistor** [comment]
yup. it seems hibernate core 5.1.1.Final has a new dependency: com.fasterxml.classmate

**Comment by anistor** [comment]
Well, it was not a new dependency, we just forgot to align versions. Here is the fix: https://github.com/infinispan/infinispan/pull/4522

**Pull request merged**
