### PR TITLE
ISPN-6474 Restore setting the default cache name on protocol server start

### PR DESCRIPTION
**Pull request by tristantarrant**
Apply to both master and 8.2.x please
https://issues.jboss.org/browse/ISPN-6474

### CODE REVIEW

**Comment by danberindei** [comment]
7 test failures: http://ci.infinispan.org/viewLog.html?buildId=41548&tab=buildResultsDiv&buildTypeId=bt9

**Comment by tristantarrant** [comment]
Should be fixed, let's wait for CI

**Comment by tristantarrant** [comment]
All green !

**Comment by anistor** [comment]
Integrated in master and 8.2.x. Thanks @tristantarrant !

**Pull request merged**
