### PR TITLE
ISPN-13193 Decouple invoke Operation from the Channel Pool

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.redhat.com/browse/ISPN-13193
https://issues.redhat.com/browse/ISPN-13206
https://issues.redhat.com/browse/ISPN-13209
https://issues.redhat.com/browse/ISPN-13227

### Hot Rod queue experiments

**The goal**
Test different Hot Rod pool queue implementations

### Question: 

- Should we have a test that ensures that events in the pool should be executed in the order that they arrived?
-- No

- Hot Rod operations are not inside an event loop?
-- Yes they are. AbstractChannelHandlerContext::write(Object msg, boolean flush, ChannelPromise promise)

**Assumptions:**
The order that the operations arrived in the server or arrived back ( response ) in the client is out of context.
I am not talking about Linearizability per key and per thread
The current code (12.1.x branch)

**The client configuration:**
builder.connectionPool().maxWait(-1).maxPendingRequests(1).maxActive(2);

**Operations:**
Let’s consider the following set of operations arrived in the pool in the following order:
putAsync(1, 2)
putAsync(1, 1)
putAsync(2, 3)
putAsync(2, 2)
putAsync(2, 1)

**Order of events:**
The client retrieves a channel and fire putAsync(1, 2)
The client retrieves a channel and fire putAsync(1, 1)
The client enqueue putAsync(2, 3) because maxActive is 2
The client enqueue putAsync(2, 2) because maxActive is 2
The client finishes writing request from putAsync(1, 1) and fire putAsync(2, 3) ( the first in the queue using the same channel )
The client enqueue putAsync(2, 1) because the channel didn’t add back to the pool
The client finishes writing request from putAsync(2, 3) and fire putAsync(2, 2) ( the second in the queue using the same channel )
The client finishes writing request from putAsync(2, 2) and fire putAsync(2, 1) ( the last in the queue using the same channel )
The client finishes writing request from putAsync(1, 1) and add the channel back to the pool
The client finishes writing request from putAsync(2, 1) and add the channel back to the pool

PRs
https://github.com/netty/netty/pull/11566

### CODE REVIEW

**Comment by diegolovison** [comment]
run custom performance tests please
cs-hotrod

**Comment by diegolovison** [comment]
run custom performance tests please
cs-hotrod

**Comment by diegolovison** [comment]
Commit: a3260d038e119806f311b71b3e77b63e357933ce
http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/19172
No performance impact

**Comment by diegolovison** [comment]
Commit: e73d04b9fb6fae747ab69edb9ae2cc5574f04e96 ( ISPN-13227 HotRodChannelPool SPI )
http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/19179
No performance impact

**Comment by diegolovison** [comment]
Commit: 5b85da93ae5cb022eacf6e5b25228565d876c649 ( ISPN-13227 HotRodChannelPool SPI )
http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/19181
No performance impact

**Comment by diegolovison** [comment]
@danberindei some considerations about the rebase based on your latest changes:

* I run my PR with https://github.com/infinispan/infinispan/pull/9659 and it passed. It has the test with maxRetries == 0
* We don't need the `getConnected` method. We can use `getIdle() == 0`. I removed `getConnected` in my PR
```java
if (pool.getConnected() == 0) {
  failedServers.add(pool.getAddress());
}
```
https://github.com/infinispan/infinispan/blob/main/client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java#L465-L467
* `HOTROD.invalidActiveCountAfterClose(channel);` and `HOTROD.invalidCreatedCountAfterClose(channel);` can be called when channel was not initialized. I added back the asserts.
https://github.com/infinispan/infinispan/blob/main/client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelPool.java#L152-L158
* The attribute `currentClusterName ` was removed
https://github.com/danberindei/infinispan/blob/8b4cc6c6583a74e49896c66348fd41e6d1355aa4/client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java#L44

**Comment by diegolovison** [comment]
Commit: c1ba5d97ca9ad3f664c9ca5a4e207d263572dfb4 ( ISPN-13227 HotRodChannelPool SPI )
http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/19501
No performance impact

**Comment by diegolovison** [comment]
https://github.com/netty/netty/pull/11857

**Comment by danberindei** [comment]
@diegolovison I'm finally coming back to this PR, but I'm not sure where to start: the commit message and the subject of ISPN-13227 both say you want to add a HotRodChannelPool SPI, but the `HotRodChannelPool` interface is in package package org.infinispan.client.hotrod.impl.transport.netty.pool so it doesn't really qualify as an SPI, and there is no test replacing it with an alternative implementation.

**Comment by diegolovison** [comment]
Hi @danberindei thanks for looking. I put a label `On Hold` because the replacement is coming. It is blocked by:

https://github.com/netty/netty/pull/11860
https://github.com/netty/netty/issues/11861

**Comment by danberindei** [comment]
I see @diegolovison.

One more thing: I looked at the ChannelRecord/ChannelKeys changes and it's not clear to me why the activation future and the unresolved address can't stay in ChannelRecord, e.g.

https://github.com/infinispan/infinispan/compare/main...danberindei:pr_diegolovison_ISPN-13185

**Pull request closed without merging**
