### PR TITLE
[9.4.x] ISPN-10924 JPA cache store (with async enabled) will log Exceptions i…

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-10924
https://issues.jboss.org/browse/ISPN-10940

### CODE REVIEW

**Comment by wburns** [comment]
Looks like a compilation error https://ci.infinispan.org/job/Infinispan/job/PR-7567/1/display/redirect

**Comment by ryanemerson** [comment]
Sorry about that, I was rushing. It's good to go now

**Comment by ryanemerson** [comment]
I've added https://issues.jboss.org/browse/ISPN-10940 to this PR as it is related.

**Comment by pruivo** [comment]
@ryanemerson there is a compilation error.

**Comment by pruivo** [comment]
integrated! thanks @ryanemerson !

**Pull request merged**
