### PR TITLE
ISPN-9949 & ISPN-8826 Remove the implicit default cache

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-9949
https://issues.jboss.org/browse/ISPN-8826

Every test now sets the default cache to be named after the test's short name.
Some commits in here will be removed when the corresponding PRs are merged.

### CODE REVIEW

**Comment by ryanemerson** [comment]
`ThreadLocalLeakTest` is now failing with `initialized with a default cache configuration but without a name for it`. Not sure why Jenkins isn't picking up the test failure though.

**Comment by tristantarrant** [comment]
Failures unrelated

**Comment by tristantarrant** [comment]
Rebased

**Comment by tristantarrant** [comment]
@ryanemerson I removed the factory factory as it was unused. I also used this.getClass().getClassLoader() in createSaslServer() to avoid overriding and I fixed the javadoc.

**Pull request merged**
