### PR TITLE
ISPN-10516 REST doc productization

### PR DESCRIPTION
**Pull request by oraNod**
https://issues.jboss.org/browse/ISPN-10516

### CODE REVIEW

**Comment by gustavonalle** [comment]
@oraNod  -1 for this  :smile: 

This breaks all the editing capabilities in Intellij unfortunately and it has so many very small pieces...

screen1
screen2

**Comment by oraNod** [comment]
@gustavonalle hmm, I've just added a commit that should resolve the include statements in IntelliJ. I'll need to change those for productization but it should do for community.

as for the many pieces, yeah... this is all part of the modularization effort. we're going that way with the other docs. I realize it adds a bit of overhead but it's honestly has lots of advantages.

I also admit I went down a wrong path initially by putting all the example REST calls in separate files so I've corrected that in this PR. could you have another look and let me know what you think please?

**Comment by oraNod** [comment]
@gustavonalle also I'd like to add that I plan on making some more changes in the next sprint to reduce the number of topics/"small pieces". perhaps I can show you what I've been doing with the CLI and Server docs and we can discuss?

**Comment by gustavonalle** [comment]
I can see that there are many CLI docs (that were just merged on master) with issues rendering on Intellij as well

**Comment by gustavonalle** [comment]
Other thing I noticed, is that on ```master```, I open rest_v2_api adoc and I can edit and see the whole document tree in Intellij ("structure") view. With this PR, it's not possible anymore, I can only edit the small pieces individually without having a notion of the context. This would force constant rendering of the docs to see the changes...

**Comment by oraNod** [comment]
@gustavonalle I've reworked it to reduce some of the complexity. I guess I got a bit carried away but will hopefully find a balance with this. I appreciate your patience and enjoy collaborating.. 

I've had a look in intellij and would make the comment that opening the title file that pulls everything in works well. imo it's also good to view the doc more in its entirety.

image

**Comment by gustavonalle** [comment]
@oraNod There's a conflict

**Comment by oraNod** [comment]
@gustavonalle no worries. I noticed Katia's PR in the queue. glad that was merged first and I got the conflict. should be sorted now. thanks again!

**Comment by oraNod** [comment]
@gustavonalle I tried to preserve the structure but instead of sections in a single file there are now files per section.

ref_rest_cache_managers.adoc
ref_rest_caches.adoc
ref_rest_clusters.adoc
ref_rest_counters.adoc
ref_rest_xsite.adoc
ref_rest_xsite_cache_managers.adoc

I think the issue with this PR is to do with the assemblies rather than the topics. I'll make some changes and try again.

**Comment by gustavonalle** [comment]
@oraNod Maybe I was not clear, was not talking about files, but sections. We shouldn't have a section named "Gathering Cluster and Cache Health and Statistics" continuing cache and and cluster mixed for example. Same for "Monitoring and Controlling Cross-Site Replication Operations" mixing cache and cache manager ops.

**Comment by gustavonalle** [comment]
@oraNod The content looks ok now, how can I preview in Intellij? I tried open stories.adoc but it appears broken ,the same for assembly_rest_api.adoc

**Comment by oraNod** [comment]
@gustavonalle can you preview titles/rest/rest.asciidoc? that file has the directory attributes that resolve {topics} and {stories} variables in those includes:: directives.

**Comment by gustavonalle** [comment]
Yes, that one works 👍

**Comment by gustavonalle** [comment]
@oraNod So it's the IntelliJ plugins fault that most files are not visible, since it does not propagate variables to the included resources?

**Comment by oraNod** [comment]
@gustavonalle I don't know if it's the intellij plugin or just the fact that we need to include path variables to the assembly files. I'm not sure how intellij could work out which assembly files are included in which title files for propagation.

I've updated the PR with a couple of new "community_path.adoc" files. these are included in `titles/rest/rest.asciidoc` and `stories/assembly_rest_api.adoc`.

from my own testing in intellij this seems to work and the includes directives are resolved correctly.

**Comment by gustavonalle** [comment]
@oraNod It seems the tasks resource is missing?  https://infinispan.org/docs/dev/titles/rest/rest.html#rest_v2_tasks

**Comment by gustavonalle** [comment]
@oraNod Also the section "Client-Side Code" is not being rendered

**Comment by oraNod** [comment]
@gustavonalle it looks like those "community_path.adoc" files were causing some weird problems. I think that's just introducing issues so I removed them and squashed.

I don't really know what to say about the intellij plugin. the issue stems from the fact that product docs tooling requires symlinks. in community adding symlinks instead of absolute references (`../../`) is a problem.

**Comment by gustavonalle** [comment]
@oraNod Is there any tool that can understand the includes and correctly preview each individual piece? Intellij is convenient but not a hard requirement.

**Comment by oraNod** [comment]
@gustavonalle not unless you open from the top level title file (master assembly). in this case that is titles/rest/rest.asciidoc. I would argue that is the correct approach because you see everything in context, which is what you want if you're previewing.

to preview the includes the tool needs to resolve the {topics} and {stories} directory variables. those are included in the title files.

sorry it's such a PITA. we're in this situation because of product docs tooling.

**Comment by gustavonalle** [comment]
Well, I guess we'll have to take the hit then :smile:

**Comment by gustavonalle** [comment]
Merged, thanks @oraNod

**Pull request merged**
