### PR TITLE
ISPN-5463 ClassCastException: org.infinispan.query.remote.indexing.Pr…

### PR DESCRIPTION
**Pull request by anistor**
…otobufValueWrapper cannot be cast to [B

jira: https://issues.jboss.org/browse/ISPN-5463

This is for 7.2.x!

### CODE REVIEW

**Comment by tristantarrant** [comment]
Looks good, testing

**Comment by anistor** [comment]
Updated. Just added a new test.

**Comment by tristantarrant** [comment]
Ok, I'll rerun the test

**Comment by tristantarrant** [comment]
Pushed, thanks

**Pull request closed without merging**
