### PR TITLE
ISPN-5726 Missing avro serializer when running indexed queries in a c…

### PR DESCRIPTION
**Pull request by gustavonalle**
…lustered server

https://issues.jboss.org/browse/ISPN-5726

Should be applied on master and on the bugfix branch 8.0.x

### CODE REVIEW

**Comment by anistor** [comment]
Is there a 'bugfix branch 8.0.x' already?

**Comment by gustavonalle** [comment]
@anistor no, should it be created?

**Comment by anistor** [comment]
We'll create it when we release 8.0.1 next week I guess.

**Comment by galderz** [comment]
Integrated

**Pull request closed without merging**
