### PR TITLE
[13.0] ISPN-13500 CLI install

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-13500

### CODE REVIEW

**Comment by tristantarrant** [comment]
@pruivo the `install` command is a feature. It should be disabled downstream

**Comment by pruivo** [comment]
> @pruivo the `install` command is a feature. It should be disabled downstream

why are we backporting to 13.0.x?

**Comment by karesti** [comment]
@pruivo because waiting to 14 to have it is too long

**Review by karesti — APPROVED** [review]

**Comment by pruivo** [comment]
well... I guess it is too late to request changes :)

**Pull request merged**
