### PR TITLE
ISPN-11424 Remove deprecated memory configurations from internal caches

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.redhat.com/browse/ISPN-11424

### CODE REVIEW

**Comment by gustavonalle** [comment]
@ryanemerson This will silence the WARNs

**Comment by anistor** [comment]
I see a single related failure: org.infinispan.client.hotrod.event.ClientClusterExpirationEventsTest.testNullValueMetadataExpiration

**Comment by gustavonalle** [comment]
This is also failing on master unfortunately:
https://ci.infinispan.org/job/Infinispan/job/master/2030/#showFailuresLink
https://ci.infinispan.org/job/Infinispan/job/master/2011/#showFailuresLink

**Comment by ryanemerson** [comment]
Thanks @gustavonalle

**Pull request merged**
