### PR TITLE
ISPN-6886 + ISPN-6887 Continous query, named params user guide

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-6886
https://issues.jboss.org/browse/ISPN-6887

### CODE REVIEW

**Comment by tristantarrant** [comment]
Hell just froze over

**Comment by anistor** [comment]
let me add some more to this pr.

**Comment by anistor** [comment]
Ready now.

**Comment by slaskawi** [comment]
Looks good - pulling

**Comment by slaskawi** [comment]
Integrated. Thanks @anistor

**Pull request closed without merging**
