### PR TITLE
ISPN-9339 Update to Jackson 2.9.5

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-9339

### CODE REVIEW

**Comment by tristantarrant** [comment]
Nice one. Thanks

**Comment by gustavonalle** [comment]
Reopening, since it was not merged

**Comment by gustavonalle** [comment]
Rebased

**Comment by johnou** [comment]
@gustavonalle Jackson 2.9.6 is out.

**Comment by gustavonalle** [comment]
Thanks @johnou, I was aware of that version, it'll be updated in a future PR

**Pull request merged**
