### PR TITLE
[14.0.x] ISPN-15092 Apache SSHD 2.10.0

### PR DESCRIPTION
**Pull request by pminz**
https://issues.redhat.com/browse/ISPN-15092

### CODE REVIEW

**Comment by ryanemerson** [comment]
@pminz Before we merge this we need a PR issued against the `main` branch. All PRs must be issued against `main` first to ensure that there are no regressions between the stable and development branch.

**Comment by tristantarrant** [comment]
I'm thinking we should upgrade both `main` and `14.0.x` to Elytron `2.2.1.Final` which no longer has a dependency on sshd and is the basis for EAP 8, so extremely long support

**Comment by tristantarrant** [comment]
> I'm thinking we should upgrade both `main` and `14.0.x` to Elytron `2.2.1.Final` which no longer has a dependency on sshd and is the basis for EAP 8, so extremely long support

I apologize, I discovered that Elytron 2.2.1.Final still depends on sshd-common in other areas, so my statement is false

**Comment by pminz** [comment]
I will issue a PR against the main branch to upgrade sshd.

**Comment by pruivo** [comment]
merged! thanks @pminz !

**Pull request merged**
