### PR TITLE
ISPN-9828 Server defaults missing for UFC_NB and MFC_NB

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9828

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please
cs

**Comment by diegolovison** [comment]
run performance tests please
cs

**Comment by diegolovison** [comment]
run performance tests please
cs

**Comment by danberindei** [comment]
Performance looks good. Non-tx reads (both repl and dist) are still about 5% slower than the 7.2 baseline, but no messages are sent in those scenarios so it's probably from the server itself.

**Pull request merged**
