### PR TITLE
[13.0.x] ISPN-13664 Deadlock on closing of PersistenceManagerImpl

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-13664

### CODE REVIEW

**Comment by danberindei** [comment]
Please update this and #9847 with the latest changes from the main branch, Will.

**Comment by wburns** [comment]
Rebased and updated cherry pick with changes from main.

**Comment by wburns** [comment]
Updated with commit from https://github.com/infinispan/infinispan/commit/9439bd29025074692d531c7f295a02e22f7eefbd

**Comment by danberindei** [comment]
Merged, thanks Will!

**Pull request merged**
