### PR TITLE
[13.0] ISPN-14103 Use supplied security provider to load keystore and init key/trust managers

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14103 Use supplied security provider to load keystore and init key/trust managers
https://issues.redhat.com/browse/ISPN-14114 Fix TLS 1.3 with cipher suites

### CODE REVIEW

**Comment by jabolina** [comment]
@tristantarrant  there is a failure in CI.

**Comment by tristantarrant** [comment]
Once https://github.com/infinispan/infinispan/pull/10281 is merged, I'll update this

**Comment by tristantarrant** [comment]
CI is ok

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
