### PR TITLE
ISPN-15262 IndexedTests can fail on clear due to blocking call

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-15262

### CODE REVIEW

**Review by fax4ever — APPROVED** [review]
I tested locally.
It seems using the current main code is it possible that a non-blocking thread can execute the `BlockingFlowableIterable$BlockingFlowableIterator#onNext` frame. While with the patch only JGroups or non-blocking Infinispan thread can execute it.
+1 to merge as soon as the CI looks good

**Comment by fax4ever** [comment]
@wburns shall we backport it?

**Comment by wburns** [comment]
> @wburns shall we backport it?

Yes, I have added the tag.

**Comment by fax4ever** [comment]
I found this log on CI:

``` bash
18:02:27  [TestSuiteProgress] Test failed: org.infinispan.persistence.sql.TableJdbcStoreFunctionalTest.testReloadWithEviction\[SQLITE, transactionalCache\=true, transactionalStore\=false\]
18:02:27  Dumping threads of process 3080429 to /home/infinispan/workspace/Infinispan_PR-11433/persistence/sql/threaddump-TableJdbcStoreFunctionalTest-20231025-1202-3080429.log
18:02:27  Interrupted thread testng-TableJdbcStoreFunctionalTest (32).
18:02:27  Killed processes 3080429
```

I restarted it

**Comment by wburns** [comment]
> I found this log on CI:
> 
> ```shell
> 18:02:27  [TestSuiteProgress] Test failed: org.infinispan.persistence.sql.TableJdbcStoreFunctionalTest.testReloadWithEviction\[SQLITE, transactionalCache\=true, transactionalStore\=false\]
> 18:02:27  Dumping threads of process 3080429 to /home/infinispan/workspace/Infinispan_PR-11433/persistence/sql/threaddump-TableJdbcStoreFunctionalTest-20231025-1202-3080429.log
> 18:02:27  Interrupted thread testng-TableJdbcStoreFunctionalTest (32).
> 18:02:27  Killed processes 3080429
> ```
> 
> I restarted it



> I found this log on CI:
> 
> ```shell
> 18:02:27  [TestSuiteProgress] Test failed: org.infinispan.persistence.sql.TableJdbcStoreFunctionalTest.testReloadWithEviction\[SQLITE, transactionalCache\=true, transactionalStore\=false\]
> 18:02:27  Dumping threads of process 3080429 to /home/infinispan/workspace/Infinispan_PR-11433/persistence/sql/threaddump-TableJdbcStoreFunctionalTest-20231025-1202-3080429.log
> 18:02:27  Interrupted thread testng-TableJdbcStoreFunctionalTest (32).
> 18:02:27  Killed processes 3080429
> ```
> 
> I restarted it

I really can't see how this would be related. The TableJDBC store does not use iterator on cache stream at all and is non blocking.

**Comment by wburns** [comment]
But the more I think about this, I think offloading to a blocking thread is probably overkill. Looking at the code more closely, I believe just adding a simple blockhound exclusion for `BlockingFlowableIterable$FlowableSubscriber#signalConsumer` should be fine as the lock is only held for a very short time.

**Comment by fax4ever** [comment]
> But the more I think about this, I think offloading to a blocking thread is probably overkill. Looking at the code more closely, I believe just adding a simple blockhound exclusion for `BlockingFlowableIterable$FlowableSubscriber#signalConsumer` should be fine as the lock is only held for a very short time.

For blocking operations (like mass-indexing) I think it was not an issue to using blocking threads. From my understanding the problem is when the operations are intrinsically non-blocking (for instance the TableJDBC store).

What you think if we introduced two kind of `AbstractCacheBackedSet` one for blocking calls and another non-blocking ones?

**Comment by wburns** [comment]
> > But the more I think about this, I think offloading to a blocking thread is probably overkill. Looking at the code more closely, I believe just adding a simple blockhound exclusion for `BlockingFlowableIterable$FlowableSubscriber#signalConsumer` should be fine as the lock is only held for a very short time.
> 
> For blocking operations (like mass-indexing) I think it was not an issue to using blocking threads. From my understanding the problem is when the operations are intrinsically non-blocking (for instance the TableJDBC store).
> 
> What you think if we introduced two kind of `AbstractCacheBackedSet` one for blocking calls and another non-blocking ones?

No, I don't think it is worth it at all. You are mixing issues. The blocking call here is solely from a response that has nothing to do with the calling code. The blocking is a very short lived ReentrantLock acquire call that can be safely ignored in our case.

The TableJDBC should make no difference as I mentioned this only affects distributed cache stream iterator calls which are not used at all with that store. If it is failing it is an issue with the test itself.

**Comment by fax4ever** [comment]
> The blocking is a very short lived ReentrantLock acquire call that can be safely ignored in our case.

at this point I agree that delegate it to a blocking thread would be an overkill :)

**Comment by fax4ever** [comment]
Merged, thank you @wburns

**Pull request merged**
