### PR TITLE
ISPN-6159 Remove deprecated continuous query API

### PR DESCRIPTION
**Pull request by anistor**
Jira: https://issues.jboss.org/browse/ISPN-6159

### CODE REVIEW

**Comment by slaskawi** [comment]
The code looks fine to me but could you please add JIRAs (or rename ISPN-6159 into more general name) to all the things you remove?

**Comment by anistor** [comment]
I squashed the commits and changed the title of the jira and updated description to specify what gets removed.

**Comment by slaskawi** [comment]
Pulling

**Comment by slaskawi** [comment]
Integrated thanks!

**Pull request closed without merging**
