### PR TITLE
ISPN-8344 DSL queries filtering only on type are always executed with…

### PR DESCRIPTION
**Pull request by anistor**
…out index

https://issues.jboss.org/browse/ISPN-8344

### CODE REVIEW

**Comment by gustavonalle** [comment]
Retriggering CI

**Comment by gustavonalle** [comment]
@anistor There's on suspect test failure:  

org.infinispan.server.test.query.RemoteQueryCompatModeIT.testCompatQuery(RemoteQueryCompatModeIT.java:94)

**Comment by gustavonalle** [comment]
The job failed in CI for some reason and there are no test results available, but scrolling at the logs I can see the same failure

**Comment by gustavonalle** [comment]
Tests should be fixed by integrating https://github.com/infinispan/infinispan/pull/5498

**Comment by danberindei** [comment]
The elasticsearch failures in the latest build are because the agent ran out of memory, integrating.

    [2017-10-05T11:09:51,273][INFO ][o.e.n.Node ] version[5.5.0], pid[14372], build[260387d/2017-06-30T23:16:05.735Z], OS[Linux/3.10.0-514.26.2.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_144/25.144-b01]
    Oct  5 11:10:43 infinispan-ci-slave-3 kernel: Killed process 14372 (java) total-vm:4729644kB, anon-rss:2295436kB, file-rss:0kB, shmem-rss:0kB

**Pull request merged**
