### PR TITLE
ISPN-6027 Use bundler sender-sends-with-timer by default

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-6027

### CODE REVIEW

**Comment by pruivo** [comment]
@danberindei should I integrate this? and when Bela removes it, we update the config again.

**Comment by danberindei** [comment]
Yes, let's integrate it @pruivo

**Comment by pruivo** [comment]
ack, testing and pushing...

**Comment by pruivo** [comment]
integrated! thanks @danberindei !

**Pull request closed without merging**
