### PR TITLE
[DO NOT INTEGRATE] testing with max active of 1

### PR DESCRIPTION
**Pull request by wburns**

### CODE REVIEW

**Comment by wburns** [comment]
run performance tests please
cs-hotrod

**Comment by wburns** [comment]
run performance tests please
cs-hotrod

**Comment by wburns** [comment]
run performance tests please
cs-hotrod

**Comment by diegolovison** [comment]
run performance tests please
cs-hotrod

**Comment by wburns** [comment]
Latest perf numbers actually showed a decrease in performance (I hard coded it to 1 instead of setting config). My guess is that the radar gun test was overriding the value. This should be abandoned until we can look into it further. My guess is we would need to limit work done while holding the channel to do this.

**Pull request closed without merging**
