### PR TITLE
ISPN-14991 Eliminate stream from getEncoder

### PR DESCRIPTION
**Pull request by marschall**
Eliminate stream creation in EncoderRegistryImpl.getEncoder.

https://issues.redhat.com/browse/ISPN-14991

### CODE REVIEW

**Comment by tristantarrant** [comment]
Thanks. Could you please rebase it against the latest main ?

**Comment by marschall** [comment]
> Thanks. Could you please rebase it against the latest main ?

Done

**Comment by pruivo** [comment]
merged! thanks @marschall !

**Comment by marschall** [comment]
Thanks for merging so quickly!

**Pull request merged**
