### PR TITLE
ISPN-5243 Configuration Value wrappers

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5243

### CODE REVIEW

**Comment by galderz** [comment]
Needs rebasing

**Comment by tristantarrant** [comment]
Done

**Comment by danberindei** [comment]
@tristantarrant I kind of liked the idea that looking up the value of a setting meant just traversing a chain of references, removing the need to cache individual settings in various components. So I was expecting you to keep the individual fields, and only use the set of attributes for generic stuff like the XML parser or `equals()`. Speaking of which, could you add a bit of javadoc to the Attribute/AttributeDefinition/AttributeSet classes?

**Comment by tristantarrant** [comment]
@danberindei ok for the javadocs.

**Comment by tristantarrant** [comment]
@danberindei having the individual fields would not be enough, since you would need to still have some metadata for that field (at least "modified" and "default"), and you couldn't do it with primitives or their wrappers. However the idea of making an AttributeSet point to a parent so that the chain you suggest can be implemented is appealing. The only concern I have is that I can do the following:
c3 = builder.read(c1).read(c2).....build();
then which chain should I follow ?

**Comment by danberindei** [comment]
@tristantarrant I just meant that having to lookup a key in a map every time we look at a setting's value is kind of heavy, so I would have liked concrete `Attribute` fields in the configuration objects. I'm not sure how much caching we do now, but I think there are quite a few settings we look up multiple times for each cache operation.

**Comment by tristantarrant** [comment]
Aha, I get it now. Yes that sounds like a good idea. Let me close this PR and experiment

**Pull request closed without merging**
