### PR TITLE
ISPN-7356 Random TimeoutExceptions on query suite

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-7356

### CODE REVIEW

**Comment by gustavonalle** [comment]
After a couple of CI runs, the errors are not happening anymore, so good to go!

**Comment by Sanne** [comment]
do you have an explanation?

**Comment by gustavonalle** [comment]
@Sanne No. I noticed the failures appeared after we stopped applying the DONT_BUNDLE flag on core, so I basically got rid of bundling altogether on tests.

**Comment by Sanne** [comment]
thanks. Looks like there's a problem with the bundlers then? Or at least how Infinispan is using them? @belaban @danberindei

**Comment by gustavonalle** [comment]
in the JIRA there is a TRACE for jgroups + infinispan in one of the failures, in case someone wants to take a deeper look.

**Comment by anistor** [comment]
I've merged it. Could not stand those failures anymore :). Thanks @gustavonalle !

**Comment by Sanne** [comment]
thanks @anistor I was about to do the same :)

Still let's not sweep mistakes under the carpet. @danberindei @belaban we might have a problem with the bundler implementation?

Since it's causing a timeout in a not so stressing test (it's not a benchmark) I think we might be on a bug r rather than a mere performance inefficiency.

**Comment by gustavonalle** [comment]
@Sanne is right, this is far from being stressful: it uses small cluester (mostly with 3 nodes) with very few entries (< 10). Those caches use indexes stored on extra caches, and it relies (mostly) on SYNC RPCs and custom commands.

**Pull request closed without merging**
