### PR TITLE
ISPN-11100 Rename org.infinispan.server.loader.Loader to InfinispanServerLoader

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.redhat.com/browse/ISPN-11100

### CODE REVIEW

**Comment by tristantarrant** [comment]
Can't you use `jps -l` and use the fqcn ?

**Comment by diegolovison** [comment]
Yes. I found it later but it "seems" good have the name in jps command. If not, we can close the PR. No problem

**Comment by tristantarrant** [comment]
Actually, to be able to distinguish it from other uses of the Loader (CLI, user tool, etc), you will still need to also invoke `jps -m` because otherwise they all look the same.

**Comment by tristantarrant** [comment]
Closing this PR, but I'd love to see the issue reworked to provide a guide for debugging, especially in connection with what is provided in https://github.com/infinispan/infinispan-images/pull/34.
@oraNod can you pick this up ?

**Comment by oraNod** [comment]
@tristantarrant ack

**Pull request closed without merging**
