### PR TITLE
[8.2.x] ISPN-9701 TransactionTable does not shutdown gracefully

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9701

### CODE REVIEW

**Comment by wburns** [comment]
I am guessing all those test failures are unrelated @danberindei ?

**Comment by danberindei** [comment]
@wburns https://github.com/infinispan/infinispan/pull/6492 should fix the ITs

**Comment by wburns** [comment]
@danberindei can you rebase, and assuming it has those same ~60 failures I am fine with integrating

**Comment by danberindei** [comment]
Forgot about this one... rebased @wburns

**Comment by wburns** [comment]
Integrated into 8.2.x, thanks @danberindei !

**Pull request merged**
