### PR TITLE
ISPN-14709 REST API: /v2/security/principals

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14709

### CODE REVIEW

**Review by ryanemerson — DISMISSED** [review]

**Comment by karesti** [comment]
@dpanshug could you check the json here is what we need for the console please ?

**Comment by dpanshug** [comment]
Using CLI I've created a principal `test` with roles `observer, monitor`. 

```
[fedora-5917@cluster//containers/default]> user roles grant --roles=observer,monitor test
[fedora-5917@cluster//containers/default]> user roles ls test
["observer","monitor"]
```

But not able to fetch it via this Rest API.
```
[dipanshu@fedora ~]$ curl http://localhost:11222/rest/v2/security/principals --digest -u admin:password
{"default:properties":["observer","admin","monitor"]}
```

**Comment by tristantarrant** [comment]
> Using CLI I've created a principal `test` with roles `observer, monitor`.
> But not able to fetch it via this Rest API.
Added a reload just before iterating the entries. It should fix this issue.

> Also, I'm not able to understand `default:properties` meaning. Will be helpful if this API can provide a list of principals with their roles assigned.

The json map is keyed by "realmname:providername". If you have more realms/providers, it will return them all

As for returning roles, this may be cheap for properties, but may be prohibitively expensive for LDAP. I'll see what it means.

**Comment by dpanshug** [comment]
> Added a reload just before iterating the entries. It should fix this issue.

Still, the issue persists. Returns the same output `{"default:properties":["admin"]}` when created principal named `test`

`user roles ls 'principal'` displays only roles inside a principal ([link](https://infinispan.org/docs/stable/titles/cli/cli.html#synopsis_43)), maybe we also need a CLI command to list all principals.

**Comment by tristantarrant** [comment]
> > Added a reload just before iterating the entries. It should fix this issue.
> 
> Still, the issue persists. Returns the same output `{"default:properties":["admin"]}` when created principal named `test`

It works for me. Make sure you're on the right commit hash and you've correctly recompiled the server

> 
> `user roles ls 'principal'` displays only roles inside a principal ([link](https://infinispan.org/docs/stable/titles/cli/cli.html#synopsis_43)), maybe we also need a CLI command to list all principals.

Yes, I'm going to add that

**Review by dpanshug — DISMISSED** [review]

**Comment by ryanemerson** [comment]
> > `user roles ls 'principal'` displays only roles inside a principal ([link](https://infinispan.org/docs/stable/titles/cli/cli.html#synopsis_43)), maybe we also need a CLI command to list all principals.
> 
> Yes, I'm going to add that

@tristantarrant Are you adding this as part of this PR?

**Comment by tristantarrant** [comment]
Yeah, I'll do that

**Comment by tristantarrant** [comment]
Added `server principals ls`

**Comment by karesti** [comment]
@dpanshug how is this looking now?

**Comment by dpanshug** [comment]
> @dpanshug how is this looking now?

It's working fine, both API and CLI :heavy_check_mark:

**Review by karesti — APPROVED** [review]

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
