### PR TITLE
add example.PROTOBUF_DIST to the server default caches enum

### PR DESCRIPTION
**Pull request by karesti**

### CODE REVIEW

**Comment by tristantarrant** [comment]
I don't want to add "example" templates to the enum, because otherwise they will be used in production environments which I want to avoid (hence the "example" naming=

**Comment by karesti** [comment]
ok, how can we help for users ? because the templates there are not usable from the console

**Comment by danberindei** [comment]
@karesti IMO the console should not use the enum values, instead it should use a REST API (which may or may not exist now) to fetch all the available configuration (templates only? @tristantarrant) from the server

**Comment by karesti** [comment]
> @karesti IMO the console should not use the enum values, instead it should use a REST API (which may or may not exist now) to fetch all the available configuration (templates only? @tristantarrant) from the server

the enum is for hotrod.

the console uses an endpoint

**Comment by karesti** [comment]
my comment about the console @danberindei  is because the problem I came into has been using the DIST template from a hot rod example, and thenbeing unable to perfom a get from the console to this cache (in the infinispan server tutorial)

**Comment by gustavonalle** [comment]
You should create the cache with the proper encoding types instead of relying on those templates

**Comment by gustavonalle** [comment]
https://github.com/infinispan/infinispan/blob/eab7715afefd447319290df099b3f0c60326c353/client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminStandaloneTest.java#L27-L29

**Comment by karesti** [comment]
> https://github.com/infinispan/infinispan/blob/eab7715afefd447319290df099b3f0c60326c353/client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminStandaloneTest.java#L27-L29
> 
> REST is:
> 
> ```
> curl -u user:user 
>     -H "Content-Type: application/json" 
>     -d '{"distributed-cache":{"mode":"SYNC","encoding":{"media-type":"application/x-protostream"}}}'  
>     http://127.0.0.1:11222/rest/v2/caches/myCache 
> ```

yes, but this is not a good user experience for the first time you use infinispan in a tutorial.
having some pre-configured and usable templates in the server and used from hotrod for learning is not very expensive and is good for learning and getting started.

**Comment by karesti** [comment]
@tristantarrant @oraNod WDYT ? question above

**Comment by karesti** [comment]
@gustavonalle I know how to create caches in XML, this is not the point. The point is helping users getting started , providing some templates that work for them easily without copy/pasting an XML file and using that API. Where is the problem about what I'm pretending to do here? I might be missing something

**Comment by gustavonalle** [comment]
> I know how to create caches in XML

I know that you know :smile: I was merely giving options for the tutorial to have the cache correctly created :)

**Comment by gustavonalle** [comment]
> Where is the problem about what I'm pretending to do here?

Btw, I didn't understand why the template needs to be in an enum in the Hot Rod client?

**Comment by danberindei** [comment]
@karesti the problem is that once we can't create an enum value for all the possible configurations.

I agree that the current XML configuration required to get a protostream cache on the server is kind of involved, but I'd rather try to improve the experience of using an XML configuration (or even allow JSON/YAML) so the user can do something like this:

```
RemoteCache<?, ?> cache = remoteCacheManager.administration().createCache("cache", new XMLStringConfiguration("<distributed-cache/>")); 
```

@gustavonalle I'm a bit confused, you say the cache should have the correct encoding set instead of relying on the templates, but your example doesn't set the encoding either. Is it because the encoding is no longer necessary in master?

**Comment by gustavonalle** [comment]
> Is it because the encoding is no longer necessary in master?

No, because I took a snippet that doesn't contain the encoding just to illustrate the idea :)

**Comment by gustavonalle** [comment]
@karesti 

In the tutorial, it is already doing this: 
```
return remoteCacheManager.administration().getOrCreateCache("temperature", "example.PROTOBUF_DIST");
```

So the value in the enum is to aid code complete?

**Comment by gustavonalle** [comment]
> the problem is that we can't create an enum value for all the possible configurations. 

Yes, plus once added to the API it becomes public, and we need to go through the deprecation cycles. That template was just a stop gap solution to be able to query a cache from the console, and should not allow it to spread

**Comment by karesti** [comment]
> So the value in the enum is to aid code complete?

The thing is that I can't even perform a "get" from the console, not related to query

Yes, I would like something that helps with an enum that refers to the templates that are already shipped by the server

**Comment by karesti** [comment]
> Yes, plus once added to the API it becomes public, and we need to go through the deprecation cycles. That template was just a stop gap solution to be able to query a cache from the console, and we should not allow it to spread

I would like to define some templates that can help the user. Maybe this template is not a good naming, we should probably chose a better name. But using the DIST template from hotrod, I could not get any value from the console (simple get key). Maybe I should run my tests again but I was very confused when I was doing the tutorial about this fact

**Comment by gustavonalle** [comment]
> The thing is that I can't even perform a "get" from the console, not related to query

Using multiple clients together will not always work out of the box, at least the encoding need to be set. 

https://infinispan.org/docs/stable/titles/developing/developing.html#endpoint_interop

> I would like to define some templates that can help the user

There are too many combinations. Also, be aware that the templates will be most useless when we migrate to Hibernate 6 and query requires to configure the indexed entities ahead of time

**Comment by danberindei** [comment]
> I would like to define some templates that can help the user.

I know that's the goal, but I'm afraid the predefined templates are complicating our life too much compared to what the users gain.

If all we had was an example in the documentation saying "this is how you define a DIST cache on the server", we could have updated the example to include `<encoding media-type="application/x-protostream"/>` and be done with it.

But because we have defined an `org.infinispan.DIST_SYNC` template to make it easier for the users, we can't just update the template, or it will break existing users when upgrading. So we have to invent another template for a DIST cache w/ protostream, then another template for REPL + protostream + indexing, and so on. And new users will STILL see the `DefaultTemplate.DIST_SYNC` enum value and try to use that.

**Comment by karesti** [comment]
@danberindei  If there is any chance someone using that template, and upgrades to Infinispan 12 and protostream is used, those users that are probably advances users at that point, can create and use their own template without marshalling in case something is  breaking.  I do't think w need to maintain those templates intact. Since the enum was introduced late in 11, I highly doubt there will be super hard breaks of users who might be using them, which is unlikely the case TBH. 

There might be a high number of combinations, no doubt, but there must be something that covers a bunch of general cases without covering corner cases or advance use cases. In that case, yes, users need to define their templates or caches exactly as they need them, to meet their requirements. What I think it's not great at all is making users start the server, and creating XML templates to use the API we have right now in a getting started, wthout simply providing a easy way to create some remplicated, invalidated and so on, caches that can help them start for learning

**Comment by karesti** [comment]
@gustavonalle right, but you know most users are using java or JVM. I'm not pretending to create templates that work in every case, but something that help users start and understand, before getting into how to define all the options of a cache. 
Some templates covering different types of caches that can be indexed, with stats activated etc. So the hotrod start is easier and things work on REST smoothly a well. Something that will cover many cases, at least to start and  learn. 
Of course, I'm planning evolving the console to have a cache creation wizard. But the getting started from infinispan server is the hotrod client right now.

**Comment by gustavonalle** [comment]
@karesti I understand your point of view, I am just saying that templates don't scale and will not be able to cover indexing in infinispan 12, since the config will require entities to be declared upfront. Regarding the enum, I wouldn't do it since you are already using the template name as a String, but it's really @tristantarrant that needs convincing :)

**Comment by karesti** [comment]
@gustavonalle I don't care adding or not this value in the enum. I really think having a referential of what exists in the server in a enum it's nice for hotrod, instead of trying to find a string value from somewhere. I don't care about adding this particular value to the enum; moreover, probably it should be renamed since it's called example. Or maybe we should have some "example" templates that evolve over time (with hibernate or not). I just want us to make something for users, specially beginners, and specially for all the get started simple tutorials, integration tutorials (SB, Quarkus, Vertx...) in general with hotrod. Of course, we already have a tutorial on "how to create caches with a particular configuration", over time this can get better as well (and the console "create cache" wizard)

**Comment by tristantarrant** [comment]
I'm closing this

**Pull request closed without merging**
