### PR TITLE
ISPN-12598 Hot Rod java client retries too many times

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.redhat.com/browse/ISPN-12598

### CODE REVIEW

**Comment by wburns** [comment]
@diegolovison This should have a separate JIRA with what the issue is described as the one mentioned was closed a while back and seems unrelated.

**Comment by wburns** [comment]
There is a build failure, otherwise seems fine as I didn't realize it was only test changes.
```
11:50:41  [ERROR] /home/infinispan/workspace/Infinispan_PR-9659/server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestServer.java:9:8: Unused import - org.testcontainers.DockerClientFactory. [UnusedImports]
```

**Comment by diegolovison** [comment]
I am investigating `org.infinispan.server.extensions.PojoMarshalling.testPojoMarshalling`

**Comment by wburns** [comment]
Integrated into main, thanks @diegolovison !

**Comment by danberindei** [comment]
@diegolovison the test failed in a couple of later PR builds with no related changes:

```
java.lang.AssertionError
	at org.infinispan.server.resilience.ResilienceMaxRetryIT.testMaxRetries0(ResilienceMaxRetryIT.java:64)
```

https://ci.infinispan.org/job/Infinispan/job/PR-9809/1/testReport/org.infinispan.server.resilience/ResilienceMaxRetryIT/testMaxRetries0/

Looking at the code, you have

```java
assert i == 0 || i == 1 || i == 2;
```

but the comment above actually says that such an assert may fail:

```
// more than 2 is highly unlikely, but it might happen because the probability is not 0"
```

A few more comments:
1. The test took 1min 23s to fail, and a successful run in the PR build took 3min 46s to pass. This is really long for a single test, testing only one (and pretty obscure, since we don't encourage max-retries=0) scenario. The test should set up the client with much lower connection/socket timeouts.
2. The comments in the code mention port1, port2, port3 a lot, but the test always uses the container driver, and the container driver uses the same port with different ip addresses (172.17.0.3:11222, 172.17.0.4:11222, 172.17.0.5:11222).
3. I don't see a reason to use the container driver here, AFAICT the embedded server driver would work just as well and it should also speed up the test. When a process stops listening to a port, the IP address is still active, and the OS responds to attempts to connect to the closed port with a RST (connection reset) flag, so the client retries (or gives up) immediately. When you kill a container, the IP address of the server "vanishes", and the client doesn't get any response to its connection attempts, so it has to wait for the connection timeout to expire.

**Comment by diegolovison** [comment]
Ok. Let me take a look again

**Pull request merged**
