### PR TITLE
ISPN-11535 Remove Transitive Dependencies

### PR DESCRIPTION
**Pull request by pruivo**
~for testing purposes...~
https://issues.redhat.com/browse/ISPN-11535

### CODE REVIEW

**Comment by ryanemerson** [comment]
LGTM, are we waiting on anything or is this Ok to be merged?

**Comment by pruivo** [comment]
I'm waiting for @tristantarrant green light :)

**Comment by ryanemerson** [comment]
@tristantarrant Seems like we need your input here

**Comment by tristantarrant** [comment]
LGTM

**Comment by wburns** [comment]
@pruivo if you rebase I would love to integrate this.

**Comment by pruivo** [comment]
@wburns done! thanks!
Let CI run first...

**Comment by wburns** [comment]
Integrated into master, thanks @pruivo !

**Pull request merged**
