### PR TITLE
ISPN-13318 Sql Store jar is not included in server distribution

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-13318

### CODE REVIEW

**Comment by tristantarrant** [comment]
Unfortunately the `infinispan-cachestore-sql` artifact has two unwanted dependencies on JDBC drivers which are therefore being pulled into the server itself:
```
INFO] +- com.ibm.db2:jcc:jar:11.5.6.0:compile
[INFO] +- com.microsoft.sqlserver:mssql-jdbc:jar:9.4.0.jre11:compile
```
These should have the `test` scope. Additionally versions should be extracted to properties in the root `pom.xml`

**Review by tristantarrant — CHANGES_REQUESTED** [review]
see comment

**Comment by wburns** [comment]
> Unfortunately the `infinispan-cachestore-sql` artifact has two unwanted dependencies on JDBC drivers which are therefore being pulled into the server itself:
> 
> ```
> INFO] +- com.ibm.db2:jcc:jar:11.5.6.0:compile
> [INFO] +- com.microsoft.sqlserver:mssql-jdbc:jar:9.4.0.jre11:compile
> ```
> 
> These should have the `test` scope. Additionally versions should be extracted to properties in the root `pom.xml`

Oh weird, these were test before. Let me fix that.

**Comment by wburns** [comment]
> Additionally versions should be extracted to properties in the root `pom.xml`

The reason I hadn't done this is the others for the jdbc test didn't define this. I can update all of them.

**Comment by wburns** [comment]
Updated to remove versions and make sure scopes are correct.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
