### PR TITLE
ISPN-6491 Remove total order thread pool

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.jboss.org/browse/ISPN-6491

### CODE REVIEW

**Comment by slaskawi** [comment]
Shouldn't we mention in the docs that we are deprecating this? That's the only bit I'm missing in this PR, otherwise looks ok to me.

**Comment by pruivo** [comment]
@slaskawi where should I mention it? 
the thread pool was deprecated (and no longer used) since 7.1. I just left the configuration and parser, that is removed in this PR.

**Comment by wburns** [comment]
@pruivo I normally mention changes like this at https://github.com/infinispan/infinispan/blob/master/documentation/src/main/asciidoc/upgrading/upgrading.adoc

**Comment by slaskawi** [comment]
@wburns Yes, that's exactly what I mean

**Comment by pruivo** [comment]
done!

**Comment by danberindei** [comment]
Integrated, thanks Pedro!

**Pull request closed without merging**
