### PR TITLE
[14.0] ISPN-14737 SoftIndexFileStore Index can become corrupted

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-14737
https://issues.redhat.com/browse/ISPN-14753

### CODE REVIEW

**Comment by pruivo** [comment]
@wburns it is failing to compile.

**Comment by wburns** [comment]
> @wburns it is failing to compile.

Fixing now, must have been a cherry-pick conflict I didn't notice.  I was mostly concentrating on main last night :)

**Comment by wburns** [comment]
Should be fixed now, failure was because cherry-pick had an extra line to set the non blocking manager on the blocking manager. This was only added in main for the new scheduled blocking stuff added for indexing, so it wasn't present in 14.0.x.

**Comment by pruivo** [comment]
Tested locally.
Merged. thanks @wburns !

**Pull request merged**
