### PR TITLE
ISPN-5833 ModuleCommandExtensions should not expose deprecated type E…

### PR DESCRIPTION
**Pull request by Sanne**
…xtendedModuleCommandFactory

https://issues.jboss.org/browse/ISPN-5833

### CODE REVIEW

**Comment by gustavonalle** [comment]
This was attempted in https://issues.jboss.org/browse/ISPN-5601 but it needed to be reverted because of binary compatibility. Not sure what was the issue, @wburns , @rvansa ?

**Comment by rvansa** [comment]
Yep, in order to keep binary compatibility between 7 and 8 for ORM we had to keep that deprecated class :-/

**Comment by wburns** [comment]
Yes, @gustavonalle @Sanne unfortunately we cannot make this change until ISPN 9 :-1: Closing this for now.

**Comment by Sanne** [comment]
> we had to keep that deprecated class

I didn't delete the class. Do you mean you had to keep the interface as-is?

**Comment by wburns** [comment]
@Sanne yes the return type has to stay the same even

**Comment by Sanne** [comment]
ok, thanks.

**Comment by alanfx** [comment]
@wburns or @Sanne, would it be worthwhile to add a comment to the interface about this issue as a warning to other users? It could also state that the class will be removed and the method signature will change in ISPN 9.

**Comment by Sanne** [comment]
Good point @alanfx ! I've pushed a change to add some comments on the SPI.

**Comment by Sanne** [comment]
(see 669d165c0d24286f8ad224ee64114d64be41d47c)

**Comment by alanfx** [comment]
Thanks, @Sanne ! :+1:

**Comment by Sanne** [comment]
It's time for pr #4517 ;-)

**Pull request closed without merging**
