### PR TITLE
ISPN-9849 Server should allocate less when looking up the cache 

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9849

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please
cs-hotrod

**Comment by diegolovison** [comment]
Hi @danberindei It failed because of ISPN-9198.
I will rerun the tests

**Comment by diegolovison** [comment]
run performance tests please
cs-hotrod

**Comment by diegolovison** [comment]
run performance tests please
cs-hotrod

**Comment by danberindei** [comment]
run performance tests please
cs-hotrod

**Comment by danberindei** [comment]
run performance tests please
cs-hotrod

**Comment by danberindei** [comment]
One more try :)

**Comment by diegolovison** [comment]
Well, it seems like Jenkins got the trigger due that you wrote `r u n p e r f o r m a n c e t e s t s p l e a s s`but the comment there was `One more try :)`. Due that it understod that the whole test suite should be running. This is the reason why it is taking time

**Comment by danberindei** [comment]
Sounds like a concurrency issue @diegolovison :)

**Comment by danberindei** [comment]
run performance tests please
cs-hotrod

**Comment by danberindei** [comment]
run performance tests please
cs-hotrod

**Comment by ryanemerson** [comment]
@danberindei I forgot to merge this week ... can you rebase, then I'll merge

**Comment by ryanemerson** [comment]
Thanks @danberindei

**Pull request merged**
