### PR TITLE
Fix Lucene Directory integration tests and improve the modules

### PR DESCRIPTION
**Pull request by Sanne**
I've added a README file in the root of the integration tests, as some changes had been made which make me suspect people didn't understand the purpose of these tests.

Please do not override all components to "align" them blindly among all components: the point of the modules - and hence the modular tests - is not only to verify a sound structure of the module, but also to verify cross-compatibility among the different versions which we expect to be valid combinations in the practical world.

 - https://issues.jboss.org/browse/ISPN-7455
 - https://issues.jboss.org/browse/ISPN-7458

### CODE REVIEW

**Comment by tristantarrant** [comment]
CI reports failures with these:
 query.DSLQueryIT  	
query.ElasticsearchIndexManagerIT  	
query.InfinispanQueryIT

**Comment by Sanne** [comment]
thanks @tristantarrant , I'll check those out. I really need a faster machine :)

**Comment by Sanne** [comment]
The tests are failing (rightfully) because after my changes the "${lucene.slot}" property of the infinispan query module is no longer being filtered correctly.

I can't see how that relates with my changes, however this works fine on master.

**Comment by Sanne** [comment]
I pushed a fix and rebased. Should all work now.

I didn't fully understand the strange behaviour of ANT in this case, but my last commit contains a workaround which seems effective.

**Comment by gustavonalle** [comment]
Thanks, let's wait for CI

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
