### PR TITLE
[10.0.x] ISPN-10862 SpringCache unwrapping NullValue singleton fails with Java…

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-10862-10.0.x

### CODE REVIEW

**Comment by karesti** [comment]
@ryanemerson is the backport needed? did we backport the marshalling stuff ?

**Comment by ryanemerson** [comment]
@karesti This is for 10.0.x :slightly_smiling_face:

**Comment by karesti** [comment]
Sorry I'm out

**Comment by karesti** [comment]
I saw backport and I was like ok this is 9.4.x haha

**Pull request merged**
