### PR TITLE
[8.2.x] ISPN-7235 XSite replication commands should unwrap security from caches

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-7235

### CODE REVIEW

**Comment by danberindei** [comment]
@tristantarrant I assume this needs Pedro's xsite fixes too?
http://ci.infinispan.org/viewLog.html?buildId=45066&buildTypeId=bt9

**Comment by pruivo** [comment]
@danberindei yes

**Comment by tristantarrant** [comment]
Fixed

**Comment by pruivo** [comment]
thanks @tristantarrant

**Pull request merged**
