### PR TITLE
Enable deployment of Infinispan Extension on Wildlfly

### PR DESCRIPTION
**Pull request by ryanemerson**
~https://issues.jboss.org/browse/ISPN-6815~
~https://issues.jboss.org/browse/ISPN-7459~
https://issues.jboss.org/browse/ISPN-7472
https://issues.jboss.org/browse/ISPN-7471

### CODE REVIEW

**Comment by ryanemerson** [comment]
@slaskawi These changes mean that it is possible for a user to download the `wildfly-modules` zip, unpack it in the module dir of their app server and then define the infinispan and jgroups extensions in their standalone/domain.xml config. This allows users to utilise caches across multiple app deployments.

**Comment by ryanemerson** [comment]
@slaskawi Also it is once again possible for cache instances to be injected via [JNDI and `@Resource`](https://github.com/ryanemerson/infinispan/blob/1255224baf8856e5eaf7625092b2fba45d2b5775/server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheAdd.java#L120-L122).

**Comment by ryanemerson** [comment]
@vblagoje FYI a few changes are required to our console to support interacting with infinispan running on widlfly, namely that we need to check that `datagrid-infinispan` subsystem actually exists as this is not guaranteed. I'll issue a PR with the appropriate changes when I get a chance.

**Comment by slaskawi** [comment]
Awesome, thanks a lot @ryanemerson !

**Comment by ryanemerson** [comment]
I've discovered some issues with JGroups class loading, so don't integrate yet.

**Comment by ryanemerson** [comment]
@slaskawi I've resolved the previous problems and updated the `wildfly-modules` documentations in the user guide.

**Comment by ryanemerson** [comment]
Don't integrate until after 9.0 is released.

**Comment by ryanemerson** [comment]
@slaskawi Reopened for 9.1. I have rebased, updated the docs and removed ISPN-6815 and ISPN-7459 as the former has already been integrated and the latter was irrelevant.

**Comment by slaskawi** [comment]
Awesome job @ryanemerson !

**Pull request merged**
