### PR TITLE
[8.0.3] ISPN-5944 Backports to 8.0.x branch

### PR DESCRIPTION
**Pull request by rhusar**
This backports few issues that we need to consume sometimes soon in WF10/EAP7.

Jira
https://issues.jboss.org/browse/ISPN-5944

Backports these 4 issues: ISPN-5858, ISPN-5917, ISPN-5918 and ISPN-5876.

### CODE REVIEW

**Comment by rhusar** [comment]
BTW everything passed locally 

Tests run: 6693, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 356.004 sec - in TestSuite

**Comment by tristantarrant** [comment]
@rhusar ISPN-5876 affects Hibernate ORM 2LC, so I want @galderz and @rvansa to chip in here.

**Comment by rvansa** [comment]
ISPN-5876 does not work well with ORM 5.x, since it's targeted as fix to ORM 4.x. We've discussed with @galderz how to deal with it, and Galder will update ORM to not rely on invalidation mode commit timing (basically forcing pre-ISPN-5876 behaviour). This PR should be integrated only after the fix is in ORM, so that we don't end up in broken ISPN 8.0 master/ORM master.

**Comment by galderz** [comment]
Indeed, as @rvansa indicated an Infinispan 8.0 + ISPN-5876 version requires an ORM upgrade which would come once the PRs for [HHH-10344](https://hibernate.atlassian.net/browse/HHH-10344) have been integrated.

**Comment by rhusar** [comment]
Thanks for the comments and the PR guys!

**Comment by rhusar** [comment]
https://github.com/hibernate/hibernate-orm/pull/1171 still not integrated.

**Comment by rhusar** [comment]
https://github.com/hibernate/hibernate-orm/pull/1171 is now merged.

**Comment by pferraro** [comment]
WildFly is now using 8.1.0.Final, so this backport is no longer necessary for us.

**Comment by rhusar** [comment]
Hooray!

**Pull request closed without merging**
