### PR TITLE
ISPN-9180 Remove compat mode from Remote Query

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-9180

### CODE REVIEW

**Comment by gustavonalle** [comment]
CI liked it

**Comment by anistor** [comment]
Looking...  :mag::mag:

**Comment by gustavonalle** [comment]
@anistor still looking?

**Comment by anistor** [comment]
Merged in master. Thanks @gustavonalle !

**Comment by gustavonalle** [comment]
Thanks @anistor , have a nice holiday! :beach_umbrella:

**Comment by anistor** [comment]
It's raining :(

**Pull request closed without merging**
