### PR TITLE
ISPN-8870 Remove logger inheritance to reduce class metadata

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-8870

This saves about 2MB of metaspace when running the default standalone server.

### CODE REVIEW

**Comment by Sanne** [comment]
Good progress, I'll merge it soon!

But should I mark the issue resolved? There are still more to go apparently:

>    ag -Q "Log extends org"

> lucene/directory-provider/src/main/java/org/infinispan/hibernate/search/logging/Log.java
> 22:public interface Log extends org.infinispan.commons.logging.Log {
> 
> jcache/remote/src/main/java/org/infinispan/jcache/remote/logging/Log.java
> 16:public interface Log extends org.infinispan.jcache.logging.Log {
> 
> jcache/commons/src/main/java/org/infinispan/jcache/logging/Log.java
> 26:public interface Log extends org.infinispan.commons.logging.Log {
> 
> jcache/embedded/src/main/java/org/infinispan/jcache/embedded/logging/Log.java
> 8:public interface Log extends org.infinispan.jcache.logging.Log {
> 
> counter/src/main/java/org/infinispan/counter/logging/Log.java
> 22:public interface Log extends org.infinispan.commons.logging.Log {

**Comment by tristantarrant** [comment]
Right, missed those. Will update it

**Comment by Sanne** [comment]
ok I'll wait then.

**Comment by tristantarrant** [comment]
Updated

**Comment by Sanne** [comment]
I'll guess these two where more complex for some reason?

jcache/embedded/src/main/java/org/infinispan/jcache/embedded/logging/Log.java
8:public interface Log extends org.infinispan.jcache.logging.Log {

jcache/remote/src/main/java/org/infinispan/jcache/remote/logging/Log.java
16:public interface Log extends org.infinispan.jcache.logging.Log {


If it compiles I'll merge it already, we can keep improvements iterative.

**Comment by Sanne** [comment]
merged.

**Pull request closed without merging**
