### PR TITLE
ISPN-7433 Lower default xmit_interval to 100ms

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-7433

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please
library

**Comment by Holmistr** [comment]
run performance tests please
[tcp]
library dist writes

**Comment by Holmistr** [comment]
@danberindei please ignore my last comment, I'm using your PR for testing of the new PerfAck parametrization :)

**Comment by Holmistr** [comment]
run performance tests please
[tcp]
library dist reads

**Comment by Holmistr** [comment]
run performance tests please
[tcp]
library dist reads

**Comment by danberindei** [comment]
run performance tests please
library

**Comment by tristantarrant** [comment]
Looks good

**Comment by danberindei** [comment]
run performance tests please
library

**Comment by jmarkos** [comment]
run performance tests please
library

**Comment by jmarkos** [comment]
run performance tests please
library

**Comment by tristantarrant** [comment]
Pushed to master

**Pull request merged**
