### PR TITLE
ISPN-7382 org.infinispan.test.integration.as.query.ElasticsearchIndex…

### PR DESCRIPTION
**Pull request by anistor**
…ManagerIT fails due to NoClassDefFoundError

https://issues.jboss.org/browse/ISPN-7382

### CODE REVIEW

**Comment by gustavonalle** [comment]
weird. It works for me:

```
$ cd integrationtests/wildfly-modules
$ mvn -Dit.test=ElasticsearchIndexManagerIT install
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.infinispan.test.integration.as.query.ElasticsearchIndexManagerIT

Tests run: 9, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 59.738 sec - in org.infinispan.test.integration.as.query.ElasticsearchIndexManagerIT
```

**Comment by gustavonalle** [comment]
@anistor where is it failing?

**Comment by anistor** [comment]
@gustavonalle  http://ci.infinispan.org/viewLog.html?buildId=48200&tab=buildResultsDiv&buildTypeId=Infinispan_MasterHotspotJdk8

**Comment by anistor** [comment]
@gustavonalle and an older run here: http://ci.infinispan.org/viewLog.html?buildId=48134&tab=buildResultsDiv&buildTypeId=Infinispan_MasterHotspotJdk8

for some reason the failed test appears under the ignored category

**Comment by gustavonalle** [comment]
@anistor ok, I see. The issue is that the failure will only manifest when the elastic cluster fails to form and the branch that calls Assert.fail is followed. 
May I propose a different fix? Change the ```ElasticSearchCluster``` to not depend on testng and instead throw a ```java.lang. AssertionError```?

**Comment by anistor** [comment]
Yes, I like that better. Testng is no longer my friend.

**Pull request merged**
