### PR TITLE
Add a docs index dropdown

### PR DESCRIPTION
**Pull request by tristantarrant**

### CODE REVIEW

**Review by oraNod — APPROVED** [review]
@tristantarrant I like this way better than linking back to the index. I pushed a commit with some suggestions.

**Comment by oraNod** [comment]
I think we should backport this to 13. That branch includes the Developer's Guide still but I still really want to see that guide go away there too so I'm torn if we should add `$('#dchooser').append('<option value="/titles/developing/developing.html">Developer guide</option>');` in the backport.

**Comment by tristantarrant** [comment]
LGTM, and let's backport it as-is

**Comment by oraNod** [comment]
I'll take care of the backport.

**Pull request merged**
