### PR TITLE
ISPN-7851 CLI: Reset the default cache session only if it exists

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-7851

### CODE REVIEW

**Comment by slaskawi** [comment]
Failures seems to be related:
```
org.infinispan.cli.interpreter.InterpreterTest.testDangling
org.infinispan.cli.interpreter.InterpreterTest.testEvict
org.infinispan.cli.interpreter.InterpreterTest.testTx
```

They are not present on master branch: http://ci.infinispan.org/job/Infinispan/job/master/137/

**Comment by tristantarrant** [comment]
Fixed

**Comment by anistor** [comment]
Seems fine.

**Comment by ryanemerson** [comment]
Integrated thanks @tristantarrant

**Pull request merged**
