### PR TITLE
ISPN-10233 Use test JDK to determine vendor for JAAS config file and keytool/vault execution 

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-10233

This is missing the keystore creation using the test JDK

### CODE REVIEW

**Comment by tristantarrant** [comment]
To test this, 
`mvn verify -Dit.test=HotRodKrbAuthIT -pl server/integration/testsuite/`
with OpenJDK 11 to verify that it works by default, then:
```
export JAVA8_HOME=/path/to/ibmj9
mvn verify -Dit.test=HotRodKrbAuthIT -pl server/integration/testsuite/ -Pjava8-test
```

**Comment by danberindei** [comment]
Works for me with OpenJDK11 and with the classic IBM JDK 8, does it need any more changes @tristantarrant?

**Comment by tristantarrant** [comment]
Yeah I still need to ensure that keystore generation is done with the correct JDK

**Comment by tristantarrant** [comment]
@danberindei this should now be ready

**Comment by danberindei** [comment]
Integrated, thanks Tristan!

**Pull request merged**
