### PR TITLE
ISPN-5576 & ISPN-5581

### PR DESCRIPTION
**Pull request by galderz**
https://issues.jboss.org/browse/ISPN-5576
https://issues.jboss.org/browse/ISPN-5581

I've separated the leak problem from the original ISPN-5523 PR into the fix for ISPN-5576. I've also added some logging to the encoder so that it can show any errors, and that's uncovered ISPN-5581, hence why submitting both fixes together.

### CODE REVIEW

**Comment by galderz** [comment]
Adding logging has uncovered an undetected exception. I'm creating a separate JIRA to address this issue:

```
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 04:29:12,353 ERROR (HotRodServerWorker-11-1:) [HotRodEncoder] ISPN005023: Exception encoding message None
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] scala.MatchError: None (of class scala.None$)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.server.hotrod.HotRodEncoder.encode(HotRodEncoder.scala:32)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:681)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:716)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:954)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:243)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.server.hotrod.HotRodDecoder.writeResponse(HotRodDecoder.scala:234)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.server.hotrod.HotRodDecoder.customDecodeHeader(HotRodDecoder.scala:193)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.server.hotrod.HotRodDecoder.org$infinispan$server$hotrod$HotRodDecoder$$decodeHeader(HotRodDecoder.scala:84)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.server.hotrod.HotRodDecoder$$anonfun$decode$1.apply$mcV$sp(HotRodDecoder.scala:47)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.server.hotrod.HotRodDecoder$$anon$1.run(HotRodDecoder.scala:206)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.server.hotrod.HotRodDecoder$$anon$1.run(HotRodDecoder.scala:205)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.security.Security.doAs(Security.java:143)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.server.hotrod.HotRodDecoder.wrapSecurity(HotRodDecoder.scala:205)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.server.hotrod.HotRodDecoder.decode(HotRodDecoder.scala:45)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.server.hotrod.HotRodDecoder.org$infinispan$server$core$transport$StatsChannelHandler$$super$channelRead(HotRodDecoder.scala:31)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.server.core.transport.StatsChannelHandler$class.channelRead(StatsChannelHandler.scala:32)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at org.infinispan.server.hotrod.HotRodDecoder.channelRead(HotRodDecoder.scala:31)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
[08:29:12] :		 [org.infinispan:infinispan-server-hotrod] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by galderz** [comment]
Both fixes are now in and can be reviewed.

**Comment by gustavonalle** [comment]
It seems there are some failures in security tests

**Comment by galderz** [comment]
I've updated the fix for ISPN-5581, it should be fine now.

**Comment by gustavonalle** [comment]
pulling...

**Pull request merged**
