### PR TITLE
Perf exp

### PR DESCRIPTION
**Pull request by tristantarrant**
Having fun with more settings and FRAG3

### CODE REVIEW

**Comment by tristantarrant** [comment]
run performance tests please
library

**Comment by wburns** [comment]
run performance tests please
cs

**Comment by Holmistr** [comment]
@wburns @tristantarrant C/S perf tests tests failed with following error:
`Caused by: java.lang.IllegalArgumentException: frag_size (60000) has to be < TP.max_bundle_size (8700) at org.jgroups.protocols.FRAG2.init(FRAG2.java:108)`

**Comment by tristantarrant** [comment]
run performance tests please
cs

**Comment by jmarkos** [comment]
@tristantarrant what @Holmistr wrote applies for FRAG3, too:
Caused by: java.lang.IllegalArgumentException: frag_size (60000) has to be < TP.max_bundle_size (8700)

**Comment by tristantarrant** [comment]
Sorry, but what configuration is being used to run the server. I've used clustered.xml as packaged with the server itself and it starts up fine

**Comment by tristantarrant** [comment]
We can close this for now

**Pull request closed without merging**
