### PR TITLE
ISPN-7036 Resolve classes properly when Thread context classloader is null

### PR DESCRIPTION
**Pull request by tsegismont**
If TCCL is null, fallback to ISPN classes classloader

### CODE REVIEW

**Comment by slaskawi** [comment]
LGTM

//cc @tristantarrant @danberindei

**Comment by tristantarrant** [comment]
We should probably always use the classloader which has loaded the Infinispan classes and ignore TCCL. Once upon a time the intention was to remove the ability for the user to specify a custom classloader. @galderz @pferraro  wdyt ?

**Comment by tsegismont** [comment]
If the fix is fine with you, I can create a PR for the 8.2.x branch

2016-09-27 9:09 GMT+02:00 Tristan Tarrant <notifications@github.com>:

**Comment by tristantarrant** [comment]
Thanks @tsegismont, pushed to both master and 8.2.x

**Pull request closed without merging**
