### PR TITLE
ISPN-9754 Cache size method should consult Shared cache stores when not

### PR DESCRIPTION
**Pull request by wburns**
async

* Directly ask loader for size when a shared store

https://issues.jboss.org/browse/ISPN-9754

### CODE REVIEW

**Comment by wburns** [comment]
To be honest a large chunk of this PR is just noise around making the AccessMode a predicate to make some methods a bit more flexible.

The real meat is contained in:
1. Actual interceptor changes - https://github.com/infinispan/infinispan/pull/6449/files#diff-d70f5361c5448faaa6e2d954a02b42bbR284
2. Size method via Predicate - https://github.com/infinispan/infinispan/pull/6449/files#diff-d93c51f709416559fc199f2b1687e2f7R774
3. Explicit test - https://github.com/infinispan/infinispan/pull/6449/files#diff-75800b15db75d9791a8459795a87b74fR106

**Comment by wburns** [comment]
Actually this is broken when running in a tx. We could only read the underlying entries in the tx and manually add/subtract. This would still prevent size being an N operation with shared store. This needs to be redone.

**Comment by ryanemerson** [comment]
@wburns NullPointerException on HotRodUpgradeWithStoreTest

**Comment by wburns** [comment]
Thanks! Actually I forgot to add a check for the flag skip cache loader as
well that needs to be added.

**Comment by wburns** [comment]
@ryanemerson weird... the NPE is from something that would have happened before even. Somehow the loaders collection and config collection are out of sync despite holding the read lock for the stores mutex.

**Comment by wburns** [comment]
Aha, wow okay we have a pretty big bug with disabling a store...
https://github.com/infinispan/infinispan/blob/master/core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java#L1186

If you notice it always removes the loader from the status. It should only remove it if the loader matched the type.

**Comment by wburns** [comment]
It seems this bug is in 9.3, 9.4 and 10.0. Crept in with the store availability changes.

**Comment by wburns** [comment]
I created https://issues.jboss.org/browse/ISPN-9773 to fix the NPE.

**Comment by wburns** [comment]
Rebased on the other PR to fix the disable store NPE.

**Pull request merged**
