### PR TITLE
[13.0.x] SIFS fixes

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-14104
https://issues.redhat.com/browse/ISPN-13751
https://issues.redhat.com/browse/ISPN-13387

### CODE REVIEW

**Comment by wburns** [comment]
There are other changes I would like to backport, but unfortunately they are heavily conflicted with the segmentation improvements so I just backported manually the easier ones, including the fix for the NPE.

**Comment by tristantarrant** [comment]
Some SIFS-related failures

**Comment by wburns** [comment]
testParallelIterationWithoutValue – org.infinispan.persistence.SoftIndexFileStoreParallelIterationTest was fixed in [ISPN-14104](https://issues.redhat.com/browse/ISPN-14104)

**Comment by wburns** [comment]
I can try to cherry pick ISPN-14104 to see if it goes in easily enough.

**Comment by wburns** [comment]
Updated to include fix for the unrelated SIFS failure

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
