### PR TITLE
[13.0.x] ISPN-13695 Add migration helper module to fp

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-13695

Backport to 13.0.x of #9968

### CODE REVIEW

**Comment by pruivo** [comment]
it would be nice to have a test using Hot Rod. Probably in `org.infinispan.test.integration.remote.AbstractHotRodQueryIT`

**Comment by fax4ever** [comment]
> it would be nice to have a test using Hot Rod. Probably in `org.infinispan.test.integration.remote.AbstractHotRodQueryIT`

This contribution is supposed to impact only the embedded mode.
The HotRod client already uses Hibernate Search 5 annotations, see for instance `org.infinispan.client.hotrod.query.testdomain.protobuf.KeywordEntity`.

**Comment by pruivo** [comment]
we don't have any tests with Hot Rod inside WildFly, otherwise, this issue was caught way sooner.

**Comment by fax4ever** [comment]
> we don't have any tests with Hot Rod inside WildFly, otherwise, this issue was caught way sooner.

I'm not really sure about the fact that the Hot Rod client needs Hibernate Search dependencies. Does it?

**Comment by pruivo** [comment]
Closing this. Users should move to Hibernate Search 6 annotations.

**Pull request closed without merging**
