### PR TITLE
ISPN-8634 Wildfly 11 fails to start with Infinispan 9.x modules insta…

### PR DESCRIPTION
**Pull request by ryanemerson**
…lled

https://issues.jboss.org/browse/ISPN-8634

### CODE REVIEW

**Comment by danberindei** [comment]
@ryanemerson the discussion in JIRA comments mentions the `org.jboss.sasl` module, but this PR doesn't do anything about it. Maybe the JIRA reference is wrong?

**Comment by danberindei** [comment]
Also, could we expand the `integrationtests/wildfly-modules` to cover the problem?

**Comment by ryanemerson** [comment]
@danberindei The JIRA is slightly behind as it was created before we updated to wildfly 11. The reason that jboss-sasl was missing before, was because wildfly 11 is based upon on Elytron and does not include the jboss-sasl module anymore. Now the issue is that the wildfly-modules were not updated to reflect the CounterManager depdencies as stated in the server feature-pack, resulting in wildfly 11 deployment still failing. 

I have extended InfinispanExtensionIT so that it will fail if either the hotrod or endpoint connectors fail to load for any reason.

**Comment by ryanemerson** [comment]
Failures don't appear related

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
