### PR TITLE
Fixed bug with JCache loader

### PR DESCRIPTION
**Pull request by rchigvintsev**
Hello everyone! Two days ago I posted a [question](http://stackoverflow.com/questions/43679623/classcastexception-in-case-of-configured-read-through-cache-with-some-cache-load) on StackOverflow related to this issue. Nobody answered so I decided to create a pull request because it seems like a bug to me.

### Short description of issue
When JCache loader is configured loaded values are put in place of keys in cache. It causes ClassCastException after calling of javax.cache.Cache.removeAll(). Iteration on cache entires is also broken (javax.cache.Cache.Entry.getKey() returns value instead of key).

### CODE REVIEW

**Comment by tristantarrant** [comment]
@galderz this is for you. In the meantime @rchigvintsev you should create a Jira on https://issues.jboss.rog please

**Comment by rchigvintsev** [comment]
@tristantarrant Done: https://issues.jboss.org/browse/ISPN-7783

**Comment by galderz** [comment]
@rchigvintsev Looks good! Nice catch. I'm going to integrate it but before doing that I'll just simply edit the title to include the JIRA id.

**Comment by galderz** [comment]
Integrated the fix, it should be available in next 9.1.0 alpha and 9.0.x releases.

**Comment by galderz** [comment]
@rchigvintsev If you have time, it'd be great if you could add the test case to the JCache testsuite. Do you think you can do that? That way we guarantee we won't drop the ball next time :). Thx!

**Comment by rchigvintsev** [comment]
@galderz Sure, I'll try to write some tests within the following few days.

**Comment by arkaev** [comment]
Please, cherry-pick it to 8.x versions... It's huge memory leak

**Pull request closed without merging**
