### PR TITLE
ISPN-7396 Improve default bundle size and fragment size

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-7396

### CODE REVIEW

**Comment by tristantarrant** [comment]
CI says: java.lang.IllegalArgumentException: frag_size (8500) has to be < TP.max_bundle_size (8000)

**Comment by danberindei** [comment]
@tristantarrant Yeah, I thought it was the other way around... I wish they could be the same :)

**Comment by danberindei** [comment]
run performance tests please
library

**Comment by tristantarrant** [comment]
It feels like a mistake: why would I ever want a bundle bigger than the fragment size ?

**Comment by tristantarrant** [comment]
Pushed to master

**Comment by danberindei** [comment]
@tristantarrant I think it's because the bundle size accounts for the size of the headers, and FRAG2 doesn't, but I'm not sure.

**Pull request merged**
