### PR TITLE
 ISPN-10136 Spurious dependency cycle detected error 

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-10136
https://issues.jboss.org/browse/ISPN-9979

### CODE REVIEW

**Comment by ryanemerson** [comment]
115 failures :see_no_evil:

**Comment by galderz** [comment]
Indeed many errors, unless this is being addressed soon this PR should probably be closed?

**Comment by danberindei** [comment]
Sorry for the delay, addressing the failures.

The problem was `BasicComponentRegistryImpl.stopWrapper()` wasn't changing the component status to `STOPPED`, and non-volatile components were not reinitialized after a cache.stop() + cache.start().

**Comment by danberindei** [comment]
The 2 remaining failures are unrelated.

**Pull request merged**
