### PR TITLE
ISPN-16809 [RESP] MULTI..EXEC not working with a transactional secure…

### PR DESCRIPTION
**Pull request by jabolina**
https://issues.redhat.com/browse/ISPN-16809

… cache

I've added the `AbstractDelegatingAdvancedCache` marker in the `SecureCacheImpl` and simplified the decorated cache for the EXEC method. Instead of trying to handle the `rewrap` method, we traverse the chain recursively and place the cache at the right spot.

### CODE REVIEW

**Comment by tristantarrant** [comment]
I don't understand why you subclassed the tests to add authz variants: since `RespSingleNodeTest` is already parameterized, why not add authz as another parameter instead ?
Also you named the package `authn` where it should have been `authz` :)

**Comment by jabolina** [comment]
Thanks for the review! I've changed it to use the parameterized option across the tests.

**Comment by tristantarrant** [comment]
A possibly-related CI failure: https://ci.infinispan.org/job/Infinispan/job/PR-13136/4/testReport/junit/org.infinispan.server.resp.dist/TransactionClusteredTest/testBlpopNotBlocking__mode__DIST_SYNC__/

**Comment by jabolina** [comment]
I saw that failure in another PR. I've created https://issues.redhat.com/browse/ISPN-16774 to handle it.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
