### PR TITLE
ISPN-15427 Upgrade JGroups to 5.3.1.Final

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.redhat.com/browse/ISPN-15427

### CODE REVIEW

**Comment by ryanemerson** [comment]
The new JGroups version breaks GraalVM native compilation :slightly_frowning_face:

```java
[2024-01-03T18:39:16.928Z] Fatal error: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: An object of type 'java.net.NetworkInterface' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
[2024-01-03T18:39:16.928Z] This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] You now have two options to resolve this:
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] 1) If it is intended that objects of type 'java.net.NetworkInterface' are persisted in the image heap, add 
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z]     '--initialize-at-build-time=java.net.NetworkInterface'
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'java.net.NetworkInterface' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] 2) If these objects should not be stored in the image heap, you can use 
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z]     '--trace-object-instantiation=java.net.NetworkInterface'
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z]     '--initialize-at-run-time=<culprit>'
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] to prevent the instantiation of the object.
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] If you are seeing this message after enabling '--strict-image-heap', this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
[2024-01-03T18:39:16.928Z] To fix this, include '--initialize-at-build-time=java.net.NetworkInterface' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.
[2024-01-03T18:39:16.928Z] Please address this problem to be prepared for future releases of GraalVM.
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] The following detailed trace displays from which field in the code the object was reached.
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
[2024-01-03T18:39:16.928Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:322)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapInstance.readFieldValue(ImageHeapInstance.java:110)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.onObjectReachable(ImageHeapScanner.java:472)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.heap.SVMImageHeapScanner.onObjectReachable(SVMImageHeapScanner.java:156)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$markReachable$5(ImageHeapScanner.java:452)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$postTask$14(ImageHeapScanner.java:695)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
[2024-01-03T18:39:16.928Z] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
[2024-01-03T18:39:16.928Z] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[2024-01-03T18:39:16.928Z] 	at java.base/java.util.concurrent.ForkJoinPool.externalHelpQuiesce(ForkJoinPool.java:2260)
[2024-01-03T18:39:16.928Z] 	at java.base/java.util.concurrent.ForkJoinPool.helpQuiescePool(ForkJoinPool.java:2297)
[2024-01-03T18:39:16.928Z] 	at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:3565)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:237)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.doTypeflow(PointsToAnalysis.java:529)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.finish(PointsToAnalysis.java:517)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:162)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:783)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:538)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:720)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
[2024-01-03T18:39:16.928Z] Caused by: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: An object of type 'java.net.NetworkInterface' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
[2024-01-03T18:39:16.928Z] This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] You now have two options to resolve this:
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] 1) If it is intended that objects of type 'java.net.NetworkInterface' are persisted in the image heap, add 
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z]     '--initialize-at-build-time=java.net.NetworkInterface'
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'java.net.NetworkInterface' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] 2) If these objects should not be stored in the image heap, you can use 
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z]     '--trace-object-instantiation=java.net.NetworkInterface'
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z]     '--initialize-at-run-time=<culprit>'
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] to prevent the instantiation of the object.
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] If you are seeing this message after enabling '--strict-image-heap', this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
[2024-01-03T18:39:16.928Z] To fix this, include '--initialize-at-build-time=java.net.NetworkInterface' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.
[2024-01-03T18:39:16.928Z] Please address this problem to be prepared for future releases of GraalVM.
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] The following detailed trace displays from which field in the code the object was reached.
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
[2024-01-03T18:39:16.928Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:322)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.getOrCreateImageHeapConstant(ImageHeapScanner.java:212)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.heap.SVMImageHeapScanner.getOrCreateImageHeapConstant(SVMImageHeapScanner.java:109)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapConstant(ImageHeapScanner.java:186)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createFieldValue(ImageHeapScanner.java:364)
[2024-01-03T18:39:16.928Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$createImageHeapInstance$4(ImageHeapScanner.java:294)
[2024-01-03T18:39:16.928Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2024-01-03T18:39:16.928Z] 	... 24 more
[2024-01-03T18:39:16.928Z] Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: An object of type 'java.net.NetworkInterface' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
[2024-01-03T18:39:16.928Z] This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] You now have two options to resolve this:
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z] 1) If it is intended that objects of type 'java.net.NetworkInterface' are persisted in the image heap, add 
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.928Z]     '--initialize-at-build-time=java.net.NetworkInterface'
[2024-01-03T18:39:16.928Z] 
[2024-01-03T18:39:16.929Z] to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'java.net.NetworkInterface' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.
[2024-01-03T18:39:16.929Z] 
[2024-01-03T18:39:16.929Z] 2) If these objects should not be stored in the image heap, you can use 
[2024-01-03T18:39:16.929Z] 
[2024-01-03T18:39:16.929Z]     '--trace-object-instantiation=java.net.NetworkInterface'
[2024-01-03T18:39:16.929Z] 
[2024-01-03T18:39:16.929Z] to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 
[2024-01-03T18:39:16.929Z] 
[2024-01-03T18:39:16.929Z]     '--initialize-at-run-time=<culprit>'
[2024-01-03T18:39:16.929Z] 
[2024-01-03T18:39:16.929Z] to prevent the instantiation of the object.
[2024-01-03T18:39:16.929Z] 
[2024-01-03T18:39:16.929Z] If you are seeing this message after enabling '--strict-image-heap', this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
[2024-01-03T18:39:16.929Z] To fix this, include '--initialize-at-build-time=java.net.NetworkInterface' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.
[2024-01-03T18:39:16.929Z] Please address this problem to be prepared for future releases of GraalVM.
[2024-01-03T18:39:16.929Z] 
[2024-01-03T18:39:16.929Z] The following detailed trace displays from which field in the code the object was reached.
[2024-01-03T18:39:16.929Z] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:186)
[2024-01-03T18:39:16.929Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:616)
[2024-01-03T18:39:16.929Z] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:296)
[2024-01-03T18:39:16.929Z] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readArrayElement(AnalysisConstantReflectionProvider.java:158)
[2024-01-03T18:39:16.929Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapObjectArray(ImageHeapScanner.java:267)
[2024-01-03T18:39:16.929Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapObject(ImageHeapScanner.java:251)
[2024-01-03T18:39:16.929Z] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$getOrCreateImageHeapConstant$2(ImageHeapScanner.java:205)
[2024-01-03T18:39:16.929Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[2024-01-03T18:39:16.929Z] 	... 31 more
```

**Comment by tristantarrant** [comment]
As it's reporting about `java.net.NetworkInterface` I'm wondering if it means that the binary image would end up containing network interfaces of the machine on which it is built and not detect them at runtime

**Comment by pruivo** [comment]
@ryanemerson @tristantarrant let me know if I fixed this properly. The stack trace was the following:
```
The culprit object has been instantiated by the 'org.jgroups.blocks.RequestCorrelator' class initializer with the following trace:
	at java.net.NetworkInterface.<init>(NetworkInterface.java:70)
	at java.net.NetworkInterface.getAll(Unknown Source)
	at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:347)
	at org.jgroups.util.Util.getAllAvailableInterfaces(Util.java:4685)
	at org.jgroups.util.Util.<clinit>(Util.java:125)
	at org.jgroups.logging.LogFactory.<clinit>(LogFactory.java:32)
	at org.jgroups.blocks.RequestCorrelator.<clinit>(RequestCorrelator.java:74)
```

**Comment by ryanemerson** [comment]
@pruivo It seems fine to me. I'm curious though, is it not possible to use `--initialize-at-run-time=org.jgroups.blocks.RequestCorrelator` or is there a reason to just defer `Util`?

**Comment by pruivo** [comment]
@ryanemerson I got the original error with it. I suppose there is another class (well, most of them)  using `org.jgroups.util.Util`

**Comment by pruivo** [comment]
I've reverted the change in the pom.xml and I added the class in `InfinispanServerProcessor.addRuntimeInitializedClasses()`

**Comment by tristantarrant** [comment]
@pruivo please rebase to bring in the latest FootprintIT changes and adjust the loaded classes count

**Comment by tristantarrant** [comment]
Hmm, an OOME because of `org.codehaus.plexus.classworlds.realm.ClassRealm`. Re-running CI

**Pull request merged**
