### PR TITLE
ISPN-13296 Create Hibernate 2LC implementation for Hibernate 6.0.x

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-13296

### CODE REVIEW

**Comment by wburns** [comment]
The tests in the cache-v60 module are not running and always displays 
`[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0`

**Comment by wburns** [comment]
This PR removes the JPA and cache-v5* modules as they were all reliant upon Hibernate 5.x. Paul has already confirmed that EAP will not require Hibernate 5.x support in the version that will import Infinispan 14.

This PR adds new jakarta classifier jars to commons, core and hotrod-client for users to utilize instead of javax packages. The new cache-v60 module uses jakarta only and relies upon Hibernate 6.

**Comment by wburns** [comment]
This issue cannot be fixed until we have the next build of Hibernate which should be coming within the next few days.

**Comment by wburns** [comment]
Rebased and updated. Note however that tests still fail and we need next release of Hibernate to fix remaining issues.

**Comment by tristantarrant** [comment]
We need docs before merging. In particular:
* add a note to the upgrade guide about both the dropping the old 2LC implementations as well as the Javax > Jakarta transition
* adjust the `ref_hibernate_second_level_cache.adoc` file to the specific versions

**Comment by wburns** [comment]
Rebased and added docs.

**Comment by tristantarrant** [comment]
A few Maven warnings:
```
[WARNING] The artifact org.hibernate:hibernate-core:jar:6.0.0.Final has been relocated to org.hibernate.orm:hibernate-core:jar:6.0.0.Final
[WARNING] The artifact org.hibernate:hibernate-testing:jar:6.0.0.Final has been relocated to org.hibernate.orm:hibernate-testing:jar:6.0.0.Final
```

and 

```
[WARNING] Some problems were encountered while building the effective model for org.infinispan:infinispan-hibernate-cache-v60:jar:14.0.0-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.hibernate:hibernate-testing:jar -> version ${versionx.org.hibernate.hibernate-core} vs ${versionx.org.hibernate.hibernate-testing} @ org.infinispan:infinispan-parent:14.0.0-SNAPSHOT, /home/tst/Work/Infinispan/infinispan/pom.xml, line 1058, column 22
```

**Comment by wburns** [comment]
Updated to remove warnings, however still looking at tests not showing up.

**Comment by wburns** [comment]
Updated pom.xml so the surefire-reports directory is generated now. Thanks @tristantarrant !

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
