### PR TITLE
ISPN-6952 Improve the JCacheTwoCachesBasicOpsTest

### PR DESCRIPTION
**Pull request by tristantarrant**
- Moved all remote tests into the "remote" package
- Use test-specific keys and values
- Remove listeners even in case of failures
- Fixed naming and added more debug information

### CODE REVIEW

**Comment by gustavonalle** [comment]
Does "Improve the JCacheTwoCachesBasicOpsTest" means fixing the random failures?

**Comment by tristantarrant** [comment]
I hope so :)

**Comment by gustavonalle** [comment]
@tristantarrant ok :)
I was a bit confused by the comment "added more debug information", it seemed it'd simply log more stuff

**Comment by danberindei** [comment]
Hey @tristantarrant, you're still using `Thread.sleep()` :)

There's also a new kind of failure here, maybe it needs more logging: http://ci.infinispan.org/job/Infinispan/job/PR-5375/2/

**Comment by tristantarrant** [comment]
I'm tempted to make all listeners synchronous

**Comment by tristantarrant** [comment]
More changes:
- converted all listeners to synchronous (although this only really affects embedded)
- use "eventual" assertions
- use AtomicIntegers and synchronized lists
- apply k(m) and v(m) to other JCache tests to better track failures there.

**Pull request merged**
