### PR TITLE
ISPN-15860 Exception with async store when not segmented

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-15860

### CODE REVIEW

**Comment by jabolina** [comment]
Are the `SharedStoreTest` failures related?

**Comment by wburns** [comment]
Checking.

**Comment by wburns** [comment]
Updated, the size stat for DummyInMemoryStore was added twice on accident

**Review by pruivo — APPROVED** [review]

**Review by jabolina — APPROVED** [review]

**Comment by jabolina** [comment]
Thanks, @wburns!

**Pull request merged**
