### PR TITLE
Ispn 5700 Client expiration events

### PR DESCRIPTION
**Pull request by wburns**
https://issues.jboss.org/browse/ISPN-5700

Note this is only the last commit.  Basically ignore everything not in client or server directories.

### CODE REVIEW

**Comment by wburns** [comment]
I will have to rebase after https://github.com/infinispan/infinispan/pull/3672 is integrated

**Comment by wburns** [comment]
Rebasing now that other commits are in.

**Comment by wburns** [comment]
Rebased after other commit.

**Comment by anistor** [comment]
Looking ..

**Comment by anistor** [comment]
Integrated. Thanks @wburns !

**Pull request closed without merging**
