### PR TITLE
Test query on bytes ProtoBuffer type field

### PR DESCRIPTION
**Pull request by fax4ever**
I'm trying to query filtering on Protocol Butters type property.
Test:  `findMovieByRating_protoBytesTypeProperty`.

I'm trying to query filtering on starting with 'v' property.
Test: `findMovieByViews_startsV`.

I'm definitely trying to do something wrong. thank you

### CODE REVIEW

**Comment by galderz** [comment]
Assigning to @anistor

**Comment by tristantarrant** [comment]
Retriggering CI

**Comment by fax4ever** [comment]
Hi @tristantarrant! Just rebased it. Thank you

**Comment by anistor** [comment]
But why do we need this test @fax4ever ? I remember having a chat about it a while ago. Querying on byte[] is not supported so why test it? I remember you were trying to query on byte[] because OGM uses a byte[] of size 1 to represent in place of byte type (because protobuf lacks a native byte type) but that's not the recommended way of mapping unsupported numerics to proto. The way to do it is to use int32.

**Comment by fax4ever** [comment]
Hi @anistor! I agree with you, it would have no sense querying on ProtoBuf bytes type. The PR contains also another test, it seems that something goes wrong when the field name starts with a 'v'. But I'm definitely trying to do something wrong. thank you

**Comment by fax4ever** [comment]
Thank you @anistor. Thus I will close the issue. :)

**Comment by fax4ever** [comment]
Thank you @anistor. :P

**Pull request closed without merging**
