### PR TITLE
ISPN-7126 InfinispanIndexManager hangs under load

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-7126

Reproducer only. 
This test hangs on master and eventually times out, but works as expected before https://github.com/infinispan/infinispan/commit/ad0b1cc84778074769adf9312042fad74169bf2d

### CODE REVIEW

**Comment by danberindei** [comment]
@gustavonalle Ok, looks like the problem is that the `QueryInterceptor.visitPutKeyValueCommand` `thenAccept` lambda does a blocking `Cache.putIfAbsent` (indirectly). 

Before ISPN-5469, this would block a remote-executor thread. After ISPN-5469, this would block the OOB thread that received the response from the primary owner. That means we need less remote-executor threads, but we need more OOB threads. I only tested with 10 threads, but that got rid of the deadlock for me.

Bela and Pedro have been discussing merging the JGroups (ex-OOB) and remote-executor thread pools with JGroups 4.0 anyway, so I think just increasing the OOB thread pool size is acceptable for now. Ideally though, indexing would also be asynchronous and return a `CompletableFuture`.

**Comment by gustavonalle** [comment]
@danberindei Thanks. I tried it yesterday and it solved for me as well. I was in doubt if that was the expected behaviour after 5469 and a bit reluctant to increase the OOB thread pool, but will do that for now.

**Comment by gustavonalle** [comment]
@danberindei wrt index being asynchronous, I will see if the putIfAbsent during lucene lock acquiring can be asynchronous, this would avoid blocking in the OOB altogether (will block somewhere else)

**Comment by danberindei** [comment]
@gustavonalle One step at a time :)

**Pull request closed without merging**
