### PR TITLE
Ispn 6354 Remove Map/Reduce

### PR DESCRIPTION
**Pull request by wburns**
https://issues.jboss.org/browse/ISPN-6354

### CODE REVIEW

**Comment by wburns** [comment]
This one is in preview until a full test suite can go by.  I will also fixup the second commit after I can confirm there were no extra files dragged along in it.

**Comment by wburns** [comment]
I still need to remove documentation

**Comment by wburns** [comment]
There are also some test failures I need to clean up.

**Comment by wburns** [comment]
Updated documentation and fixed tests I saw.  Waiting on a rerun of tests and it should be good.

**Comment by vblagoje** [comment]
Oh noooo @wburns an era of M/R gone by :-) However, a new one coming online now! Cheers

**Comment by gustavonalle** [comment]
The world is experiencing a map reduce hangover :smile:  (from [1])

dumbo-drunk

[1] http://www.confluent.io/blog/introducing-kafka-streams-stream-processing-made-simple

**Comment by wburns** [comment]
Rebased.

**Comment by tristantarrant** [comment]
The BulkGetKeys stuff in the hotrod client testsuite is failing consistently :)

**Comment by wburns** [comment]
Hrmm weird, the other test was working when I tried this.  I will take a look.

**Comment by wburns** [comment]
Alright I have a fix that should fix the ones I could see.  Going to wait for a full CI run though to confirm.

**Comment by wburns** [comment]
The last failure should be fixed and I found another reference to remove.  The testsuite takes FOREVER to run though so I haven't been able to confirm it fixed it yet.  Will just wait for another test run.

**Comment by wburns** [comment]
The test failures seem unrelated now and also majority didn't fail on the previous run when all I changed was https://github.com/infinispan/infinispan/pull/4112/files#diff-a5633337487062932a2065c5635951c5R8

**Comment by tristantarrant** [comment]
Going

**Comment by tristantarrant** [comment]
Going

**Comment by tristantarrant** [comment]
Gone !

**Pull request closed without merging**
