### PR TITLE
ISPN-7181 Include RocksDB JNI into ISPN embedded uber jar

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.jboss.org/browse/ISPN-7181

### CODE REVIEW

**Comment by tristantarrant** [comment]
the uberjar is currently full of unneeded dependencies. Would like to see that cleaned up first

**Comment by vjuranek** [comment]
Sorry for late reply @tristantarrant . I looked on it little bit and honestly I'm not sure what should be contained in given uber-jar. I there any list or some description, what should be there (I'm afraid test suite coverage is not sufficient to use it as a hint ... in sense that if test suite is passing it doesn't imply that the changes are ok). Thanks!

**Comment by slaskawi** [comment]
@tristantarrant @vjuranek Hey Guys! Could you please tell me what is the expected result with this PR? The JIRA mentions adding RockDB to the Uber jar and from the commit I see it's being removed. So I'm a bit confused. Could you please give me a hand with this?

**Comment by vjuranek** [comment]
@slaskawi it's removed from exclusion, so effectively it's added :-) Removed is from integration tests where it was added just to make them passing

**Comment by slaskawi** [comment]
ooh sorry, I'm blind... yes, now it makes sense. @tristantarrant I'm ok with those changes. How about you?

**Comment by slaskawi** [comment]
Integrated thanks!

**Pull request merged**
