### PR TITLE
ISPN-5683 Enable Checkstyle

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-5683

### CODE REVIEW

**Comment by slaskawi** [comment]
Hey @gustavonalle !

I believe it was correct... You need to run it separately from project's root directory (and if you need to run it against one module - use this example `./build.sh checkstyle:check -pl cdi/cdi-common`).

Otherwise it would be really hard to integrate it to CI: http://ci.infinispan.org/viewLog.html?buildId=37811&buildTypeId=Infinispan_MasterHotspotJdk8&tab=buildLog#_state=44,389&focus=409

**Comment by gustavonalle** [comment]
@slaskawi I wasn't actually trying to run checkstyle for one module, I was just doing ```mvn clean install``` inside ```lucene-directory``` and getting unrelated checkstyle errors. This should not break regardless of checkstyle.

> Otherwise it would be really hard to integrate it to CI

Why? This PR does not change how to run checkstyle, it still can be run as ```mvn checkstyle:check```

**Comment by slaskawi** [comment]
Retriggering CI to see if it works correctly with new settings...

**Comment by slaskawi** [comment]
Ok, it looks like I was wrong.. pulling into `master` and `8.2.x`

**Comment by slaskawi** [comment]
Pulled into the master branch. There was some conflicts against 8.2.x so please open another PR if needed.

**Pull request closed without merging**
