### PR TITLE
ISPN-10225 Upgrade to WildFly 17.0.1.Final

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-10225

### CODE REVIEW

**Comment by ryanemerson** [comment]
@tristantarrant I thought we were mothballing the wildfly server? Or will the version simply be frozen at `17.x.y` once Infinispan 10 is released?

**Comment by tristantarrant** [comment]
The wildfly server will be deprecated in 10.0, but we should still be in a position to align it to the future WildFly 18/EAP 7.3.

**Comment by ryanemerson** [comment]
@tristantarrant Wildfly 17.0.0.Final is now out

**Comment by tristantarrant** [comment]
Upgraded to Final, still some failures around deployments.

**Comment by danberindei** [comment]
Integrated, thanks Tristan!

**Pull request merged**
