### PR TITLE
[8.2.x] ISPN-7182 Upgrade to protostream-3.0.7.Final

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-7182

This is **8.2.x** only.

### CODE REVIEW

**Comment by gustavonalle** [comment]
There are test failures on ``` ProtobufMetadataManagerInterceptorTest```

**Comment by anistor** [comment]
I've released protostream-3.0.7.Final to fix the issue.

**Comment by gustavonalle** [comment]
@anistor integrated. I noticed that there is no 3.0.7.Final tag on protostream  
https://github.com/infinispan/protostream/tree/3.0.7.Final? Is there something wrong with the release script maybe?

**Comment by anistor** [comment]
I forgot to push the tags. Should be ok now.

**Pull request merged**
