### PR TITLE
[14.0] ISPN-14195+ISPN-14203 Hit count efficiency contributions

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-14195
https://issues.redhat.com/browse/ISPN-14203

Backport of https://github.com/infinispan/infinispan/pull/11005

### CODE REVIEW

**Comment by fax4ever** [comment]
I updated the backport too

**Comment by tristantarrant** [comment]
Some related failures (also apply to main: unfortunately I merged that already)

**Comment by fax4ever** [comment]
> Some related failures (also apply to main: unfortunately I merged that already)

going to check it

**Comment by fax4ever** [comment]
> Some related failures (also apply to main: unfortunately I merged that already)

You're right. Sorry. The last commit is supposed to fix it.
For the main I sent this pr => https://github.com/infinispan/infinispan/pull/11088

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
