### PR TITLE
Upgrade Integration Tests to WildFly 9

### PR DESCRIPTION
**Pull request by Sanne**
And some integration test improvements:

 - https://issues.jboss.org/browse/ISPN-5339
 - https://issues.jboss.org/browse/ISPN-5398
 - https://issues.jboss.org/browse/ISPN-5442

### CODE REVIEW

**Comment by alanfx** [comment]
@gustavonalle any chance you can take a look at this one?! I would but I have no commit rights...

**Comment by gustavonalle** [comment]
looking

**Comment by gustavonalle** [comment]
There are failures on integrationtests/security-it:
```
NodeAuthorizationMD5FailIT.org.infinispan.test.integration.security.embedded.NodeAuthorizationMD5FailIT » Lifecycle
  NodeAuthenticationKrbPassIT.org.infinispan.test.integration.security.embedded.NodeAuthenticationKrbPassIT » Lifecycle
  NodeAuthenticationMD5FailIT.org.infinispan.test.integration.security.embedded.NodeAuthenticationMD5FailIT » Lifecycle
  LdapAuthenticationIT.org.infinispan.test.integration.security.embedded.LdapAuthenticationIT » Lifecycle
  NodeAuthenticationMD5PassIT.org.infinispan.test.integration.security.embedded.NodeAuthenticationMD5PassIT » Lifecycle
  KrbLdapAuthenticationIT.org.infinispan.test.integration.security.embedded.KrbLdapAuthenticationIT » Lifecycle
  NodeAuthenticationKrbFailIT.org.infinispan.test.integration.security.embedded.NodeAuthenticationKrbFailIT » Lifecycle
```

it also needs a trivial arquillian maven coordinates change at ```jcache/remote/pom.xml```

**Comment by gustavonalle** [comment]
The test fix is trivial, will fix it and integrated

**Comment by Sanne** [comment]
I thought I had done the requested fixes already, but the security tests fail me all the time and couldn't look at it.
AFAIR they also fail me on master though so it might be unrelated?

**Comment by gustavonalle** [comment]
The failure in security module is due to  ```<extension module="org.jboss.as.threads"/>```  being present in its wildfly config, which is not valid to WF9

**Comment by gustavonalle** [comment]
I fixed it, but while running the tests, the suite hanged in the test ```org.infinispan.server.test.cache.container.CacheContainerIT#testEndpointConfiguration```

```
"main" #1 prio=5 os_prio=0 tid=0x00007f54d0008800 nid=0xb3c in Object.wait() [0x00007f54d9d9c000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.UNIXProcess.waitFor(UNIXProcess.java:264)
        - locked <0x000000077935c6f0> (a java.lang.UNIXProcess)
        at org.jboss.as.arquillian.container.managed.ManagedDeployableContainer.stopInternal(ManagedDeployableContainer.java:321)
        at org.jboss.as.arquillian.container.CommonDeployableContainer.stop(CommonDeployableContainer.java:124)
        at org.jboss.arquillian.container.impl.ContainerImpl.stop(ContainerImpl.java:217)
        at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$9.perform(ContainerLifecycleController.java:178)
        at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController$9.perform(ContainerLifecycleController.java:172)
        at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.forContainer(ContainerLifecycleController.java:255)
        at org.jboss.arquillian.container.impl.client.container.ContainerLifecycleController.stopContainer(ContainerLifecycleController.java:171)
```

This test runs under infinispan server (which is based on WF8), so I'm wondering if the arquillian upgrade in this PR is causing this side effect?

**Comment by gustavonalle** [comment]
Actually it was the server that deadlocked, and as a result, arquillian got blocked while waiting forever for it:

```
Found one Java-level deadlock:
=============================
"undefined":
  waiting to lock monitor 0x00007f55d001d768 (object 0x00000000e07c1fc8, a org.jboss.as.threads.ScheduledThreadPoolService),
  which is held by "MSC service thread 1-9"
"MSC service thread 1-9":
  waiting for ownable synchronizer 0x00000000e07c1e80, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "undefined"

Java stack information for the threads listed above:
===================================================
"undefined":
        at org.jboss.as.threads.ScheduledThreadPoolService$ExecutorImpl.terminated(ScheduledThreadPoolService.java:121)
        - waiting to lock <0x00000000e07c1fc8> (a org.jboss.as.threads.ScheduledThreadPoolService)
        at java.util.concurrent.ThreadPoolExecutor.tryTerminate(ThreadPoolExecutor.java:706)
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)
"MSC service thread 1-9":
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000e07c1e80> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
        at java.util.concurrent.ThreadPoolExecutor.interruptIdleWorkers(ThreadPoolExecutor.java:783)
        at java.util.concurrent.ThreadPoolExecutor.tryTerminate(ThreadPoolExecutor.java:697)
        at java.util.concurrent.ThreadPoolExecutor.shutdown(ThreadPoolExecutor.java:1394)
        at java.util.concurrent.ScheduledThreadPoolExecutor.shutdown(ScheduledThreadPoolExecutor.java:761)
        at org.jboss.as.threads.ManagedScheduledExecutorService.internalShutdown(ManagedScheduledExecutorService.java:53)
        at org.jboss.as.threads.ScheduledThreadPoolService.stop(ScheduledThreadPoolService.java:67)
        - locked <0x00000000e07c1fc8> (a org.jboss.as.threads.ScheduledThreadPoolService)
        at org.jboss.msc.service.ServiceControllerImpl$StopTask.stopService(ServiceControllerImpl.java:2056)
        at org.jboss.msc.service.ServiceControllerImpl$StopTask.run(ServiceControllerImpl.java:2017)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Found 1 deadlock.


```

**Comment by gustavonalle** [comment]
It seems related to  https://issues.jboss.org/browse/WFLY-3549

**Comment by gustavonalle** [comment]
Created https://issues.jboss.org/browse/ISPN-5525 to track the deadlock issue.
Fixed the failing security test and integrated, thanks @Sanne !

**Comment by Sanne** [comment]
thanks for your help! very glad this is done.

**Pull request closed without merging**
