### PR TITLE
[9.3.x] ISPN-11116 Invalidation commands should not load the previous value

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-11116

### CODE REVIEW

**Comment by ivassile** [comment]
JBEAP (7.2.z): https://issues.redhat.com/browse/JBEAP-18403
Upstream: https://issues.redhat.com/browse/ISPN-11116
Upstream PR: https://github.com/infinispan/infinispan/pull/7712

**Comment by ivassile** [comment]
@danberindei One off patch has been requested for this due to high priority case and we need to include it in EAP 7.2.7 which is currently in final stage so we have to merge it and release Infinispan 9.3.8 ( https://issues.redhat.com/browse/JBEAP-18404 )

**Comment by pruivo** [comment]
integrated! thanks @danberindei !

**Comment by ivassile** [comment]
@pruivo We need Infinispan 9.3.8 release to include this change in EAP 7.2.7 [1]. Can you tag it or ping the person who can tag the release. Thanks!

[1] https://issues.redhat.com/browse/JBEAP-18404

**Comment by pruivo** [comment]
@ivassile 9.3.8 released: https://repository.jboss.org/nexus/content/groups/public-jboss/org/infinispan/infinispan-core/9.3.8.Final/

**Comment by ivassile** [comment]
@pruivo Thanks for the release!

**Pull request merged**
