### PR TITLE
ISPN-11006 Remove REST v1 API

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-11006

### CODE REVIEW

**Comment by gustavonalle** [comment]
Failures unrelated

**Comment by gustavonalle** [comment]
@anistor You wanted to see the removal of REST v1, here you go :smile:

**Comment by anistor** [comment]
Joy Joy Hoy

**Comment by anistor** [comment]
Merged. Thanks @gustavonalle !

**Pull request closed without merging**
