### PR TITLE
ISPN-9440 Hibernate second level cache - Add native query test

### PR DESCRIPTION
**Pull request by diegolovison**
ISPN-9440 Hibernate second level cache - Add native query test

### CODE REVIEW

**Comment by galderz** [comment]
Why the need for such a test? What is the difference in Hibernate code that leads to think that the second level cache would deal with such native query differently? I don't want to add more tests unless they are testing something not already covered from a second-level cache perspective. IOW, we're not trying to take all Hibernate features and run them as tests with second-level cache and see whether something fails... It just wouldn't scale.

**Comment by diegolovison** [comment]
If this test was covered somehow. I fine to close this PR

**Comment by galderz** [comment]
Queries are being tested, but I don't know whether native queries are somehow different from a second-level cache perspective. That's what I was hoping you'd look into ;)

**Comment by diegolovison** [comment]
Yep. I did it :)

**Comment by diegolovison** [comment]
createSQLQuery will invalidate all regions. If you would like to avoid that you can set `addSynchronizedEntityClass`.
Invalidation was covered in other tests.
I am closing this PR.

**Comment by galderz** [comment]
Thanks @diegolovison :)

**Pull request closed without merging**
