### PR TITLE
ISPN-8519 deleted not needed

### PR DESCRIPTION
**Pull request by karesti**
https://issues.jboss.org/browse/ISPN-8519

### CODE REVIEW

**Comment by pruivo** [comment]
why is the test not needed?

**Comment by karesti** [comment]
because there is already one with 3 nodes where I kill one and I have another test where I do an split brain with two minority partitions. Vert.x tests run now on 2 nodes killing one but this does not make too much sense and should be running with 3 nodes.

**Comment by danberindei** [comment]
Integrated, thanks Katia!

**Comment by pruivo** [comment]
you have a failure:
org.infinispan.lock.ClusteredLockSplitBrainTest.testAutoReleaseIfLockIsAcquiredFromAMinorityPartition[DIST_SYNC] (from infinispan-clustered-lock)
is it tracked?

**Comment by karesti** [comment]
@pruivo 😭  nooooooooooooooo

**Pull request merged**
