### PR TITLE
ISPN-10967 CORS rules for localhost don't take offset into account

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-10967

### CODE REVIEW

**Comment by pruivo** [comment]
@gustavonalle how is it suppose to work if you bind the server to other IP than the localhost?
I bind the server to the wi-fi IP and I'm getting forbidden errors when I try to create a cache.

**Comment by pruivo** [comment]
works fine for localhost!

**Comment by gustavonalle** [comment]
@pruivo OOTB it contains rules for localhost only. For other IPs, configuration is needed atm.
https://infinispan.org/docs/stable/titles/rest/rest.html#rest_server_cors

**Comment by pruivo** [comment]
@gustavonalle ops! I clicked the merge button too soon. The failure `org.infinispan.server.configuration.JsonSerializationTest.testJsonSerialization(JsonSerializationTest.java:198)` seems related to your changes!

@gustavonalle thanks for the explanation!

**Comment by gustavonalle** [comment]
@pruivo I'll take a look in the failure

**Comment by gustavonalle** [comment]
@pruivo Fixed in https://github.com/infinispan/infinispan/pull/7616

**Pull request merged**
