### PR TITLE
[15.0.x] ISPN-15916 Certificate reloading

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-15916

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#3](https://ci.infinispan.org/job/Infinispan/job/PR-12642/3/):
```
quay.io/infinispan-test/server:PR-12642
```

**Comment by tristantarrant** [comment]
Hm, there is a weird jgroups failure ? Was it introduced by a jgroups upgrade ? I don't see it on the 15.0.x builds.

**Comment by ryanemerson** [comment]
I'm marking this as "On Hold" as upgrading to JGroups 5.3.7 or higher introduces an incompatibility with metrics. I'm meeting with Bela tomorrow to try to figure out a solution going forward.

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#4](https://ci.infinispan.org/job/Infinispan/job/PR-12642/4/):
```
quay.io/infinispan-test/server:PR-12642
```

**Comment by cmuchinsky** [comment]
I noticed this PR introduced a new runtime dependency `org.wildfly.security:wildfly-elytron-keystore` to `org.infinispan:infinispan-commons`, is this by design or should this have been scoped as a test only dependency?

**Comment by ryanemerson** [comment]
Good spot @cmuchinsky. I think this dependency is a leftover from an earlier version of the solution that was missed on the PR review. I've created https://github.com/infinispan/infinispan/pull/12723 to remove this dependency and I'll make sure this is backported for 15.0.8.Final.

**Pull request merged**
