### PR TITLE
ISPN-7424 Rewrite JPA/Hibernate 2L cache docu

### PR DESCRIPTION
**Pull request by galderz**

### CODE REVIEW

**Comment by tristantarrant** [comment]
Would also need to add anything Spring-related if necessary /cc @slaskawi

**Comment by galderz** [comment]
That's the plan... as well as on Wildlfy... but I'm working on those tutorials and once I've got them working I can add more. However...

Turns out Radim added 2LC docu to Hibernate itself! See [here](http://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#caching-provider-infinispan).

I wasn't aware of that, and he didn't sort out the duplication issue. So, don't integrate PR since I'm goin to send a PR to Hibernate docu itself, and then from Infinispan docu we just link to it. Plan?

**Comment by tristantarrant** [comment]
Sounds like a plan !

**Comment by galderz** [comment]
Closing for now. I'll reopen when ready.

**Pull request closed without merging**
