### PR TITLE
Fix a classloading issue if HR client tests are used with EAP modules

### PR DESCRIPTION
**Pull request by jmarkos**
This is a fix needed for product testing.

### CODE REVIEW

**Comment by danberindei** [comment]
@jmarkos Need a JIRA reference :)

Also, I think the "proper" fix would be to set the classloader in the `RemoteCacheManager` configuration (`ConfigurationBuilder.classLoader(cl)`). If that doesn't work, then this is a bug in the production code, not in the test.

**Comment by jmarkos** [comment]
@danberindei I looked around, and I don't see the classloader of RemoteCacheManager being used for anything. It was last used in the 5.2.x branch, or I'm missing something.

**Comment by danberindei** [comment]
@jmarkos Ouch! True, it wasn't very encouraging when I didn't find any javadoc for `ConfigurationBuilder.classLoader()`, but there was only one thing I could imagine it being for: unmarshalling. You're right, it's not used at all, so I've created https://issues.jboss.org/browse/ISPN-6367

**Comment by danberindei** [comment]
I added a comment referencing ISPN-6367 and I integrated it. Thanks Jakub!

**Pull request closed without merging**
