### PR TITLE
ISPN-13515 Jdbc Store Boolean does not work

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-13515

### CODE REVIEW

**Comment by wburns** [comment]
I have only confirmed on POSTGRES, H2 and SQLLITE so far. Need to confirm the other DBs all pass as well tomorrow.

**Comment by wburns** [comment]
Postgres has a boolean type as an int32 with a type name of BIT, so that case is covered here.
Drivers that properly implement with the boolean type should still work, but I have a feeling one of the databases still has a weird edge case.

**Comment by alanfx** [comment]
@gustavolira can you check this PR with the other DBs, please? Thanks!

**Comment by gustavolira** [comment]
> @gustavolira can you check this PR with the other DBs, please? Thanks!

Sure

**Comment by wburns** [comment]
Oracle has no actual boolean like type. So we will have to add something special for the Oracle case.

**Comment by wburns** [comment]
Oracle and MSQL Server are now fixed as well. Rest of the DBs passed afaik @gustavolira. If you could confirm they are passing, that would be great.

**Comment by gustavolira** [comment]
> Oracle and MSQL Server are now fixed as well. Rest of the DBs passed afaik @gustavolira. If you could confirm they are passing, that would be great.

MySQL, PostgreSQL, MariaDB, MSSQL are fine

**Review by karesti — APPROVED** [review]

**Pull request merged**
