### PR TITLE
ISPN-11857 eventually() default poll interval is too long

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-11857

### CODE REVIEW

**Comment by wburns** [comment]
Looks like there are some compilation errors with the methods you changed/removed.

**Comment by danberindei** [comment]
Weird, I didn't get the compilation error locally. I rebased, hopefully this time it works in CI as well.

**Comment by danberindei** [comment]
Compiles fine now

**Comment by ryanemerson** [comment]
CI looks good, thanks @danberindei

**Pull request merged**
