### PR TITLE
ISPN-7632 Remove useEagerLocking configuration

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-7632

### CODE REVIEW

**Comment by pruivo** [comment]
isn't kind of bad changing public API just before final?

**Comment by danberindei** [comment]
@pruivo I'll let @tristantarrant decide, but I figure this has stayed deprecated long enough that it's not worth maintaining it in all 9.x minor versions.

**Comment by tristantarrant** [comment]
I think we'll do a CR4 at this point. +1 on this removal

**Comment by pruivo** [comment]
integrated! thanks @danberindei

**Pull request merged**
