### PR TITLE
[14.0] ISPN-15144 Protostream 4.6.5.Final

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-15144

### CODE REVIEW

**Comment by pruivo** [comment]
is there a PR for main branch?

**Comment by tristantarrant** [comment]
I wanted to get this out of the way first. If you don't want to investigate your changes on 4.7.x for main, I can create it

**Review by fax4ever — APPROVED** [review]
LGTM

**Comment by tristantarrant** [comment]
ready to merge

**Comment by fax4ever** [comment]
Merged, thank you

**Comment by fax4ever** [comment]
I'm not closing the Jira since maybe we want to have it in the main branch as well?

**Pull request merged**
