### PR TITLE
ISPN-7850 JDBC Migrator 9.x Marshaller Incorrectly Loaded.

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-7850

This also needs backporting to 9.0.x

### CODE REVIEW

**Comment by gustavonalle** [comment]
@ryanemerson Just curious why didn't the testsuite catch the stackoverflow problem, is this a cross version issue?

**Comment by ryanemerson** [comment]
@gustavonalle Currently our testsuite does not have any tests for interacting with a database, i.e. via h2, only tests to ensure that the legacy marshaller works and that the migrator configuration is correctly parsed. I will update the PR to include these tests.

**Comment by gustavonalle** [comment]
@ryanemerson Great, thanks!

**Comment by ryanemerson** [comment]
@gustavonalle Reproducer test added.

**Comment by gustavonalle** [comment]
running tests locally as CI seems congested  :)

**Comment by gustavonalle** [comment]
Pushed to master, thanks @ryanemerson!

**Comment by gustavonalle** [comment]
Cherry-picking to 9.0.x as well

**Pull request merged**
