### PR TITLE
ISPN-16808 Do not limit delete cq command

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-16808

Co-authored-by: Pedro Ruivo <pruivo@redhat.com>

Pedro found the issue. I added the test.

### CODE REVIEW

**Comment by pruivo** [comment]
can't a test method be added to `RemoteQueryStringBroadcastTest` for example? It seems a bit wasteful to start 2 servers for a single method test. 
Also, you don't need to insert 150 entries. Modifying the default max results to 1 and inserting 2 entries is enough to test the code :smile:

**Comment by fax4ever** [comment]
Thanks for the review, @pruivo. I applied the idea of reducing the size of the inserted entities. About the idea of merging this test with `RemoteQueryStringBroadcastTest`, I don't this it is a good idea updating the `defaultMaxResults` on `RemoteQueryStringBroadcastTest` only to test in the same test the current issue.
In principle, every test shouldn't interfere with other tests.

**Comment by pruivo** [comment]
Interfere? how? I changed my mind, `RemoteQueryStringTest` would be a better place :)

**Comment by fax4ever** [comment]
Is the test  I'm adding about `QueryString`?

**Comment by pruivo** [comment]
IMO, yes. The base class is testing removal too https://github.com/infinispan/infinispan/blob/d31ca937344a16d0f373cadb59fe3b6a3561fde7/client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryStringTest.java#L206

Creating a cache with a different configuration will always be faster than starting a cluster for a single test. Not only it saves time but it tests with different cache configurations. 

I restarted CI and I'll merge if you don't want to do the change.

**Review by pruivo — APPROVED** [review]

**Comment by tristantarrant** [comment]
I agree with @pruivo : unless the servers require a specific server configuration, it is better to reuse them across multiple tests, creating a dedicated cache for the tests. This is the approach taken by the server testsuite, but it should really be applied in other places.

**Comment by pruivo** [comment]
merged! thanks @fax4ever !

**Comment by fax4ever** [comment]
Thanks

**Pull request merged**
