### PR TITLE
ISPN-10333 Bump RocksDB to 5.18.3

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.jboss.org/browse/ISPN-10333

### CODE REVIEW

**Comment by tristantarrant** [comment]
While it solves one specific issue with a platform, I'd rename the Jira/PR/commit to a component upgrade (which happens to have the side-effect of fixing running on OSX)

**Comment by diegolovison** [comment]
@tristantarrant done. thanks

**Comment by tristantarrant** [comment]
There are ~3500 missing tests.

**Comment by diegolovison** [comment]
@tristantarrant now we have `26,579 tests (+3638)` I did the rebase

**Pull request merged**
