### PR TITLE
ISPN-7706 ISPN-7707 ISPN-7709 SSL enhancements

### PR DESCRIPTION
**Pull request by tristantarrant**
ISPN-7706 If mech EXTERNAL and no callback supplied, use VoidCallbackHandler
ISPN-7707 Finer configuration options for keystores/truststores
    - Allow specifying a key alias
    - Allow specifying the SSL protocol type
    - Allow specifying the key store type
ISPN-7709 Generate certificates/keystores on the fly so they work on all JDKs
    - No more JDK-dependent keystore files committed to git
    - Generate vault on the fly too
    - Fixes all certificate-related tests (Hot Rod, REST, JGroups) on IBM JDK

https://issues.jboss.org/browse/ISPN-7706
https://issues.jboss.org/browse/ISPN-7707
https://issues.jboss.org/browse/ISPN-7709

### CODE REVIEW

**Comment by tristantarrant** [comment]
Some related failures...

**Comment by tristantarrant** [comment]
All security failures are fixed now

**Comment by wburns** [comment]
Seems fine to me.

**Comment by danberindei** [comment]
@tristantarrant I'm getting this error if I run ``mvn clean install -am -pl client/hotrod-client` and then `mvn test -pl client/hotrod-client`:

[INFO] --- keytool-maven-plugin:1.5:generateKeyPair (ca) @ infinispan-client-hotrod ---
[INFO] /bin/sh -c cd /home/dan/Work/tmpbuild/infinispan/client/hotrod-client && /home/dan/Tools/jdk1.8.0_121/jre/../bin/keytool -genkeypair -v -keystore /home/dan/Work/tmpbuild/infinispan/client/hotrod-client/target/test-classes/ca.jks -storepass secret -alias infinispan-ca -dname 'CN=CA,OU=Infinispan,O=JBoss,L=Red Hat' -keypass secret -validity 365 -keyalg RSA -keysize 2048 -ext bc:c
[INFO] keytool error: java.lang.Exception: Key pair not generated, alias <infinispan-ca> already exists
[INFO] java.lang.Exception: Key pair not generated, alias <infinispan-ca> already exists
[INFO] 	at sun.security.tools.keytool.Main.doGenKeyPair(Main.java:1597)
[INFO] 	at sun.security.tools.keytool.Main.doCommands(Main.java:966)
[INFO] 	at sun.security.tools.keytool.Main.run(Main.java:343)
[INFO] 	at sun.security.tools.keytool.Main.main(Main.java:336)

Perhaps we need to use [skipIfExist](http://www.mojohaus.org/keytool/keytool-maven-plugin/generateKeyPair-mojo.html#skipIfExist)?

**Pull request merged**
