### PR TITLE
ISPN-6426 - HotRodOperationsAuthzIT.​testSupervisorStats always fails after ISPN-6333 fix

### PR DESCRIPTION
**Pull request by andyuk1986**
https://issues.jboss.org/browse/ISPN-6426

### CODE REVIEW

**Comment by andyuk1986** [comment]
@slaskawi @danberindei The build on CI yesterday had 1 test failure which seems to be unrelated, I have run the same test on my local and it passed. I have triggered another build for this pull request.

**Comment by slaskawi** [comment]
Pulling

**Comment by slaskawi** [comment]
Integrated thanks!

**Comment by danberindei** [comment]
@andyuk1986 I would have liked to see a short description of the issue and/or the fix in the JIRA/PR/commit message :)

**Comment by andyuk1986** [comment]
@danberindei thank you for the note. I will take that into account for my next pull requests. Also I have updated the JIRA https://issues.jboss.org/browse/ISPN-6426 with the description of the problem and the solution.

**Pull request closed without merging**
