### PR TITLE
ISPN-6326 Make task execution log to the event log only if requested

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-6326

### CODE REVIEW

**Comment by anistor** [comment]
Looks good. Pulling ...

**Comment by anistor** [comment]
Actually no. 
```Failed tests: 
  TaskManagerTest.testRunTask:69 expected:<ISPN101000: Task SUCCESSFUL_TASK completed successfully> but was:<null>
```

**Comment by tristantarrant** [comment]
@anistor fixed it

**Comment by anistor** [comment]
Integrated. Thanks @tristantarrant !

**Pull request closed without merging**
