### PR TITLE
ISPN-6051 ClusterExpirationManager missing locking

### PR DESCRIPTION
**Pull request by wburns**
* Added entry locking so when an entry is updated we don't
* expire a previous value

https://issues.jboss.org/browse/ISPN-6051

### CODE REVIEW

**Comment by wburns** [comment]
Actually I need to think about this more.  I still think this is possible to get a deadlock, I need to write a test tomorrow for it.

**Comment by wburns** [comment]
Actually this is fine.

**Comment by galderz** [comment]
Any tests to verify this?

**Comment by wburns** [comment]
It fixes the ExpiryTest mentioned in the JIRA

**Comment by tristantarrant** [comment]
Pushed, thanks

**Pull request closed without merging**
