### PR TITLE
ISPN-10274 Distribution restructuring

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-10274

* Drop uberjars
* Drop all, minimal and remote distributions

### CODE REVIEW

**Comment by alanfx** [comment]
That's not a real JIRA! 🥇

**Comment by tristantarrant** [comment]
That's my automatic PR

**Comment by alanfx** [comment]
🎸 🥁 🎹 It's a band!

**Comment by galderz** [comment]
@tristantarrant LGTM, why is this preview?

**Comment by tristantarrant** [comment]
Because I would like to have some input about what should be in the zip distros.

**Comment by ryanemerson** [comment]
We probably want to include `infinispan-tools.jar` somewhere so that users have access to the store migrator

**Pull request closed without merging**
