### PR TITLE
ISPN-9843 RocksDBStore should not write entire MarshalledEntry as sto…

### PR DESCRIPTION
**Pull request by ryanemerson**
…re value

https://issues.jboss.org/browse/ISPN-9843

### CODE REVIEW

**Comment by ryanemerson** [comment]
This will break store compatibility, but that is already going to happen with the pending marshalling changes. Issuing as separate PR for simplicity.

**Comment by danberindei** [comment]
The key is usually much smaller than the value, I was much more interested in getting rid of the separate expiration DB :)

After reading a bit more about RocksDB, however, I'd be happy with just https://issues.jboss.org/browse/ISPN-8242

**Comment by tristantarrant** [comment]
Yes, using a single db with column families reduces open file descriptors.

**Comment by danberindei** [comment]
Integrated, thanks Ryan!

**Pull request merged**
