### PR TITLE
ISPN-5548 Realign JGroups subsystem with the one from WildFly

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5548

This PR contains a variety of changes:

ISPN-5548 Realign the JGroups subsystem to the one included in WF 9
Adapt the Infinispan subsytem to the above
"Rename" the JGroups, Infinispan and Endpoint subsystem model names so that they don't conflict with their WildFly counterparts

I've disabled some tests which will be re-enabled when WFLY-4771 is fixed. See https://issues.jboss.org/browse/ISPN-5580

The Infinispan subsystem has also temporarily lost the ability to inject thread pools. This will be ported from the work @rhusar is doing for WFLY-497 into https://issues.jboss.org/browse/ISPN-5579

### CODE REVIEW

**Comment by tristantarrant** [comment]
This needs a new release of infinispan-arquillian

**Comment by gustavonalle** [comment]
Something went wrong with the tests

**Comment by galderz** [comment]
Needs rebasing too

**Comment by tristantarrant** [comment]
This now is ready to integrate

**Comment by wburns** [comment]
Can we have all of the LGPL license headers on our files now that we are ASL ?  Seems wrong to me.

**Comment by tristantarrant** [comment]
Server can only be LGPL, since it is derived from WildFly code.

**Comment by wburns** [comment]
Guess I am not aware of where that distinction is detailed, but I trust you :)

**Comment by wburns** [comment]
Pulling...

**Comment by wburns** [comment]
Integrated into master, thanks @tristantarrant !

**Pull request closed without merging**
