### PR TITLE
ISPN-7407 Increase max_credits to 8m

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-7407

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please
library dist

**Comment by pruivo** [comment]
@danberindei should we integrate this?

**Comment by rvansa** [comment]
@pruivo Previews shouldn't be integrated until author changes the label.

While the effect of UFC is interesting, I don't think that we should keep increasing the default anytime we find out that it causes hiccups in some scenario.

**Comment by pruivo** [comment]
@rvansa I know. it is just has been 4 days without activity :)

**Comment by danberindei** [comment]
@pruivo To be fair, 2 of those days were in the weekend :)

I'm closing it, setting `max_credits` to 8m seems too much like disabling FC and that makes me nervous. Still, it's good to know that it does improve non-tx reads if we run out of options :)

**Pull request closed without merging**
