### PR TITLE
ISPN-11001 Get config templates

### PR DESCRIPTION
**Pull request by karesti**
https://issues.jboss.org/browse/ISPN-11001

### CODE REVIEW

**Comment by gustavonalle** [comment]
@karesti I though you'd filter the templates out of ```/v2/cache-managers/{name}/cache-configs``` by having a parameter, like ```/v2/cache-managers/{name}/cache-configs?ignore-templates``` or something similar, but this PR instead created another method to bring only the templates?

**Comment by oraNod** [comment]
@karesti hey, added a commit with suggested edit. hope that's ok. cheers!

**Comment by karesti** [comment]
@gustavonalle yes, I was thinking more on the cache-configs/templates like a filter instead a parameter.
I can change that if you want definetly

**Comment by karesti** [comment]
@oraNod thanks for the doc Don!

**Comment by gustavonalle** [comment]
ok, I was confused with the purpose of the PR, but @karesti has clarified.

**Comment by karesti** [comment]
@gustavonalle I will ping you when the build is over for merge, thnaks!!

**Comment by karesti** [comment]
@gustavonalle you can merge, failures are unrelated

**Comment by gustavonalle** [comment]
merged, thanks @karesti

**Pull request merged**
