### PR TITLE
ISPN-9788 edits to obtaining cache docs

### PR DESCRIPTION
**Pull request by oraNod**
https://issues.jboss.org/browse/ISPN-9788

Needs backport to 9.4.x.

### CODE REVIEW

**Comment by oraNod** [comment]
@tristantarrant Would you mind taking a quick look through these changes, please? I've made a few edits and added the `IMMUTABLE` configuration storage provider. cheers.

**Comment by oraNod** [comment]
@karesti I think we're good to merge here. @tristantarrant made a few changes to javadocs with ISPN-9823, which covers the details for configuration storage providers. thanks!

**Comment by karesti** [comment]
@oraNod merged, now you can backport I guess so we close the issue? 💃

**Comment by oraNod** [comment]
@karesti thanks! I've created a backport: https://github.com/infinispan/infinispan/pull/6545

**Pull request merged**
