### PR TITLE
Ispn 7267/ispn 4189/ispn 7373/disabled some of the tests for certain oses

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/ISPN-7267
https://issues.jboss.org/browse/ISPN-4189
https://issues.jboss.org/browse/ISPN-7373

### CODE REVIEW

**Comment by alanfx** [comment]
@slaskawi this is 🥇 functionality!

**Comment by tristantarrant** [comment]
This could actually be contributed back to TestNG :)

**Comment by tristantarrant** [comment]
Something broke the build early. Check CI please

**Comment by slaskawi** [comment]
I'm really not sure why this is happening... It looks like something triggers classpath scanning, which fails in some modules (like core). LevelDB module for example is fine... 

It needs some more investigation...

**Comment by slaskawi** [comment]
A note to myself: It seems that TestNG scans all packages where listeners are located. Moving JUnit listener to separate package might solve the issue.

**Comment by slaskawi** [comment]
Should be fixed now. For some reason the logger cause Class Loading... Don't know why but at this point I'm sure Java Util Logging is rubbish...

**Comment by galderz** [comment]
Let's see how it looks when the next clean CI run comes along...

**Comment by slaskawi** [comment]
Rebased

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
