### PR TITLE
ISPN-9638 Make Single port server a feature

### PR DESCRIPTION
**Pull request by wburns**
* Prevent startup when single port is configured but not enabled

https://issues.jboss.org/browse/ISPN-9638

### CODE REVIEW

**Comment by tristantarrant** [comment]
A bit overengineered (it is code we will want to remove at some point). I think we'd better have a generic "feature x is disabled" log in commons' Log and just do if (!featureInstance.isAvailable(x)) throw log.featureDisabled(x)). I now see that PersistenceManager also has a specific log. Can you fix that too please ?

**Comment by wburns** [comment]
Sure.

**Comment by wburns** [comment]
Updated to use same log method.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
