### PR TITLE
ISPN-6402 Default GMS.join_timeout is too long

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-6402

* Change the production default to 5000ms, and the tests to 2000ms.
* Set the jgroups.join_timeout property for Arquillian/JCache tests

### CODE REVIEW

**Comment by slaskawi** [comment]
Triggered CI manually

**Comment by tristantarrant** [comment]
I ran the server testsuite locally and it passed. @danberindei would it be possible to have this for 8.2.x as well ?

**Comment by tristantarrant** [comment]
Pushed to master. Thanks.

**Comment by danberindei** [comment]
@tristantarrant https://github.com/infinispan/infinispan/pull/4199 includes both this and the ISPN-6399 workaround.

**Pull request closed without merging**
