### PR TITLE
ISPN-5398 Test modules with WildFly 9.0.0.Beta2

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5398

This is a preview since there are some failures (JPA...)

### CODE REVIEW

**Comment by Sanne** [comment]
All tests are passing now, but this will have to wait for the next WildFly 9 tag to be integrated.
(Assuming they accept my pull requests)

**Comment by Sanne** [comment]
Requires:
 - https://github.com/wildfly/wildfly/pull/7353
Optional (but will be affected by):
 - https://github.com/wildfly/wildfly/pull/7375

**Comment by tristantarrant** [comment]
It looks like the first one is in. Hopefully we can bump this to 9.0.0.CR1 once it's out.

**Comment by galderz** [comment]
Needs rebase

**Comment by Sanne** [comment]
@tristantarrant is a follow up coming? Shall I send one using WildFly 9.0.0.CR1 ?

**Comment by tristantarrant** [comment]
Sorry, I was expecting you to handle it :)

**Comment by Sanne** [comment]
sure, I'll look at it. Just needed confirmation..

**Pull request closed without merging**
