### PR TITLE
ISPN-2435 Creating a ReplaceOperationStressTest

### PR DESCRIPTION
**Pull request by Sanne**
# Preview!

All 6 included tests fail. I'd love your help to figure out if the test is valid... I think so, in case we'll need this fixed critically in both `9` and `8.x`

@pruivo @danberindei @wburns

### CODE REVIEW

**Comment by rvansa** [comment]
Shouldn't `MOVES % THREADS` be `0`? I got the test stuck at the barrier...

**Comment by Sanne** [comment]
> Shouldn't MOVES % THREADS be 0? I got the test stuck at the barrier...

Yes! thanks. Sorry, that will teach me to toy with parameters at last minute ..

**Comment by rvansa** [comment]
@Sanne It seems that thread with index 0 is doing replace v_0 -> v_0 as its first operation, and it is possible that this succeeds. Other thread wit index X then replaces v_0 -> v_X and succeeds as well - voila, fail.

**Comment by pruivo** [comment]
just to transcript the chat to here:

* use ```PESSIMISTIC``` locking instead of ```OPTIMISTIC``` 
* avoid same ```expected``` and ```targetValue```
* locks are released asynchronously after the operation returns (tx mode). It should do some retries instead of failing immediately.

**Comment by rvansa** [comment]
@Sanne And wrt. transactional caches, you need to enable write skew check (+ RR isolation and simple versioning), otherwise this is expected behaviour. Yes, we know that not having WSC on by default sucks and we keep forgetting to change the default since 7.x or so.

**Comment by Sanne** [comment]
Thanks @rvansa and @pruivo ! Great hints. I somehow forgot about those, yes we discussed it years ago but I guess I thought we were beyond the dark ages :D

**Comment by Sanne** [comment]
I'll close this for now.

**Pull request closed without merging**
