### PR TITLE
ISPN-10798 JCache annotations attribute cacheResolverFactory is ignored 

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-10798
~~https://issues.jboss.org/browse/ISPN-10745~~
https://issues.jboss.org/browse/ISPN-10804

* Added support for custom `CacheResolverFactory` implementations
* Deprecated managed interceptors
* Fixed exclusion of interception TCK tests

### CODE REVIEW

**Comment by tristantarrant** [comment]
Quite a few cdijcache failures

**Comment by danberindei** [comment]
The reason for the failures is that split packages are bad both with CDI and OSGi (our jcache modules are OSGi bundles), so the only way to support remote caches with the existing interceptors was to move all the CDI interceptors to the `jcache-commons` module. But some of the interceptors (the *managed* ones, `InjectedCache*Interceptor`) require core classes like `EmbeddedCacheManager` by definition, so I had to somehow inject a bean from the `jcache-embedded` module into a bean in the `jcache-commons` module.

The `cdi-jcache-it` failures were easy to fix, I just added the moved classes to the deployment in `org.infinispan.integrationtests.cdijcache.Deployments`. But that was not an option in the `wildfly-modules` ITs, because there `jcache-commons` and `jcache-embedded` are actual JBoss modules and get their own isolated `BeanManager` instance, and they cannot see each other's beans.

I also had a backup plan, to put only some common classes in `jcache-commons`, but to keep the CDI interceptors in `jcache-embedded` and to add some remote-specific interceptors in a new package in `jcache-remote`. I made some progress, but I had a conflict with #7428, because now `DefaultCacheKey` depends on `MarshallableUserObject`, a core class, so I can't move it to `jcache-commons` anymore.

I deprecated the *managed* interceptors, so when we shouldn't worry about moving them or split packages in 11.0 at least :)

**Comment by danberindei** [comment]
I configured the TCK to use `JavaSerializationMarshaller` and added the needed classes to the whitelist to fix the test failures.

**Comment by ryanemerson** [comment]
@danberindei I'll give a proper review later on today, but for the `JavaSerializationMarshaller` NPE there is a Jira https://issues.jboss.org/browse/ISPN-10865

**Comment by danberindei** [comment]
@ryanemerson I rebased and removed the NPE commit

**Comment by ryanemerson** [comment]
@danberindei Still lots of failures on the CI:

```java

org.jsr107.tck.annotation.InterceptionUsingDefaultCacheNameTest.test_AT_CacheResult
org.jsr107.tck.annotation.InterceptionUsingDefaultCacheNameTest.test_AT_CacheResult_UsingAt_CacheKeyParam
org.jsr107.tck.annotation.InterceptionUsingDefaultCacheNameTest.test_AT_CacheRemoveEntry
org.jsr107.tck.annotation.InterceptionUsingDefaultCacheNameTest.test_AT_CacheRemoveAll
org.jsr107.tck.integration.CacheWriterTest.shouldWriteThoughUsingPutAll_partialSuccess
org.infinispan.configuration.ConfigurationUnitTest.testSchema
org.infinispan.configuration.JsonSerializationTest.testLatestVersion
org.jsr107.tck.event.CacheListenerTest.testFilteredListener[true]
org.jsr107.tck.event.CacheListenerTest.testBrokenCacheEntryListener[true]
org.jsr107.tck.event.CacheListenerTest.testCacheEntryListener[true]
org.jsr107.tck.event.CacheListenerTest.testFilteredListener[false]
org.jsr107.tck.event.CacheListenerTest.testBrokenCacheEntryListener[false]
org.jsr107.tck.event.CacheListenerTest.testCacheEntryListener[false]
```

**Comment by ryanemerson** [comment]
@danberindei Do you think it's possible to get this in for .Final? There are still quite a few related failures.

**Comment by tristantarrant** [comment]
@danberindei closing this PR. Please reopen when you are ready to work on it again.

**Pull request closed without merging**
