### PR TITLE
[14.0] SIFS and persistence changes

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-15377
https://issues.redhat.com/browse/ISPN-15394
https://issues.redhat.com/browse/ISPN-15253
https://issues.redhat.com/browse/ISPN-15466
https://issues.redhat.com/browse/ISPN-15675
https://issues.redhat.com/browse/ISPN-15169

### CODE REVIEW

**Comment by tristantarrant** [comment]
Crashed tests:
23:18:06  org.infinispan.persistence.sifs.SoftIndexFileStoreFunctionalTest

**Comment by wburns** [comment]
Updated to remove the completion stages changes as I don't think it is necessary yet and added in changes to not attempt pmem every time for a given directory (if first fails then don't use it again)

**Review by jabolina — APPROVED** [review]

**Comment by jabolina** [comment]
Thanks, @wburns!

**Comment by FireBurn** [comment]
Can any of these be backported to 13.0.x too?

**Comment by tristantarrant** [comment]
According to https://github.com/infinispan/infinispan/blob/main/SECURITY.md we no longer maintain anything older than 14.0.
However, if you want to backport this yourself, we'll gladly welcome your PR and we can handle the release.

**Comment by FireBurn** [comment]
Thanks, I'll see what I can do

**Pull request merged**
