### PR TITLE
ISPN-6382 Upgrade to Hibernate Search 5.6.0.Alpha3

### PR DESCRIPTION
**Pull request by Sanne**
- https://issues.jboss.org/browse/ISPN-6382

### CODE REVIEW

**Comment by Sanne** [comment]
I'd prefer this could be applied also on 8.2.x ?

**Comment by gustavonalle** [comment]
pulling

**Comment by gustavonalle** [comment]
Applied to master and 8.2.x, thanks @Sanne !

**Comment by Sanne** [comment]
great, thanks! let me know if it finally fixes all unstable tests..

**Pull request closed without merging**
