### PR TITLE
ISPN-12441 Upgrade to protostream 4.4.0.Alpha2

### PR DESCRIPTION
**Pull request by anistor**
https://issues.redhat.com/browse/ISPN-12441

### CODE REVIEW

**Comment by anistor** [comment]
A side effect of this is that ```org.infinispan.persistence.m.event_logger.UUID``` protobuf type becomes ```org.infinispan.persistence.event_logger.UUID``` and is defined in a different file. As far as I can tell this has no impact of backward compat. I can provide more details on my view if this opinion is challenged.

**Comment by tristantarrant** [comment]
@anistor I fixed an issue with Docker on the CI agent, but there are now a number of related failures.

**Comment by anistor** [comment]
The failures are due to the change of default value of the ```@AutoProtoSchemaBuilder.service``` flag. Need to turn it off explicitly. This is the perfect example of why I insisted we need to have a way to bypass the automatic discovery of SCIs.

**Comment by anistor** [comment]
The failures are fixed now.

**Comment by anistor** [comment]
Rebased and pushed some more minor cleanups. This should be ready now @tristantarrant @gustavonalle

**Review by gustavonalle — APPROVED** [review]

**Comment by gustavonalle** [comment]
21 failures on Eviction tests, could this be related?

**Comment by anistor** [comment]
I don't think these failures are related. There's a huge number of new failures (mostly related to ExceptionEvictionTest) in build #14 vs. build #13 and the only difference between them is a squashed commit. Build #13 has just 3 failures. I suspect ExceptionEvictionTest is a bit unstable nowadays. I could not reproduce any of those failures while running locally. And none fails when executef individually from IDE. But let's have a couple more CI runs and see

**Comment by anistor** [comment]
More CI builds, more unrelated failures.

**Comment by ryanemerson** [comment]
Thanks @anistor

**Pull request merged**
