### PR TITLE
ISPN-11889 Remove deprecated parser attributes

### PR DESCRIPTION
**Pull request by danberindei**
~~https://issues.redhat.com/browse/ISPN-11889~~

### CODE REVIEW

**Comment by danberindei** [comment]
Updated to remove test XML configurations for versions 7.0-8.5.

**Comment by danberindei** [comment]
After the Zulip discussion, I reverted the attribute removals and I only changed the parser to reject some replication queue attributes that were silently ignored.

**Comment by ryanemerson** [comment]
LGTM, just restarting the CI build as the last one was interrupted.

**Comment by ryanemerson** [comment]
Thanks @danberindei

**Pull request merged**
