### PR TITLE
[14.0.x] ISPN-14361 Create Hibernate 2LC implementation for Hibernate 6.2.x

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-14361

Cherry-picked commit from https://github.com/infinispan/infinispan/pull/10570 and then added back in cache 6.0 support as appropriate.

### CODE REVIEW

**Comment by wburns** [comment]
Waiting until Final is released, so we don't have a dependency on a non final version.

**Comment by tristantarrant** [comment]
CR4 is out

**Comment by wburns** [comment]
> CR4 is out

Updating

**Comment by wburns** [comment]
It looks like 6.2.0 was tagged yesterday as well, but it isn't in maven yet. Updated to CR4, needs squash after CI here confirms it is okay.

**Comment by pferraro** [comment]
@wburns 6.2.0.Final is available in maven central now.

**Comment by wburns** [comment]
Updating to 6.2.0.Final

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
