### PR TITLE
ISPN-15963 Protostream 5.0.2.Final

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-15963

### CODE REVIEW

**Comment by pruivo** [comment]
@tristantarrant do you mind adding 
```java
int BITSET = CORE_LOWER_BOUND + 13;
```
after this line:
https://github.com/infinispan/infinispan/blob/c28ddb964f4b76cba1da0d1d4ca3d18abafb857a/commons/all/src/main/java/org/infinispan/commons/marshall/ProtoStreamTypeIds.java#L65
so we keep track of the type id assigned to `BitSetAdapter:
https://github.com/infinispan/protostream/blob/15470cf1a229b33ea891227a26f93aad216b0752/types/src/main/java/org/infinispan/protostream/types/java/util/BitSetAdapter.java#L10

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Comment by ryanemerson** [comment]
Argh sorry @pruivo, I merged just as your comment appeared

**Comment by pruivo** [comment]
no problem @ryanemerson. I've opened a PR here: https://github.com/infinispan/infinispan/pull/12272

**Pull request merged**
