### PR TITLE
ISPN-14435 Backwards compatibility broken with InvalidMagicIdException

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.redhat.com/browse/ISPN-14435

### CODE REVIEW

**Review by karesti — APPROVED** [review]
LGTM

**Comment by wburns** [comment]
Rerunning CI, looks like it got the OOM as well 😢

**Comment by tristantarrant** [comment]
Is testDistExecPutGet([D]) – org.infinispan.client.hotrod.ExecTest related ?

**Comment by pruivo** [comment]
@tristantarrant it is not related. It looks like a deadlock caused by the script `test-put-get-dist.js` being executed in all nodes at the same time. 
```
Caused by: org.infinispan.util.concurrent.TimeoutException: ISPN000299: Unable to acquire lock after 10 seconds for key dist-key and requestor GlobalTransaction{id=60, addr=ExecTest-NodeA, remote=true, xid=Xid{formatId=131077, globalTransactionId=00000000000000000000FFFF0A00956600008A7D63BC12200000007E31,branchQualifier=00000000000000000000FFFF0A00956600008A7D63BC12200000007F0000000000000000}, internalId=-1}. Lock is held by GlobalTransaction{id=59, addr=ExecTest-NodeB, remote=false, xid=Xid{formatId=131077, globalTransactionId=00000000000000000000FFFF0A00956600008A7D63BC12200000007A31,branchQualifier=00000000000000000000FFFF0A00956600008A7D63BC12200000007B0000000000000000}, internalId=-1}
```

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
