### PR TITLE
ISPN-9590 ExtendedSearchWorkCreator and SearchWorkCreatorContext are …

### PR DESCRIPTION
**Pull request by anistor**
…no longer needed

https://issues.redhat.com/browse/ISPN-9590
https://issues.redhat.com/browse/ISPN-11132

The fix includes relevant stuff from https://github.com/infinispan/infinispan/pull/7725

### CODE REVIEW

**Comment by anistor** [comment]
Once this runs in CI we'll need to backport to 9.4.x a subset of the changes (only the move to cacheStarting) @gustavonalle

**Comment by gustavonalle** [comment]
I found a couple of issues in the reproducer: 
1)  It fails about 10% of the time
2)  It does not test TX caches

I am fixing 1) and adding a TX test to it. BTW, at least on 9.4, even with this fix TX caches don't index during State Transfer...

**Comment by gustavonalle** [comment]
FYI, I added TX to the reproducer, and it fails on 9.4.x even with the lifecycle fix. This is probably a separate problem not related to registry but still should fall under this JIRA

**Comment by anistor** [comment]
CI looks good.

**Comment by gustavonalle** [comment]
Merged, thanks @anistor !

**Pull request merged**
