### PR TITLE
ISPN-5121 The CDIDistributedTaskLifecycle should not do anything when CDI is not available

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5121

For master and 7.0.x

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8231/tristantarrant:ISPN-5121/distexec_without_cdi](http://ci.infinispan.org/viewLog.html?buildId=22621&buildTypeId=bt9&guest=1) for 0737cbf14bd977dc4319ac7c5f6b1cadf33603d7
Tests: 11218, 3 failed (2 new), 23 ignored. Build time: 01:52:07

Failed tests detected
* (new) TestSuite: org.infinispan.api.ConditionalOperationPrimaryOwnerFailTest.clearContent


* (new) TestSuite: org.infinispan.notifications.cachelistener.cluster.ClusterListenerDistAddListenerTest.testMemberJoinsWhileClusterListenerInstalledDuplicate


* (since 07-Jan-2015) org.infinispan.server.test.query.ManualIndexingIT.testManualIndexing



Error message is logged

Build duration (secs) is too large: 6713

**Comment by wburns** [comment]
Pulling...

**Comment by wburns** [comment]
Integrated in to master, thanks @tristantarrant !

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8267/tristantarrant:ISPN-5121/distexec_without_cdi](http://ci.infinispan.org/viewLog.html?buildId=22703&buildTypeId=bt9&guest=1) for 0737cbf14bd977dc4319ac7c5f6b1cadf33603d7
Tests: 11232, 2 failed (2 new), 23 ignored. Build time: 02:12:17

Failed tests detected
* (new) TestSuite: org.infinispan.api.AsyncAPITest.testAsyncMethodWithLifespanAndMaxIdle


* (new) TestSuite: org.infinispan.notifications.cachelistener.cluster.ClusterListenerReplTest.testPrimaryOwnerGoesDownAfterBackupRaisesEvent



Error message is logged

Build duration (secs) is too large: 7917

**Pull request closed without merging**
