### PR TITLE
ISPN-6445 PreloadingWithWriteBehindTest.testIfCanLoadKeysConcurrently

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-6445

* Deleted PreloadingWithWriteBehindTest.
* Preloading with async stores was already tested by
PreloadWithAsyncStoreTest.
* New test for parallel iteration with async stores,
AsyncStoreParallelIterationTest.

### CODE REVIEW

**Comment by slaskawi** [comment]
Looks good to me

**Comment by slaskawi** [comment]
Could we squash those 2 PRs: https://github.com/infinispan/infinispan/pull/4198 and https://github.com/infinispan/infinispan/pull/4191 ?

**Comment by danberindei** [comment]
Sorry @slaskawi, I forgot to add the PR link in JIRA yesterday :)
Closing this one.

**Comment by danberindei** [comment]
Reopening, the other is actually a different issue but I copied the wrong JIRA reference.

**Comment by slaskawi** [comment]
There are 2 persistence test failures... they might be related.

**Comment by slaskawi** [comment]
Otherwise looks good to me

**Comment by slaskawi** [comment]
Testing locally and pushing if it's fine

**Comment by slaskawi** [comment]
Pushed to master. Thanks!

**Comment by danberindei** [comment]
@slaskawi looks like those test failures were indeed related, they only failed on this PR.

**Comment by danberindei** [comment]
@slaskawi Never trust your local build! Individual CI builds aren't the ultimate source of truth either, but the test history is usually much more helpful:

http://ci.infinispan.org/project.html?projectId=Infinispan&testNameId=-3796303331599289332&tab=testDetails

**Comment by slaskawi** [comment]
@danberindei hahaha that will teach me :) BTW - no worries and thanks for quick reaction!

**Pull request closed without merging**
