### PR TITLE
ISPN-9583 KeyTransformationHandler should be a component and should have a reference to the cache's classloader

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-9583

### CODE REVIEW

**Comment by anistor** [comment]
Rebased.

**Comment by danberindei** [comment]
Includes https://github.com/infinispan/infinispan/pull/6304 I see...

**Comment by anistor** [comment]
Rebased. Also added back QueryInterceptor.getSearchWorkCreator/setSearchWorkCreator which I previoulsy removed. But these should be removed in a separate jira because might still be used by other parties.

**Comment by gustavonalle** [comment]
LGTM, but need to see CI

**Comment by anistor** [comment]
I think CI has already popped the Friday champagne bottle

**Comment by anistor** [comment]
There was a whitespace related checkstyle violation. Fixed.

**Comment by gustavonalle** [comment]
Merged, thanks!

**Comment by anistor** [comment]
Thanks @gustavonalle !

**Pull request merged**
