### PR TITLE
ISPN-8064 Clean up public API javadocs

### PR DESCRIPTION
**Pull request by tristantarrant**
- remove @public doclet from scripting, cdi commons, rest internals, etc
- include rocskdb and soft-index in javadocs
- consistent naming of Hot Rod
- better grouping of correlated javadocs
- minor cleanups

https://issues.jboss.org/browse/ISPN-8064

### CODE REVIEW

**Comment by pruivo** [comment]
in javadoc-embedded and javadoc-all pom files, they have a link to `http://docs.jboss.org/hibernate/search/4.5/api/`. shouldn't it be updated to 5.8?

Also, there is an additional dependency that may need update.
```
<additionalDependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-core</artifactId>
    <version>4.3.8.Final</version>
</additionalDependency>
```

**Comment by anistor** [comment]
```http://lucene.apache.org/core/4_0_0/core/``` is old too

**Comment by tristantarrant** [comment]
Updated

**Comment by anistor** [comment]
Integrated in master. Thanks @tristantarrant !

**Pull request closed without merging**
