### PR TITLE
[10.1.x] ISPN-11179 Ignore OkHttp thread leaks and close our responses

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-11179

Backport of #7784

### CODE REVIEW

**Comment by tristantarrant** [comment]
@danberindei you created the PR against master...

**Comment by danberindei** [comment]
I was playing with the `gh` CLI and forgot to check that it selected the right base branch.
Luckily I found the option to change the base branch, so I didn't have to open a new PR :)

**Comment by tristantarrant** [comment]
The build is broken

**Comment by tristantarrant** [comment]
Conflicts now

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
