### PR TITLE
ISPN-8729 Use async operations in Hot Rod server

### PR DESCRIPTION
**Pull request by rvansa**
https://issues.jboss.org/browse/ISPN-8729

Highlights:

* removes context switch by using async API
* structures the cache/counter/multimap operations nicely
* reduces number of lambda allocations in counters (caching lambdas for the other async APIs as well)

Depends on #5701

### CODE REVIEW

**Comment by rvansa** [comment]
run performance tests please
cs-hotrod

**Comment by diegolovison** [comment]
run performance tests please
cs-hotrod

**Comment by rvansa** [comment]
run performance tests please
cs-hotrod
[UDP 1kB]

**Comment by rvansa** [comment]
Gustavo has pointed out that in some situations the commands are still blocking. We need to detect these and derail the execution then.

So far I know that a blocking could be caused by:
* indexing
* persistence

**Comment by diegolovison** [comment]
run performance tests please
cs-hotrod
[UDP 1kB]

**Comment by rvansa** [comment]
run performance tests please
cs-hotrod
[UDP 1kB]

**Comment by rvansa** [comment]
run performance tests please
cs-hotrod
[UDP 1kB]

**Comment by rvansa** [comment]
run performance tests please
cs-hotrod
[UDP 1kB]

**Comment by rvansa** [comment]
There is still some regression (though < 5%), will investigate...

**Comment by rvansa** [comment]
I've realized critical flaw, need to fix this...

**Comment by rvansa** [comment]
run performance tests please
cs-hotrod
[UDP 1kB]

**Comment by diegolovison** [comment]
run performance tests please
cs-hotrod
[UDP 1kB]

**Comment by diegolovison** [comment]
run performance tests please
cs-hotrod
[UDP 1kB]

**Comment by diegolovison** [comment]
run performance tests please
cs-hotrod
[UDP 1kB]

**Comment by rvansa** [comment]
run performance tests please
cs-hotrod
[UDP 1kB]

**Comment by rvansa** [comment]
run performance tests please
cs-hotrod
[UDP 1kB]

**Comment by rvansa** [comment]
run performance tests please
cs-hotrod
[UDP 1kB]

**Comment by rvansa** [comment]
@tristantarrant yep, there's a 1% regression on reads but from perf POV I think this is good enough now. We might be able to shave off some more allocations in the future.
We should get #5701 in (@pruivo is worried about some IndexingDuringStateTransferTest.testMergeRemove failures in CI) and then fix the bunch of integration tests. Hopefully next week I could get it to a better shape.

**Comment by rvansa** [comment]
run performance tests please
cs-hotrod

**Comment by rvansa** [comment]
CI seems to dislike this PR and I don't know why... will try to reopen it as another PR.

**Comment by tristantarrant** [comment]
I see we have ~+5% on 10 threads and ~-5% on 100 threads.

**Comment by rvansa** [comment]
@tristantarrant Yes, with 10kB entries. With 1kB entries the 100 threads regression is -1.7% and 10 threads get the 11% boost. Do you want me to spend time trying to improve the 100 threads case, within this PR?

**Comment by tristantarrant** [comment]
No, it can wait for 9.3

**Pull request closed without merging**
