### PR TITLE
ISPN-6494 Change the default bundler to transfer-queue

### PR DESCRIPTION
**Pull request by danberindei**
Do not close ISPN-6494, bundlers still need evaluating.

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please

**Comment by danberindei** [comment]
@diegolovison could you make sure the performance tests run?

**Comment by diegolovison** [comment]
It is running

**Comment by diegolovison** [comment]
http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/19128

**Comment by danberindei** [comment]
@diegolovison please trigger another run now, I have reverted the DONT_BUNDLE commit.

**Comment by diegolovison** [comment]
Benchmarking the commit `6814ebd82918f4eb509baf1444c3f73462be38c3`

**Comment by diegolovison** [comment]
@danberindei http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/19131

**Comment by danberindei** [comment]
I brought back DONT_BUNDLE, which should fix the tests (and lower throughput) @tristantarrant

**Comment by danberindei** [comment]
Updated to remove the DONT_BUNDLE flag and to process messages on the non-blocking executor instead.

@gustavolira please trigger another perf-ack job
UDP with 1kb values, just like http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/19131

**Comment by gustavolira** [comment]
> http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/19131

@danberindei http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/19132

**Comment by danberindei** [comment]
Thanks @gustavolira, unfortunately my change was wrong and I hadn't removed DONT_BUNDLE so we need another run.

I really hope perf-ack is going to look good for the latest commit, because it would be awesome to have a PR integrated with 0 test failures :)

**Comment by gustavolira** [comment]
@danberindei http://perfrepo.mw.lab.eng.bos.redhat.com/reports/tableComparisonReport/19135

**Comment by danberindei** [comment]
@tristantarrant the benchmark looks good to me (although for some of the tests it's still better delivering all the messages of a batch on the same thread).

**Comment by tristantarrant** [comment]
Merged !

**Comment by danberindei** [comment]
@tristantarrant @gustavolira so sorry, while squashing the commits I lost most of the changes for ISPN-12908 and brought back the DONT_BUNDLE flag.

@gustavolira could you trigger perf-ack again for the current HEAD (commit a11c00ce80ba4d199b454f568c042f10dda348f3)?

**Pull request merged**
