### PR TITLE
ISPN-6315 Add test for remote query using the client as-modules with annotation based protostream marshallers

### PR DESCRIPTION
**Pull request by anistor**
jira: https://issues.jboss.org/browse/ISPN-6315
https://issues.jboss.org/browse/ISPN-6312

### CODE REVIEW

**Comment by anistor** [comment]
Protostream 3.0.5 is not released yet.

**Comment by anistor** [comment]
Protostream is now released but it takes a bit of time until the repo is synced.

**Comment by tristantarrant** [comment]
Running this locally gave me:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.47 sec <<< FAILURE! - in org.infinispan.test.integration.as.HotRodQueryIT
testRemoteQuery(org.infinispan.test.integration.as.HotRodQueryIT)  Time elapsed: 0.428 sec  <<< ERROR!
org.infinispan.client.hotrod.exceptions.HotRodClientException: java.lang.RuntimeException: protostream.com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
protostream.com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at org.infinispan.client.hotrod.impl.protocol.Codec20.checkForErrorsInResponseStatus(Codec20.java:343)
	at org.infinispan.client.hotrod.impl.protocol.Codec20.readPartialHeader(Codec20.java:132)
	at org.infinispan.client.hotrod.impl.protocol.Codec20.readHeader(Codec20.java:118)
	at org.infinispan.client.hotrod.impl.operations.HotRodOperation.readHeaderAndValidate(HotRodOperation.java:56)
	at org.infinispan.client.hotrod.impl.operations.QueryOperation.executeOperation(QueryOperation.java:66)
	at org.infinispan.client.hotrod.impl.operations.QueryOperation.executeOperation(QueryOperation.java:28)
	at org.infinispan.client.hotrod.impl.operations.RetryOnFailureOperation.execute(RetryOnFailureOperation.java:54)
	at org.infinispan.client.hotrod.impl.query.RemoteQuery.executeQuery(RemoteQuery.java:61)
	at org.infinispan.client.hotrod.impl.query.RemoteQuery.list(RemoteQuery.java:51)
	at org.infinispan.test.integration.as.HotRodQueryIT.testRemoteQuery(HotRodQueryIT.java:72)

```

**Comment by anistor** [comment]
I see the same error on CI http://ci.infinispan.org/project.html?projectId=Infinispan&testNameId=-5341916214441301521&tab=testDetails but I cannot reproduce it locally.

**Comment by anistor** [comment]
HotRodClientIT and HotRodQueryIT run sequentially and use the same server and cache. If HotRodClientIT runs first it will leave garbage in the cache that makes HotRodQueryIT fail. One possible fix is to clear the cache before running.

**Comment by tristantarrant** [comment]
Pushed, thanks

**Pull request closed without merging**
