### PR TITLE
ISPN-5551 Include a private "slotted" version of JBoss Marshalling to avoid conflicts with the one provided by the AS

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5551

Please apply to both master and 7.2.x

### CODE REVIEW

**Comment by tristantarrant** [comment]
None of the CI failures are related to this

**Comment by galderz** [comment]
Are you sure this failure is not related to this?

```
org.infinispan.server.test.client.hotrod.HotRodCustomMarsha…rIteratorIT(localmode-udp).org.infinispan.server.test.client (1) hotrod.HotRodCustomMarshallerIteratorIT
```

https://gist.github.com/galderz/9d7b3789a9579a22411f

**Comment by gustavonalle** [comment]
@galderz This specific failure should be solved with https://github.com/infinispan/infinispan/pull/3567

**Comment by galderz** [comment]
@gustavonalle Right, just spotted that it started failing when WF9 was integrated. I'll go ahead and integrate this.

**Comment by galderz** [comment]
Applied both to master and 7.2.x

**Comment by galderz** [comment]
Integrated, please make sure you follow guidelines for git commit messages :) (see [here](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html))

**Pull request closed without merging**
