### PR TITLE
Ispn 5127

### PR DESCRIPTION
**Pull request by wburns**
This is here to try to get a failure with some sort of tracing to help figure out why this is failing.

### CODE REVIEW

**Comment by slaskawi** [comment]
Hey @wburns ! Did you manage to collect test results? May I close this one?

**Comment by wburns** [comment]
Unfortunately this still hasn't reproduced the issue out of the half a dozen runs or so.  We can close it for now, but it seems this test hasn't failed in almost a month now.

**Comment by wburns** [comment]
I will change the messages over to trace level and then we can hope that the test fails on a TRACE ci run.

**Comment by wburns** [comment]
Updated to use trace level instead so it can be committed to master in hopes that this test will eventually fail when TRACE is enabled.

**Comment by slaskawi** [comment]
Looking

**Comment by slaskawi** [comment]
Squashed and integrated. Thanks!

**Pull request closed without merging**
