### PR TITLE
ISPN-7364 SingleFrameDecoder is not applied to hot rod tests

### PR DESCRIPTION
**Pull request by wburns**
* Make sure hotrod tests use single frame decoder
* Fixed replay bugs that snuck in

https://issues.jboss.org/projects/ISPN/issues/ISPN-7358

### CODE REVIEW

**Comment by wburns** [comment]
Still need to wait for CI to verify not everything is broken now

**Comment by galderz** [comment]
@wburns I've run the JS client test and still fails with your changes. You have tried to run the `HotRodPipeTest` that I created for #4767?

**Comment by galderz** [comment]
Actually, I might have been running the wrong snapshot, trying again...

**Comment by galderz** [comment]
Indeed I was testing the wrong thing! I've retested with the proper build for the branch in this PR and the test works fine :)

As mentioned on IRC, can you also add the changes on `Util.java` from #4767 and add some TRACE log messages to better detect potential issues? 

Also, please add `HotRodPipeTest.java` so that we have a backup in case you end up reverting the single frame decoder again ;). The number of requests might need decreasing as well as slightly increasing the `eventually` call timeout.

Thanks @wburns!

**Comment by wburns** [comment]
Sure I can add another commit with the additional tests and then mark it as ready to review.

**Comment by galderz** [comment]
Hmmmm, seeing NullPointeExceptions with the latest changes...

```
2017-01-19 10:08:54,390 DEBUG [org.infinispan.server.hotrod.HotRodExceptionHandler] (HotRodServerWorker-9-1) Exception caught: org.infinispan.server.hotrod.HotRodException
	at org.infinispan.server.hotrod.HotRodDecoder.decode(HotRodDecoder.java:130)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.infinispan.server.core.transport.StatsChannelHandler.channelRead(StatsChannelHandler.java:26)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

2017-01-19 10:08:54,390 TRACE [org.infinispan.server.hotrod.HotRodEncoder] (HotRodServerWorker-9-1) Encode msg ERROR{version=25, messageId=83, cacheName='', clientIntel=3, operation=ERROR, status=ServerError, topologyId=0, msg=java.lang.NullPointerException}
```

**Comment by galderz** [comment]
Indeed, the NPE comes from:

```
   public static String toHexString(byte input[]) {
      return toHexString(input, input.length);
   }
```

It should be changed to:

```
   public static String toHexString(byte input[]) {
      return input == null ? "null" : toHexString(input, input.length);
   }
```

**Comment by wburns** [comment]
Ah yes I will fix that up.

**Comment by wburns** [comment]
Should be fixed now.

**Comment by galderz** [comment]
Thx @wburns, one last quick test...

**Comment by galderz** [comment]
Looks good, integrating...

**Pull request merged**
