### PR TITLE
ISPN-12785 List protobuf types in the REST API

### PR DESCRIPTION
**Pull request by karesti**
https://issues.redhat.com/browse/ISPN-12785

### CODE REVIEW

**Comment by karesti** [comment]
@fax4ever would be perfect if we could add also a "indexed" types only. The code for types with indexing annotations seemed a bit complicated to use and refactor in the same PR. Let me know what you think about it. 
we also need a REST API (issue already created) that tells which caches are actually indexing a type in a particular schema, to be able to prevent the user about the changes (what we already discussed)

**Comment by fax4ever** [comment]
> @fax4ever would be perfect if we could add also a "indexed" types only. The code for types with indexing annotations seemed a bit complicated to use and refactor in the same PR. Let me know what you think about it. we also need a REST API (issue already created) that tells which caches are actually indexing a type in a particular schema, to be able to prevent the user about the changes (what we already discussed)

I think that we can use the Index metamodel to know at runtime if a message is indexed or not, that would be basically the same that parse the annotations again, without doing it.

**Comment by fax4ever** [comment]
Pull request looks very good anyway

**Review by fax4ever — APPROVED** [review]
The list of indexed entities is present at cache level, not a global level, at `org.infinispan.search.mapper.mapping.SearchMapping#allIndexedEntityNames`

**Comment by fax4ever** [comment]
Merged, thank you @karesti!

**Pull request merged**
