### PR TITLE
ISPN-8109 Upgrade RocksDB to 5.6.1

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-8109

### CODE REVIEW

**Comment by tristantarrant** [comment]
https://repo.maven.apache.org/maven2/org/rocksdb/rocksdbjni/5.6.1/

**Comment by ryanemerson** [comment]
@tristantarrant Updated. I should have waited a few more hours

**Comment by tristantarrant** [comment]
Merged to master, thanks

**Comment by gustavonalle** [comment]
This cause test failures on MacOS:

```
[TestSuiteProgress] Tests succeeded: 2, failed: 0, skipped: 0
SUREFIRE-859: Assertion failed: (is_last_reference), function ~ColumnFamilyData, file db/column_family.cc, line 457.
/bin/sh: line 1:  6617 Abort trap: 6           /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/bin/java -Xmx2G -Dsun.nio.ch.bugLevel -jar /infinispan/persistence/rocksdb/target/surefire/surefirebooter5673042314039179281.jar /infinispan/persistence/rocksdb/target/surefire/surefire7951183691735316134tmp /infinispan/persistence/rocksdb/target/surefire/surefire_02365954805080770500tmp
```

**Comment by ryanemerson** [comment]
@gustavonalle It appears that this failure is limited to Mac as it does not occur for me locally or on CI. Could you look into the issue? I don't have a means to investigate as I don't have access to a Mac.

**Comment by gustavonalle** [comment]
Np @ryanemerson I'll look into it https://issues.jboss.org/browse/ISPN-8135

**Pull request merged**
