### PR TITLE
ISPN-13086 EventLoggerCompatibilityTest.testReadWriteFrom11EventCache…

### PR DESCRIPTION
**Pull request by wburns**
… always fails

* Ensured expiration was not applied

https://issues.redhat.com/browse/ISPN-13086

### CODE REVIEW

**Comment by wburns** [comment]
All I did was change `org.infinispan.server.logging.events.LifecycleCallbacks` to not apply the expiration and started up two servers with default configuration and shut them down. Then copied over the dat file.

**Comment by danberindei** [comment]
Thanks Will!

**Comment by ryanemerson** [comment]
Thanks @wburns. Can you backport to 12.1.x when you get a chance?

**Comment by wburns** [comment]
> Thanks @wburns. Can you backport to 12.1.x when you get a chance?

Ah, yes, totally forgot this was in 12.1.x as well.

**Pull request merged**
