### PR TITLE
ISPN-10618 Expiration creation/lastUsed timestamp are lost when prelo…

### PR DESCRIPTION
**Pull request by wburns**
…ading from store

https://issues.jboss.org/browse/ISPN-10618

### CODE REVIEW

**Comment by wburns** [comment]
Failures appear related https://ci.infinispan.org/job/Infinispan/job/PR-7347/1/

**Comment by wburns** [comment]
Should hopefully be fixed now :)

**Comment by pruivo** [comment]
@wburns needs rebase

**Comment by wburns** [comment]
Rebased and change commit JIRA to other one

**Comment by pruivo** [comment]
@wburns there are failures in `*StorePreloadTest`.

**Comment by wburns** [comment]
Weird, I fixed this earlier. I must have undone something at some point. Issue was just that it was waiting on the wrong cache to complete rehash.

**Comment by wburns** [comment]
Should be fixed.

**Comment by pruivo** [comment]
integrated! thanks @wburns !

**Pull request merged**
