### PR TITLE
ISPN-15173 Exceptional HEAD requests return a non-zero Content-Length…

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-15173

@tristantarrant I wasn't sure whether the `RestRequestHandler` or `ResponseWriter` was the correct place to fix this, in the end I went with the former so that we didn't have to repeat the logic across the Enum implementations.

### CODE REVIEW

**Review by tristantarrant — APPROVED** [review]
LGTM

**Comment by pruivo** [comment]
@ryanemerson a quick search shows some methods that return a non-null entity or set content-length != 0 when method `HEAD` is used. Example: https://github.com/infinispan/infinispan/blob/19157d5ddd0cedbe95f5678a81629da39ffd87db/server/rest/src/main/java/org/infinispan/rest/resources/BackupManagerResource.java#L111-L114

Should we fix those?

**Review by pruivo — APPROVED** [review]

**Comment by pruivo** [comment]
LGTM, waiting for the CI results.

**Comment by tristantarrant** [comment]
The testsuite crashed during the rest tests

**Comment by ryanemerson** [comment]
> The testsuite crashed during the rest tests

I have re-ran a few times locally without issue so I don't think the crash is related to my changes. I have rebased and repushed, let's see what CI says this time.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
