### PR TITLE
ISPN-6241 Upgrade commons-logging to 1.2 to avoid pulling in unwanted…

### PR DESCRIPTION
**Pull request by tristantarrant**
… dependencies

https://issues.jboss.org/browse/ISPN-6241

Apply to master and cherry-pick to 8.2.x

### CODE REVIEW

**Comment by pruivo** [comment]
for some strange reason (since only 1 line changed), it needs rebase.

**Comment by galderz** [comment]
Fixed rebase and pushed to master.

**Comment by galderz** [comment]
Integrated in 8.2.x too

**Comment by danberindei** [comment]
@galderz there was a compilation failure :(
http://ci.infinispan.org/viewLog.html?buildId=44102&buildTypeId=bt9

**Comment by galderz** [comment]
Ups! @danberindei Is this fixed now?

**Pull request closed without merging**
