### PR TITLE
ISPN-7063 FunctionalCachestoreTest and FunctionalInMemoryTest random …

### PR DESCRIPTION
**Pull request by rvansa**
https://issues.jboss.org/browse/ISPN-7063

### CODE REVIEW

**Comment by rvansa** [comment]
@danberindei Rebased and added some comments to praise the gods of javadoc.

**Comment by slaskawi** [comment]
Looking

**Comment by slaskawi** [comment]
Let's give CI some time to check it.

**Comment by slaskawi** [comment]
There are over 20 test failures: http://ci.infinispan.org/viewLog.html?buildId=43393&buildTypeId=bt9

Could you please have a look at them?

**Comment by slaskawi** [comment]
hmmm wait.. it looks like TC didn't refresh git...

**Comment by rvansa** [comment]
@slaskawi eh, so is the TC up-to date? Should I do anything?

**Comment by danberindei** [comment]
@rvansa @slaskawi I think TC is building the right commit, refs/pull/4577/merge 9a7376bbbf65bc328bba29d34b06e0eab5826927. It says "No changes" when neither the PR branch nor master changed since the previous build.

The failures look a bit different from what I've been seeing in my local tests, and I haven't been able to reproduce them locally (with TRACE enabled).

**Comment by slaskawi** [comment]
yeah.. those failures look a bit weird... anyway...I'm integrating this into master.

**Pull request merged**
