### PR TITLE
Perf test for Protostream Alpha8

### PR DESCRIPTION
**Pull request by ryanemerson**
DO NOT MERGE

### CODE REVIEW

**Comment by ryanemerson** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/ryanemerson/40e40efb6e73c8c19c8a5d42c3dfe32f/raw/e57b17d984c9816580519c6b2f8a5aede60e601d/PR-7153.xml
jdg_config https://gist.githubusercontent.com/ryanemerson/df5fd0c76241b9ced6b7d8ea92e1d924/raw/83d4c7fe40a0e05e2d980ad895ac883b2d4802d8/PR-7153-DG.xml
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/7ab5cb69e9ff3f8a21051c005da82065/raw/a49f8fe75a9a35e97a2d03b849ce0a02d1e0489c/pr-7153.xml
jdg_config https://gist.githubusercontent.com/diegolovison/18874ececa29431814a34ff0d6d43472/raw/316323a7bf52a9a4419ea40431a9e611ff0fc2b5/pr-7153-dg.xml
custom_library

**Comment by ryanemerson** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/7ab5cb69e9ff3f8a21051c005da82065/raw/a49f8fe75a9a35e97a2d03b849ce0a02d1e0489c/pr-7153.xml
jdg_config https://gist.githubusercontent.com/diegolovison/18874ececa29431814a34ff0d6d43472/raw/316323a7bf52a9a4419ea40431a9e611ff0fc2b5/pr-7153-dg.xml
custom_library

**Comment by ryanemerson** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/ryanemerson/40e40efb6e73c8c19c8a5d42c3dfe32f/raw/99ded6d69066168d604705dccf9128cc564b63e2/PR-7153.xml
jdg_config https://gist.githubusercontent.com/ryanemerson/df5fd0c76241b9ced6b7d8ea92e1d924/raw/8bc5fe883060fd0a4d674e41fcf606f83e86f5cd/PR-7153-DG.xml
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/ryanemerson/40e40efb6e73c8c19c8a5d42c3dfe32f/raw/99ded6d69066168d604705dccf9128cc564b63e2/PR-7153.xml
jdg_config https://gist.githubusercontent.com/ryanemerson/df5fd0c76241b9ced6b7d8ea92e1d924/raw/8bc5fe883060fd0a4d674e41fcf606f83e86f5cd/PR-7153-DG.xml
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/ryanemerson/40e40efb6e73c8c19c8a5d42c3dfe32f/raw/99ded6d69066168d604705dccf9128cc564b63e2/PR-7153.xml
jdg_config https://gist.githubusercontent.com/ryanemerson/df5fd0c76241b9ced6b7d8ea92e1d924/raw/8bc5fe883060fd0a4d674e41fcf606f83e86f5cd/PR-7153-DG.xml
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/ryanemerson/40e40efb6e73c8c19c8a5d42c3dfe32f/raw/99ded6d69066168d604705dccf9128cc564b63e2/PR-7153.xml
jdg_config https://gist.githubusercontent.com/ryanemerson/df5fd0c76241b9ced6b7d8ea92e1d924/raw/8bc5fe883060fd0a4d674e41fcf606f83e86f5cd/PR-7153-DG.xml
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/ryanemerson/40e40efb6e73c8c19c8a5d42c3dfe32f/raw/99ded6d69066168d604705dccf9128cc564b63e2/PR-7153.xml
jdg_config https://gist.githubusercontent.com/ryanemerson/df5fd0c76241b9ced6b7d8ea92e1d924/raw/8bc5fe883060fd0a4d674e41fcf606f83e86f5cd/PR-7153-DG.xml
custom_library
entry_factor 4
skip_build

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/ryanemerson/40e40efb6e73c8c19c8a5d42c3dfe32f/raw/99ded6d69066168d604705dccf9128cc564b63e2/PR-7153.xml
jdg_config https://gist.githubusercontent.com/ryanemerson/df5fd0c76241b9ced6b7d8ea92e1d924/raw/8bc5fe883060fd0a4d674e41fcf606f83e86f5cd/PR-7153-DG.xml
custom_library
entry_factor 4
skip_build

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/ryanemerson/40e40efb6e73c8c19c8a5d42c3dfe32f/raw/99ded6d69066168d604705dccf9128cc564b63e2/PR-7153.xml
jdg_config https://gist.githubusercontent.com/ryanemerson/df5fd0c76241b9ced6b7d8ea92e1d924/raw/8bc5fe883060fd0a4d674e41fcf606f83e86f5cd/PR-7153-DG.xml
custom_library
entry_factor 8
skip_build

**Pull request closed without merging**
