### PR TITLE
ISPN-12549 Fix java.lang.NoClassDefFoundError: [Lorg/jboss/shrinkwrap/api/spec/J…

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-12549

### CODE REVIEW

**Comment by pruivo** [comment]
@tristantarrant didn't work: https://ci.infinispan.org/job/Infinispan/job/PR-8893/1/

**Comment by tristantarrant** [comment]
It did, but you've been tricked by Jenkins which parsed the commit line as an Error...
There is another failure caused by `server/rest` tests not completing correctly most of the time. It is unrelated, but a pain nonetheless

**Comment by pruivo** [comment]
@tristantarrant can you rebase?

**Comment by tristantarrant** [comment]
Rebased and changed the commit message so it won't trigger the error by mistake. I've also created a Jira for this

**Review by pruivo — APPROVED** [review]

**Comment by pruivo** [comment]
integrated! thanks @tristantarrant !

**Pull request merged**
