### PR TITLE
ISPN-7639 PolarionJUnitXMLReporter doesn't report failures in configu…

### PR DESCRIPTION
**Pull request by danberindei**
…ration methods

https://issues.jboss.org/browse/ISPN-7639

### CODE REVIEW

**Comment by danberindei** [comment]
I've included a fix for the HotRodWithStoreTest setup failure that triggered my investigation.

**Comment by alanfx** [comment]
Looks good to me, @danberindei. The JUnit report may end up with configuration method names as the test case name, but that's just something I'll have to deal with.

**Comment by wburns** [comment]
Pulling...

**Comment by wburns** [comment]
Integrated into master, thanks @danberindei !

**Pull request merged**
