### PR TITLE
ISPN-8111 OffHeapBoundedSingleNodeTest.testMultiThreaded fails with

### PR DESCRIPTION
**Pull request by wburns**
trace logging enabled

* Disabled transactions which should let it run faster

https://issues.jboss.org/browse/ISPN-8111

### CODE REVIEW

**Comment by danberindei** [comment]
Please change `OffHeapSingleNodeTest` and `OffHeapMultiNodeTest` as well.

Speaking of which, does the off-heap implementation work differently in single-node vs multi-node?

**Comment by wburns** [comment]
No, should be the same. Just wanted to test different scenarios is all. Obviously missed stores :(

**Comment by wburns** [comment]
Updated to disable transactions in other tests as well.

**Comment by danberindei** [comment]
Integrated, thanks Will!

**Pull request merged**
