### PR TITLE
Ispn 5664 HotRod client expiration fixes

### PR DESCRIPTION
**Pull request by wburns**
https://issues.jboss.org/browse/ISPN-5670
https://issues.jboss.org/browse/ISPN-5664

### CODE REVIEW

**Comment by wburns** [comment]
Waiting for local test run to complete before marking Ready for Review.

**Comment by wburns** [comment]
Tests will fail unfortunately as many places aren't using the correct default metadata.  Fixing...

**Comment by wburns** [comment]
Should be good now.

**Comment by wburns** [comment]
This would be great to also cherry-pick into 7.2.x when completed.

**Comment by galderz** [comment]
Looks good, integrated. Thanks!

**Comment by galderz** [comment]
@wburns Hmmm, I didn't do that...

**Comment by wburns** [comment]
I created another one for 7.2.x already https://github.com/infinispan/infinispan/pull/3649

**Pull request closed without merging**
