### PR TITLE
ISPN-8091 Don't deploy uberjars

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-8091
https://issues.jboss.org/browse/ISPN-8356

Also rename the binary distribution package names to avoid confusion

### CODE REVIEW

**Comment by tristantarrant** [comment]
The corresponding website PR is https://github.com/infinispan/infinispan.github.io/pull/49

**Comment by pruivo** [comment]
@tristantarrant looks good to me. I guess this will be tested in the next release right?

**Comment by tristantarrant** [comment]
I've done a simulation, but yes, the real test is the release itself :)

**Comment by pruivo** [comment]
integrated! thanks @tristantarrant

**Pull request merged**
