### PR TITLE
Upgrade circus

### PR DESCRIPTION
**Pull request by tristantarrant**
* https://issues.redhat.com/browse/ISPN-13306 Fabric8 Kubernetes Client 5.7.3
* https://issues.redhat.com/browse/ISPN-13297 Mashona 1.0.0
* https://issues.redhat.com/browse/ISPN-13298 Hibernate Search 6.0.6.Final
* https://issues.redhat.com/browse/ISPN-13299 Hibernate ORM 5.3.22.Final
* https://issues.redhat.com/browse/ISPN-13300 Agroal 1.12
* https://issues.redhat.com/browse/ISPN-13301 JBoss Marshalling 2.0.12.Final
* https://issues.redhat.com/browse/ISPN-13302 Narayana 5.12.Final
* https://issues.redhat.com/browse/ISPN-13303 Spring Boot 2.5.4
* https://issues.redhat.com/browse/ISPN-13304 Spring Session 2.5.2
* https://issues.redhat.com/browse/ISPN-13305 Spring 5.3.10

and (no jiras for these since they are test/build only)

* Bouncycastle 1.69
* Byteman 4.0.9

### CODE REVIEW

**Review by karesti — APPROVED** [review]

**Comment by karesti** [comment]
@tristantarrant needs rebase

**Comment by tristantarrant** [comment]
I'll create Jiras after CI is done too

**Comment by tristantarrant** [comment]
The only related test failure seems to be
https://ci.infinispan.org/job/Infinispan/job/PR-9535/1/testReport/junit/org.infinispan.query.jmx/DistributedMassIndexingViaJmxTest/ThreadLeakChecker/

**Comment by tristantarrant** [comment]
Can be merged without waiting for a new CI run: I only amended the commit message

**Pull request merged**
