### PR TITLE
ISPN-13585 Disable PDF generation

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-13585

### CODE REVIEW

**Comment by pruivo** [comment]
@oraNod can we remove the pdf generation?

**Comment by oraNod** [comment]
I encountered a build failure with the distribution. But if I commented this line the build was fine: https://github.com/infinispan/infinispan/pull/9747/commits/3c53e8e446ba6e5f4aa1366f8e3c3a483575b0c1#diff-50bda33cd95bf7733f9c86e14888dcac8d987c8b663c9816f021b92a188b75d4R380

@tristantarrant I think we need to drop `<descriptor>src/main/assemblies/pdf.xml</descriptor>`

**Comment by oraNod** [comment]
> @oraNod can we remove the pdf generation?

@pruivo Yes, I think it's fine. We don't link to the PDF on the site anymore. That transform was used for the PDF links on some of the old index.html pages like 9.4.x: https://infinispan.org/docs/9.4.x/index.html

For 14 and later we don't link to PDFs from the site so it's kind of a pointless run. I will double check everything now though to be sure.

**Comment by pruivo** [comment]
great! @tristantarrant you can remove the pdf generation :+1:

**Review by oraNod — APPROVED** [review]
LGTM!

**Comment by oraNod** [comment]
Thanks @tristantarrant !!

**Pull request merged**
