### PR TITLE
ISPN-9334 Expose the metrics for memory utilization when BINARY storage

### PR DESCRIPTION
**Pull request by wburns**
is used

* Add data memory used stats to various classes
* Works with off heap and binary when memory eviction is used

https://issues.jboss.org/browse/ISPN-9334

### CODE REVIEW

**Comment by wburns** [comment]
Fixed failing tests due to resource descriptor resolver missing changes.

**Comment by wburns** [comment]
Should be rebased now.

**Comment by pruivo** [comment]
@wburns it looks good to me, but CI has a bunch of failures. they seem unrelated. could you double check? (`integration.as.*`)

**Comment by wburns** [comment]
yeah those errors make no sense for the changes I have here. I can try to run it again to see.

**Comment by wburns** [comment]
Now with all the lucene junk failures CI passed fine.

**Pull request merged**
