### PR TITLE
ISPN-8321 Disable TestDisconnectHandler to avoid deadlock

### PR DESCRIPTION
**Pull request by galderz**
https://issues.jboss.org/browse/ISPN-8321

### CODE REVIEW

**Comment by gustavonalle** [comment]
@galderz @danberindei the build did not run:  
```
Not enough free space after deleting all the build directories! (/dev/vda1       7.9G)
```

**Comment by danberindei** [comment]
@gustavonalle Problems with the cleanup script, triggered again.

**Comment by gustavonalle** [comment]
Probably the Rolling Upgrade failure is in master as well; in any case it's not related to this PR and I've fixed it in https://github.com/infinispan/infinispan/pull/5311, so merging this PR

**Comment by gustavonalle** [comment]
Integrated, thanks @galderz !

**Pull request merged**
