### PR TITLE
ISPN-14740 Reuse EMPTY Metadata when lifespan and maxIdle are not pro…

### PR DESCRIPTION
**Pull request by wburns**
…vided

https://issues.redhat.com/browse/ISPN-14740

### CODE REVIEW

**Comment by wburns** [comment]
This may seem small, but to clarify this will change the effect so that stores will now receive a null metadata when no expiration is specified. It also changes it so that an EMPTY metadata is passed if a lifespan and/or max idle is supplied with a negative value.

This is important because then stores are already implemented to handle a null metadata. In that case they have less work to do. For example SIFS does 2 less calls to FileChannel write and also reduces the entry size by at least 26 bytes.

**Comment by tristantarrant** [comment]
Many related failures

**Comment by wburns** [comment]
Test failures were due to a typo that the max idle time unit was using the lifespan unit on accident when lifespan wasn't provided. This couldn't happen before as -1 was considered provided before these changes.

**Comment by wburns** [comment]
Still some more failures outside of the core module.

**Comment by wburns** [comment]
Looking closer at this, I don't think this can be implemented this way with how we aren't providing a common way for overriding the default lifespan or max idle expiration. We may be able to instead do a check in the persistence layer to only provide the metadata if it has some pertinent information, but I think this is a bit of a losing battle at this point.

**Pull request closed without merging**
