### PR TITLE
Ispn 6575

### PR DESCRIPTION
**Pull request by wburns**
https://issues.jboss.org/browse/ISPN-6575

### CODE REVIEW

**Comment by wburns** [comment]
This is to be backported to 8.2.x as well, it should cherry-pick as is.

**Comment by tristantarrant** [comment]
It does not cherry-pick to 8.2.x since the changes you made to CacheStream :)

**Comment by wburns** [comment]
Alright I will make a new PR then.

**Comment by tristantarrant** [comment]
I've pushed this to master. Waiting for the 8.2.x PR to close the Jira

**Pull request closed without merging**
