### PR TITLE
[14.0] ISPN-15036 Never use search#hitCount() without check if it is exact

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-15036

Backport of #11108

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#2](https://ci.infinispan.org/job/Infinispan/job/PR-11109/2/):
```
quay.io/infinispan-test/server:PR-11109
```

**Comment by fax4ever** [comment]
Updated the backport as well

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#3](https://ci.infinispan.org/job/Infinispan/job/PR-11109/3/):
```
quay.io/infinispan-test/server:PR-11109
```

**Comment by ahus1** [comment]
@fax4ever - some good news:

Good news: I the failing test now passes once I run it against the container created by Jenkins. 
Will run some more tests in this suite to confirm it is working nicely. 

I'll now build the client libraries as well - I just learned that I need to use the `maven-settings.xml` for this.

**Comment by ahus1** [comment]
@fax4ever - concluded my tests with a locally build library and and the container. The tests of that test suite pass now. The other tests we've seen in the integration test suite have the same error messages, so I assume they are fixed as well. 

Therefore I'm +1 for this change from a consumer's perspective. Thank you for the fix!

**Comment by fax4ever** [comment]
> Therefore I'm +1 for this change from a consumer's perspective. Thank you for the fix!

Thank you for spotting and testing the issue! 
Next time I'll try to not introduce regression when I apply the next optimizations to the queries :P

**Comment by ryanemerson** [comment]
Thanks @fax4ever

**Pull request merged**
