### PR TITLE
[9.4.x] ISPN-9886 JGRP-2301 Add UFC protocol even in TCP stacks

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/JDG-2940

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please
library
cs
[TCP]

**Comment by danberindei** [comment]
run performance tests please
library
cs
[TCP]

**Comment by tristantarrant** [comment]
Status on this ?

**Comment by danberindei** [comment]
run performance tests please
library
cs
[TCP]

**Comment by danberindei** [comment]
@tristantarrant forgot to trigger perf ack again now that it's working

**Comment by diegolovison** [comment]
run performance tests please
library
cs
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library
cs
[TCP]

**Comment by danberindei** [comment]
Rebased

**Pull request merged**
