### PR TITLE
[14.0.x] Docs review Query hit count efficiency

### PR DESCRIPTION
**Pull request by dvagnero**
Docs review of
https://issues.redhat.com/browse/ISPN-14195

backports #11146

### CODE REVIEW

**Comment by dvagnero** [comment]
@fax4ever please take a look to make sure I didn't include any info that would be Infinispan 15 specific. What is the default value? 10_000 or 10000? Based on the schema I went with 10000

**Review by fax4ever — APPROVED** [review]
Great job @dvagnero. Thank you
Maybe we can remove the line:

> https://issues.redhat.com/browse/ISPN-14203

from the backport request description.
Since [ISPN-14203](https://issues.redhat.com/browse/ISPN-14203) will targets Infinispan 15 only.

**Comment by fax4ever** [comment]
> @fax4ever please take a look to make sure I didn't include any info that would be Infinispan 15 specific. What is the default value? 10_000 or 10000? Based on the schema I went with 10000

Right. 10000 (ten thousand) is the right default value. I wrote 10_000 following the Java convention, but 10000 is better.

**Comment by fax4ever** [comment]
Thanks

**Pull request merged**
