### PR TITLE
Move org.infinispan.Version to org.infinispan.commons.util.Version

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-10520

### CODE REVIEW

**Comment by tristantarrant** [comment]
First off, only infinispan-core did that (and the embedded uberjar by transitive property). None of our other jars had the Version class (or equivalent).
In any case I always found that functionality a bit redundant, as the version is part of the artifact name, and it is included in the META-INF/MANIFEST.MF file using all of the standard manifest entries. In this case tradition is not really an advantage.

**Comment by anistor** [comment]
Redundant, yes. Why do we still keep it? I don't see this PR as fixing anything because now the class is basically in another jar, so the Main-Class manifest entry is even more pointless. Also the Version mechanism was supposed to return the real version (in a very hardcoded way). Now it returns whatever commons jar says. So If I mistakenly mix commons jar ver X with core jar version Y what do I get?

**Comment by tristantarrant** [comment]
I have removed the main-class entry from the manifests

**Comment by anistor** [comment]
Good! We are halfway there.

**Comment by tristantarrant** [comment]
I could not care less about users mixing wrong versions. I don't want to program defensively for this kind of problem.

**Comment by anistor** [comment]
You've said it ! My empathy towards user mistakes is sooo very low. Merging!

**Comment by anistor** [comment]
Merged in master. Thanks @tristantarrant !

**Pull request merged**
