### PR TITLE
ISPN-6358 Remove filterEntries method from AdvancedCache

### PR DESCRIPTION
**Pull request by wburns**
https://issues.jboss.org/browse/ISPN-6358

### CODE REVIEW

**Comment by wburns** [comment]
I still need to remove documentation

**Comment by wburns** [comment]
Updated to remove from user guide.

**Comment by wburns** [comment]
Rebased.

**Comment by anistor** [comment]
Looking...

**Comment by anistor** [comment]
There are still some unused imports to remove from ControlledCommandFactory, BaseStreamIteratorEvictionTest, SecureCacheImpl, ReadOnlyMapImpl, CommandsFactoryImpl, CommandsFactory. Looks good.

**Comment by wburns** [comment]
Fixed imports, thanks @anistor

**Comment by anistor** [comment]
CommandsFactoryImpl still has them.

**Comment by wburns** [comment]
Weird I did import update, but it is fixed now.  Sorry about that.

**Comment by anistor** [comment]
Pulling ...

**Comment by anistor** [comment]
Integrated. Thanks @wburns !

**Pull request closed without merging**
