### PR TITLE
ISPN-7286: Cache stores should declare whether they can be shared (Am…

### PR DESCRIPTION
**Pull request by ryanemerson**
…endment).

https://issues.jboss.org/browse/ISPN-7286

### CODE REVIEW

**Comment by galderz** [comment]
Some new errors have appeared:

```
ConfigurationConverterTest.testConversionAndSerializationFrom60 	
ConfigurationConverterTest.testConversionFrom60
StateTransferFileCacheLoaderFunctionalTest.testSharedLoader
...
```

And some more, check CI.

**Comment by ryanemerson** [comment]
@galderz Sorry about that, I forgot to update the tests after adding the `@Store` annotation to `SingleFileStore`. There is a bit of a hack in your test `StateTransferFileCacheLoaderFunctionalTest.java` so that the test can function as before as this test needs a SingleFileStore to be shared.

**Comment by galderz** [comment]
Needs rebasing...

**Comment by ryanemerson** [comment]
@galderz Rebased

**Comment by galderz** [comment]
Looks good now, integrating...

**Pull request merged**
