### PR TITLE
ISPN-6301 Server configurations should be "templates" by default

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-6301

### CODE REVIEW

**Comment by anistor** [comment]
Pulling ...

**Comment by anistor** [comment]
Integrated. Thanks @tristantarrant !

**Comment by gustavonalle** [comment]
This is causing failures in the ```jcache/tck-runner``` and also preventing the build to complete

**Comment by gustavonalle** [comment]
```
Caused by: org.infinispan.commons.CacheConfigurationException: ISPN000373: Attempted 
to start a cache using configuration template 'org.jsr107.tck.PutTest'"}},"rolled-back" => true}},"failure-
description" => {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" 
=> {"Operation step-2" => {"WFLYCTL0080: Failed services" => {"jboss.datagrid-
infinispan.local.\"org.jsr107.tck.PutTest\"" => "org.jboss.msc.service.StartException in service 
jboss.datagrid-infinispan.local.\"org.jsr107.tck.PutTest\": Failed to start service
    Caused by: org.infinispan.commons.CacheConfigurationException: ISPN000373: Attempted to start 
a cache using configuration template 'org.jsr107.tck.PutTest'"}}}},"rolled-back" => true}
```
in an infinite loop and hangs

**Comment by anistor** [comment]
Let's roll it back then. I did run some of the tests, but not all. And CI is not helping ...

**Comment by gustavonalle** [comment]
@anistor ok, I'll revert it for now

**Comment by tristantarrant** [comment]
Ok, I believe it is fixed now

**Comment by anistor** [comment]
Looks good. Pulling ...

**Comment by anistor** [comment]
Integrated. Thanks @tristantarrant !

**Pull request closed without merging**
