### PR TITLE
ISPN-5991 Upgrade Jandex to the Final version 2.0.0.Final

### PR DESCRIPTION
**Pull request by Sanne**
https://issues.jboss.org/browse/ISPN-5991

### CODE REVIEW

**Comment by anistor** [comment]
Do we want to backport this?

**Comment by Sanne** [comment]
Probably, but just because it looks better to not depend on non-Final stuff..

**Comment by anistor** [comment]
Integrated in master. Thanks @Sanne !

**Comment by anistor** [comment]
Backported to 8.0.x too.

**Pull request merged**
