### PR TITLE
Fix duplicated tests

### PR DESCRIPTION
**Pull request by slaskawi**

### CODE REVIEW

**Comment by tristantarrant** [comment]
Is this supposed to be merged ?

**Comment by slaskawi** [comment]
Let me do another build... just to be 100% that those duplicates are gone...

**Comment by slaskawi** [comment]
@tristantarrant Done.

I also had to disable stress tests. Some of them were killing Jenkins Agents. Let's finish Jenkins migration first and then implement stress tests.

**Comment by slaskawi** [comment]
Should be good now, merging.

**Pull request merged**
