### PR TITLE
ISPN-5469 Invoke remote commands asynchronously (after ISPN-5467)

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-5469

Please review https://github.com/infinispan/infinispan/pull/4520 first.

### CODE REVIEW

**Comment by danberindei** [comment]
So far, performance seems identical to ISPN-5467.

| | iteration 1 | iteration 2 | iteration 3 | iteration 4 | iteration 5 |
|---|--:|--:|--:|--:|--:|
| Infinispan 9.0.0-ISPN-5467_CompletableFuture-like_API dist-no-tx | 131868 reqs/s | 212681 reqs/s | 227288 reqs/s | 227733 reqs/s | 149275 reqs/s | 118970 reqs/s |
| Infinispan 9.0.0-ISPN-5469_async_remote_perform dist-no-tx| 131133 reqs/s | 218097 reqs/s | 234579 reqs/s | 226498 reqs/s | 152675 reqs/s | 127093 reqs/s |
| Infinispan 9.0.0-ISPN-5467_CompletableFuture-like_API dist-tx | 104036 reqs/s | 227968 reqs/s | 307952 reqs/s | 316431 reqs/s | 331697 reqs/s | 334842 reqs/s |
| Infinispan 9.0.0-ISPN-5469_async_remote_perform dist-tx| 103838 reqs/s | 216397 reqs/s | 302928 reqs/s | 320335 reqs/s | 340910 reqs/s | 329935 reqs/s |
| Infinispan 9.0.0-ISPN-5467_CompletableFuture-like_API repl-no-tx | 19180860 reqs/s | 19381369 reqs/s | 19579790 reqs/s | 19851493 reqs/s | 19840807 reqs/s | 19957206 reqs/s |
| Infinispan 9.0.0-ISPN-5469_async_remote_perform repl-no-tx| 18747794 reqs/s | 19043134 reqs/s | 19293469 reqs/s | 19293399 reqs/s | 19511212 reqs/s | 19237235 reqs/s |
| Infinispan 9.0.0-ISPN-5467_CompletableFuture-like_API | repl-tx 2210369 reqs/s | 2214574 reqs/s | 2188473 reqs/s | 2174754 reqs/s | 2141263 reqs/s | 2162410 reqs/s |
| Infinispan 9.0.0-ISPN-5469_async_remote_perform repl-tx| 2182740 reqs/s | 2171411 reqs/s | 2149473 reqs/s | 2150927 reqs/s | 2134491 reqs/s | 2125411 reqs/s |


| | iteration 1 | iteration 2 | iteration 3 | iteration 4 | iteration 5 |
|---|--:|--:|--:|--:|--:|
| Infinispan 9.0.0-ISPN-5467_CompletableFuture-like_API dist-no-tx | 42840 reqs/s | 62100 reqs/s | 65745 reqs/s | 68855 reqs/s | 73780 reqs/s | 79423 reqs/s |
| Infinispan 9.0.0-ISPN-5469_async_remote_perform dist-no-tx | 42412 reqs/s | 63017 reqs/s | 67105 reqs/s | 71484 reqs/s | 76067 reqs/s | 84243 reqs/s |
| Infinispan 9.0.0-ISPN-5467_CompletableFuture-like_API dist-tx    | 24737 reqs/s | 33279 reqs/s | 33019 reqs/s | 34582 reqs/s | 38529 reqs/s | 43402 reqs/s |
| Infinispan 9.0.0-ISPN-5469_async_remote_perform dist-tx | 23996 reqs/s | 32030 reqs/s | 31713 reqs/s | 33913 reqs/s | 39013 reqs/s | 43435 reqs/s |
| Infinispan 9.0.0-ISPN-5467_CompletableFuture-like_API repl-no-tx | 20493 reqs/s | 25646 reqs/s | 29310 reqs/s | 29818 reqs/s | 30227 reqs/s | 28891 reqs/s |
| Infinispan 9.0.0-ISPN-5469_async_remote_perform repl-no-tx | 20897 reqs/s | 25429 reqs/s | 28554 reqs/s | 31445 reqs/s | 31224 reqs/s | 30166 reqs/s |
| Infinispan 9.0.0-ISPN-5467_CompletableFuture-like_API repl-tx    | 11919 reqs/s | 13121 reqs/s | 13656 reqs/s | 13430 reqs/s | 13108 reqs/s | 13892 reqs/s |
| Infinispan 9.0.0-ISPN-5469_async_remote_perform repl-tx | 11395 reqs/s | 12282 reqs/s | 13158 reqs/s | 13686 reqs/s | 13239 reqs/s | 14203 reqs/s |

I would say that's good enough for now. There's some work ahead to 1) execute write commands directly on the OOB thread and 2) reduce memory allocations. Bytes allocated per operation:

| branch | bytes/op |
|---|---:|---:|
| master |  12140.888 +- 12447.780 |
| ISPN-5467 |  11743.773 +- 12208.991 |
| ISPN-5469 |  12676.903 +- 12734.219 |

**Comment by tristantarrant** [comment]
Pushed to master. Thank Dan

**Comment by danberindei** [comment]
@tristantarrant I think this actually needed more work after the latest rebase... looking into the failures.

**Comment by rvansa** [comment]
@danberindei I like that now the synchronous invocation on stack really shows the stack in stack traces, but we should get rid of methods returning `Object` in `Visitor` - it generates bridge methods and each interceptor involves unnecessary method call.

**Pull request closed without merging**
