### PR TITLE
ISPN-7678 Endpoints should not depend on the default cache

### PR DESCRIPTION
**Pull request by tristantarrant**
- Prevents endpoint restart on default cache reconfiguration

ISPN-7683 Unregisters the internal topology cache on server stop

https://issues.jboss.org/browse/ISPN-7678
https://issues.jboss.org/browse/ISPN-7683

### CODE REVIEW

**Comment by ryanemerson** [comment]
@tristantarrant Tested locally and this fixes the previous problems. Waiting on CI.

**Comment by tristantarrant** [comment]
@ryanemerson I've also added ISPN-7683

**Comment by tristantarrant** [comment]
It seems like the changes are causing a number of regressions in some server tests. I'll come up with a better solution

**Comment by danberindei** [comment]
@tristantarrant couldn't we also restart the cache manager when we restart the server?

**Comment by tristantarrant** [comment]
The issue here is backwards: the server's highly concurrent service design makes the endpoint start as soon as the cache manager service is installed. However this could happen before any actual cache services are started. The Hot Rod endpoint, for legacy reasons, wants to start the default cache (which might not have been configured yet). The fixes we need are:

- make the Hot Rod endpoint start regardless of the presence of any caches
- requesting a cache over Hot Rod should actually wait for the cache (if present obviously) to be started by the server. If the cache is clustered, we should ensure that it is started on all nodes.

**Comment by tristantarrant** [comment]
Closing this for now

**Pull request closed without merging**
