### PR TITLE
[9.4] ISPN-11318 Netty 4.1.45.Final

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-11318

### CODE REVIEW

**Comment by pruivo** [comment]
@tristantarrant CI is unable to build this PR.

**Comment by tristantarrant** [comment]
Fixing it. Netty added some new optional deps

**Comment by tristantarrant** [comment]
Repushed with the OSGi fix

**Comment by tristantarrant** [comment]
Rebased

**Comment by pruivo** [comment]
thanks @tristantarrant ! integrated!

**Pull request merged**
