### PR TITLE
[13.0.x] ISPN-14257: Add a statement why we provide no performance numbers

### PR DESCRIPTION
**Pull request by dfitzmau**
ISPN: https://issues.redhat.com/browse/ISPN-14257

Backport for https://github.com/infinispan/infinispan/pull/10380

### CODE REVIEW

**Comment by dfitzmau** [comment]
Hi @wfink and @oraNod . Here is the content that I back ported from https://github.com/infinispan/infinispan/pull/10380 . Not sure if I need an ack from you both for this?

**Comment by wfink** [comment]
Looks good to me

**Review by oraNod — APPROVED** [review]

**Comment by oraNod** [comment]
@tristantarrant @pruivo Hi, can one of you please merge this backport? I'm not sure if 13.0.x is open or not. Cheers.

**Comment by pruivo** [comment]
IMO, it is fine to update the docs :)
Merged! thanks @dfitzmau !

**Comment by oraNod** [comment]
Thanks @pruivo :coffee:

**Pull request merged**
