### PR TITLE
ISPN-12823 JGroups retransmission requests are too frequent and overlap

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-12823

Increase xmit_interval and reduce max_xmit_request_size

### CODE REVIEW

**Comment by tristantarrant** [comment]
Would this affect the bundler results under load ?

**Comment by danberindei** [comment]
@tristantarrant even under load, I don't think there should be many dropped messages that need to be retransmitted, unless there is a very long GC pause. In that case, the sender could send 4MB worth of messages (UFC.max_credits), which could mean 4000 messages of 1KB or maybe 40000 messages of 100B each.

To make the computation easier, I updated the PR to make both xmit_interval and max_xmit_request_size 200. In the extreme case of 40000 backlogged messages, it would take 200 XMIT requests to cover all of them, or 40 seconds, which I think is reasonable for a one-time event. For a more common scenario of only 4000 backlogged messages, it would take only 4 seconds to catch up.

I could make max_xmit_request_size a little higher, but I'm not sure, because it would cause an increase in duplicate retransmission requests if the destination is "alive" enough to request retransmission every xmit_interval, yet doesn't have the capacity to actually process the messages at the rate they are retransmitted.

**Comment by tristantarrant** [comment]
Please rebase

**Comment by danberindei** [comment]
Rebased

**Comment by tristantarrant** [comment]
LGTM. Please add a note to the upgrading guide about these new defaults.

**Comment by danberindei** [comment]
I added a note @tristantarrant.

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by danberindei** [comment]
run performance tests please

**Comment by diegolovison** [comment]
Hi @danberindei 
we look only for PR that is opened

**Comment by danberindei** [comment]
That's fine @diegolovison, you can ignore it.

**Pull request merged**
