### PR TITLE
ISPN-16057 Restore 3rd party integration tests for Wildfly and Tomcat

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-16057

Wildfly version bumped to 32.0

Tomcat tested with 10.1.23. Unfortunately we need to rely on a SNAPSHOT release of `arquillian-tomcat-managed-10` as this has [not yet been released](https://github.com/arquillian/arquillian-container-tomcat/pull/148), however I'm chasing our good friend @rhusar to see if we can get this released ASAP. This won't affect upstream CI as we don't execute the Tomcat tests here anyway.

@tristantarrant I dropped `MemcachedClientIT` as it relies upon the `SimpleMemcachedClient` that AFAICT is no longer compatible with the changes on our server and I didn't think was worth the time investment of debugging/fixing.

### CODE REVIEW

**Comment by tristantarrant** [comment]
Could not find artifact org.opensaml:opensaml-core:jar:4.2.0 in central (https://repo.maven.apache.org/maven2/)

**Comment by tristantarrant** [comment]
According to mvnrepository.com, it seems like version 4.2.0 is only available from the Shibboleth repo: https://mvnrepository.com/artifact/org.opensaml/opensaml-core?repo=shibboleth-releases

**Comment by rhusar** [comment]
@ryanemerson Sure thing! Lets catch up on Monday as I am on PTO today.

**Comment by rhusar** [comment]
> Tomcat tested with 10.1.23. Unfortunately we need to rely on a SNAPSHOT release of `arquillian-tomcat-managed-10` as this has [not yet been released](https://github.com/arquillian/arquillian-container-tomcat/pull/148), however I'm chasing our good friend @rhusar to see if we can get this released ASAP. This won't affect upstream CI as we don't execute the Tomcat tests here anyway.

@ryanemerson Looking at this bit more today, what you could use right-away, is the `arquillian-tomcat-managed-8` version 1.1.0.Final which is compatible with Tomcat 10.1 as well, e.g. just use the following in the pom: 

```
        <dependency>
            <groupId>org.jboss.arquillian.container</groupId>
            <artifactId>arquillian-tomcat-managed-8</artifactId>
            <version>1.1.0.Final</version>
            <scope>test</scope>
        </dependency>
```

Should that be problematic, we can just do the release form the main branch of that project as originally discused.

**Comment by ryanemerson** [comment]
@rhusar  I just tried again to be sure and I get 500 errors with `arquillian-tomcat-managed-8` and Tomcat 10.1.23, so I think we need the release.

**Comment by rhusar** [comment]
> @rhusar I just tried again to be sure and I get 500 errors with `arquillian-tomcat-managed-8` and Tomcat 10.1.23, so I think we need the release.

@ryanemerson OK cool - the release is out now - https://github.com/arquillian/arquillian-container-tomcat/releases/tag/1.2.1.Final and released in our nexus (so it might need a minute to sync). Let me know if that works for you :-)

**Comment by ryanemerson** [comment]
Thanks @rhusar that worked for me locally.

@tristantarrant This should be good to merge once CI has completed.

**Pull request merged**
