### PR TITLE
ISPN-8217 RestStoreTest.tearDown intermittent failure

### PR DESCRIPTION
**Pull request by ryanemerson**
- Upgrade Netty to 4.1.14.Final

https://issues.jboss.org/browse/ISPN-8217

### CODE REVIEW

**Comment by karesti** [comment]
@ryanemerson It looks good, but there are failing tests

**Comment by ryanemerson** [comment]
@karesti Those test failures seem very strange as they don't appear related to my changes and I can't recreate them locally. Anyway, I have triggered another build to see if the last run was an anomaly

**Comment by ryanemerson** [comment]
Hmm, all of the previous test failures have disappeared with the exception of HotRodSniFunctionalTest which is definitely related. I'll investigate further

**Comment by tristantarrant** [comment]
Temporarily closing this until it is fixed.

**Pull request closed without merging**
