### PR TITLE
[13.0] ISPN-14187 SoftIndexFileStore not removing log files with expiration

### PR DESCRIPTION
**Pull request by wburns**
* Unset schedule flag when completing file - set from expiration
* Make sure nextExpirationTime is set properly if stats already exist

https://issues.redhat.com/browse/ISPN-14187

### CODE REVIEW

**Comment by tristantarrant** [comment]
Some compilation errors

**Comment by wburns** [comment]
Fixed compilation

**Comment by wburns** [comment]
Test failures seem unrelated.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
