### PR TITLE
ISPN-11212 Ensure Max idle works with passivation

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-11212
https://issues.redhat.com/browse/ISPN-11218
https://issues.redhat.com/browse/ISPN-13320

### CODE REVIEW

**Comment by tristantarrant** [comment]
Class org.infinispan.persistence.PassivationOptionsTest has an invalid testName: persistence.PassivationFunctionalTest

**Comment by wburns** [comment]
> Class org.infinispan.persistence.PassivationOptionsTest has an invalid testName: persistence.PassivationFunctionalTest

Updated, thanks.

**Comment by tristantarrant** [comment]
A number of related `org.infinispan.reactive.publisher.impl.RehashClusterPublisherManagerTest` failures

**Comment by wburns** [comment]
> A number of related `org.infinispan.reactive.publisher.impl.RehashClusterPublisherManagerTest` failures

Ah, tests just need to be updated to spy the correct method. Fixing.

**Comment by wburns** [comment]
Test failures should be all fixed now.

**Comment by tristantarrant** [comment]
In it goes. Thanks @wburns

**Pull request merged**
