### PR TITLE
ISPN-10029 Fix topology id for non-tx invalidation commands

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-10029

The original fix didn't set the topology id in non-txt caches, only in tx caches.

### CODE REVIEW

**Comment by danberindei** [comment]
Added a 2nd commit to fix the random failure in SyncInvalidationTest

**Comment by tristantarrant** [comment]
45 failures...

**Comment by danberindei** [comment]
Looks like I broke the hibernate L2 cache implementation

**Comment by danberindei** [comment]
Updated, hopefully all the failures are fixed now.

**Comment by tristantarrant** [comment]
Still has a hibernate-related failure

**Pull request merged**
