### PR TITLE
ISPN-13355 Set LDAP server properties only in LdapServerListener

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-13355

### CODE REVIEW

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Comment by diegolovison** [comment]
It was fixed in https://github.com/infinispan/infinispan/pull/9657

**Comment by ryanemerson** [comment]
Sorry @diegolovison that obviously missed our attention.

**Comment by diegolovison** [comment]
No problem. I liked the move that you did and implement on my PR as well :)

**Pull request merged**
