### PR TITLE
ISPN-12366 infinispan-commons is not a valid Multi-Release jar

### PR DESCRIPTION
**Pull request by rhusar**
Resolves
https://issues.redhat.com/browse/ISPN-12366

### CODE REVIEW

**Comment by tristantarrant** [comment]
Yeah, I have the same in https://github.com/infinispan/infinispan/pull/8659/commits/9ca724970108ac50c5731473325c9bc36bb646b6#diff-546390a73c23fef04b49a22d2f7c4740

**Comment by rhusar** [comment]
@tristantarrant Cool, what a coincidence. Might have saved me half an hour debugging :-) Might as well merge this one to get proper tracking and get testing if your PR is still in the works.

**Comment by tristantarrant** [comment]
Merged to master and 11.0.x

**Comment by rhusar** [comment]
@tristantarrant Great, thanks!

**Pull request merged**
