### PR TITLE
ISPN-16629 Ensure that at least 30000 have been run

### PR DESCRIPTION
**Pull request by rigazilla**
fail if too few tests have been run
see [ISPN-16629](https://issues.redhat.com/browse/ISPN-16629)

### CODE REVIEW

**Comment by ryanemerson** [comment]
I see in `check-ci test report` that 23726 tests have been run, but I can't see the failed check with `Fail. $COUNT test ran, minimum required is $MIN_TEST_NUM`. Am I missing something or does it not exist?

Minor issue, but why does `check-ci test report` appear under "Pull Request Open -> on: pull_request_target"?

**Comment by rigazilla** [comment]
> I see in `check-ci test report` that 23726 tests have been run, but I can't see the failed check with `Fail. $COUNT test ran, minimum required is $MIN_TEST_NUM`. Am I missing something or does it not exist?
> 
> Minor issue, but why does `check-ci test report` appear under "Pull Request Open -> on: pull_request_target"?

PR is on my fork, so github hadn't run changes on github actions. I'll move the branch on infinispan repo

**Comment by rigazilla** [comment]
same run but on a PR: https://github.com/rigazilla/infinispan/pull/20

**Comment by rigazilla** [comment]
> Minor issue, but why does `check-ci test report` appear under "Pull Request Open -> on: pull_request_target"?

it is due to github: workflow_run is not deterministically attached to the triggering workflow. I've read it somewhere, but I'm unable to find that link again atm

**Comment by ryanemerson** [comment]
Thanks @rigazilla

**Pull request merged**
