### PR TITLE
ISPN-5244 Verify container and cluster-wide cache stats

### PR DESCRIPTION
**Pull request by vblagoje**
Master only. See https://issues.jboss.org/browse/ISPN-5244 for details @tristantarrant please review

### CODE REVIEW

**Comment by mgencur** [comment]
Hi @vblagoje , I did some testing with this PR and here are my findings:
* the numberOfEntries and similar integer results now return -1 instead of -2 which is correct
* there's another problem with several methods such as ReadWriteRation, HitRatio, AvgReadTime etc, and this problem is also in the cluster cache statistics. It is that there are integers used for division where double should be used instead. So you can easily get 0.0 for read/write ratio ,even if you have stores==2 and hits==1.

**Comment by vblagoje** [comment]
Thanks @mgencur I will update the branch for you to try again!

**Comment by vblagoje** [comment]
@mgencur Would you please give it another run. Let me know your findings.

**Comment by vblagoje** [comment]
@mgencur said "I meant sum across all caches on that single node. If you have 100 caches defined on that node and you only write/read to a single one, you still divide the number by 100 (existingCacheCounter) in the end which gives a totally different number. I did not mean sum of cache across different nodes" 

Right, we still average across 100 caches even though only one cache is written to - in this use case. But how else can we treat this use case? We could only count caches that have some values to contribute to the average, right? Good point.

**Comment by mgencur** [comment]
I was thinking that we could have this number computed in the following way: (sum of all reads in all caches) / (sum of all writes in all caches)
This way we would get overall read/write ratio for all caches on the single node (and would not be affected by empty caches) which could help admins estimate whether this single node is not overloaded. I'm still trying to understand why we would need an average value across caches. This number can be easily degraded by empty caches or caches with little data.

**Comment by vblagoje** [comment]
@mgencur that is what we already do. We just do it in a different way. So say we have three cache on a node. Let read/write ratio be 3/5, 2/5, and finally 1/5. Using current formula we get (3/5+2/5+1/5)/3= (6/5)/3= 0.4 If we use your approach we get 3+2+1=6 read and 5+5+5=15 writes. Therefore 6/15=0.4

**Comment by vblagoje** [comment]
However, you made a going point that we should only count valid values for average read/write/remove. We counted all values and results were skewed. I am correcting that now. Will update PR soon.

**Comment by mgencur** [comment]
OK. Thanks:)

**Comment by danberindei** [comment]
@vblagoje I think it's worth doing it the way @mgencur suggested anyway, because the result of floating-point operations is an approximation most of the time. With Martin's suggestion you have a single floating-point division at the end, with the existing approach you have n divisions (one for each cache) and then another n-1 sums, and the errors can add up.

**Comment by vblagoje** [comment]
Ok @danberindei will do so. @mgencur how does everything else look like now?

**Comment by mgencur** [comment]
Still getting wrong number for hitRatio. In my test, I do 1 put, 1 get and 1 remove on the same key and I get hitRatio == 0.
The expected result is 1, IMO.   My cluster is DIST, two-node, 2-owners.

**Comment by vblagoje** [comment]
@mgencur give it another go now. I believe I have addressed both your and @danberindei concerns. Please report back as well. Thank you

**Comment by mgencur** [comment]
Hi @vblagoje , I checked the solution and my tests pass! Now there are only https://issues.jboss.org/browse/ISPN-5240 and https://issues.jboss.org/browse/ISPN-5239. They might be addressed in a different PR.

**Comment by vblagoje** [comment]
I agree @mgencur Thanks for all the tests you have done. @tristantarrant and @danberindei would you please consider this one for integration now!

**Comment by mgencur** [comment]
No problem @vblagoje . Once this PR is integrated, I'll send another one with the tests for client-server mode.

**Comment by galderz** [comment]
Integrated, thanks Vladimir :)

**Pull request closed without merging**
