### PR TITLE
Scala removal2 - Memcached

### PR DESCRIPTION
**Pull request by wburns**

### CODE REVIEW

**Comment by wburns** [comment]
There are some test failures I didn't see locally I need to investigate still.

**Comment by galderz** [comment]
Needs rebasing

**Comment by galderz** [comment]
Looks good otherwise 😄

**Comment by wburns** [comment]
I just have a few tests I need to fix up, could have sworn I tested before I did the last push :/

**Comment by wburns** [comment]
Rebased and fixes tests.

**Comment by tristantarrant** [comment]
Pushed to master, thanks

**Pull request closed without merging**
