### PR TITLE
ISPN-2752 IllegalStateException on shutdown

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-2752
https://issues.jboss.org/browse/ISPN-3142

### CODE REVIEW

**Comment by wburns** [comment]
Are all of the changes in the first commit required to reenable the test?  It might be more clear for the future when looking at it to see what actually allowed us to reenable the test.  If only one line is needed I would say to move it to the other commit or if all 3 then change the commit comment on the second one to say it was solved by ISPN-2752 at least.

**Comment by danberindei** [comment]
@wburns The first commit only has one line...

**Comment by danberindei** [comment]
@wburns Ah sorry, I was looking at the second commit. There's no connection between the two commits really, ISPN-3142 was fixed by ISPN-2577 as described in the JIRA comment and I just noticed that it was still in the unstable group while investigating ISPN-2752.

**Comment by danberindei** [comment]
I updated the commit message for ISPN-3142

**Comment by galderz** [comment]
Integrated, thanks @danberindei

**Pull request closed without merging**
