### PR TITLE
ISPN-13946 Expose indexes metamodel

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-13946

### CODE REVIEW

**Comment by tristantarrant** [comment]
This needs docs added to the REST API book

**Comment by fax4ever** [comment]
> This needs docs added to the REST API book

Sure. I'm going to do that.

**Comment by fax4ever** [comment]
I updated that doc (here and in the backport). 
Thanks for the review @tristantarrant.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
