### PR TITLE
Set the codename for 9.0

### PR DESCRIPTION
**Pull request by tristantarrant**
http://www.ruppaner-bodensee.de/unsere-biere/

### CODE REVIEW

**Comment by belaban** [comment]
Schimmele sounds pretty good, although difficult to pronounce for english speaking people... :-)

**Comment by danberindei** [comment]
:+1:

**Comment by vjuranek** [comment]
there's still one nice [proposal](http://lists.jboss.org/pipermail/infinispan-dev/2014-November/015735.html) by @gustavonalle  ... or is this once reserved for ISPN 10 :smile: ?

**Comment by tristantarrant** [comment]
Since Konstanz has been the location for very important progress this year, the codename of 9 reflects that. As for Gustavo's proposal... :)

**Comment by anistor** [comment]
[Spezial Export](http://www.ruppaner-bodensee.de/unsere-biere/spezial-export/) sounds like the best they have. And I like the Z :)

**Comment by tristantarrant** [comment]
I was going to use the brand name alone, as we have done in the past with Starobrno, Brahma, Guiness, Mahou...

**Comment by ryanemerson** [comment]
+1

**Comment by rhusar** [comment]
👍

**Comment by belaban** [comment]
Rado, we missed you... :-)

**Comment by alanfx** [comment]
👍 @rhusar, there were cigars too...

**Comment by rhusar** [comment]
Ah, sad to miss then, but we had a great EAP meeting last week too :-) no cigars though!

**Pull request merged**
