### PR TITLE
ISPN-16527: Doc edits for index/query by key for remote queries docs

### PR DESCRIPTION
**Pull request by theashiot**
https://issues.redhat.com/browse/ISPN-16527

### CODE REVIEW

**Comment by theashiot** [comment]
Hi @fax4ever, 

Can you please review the docs updates?

thanks,
ashwin

**Review by fax4ever — APPROVED** [review]
LGTM, thank you @theashiot.
I restarted the CI, if it passes, then we can merge it.

**Comment by theashiot** [comment]
Thanks, @fax4ever!

**Comment by fax4ever** [comment]
Merged, thanks

**Pull request merged**
