### PR TITLE
ISPN-5923 Wrong results when applying the <= operator to a string attribute having a null token defined

### PR DESCRIPTION
**Pull request by anistor**
Jira: https://issues.jboss.org/browse/ISPN-5923
https://issues.jboss.org/browse/ISPN-5926

### CODE REVIEW

**Comment by anistor** [comment]
This is Preview because it needs a release of hibernate-search-5.5.1.Final first.

**Comment by tristantarrant** [comment]
@Sanne can we have the release of Hibernate Search 5.5.1.Final please ?

**Comment by Sanne** [comment]
@tristantarrant :+1: early afternoon

**Comment by tristantarrant** [comment]
Pushed, thanks

**Pull request closed without merging**
