### PR TITLE
ISPN-12825 Add query timeouts to the JDBC store

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-12825

### CODE REVIEW

**Review by ryanemerson — CHANGES_REQUESTED** [review]
The approach seems fine to me, but I think all methods that use prepared statements need to be updated to use this. `loadEntry`, `bulkUpdate`, `deleteBatch`, `clear`, `delete`, `purge` `.FlowableConnection`, `prepareWithModifications` and `size`,  all need updating.

**Comment by tristantarrant** [comment]
We should only apply the timeouts to "single-row" operations. Everything else would not be easy to quantify since it would vary on the number of entries.

**Comment by ryanemerson** [comment]
> We should only apply the timeouts to "single-row" operations. Everything else would not be easy to quantify since it would vary on the number of entries.

From the [docs](https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#setQueryTimeout(int)):
```quote
Note: In the case of Statement batching, it is implementation defined as to whether the time-out is applied to individual SQL commands added via the addBatch method or to the entire batch of SQL commands invoked by the executeBatch method (consult your driver vendor documentation for details).
```

So I guess we should probably verify how the main vendors approach this.

**Comment by tristantarrant** [comment]
MySQL applies setQueryTimeout for the entire batch, which is absurd, since our batches may have wildly different sizes.

**Comment by tristantarrant** [comment]
@ryanemerson `delete` and `loadEntry` do have the timeout set (unless I'm missing something)

**Review by ryanemerson — APPROVED** [review]
LGTM just waiting on CI

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
