### PR TITLE
Increase infinispan.stagger.delay default to 5000

### PR DESCRIPTION
**Pull request by tristantarrant**
Want to test 1kb udp dist

### CODE REVIEW

**Comment by alanfx** [comment]
run performance tests
[udp] 
library dist

**Comment by alanfx** [comment]
run performance tests please
[udp]
library dist reads

**Comment by pruivo** [comment]
run performance tests please
[udp]
library dist reads

**Comment by alanfx** [comment]
run performance tests please
[udp]
library dist reads

**Comment by alanfx** [comment]
run performance tests please
[udp]
library dist reads

**Comment by Holmistr** [comment]
run performance tests please
[udp 1kb]
library dist

**Comment by Holmistr** [comment]
run performance tests please
[udp 1kb]
library dist

**Comment by Holmistr** [comment]
@tristantarrant The results above are not correct as it seems that the test run still with 10kb entries. Let me re-run it.

**Comment by Holmistr** [comment]
run performance tests please
[udp 1kb]
library dist

**Comment by Holmistr** [comment]
@tristantarrant The results above should be correct for 1kb entries.

**Pull request closed without merging**
