### PR TITLE
ISPN-14874 Ensure HotRod server has proper pipelining support

### PR DESCRIPTION
**Pull request by wburns**
* Add FlushConsolidationHandler

https://issues.redhat.com/browse/ISPN-14874

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#1](https://ci.infinispan.org/job/Infinispan/job/PR-12910/1/):
```
quay.io/infinispan-test/server:PR-12910
```

**Review by pruivo — APPROVED** [review]

**Comment by wburns** [comment]
Rebased

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#2](https://ci.infinispan.org/job/Infinispan/job/PR-12910/2/):
```
quay.io/infinispan-test/server:PR-12910
```

**Comment by pruivo** [comment]
@wburns Is the failure `ManagedConnectionOperations.testDataSourceCLI:92 Expected output did not contain expected string after timeout expected:<[//containers/default]>]> but was:<[[disconnected]> connect 172.17.0.4:11222` related? Can't the flush be delayed for too long?

**Comment by wburns** [comment]
> @wburns Is the failure `ManagedConnectionOperations.testDataSourceCLI:92 Expected output did not contain expected string after timeout expected:<[//containers/default]>]> but was:<[[disconnected]> connect 172.17.0.4:11222` related? Can't the flush be delayed for too long?

Unrelated, this only changes HR protocol. And no I have not seen issues with flushing being delayed too long. The default is at worst after 256 flushes, but we have never gotten anywhere near that.

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#3](https://ci.infinispan.org/job/Infinispan/job/PR-12910/3/):
```
quay.io/infinispan-test/server:PR-12910
```

**Comment by pruivo** [comment]
@wburns feeling like rebase it again? I would like to see a CI run :)

**Comment by wburns** [comment]
> @wburns feeling like rebase it again? I would like to see a CI run :)

I literally just rebased ;)

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#4](https://ci.infinispan.org/job/Infinispan/job/PR-12910/4/):
```
quay.io/infinispan-test/server:PR-12910
```

**Comment by jabolina** [comment]
Thanks, @wburns!!

**Pull request merged**
