### PR TITLE
Test simple projection in embedded mode

### PR DESCRIPTION
**Pull request by anistor**
Just a test to highlight the issue, not a fix. Please do not close the issue yet.

### CODE REVIEW

**Comment by gustavonalle** [comment]
@anistor Test ```org.infinispan.query.dsl.embedded.impl.EmbeddedQueryEngineTest.testSimpleProjection2``` fails, is this supposed to be ignored?

**Comment by anistor** [comment]
Ooops, that should be ignored because of ... (I do not remember the jira id but I'll find it and update)

**Comment by anistor** [comment]
Updated. CI seems ok now.

**Comment by gustavonalle** [comment]
merged, thanks @anistor

**Pull request merged**
