### PR TITLE
ISPN-9886 Use UFC_NB and MFC_NB in both server and embedded configs 

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9886

1. Add UFC protocol even in TCP stacks 
2. Replace UFC with UFC_NB and MFC with MFC_NB everywhere

### CODE REVIEW

**Comment by tristantarrant** [comment]
@danberindei should we ask for a perfack job ?

**Comment by danberindei** [comment]
run performance tests please

[TCP]
[UDP]

**Comment by diegolovison** [comment]
run performance tests please

[TCP]
[UDP]

**Comment by diegolovison** [comment]
run performance tests please
[TCP]

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please
library
cs
[UDP]

**Comment by diegolovison** [comment]
run performance tests please
library
cs
[UDP]

**Comment by diegolovison** [comment]
run performance tests please
library
cs
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
cs-hotrod repl reads
[UDP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library dist reads
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library
cs
[TCP]

**Comment by danberindei** [comment]
run performance tests please
library
cs
[TCP]

**Comment by diegolovison** [comment]
run performance tests please
library
cs
[TCP]

**Comment by danberindei** [comment]
@tristantarrant max_credits="3m" looks good

**Comment by danberindei** [comment]
I had forgotten to update the protocol list in JGroupsConfigBuilder, the test suite should be ok now.

**Pull request merged**
