### PR TITLE
Bump version to 9.4.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by danberindei**

### CODE REVIEW

**Comment by gustavonalle** [comment]
We also need to bump schemas and 9.3 internal references, I believe there's a script for this

**Comment by danberindei** [comment]
@gustavonalle `reversion.sh` already changes schemas, but it didn't include the endpoint test configuration. I've added a commit for that as well.

**Comment by galderz** [comment]
Build error:

    java.io.FileNotFoundException... rolling-upgrades-clustered-rest-9.4.xml

**Comment by danberindei** [comment]
Updated again to include more xmls in the reversion.sh script and to fix the `Namespace` class that I missed.

**Comment by gustavonalle** [comment]
Build failed, triggered another one...

**Comment by tristantarrant** [comment]
Fixed the jgroups subsystem failures and pushed.

**Pull request closed without merging**
