### PR TITLE
ISPN-6494 Change the default bundler to transfer-queue

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-6494

Stop adding the DONT_BUNDLE flag for OOB+GET_ALL/GET_FIRST messages

### CODE REVIEW

**Comment by alanfx** [comment]
Hey @danberindei, does this change need to be made in the default-configs in core, or is this PR to start comparing the bundlers first? Just wondering

**Comment by danberindei** [comment]
@alanfx  Yes, I somehow missed exactly the defaults that I wanted to change, but they should be updated now.

**Comment by alanfx** [comment]
Haha, got it this time @danberindei! 💯

**Comment by tristantarrant** [comment]
Pushed to master, thanks

**Pull request closed without merging**
