### PR TITLE
ISPN-6472 Add server-side SASL EXTERNAL mech for client-certificate authentication

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-6472
https://issues.jboss.org/browse/ISPN-6473

### CODE REVIEW

**Comment by vjuranek** [comment]
Tested with standalone as well as clustered config and everything looks good :+1:

**Comment by tristantarrant** [comment]
This now includes @vjuranek 's integration tests https://github.com/infinispan/infinispan/issues/4220

**Comment by galderz** [comment]
Looks good, testing...

**Comment by galderz** [comment]
CI says there's a new test failure in:

     SecurityManagerCacheAuthorizationTest.testAllCombinations

I run it locally and I see that test failing the same way as CI.

It doesn't look related but could it be somehow? @tristantarrant ?

**Comment by vjuranek** [comment]
@galderz it's not related and was fixed in 31bf6d87dd86411e10fd95fe69357f1836c38a7b, if you rebase, test should be passing

**Comment by tristantarrant** [comment]
@galderz as @vjuranek says this is unrelated and already fixed

**Comment by galderz** [comment]
Thanks guys, I'll integrate :)

**Comment by galderz** [comment]
Integrated! Thanks!

**Pull request closed without merging**
