### PR TITLE
ISPN-8879 Do not use a default realtive-to for the server shared pers…

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-8879

### CODE REVIEW

**Comment by ryanemerson** [comment]
@tristantarrant it seems `org.infinispan.server.test.query.RemoteQueryStringIT.testFullTextTermRightOperandAnalyzed` is related.

```
Caused by: org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0089: Failed to write configuration
	at org.jboss.as.controller.persistence.AbstractConfigurationPersister.marshallAsXml(AbstractConfigurationPersister.java:100)
	at org.jboss.as.controller.persistence.AbstractFilePersistenceResource.<init>(AbstractFilePersistenceResource.java:42)
	... 32 more
```

**Comment by tristantarrant** [comment]
Actually it is not related at all, because the exception happens while writing the cachecontainer name...

**Comment by tristantarrant** [comment]
Issuing a rebuild just to make sure

**Comment by tristantarrant** [comment]
Latest build doesn't have that failure

**Pull request merged**
