### PR TITLE
[9.4.x] ISPN-10556 Add antlr-runtime to the javadoc dependencies to fix build

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.jboss.org/browse/ISPN-10556

### CODE REVIEW

**Comment by pruivo** [comment]
added the same fix for javadoc-embedded and javadoc-remote

**Comment by anistor** [comment]
LGTM. Why is it 'on hold'?

**Comment by pruivo** [comment]
@anistor it isn't. The label was removed 2h ago :)

**Comment by anistor** [comment]
ok. just noticed gson needs exactly the same handling as antlr. will fix that myself and merge.

**Comment by anistor** [comment]
Merged. thanks @pruivo !

**Pull request closed without merging**
