### PR TITLE
[13.0.x] ISPN-13711 Improve memory usage for IRAC

### PR DESCRIPTION
**Pull request by pruivo**
Depends on https://github.com/infinispan/infinispan/pull/9955

https://issues.redhat.com/browse/ISPN-13711

### CODE REVIEW

**Comment by tristantarrant** [comment]
Seeing some async xsite failures

**Comment by pruivo** [comment]
they are caused by https://github.com/infinispan/infinispan/pull/9954 and they are fixed in that PR.

**Comment by tristantarrant** [comment]
Can you rebase ?

**Comment by wburns** [comment]
Integrated into 13.0.x, thanks @pruivo !

**Pull request merged**
