### PR TITLE
ISPN-9950 CLI

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-9950

This PR is quite large as it completely replaces our old CLI. 
There are two commits. The first one affects the rest client:
* refactoring of our RESTful client to be a bit less "raw"
* automatic detection of HTTP authentication and caching of authorization tokens (BASIC, DIGEST, BEARER)

The second commit is the CLI itself. Highlights:
* Based on the latest aesh code
* Hierarchical representation of the server (only caches and counters for now) with cd/ls commands as well as shortcuts (cache) to jump to specific parts of the tree
* cache/counter create/drop, put/get/remove/query, describe
* tab completion for everything
* automatically detects if authentication is required and prompts for credentials if they have not been supplied
* TLS support
* For the first time a test which programmatically controls the CLI input/output against a real cluster of servers.

Missing bits (coming as future PRs):
* full help/man page support
* transactional commands (because the REST endpoint doesn't support them yet)
* server/cluster/nodes views in the hierarchy
This breaks the embedded functionality temporarily. This will be restored in 10.1 with https://issues.jboss.org/browse/ISPN-10593

### CODE REVIEW

**Comment by ryanemerson** [comment]
Not had a chance to look at the code, but `cli.BatchingTest` is failing.

**Comment by tristantarrant** [comment]
I disabled the test for now

**Comment by tristantarrant** [comment]
This is now ready

**Comment by tristantarrant** [comment]
Failures are unrelated

**Comment by gustavonalle** [comment]
Integrated, thanks @tristantarrant !

**Pull request merged**
