### PR TITLE
ISPN-6803 Pre-compute bitsets for each flag

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-6803

### CODE REVIEW

**Comment by rvansa** [comment]
Have you checked generated assembly what the original `hasFlag(Flag.SOME)` really did? I would assume that in C2 this is already inlined to a constant.

**Comment by danberindei** [comment]
@rvansa Yes, this came from looking at the generated assembly (and one of Shipilev's blog posts). C2 can only replace `static final` fields with a constant, not regular `final` fields (like the ordinal in an enum).

**Comment by danberindei** [comment]
Rebased + updated to replace some usages of `EnumUtil.hasEnum()` and `EnumUtil.setEnum()` with their `FlagBitSets`-based alternatives.

**Comment by tristantarrant** [comment]
In it goes. Thanks

**Pull request closed without merging**
