### PR TITLE
ISPN-10813 File Stores should notify user of being segmented can use many file descriptors

### PR DESCRIPTION
**Pull request by wburns**
https://issues.jboss.org/browse/ISPN-10813

### CODE REVIEW

**Comment by wburns** [comment]
This PR is really only the last commit, the other is from https://github.com/infinispan/infinispan/pull/7447

**Comment by wburns** [comment]
I expect the first real run to have a number of failures, but hopefully should be simple enough to resolve.

**Comment by wburns** [comment]
Changed to only print a WARN message when segmented file stores are used in config.

**Comment by ryanemerson** [comment]
Thanks @wburns

**Pull request merged**
