### PR TITLE
ISPN-15026 Automatically map ADMIN and MONITOR permissions to JMX roles

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-15026

Missing tests and docs. @ryanemerson see if this works for your needs

### CODE REVIEW

**Comment by ryanemerson** [comment]
I tested locally with `jmc` and was able to connect as expected if a user was created with `admin` or `monitor` group :+1:

**Comment by tristantarrant** [comment]
Added JMX tests

**Comment by ryanemerson** [comment]
`AuthorizationJMXIT` is failing with a NPE.

**Comment by tristantarrant** [comment]
> `AuthorizationJMXIT` is failing with a NPE.

Obviously, running locally, it works fine

**Comment by tristantarrant** [comment]
I believe I've found the correct incantation for connecting to JMX through the container

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Comment by tristantarrant** [comment]
@ryanemerson maybe we should backport it ?

**Pull request merged**
