### PR TITLE
ISPN-8184 Replace maven keytool plugin with faster ant script

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-8184

Additionally fix some maven warnings.

### CODE REVIEW

**Comment by gustavonalle** [comment]
There are test failures related to security

**Comment by tristantarrant** [comment]
Yeah, missed a certificate. Let's wait for CI again

**Comment by tristantarrant** [comment]
There was one last issue related to the client cert identity in the server testsuite. Fixed now.

**Comment by ryanemerson** [comment]
@tristantarrant Merged, thanks! We even got a green build.

**Pull request merged**
