### PR TITLE
[14.0.x] ISPN-14329 Availability of caches should be prevented until a cluster...

### PR DESCRIPTION
**Pull request by jabolina**
is complete after "shutdown cluster"

https://issues.redhat.com/browse/ISPN-14329
https://issues.redhat.com/browse/ISPN-14414

Backporting #10479.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#3](https://ci.infinispan.org/job/Infinispan/job/PR-10727/3/):
```
quay.io/infinispan-test/server:PR-10727
```

**Comment by wburns** [comment]
There are a lot of failures, I am guessing they are unrelated?

**Comment by jabolina** [comment]
I think so, but replaying again just to check.

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#4](https://ci.infinispan.org/job/Infinispan/job/PR-10727/4/):
```
quay.io/infinispan-test/server:PR-10727
```

**Pull request merged**
