### PR TITLE
ISPN-8894 Remove usages of junit.framework.*

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-8894

### CODE REVIEW

**Comment by tristantarrant** [comment]
Looks like you have just introduced the following new failures:
org.infinispan.test.hibernate.cache.commons.entity.EntityRegionAccessStrategyTest.testInsert[non-JTA, INVALIDATION_SYNC,AccessType[transactional]]
org.infinispan.test.hibernate.cache.commons.entity.EntityRegionAccessStrategyTest.testPutFromLoad[non-JTA, INVALIDATION_SYNC,AccessType[transactional]]
org.infinispan.test.hibernate.cache.commons.entity.EntityRegionAccessStrategyTest.testPutFromLoadMinimal[non-JTA, INVALIDATION_SYNC,AccessType[transactional]]
org.infinispan.test.hibernate.cache.commons.entity.EntityRegionAccessStrategyTest.testUpdate[non-JTA, INVALIDATION_SYNC,AccessType[transactional]]
org.infinispan.test.hibernate.cache.commons.entity.EntityRegionAccessStrategyTest.testInsert[non-JTA, INVALIDATION_SYNC,AccessType[transactional]]
org.infinispan.test.hibernate.cache.commons.entity.EntityRegionAccessStrategyTest.testPutFromLoad[non-JTA, INVALIDATION_SYNC,AccessType[transactional]]
org.infinispan.test.hibernate.cache.commons.entity.EntityRegionAccessStrategyTest.testPutFromLoadMinimal[non-JTA, INVALIDATION_SYNC,AccessType[transactional]]
org.infinispan.test.hibernate.cache.commons.entity.EntityRegionAccessStrategyTest.testUpdate[non-JTA, INVALIDATION_SYNC,AccessType[transactional]]

**Comment by anistor** [comment]
I've undone the junit.framework.AssertionFailedError related changes and kept the rest.

**Comment by danberindei** [comment]
@anistor I see you've kept the `AssertionFailedError` -> `AssertionError` change in `QueryRegionImplTest`, could you add some details in JIRA on why it works there and not in the other tests?

**Comment by anistor** [comment]
Rebased and removed some of my changes related to AssertionFailedError because they are fixed by Radim's work.

**Comment by danberindei** [comment]
Integrated, thanks Adrian!

**Pull request merged**
