### PR TITLE
ISPN-15725 TracingConfiguration categories always serialized

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-15725

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#1](https://ci.infinispan.org/job/Infinispan/job/PR-12015/1/):
```
quay.io/infinispan-test/server-native:PR-12015
```

**Review by fax4ever — CHANGES_REQUESTED** [review]
Hi @ryanemerson. Thanks for the PR.
We have [this test failing](https://ci.infinispan.org/job/Infinispan/job/PR-12015/1/testReport/junit/org.infinispan.configuration.parsing/UnifiedXmlFileParsingTest/testParseAndConstructUnifiedXmlFile__15_0_xml__/).
The container is supposed to enabled by default.

**Comment by ryanemerson** [comment]
@fax4ever It should be good now. I had to move the default value logic to be contained exclusively within the attribute initializer.

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#2](https://ci.infinispan.org/job/Infinispan/job/PR-12015/2/):
```
quay.io/infinispan-test/server:PR-12015
```

**Comment by fax4ever** [comment]
> @fax4ever It should be good now. I had to move the default value logic to be contained exclusively within the attribute initializer.

@ryanemerson  the change looks good. I'm just running some test locally then I merge it. Thank you

**Comment by fax4ever** [comment]
Merged, thanks for this fix @ryanemerson!

**Pull request merged**
