### PR TITLE
[PERF] testing with triangle

### PR DESCRIPTION
**Pull request by pruivo**
Includes ISPN-7367 (PR: https://github.com/infinispan/infinispan/pull/4774)
Partial work: removing the PrimaryAckCommand
Testing: Add NO_FC to BackupAck.
Some refactoring in small methods.

### CODE REVIEW

**Comment by pruivo** [comment]
run performance tests please
library dist writes

**Comment by pruivo** [comment]
run performance tests please
library dist writes

**Comment by pruivo** [comment]
ops...

**Comment by Holmistr** [comment]
run performance tests please
library dist writes

**Comment by pruivo** [comment]
run performance tests please
library dist writes

**Comment by pruivo** [comment]
last try...

**Pull request closed without merging**
