### PR TITLE
ISPN-11156 Move the CustomFailurePolicy interface to a different pack…

### PR DESCRIPTION
**Pull request by pruivo**
…age than org.infinispan.xsite

https://issues.redhat.com/browse/ISPN-11156

### CODE REVIEW

**Comment by pruivo** [comment]
@wburns agree! 
I added a sentence to the upgrade guide.

**Comment by wburns** [comment]
Integrated into master, thanks @pruivo !

**Comment by danberindei** [comment]
@pruivo @wburns I'm not aware of any other SPI like this being in the configuration package, wouldn't it have been simpler to move the impl classes to another package?

**Comment by wburns** [comment]
> @pruivo @wburns I'm not aware of any other SPI like this being in the configuration package, wouldn't it have been simpler to move the impl classes to another package?

I am not picky, so wherever you think is best :)

**Comment by pruivo** [comment]
> @pruivo @wburns I'm not aware of any other SPI like this being in the configuration package, wouldn't it have been simpler to move the impl classes to another package?

what impl? to move it here? `org.infinispan.xsite` isn't public. It is simpler to be in the configuration package than move all xsite classes to another package just to make the `org.infinispan.xsite` public.

**Comment by danberindei** [comment]
@pruivo yes, it's simpler for us to move the class to the configuration package, but for the user we've just added yet another inconsistency in our API.

**Pull request merged**
