### PR TITLE
ISPN-14064 RESP server should implement COMMAND command

### PR DESCRIPTION
**Pull request by wburns**
* ERR for any command arguments

https://issues.redhat.com/browse/ISPN-14064

### CODE REVIEW

**Comment by jabolina** [comment]
CI was crazy, just restarted. Should we add a test for this?

**Comment by wburns** [comment]
> CI was crazy, just restarted. Should we add a test for this?

Sure, I can add a simple one real quick

**Comment by wburns** [comment]
Actually I don't see a way with lettuce to invoke `COMMAND DOCS`. Guessing the API was only designed for redis 6, probably why lettuce is on release 6 as well. Guessing once Lettuce 7 comes out we can add a test if we ever remember.

**Comment by tristantarrant** [comment]
> Actually I don't see a way with lettuce to invoke `COMMAND DOCS`. Guessing the API was only designed for redis 6, probably why lettuce is on release 6 as well. Guessing once Lettuce 7 comes out we can add a test if we ever remember.

You can use https://github.com/lettuce-io/lettuce-core/wiki/Custom-commands,-outputs-and-command-mechanics

```java
Command<...> response = redis.dispatch(CommandType.COMMAND, new StatusOutput<>(StringCodec.UTF8),
               new CommandArgs<>(StringCodec.UTF8).add("DOCS"));
```

**Comment by tristantarrant** [comment]
I've created https://github.com/wburns/infinispan/pull/3

**Comment by wburns** [comment]
Pulled in your changes, thanks @tristantarrant Just added a very small tweak to limit lines changed.

**Review by jabolina — APPROVED** [review]

**Pull request merged**
