### PR TITLE
ISPN-9224 Reduce ExceptionEvictionTest combinations

### PR DESCRIPTION
**Pull request by wburns**
* Comment out OFFHEAP/BINARY cluster mode options

https://issues.jboss.org/browse/ISPN-9224

### CODE REVIEW

**Comment by danberindei** [comment]
@wburns, I've looked a little more into this and I think it would be better to keep all the configurations for the base test if we split off the expiration, state transfer, and overflow on scale down test methods into separate classes that only deal with OBJECT storage (or BINARY, or OFF_HEAP if you think it would be more interesting).

There's also a small inefficiency in `clearContent()`, which invokes `cache.clear()` on all the caches but without `CACHE_MODE_LOCAL`. Just setting the interceptor field saved me almost 1 minute (w/ trace logging enabled). Weird, because it's 1 call instead of 3, calling just `cache(0).clear()` got me almost exactly in the middle, with 30s saved vs. master.

So even without the OffHeapMemory logging, the extra data container iterations seem quite expensive. I wonder if we could make it faster, maybe we could implement `forEach()` in `OffHeapDataContainer` to avoid the stream overhead?

We could also skip the data container iteration in `ClearCommand` and `AbstractClusterDependentLogic` if there are no remove listeners, but I'm not sure how I'd like a remove-specific method in `CacheNotifier`, I'd like a more generic solution there for interceptors to also skip loading the previous value when possible. Maybe `CacheImpl` could set the `SKIP_CACHE_LISTENERS` flag on the command when there are no listeners registered at command start? Or maybe we'll even change `clear()` to not notify listeners at all...

**Comment by danberindei** [comment]
Forgot another option, maybe we could use a smaller `addressCount` in tests and/or when we know the size limit?

**Comment by wburns** [comment]
Reducing the address count to say `1 << 7` cut the time to a third. So I can just change that.

**Comment by wburns** [comment]
Updated.

**Comment by tristantarrant** [comment]
Merged

**Pull request merged**
