### PR TITLE
ISPN-8167 Archive debug logs in CI

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-8167

Personally I'm hoping to get more info about the `SiteStatementTest` random failure...

### CODE REVIEW

**Comment by pruivo** [comment]
@danberindei it looks good to me... but aren't we having problems with disk space? when are they deleted?

**Comment by danberindei** [comment]
@pruivo The zipped logs are ~ 40MB per build, which means < 10GB for 200 builds, so we should be fine. We ran out of disk space on the Jenkins server mostly because of a few 8.2.x builds that had > 2GB of logs (ISPN-8170).

**Comment by pruivo** [comment]
ok. going to merge

**Comment by pruivo** [comment]
integrated! thanks @danberindei !

**Comment by tristantarrant** [comment]
Tried using tar cJf. The savings are great:

41852 logs-PR-5365-2.zip  17152 logs.tar.xz

**Pull request merged**
