### PR TITLE
ISPN-6685 Hot Rod server fails to start due to NPE in PersistenceManagerImpl.preload()

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-6685

### CODE REVIEW

**Comment by danberindei** [comment]
Integrated, thanks Gustavo!

**Comment by danberindei** [comment]
Note: the test failures were caused by a leftover build, stuck in `ClientEventsOOMTest`.

**Comment by danberindei** [comment]
@gustavonalle There were some conflicts rebasing to 8.2.x, and while resolving them I noticed that other methods like `visitRemoveCommand` also invoke sub-commands. Shouldn't they also copy the flags of the parent command?

**Comment by danberindei** [comment]
@gustavonalle There were some conflicts rebasing to 8.2.x, and while resolving them I noticed that other methods like `visitRemoveCommand` also invoke sub-commands. Shouldn't they also copy the flags of the parent command?

**Comment by gustavonalle** [comment]
@danberindei those extra commands do not happen on preload, so the fact the flags are not copied does not cause any issues.

**Comment by tristantarrant** [comment]
So should this be closed ?

**Comment by danberindei** [comment]
Yep, closing.

**Pull request closed without merging**
