### PR TITLE
Reduce the number of ignored tests

### PR DESCRIPTION
**Pull request by tristantarrant**
- Fix SecureScriptingTest
- Skip subsystem template validation until it supports supplements
- Remove unnecessary tests

### CODE REVIEW

**Comment by tristantarrant** [comment]
It should bring the count down from 58 to less than 30, but let's wait for CI

**Comment by tristantarrant** [comment]
Tests failed: 4 (3 new), passed: 18478, ignored: 18, muted: 4

**Comment by gustavonalle** [comment]
Integrated, thanks @tristantarrant !

**Comment by danberindei** [comment]
Nice!

**Pull request merged**
