### PR TITLE
ISPN-7402 Expose ProtobufMetadataManager.getFileErrors and ProtobufMe…

### PR DESCRIPTION
**Pull request by anistor**
…tadataManager.getFilesWithErrors as DMR operations

https://issues.jboss.org/browse/ISPN-7402
https://issues.jboss.org/browse/ISPN-7416

### CODE REVIEW

**Comment by anistor** [comment]
Sample CLI invocations:

Get all file names that have errors:
./bin/ispn-cli.sh -c '/subsystem=datagrid-infinispan/cache-container=local:get-proto-schemas-with-errors'

Get error message for a particular file:
./bin/ispn-cli.sh -c '/subsystem=datagrid-infinispan/cache-container=local:get-proto-schema-errors(file-name=myfile.proto)'

**Comment by anistor** [comment]
Updated.

**Comment by tristantarrant** [comment]
I'd collapse the two ops into one: if the file-name parameter is missing, list the broken files

**Comment by anistor** [comment]
@tristantarrant I kept the DMR ops separated in order to have a direct 1-1 mapping to methods in ProtobufMetadataManagerMBean interface. And also to mirror the other ops for obtaining the schema names and schema contents respectivvely: get-proto-schema-names and get-proto-schema. I'd rather keep them separated.

**Comment by anistor** [comment]
@tristantarrant @vblagoje Can one of you merge this? I'm currently on PTO.

**Pull request merged**
