### PR TITLE
ISPN-16233 Fix Netty buffer leaks

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-16233

I've added code that fails the server testsuite if a leak is detected

### CODE REVIEW

**Comment by ryanemerson** [comment]
Changes LGTM. Just waiting on CI.

**Comment by ryanemerson** [comment]
Restarting CI, the previous run failed with:

```
[2024-07-17T08:32:54.240Z] [TestSuiteProgress] Test failed: org.infinispan.server.resp.persistent.ClusteredPersistentStringCommandTest.clearContent
[2024-07-17T08:32:54.241Z] Dumping threads of process 22772 to /home/infinispan/workspace/Infinispan_PR-12645/server/resp/threaddump-ClusteredPersistentStringCommandTest-20240717-0432-22772.log
[2024-07-17T08:32:54.241Z] Interrupted thread testng-ClusteredPersistentStringCommandTest (39).
```

**Comment by tristantarrant** [comment]
It's green now

**Comment by tristantarrant** [comment]
Green now

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
