### PR TITLE
ISPN-5154 Generalize JCache constructor so that it can be reused by a custom CachingProvider.

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/ISPN-5154

### CODE REVIEW

**Comment by galderz** [comment]
@pferraro Can you create a JIRA for this?

Also, I can see why you'd want to use an interface as parameter instead of a class. I'm not 100% sure about the need to remove `final` though. Can you post a link to a branch where you're integrating JCache into Wildfly? I'd like to have a look to see if it could be done any different.

**Comment by pferraro** [comment]
In Infinispan's implementation, there is a 1:1 relationship between a JCacheManager and an EmbeddedCacheManager.  In WildFly's implementation, I expect this to be a many:1 relationship.  That is, rather than a JCacheManager being uniquely identified by both URI and ClassLoader, WildFly's CachingProvider will use a CacheManager per URI, and identify a Cache by both module and cache name.  In this way Cache.getName() might be "foo", but the underlying Infinispan Cache.getName() is actually "foo+module-id".  To do this, I would need to be able to override the JCache.getName() method.

**Comment by danberindei** [comment]
@pferraro Looks ok to me, but I'd squash the commits and add the issue number in the commit message.

**Comment by pferraro** [comment]
Done.

**Comment by galderz** [comment]
@pferraro Wouldn't delegation work here as well? I agree that's more cumbersome and extra cache object, but a new JCache implementation for WF delegating to the `infinispan-cache` one might have worked... I'm happy to integrate as is, but just wondering...

**Comment by pferraro** [comment]
Delegation won't work if I want to override the behavior of JCache.getName(), since internal (i.e. within JCache itself) requests for the name of the cache will use the JCache implementation, instead of the decorator implementation.

**Comment by galderz** [comment]
@pferraro Makes sense, I'll get this integrated right away.

**Pull request closed without merging**
