### PR TITLE
ISPN-12909 CloudEvents integration not working in server

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-12909

* Fix cloud events invalid configuration test
* Add cloudevents-integration dependency to server
* Add scope annotation to KafkaEventSenderFactory
* Do not send cloud events for internal caches
* Add integration test for cloud events

### CODE REVIEW

**Comment by danberindei** [comment]
Updated to fix a server startup failure in the server-integration module.

**Comment by danberindei** [comment]
Updated to fix the failures in `CloudEventsCacheEventsTest`. `TestModuleLifecycle` was registering the mock component factory too early, I fixed it by adding an optional dependency on the `cloudevents` module in the `core-tests` module.

**Review by wburns — APPROVED** [review]
Changes look good to me. Just need to wait for CI.

**Comment by wburns** [comment]
Integrated into master, thanks @danberindei !

**Pull request merged**
