### PR TITLE
ISPN-5683 Removed whitespaces at the end of the lines

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/ISPN-5683

Please do not close the issue once this PR gets in. I'm turning on the rules gradually. 

Fixed by a simple command:
```
find . -name "*.java" -exec sed -i 's/\s*$//' {} \;
```

@rvansa @anistor @galderz @Sanne Could you please review it?

### CODE REVIEW

**Comment by rvansa** [comment]
-1 I use git annotate (blame) to crawl through history quite often, and this introduced unwanted churr.

**Comment by slaskawi** [comment]
@rvansa Hey Radim! Just to be crystal clear - the alternative is to skip this rule. 

I assume you are `-1` for submitting this change and `+1` for removing the rule for checking empty char at the end of the line?

**Comment by anistor** [comment]
http://bit.ly/29oQu40  :broken_heart: :disappointed:

**Comment by rvansa** [comment]
@slaskawi Yep. My priority list is : nice history > no invisible chars on the end of lines > invisible chars on the end of lines

Is it possible that such post-processing would be rather a part of a commit hook, affecting only diffs?

**Comment by slaskawi** [comment]
I have an idea - would you prefer to have this one or https://github.com/infinispan/infinispan/pull/4515 ? Let the vote begin!

**Comment by slaskawi** [comment]
:-1: from me

**Comment by anistor** [comment]
If we give up on this then we might as well give up on the remaining ~35 rules. -1 for giving up.

**Comment by anistor** [comment]
By looking at the changes I see that the majority are on empty lines or javadocs, and few on actual statements. There will be some noise in history indeed, but not where it hurts the most. I'd allow this. And would even go as far as activate the manadatory new-line at EOF rule too so we are spared from seeing these: https://github.com/infinispan/infinispan/pull/4513/files#diff-e2e6f183514f1de4a3e41498851f8a46L6

**Comment by slaskawi** [comment]
@anistor has a point here. If we give up one simple rule like this one, we might give up all of them. Also if you use formatter, you should never see this violation in practice. So changing my mind, :+1: from me.

**Comment by tristantarrant** [comment]
My vote is with Adrian on this one

**Comment by rvansa** [comment]
Okay, I admit I haven't checked all the files - if it's mostly javadoc, it probably won't hurt.

**Comment by ryanemerson** [comment]
+1 It will be worth the initial pain in the long run.

**Comment by slaskawi** [comment]
Rebased

**Comment by anistor** [comment]
Looking again and pulling...

**Comment by anistor** [comment]
Integrated. Thanks @slaskawi !

**Pull request merged**
