### PR TITLE
[11.0.x] ISPN-12184 Don't override explicit authentication mechanisms

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-12184

### CODE REVIEW

**Comment by tristantarrant** [comment]
A green build !

**Comment by pruivo** [comment]
@tristantarrant is this updated with the comments I made for the master PR? or I need to review this one? :)

**Comment by tristantarrant** [comment]
Yes, I believe I've backported all the relevant ones (a lot of the changes were in the multi endpoint code)

**Comment by pruivo** [comment]
integrated! thanks @tristantarrant !

**Pull request merged**
