### PR TITLE
ISPN-9863 Fix testsuite thread leaks 

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9863
https://issues.jboss.org/browse/ISPN-8610
https://issues.jboss.org/browse/ISPN-9882
https://issues.jboss.org/browse/ISPN-9884
https://issues.jboss.org/browse/ISPN-9898
https://issues.jboss.org/browse/ISPN-9933

### CODE REVIEW

**Comment by danberindei** [comment]
Updated, should fix or ignore all the reported leaks now.

**Comment by danberindei** [comment]
Rebased and added fix for https://issues.jboss.org/browse/ISPN-9933 + ignore thread leak caused by https://issues.jboss.org/browse/ISPN-9935

**Comment by ryanemerson** [comment]
@danberindei It seems there are still some related failures.

**Comment by danberindei** [comment]
I finally got back to this @ryanemerson 

The `unset-*` "leaks" were from tests that didn't extend `AbstractInfinispanTest` and so never set the test name for the thread. The one in the router module was an actual leak in the test.

**Comment by ryanemerson** [comment]
@danberindei So close! But `SampleRemoteCacheTest.springTestContextAfterTestClass` still has a leak.

**Comment by danberindei** [comment]
@ryanemerson it wasn't a leak really, H2 starts a thread and only waits 400ms for it to finish (allegedly it normally takes < 200ms), so I added it to the whitelist in `ThreadLeakChecker`.

**Comment by danberindei** [comment]
The new leak is caused by https://issues.jboss.org/browse/ISPN-9988, I'll fix it in a separate PR @ryanemerson

**Comment by ryanemerson** [comment]
Soo many Jiras to resolve :smile: Thanks @danberindei

**Comment by danberindei** [comment]
Yeah, this is one PR where I can really say that I did not intent for it to grow nearly as big :))
Thanks Ryan!

**Pull request merged**
