### PR TITLE
ISPN-7144 Cross-Site Replication: inconsistent data with multiple sit…

### PR DESCRIPTION
**Pull request by pruivo**
…e masters

* Force single and same route for all requests

https://issues.jboss.org/browse/ISPN-7144

### CODE REVIEW

**Comment by tristantarrant** [comment]
Doesn't this change affect both sync and async behaviour ?

**Comment by pruivo** [comment]
yes :(

**Comment by tristantarrant** [comment]
So effectively this is disabling multiple site masters. Wouldn't it be better then to just discourage its use, via a warning, instead of modifying the behaviour ?

**Comment by pruivo** [comment]
a warning doesn't solve the inconsistencies when they happen :)
but if you think it would be better, I'll change but it won't be 100% accurate because you can have a single site-master in site A (Primary Site) e multiple site-masters in site B (Backup Site) .

**Comment by galderz** [comment]
Is multiple site masters enabled by default? I wasn't aware of it actually, what is used for? Failover? Or to have one master connected to one site and another master to a different site? Couldn't find anything in the docu about multiple site masters

**Comment by pruivo** [comment]
@galderz no, the default is a single site master. It is to improve the performance. if you have a single site master, all the requests sent to the remote site need to go through that node. If you have more than one, it picks one site master randomly. Finally, a single site master can be connected to multiple remote sites.

**Comment by tristantarrant** [comment]
Merged to master

**Comment by tristantarrant** [comment]
Merged to 9.0.x too

**Pull request merged**
