### PR TITLE
ISPN-5009 Rebase server to WildFly 8.2

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5009
- ISPN-5009 WildFly 8.2
- Also micro bumps of Netty and Scala

### CODE REVIEW

**Comment by galderz** [comment]
I'm looking at those two failures

**Comment by galderz** [comment]
Had a look but could not see anything obviously wrong with it.

**Comment by slaskawi** [comment]
Hey @tristantarrant, @galderz !

For some reason `Cache` and `AdvancedCache` producers (InfinispanExtensionEmbedded#registerCacheBeans) are not added to the BeanManager and because of that are not used for injection. As a result we can see error messages like this [1].

I noticed that the beans are registered a bit differently in Weld's 2.2 manual [2]. I will try this approach and ask Weld Team for advice if needed. In the meantime I would suggest turning off those tests and creating Jira for them (please feel free to assign me to this issue). 

[1] https://gist.github.com/slaskawi/ac83d30a62a8d12550f4
[2] http://docs.jboss.org/weld/reference/latest-2.2/en-US/html_single/#_registering_a_literal_bean_literal

**Comment by galderz** [comment]
@slaskawi Rather than disabling the tests, let's close this PR and open a new one when the upgrade to WF 8.2 works as expected. Closing this PR for the time being.

**Pull request closed without merging**
