### PR TITLE
ISPN-13915 and others to fix build for Quarkus

### PR DESCRIPTION
**Pull request by tristantarrant**
Some cumulative fixes for Quarkus builds

https://issues.redhat.com/browse/ISPN-13912 Elytron 1.19.0.Final
https://issues.redhat.com/browse/ISPN-13913 Kubernetes Client 5.12.2
https://issues.redhat.com/browse/ISPN-13914 Remove filesystem-realm from the server
https://issues.redhat.com/browse/ISPN-13915 Refactor registration of InitialContextFactoryBuilder for Quarkus substitution

### CODE REVIEW

**Comment by ryanemerson** [comment]
The testsuite doesn't seem to like the parser changes

**Comment by tristantarrant** [comment]
Failures are unrelated

**Comment by ryanemerson** [comment]
Almost there!
```
[org.infinispan.server.configuration.security.KeyStoreConfigurationTest.shouldThrowOnInvalidAlias[application/xml]](https://ci.infinispan.org/job/Infinispan/job/PR-10131/3/testReport/junit/org.infinispan.server.configuration.security/KeyStoreConfigurationTest/shouldThrowOnInvalidAlias_application_xml_/)
[org.infinispan.server.configuration.security.KeyStoreConfigurationTest.shouldThrowOnInvalidAlias[application/yaml]](https://ci.infinispan.org/job/Infinispan/job/PR-10131/3/testReport/junit/org.infinispan.server.configuration.security/KeyStoreConfigurationTest/shouldThrowOnInvalidAlias_application_yaml_/)
[org.infinispan.server.configuration.security.KeyStoreConfigurationTest.shouldThrowOnInvalidAlias[application/json]](https://ci.infinispan.org/job/Infinispan/job/PR-10131/3/testReport/junit/org.infinispan.server.configuration.security/KeyStoreConfigurationTest/shouldThrowOnInvalidAlias_application_json_/)
```

**Comment by tristantarrant** [comment]
Those are present on `main` too https://ci.infinispan.org/job/Infinispan/job/main/496/

**Comment by ryanemerson** [comment]
Argh I see! Merged, thanks @tristantarrant

**Pull request merged**
