### PR TITLE
[8.2.x] ISPN-7991 Improve Compatibility between Rest and HotRod for text content

### PR DESCRIPTION
**Pull request by gustavonalle**
- created no-arg ctor marshaller to be used as compat marshaller for Strings

https://issues.jboss.org/browse/ISPN-7991

### CODE REVIEW

**Comment by tristantarrant** [comment]
As I commented on https://github.com/infinispan/infinispan/pull/5277 it would be better to backport StringMarshaller from master adding a no-arg constructor which uses UTF-8

**Comment by anistor** [comment]
Some comments from https://github.com/infinispan/infinispan/pull/5278 should be applied here too.

**Comment by gustavonalle** [comment]
@anistor I renamed the marshaller to match other branches, anything else missing?

**Comment by anistor** [comment]
Integrated in 8.2.x. Thanks @gustavonalle !

**Pull request merged**
