### PR TITLE
ISPN-15383 Support vector search filtering elements

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-15383

~~Based on top of https://github.com/infinispan/infinispan/pull/12211~~ done!

### CODE REVIEW

**Review by rigazilla — COMMENTED** [review]
Overall LGTM.
Do we have test for cases where prefiltering selects 0 or less then ~k items?

**Comment by fax4ever** [comment]
> Overall LGTM. Do we have test for cases where prefiltering selects 0 or less then ~k items?

Thank you @rigazilla for the review.
Sure it is a good idea to add the test. Done

**Review by rigazilla — APPROVED** [review]

**Review by karesti — APPROVED** [review]
I'm eager to use it for langchain filtering already. 
I'm unable to tell if something is missing without actually working on the integration. Maywe release and add eventual missing pieces afterwards ?

**Comment by rigazilla** [comment]
merged thanks @fax4ever !

**Pull request merged**
