### PR TITLE
ISPN-14179 Update for Infinispan Quarkus

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-14179

### CODE REVIEW

**Comment by wburns** [comment]
This accidentally disables logging output for some reason.. still investigating why as the methods are all invoked still.

**Comment by wburns** [comment]
Pretty sure it was because I accidentally moved the logJVMInformation method before the logger initialization. Verifying..

**Comment by wburns** [comment]
Should be working fine now that I swapped the position of the logging and JVM information methods.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
