### PR TITLE
ISPN-16680 Alias reassignment

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-16680

### CODE REVIEW

**Comment by karesti** [comment]
I respectfully disagree with the approach taken in this operation:

While this may appear to be a simple configuration change, it could potentially have significant negative impacts on your applications, especially when dealing with multiple caches in production. The API behavior seems inconsistent.

Comparing to the delete cache operation, it is clearly labeled as "delete," ensuring that users are fully aware of its intent. In contrast, the alias flip functions inconsistently, whether creating or removing aliases. 

Given these concerns, I won’t be able to approve this PR myself. I’m sorry for any inconvenience caused. 😅

**Review by karesti — CHANGES_REQUESTED** [review]
Comment added

**Comment by tristantarrant** [comment]
I get your complaint, but you are asking for a cache configuration attribute to be treated differently from all other attributes. Note that configuration mutation requires `ADMIN` permissions.
Would it be ok if we added a `FORCE` flag to https://github.com/infinispan/infinispan/blob/b423976813c2b26dfe3d7f322b06c2407055b409/commons/all/src/main/java/org/infinispan/commons/api/CacheContainerAdmin.java#L37
Reassignment of an existing alias would require the `FORCE` flag to be present.

**Comment by karesti** [comment]
@tristantarrant small message looks good to me

**Pull request merged**
