### PR TITLE
ISPN-11849 ParamKeyValueFilterConverterFactory missing from Server Extensions

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-11837
https://issues.redhat.com/browse/ISPN-11849

### CODE REVIEW

**Comment by wburns** [comment]
Looks like there are some related test failures now https://ci.infinispan.org/job/Infinispan/job/PR-8324/4/#showFailuresLink

**Comment by wburns** [comment]
Unfortunately I am not familiar with the stuff in here, but otherwise appears okay to me.

**Comment by ryanemerson** [comment]
```
InfinispanRuleBasicTest.testSingleServer
org.infinispan.server.test.junit5.InfinispanServerExtensionContainerTest.testSingleServer
``

^ Two failures already exist on master.
https://ci.infinispan.org/job/Infinispan/job/master/2065/

**Comment by wburns** [comment]
Integrated into master, thanks @ryanemerson !

**Pull request merged**
