### PR TITLE
ISPN-10782 Log if the serverNG failed to start

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.jboss.org/browse/ISPN-10782

### CODE REVIEW

**Comment by tristantarrant** [comment]
Why not check for a FATAL log message. In any case we certainly don't want to add this as an INFO category.

**Comment by diegolovison** [comment]
@tristantarrant how about change https://github.com/infinispan/infinispan/pull/7449/files#diff-00a6752797eaa8e438ab77a723447b6dR118 to https://github.com/infinispan/infinispan/pull/7449/files#diff-c53a72e8a37159e3adb6a588c80f303cR115

We tail the log all the time. Looking for FATAL message with the only the Error message will need a surgical regex

**Comment by wburns** [comment]
This seems like a FATAL log message to me as well

**Comment by tristantarrant** [comment]
The server will output a FATAL log ONLY when it cannot start. All other messages will be ERROR or less. So it is safe to abort the RadarGun execution based on FATAL alone

**Comment by wburns** [comment]
Agreed, if you see any FATAL messages that should probably abort 👍

**Comment by diegolovison** [comment]
@tristantarrant @wburns how about https://github.com/infinispan/infinispan/pull/7449/commits/abeea118fc3ab2686c03f463f7d6aa9210ac0fac ?

**Comment by wburns** [comment]
Seems good to me 👍

**Comment by tristantarrant** [comment]
Yes.

**Comment by ryanemerson** [comment]
Thanks @diegolovison

**Pull request merged**
