### PR TITLE
ISPN-7912 Prevent RocksDBStore writes blocking on full expiry queue

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.jboss.org/browse/ISPN-7912

### CODE REVIEW

**Comment by diegolovison** [comment]
@ryanemerson I few questions:

- Dan wrote: `we changed the format of the expiration "table" to key = <expiration timestamp> + <key bytes>, value = <nothing>.` is it an improvement or what I did is wrong?
- What should I do with `@Deprecated` due that that config is not in use?

Thanks

**Comment by danberindei** [comment]
@diegolovison Yes, my expiration DB format is an improvement suggestion over Ryan's suggestion.

Currently updating the expiration info for one entry is very expensive: compared to updating the entry itself, which is a single RocksDB write, updating the expiration info needs to read the existing info for all the keys with the same expiration timestamp, unmarshalling that info, adding the new expiration info, serializing the whole thing, and writing it to RocksDB again.

We "cheat" by writing the expiration info to a queue and having a separate purge thread that reads from the expiration queue and writing the expiration info. In theory that helps when we write multiple cache entries with the same expiration timestamp in quick succession, and the purge thread can batch all their expiration info with a single RocksDB write. In practice, I believe we'd need to reduce the resolution of the expiration timestamps or we won't see almost any batches.

The problem with the purge thread is that it's just one thread. Like I said, updating the expiration info is slower than a regular write, and when there are lots of threads writing to the cache the purge thread can't keep up.

Ryan's suggestion was to help the purger thread by writing the expiration info from the main write thread, but only when the expiration queue is full. That keeps the write latency low when there are few writers and degrades gracefully when there are many writers.

My suggestion was to include the cache key in the expiration info key (which is currently just the expiration timestamp). That makes every key in the expiration DB unique, meaning we can do a blind write instead of first reading the existing expiration info, making the expiration info update cheaper. Potentially that would make the expiration info update cheap enough that we can do it directly from the writer thread, without an expiration queue and purge thread.

Your change removes the expiration queue but doesn't change how the expiration info is stored. So writes are slower than with Ryan's suggestion, because they work as if the queue was full all the time, and they're also slower than with my suggestion, because you still have the expiration DB read.

WRT deprecated options, we would normally keep deprecated options until at least version 11.0.

**Comment by ryanemerson** [comment]
> My suggestion was to include the cache key in the expiration info key (which is currently just the expiration timestamp). That makes every key in the expiration DB unique, meaning we can do a blind write instead of first reading the existing expiration info, making the expiration info update cheaper. Potentially that would make the expiration info update cheap enough that we can do it directly from the writer thread, without an expiration queue and purge thread.

I like the sound of this, but obviously we will need make this is properly benchmarked before being merged. Another consideration (IMO not a blocker) is that it will change the stored format of the expriry db, so in the upgrade notes we will have to make it clear that when upgrading from `10.0` to `10.1` that the expiry db must be removed before cache startup.

**Comment by diegolovison** [comment]
@danberindei @ryanemerson can we configure the `expiredDb` to use https://github.com/facebook/rocksdb/wiki/Block-Cache ?

**Comment by diegolovison** [comment]
Also, do you have a perf scenario + cache configuration to run?
Find out the expiration time when 20000 keys will expire.
Configure the expiration time based on the scenario above.
Run a perf tests with 40000 keys.. In this case, we will have lower writes because `expiryEntryQueue` will block, right ?

**Comment by danberindei** [comment]
> @danberindei @ryanemerson can we configure the `expiredDb` to use https://github.com/facebook/rocksdb/wiki/Block-Cache ?

Isn't the cache enabled by default? I'm not at all familiar with RocksDB and its performance tuning.

I might be wrong and the extra read is irrelevant. But my thinking is either we have a collision and we have to do extra unmarshalling + marshalling to store 2 keys in the same expiration bucket, or we don't have a collision and the read is wasted.

> Also, do you have a perf scenario + cache configuration to run?

I don't know how the queue got full when the issue was reported.

My first thought is to generate at least 20k unique keys and have 1 thread write to random keys as fast as it can, then add 1 more stressor thread and see if we get a better total throughput. The default expiration queue size is 10k, so 20k unique keys should be enough to fill the queue.

You'd also need different strategies for generating lifespans. I think the best strategy for the current code is to use a constant lifespan, so only entries that are one after the other may share an expiration bucket, and it would be a nice access pattern for the RocksDB cache. (I thought we drain the expiration queue into a map and we write entries with the same timestamp in one batch, but looking again at the code we don't, so without the block-cache it wouldn't matter.)

An interesting case for the current code (and with your changes too) would be to set the same expiration timestamp for all entries, with `lifespan = <expiration timestamp> - <current timestamp>`. It might be really bad for the current code because the `ExpiryBucket` will get very large and needs lots of marshalling/unmarshalling, but it might also be good because that entry is always going to be in RocksDB's cache.

**Comment by diegolovison** [comment]
When we have the following running on infinispan/master:
```java
      cacheManager.defineConfiguration("weather", new ConfigurationBuilder()
         .persistence()
            .addStore(RocksDBStoreConfigurationBuilder.class)
            .location("target/data")
            .expiredLocation("target/expired")
         .expiration().lifespan(5, TimeUnit.SECONDS)
         .build());
      cache = cacheManager.getCache("weather");

      int max = 10001;
      for (int i=0; i<max; i++) {
         cache.put(UUID.randomUUID().toString(), UUID.randomUUID().toString());
      }
```
The test never ends. The max could be the following but not 10001

- 9999
- 10000

**Comment by diegolovison** [comment]
How about if we could have both of the world: When the queue is full write directly to rocksDB ?

**Comment by danberindei** [comment]
> 
> The test took 60478ms. The max could be the following but not 10001

On which branch?
Why not 10001?
Or why not 20k? The default queue size being 10k, it's very likely to get full with only 10k insertions.

> The ms values are from my local laptop not running in the perf lab. It just "show the problem".

I don't see any problem, those 20ms could very well be random noise.

>     1. How about if we could have both of the world: When the queue is full write directly to rocksDB ?

That was Ryan's initial suggestion in the JIRA :)

>     2. The problem is that I am not able to run a perf test in master because 9999 is a lower value to measure a put operation.

Not sure what you mean here, but we should definitely not test with only 9999 keys. If we do test with ~10k put operations, we should lower the expiration queue size to maybe 1k so the test has a chance to fill the queue.

**Comment by diegolovison** [comment]
I would like to test when we have more than 10.000, how many time the client will be blocked. In this case, it is 60000ms.

> Isn't the cache enabled by default? I'm not at all familiar with RocksDB and its performance tuning.

I am waiting for https://github.com/infinispan/infinispan/pull/7574 to have concrete numbers.

**Comment by danberindei** [comment]
> I would like to test when we have more than 10.000, how many time the client will be blocked. In this case, it is 60000ms.

I believe every write blocks for a while, because this call is synchronous:

```
                    db.put(handle, marshalledKey, marshalledValue);
```

> I am waiting for #7574 to have concrete numbers.

I already commented on #7574, but I don't think it's ok to add a generic configuration option unless you're also exposing the statistics in a store-agnostic way, otherwise you would have a documented config option but only an undocumented way to obtain the statistics.

I have never tried it, but I think/hope it's relatively easy to extend `RocksDBStore` and `RocksDBStoreConfiguration[Builder]` to add create a store with statistics enabled just for your test.

**Comment by diegolovison** [comment]
> I would like to test when we have more than 10.000, how many time the client will be blocked. In this case, it is 60000ms.

@danberindei I mean, running the code from master. The entry 10.001 will be blocked for about 60.000ms.

In this PR, yes. Every write blocks for a while.

**Comment by danberindei** [comment]
> > I would like to test when we have more than 10.000, how many time the client will be blocked. In this case, it is 60000ms.
> 
> @danberindei I mean, running the code from master. The entry 10.001 will be blocked for about 60.000ms.
> 

My bad, I've been misreading the JIRA description (and the code). I got this idea that there is a special thread dedicated to writing the expiration info, and writes only block when that thread can't keep up with all the writer threads that add elements to the expiration queue.

Instead on master we reuse the expiration purge thread that wakes every 60s by default (`<expiration interval="60000"/>`) to delete expired entries from the stores. Since the thread only wakes up every 60s, there's nobody reading from the expiration queue, and that's why the 10k+1 write takes so long.

If we want to keep the expiration queue, we really have to fix this. 

IMO we can't allocate a thread to always read from the expiration queue, because we'd have one thread for each store (and we can't take over a thread from `ctx.getExecutor()` because there may be more stores than threads in that executor).

Instead we'd have to submit expiration write tasks to `ctx.getExecutor()`, but only if there isn't already an active task writing expiration info. We can't submit a task for each expiration info we add to the queue, because the executor might have a much smaller queue, but the deciding when to submit a task so that it processes all the items in the queue is going to be a little tricky.

For performance testing, I suggest changing the expiration wakeup interval in master to 10ms so we can pretend we got the the queue handling right.

**Comment by diegolovison** [comment]
> Potentially that would make the expiration info update cheap enough that we can do it directly from the writer thread, without an expiration queue and purge thread.

If we decide to remove the purge thread a do it directly in writer thread. Is it means that we during a put operation we should read all keys from the database and remove what was expired? I didn't get this point.

Thanks for all details and explanation it pretty cool!!!!!!

**Comment by diegolovison** [comment]
Move to https://github.com/infinispan/infinispan/pull/7605 It reflects the JIRA and the change

**Pull request closed without merging**
