### PR TITLE
ISPN-11427 RestMetricsResource#testMicroprofileMetricsMetadata can ti…

### PR DESCRIPTION
**Pull request by wburns**
…meout

https://issues.redhat.com/browse/ISPN-11427

Metrics are really slow with a lot, thus it is the first run test in the suite.

### CODE REVIEW

**Comment by anistor** [comment]
CI has some strange failures, but I did not get those failures locally. Merged. Thanks @wburns !
Should I let the jira still open as this does not really fix the underlying issue ?

**Comment by wburns** [comment]
Fine by me. However we want to proceed.

**Comment by anistor** [comment]
I've backported to 10.1.x also

**Comment by anistor** [comment]
@wburns Actually, I think I'll just close that jira as I'm satisfied with current results. This inefficiency in JsonMetadataExporter should never happen in real life.

**Pull request merged**
