### PR TITLE
ISPN-5433 Move jcache annotation code to jcache-commons so that it can be shared between the various implementations

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5433

### CODE REVIEW

**Comment by tristantarrant** [comment]
@mcimbora please look at this

**Comment by mcimbora** [comment]
@tristantarrant Looks good to me.

**Comment by galderz** [comment]
Sorry for delay @tristantarrant but needs rebasing

**Comment by tristantarrant** [comment]
Rebased

**Comment by wburns** [comment]
Seems there are 4 cdi jcache failures, are they related?
http://ci.infinispan.org/viewLog.html?buildId=27444&buildTypeId=bt9&guest=1

**Comment by mcimbora** [comment]
@tristantarrant Implemented some improvements to current tests (waiting for cluster formation, not starting servers after each test, fixed annotation tests) on the top of this branch - available at https://github.com/mcimbora/infinispan/commit/0ad5dec97deba21968568858cc8b1c79db1d19c1. Shall I create a new PR for those changes or will you incorporate them as a part of this one?

**Comment by galderz** [comment]
@mcimbora Wait for this PR to be integrated. @tristantarrant those CDI JCache errors are still there.

**Comment by galderz** [comment]
Closing, @tristantarrant reopen it when this is ready.

**Pull request closed without merging**
