### PR TITLE
[12.0] ISPN-12774 Credential store support example for datasource is incomplete

### PR DESCRIPTION
**Pull request by gustavolira**
https://issues.redhat.com/browse/ISPN-12774

### CODE REVIEW

**Comment by tristantarrant** [comment]
Open this for master please

**Comment by gustavolira** [comment]
> Open this for master please

@tristantarrant It's already merged on master #9084

**Comment by tristantarrant** [comment]
The backport is unnecessary

**Comment by oraNod** [comment]
@gustavolira Closing this after some discussion. 12.0 is not relevant to downstream.

**Pull request closed without merging**
