### PR TITLE
ISPN-14794 Create locked InfinispanLock

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.redhat.com/browse/ISPN-14794

### CODE REVIEW

**Comment by wburns** [comment]
Do you think you could run a benchmark to see if there is any appreciable difference in performance? I normally use a modified version of https://github.com/infinispan/infinispan-benchmarks/tree/main/getputremovetest

**Comment by pruivo** [comment]
Run the benchmark locally, using a local cache. Default options.
CPU: AMD Ryzen 5 5600X 6-Core Processor

```
# JMH version: 1.35
# VM version: JDK 17.0.6, OpenJDK 64-Bit Server VM, 17.0.6+10
# VM invoker: /home/pedro/.opt/java/jdk-17.0.6+10/bin/java
# VM options: -Xmx10G -Xms10G -XX:+HeapDumpOnOutOfMemoryError -Xss512k


== MAIN BRANCH ==
Benchmark                            (insertEntries)  (nodes)  (useStrings)   Mode  Cnt        Score         Error  Units
JMHBenchmarks.infinispanPutIsolated            false        1          true  thrpt    5  7324116.398 ± 1287206.080  ops/s
JMHBenchmarks.infinispanPutIsolated            false        1         false  thrpt    5  6957204.646 ±  886157.274  ops/s

== NEW LOCK BRANCH ==
Benchmark                            (insertEntries)  (nodes)  (useStrings)   Mode  Cnt        Score        Error  Units
JMHBenchmarks.infinispanPutIsolated            false        1          true  thrpt    5  8242044.932 ± 588938.746  ops/s
JMHBenchmarks.infinispanPutIsolated            false        1         false  thrpt    5  7992423.895 ±  99888.069  ops/s
```

**Comment by wburns** [comment]
I was hoping for an even more streamlined uncontended lock, but this is a good step as it saves about 1 microsecond per operation.

**Comment by wburns** [comment]
Integrated into main, thanks @pruivo !

**Pull request merged**
