### PR TITLE
ISPN-15744 Remove metric data from the overview report

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-15744

The new report looks like:
``` json
{
    "version": "1.0.0",
    "product-version": "15.0.0-SNAPSHOT",
    "node-id": "53722a5e-705f-4240-a0d1-0e21764fb8ee",
    "coordinator-id": "53722a5e-705f-4240-a0d1-0e21764fb8ee",
    "cluster-size": 2,
    "sites": 0,
    "relay-node": false,
    "cache-cardinalities": [
        "K",
        "K",
        "K"
    ],
    "cache-features": {
        "no-features": 3
    },
    "cache-stores": [],
    "proto-schemas": 0,
    "used-encodings": [
        "application/octet-stream",
        "text/plain"
    ],
    "clients": {
        "Memcached": {
            "protocol-versions": [
                "MCTXT"
            ]
        },
        "SinglePort": {
            "protocol-versions": [
                "HOTROD/4.0"
            ]
        }
    },
    "security": {
        "security-realms": {
            "default": {
                "server-ssl": false,
                "client-ssl": false
            }
        },
        "tls-endpoints": []
    }
}
```

### CODE REVIEW

**Comment by wburns** [comment]
Is this correct?

```
    "memory": {
        "available": "MEGA",
        "max": "GIGA",
        "total": "MEGA",
        "used": "MEGA"
    },
```
Do we not want to put the actual number any longer?

**Comment by fax4ever** [comment]
> Is this correct?
> 
> ```
>     "memory": {
>         "available": "MEGA",
>         "max": "GIGA",
>         "total": "MEGA",
>         "used": "MEGA"
>     },
> ```
> 
> Do we not want to put the actual number any longer?

Hi @wburns. Last week we had a meeting to address the BU changes to this report. IIUC @tristantarrant suggested keeping the memory metrics, but keeping the order of magnitude of the values.

**Comment by ryanemerson** [comment]
@fax4ever Should we be masking the following fields as suggested by @pruivo on Zulip?

- cluster name
- node names (replaced by number of nodes)
- site names.

**Comment by fax4ever** [comment]
> @fax4ever Should we be masking the following fields as suggested by @pruivo on Zulip?
> 
> * cluster name
> * node names (replaced by number of nodes)
> * site names.

Hi @ryanemerson, sorry I missed it on Zulip. :)
What would be algorithm to apply to masking (cluster name, node names and site names)?
Could I have an instance of application, please?

**Comment by fax4ever** [comment]
> I don't think I can do an actual review on this, but LGTM 🚢

Thank you for the feedback Ben!

**Comment by wburns** [comment]
> ```
> "memory": {
>     "available": "MEGA",
>     "max": "GIGA",
>     "total": "MEGA",
>     "used": "MEGA"
> },
> ```
> 
> Is there any value in this data? What are we going to do with the information once we find out half of the servers use `MEGA` amounts of memory and the second half `GIGAs`? We don't known whether that's 1GB or 990GB. Isn't it enough to have JVM memory settings from JVM report? Btw. given the report is sent every 24h it's possible it'll be sent right after the caches have been flushed should any users flush the caches on daily bases, making the data somewhat malformed.
> 
> On a bit different topic, is there a reason why the report doesn't contain Infnispan version?

Exactly what I was thinking regarding the memory usage.. it seems pretty useless to me.

**Comment by kittylyst** [comment]
FWIW, I don't think that sending the actual size (rather than the order-of-magnitude) is actually a problem.

However, there are problems here - and they are two-fold (or maybe 3-fold):

1. The report is generated at process start, and then every 24 hours thereafter. So the initial report is generated *before* the cache has filled - so we won't get accurate sizing until the process has been alive for 24 hours
2. The Insights data isn't really set up for this type of data - process metrics are much better handled as time-series

**Comment by fax4ever** [comment]
@wburns @ryanemerson @Crumby @kittylyst @tristantarrant 
Thanks for the reviews.
I updated the contribution.
Let me know if the report is fine for you. Thanks

**Review by ryanemerson — APPROVED** [review]

**Comment by fax4ever** [comment]
Thanks @ryanemerson

**Comment by fax4ever** [comment]
Thanks @tristantarrant

**Pull request merged**
