### PR TITLE
ISPN-4322 AS Remote Client Module Integration Tests module fails with IBM JDK. Created unified solution

### PR DESCRIPTION
**Pull request by vchepeli**

### CODE REVIEW

**Comment by danberindei** [comment]
@vchepeli There are quite a few new test failures, I'm not sure why. 

Also, the comment on the first commit seems wrong, as it just tells the failsafe plugin not to fail the build if there are no integration tests.

**Comment by vchepeli** [comment]
@danberindei yep I saw but I do not think they are related to this PR. It looks strange for me too. Yep I added property not to fail build if no tests were running e.g. no unstable tests found because it starts H2 database and after mvn failure does not stop it. Thats why I added this property to the main failsafe plugin

**Comment by danberindei** [comment]
@vchepeli Yeah, I agree that the test failures don't appear to be related.

I meant "ISPN-4322 when skipTests is defined do not prepare test configuration" doesn't sound accurate.

**Comment by vchepeli** [comment]
> @vchepeli Yeah, I agree that the test failures don't appear to be related.
> 
> About the commit comment, I meant "ISPN-4322 when skipTests is defined do not prepare test configuration" doesn't sound accurate.

Yep @danberindei you are right I was thinking about commit message and nothing came into mind. May you advice me how to change it?

**Comment by galderz** [comment]
Integrated

**Pull request closed without merging**
