### PR TITLE
ISPN-3824 Upgrade do Narayana 5.0.4

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-3824

### CODE REVIEW

**Comment by Sanne** [comment]
should we bite the bullet and jump to 5.0.4.Final ?

**Comment by galderz** [comment]
WF 8.x uses Narayana, 5.0.0, so it'd make sense to do so IMO...

**Comment by Sanne** [comment]
@tristantarrant not finding the upgrade to 5 in this branch. Forgot to push -force the update?

**Comment by tristantarrant** [comment]
Silly me, I renamed the branch. Closing this.

**Pull request closed without merging**
