### PR TITLE
ISPN-5855 RemoteContinuousQueryTest fails consistently

### PR DESCRIPTION
**Pull request by wburns**
* Make sure expiration checks pay attention to equality

https://issues.jboss.org/browse/ISPN-5855

### CODE REVIEW

**Comment by danberindei** [comment]
@wburns Perhaps we should have a test in core for this?

**Comment by anistor** [comment]
This needs backporting to 8.0.x too

**Comment by anistor** [comment]
I see plenty of unused imports in ExpirationManagerImpl.

**Comment by wburns** [comment]
@danberindei The issue cannot be in core, unless we had a custom data container equivalence with objects that don't implement equality properly.  We would have to make a very contrived test that is quite a bit confusing just to test it.

@anistor The other imports were already there, I guess I can fix it as well.  Also I was thinking when whomever integrated they would cherry-pick into 8.0.x since it should apply instantly and then I don't have to update stuff twice for review comments

**Comment by danberindei** [comment]
@wburns There are also some `ClassCastException`s in the integration tests: 
http://ci.infinispan.org/viewLog.html?buildId=30924&buildTypeId=bt9&guest=1

**Comment by wburns** [comment]
@danberindei Sounds like a different issue.

**Comment by wburns** [comment]
@danberindei Interestingly the other tests seemed to have failed on another PR as well: http://ci.infinispan.org/project.html?projectId=Infinispan&testNameId=623317564722301945&tab=testDetails  I am thinking we should log another PR for that one as this change wouldn't cause a CCE

**Comment by anistor** [comment]
@wburns @danberindei I started to investigate those. They are not related. This PR LGTM.

**Comment by anistor** [comment]
Integrated in master and 8.0.x. Thanks @wburns!

**Pull request closed without merging**
