### PR TITLE
ISPN-13809 Test indexed property name change

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-13809

basically cannot be reproduced, since it was solved by https://github.com/infinispan/infinispan/pull/10038.
If we want, we can merge this new test.

### CODE REVIEW

**Review by wburns — APPROVED** [review]
LGTM

**Comment by fax4ever** [comment]
Thanks @wburns!

**Comment by wburns** [comment]
Integrated into main, thanks @fax4ever !

**Comment by fax4ever** [comment]
Thanks Will!

**Pull request merged**
