### PR TITLE
ISPN-8001 HotRodCustomMarshallerIteratorIT fails randomly

### PR DESCRIPTION
**Pull request by anistor**
Fixing this was not easy... the principle of operation is clearly explained here: 

https://www.youtube.com/watch?v=dg5xeesapQQ

https://issues.jboss.org/browse/ISPN-8001

### CODE REVIEW

**Comment by anistor** [comment]
It does not fail on 9.0.x branch (https://github.com/infinispan/infinispan/pull/5607) so I guess there's something about encoding that affects it.

**Comment by anistor** [comment]
It's weird that this not fails when I run it locally, but fails in CI.

**Comment by gustavonalle** [comment]
@anistor This happens a lot, CI is considerably slower than anything outside it. You mentioned encoding, so I'd expect it to always fail on master? Do you have the server error log?

**Comment by anistor** [comment]
no longs I'm afraid

**Comment by gustavonalle** [comment]
Checking the failure, should be the same cause as the PR for the 9.1 branch

**Comment by gustavonalle** [comment]
I can't reproduce the failure locally

**Comment by gustavonalle** [comment]
Actually I can!

```
cd server/integration/testsuite
mvn verify -Dit.test=RemoteQueryCompatModeIT,*CustomMarshaller*IT -s ../../../maven-settings.xml
```

**Comment by gustavonalle** [comment]
@anistor So the issue is probably ```RemoteQueryCompatModeIT``` register a marshaller, and  ```HotRodCustomMarshallerIteratorIT``` fails when trying to register another one.

**Comment by gustavonalle** [comment]
@anistor  So https://github.com/infinispan/infinispan/pull/5615 is probably fixing it, if you extend it to also undeploy for the *CustomMarshaller*IT classes

**Comment by anistor** [comment]
No failures. This is too good to be true. I'll run the build again.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
