### PR TITLE
ISPN-13421 Address doc review comments

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-13421

### CODE REVIEW

**Review by oraNod — APPROVED** [review]
LGTM thanks @danberindei

**Comment by oraNod** [comment]
@danberindei Shall I go ahead and merge this or would you like more approvals?

**Comment by danberindei** [comment]
Go ahead and push the button @oraNod

**Comment by oraNod** [comment]
thanks @danberindei

**Pull request merged**
