### PR TITLE
ISPN-10399 Add JGroups native S3_PING to feature-packs

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-10399

### CODE REVIEW

**Comment by ryanemerson** [comment]
@tristantarrant All the transitive dependencies should be in place for runtime execution, not sure how to actually test this though.

**Comment by tristantarrant** [comment]
@ryanemerson you have not added an optional dependency in modules/system/add-ons/ispn/org/jgroups/{slot}/module.xml

**Comment by ryanemerson** [comment]
:see_no_evil: that's pretty important! Updated.

**Comment by tristantarrant** [comment]
I've made some changes and verified against a real S3 bucket that it works.

**Comment by pruivo** [comment]
are we supposed to ship the AWS jars?
```
[pedro@pedro-laptop-3 distribution]$ unzip -l infinispan-wildfly-modules-10.0.0-SNAPSHOT.zip | grep aws
        0  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/com/amazon/aws/
        0  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/com/amazon/aws/s3/
        0  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/com/amazon/aws/s3/ispn-10.0/
        0  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/org/jgroups/aws/
        0  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/org/jgroups/aws/s3/
        0  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/org/jgroups/aws/s3/ispn-10.0/
    26879  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/com/amazon/aws/s3/ispn-10.0/jmespath-java-1.11.368.jar
   866196  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/com/amazon/aws/s3/ispn-10.0/aws-java-sdk-core-1.11.368.jar
   902512  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/com/amazon/aws/s3/ispn-10.0/aws-java-sdk-s3-1.11.368.jar
     1107  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/com/amazon/aws/s3/ispn-10.0/module.xml
   565410  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/com/amazon/aws/s3/ispn-10.0/ion-java-1.0.2.jar
   404152  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/com/amazon/aws/s3/ispn-10.0/aws-java-sdk-kms-1.11.368.jar
      506  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/org/jgroups/aws/s3/ispn-10.0/module.xml
    15152  2019-07-11 18:53   infinispan-wildfly-modules-10.0.0-SNAPSHOT/modules/system/add-ons/ispn/org/jgroups/aws/s3/ispn-10.0/native-s3-ping-0.9.5.Final.jar
```

**Comment by ryanemerson** [comment]
Thanks for the additions @tristantarrant.

@pruivo They are required dependencies of native-s3-ping, so not sure how we can omit them in a way that does not require the user to perform additional tasks to use the library. 

One option could be to provide the aws modules with the modules.xml commented out and the artifacts removed. The user then needs to download the artifacts and manually copy the jars across. 

I understand why we don't want to provide the jars downstream, but not sure additional steps should be required upstream ... but I know that will add additional steps to the prod process. WDYT?

**Comment by pruivo** [comment]
@ryanemerson no worries. the production process can handle it.

**Comment by pruivo** [comment]
integrated! thanks @ryanemerson !

**Pull request merged**
