### PR TITLE
[13.0] ISPN-14143 + ISPN-14144 + ISPN-14131 Task authorization

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14143
https://issues.redhat.com/browse/ISPN-14144
https://issues.redhat.com/browse/ISPN-14131

### CODE REVIEW

**Comment by ryanemerson** [comment]
There's a lot of security related test failures on the 3 runs.

**Review by wburns — COMMENTED** [review]
Changes in general seem fine to me. Unfortunately, there are a lot of test failures.

**Comment by tristantarrant** [comment]
Fixed all related issues

**Comment by wburns** [comment]
Integrated into 13.0.x, thanks @tristantarrant !

**Pull request merged**
