### PR TITLE
ISPN-12776 Upgrade to Hibernate Search 6.0.2.Final

### PR DESCRIPTION
**Pull request by yrodiere**
https://issues.redhat.com/browse/ISPN-12776

This may also fix https://issues.redhat.com/browse/ISPN-12694

CC @gustavonalle

### CODE REVIEW

**Comment by tristantarrant** [comment]
Can lucene also be upgraded ?

**Comment by yrodiere** [comment]
@tristantarrant Any particular reason to want that? There are no new versions in Lucene's 8.7 branch at the moment.

I don't intend to upgrade to Lucene 8.8 in the 6.0 branch of Hibernate Search, because I don't want to take unnecessary risks with backwards compatibility, especially considering users are able to use exotic Lucene APIs that we (in Search) don't use. Hibernate Search 6.1 (not yet released) will upgrade to Lucene 8.8, but not 6.0.

But those concerns are not relevant for Infinispan, at least in the remove case. You should be able to upgrade to Lucene 8.8 in Infinispan without any problem. This is the upgrade in Search 6.1, zero change required: https://github.com/hibernate/hibernate-search/pull/2473/files

**Comment by gustavonalle** [comment]
Infinispan doesn't use Lucene anymore by itself, only through Hibernate Search, so there's no need to have a different version IMO

**Comment by yrodiere** [comment]
@tristantarrant @gustavonalle I think the test failures are unrelated? Can we merge this?

**Comment by gustavonalle** [comment]
Merged, thanks @yrodiere

**Comment by yrodiere** [comment]
Thanks!

**Pull request merged**
