### PR TITLE
ISPN-5192 infinispan-remote uber jar contains 2x versions of shaded javassist packages

### PR DESCRIPTION
**Pull request by anistor**
jira: https://issues.jboss.org/browse/ISPN-5192

### CODE REVIEW

**Comment by tristantarrant** [comment]
@anistor, now we have javassist/protostream and javassist/infinispan, which is still wrong.

**Comment by anistor** [comment]
protostream shades javassist and might use a different javassist version at some point so infinispan cannot rely on the javassist coming with protostream. I'm not even sure the versions are the same today.

**Comment by tristantarrant** [comment]
Remote only shades javassist because it was a dependency of protostream. When protostream started shading it itself, the need for this to be included by infinispan-remote has gone away

**Comment by anistor** [comment]
I thought I marked that optional in protostream... Ok, will exclude it then.

**Comment by anistor** [comment]
Updated.

**Comment by galderz** [comment]
Revert the cosmetic changes please :)

**Comment by anistor** [comment]
oh noes, intellij does not let me do that! :)

**Comment by anistor** [comment]
updated.

**Comment by anistor** [comment]
@galderz @tristantarrant CI says all is well. Could you integrate this please?

**Comment by galderz** [comment]
Integrated

**Pull request closed without merging**
