### PR TITLE
ISPN-5395 Upgrade the server base to WildFly 8.2

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5395

### CODE REVIEW

**Comment by galderz** [comment]
Hmmmm, I guess as long as we're only upgrading the server base we're fine, because for CDI we know there are some issues that require WF 9, see #3096

**Comment by galderz** [comment]
There are 43 new failures btw

**Comment by tristantarrant** [comment]
Changed. It should work now

**Comment by galderz** [comment]
Hmmmm... even more failures now:

    Tests failed: 324 (321 new), passed: 12010...

**Comment by tristantarrant** [comment]
All those failures were caused by the JBoss Logging 3.2 upgrade which was reverted this morning (Caused by: java.lang.NoSuchMethodError: org.infinispan.util.logging.Log.tracef(Ljava/lang/String;I)V). Try again

**Comment by galderz** [comment]
Ah ok :)

**Comment by galderz** [comment]
Integrated

**Pull request closed without merging**
