### PR TITLE
ISPN-7684 Generate keystore automatically

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/ISPN-7684

### CODE REVIEW

**Comment by danberindei** [comment]
@slaskawi Will any test use this?

**Comment by slaskawi** [comment]
@danberindei No, we don't want to use this functionality in the testsuite.

**Comment by galderz** [comment]
That's a nice little helper at least with getting started with Java clients. Not very useful for Node.js clients since they self-signed certificates are refused. @tristantarrant Any comments to add?

**Comment by ryanemerson** [comment]
Integrated, thanks @slaskawi

**Pull request merged**
