### PR TITLE
ISPN-12946 CloudEventsIntegrationIT fails because of rate limit

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-12946

Use Kafka image from quay.io

### CODE REVIEW

**Comment by pruivo** [comment]
didn't work:
`Caused by: java.lang.IllegalStateException: Failed to verify that image 'quay.io/confluentinc/cp-kafka:5.4.3' is a compatible substitute for 'confluentinc/cp-kafka'. This generally means that you are trying to use an image that Testcontainers has not been designed to use. If this is deliberate, and if you are confident that the image is compatible, you should declare compatibility in code using the `asCompatibleSubstituteFor` method. For example:`

**Comment by danberindei** [comment]
@pruivo I haven't considered the possibility, but it looks like the `quai.io/confluentinc/cp-kafka` does not exist :)

I pushed an update that uses the Strimzi test-container image and it works, but for whatever reason starting the container takes ages.

**Comment by pruivo** [comment]
well, somehow, I can find it
```
docker pull quay.io/confluentinc/cp-kafka:5.4.3
5.4.3: Pulling from confluentinc/cp-kafka
290431e50016: Pulling fs layer 
7ec8f1cbc52d: Download complete 
2e4268618b5d: Pulling fs layer 
708285f10926: Download complete 
95501030aa9b: Waiting 
a26f4effffdb: Waiting 
6aa5a7b6ed06: Waiting 
```
you have a mirror here: https://quay.io/repository/cloudservices/cp-kafka

**Comment by danberindei** [comment]
Updated to use the `quay.io/cloudservices/cp-kafka` mirror

**Comment by pruivo** [comment]
integrated! thanks @danberindei !

**Pull request merged**
