### PR TITLE
ISPN-11024 Unable to use binary memory eviction with protobuf

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-11024

### CODE REVIEW

**Comment by wburns** [comment]
Note that I cannot confirm it is completely working due to https://issues.redhat.com/browse/ISPN-11086. But the ClassCastException would be fixed.

**Comment by danberindei** [comment]
@wburns why do we need so many new tests? Based on the description I would have expected just one test in the core module, and none in the client.

**Comment by wburns** [comment]
The reason for all the tests is that query and alternative storage mechanisms just isn't tested well and I am tired of getting random issues that should be foreseeable.  Also just having the test in core won't work as the ProtobufValueWrapper only exists when using the query module.

**Comment by danberindei** [comment]
> The reason for all the tests is that query and alternative storage mechanisms just isn't tested well and I am tired of getting random issues that should be foreseeable. 

Fair enough, I should have remembered that `ProtobufWrapper` is only in remote-query, and enhancing the query tests with alternative storage is more than welcome.

But IMO eviction tests should live in core. `WrappedBytes` is conceptually a core SPI used by `remote-query`, so core should have tests to make sure that core features work well with custom implementations of `WrappedBytes`. The tests you've modified always set the eviction limit so that no entry is ever evicted, so you're basically running the no-eviction code 3 times.

**Comment by wburns** [comment]
Not true, there are other code paths that it hits when having eviction enabled, such as doing counts of the size of the object, which this is trying to test. And since each of these tests puts a different value into the cache it tests those. And this found the issue that I logged https://issues.redhat.com/browse/ISPN-11086

**Comment by danberindei** [comment]
> such as doing counts of the size of the object

Wouldn't a core test for the `WrappedBytes` SPI do that?

> each of these tests puts a different value into the cache

And how is eviction different for each value?

E.g. in your PR, `RemoteAlternativeStorageNonIndexedQueryDslConditionsTest` has 1456 tests. How much value are we adding with each new method we run with eviction enabled?

>  I logged https://issues.redhat.com/browse/ISPN-11086

I don't see any connection to eviction there, either.

**Comment by wburns** [comment]
> And how is eviction different for each value?

Memory is vastly different than size when it comes to the different types.

> I don't see any connection to eviction there, either.

It isn't directly related to eviction. I am saying the tests I added found this issue, which was showing they have value, since this failure is not found by others. This isn't just for eviction, but indexing and different types in general.

**Comment by wburns** [comment]
Also to note I removed some classes, so it isn't like all the new factory methods are brand new as some of these options were being tested before as well. I just added the eviction related ones.

**Comment by danberindei** [comment]
> Memory is vastly different than size when it comes to the different types.

Sure, but what's the effect on query?

I would expect those vast differences are already tested in the core test suite, and query would be able to ignore them.

> It isn't directly related to eviction. I am saying the tests I added found this issue, which was showing they have value, since this failure is not found by others. This isn't just for eviction, but indexing and different types in general.

What I'm trying to say is that different tests should test different things.

E.g. the name `ClientProtoStreamMarshallerTest` tells me it tests the protostream marshalling in the client, and there's no obvious connection between protostream marshalling and eviction to me.
The same with `RemoteAlternativeStorageNonIndexedQueryDslConditionsTest`, it's ostensibly a test of query with different storage types, what's the connection to eviction? You already have an `EvictionQueryTest`, no?
And why isn't the behaviour of different storage types + different kinds of eviction already tested in core, what's missing in core so that query has to test them?

**Comment by tristantarrant** [comment]
Closing for inactivity. Please reopen once ready.

**Pull request closed without merging**
