### PR TITLE
ISPN-12889 ClusteredLockTest.destroyLock random failures

### PR DESCRIPTION
**Pull request by wburns**
* Make sure to wait on unlocks to complete

https://issues.redhat.com/browse/ISPN-12889

### CODE REVIEW

**Comment by gustavonalle** [comment]
It seems you need to add some BlockHound rules to allow the test to block

**Comment by wburns** [comment]
Thanks, I will add this in a bit here.

**Comment by wburns** [comment]
Updated to add block hound exception.

**Comment by gustavonalle** [comment]
Merged, thanks!

**Pull request merged**
