### PR TITLE
ISPN-5255 Port Infinispan Lucene directory integration tests from Hibernate Search codebase

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-5255

### CODE REVIEW

**Comment by gustavonalle** [comment]
@Sanne please take a look. Tests are now running on MacOS X. I had to change the stack to TCP, meaning using ```user-provided-infinispan.xml``` on ```SearchNewEntityJmsMasterSlaveUsingInfinispanAs2ndCacheAndModulesIT```

**Comment by Sanne** [comment]
Marking for rebase as we need to adjust the version numbers after the other merges today. Feel free to ping me as soon as it's ready!

**Comment by gustavonalle** [comment]
Rebased

**Comment by Sanne** [comment]
I'm looking at them, trying to get the build to work here. Had some issues as I have a fresh install on my workstation.
It's running again now, I'll take a break and come back later to merge if it succeeded.

**Comment by Sanne** [comment]
merged!
Some more things are needed, but I'll create isolated issues.

**Pull request closed without merging**
