### PR TITLE
ISPN-13276 Improve XSite Rest Endpoint

### PR DESCRIPTION
**Pull request by pruivo**
* status now prints the nodes/caches that are online or offline and
  caches with mixed status

https://issues.redhat.com/browse/ISPN-13276

### CODE REVIEW

**Comment by karesti** [comment]
@pruivo docs ?

**Review by karesti — CHANGES_REQUESTED** [review]
I think the only thing missing might be the REST API docs updades ? seems like there is change, isn't it?

**Comment by pruivo** [comment]
done

**Comment by karesti** [comment]
@pruivo might be related ?
org.infinispan.xsite.offline.InvalidConfigurationOfflineTest.testTakeOffline([not-started-true, true, NOT_STARTED])
org.infinispan.xsite.offline.InvalidConfigurationOfflineTest.testTakeOffline([not-started-false, false, NOT_STARTED])

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
