### PR TITLE
[11.0] ISPN-12576 Filter authentication mechanism on the Elytron authenticator

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-12576

### CODE REVIEW

**Comment by karesti** [comment]
@tristantarrant testing with the js client

**Comment by karesti** [comment]
@tristantarrant seems like there are related tests on this one



org.infinispan.server.security.AuthenticationKerberosIT.testProtocol[(HTTP_11)]org.infinispan.server.security.AuthenticationKerberosIT.testProtocol[(HTTP_20)]org.infinispan.server.security.authentication.RestAuthentication.testRestReadWrite[(HTTP_11)]org.infinispan.server.security.authentication.RestAuthentication.testRestReadWrite[(HTTP_20)]org.infinispan.server.security.authorization.AuthorizationKerberosIT.testRestNonAdminsMustNotCreateCacheorg.infinispan.server.security.authorization.AuthorizationLDAPIT.testRestNonAdminsMustNotCreateCacheorg.infinispan.server.security.authorization.AuthorizationPropertiesIT.testRestNonAdminsMustNotCreateCache
  |

**Review by karesti — CHANGES_REQUESTED** [review]
some test failures seem related

**Comment by tristantarrant** [comment]
Should be fixed now

**Review by karesti — APPROVED** [review]

**Pull request merged**
