### PR TITLE
Kill JDBC binary/mixed stores

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-7123
https://issues.jboss.org/browse/ISPN-7124
https://issues.jboss.org/browse/ISPN-7325

### CODE REVIEW

**Comment by galderz** [comment]
> +1,251 −4,757  UnifiedSplit Review changes 

^ Woo hoo! These are the best PRs :)

**Comment by galderz** [comment]
Docu for migrator is missing but @ryanemerson will be sending a PR for that later on. Looks good otherwise :)

**Comment by galderz** [comment]
Needs rebase

**Comment by ryanemerson** [comment]
@galderz Rebased

**Comment by gustavonalle** [comment]
"From all the JDBC Stores, the Binary is my favourite, even when it's part of the Mixed"
Said nobody ever

**Pull request merged**
