### PR TITLE
[13.0] ISPN-13562 Log4J 2.15.0

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-13562

### CODE REVIEW

**Comment by pruivo** [comment]
@tristantarrant can you update this PR too? 
LDAP tests are failing with `ELY01125: Ldap-backed realm failed to obtain context`

**Comment by tristantarrant** [comment]
Repushed

**Comment by pruivo** [comment]
hmmm... tests are still failing. wondering if it is something else.

**Comment by tristantarrant** [comment]
Trying something

**Comment by tristantarrant** [comment]
Looks good now

**Comment by pruivo** [comment]
merged! thanks @tristantarrant

**Pull request merged**
