### PR TITLE
ISPN-12341 Add Memcached client test for third-party-server

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.redhat.com/browse/ISPN-12341

### CODE REVIEW

**Comment by tristantarrant** [comment]
I don't understand the purpose of this PR. It is not testing any of our code on the client side, and server-side memcached tests are already done elsewhere.

**Comment by diegolovison** [comment]
Hi Tristan,

The purpose of `third-party-server` is to add basic tests to try to identify classpath issues or missing configurations.

`third-party-server` can run tests in Wildfly ( enabled by default ) and other profiles ( currently, Tomcat )

**Comment by wburns** [comment]
What classpath issues are trying to find with this? I am also at a bit of a loss to the benefits of this PR.

**Comment by wburns** [comment]
Integrated into master, thanks @diegolovison !

**Pull request merged**
