### PR TITLE
ISPN-14187 SoftIndexFileStore not removing log files with expiration

### PR DESCRIPTION
**Pull request by wburns**
* Unset schedule flag when completing file - set from expiration
* Make sure nextExpirationTime is set properly if stats already exist

https://issues.redhat.com/browse/ISPN-14187

### CODE REVIEW

**Review by jabolina — APPROVED** [review]
LGTM overall, just small comments in tests. Gotta love these problems that need to change just a few lines.

**Comment by wburns** [comment]
Updated

**Comment by jabolina** [comment]
Replayed CI, just waiting now.

**Comment by jabolina** [comment]
Merged, thanks @wburns

**Pull request merged**
