### PR TITLE
ISPN-7116 Test methods that use a TestNg dataProvider are duplicated in

### PR DESCRIPTION
**Pull request by alanfx**
JUnit reports

https://issues.jboss.org/browse/ISPN-7116

* Disabled the XML report in the parent POM
* Changed the XML file prefix in PolarionJUnitXMLReporter from
"POLARION-" to "TEST-"

### CODE REVIEW

**Comment by alanfx** [comment]
@danberindei can you take a look at this? I figured out how to disable the creation of the Surefire XML results files, and the text summary results files can be disabled by adding `<useFile>false</useFile>` to the parent POM as well. Thanks

**Comment by danberindei** [comment]
@alanfx Looks like nobody uses the text reports, please disable them too.

**Comment by alanfx** [comment]
@danberindei updated!

**Comment by danberindei** [comment]
@alanfx replacing the Surefire XML report with yours seems to have impacted the number of tests in CI: 14945 (this PR) vs 17709 (master)

http://ci.infinispan.org/viewLog.html?buildId=49855
http://ci.infinispan.org/viewLog.html?buildId=48199

You can download a CSV of the test names as parsed by TeamCity from the tests tab and compare them to see which ones are missing, then compare the generated XML from your reporter and the default one.

Also, I like how the suite name is now the module name, but there are still > 2k tests with `<no suite>`. Maybe we can set a proper suite for those too?

**Comment by alanfx** [comment]
@danberindei ok, I got it figured out. Disabling the XML file in the parent/pom.xml was also preventing the XML file from being generated for modules that use JUnit. I had to enable the XML results file in those modules to fix the issue, and now the number of tests executed on this branch is higher due to the changes to show each of the test invocations for tests that use a data provider. Let me know what you think.

**Comment by alanfx** [comment]
@danberindei updated with the changes we discussed. Tests that are invoked multiple times will report a single `<testcase>` element if all invocations pass, or will report all failures for the test.

**Comment by danberindei** [comment]
Integrated, thanks Alan!

**Comment by alanfx** [comment]
@danberindei I don't see these changes in Infinispan master. Can you check again? Thanks

**Comment by danberindei** [comment]
Sorry @alanfx, I had pushed it to my fork by mistake... it's in now.

**Comment by alanfx** [comment]
No worries @danberindei, and thanks for sticking with me on this!

**Pull request closed without merging**
