### PR TITLE
ISPN-10431 REST client library

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-10431

this will be needed by the new CLI and I've refactored the server testsuite to use this.
I've decided to go with OkHttp 3.x because:
* OkHttp 4.x depends on Kotlin
* we cannot use the JDK HttpClient as it is only available since JDK 11
* AsyncHttpClient doesn't support HTTP/2 and is semi-abandoned
* Apache HC 4 doesn't suppport HTTP/2 either
* Apache HC 5 is still Beta

The backend can be replaced in the future (either Apache HC 5 when it becomes final or the JDK HttpClient when we baseline on JDK 11)

I've implemented support for Basic, Digest and Bearer authentication
I've left the Netty test client in the rest testsuite since it allows us to fine-tune some things like sending HTTP Upgrade headers even in plain text.

### CODE REVIEW

**Comment by gustavonalle** [comment]
LGTM, waiting for CI

**Comment by tristantarrant** [comment]
failures unrelated

**Comment by gustavonalle** [comment]
Conflicts

**Comment by tristantarrant** [comment]
Rebased

**Comment by tristantarrant** [comment]
@gustavonalle failures unrelated

**Comment by gustavonalle** [comment]
merged, thanks @tristantarrant !

**Pull request merged**
