### PR TITLE
ISPN-7670 Upgrade to Hibernate Search 5.8.0.Beta1

### PR DESCRIPTION
**Pull request by Sanne**
Upgrading Hibernate Search to the latest.

Headlines are here, essentially it now supports Elasticsearch 5 and the client is much improved:
 - http://in.relation.to/2017/04/15/HibernateSearchNowSpeakingEs5/

Relevant for Infinispan: several internal bugfixes, some small performance improvements and most notably we flipped the default value for this configuration property:
 - https://docs.jboss.org/hibernate/search/5.8/api/org/hibernate/search/cfg/Environment.html#INDEX_UNINVERTING_ALLOWED

This PR includes a "flip back" of the defaults for Infinispan, as I believe Infinispan Server is not ready to handle that yet.

 - https://issues.jboss.org/browse/ISPN-7670

### CODE REVIEW

**Comment by ryanemerson** [comment]
@Sanne It appears that some of the test failures are related to your changes

**Comment by Sanne** [comment]
Thanks, I'll check it again locally. Some of the failures reported by CI are likely related, however a couple of those are definitely not.

**Comment by Sanne** [comment]
I've updated the PR.
It's rebased on latest master, and now also includes:
 - https://issues.jboss.org/browse/ISPN-7742

**Comment by Sanne** [comment]
There's one more problem, I'll look at it soon.

**Comment by Sanne** [comment]
Fixed and rebased.

**Comment by anistor** [comment]
CI says there are test failures. I tried to have a look but Mr. Jenkins was very unkind today and hid those test reports somewhere.

**Comment by Sanne** [comment]
>CI says there are test failures.

Aren't there always? :)

> I tried to have a look but Mr. Jenkins was very unkind today and hid those test reports somewhere.

So what now? Do we have some way to recover them or get another build run? @slaskawi ?

**Comment by slaskawi** [comment]
Tests results are here: http://ec2-52-215-14-157.eu-west-1.compute.amazonaws.com/job/Infinispan/job/PR-5090/4/

For more details look into [Jenkins JIRA](https://issues.jenkins-ci.org/browse/JENKINS-43751) and your email box (I wrote about this on internal mailing list) :) Nobody reads emails these days...

**Comment by anistor** [comment]
I've read about the jenkins migration and blueocean's wrinkles, but I'm not subscribed to Jenkins jira and I'm not familiar with this workaround. Thanks!

**Comment by Sanne** [comment]
Thanks @slaskawi !

@anistor looks like those failures are unrelated: the module `server/integration/testsuite/` worked just fine when running the build locally (although it took ages).

I could reproduce the OSGi test, but it fails for me in master as well (w/o my changes).

**Comment by Sanne** [comment]
rebased and re-pushed, so to trigger a new CI build.

**Comment by anistor** [comment]
Integrated. Thanks @Sanne !

**Comment by Sanne** [comment]
thanks @anistor and @ryanemerson !

**Pull request merged**
