### PR TITLE
ISPN-5475 Narayana should use a volatile store for all tests

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-5475

### CODE REVIEW

**Comment by tristantarrant** [comment]
Didn't we already do this a while back. It seems to creep back in every now and then...

**Comment by tristantarrant** [comment]
@danberindei , no ObjectStore files archived, so I guess this is looking good

**Comment by danberindei** [comment]
@tristantarrant we did do something, but AFAICT it only worked for core.

**Comment by danberindei** [comment]
Ready for review, I removed the archive step.

**Comment by tristantarrant** [comment]
Merged thanks

**Pull request merged**
