### PR TITLE
ISPN-5055 Use Vault for HR security tests

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.jboss.org/browse/ISPN-5055

### CODE REVIEW

**Comment by tristantarrant** [comment]
Running with: mvn clean verify -pl server/integration/testsuite/ -Psuite.security.manual
I get the following failures:
Tests in error: 
  HotRodPlainAuthLocalIT.testAdmin » IllegalArgument Cannot find specified objec...
  HotRodPlainAuthLocalIT.testReaderWrite » IllegalArgument Cannot find specified...
  HotRodPlainAuthLocalIT.testWriterWriteRead » IllegalArgument Cannot find speci...
  HotRodPlainAuthLocalIT.testReader » IllegalArgument Cannot find specified obje...
  HotRodPlainAuthLocalIT.testWriter » IllegalArgument Cannot find specified obje...
  HotRodPlainAuthLocalIT.testSupervisor » IllegalArgument Cannot find specified ...
  HotRodDigestMd5AuthLocalIT.testAdmin » IllegalArgument Cannot find specified o...
  HotRodDigestMd5AuthLocalIT.testReaderWrite » IllegalArgument Cannot find speci...
  HotRodDigestMd5AuthLocalIT.testWriterWriteRead » IllegalArgument Cannot find s...
  HotRodDigestMd5AuthLocalIT.testReader » IllegalArgument Cannot find specified ...
  HotRodDigestMd5AuthLocalIT.testWriter » IllegalArgument Cannot find specified ...
  HotRodDigestMd5AuthLocalIT.testSupervisor » IllegalArgument Cannot find specif...

Tests run: 77, Failures: 0, Errors: 12, Skipped: 3

The failure is similar for all cases:

testSupervisor(org.infinispan.server.test.client.hotrod.security.HotRodDigestMd5AuthLocalIT)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.IllegalArgumentException: Cannot find specified object in InfinispanContext, type: org.infinispan.arquillian.core.RemoteInfinispanServer, qualifier: hotrodAuth
	at org.infinispan.arquillian.core.InfinispanTestEnricher.enrich(InfinispanTestEnricher.java:62)
	at org.jboss.arquillian.test.impl.TestInstanceEnricher.enrich(TestInstanceEnricher.java:52)
	at org.jboss.arquillian.container.test.impl.ClientTestInstanceEnricher.enrich(ClientTestInstanceEnricher.java:51)
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:142)
	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createBeforeContext(ContainerEventController.java:124)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:102)
	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:84)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:65)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:145)
	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:116)
	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.before(EventTestRunnerAdaptor.java:95)
	at org.jboss.arquillian.junit.Arquillian$5.evaluate(Arquillian.java:258)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:193)
	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:345)
	at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:49)
	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:207)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:155)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:141)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:114)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:86)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:134)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8189/vjuranek:ISPN-5055](http://ci.infinispan.org/viewLog.html?buildId=22551&buildTypeId=bt9&guest=1) for 5135955b271bf6beb7334cb11ea0c4b9fb5ef848
Tests: 11215, 1 failed (1 new), 23 ignored. Build time: 01:40:40

Failed tests detected
* (new) TestSuite: org.infinispan.interceptors.ConcurrentInterceptorVisibilityTest.testSizeVisibility

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8216/vjuranek:ISPN-5055](http://ci.infinispan.org/viewLog.html?buildId=22588&buildTypeId=bt9&guest=1) for 5135955b271bf6beb7334cb11ea0c4b9fb5ef848
Tests: 11216, 1 failed (0 new), 23 ignored. Build time: 01:41:20

Failed tests detected
* (since 05-Jan-2015) TestSuite: org.infinispan.interceptors.ConcurrentInterceptorVisibilityTest.testSizeVisibility

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8243/vjuranek:ISPN-5055](http://ci.infinispan.org/viewLog.html?buildId=22655&buildTypeId=bt9&guest=1) for 5135955b271bf6beb7334cb11ea0c4b9fb5ef848
Tests: 11217, 4 failed (4 new), 23 ignored. Build time: 02:11:01

Failed tests detected
* (new) TestSuite: org.infinispan.client.hotrod.query.MultiHotRodServerIspnDirReplQueryTest.testAttributeQuery


* (new) TestSuite: org.infinispan.client.hotrod.query.MultiHotRodServerIspnDirReplQueryTest.testEmbeddedAttributeQuery


* (new) TestSuite: org.infinispan.client.hotrod.query.MultiHotRodServerIspnDirReplQueryTest.testProjections


* (new) TestSuite: org.infinispan.xsite.statetransfer.failures.SiteProviderTopologyChangeTest.testXSiteSTDuringSiteMasterLeave



Error message is logged

Process exited with code 1

Build duration (secs) is too large: 7845

**Comment by vjuranek** [comment]
This is due to [ISPN-4990](https://issues.jboss.org/browse/ISPN-4990), these two tests need different profile, you can run these two with `mvn clean verify -pl server/integration/testsuite/ -Psuite.security -Dit.test=HotRodPlainAuthLocalIT,HotRodDigestMd5AuthLocalIT`

My original intention was include these two tests into default test suite once stable enough (which hopefully already are) and remaining tests run only on demand as these are quiet time expensive - therefore two different profiles. Will fix this (ISPN-4990) soon.

**Comment by vjuranek** [comment]
Consolidation of the security tests is done in PR #3199

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity Infinispan :: Pull requests monitor [Build 8270/vjuranek:ISPN-5055](http://ci.infinispan.org/viewLog.html?buildId=22714&buildTypeId=bt9&guest=1) for 5135955b271bf6beb7334cb11ea0c4b9fb5ef848
Tests: 11231, 0 failed (0 new), 23 ignored. Build time: 01:40:40

**Comment by tristantarrant** [comment]
Pulled, thanks

**Pull request closed without merging**
