### PR TITLE
ISPN-13732 Adding jdbc type BIT and TIME

### PR DESCRIPTION
**Pull request by varunshastry**
https://issues.redhat.com/browse/ISPN-13732

### CODE REVIEW

**Comment by wburns** [comment]
What database are you using @varunshastry ? DATE iirc had a different issue with a specific database provider I believe. Also we will need to add a test for these data types so we can verify they work across the various providers.

**Comment by varunshastry** [comment]
@wburns MySQL (8.0.25) is the database. The build has some failed tests https://ci.infinispan.org/job/Infinispan/job/PR-9916/2/ . How can I run these tests locally? I'm getting the following error in "Infinispan Commons" maven project on running "mvn verify" :

[ERROR] Failed to execute goal org.infinispan.maven-plugins:proto-schema-compatibility:1.0.2.Final:proto-schema-compatibility-check (default) on project infinispan-commons: Backwards compatibility check failed with: [protolock]: lstat <...>/infinispan-src/commons/all/target/classes/proto: no such file or directory

**Comment by wburns** [comment]
That link doesn't have any failures related to your changes. I wouldn't expect your PR to break anything as the SQL Store tests aren't using the datatypes you added in any tests currently.

**Comment by varunshastry** [comment]
@wburns  Add a junit test for AbstractSchemaJdbcStore

**Comment by varunshastry** [comment]
@wburns I'm not able to run the tests locally. Currently, the build has a test failure https://ci.infinispan.org/job/Infinispan/job/PR-9916/6/testReport/junit/org.infinispan.server.persistence/JdbcStringBasedCacheStorePassivation/testFailoverWithPassivation_mysql_

**Comment by tristantarrant** [comment]
This needs rebasing. Please reopen a new PR.

**Pull request closed without merging**
