### PR TITLE
ISPN-10975 Transactional cache will slow down the expiration reaper

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-10975

### CODE REVIEW

**Comment by danberindei** [comment]
Compilation failure @wburns

**Comment by wburns** [comment]
Fixed the compilation error.

**Comment by danberindei** [comment]
Integrated, thanks Will!

**Comment by danberindei** [comment]
@wburns There's a failure that happens in CI only on the 9.4.x branch and on this PR, could you investigate?

```
16:31:25,216 ERROR (testng-ExceptionEvictionTest:[]) [TestSuiteProgress] Test failed: org.infinispan.eviction.impl.ExceptionEvictionTest.testEntryExpirationOverwritten[DIST_SYNC, nodeCount=1, storageType=OBJECT, optimisticTransaction=true]([false, false])
java.lang.AssertionError: Wrong exception thrown: expected:<org.infinispan.interceptors.impl.ContainerFullException>, actual:<java.lang.AssertionError>
	at org.infinispan.test.Exceptions.assertException(Exceptions.java:22) ~[test-classes/:?]
	at org.infinispan.eviction.impl.ExceptionEvictionTest.testEntryExpirationOverwritten(ExceptionEvictionTest.java:452) ~[test-classes/:?]
Caused by: java.lang.AssertionError: Should have thrown an exception!
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) ~[testng-6.14.3.jar:?]
	at org.infinispan.eviction.impl.ExceptionEvictionTest.testEntryExpirationOverwritten(ExceptionEvictionTest.java:450) ~[test-classes/:?]
```

**Pull request merged**
