### PR TITLE
ISPN-10788 Display serverNG environment always

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.jboss.org/browse/ISPN-10788

### CODE REVIEW

**Comment by ryanemerson** [comment]
Thansk @diegolovison

**Comment by tristantarrant** [comment]
I dislike this being the default

**Comment by ryanemerson** [comment]
@tristantarrant Why? It will be very useful when debugging customer logs in the image, because we can readily see what java otps etc have been tweaked.

**Comment by tristantarrant** [comment]
Because I'd prefer this information to be output using the server logger. Doing it like this means stdout only

**Comment by ryanemerson** [comment]
That's a fair point. I think Logging those values at INFO level would make sense so that they're written by default.

**Pull request merged**
