### PR TITLE
ISPN-10335 Use stub for PersistenceManager when no stores are configured

### PR DESCRIPTION
**Pull request by wburns**
https://issues.jboss.org/browse/ISPN-10335

### CODE REVIEW

**Comment by wburns** [comment]
@danberindei this PR should help alleviate some of the test suite leaks - others will still remain, have to narrow those down still.

**Comment by danberindei** [comment]
Unused import @wburns, otherwise looks good

**Comment by wburns** [comment]
Fixed import.

**Comment by danberindei** [comment]
Integrated, thanks Will!

**Pull request merged**
