### PR TITLE
ISPN-10273 Convert Primitive Cache Streams to use Distributed Publish…

### PR DESCRIPTION
**Pull request by wburns**
…er underneath

https://issues.jboss.org/browse/ISPN-10273

### CODE REVIEW

**Comment by wburns** [comment]
Can't use serialization for the primitive types operations.

**Comment by wburns** [comment]
@ryanemerson mentioned that lambdas are actually supported to be serializable, so we are good there. 

Also to note that these primitive cache streams are not used often so performance is not that key at this point. We can change if needed later, but I highly doubt that will come up as we move to non blocking API anyways.

**Comment by wburns** [comment]
The flatMap key tracking is broken currently, I need to reevaluate how to do this still.

**Comment by wburns** [comment]
I accidentally forgot to remove `Changes Required` tag and put a comment on the wrong PR.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
