### PR TITLE
ISPN-8295 JGroups 4.0.6

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-8295

### CODE REVIEW

**Comment by danberindei** [comment]
@tristantarrant I've seen some test failures in core when running with trace logging enabled on my machine, I'm investigating them.

**Comment by danberindei** [comment]
@tristantarrant because of the https://issues.jboss.org/browse/JGRP-2205 changes, nodes that should be isolated with DISCARD are now able to send multicast messages, and it takes longer for the cluster to settle into partitions. We need to use `setExcludeItself(false)` to prevent it, like this:

https://github.com/infinispan/infinispan/commit/6e35447d9730d790127f26ac7b46a6765dd75ba6

**Comment by tristantarrant** [comment]
@danberindei  I've made the changes. Let's wait for CI

**Comment by tristantarrant** [comment]
A usual suspect in there, but otherwise a successful run

**Comment by danberindei** [comment]
Integrated, thanks Tristan!

**Pull request merged**
