### PR TITLE
ISPN-9282 Near-Real-Time indexes lost when server is stopped

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-9282

### CODE REVIEW

**Comment by gustavonalle** [comment]
Those test failures are happening a lot on master as well. Any idea what might have changed to cause Datasource related issues?
```
Caused by: javax.resource.ResourceException: IJ000655: No managed connections available within configured blocking timeout (30000 [ms])
```

**Comment by gustavonalle** [comment]
This needs https://github.com/infinispan/infinispan/pull/6062  for the tests to pass

**Comment by gustavonalle** [comment]
Should be fine now

**Comment by tristantarrant** [comment]
Nice one. Merged.

**Pull request merged**
