### PR TITLE
ISPN-11585 Use JavaSerializationMarshaller in JCache TCK suites

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-11585

### CODE REVIEW

**Comment by gustavonalle** [comment]
Could you try on top of https://github.com/infinispan/infinispan/pull/8129?

**Comment by ryanemerson** [comment]
@danberindei `Test Result (508 failures / +5)` :fearful:

**Comment by tristantarrant** [comment]
@danberindei  closing this PR. Please reopen when you are ready to work on it again.

**Comment by danberindei** [comment]
Reopening to rebase on https://github.com/infinispan/infinispan/pull/8824

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
