### PR TITLE
ISPN-10820 Upgrade to JGroups 4.1.6.Final + lower join_timeout + use LOCAL_PING

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-10820
https://issues.jboss.org/browse/ISPN-10821
https://issues.jboss.org/browse/ISPN-10575

### CODE REVIEW

**Comment by tristantarrant** [comment]
Rolling upgrade failures ?

**Comment by danberindei** [comment]
@tristantarrant I thought "upgrade" meant upgrading from HTTP to HotRod so I ignored them :)
I believe they were caused by #7447: https://ci.infinispan.org/job/Infinispan/job/PR-7447/1/

**Comment by wburns** [comment]
They didn't fall in the most recent run
https://ci.infinispan.org/job/Infinispan/job/PR-7447/14/#showFailuresLink

I can look at it closer when I get back though.

**Comment by danberindei** [comment]
@wburns you were right, the failure is caused by my changes: the source and the target nodes were forming a single cluster, and the writing to the target node triggered via the remote store a synchronous write to the same node with the same key, but a different owner (i.e. command invocation id).

**Comment by danberindei** [comment]
Fixed

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
