### PR TITLE
ISPN-10425 Update Netty and RxJava2 to align with Quarkus dependencies

### PR DESCRIPTION
**Pull request by wburns**
https://issues.jboss.org/browse/ISPN-10425

### CODE REVIEW

**Comment by wburns** [comment]
Waiting for CI to give the green light :)

**Comment by tristantarrant** [comment]
There seem to be a number of related test failures which throw io.netty.channel.ExtendedClosedChannelException

**Comment by wburns** [comment]
Also it appears I need to find the appropriate version for the native jar as well.

**Comment by wburns** [comment]
Updated tcnative, just waiting to see if that fixes more than just the couple.

**Pull request merged**
