### PR TITLE
[perfack-only] Big context lock

### PR DESCRIPTION
**Pull request by rvansa**
https://issues.jboss.org/browse/ISPN-7889

### CODE REVIEW

**Comment by rvansa** [comment]
run performance tests please
library
[UDP 1kB]

**Comment by tristantarrant** [comment]
Checkstyle failure

**Comment by rvansa** [comment]
Doesn't matter, perfack is not concerned about such subtleties.

**Comment by diegolovison** [comment]
run performance tests please
library
[UDP 1kB]

**Comment by diegolovison** [comment]
run performance tests please
library
[UDP 1kB]

**Comment by diegolovison** [comment]
run performance tests please
library
[UDP 1kB]

**Comment by pruivo** [comment]
@rvansa maybe perfack needs to compile the code and it fails if the checkstyle fails? (cc @diegolovison )

**Comment by diegolovison** [comment]
@pruivo we disabled. it was taking to much time to get the performance results when a check style error was present.

when jdg-bot was creating a failure comment, it was triggering the job again. I fixed it.

**Pull request closed without merging**
