### PR TITLE
ISPN-14958 Add health endpoint per cache

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-14958

### CODE REVIEW

**Review by karesti — APPROVED** [review]

**Comment by wburns** [comment]
This looks fine to me... only thing I do wonder is what if the cache doesn't exist, what should the status be then or is just an error okay?

**Comment by ryanemerson** [comment]
That's a good point @wburns. I've updated the endpoint to return a 404 if the cache doesn't exist.

**Review by karesti — APPROVED** [review]

**Comment by karesti** [comment]
@ryanemerson needs the backport right ?

**Comment by ryanemerson** [comment]
No need to backport. In the Operator I need to handle older server versions that don't have this method anyway, so I can just start using this from 15.0.x onwards.

**Pull request merged**
