### PR TITLE
ISPN-2886 CDI creates CacheManagers with custom names

### PR DESCRIPTION
**Pull request by slaskawi**
Added Cache Manager name to global configuration in CDI Extension. This prevents throwing `JmxDomainConflictException` when deploying on Wildfly using Library mode.

Ticker URL: https://issues.jboss.org/browse/ISPN-2886

Additional changes:
* Upgraded Shrinkwrap resolvers to more recent version
* Cleaned up code throwing JmxDomainConflictException
* Added additional parameter to the JmxDomainConflictException message

### CODE REVIEW

**Comment by tristantarrant** [comment]
I get these failures 
Tests in error: 
  GreetingServiceIT.testGreetMethod » Runtime Could not inject members
  GreetingServiceIT.testGreetMethodCache » Runtime Could not inject members

**Comment by slaskawi** [comment]
Yes, I overlooked those tests. I'll add necessary changes. Thanks for checking it.

**Comment by slaskawi** [comment]
Additionally removed `test-unstable` profile (unused)

**Comment by galderz** [comment]
Integrated, thanks @slaskawi

**Pull request closed without merging**
