### PR TITLE
ISPN-6767 Upgrade some dependencies to match hibernate-core-5.1.1.Fin…

### PR DESCRIPTION
**Pull request by anistor**
…al requirement

jira: https://issues.jboss.org/browse/ISPN-6767

### CODE REVIEW

**Comment by anistor** [comment]
In my local tests I no longer see the problem reported by @gustavonalle . The only osgi failures I see now are those caused by https://issues.jboss.org/browse/JBMAR-188 ( InfinispanEmbeddedServiceFactoryTest and OSGiKarafFeaturesTest) which are know (reported by @danberindei). 

Still, let's wait for CI this time :)

**Comment by slaskawi** [comment]
Wow, green! :)

**Comment by gustavonalle** [comment]
pulling

**Comment by gustavonalle** [comment]
merged, thanks @anistor

**Pull request merged**
