### PR TITLE
ISPN-6979 Missing PRIMARY_OWNER indexing mode in the xsd

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-6979

### CODE REVIEW

**Comment by anistor** [comment]
@gustavonalle I'm wondering if it would be possible to make the Indexing enum just ON/OFF and leave the ALL/LOCAL/PRIMARY to be determined internally instead of asking the use to decide.

**Comment by gustavonalle** [comment]
@anistor As part of https://issues.jboss.org/browse/ISPN-6947, this configuration will be moved to the index level rather than cache level, and the idea is to assume defaults depending on the index manager, with a possibility to override it.

**Comment by anistor** [comment]
LGTM then. Pulling...

**Comment by anistor** [comment]
Integrated in master. Thanks @gustavonalle !

**Pull request closed without merging**
