### PR TITLE
ISPN-7460: infinispan-defaults dependency resolution error on mvn clean.

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-7460

### CODE REVIEW

**Comment by pruivo** [comment]
are these changes really needed? I don't have any problem doing ```mvn clean``` locally (and I do it all the time :P)

**Comment by ryanemerson** [comment]
@pruivo These changes are required because without them `mvn clean` fails until you perform `mvn install` for the first time (can't find the defaults plugin in the local repo). This causes issues with the release script as it updates the version number, performs `mvn clean` and then starts the build, so the release always fails. For the CR1 release Tristan had to manually intervene to hack around this limitation.

**Comment by pruivo** [comment]
@ryanemerson ok. I'm gonna fix the CI and wait for the results before push the button :+1:

**Comment by tristantarrant** [comment]
This still doesn't fix the issue (see below). You need to explicitly define the plugin execution phase as follows:
`<plugin>
            <groupId>${project.groupId}</groupId>
            <artifactId>infinispan-defaults-maven-plugin</artifactId>
            <version>${project.version}</version>
            <executions>
               <execution>
                  <id>extract-defaults</id>
                  <phase>package</phase>
                  <goals>
                     <goal>extract-defaults</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>`

`[INFO] ------------------------------------------------------------------------
[INFO] Building Infinispan Core 9.0.0.Beta9
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Infinispan BOM ..................................... SUCCESS [  0.041 s]
[INFO] Infinispan Checkstyle Rules ........................ SUCCESS [  0.009 s]
[INFO] Infinispan Common Parent ........................... SUCCESS [  0.038 s]
[INFO] Infinispan Commons ................................. SUCCESS [  0.002 s]
[INFO] Infinispan Commons Test Dependencies ............... SUCCESS [  0.001 s]
[INFO] Infinispan Defaults Maven Plugin ................... SUCCESS [  0.001 s]
[INFO] Infinispan Core .................................... FAILURE [  0.006 s]
[INFO] Infinispan Cloud ................................... SKIPPED
[INFO] Infinispan Extended Statistics ..................... SKIPPED
[INFO] Parent pom for cachestore modules .................. SKIPPED
[INFO] Infinispan JDBC CacheStore ......................... SKIPPED
[INFO] Infinispan JPA CacheStore .......................... SKIPPED
[INFO] Infinispan RocksDB CacheStore ...................... SKIPPED
[INFO] Infinispan LevelDB CacheStore ...................... SKIPPED
[INFO] Infinispan Query DSL API ........................... SKIPPED
[INFO] Infinispan Object Querying and Filtering API ....... SKIPPED
[INFO] Parent pom for the Lucene integration modules ...... SKIPPED
[INFO] Infinispan Lucene Directory Implementation ......... SKIPPED
[INFO] Infinispan Directory Provider for Hibernate Search . SKIPPED
[INFO] Infinispan Query ................................... SKIPPED
[INFO] Infinispan Remote Query Client ..................... SKIPPED
[INFO] Parent pom for server modules ...................... SKIPPED
[INFO] Infinispan Server - Core Components ................ SKIPPED
[INFO] Infinispan Remote Query Server ..................... SKIPPED
[INFO] Infinispan Tasks API ............................... SKIPPED
[INFO] Infinispan Tasks ................................... SKIPPED
[INFO] Infinispan Scripting ............................... SKIPPED
[INFO] Infinispan Hot Rod Server .......................... SKIPPED
[INFO] Infinispan Hot Rod Client .......................... SKIPPED
[INFO] Infinispan Remote CacheStore ....................... SKIPPED
[INFO] Infinispan REST Server ............................. SKIPPED
[INFO] Infinispan REST CacheStore ......................... SKIPPED
[INFO] Infinispan Tools ................................... SKIPPED
[INFO] Infinispan Tree API ................................ SKIPPED
[INFO] Infinispan CLI Client .............................. SKIPPED
[INFO] Infinispan Memcached Server ........................ SKIPPED
[INFO] Infinispan CLI Interpreter ......................... SKIPPED
[INFO] Infinispan Command Line Interface persistence ...... SKIPPED
[INFO] Infinispan Soft-Index CacheStore ................... SKIPPED
[INFO] Infinispan WebSocket Server ........................ SKIPPED
[INFO] Infinispan Multi Tenant Router ..................... SKIPPED
[INFO] Infinispan Atomic Factory .......................... SKIPPED
[INFO] Parent pom for uberjar modules ..................... SKIPPED
[INFO] Infinispan CDI support parent ...................... SKIPPED
[INFO] Infinispan CDI support common ...................... SKIPPED
[INFO] Infinispan CDI remote support ...................... SKIPPED
[INFO] Infinispan JCACHE (JSR-107) Parent ................. SKIPPED
[INFO] Infinispan JCACHE (JSR-107) Common Components ...... SKIPPED
[INFO] Infinispan JCACHE (JSR-107) Remote Implementation .. SKIPPED
[INFO] Infinispan Remote Client ........................... SKIPPED
[INFO] Infinispan CDI embedded support .................... SKIPPED
[INFO] Infinispan JCACHE (JSR-107) Embedded Implementation  SKIPPED
[INFO] Infinispan Embedded ................................ SKIPPED
[INFO] Infinispan Embedded Query .......................... SKIPPED
[INFO] Infinispan CLI ..................................... SKIPPED
[INFO] Infinispan OSGi Service ............................ SKIPPED
[INFO] Infinispan Spring support .......................... SKIPPED
[INFO] Infinispan Spring 4 Common module .................. SKIPPED
[INFO] Infinispan Spring 4 Embedded support ............... SKIPPED
[INFO] Infinispan Spring 4 Remote support ................. SKIPPED
[INFO] Infinispan GUI Demo ................................ SKIPPED
[INFO] Infinispan Distributed Executors and Map/Reduce Demo SKIPPED
[INFO] Infinispan Lucene Directory Demo ................... SKIPPED
[INFO] Infinispan GridFileSystem WebDAV interface ......... SKIPPED
[INFO] Infinispan Server - BOM ............................ SKIPPED
[INFO] Infinispan Server - Commons ........................ SKIPPED
[INFO] Infinispan Server - Event Logger ................... SKIPPED
[INFO] Infinispan Server - JGroups Subsystem .............. SKIPPED
[INFO] Infinispan Server - Infinispan Subsystem ........... SKIPPED
[INFO] Infinispan Server - Endpoints Subsystem ............ SKIPPED
[INFO] Infinispan Server: Command line interface .......... SKIPPED
[INFO] Infinispan Server: Feature Pack .................... SKIPPED
[INFO] Infinispan Server - Build .......................... SKIPPED
[INFO] Integration tests: Security Tests .................. SKIPPED
[INFO] Infinispan Server - Test Suite ..................... SKIPPED
[INFO] Infinispan Server .................................. SKIPPED
[INFO] Infinispan JCACHE (JSR-107) TCK Runner ............. SKIPPED
[INFO] Infinispan modules for Wildfly ..................... SKIPPED
[INFO] Infinispan Integration Tests Parent ................ SKIPPED
[INFO] Integration tests: Wildfly Module Integration Tests  SKIPPED
[INFO] Integration tests: AS Lucene Directory ............. SKIPPED
[INFO] Integration tests: Infinispan compatibility mode ... SKIPPED
[INFO] Integration tests: Infinispan CDI/JCache interactions SKIPPED
[INFO] Integration tests: SecurityManager tests ........... SKIPPED
[INFO] Integration tests: Karaf ........................... SKIPPED
[INFO] Integration tests: Weld SE CDI tests ............... SKIPPED
[INFO] Infinispan Embedded Integration Tests .............. SKIPPED
[INFO] Infinispan Embedded Query Integration Tests ........ SKIPPED
[INFO] Infinispan Remote Client Integration Tests ......... SKIPPED
[INFO] Integration tests: Spring Boot ..................... SKIPPED
[INFO] Parent pom for alternative client marshaller implementation SKIPPED
[INFO] Infinispan Common Marshaller Test Classes .......... SKIPPED
[INFO] Infinispan Kryo Marshaller Bridge .................. SKIPPED
[INFO] Infinispan kryo Marshaller Bridge Compatibility Bundle SKIPPED
[INFO] Infinispan Protostuff Marshaller Bridge ............ SKIPPED
[INFO] Infinispan Protostuff Marshaller Bridge Compatibility Bundle SKIPPED
[INFO] Infinispan ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.238 s
[INFO] Finished at: 2017-02-14T08:17:19+01:00
[INFO] Final Memory: 98M/638M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.infinispan:infinispan-defaults-maven-plugin:9.0.0.Beta9 or one of its dependencies could not be resolved: Failure to find org.infinispan:infinispan-defaults-maven-plugin:jar:9.0.0.Beta9 in https://repository.jboss.org/nexus/content/groups/public-jboss/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
`

**Comment by ryanemerson** [comment]
@tristantarrant I don't think setting `<phase>package</phase>` is correct as the defaults plugin is already bound to "[processes-classes" by default](https://github.com/infinispan/infinispan/blob/master/plugins/infinispan-defaults-maven-plugin/src/main/java/org/infinispan/plugins/maven/defaults/DefaultsExtractorMojo.java#L57) as we need to ensure that xsd files etc are generated before testsuite is executed otherwise ConfigurationUnitTest (for example) will fail.

**Comment by tristantarrant** [comment]
ok, but the plugin isn't available until it is built, therefore you need to explicitly set the phase in the XML.

**Comment by ryanemerson** [comment]
@pruivo, @tristantarrant Updated so that the process-classes phase is explicitly defined. This seems to have fixed the problem.

**Comment by tristantarrant** [comment]
I verified locally that it works. Merged, thanks

**Pull request merged**
