### PR TITLE
ISPN-13611 REST server invokes potentially blocking operations on Net…

### PR DESCRIPTION
**Pull request by wburns**
…ty threads

* Make shutdown commands are done on blocking threads

https://issues.redhat.com/browse/ISPN-13611

### CODE REVIEW

**Review by danberindei — APPROVED** [review]
Looks good, Will!

Do you also want to remove the BlockHound exceptions for container/cache stop, or are you planning to do that in a separate PR?

Something is odd with the test suite: `CollectionRegionAccessStrategyTest` took 58 minutes. But I can't see how that could be connected to your changes here :)

**Comment by ryanemerson** [comment]
I needed to backport in order to test the Operator so I issued a PR: https://github.com/infinispan/infinispan/pull/9829

**Review by pruivo — APPROVED** [review]

**Comment by pruivo** [comment]
> Something is odd with the test suite: `CollectionRegionAccessStrategyTest` took 58 minutes. But I can't see how that could be connected to your changes here :)

It is not. In the oldest main CI build, it takes the same time: https://ci.infinispan.org/job/Infinispan/job/main/280/testReport/org.infinispan.test.hibernate.cache.commons.collection/

**Comment by pruivo** [comment]
merged! thanks @wburns !

**Pull request merged**
