### PR TITLE
ISPN-5781 Upgrade server base to WildFly 10.0.0.CR1

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5781

### CODE REVIEW

**Comment by tristantarrant** [comment]
The server upgrade works great.
The container upgrade for the integration tests is causing some failures, because of some issues with the batching (!) subsystem, so I suggest we upgrade the test container later.

**Comment by galderz** [comment]
CI says there's a compilation error

**Comment by tristantarrant** [comment]
I have fixed it properly this time. The itests still use WF 10.0.0.Beta1.

**Comment by tristantarrant** [comment]
@galderz one unrelated failure now

**Comment by galderz** [comment]
Integrated, thanks @tristantarrant

**Pull request closed without merging**
