### PR TITLE
ISPN-11595 Non Blocking Transaction Performance Regression

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-11595

### CODE REVIEW

**Comment by wburns** [comment]
run performance tests please
library

**Comment by wburns** [comment]
Initial changes show about a 3.5% improvement in throughput and latency. There are a few more places I can make some changes, but it will start making the code a bit larger.

**Comment by wburns** [comment]
run performance tests please
library

**Comment by diegolovison** [comment]
I am investigating the failure

**Comment by wburns** [comment]
> I am investigating the failure

Thanks 👍

**Comment by wburns** [comment]
run performance tests please
library

**Comment by diegolovison** [comment]
run performance tests please
library

**Comment by diegolovison** [comment]
run performance tests please
library

**Comment by wburns** [comment]
run performance tests please
library

**Comment by wburns** [comment]
It appears the changes have made a consistent increase in performance for tx reads. This should be okay now.

**Comment by pruivo** [comment]
integrated! thanks @wburns !

**Pull request merged**
