### PR TITLE
ISPN-14792 Add wildfly-commons back

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.redhat.com/browse/ISPN-14792

### CODE REVIEW

**Comment by pruivo** [comment]
updated: fix version

**Comment by tristantarrant** [comment]
Wouldn't https://github.com/wildfly/wildfly-common/releases/tag/1.6.0.Final work ?

**Comment by tristantarrant** [comment]
It seems like the commits from https://issues.redhat.com/browse/WFCOM-43  are not included in `1.6.0.Final` :$

**Comment by pruivo** [comment]
@tristantarrant yes, it fails with 
```
com.oracle.svm.core.util.UserError$UserException: Cannot find org.jboss.logmanager.formatters.ColorPatternFormatter.isTrueColor, org.jboss.logmanager.formatters.ColorPatternFormatter can not be loaded, due to org/wildfly/common/format/Printf not being available in the classpath. Are you missing a dependency in your classpath?
```

**Comment by tristantarrant** [comment]
It looks like the missing classes have been added to jboss-logmanager instead

**Comment by tristantarrant** [comment]
It's quarkus-core's fault

**Pull request merged**
