### PR TITLE
ProtoStream will throw an Exception if a remote-task is executed in T…

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-14131

### CODE REVIEW

**Comment by wfink** [comment]
checked with upstream, works as expected

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by wburns** [comment]
This brings up the question, should we decided to serialize/marshall immutable collections in protostream? We did with jboss marshalling, which may end up causing issues for people migrating.

**Comment by ryanemerson** [comment]
> This brings up the question, should we decided to serialize/marshall immutable collections in protostream? We did with jboss marshalling, which may end up causing issues for people migrating.

It's possible, but we would need an alternative mechanism in ProtoStream to `AbstractCollectionAdapter` interface that immutable collections use.

A workaround for a users with immutable collections is to make it so they return the field via methods and do the conversion themselves, e.g.:

```java
class Example {
   List<String> unmodifiableEntries;

   @ProtoFactory
   public Example(List<String> entries) {
       this.unmodifiableEntries = Collections.unmodifiableList(entries);
   }
   @ProtoField(number = 1, collectionImplementation = ArrayList.class)
   List<String> entries() {
      return new ArrayList<>(unmodifiableEntries);
   }
}
```

**Pull request merged**
