### PR TITLE
Fixes in RPC handling (8.2.x)

### PR DESCRIPTION
**Pull request by rvansa**

### CODE REVIEW

**Comment by pferraro** [comment]
This doesn't compile.
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/paul/infinispan/8.2.x/infinispan/core/src/main/java/org/infinispan/partitionhandling/impl/PartitionHandlingInterceptor.java:[151,18] cannot find symbol
  symbol:   class Address
  location: class org.infinispan.partitionhandling.impl.PartitionHandlingInterceptor

**Comment by pferraro** [comment]
@rvansa After fixing the compilation issue, these commits seem to fix the issues seen in WFLY-6926.

**Comment by rvansa** [comment]
Added the missing import (no idea how it got lost, I ran the testsuite).

**Comment by danberindei** [comment]
@rvansa please update to match the master PR.

**Comment by rvansa** [comment]
sure, on my TODO

**Comment by rvansa** [comment]
Updated (cherry-pick from master).

**Comment by danberindei** [comment]
Integrated, thanks Radim!

**Pull request closed without merging**
