### PR TITLE
ISPN-9655 REST Access Log headers

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-9655

### CODE REVIEW

**Comment by tristantarrant** [comment]
@oraNod you will want to look at my doc changes here.

**Comment by tristantarrant** [comment]
Well, that would be up to the user to configure things sensibly. By default we don't.

**Comment by wburns** [comment]
Integrated into master, thanks @tristantarrant !

**Comment by wburns** [comment]
Cherry-picked to 9.4.x

**Pull request merged**
