### PR TITLE
ISPN-14573 AbstractAuthorization.testRestServerNodeReport is failing

### PR DESCRIPTION
**Pull request by jabolina**
https://issues.redhat.com/browse/ISPN-14573

Is not the fix yet, but I added a way to detect better if the report script is failing.

### CODE REVIEW

**Comment by jabolina** [comment]
From CI we have that:

```
12:35:08,493 ERROR (non-blocking-thread--p2-t5) [org.infinispan.rest.RestRequestHandler] ISPN012005: An error occurred while responding to the client java.util.concurrent.CompletionException: java.lang.IllegalStateException: Report process exit failed. Exit code: '127' Message: /opt/infinispan/bin/report.sh: line 29: ip: command not found
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
    at java.base/java.lang.Thread.run(Thread.java:829)
 Caused by: java.lang.IllegalStateException: Report process exit failed. Exit code: '127' Message: /opt/infinispan/bin/report.sh: line 29: ip: command not found
    at org.infinispan.server.Server.lambda$getServerReport$11(Server.java:700)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    ... 5 more 
```

**Comment by jabolina** [comment]
ok, after a few rounds of running with `set -e` to check the problem, it was because the image now does not ship with `tar`. I've changed the test to install it in the container.

Looking at [image information](https://catalog.redhat.com/software/containers/ubi8/openjdk-11-runtime/606dcb7d0f75e8ece4deec1f), until tag 1.13-1, 10 months old, tar was included. Since this test is flaky, I can only assume we have a cached image and in some a newer version, although I am not sure if that's possible or not. All in all, I included tar for the test container we use.

**Comment by tristantarrant** [comment]
@ryanemerson IIRC tar is essential also for `oc rsync`

**Comment by ryanemerson** [comment]
That's right. We had to explicitly add `tar` to our server image when `ubi8/openjdk-11-runtime` dropped it https://github.com/infinispan/infinispan-images/pull/192

**Comment by tristantarrant** [comment]
Merged, thanks. Can we have a backport please _

**Pull request merged**
