### PR TITLE
[11.0] ISPN-12515 Improve the HR message when authenticaiton config is incom…

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-12515

### CODE REVIEW

**Comment by ryanemerson** [comment]
@tristantarrant Thanks!

**Comment by tristantarrant** [comment]
Argh, this was still in draft mode

**Comment by tristantarrant** [comment]
I'll create a new PR with the missing bits from master

**Comment by ryanemerson** [comment]
Sorry ... I thought that was because master was pending. I'll ask next time!

**Comment by tristantarrant** [comment]
Apologies: I had actually updated it and I forgot...
Senility kicking in

**Pull request merged**
