### PR TITLE
ISPN-5320 Use BoundedCHMv8 for bounded Hot Rod client near cache

### PR DESCRIPTION
**Pull request by galderz**
https://issues.jboss.org/browse/ISPN-5320

### CODE REVIEW

**Comment by wburns** [comment]
Pulling...

**Comment by wburns** [comment]
I still can't run tests on client/hotrod-client module for some reason or another.  Going to make wait for CI

**Comment by gustavonalle** [comment]
There are test failures

**Comment by galderz** [comment]
There's only 1 failure and it's not related to this PR.

**Comment by gustavonalle** [comment]
@galderz right, the test failures on HotRod I was seeing was being caused by another PR, which was fixed since then.

**Comment by wburns** [comment]
Pulling...

**Comment by wburns** [comment]
Integrated into master, thanks @galderz !

**Pull request closed without merging**
