### PR TITLE
ISPN-7948 Generate metadata files in target/classes

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-7948

### CODE REVIEW

**Comment by galderz** [comment]
Looks good to me, wait for good CI run

**Comment by anistor** [comment]
LGTM.

**Comment by tristantarrant** [comment]
Tests are not affected by this PR: http://ci.infinispan.org/job/Infinispan/job/PR-5216/2/

**Comment by danberindei** [comment]
Integrated, thanks Tristan!

**Pull request closed without merging**
