### PR TITLE
ISPN-10439 Rest server-ng Resource

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-10439

### CODE REVIEW

**Comment by gustavonalle** [comment]
I'm going to do a slightly change: remove the ```/v2/jvm``` resources and create separate ones for memory and system properties

**Comment by tristantarrant** [comment]
@gustavonalle we might want to make the jvm part (which is obtained solely through MBeans) optional so that it will work in substratevm

**Comment by gustavonalle** [comment]
@tristantarrant sounds good, but do I need to change anything? I assume it will just throw an exception on susbtrateVM?

**Comment by gustavonalle** [comment]
Maybe not trying to obtain those MXBeans in a static block would be the first step :)

**Comment by gustavonalle** [comment]
Updated

**Comment by tristantarrant** [comment]
Conflicts

**Comment by gustavonalle** [comment]
fixed

**Comment by gustavonalle** [comment]
Just realize I missed one thing: returning the cache manager names from the server.

**Comment by gustavonalle** [comment]
Done

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
