### PR TITLE
ISPN-10582 Remove ANTLR 2.x

### PR DESCRIPTION
**Pull request by anistor**
Cretaceous dependency

https://issues.jboss.org/browse/ISPN-10582

### CODE REVIEW

**Comment by ryanemerson** [comment]
@anistor The changes seem fine, but can you create a JIRA for this is so it can be tracked.

**Comment by anistor** [comment]
Jira created and rebased @ryanemerson . There are some test failures here, but those seem to be happening on master also.

Two of them seem to be happening after recent OSGi related work by   @danberindei

**Comment by anistor** [comment]
Updated, removed some more rust from POM

**Comment by ryanemerson** [comment]
Thanks @anistor

**Pull request merged**
