### PR TITLE
ISPN-11032 Retrieve cluster members physical/logical addresses mapping

### PR DESCRIPTION
**Pull request by karesti**
https://issues.jboss.org/browse/ISPN-11032

### CODE REVIEW

**Comment by karesti** [comment]
does this make any sense ?

**Comment by belaban** [comment]
Hi @karesti : LGTM; the use of `Event.GET_LOGICAL_PHYSICAL_MAPPINGS` is correct.

**Comment by gustavonalle** [comment]
@karesti Do you have a "commit when saving file" plugin on Intellij?  :smile:

**Comment by karesti** [comment]
We learned something

**Pull request closed without merging**
