### PR TITLE
ISPN-8263 Ignore randomly failing tests

### PR DESCRIPTION
**Pull request by galderz**
Things are still not fully tight... working on it. Ignore for the time being.

### CODE REVIEW

**Comment by danberindei** [comment]
One more failure in CI:

http://ci.infinispan.org/job/Infinispan/job/PR-5417/2/testReport/junit/org.infinispan.test.hibernate.cache.collection/CollectionRegionAccessStrategyTest/testRemoveAll_JTA__REPL_SYNC_AccessType_nonstrict_read_write__/

**Comment by galderz** [comment]
@danberindei Added

**Comment by danberindei** [comment]
@galderz One more failure (in 2 cache modes) here:

http://ci.infinispan.org/job/Infinispan/job/PR-5417/4/

**Comment by galderz** [comment]
@danberindei Pushed an update

**Comment by tristantarrant** [comment]
@galderz with https://github.com/infinispan/infinispan/pull/5425 I have introduced the Unstable category for JUnit tests, which I greatly prefer over Ignore.

**Comment by tristantarrant** [comment]
Closing this and adding the same tests to unstable in https://github.com/infinispan/infinispan/pull/5425

**Pull request closed without merging**
