### PR TITLE
ISPN-10519 Upgrade to protostream-4.3.0.Alpha11

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-10519

### CODE REVIEW

**Comment by ryanemerson** [comment]
@anistor The upgrade has broken karaf :worried:

**Comment by pruivo** [comment]
@anistor don't forget to test with `-Pdistribution` because I had some compilation errors downstream (nightly job).
I added `com.google.code.gson:gson` as a dependency in `javadoc-all` and `hotrod-client` module.

**Comment by anistor** [comment]
Rebased.

**Comment by ryanemerson** [comment]
Still failures related to `NoClassDefFoundError` and gson.

**Comment by anistor** [comment]
Updated @ryanemerson !  The fixup commits on the productisation branch should not be necessary anymore @pruivo

**Comment by pruivo** [comment]
integrated! thanks @anistor

**Pull request merged**
