### PR TITLE
[EXPERIMENTAL] Increase infinispan.stagger.delay default to 5000

### PR DESCRIPTION
**Pull request by danberindei**

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please
library dist

**Comment by danberindei** [comment]
run performance tests please

**Comment by tristantarrant** [comment]
Looks like we want a little more. Writes get an extra boost with the longer delay

**Comment by danberindei** [comment]
@tristantarrant The stagger delay really shouldn't influence write performance, running the tests again.

**Comment by danberindei** [comment]
run performance tests please
library dist
cs dist

**Comment by Holmistr** [comment]
@danberindei The client/server tests are currently broken from some reason, @jmarkos is working on that. Just FYI.

**Comment by danberindei** [comment]
@Holmistr we had some vain hope this PR would help with that :)

**Comment by danberindei** [comment]
run performance tests please
library dist

**Comment by jmarkos** [comment]
run performance tests please
library dist
cs dist

**Comment by Holmistr** [comment]
run performance tests please
cs dist

**Comment by Holmistr** [comment]
@danberindei The results above are only for library mode, because PerfAck picked your comment before the @jmarkos 's one (which I have deleted). The PerfAck is now running according to last comment, therefore library cs and cs dist :) Just FYI.

**Comment by danberindei** [comment]
@tristantarrant looks like the write throughput changes were just random noise.

**Comment by tristantarrant** [comment]
We can close this

**Pull request closed without merging**
