### PR TITLE
ISPN-6706: Do not invoke CacheWriter.purge() if there is no eviction …

### PR DESCRIPTION
**Pull request by ksobolew**
…and the writer has preload enabled.

The thinking behind this is that when these two conditions are met, the cache
store's state is expected to be an exact copy of the transient state, and
purging the store itself is redundant: since the transient state is expected to
be the same as the persistent state, the entry will be removed from the store
IFF it is removed from the transient state.

Caveat: manual calls to evict() will break this assumption.

### CODE REVIEW

**Comment by wburns** [comment]
@ksobolew Unfortunately CacheWriter purge isn't related to eviction.  This is to remove entries that have expired [1].  Expiration can be configured both via xml and inserted programatically.  Due to the latter we have to always call the purge method.  It is feasible to keep state on the writer such as a boolean to trigger if any entry has ever been able to expire and it not then skip purge.

I am closing this PR, however if you wanted to possibly add the previous optimization we could field that.  Also if you wanted to suggest a change we could discuss it on the dev mailing list.  Info can be found at [2]

[1] http://infinispan.org/docs/9.0.x/user_guide/user_guide.html#_difference_between_eviction_and_expiration
[2] https://lists.jboss.org/mailman/listinfo/infinispan-dev

**Comment by ksobolew** [comment]
I answered in the ISPN-6706 JIRA

**Comment by wburns** [comment]
@ksobolew thanks, moved discussion to there.

**Comment by wburns** [comment]
Although I do like the creativity with the optimization :+1:

**Pull request closed without merging**
