### PR TITLE
ISPN-14584 Merge infinispan-quarkus into main Infinispan repository

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-14584

- Quarkus code updated to work with Infinispan 15.0.0-SNAPSHOT. See https://github.com/infinispan/infinispan-quarkus/pull/126 for a diff containing these changes only.
- GH action added so that a GH Release is created on release tag with the native CLI binaries attached.
- PRs can now request a native image build with the "Native Image Required" label
- `quay.io/repository/infinispan/server-native:latest` image is updated for each commit to `main`.
- Quarkus integration tests executed as part of Jenkins CI

### CODE REVIEW

**Comment by ryanemerson** [comment]
Before we can merge this PR we need to upgrade all of the CI agents to have the GraalVM JDK

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#3](https://ci.infinispan.org/job/Infinispan/job/PR-10706/3/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by ryanemerson** [comment]
> Do we want to build a native every time ? I fear that requires a lot of extra memory/time for every build.

If we don't do this then I fear we're going to have the same problem that we currently have, which is that PRs with breaking changes are merged and then it's left up to a small subset of the team to fix the issue. Full disclaimer, my primary motivation for creating this PR was because I got fed up of having to fix these issues at image release time.

The current infinispan-quarkus Jenkins job takes ~19 minutes, however that builds all of Infinispan as well, so we're probably talking ~15 mins per PR.

Another option is that we exclusively build the native parts with GH actions. That way we're not using our hardware and the native build will be created in parallel to the Jenkins job :tada:

**Comment by wburns** [comment]
Seems good to me. I wonder if we can just do a nightly build for native if that would be good enough coverage or not.

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#5](https://ci.infinispan.org/job/Infinispan/job/PR-10706/5/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#6](https://ci.infinispan.org/job/Infinispan/job/PR-10706/6/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by ryanemerson** [comment]
> Seems good to me. I wonder if we can just do a nightly build for native if that would be good enough coverage or not.

I fear with this approach the failures will continue to be ignored until release time.

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#8](https://ci.infinispan.org/job/Infinispan/job/PR-10706/8/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#9](https://ci.infinispan.org/job/Infinispan/job/PR-10706/9/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#12](https://ci.infinispan.org/job/Infinispan/job/PR-10706/12/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#16](https://ci.infinispan.org/job/Infinispan/job/PR-10706/16/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by ryanemerson** [comment]
@wburns FYI I had to add a new commit to workaround your recent changes to the `Resp3Handler`. Let me know if this is an issue or there's a better way to handle it.

**Comment by wburns** [comment]
> @wburns FYI I had to add a new commit to workaround your recent changes to the `Resp3Handler`. Let me know if this is an issue or there's a better way to handle it.

Oops, the newly integrated RESP PR changes this again. If anything it should not be needed now iirc.

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#17](https://ci.infinispan.org/job/Infinispan/job/PR-10706/17/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#19](https://ci.infinispan.org/job/Infinispan/job/PR-10706/19/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#20](https://ci.infinispan.org/job/Infinispan/job/PR-10706/20/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#21](https://ci.infinispan.org/job/Infinispan/job/PR-10706/21/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#22](https://ci.infinispan.org/job/Infinispan/job/PR-10706/22/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#24](https://ci.infinispan.org/job/Infinispan/job/PR-10706/24/):
```
quay.io/infinispan-test/server-native:PR-10706
```

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
