### PR TITLE
ISPN-8200 StringBasedStoreMultinodeIT.testFetchState failure

### PR DESCRIPTION
**Pull request by ryanemerson**
Caused by test logic depending on eviction order.

https://issues.jboss.org/browse/ISPN-8200

### CODE REVIEW

**Comment by tristantarrant** [comment]
http://ci.infinispan.org/job/Infinispan/job/PR-5375/2/testReport/org.infinispan.server.test.cs.jdbc.multinode/StringBasedStoreMultinodeIT/testFetchState/

**Comment by ryanemerson** [comment]
@tristantarrant I removed most of the eviction ordering logic, but then added a little myself :see_no_evil:. It should be right now

**Comment by danberindei** [comment]
@ryanemerson @tristantarrant TBH I'd remove the eviction check completely, as there should be plenty of tests in core checking that eviction happens correctly, but this is good enough ;)

**Comment by tristantarrant** [comment]
Pushed to master

**Pull request merged**
