### PR TITLE
ISPN-10632 Cleanup leftovers of WF removal

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.jboss.org/browse/ISPN-10632

### CODE REVIEW

**Comment by ryanemerson** [comment]
@pruivo The changes LGTM, we'll just need to make sure we get a run where the SNAPSHOTs don't exist at the start.

**Comment by pruivo** [comment]
any comment about https://github.com/infinispan/infinispan/pull/7332/files#diff-0bb53e4d87f456feef54a29ab7a4b24bR282
I'm not sure if we have any server-connector to show in javadoc :/

**Comment by tristantarrant** [comment]
@pruivo I have added an extra commit that @ryanemerson requested which removes the infinispan-wildfly-versions module

**Comment by ryanemerson** [comment]
Thanks @pruivo @tristantarrant

**Pull request merged**
