### PR TITLE
ISPN-13905 Baseline to JDK 11

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-13905

~~Note: building with JDK 19 will **not** work because Maven Shade doesn't support class file major version 63~~
Upgraded ow2 asm to 9.3 makes everything build with JDK 19-ea

### CODE REVIEW

**Comment by pruivo** [comment]
`java8-test` profile in `server/rest/pom.xml` can be removed.
I guess the following dependency can be removed now: 
```
         <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
            <version>${versionx.com.fasterxml.jackson.modules.jackson-modules-java8}</version>
         </dependency>
 ```

**Comment by tristantarrant** [comment]
The jackson dependency is not what you think: it adds support for JDK 8 data types

**Comment by pruivo** [comment]
I think the following configuration can be removed (`server/runtime/pom.xml`, `api/pom.xml`, `client/hotrod/pom.xml`) since it does not change anything from parent pom.
```
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
               <!-- Forking is necessary to allow for the compiler args to be picked up. -->
               <fork combine.children="append">true</fork>
               <release>11</release>
               <!-- Workaround for https://youtrack.jetbrains.com/issue/IDEA-199818 -->
               <source>11</source>
               <target>11</target>
            </configuration>
```

**Comment by pruivo** [comment]
may I suggest removing `commons/jdk11`? I think the code was moved to `commons/all` right?

**Comment by pruivo** [comment]
> The jackson dependency is not what you think: it adds support for JDK 8 data types

ah my bad... do we still need support for JDK 8 types? :)

**Comment by tristantarrant** [comment]
> may I suggest removing `commons/jdk11`? I think the code was moved to `commons/all` right?

Removed

**Review by pruivo — APPROVED** [review]

**Comment by tristantarrant** [comment]
@pruivo I've released a new version of  `infinispan-javadoc` that works with JDK 17 and made some changes here in the second commit

**Review by pruivo — APPROVED** [review]

**Comment by pruivo** [comment]
merged! thanks @tristantarrant !

**Comment by alanfx** [comment]
Hey @tristantarrant is it possible to have a followup task to make sure that the client tests have a profile or some other way to run under JDK8?

**Comment by alanfx** [comment]
@tristantarrant but won't QE need to verify that the client on the `main/14.0.x` branch runs with JDK8?

**Pull request merged**
