### PR TITLE
ISPN-8654 NPE EntryMergePolicyFactoryRegistry

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-8654

### CODE REVIEW

**Comment by gustavonalle** [comment]
Thanks @ryanemerson, let me run some tests

**Comment by ryanemerson** [comment]
@gustavonalle I don't think that `CustomEntryMergePolicyIT` ever caused the deadlock tbh. When running `mvn verify` on the `server/integration/testsuite` dir the test always hang on `HotRodRemoteStreamingIT.serverShutdownTest` even if `CustomEntryMergePolicyIT` is removed.

**Comment by galderz** [comment]
Last CI did not finish, kicking it off again

**Comment by gustavonalle** [comment]
CI refuses to build this PR after several tries (due to some network error), let me build it locally

**Comment by gustavonalle** [comment]
Merged, thanks @ryanemerson !

**Pull request merged**
