### PR TITLE
ISPN-14361 Create Hibernate 2LC implementation for Hibernate 6.2.x

### PR DESCRIPTION
**Pull request by wburns**
* Drop 6.0 support
* Update jakarta dependency

https://issues.redhat.com/browse/ISPN-14361

### CODE REVIEW

**Review by Sanne — APPROVED** [review]
Looks good, thanks!

**Comment by Sanne** [comment]
it failed to compile though:
```
[ERROR] /home/infinispan/workspace/Infinispan_PR-10570/hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/SessionAccess.java:[5,43] error: cannot find symbol
[2023-01-30T18:05:13.996Z] 13:05:13.375 [ERROR]   symbol:   class IsolationDelegate
[2023-01-30T18:05:13.996Z] 13:05:13.375 [ERROR]   location: package org.hibernate.engine.transaction.spi
[2023-01-30T18:05:13.996Z] 13:05:13.375 [ERROR] /home/infinispan/workspace/Infinispan_PR-10570/hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/SessionAccess.java:[24,6] error: cannot find symbol
[2023-01-30T18:05:13.996Z] 13:05:13.375 [ERROR]   symbol:   class IsolationDelegate
[2023-01-30T18:05:13.996Z] 13:05:13.375 [ERROR]   location: interface TransactionCoordinatorAccess
[2023-01-30T18:05:13.996Z] 13:05:13.375 [ERROR] -> [Help 1]
```

**Comment by wburns** [comment]
Yeah,  something changed in CR2 that seems to be causing, but didn't get a chance to look more closely yet.

**Comment by wburns** [comment]
Looks like tests pass with CR2, squashing commit.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
