### PR TITLE
ISPN-7510 Upgrade to protostream-4.0.0.Alpha7

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-7510

### CODE REVIEW

**Comment by tristantarrant** [comment]
Ci reports two errors related to protobuf

**Comment by anistor** [comment]
Should be fine now.

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by gustavonalle** [comment]
@anistor FYI the tag ```4.0.0.Alpha7``` is missing in the protostream repo

**Comment by anistor** [comment]
I forgot to push it upstream, it was only on my origin. Now it is on both.

**Pull request merged**
