### PR TITLE
[14.0] ISPN-15325 Log4j 2.22.0

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-15325

### CODE REVIEW

**Comment by tristantarrant** [comment]
Just flaky tests

**Comment by tarioch** [comment]
I'm seeing something strange on a PR which only upgrades infinispan from 14.0.21 to 14.0.22 and I'm wondering if this could be caused by changes in here.

The maven plugin cxf-codegen wsdl2java fails with this

```
16:46:05  [WARNING] SEVERE: Tools can not load the frontend plugin class org.apache.cxf.tools.wsdlto.frontend.jaxws.generators.AntGenerator
16:46:05  [WARNING] Exception in thread "main" org.apache.cxf.tools.common.ToolException: Tools can not load the frontend plugin class org.apache.cxf.tools.wsdlto.frontend.jaxws.generators.AntGenerator
16:46:05  [WARNING] 	at org.apache.cxf.tools.wsdlto.core.PluginLoader.getFrontEndGenerators(PluginLoader.java:275)
16:46:05  [WARNING] 	at org.apache.cxf.tools.wsdlto.core.PluginLoader.getFrontEndProfile(PluginLoader.java:385)
16:46:05  [WARNING] 	at org.apache.cxf.tools.wsdlto.WSDLToJava.loadFrontEnd(WSDLToJava.java:64)
16:46:05  [WARNING] 	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:96)
16:46:05  [WARNING] 	at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:86)
16:46:05  [WARNING] 	at org.apache.cxf.maven_plugin.wsdl2java.ForkOnceWSDL2Java.main(ForkOnceWSDL2Java.java:51)
16:46:05  [WARNING] Caused by: java.lang.reflect.InvocationTargetException
16:46:05  [WARNING] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
16:46:05  [WARNING] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
16:46:05  [WARNING] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
16:46:05  [WARNING] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
16:46:05  [WARNING] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
16:46:05  [WARNING] 	at org.apache.cxf.tools.wsdlto.core.PluginLoader.getFrontEndGenerators(PluginLoader.java:270)
16:46:05  [WARNING] 	... 5 more
16:46:05  [WARNING] Caused by: java.lang.ExceptionInInitializerError
16:46:05  [WARNING] 	at org.apache.velocity.app.Velocity.init(Velocity.java:102)
16:46:05  [WARNING] 	at org.apache.cxf.tools.common.VelocityGenerator.initVelocity(VelocityGenerator.java:87)
16:46:05  [WARNING] 	at org.apache.cxf.tools.common.VelocityGenerator.<init>(VelocityGenerator.java:53)
16:46:05  [WARNING] 	at org.apache.cxf.tools.wsdlto.core.AbstractGenerator.<init>(AbstractGenerator.java:46)
16:46:05  [WARNING] 	at org.apache.cxf.tools.wsdlto.frontend.jaxws.generators.AbstractJAXWSGenerator.<init>(AbstractJAXWSGenerator.java:30)
16:46:05  [WARNING] 	at org.apache.cxf.tools.wsdlto.frontend.jaxws.generators.AntGenerator.<init>(AntGenerator.java:44)
16:46:05  [WARNING] 	... 11 more
16:46:05  [WARNING] Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because "configFile" is null
16:46:05  [WARNING] 	at org.infinispan.commons.logging.log4j.XmlConfiguration.setup(XmlConfiguration.java:90)
16:46:05  [WARNING] 	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:262)
16:46:05  [WARNING] 	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:313)
16:46:05  [WARNING] 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:631)
16:46:05  [WARNING] 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:713)
16:46:05  [WARNING] 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:735)
16:46:05  [WARNING] 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:260)
16:46:05  [WARNING] 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:154)
16:46:05  [WARNING] 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:46)
16:46:05  [WARNING] 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:197)
16:46:05  [WARNING] 	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:136)
16:46:05  [WARNING] 	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:58)
16:46:05  [WARNING] 	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
16:46:05  [WARNING] 	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:32)
16:46:05  [WARNING] 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:426)
16:46:05  [WARNING] 	at org.apache.velocity.runtime.RuntimeInstance.<init>(RuntimeInstance.java:121)
16:46:05  [WARNING] 	at org.apache.velocity.runtime.RuntimeSingleton.<clinit>(RuntimeSingleton.java:79)
16:46:05  [WARNING] 	... 17 more
```

So it seems to somehow pick up ```org.infinispan.commons.logging.log4j.XmlConfiguration``` any idea what could be going on?

**Comment by tristantarrant** [comment]
It's finding `META-INF/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat` which is in `infinispan-commons-14.0.22.Final` (but it has been there for a while, so this may be a recent change in log4j2 behavior).
I need to make the Infinispan `XmlConfiguration` more robust (I have created https://issues.redhat.com/browse/ISPN-15507). I'm not sure if there is a way to tell log4j to use another configuration provider

**Comment by tristantarrant** [comment]
https://github.com/infinispan/infinispan/pull/11745

**Pull request merged**
