### PR TITLE
ISPN-14731 Additional properties for the DNS resolver

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14731

### CODE REVIEW

**Comment by tristantarrant** [comment]
DnsResolver has three values: DEFAULT, ROUND_ROBIN and CUSTOM.
I was thinking of making ROUND_ROBIN the default, as it supports more scenarios, but this means that DEFAULT is a misnomer. Maybe JDK ?

**Comment by ryanemerson** [comment]
I know we already have the configuration in place, but do we really need this to be configurable?  Can we just always use ROUND_ROBIN and then the user doesn't have to worry about this.

**Comment by tristantarrant** [comment]
I think allowing custom TTL is a good thing, but yeah, we can drop the dns resolver type

**Comment by tristantarrant** [comment]
@ryanemerson I've hardcoded the roundrobin DNS as the default and left the TTL configs.

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
