### PR TITLE
ISPN-8771 Use full license name in poms

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-8771

### CODE REVIEW

**Comment by ryanemerson** [comment]
@tristantarrant I'm regretting saying this already, but our license files are going to need some TLC after the WFLY 11 upgrade.

**Comment by tristantarrant** [comment]
Yes, but at least lets fix our POMs

**Comment by tristantarrant** [comment]
Yes, but at least lets fix our POMs

**Comment by ryanemerson** [comment]
@tristantarrant I'll fix it before Final [ISPN-8772](https://issues.jboss.org/browse/ISPN-8772).

**Pull request merged**
