### PR TITLE
ISPN-14210 Stores that do not return the EXPIRATION Characteristic sh…

### PR DESCRIPTION
**Pull request by wburns**
…ould not allow expiration

https://issues.redhat.com/browse/ISPN-14210

### CODE REVIEW

**Comment by tristantarrant** [comment]
I think this needs to be documented

**Comment by wburns** [comment]
> I think this needs to be documented

We document that expiration is not supported with SQL store already. However, it is a very small blurb and don't document what that actually means. I can try to expand upon it.

**Comment by wburns** [comment]
Let me know what you think @tristantarrant

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
