### PR TITLE
ISPN-6014 DebuggingUnitTestNGListener handles threadTestName incorrectly

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.jboss.org/browse/ISPN-6014

### CODE REVIEW

**Comment by danberindei** [comment]
@mgencur I'm surprised someone's still using `DebuggingUnitTestTestNGListener` :) I was going to remove it, because leaks are almost always going to happen in failing tests, so running once in a while with `DebuggingUnitTestTestNGListener` won't find any of them.

**Comment by mgencur** [comment]
I think Sebastian is going to use it in his CI. He actually asked me to fix this problem.

**Comment by slaskawi** [comment]
Hey @danberindei! I have noticed this problem during downstream build. I'm all for removing this functionality completely (if that's the simpler thing to do).

**Comment by danberindei** [comment]
@slaskawi Yes, I don't think the `debug-tests` profile is really useful any more, so I'd rather remove it.

**Comment by slaskawi** [comment]
@mgencur @danberindei +1. I've removed it from Jenkins job also.

**Comment by danberindei** [comment]
@mgencur @slaskawi Replaced with https://github.com/infinispan/infinispan/pull/3886

**Pull request closed without merging**
