### PR TITLE
ISPN-15255 Use clustered stats component

### PR DESCRIPTION
**Pull request by karesti**
https://issues.redhat.com/browse/ISPN-15255

### CODE REVIEW

**Review by tristantarrant — CHANGES_REQUESTED** [review]
This is causing several failures

**Comment by karesti** [comment]
@tristantarrant yes, json was not implemented. I've removed the trivial case less trivial now

**Comment by karesti** [comment]
@tristantarrant I was working on it yet haha

**Comment by karesti** [comment]
@tristantarrant now should be working. lets wait for CI

**Comment by karesti** [comment]
@tristantarrant looks good now

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
