### PR TITLE
[10.1.x] ISPN-11525 Fix Authz with REST admin ops 

### PR DESCRIPTION
**Pull request by karesti**
https://issues.redhat.com/browse/ISPN-11525

Backport of https://github.com/infinispan/infinispan/pull/8128

### CODE REVIEW

**Comment by karesti** [comment]
@tristantarrant @gustavonalle test failures seem unrelated

**Comment by gustavonalle** [comment]
Do you really need to backport "ISPN-11446 Always set a default request MediaType for caches" ?
This was created for 11.0 only and it is a large change

This one is fine (ISPN-11643 REST connector misinterprets % in query path elements), but seems unrelated to security?

**Comment by gustavonalle** [comment]
I'd like to avoid backporting ISPN-11446 unless it's strictly necessary. This changes internal behaviour of data conversion and should not go into a micro version

**Comment by karesti** [comment]
what I've backported was necessary (for me) because I was getting compilation problems otherwise.

**Comment by gustavonalle** [comment]
Sorry @karesti, but ISPN-11446 is a partial work done for 11 only, we'll have to find an alternative to fix those compilation problems. Let me give a try here

**Comment by gustavonalle** [comment]
There was only 1 compilation failure that I manually fixed without the need for ISPN-11446: https://github.com/infinispan/infinispan/pull/8258, let's see what CI says

**Pull request closed without merging**
