### PR TITLE
DB2 and Sybase SQL errors

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-8749
https://issues.jboss.org/browse/ISPN-8758

### CODE REVIEW

**Comment by karesti** [comment]
@gustavonalle apparently github suggest that you might be a good reviewer for this issue

**Comment by gustavonalle** [comment]
Retriggering CI

**Comment by gustavonalle** [comment]
@ryanemerson CI cannot build this PR. Looks like the same behaviour as https://github.com/infinispan/infinispan/pull/5722

**Comment by karesti** [comment]
@gustavonalle I was about to add a comment to say that it was taking like a million years to get built!

**Comment by gustavonalle** [comment]
@ryanemerson Could you close this PR and open another one? This did the trick for @tristantarrant

**Pull request closed without merging**
