### PR TITLE
[8.2.x] ISPN-3391 Upgrade to JBoss Marshalling 2.0.0.Beta3

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.jboss.org/browse/ISPN-3391

See https://issues.jboss.org/browse/WFLY-7746 for rationale.

### CODE REVIEW

**Comment by galderz** [comment]
Looks good, same comment about the commit message.

**Comment by pferraro** [comment]
@galderz Done.

**Comment by gustavonalle** [comment]
@galderz @pferraro  This caused 80+ failures in the server test suite http://ci.infinispan.org/viewLog.html?buildId=46282&tab=buildResultsDiv&buildTypeId=Infinispan_82xHotspotJdk8&guest=1

**Comment by gustavonalle** [comment]
Looks like the build is not available anymore, but the failures can be seen on 8.2.x, test is ```org.infinispan.server.test.client.hotrod.HotRodRemoteCacheIT```

**Comment by galderz** [comment]
After doing some debugging I've noticed that server is built with JBoss Marshalling jar 2.0.0.Beta3, but the River marshaller jar still points to 1.4.10. That's probably the cause, but I'm unsure in which of all the pom(s) the change should be applied. I've pinged @tristantarrant.

**Comment by gustavonalle** [comment]
@galderz You can try creating a module for the river on ```https://github.com/infinispan/infinispan/tree/8.2.x/server/integration/feature-pack/src/main/resources/modules/system/layers/base/org/jboss/marshalling```. Weird that ```master``` works with 1.4.1 though.

**Comment by galderz** [comment]
I've just created [ISPN-7652](https://issues.jboss.org/browse/ISPN-7652). I think I've fixed the issue in 8.2.x branch, but I need to see if I can add a test that causes master to fail too.

**Pull request merged**
