### PR TITLE
ISPN-6182 Scala blueprint generator does not work on JDK 1.9

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.jboss.org/browse/ISPN-6182

### CODE REVIEW

**Comment by anistor** [comment]
Looking...

**Comment by anistor** [comment]
hey @mgencur, I get this error: https://gist.githubusercontent.com/anistor/ba7e4dab3ca2d71f3131/raw/01a8d2f338ed51aaa96188a23dfe5572b6debce3/gistfile1.txt

I have Java "9-ea", maven 3.3.3.

Ever seen something similar?

**Comment by mgencur** [comment]
Sure. It's the same problem I'm solving here. I got rid of scala where I could. But for Hotrod modules there is no workaround. See the jira and the referenced jira in it.

**Comment by mgencur** [comment]
Updated the jira description

**Comment by anistor** [comment]
Understood. thanks!

**Comment by Sanne** [comment]
merged! thanks
I updated the JIRA description to make this task as "build infinispan-core successfully on JDK9" as we still have the problem with other modules.

**Comment by galderz** [comment]
@mgencur Thanks for fix :smile:

**Pull request closed without merging**
