### PR TITLE
Segregate m2e config in bom

### PR DESCRIPTION
**Pull request by sparty02**
Move m2e config into its own profile to tuck it away from the actual bom config.  The m2e profile gets activated when the m2e.version property is set (which happens when its build with m2e...otherwise, its ignored, as it should be).

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity Infinispan :: Pull requests monitor [Build 8179/sparty02:patch-1](http://ci.infinispan.org/viewLog.html?buildId=22530&buildTypeId=bt9&guest=1) for 417e89cc7bd7aa3906536f7fc71d945f9a45c4d6
Tests: 11215, 0 failed (0 new), 23 ignored. Build time: 02:09:18

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8198/sparty02:patch-1](http://ci.infinispan.org/viewLog.html?buildId=22560&buildTypeId=bt9&guest=1) for 417e89cc7bd7aa3906536f7fc71d945f9a45c4d6
Tests: 11215, 2 failed (2 new), 23 ignored. Build time: 01:51:41

Failed tests detected
* (new) TestSuite: org.infinispan.tx.totalorder.statetransfer.ReplTotalOrderVersionedStateTransferTest.testStateTransfer


* (new) org.infinispan.server.test.query.ManualIndexingIT.testManualIndexing

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8207/sparty02:patch-1](http://ci.infinispan.org/viewLog.html?buildId=22574&buildTypeId=bt9&guest=1) for 417e89cc7bd7aa3906536f7fc71d945f9a45c4d6
Tests: 11214, 2 failed (1 new), 23 ignored. Build time: 01:51:42

Failed tests detected
* (new) TestSuite: org.infinispan.atomic.DistWriteSkewAtomicMapAPITest.testConcurrentWritesAndIteration


* (since 05-Jan-2015) org.infinispan.server.test.query.ManualIndexingIT.testManualIndexing

**Comment by isavin** [comment]
Looking...

**Comment by isavin** [comment]
Integrated. Thanks!

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8230/sparty02:patch-1](http://ci.infinispan.org/viewLog.html?buildId=22620&buildTypeId=bt9&guest=1) for 417e89cc7bd7aa3906536f7fc71d945f9a45c4d6
Tests: 11156, 1 failed (0 new), 22 ignored. Build time: 02:22:04

Failed tests detected
* (since 22-Dec-2014) org.infinispan.test.integration.as.InfinispanLuceneDirectoryIT



Error message is logged

Build duration (secs) is too large: 8614

**Pull request closed without merging**
