### PR TITLE
ISPN-5536 Base Server onto WildFly 9.0.0.CR2 using feature packs

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5536

### CODE REVIEW

**Comment by gustavonalle** [comment]
Something caused the build to abort:
```Failed to execute goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.0.0.Final:build (server-provisioning) on project infinispan-server-build: Execution server-provisioning of goal org.wildfly.build:wildfly-server-provisioning-maven-plugin:1.0.0.Final:build failed: java.lang.RuntimeException: java.lang.IllegalStateException: No supplement called 'clustered' could be found to augment the subsystem configuration```

**Comment by tristantarrant** [comment]
Fixed most failures, remaining ones caused by https://issues.jboss.org/browse/WFLY-4771 and we'll need wildfly arquillian 1.0.0.CR2 for that

**Comment by wburns** [comment]
It seems to me that we can't really integrate this with ALL of the arquillian tests broken though.. Is there some way to workaround this (at least in a hacky way) until the issue can be resolved?

**Comment by tristantarrant** [comment]
I have issued a PR for WildFly Arquillian https://github.com/wildfly/wildfly-arquillian/pull/20

**Comment by tristantarrant** [comment]
Thanks to Tomasz Cerar, I have modified the arquillian.xml file to add the <defaultProtocol type="jmx-as7"/> line which won't require updating WildFly Arquillian. Waiting for CI to verify this

**Comment by wburns** [comment]
It looks like the tests still failed:
http://ci.infinispan.org/viewLog.html?buildId=27535&buildTypeId=bt9&guest=1

**Comment by tristantarrant** [comment]
We're still having some test failures:
Tests failed: 8 (4 new)
but some are still related to  https://issues.jboss.org/browse/WFLY-4771, although I've worked around most of the others and others seem related to https://issues.jboss.org/browse/ISPN-4123

**Comment by tristantarrant** [comment]
This is now good to go !

**Comment by wburns** [comment]
It seems there is a compilation error now

http://ci.infinispan.org/viewLog.html?tab=buildLog&logTab=tree&filter=err&expand=all&buildId=27669#_focus=167509

**Comment by tristantarrant** [comment]
Should be fixed, waiting for CI

**Comment by wburns** [comment]
Rerunning on CI again as it seems to have crashed.

**Comment by wburns** [comment]
Pulling...

**Comment by wburns** [comment]
Integrated into master, thanks @tristantarrant !

**Pull request closed without merging**
