### PR TITLE
ISPN-9998 Fix server CLI with Java 11

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-9998

### CODE REVIEW

**Comment by ryanemerson** [comment]
@tristantarrant The CLI loads now, however the script is looking for the `jboss-cli-logging.properties` not the `ispn` one, so we get log output and an error message:

```
Unable to read the logging configuration from 'file:/home/remerson/workspace/RedHat/infinispan/infinispan-alt/server/integration/build/target/server-distribution-thin/infinispan-server-10.0.0-SNAPSHOT/bin/jboss-cli-logging.properties' (java.io.FileNotFoundException: /home/remerson/workspace/RedHat/infinispan/infinispan-alt/server/integration/build/target/server-distribution-thin/infinispan-server-10.0.0-SNAPSHOT/bin/jboss-cli-logging.properties (No such file or directory))
INFO  [org.jboss.modules] JBoss Modules version 1.8.6.Final
WARN: can't find jboss-cli.xml. Using default configuration values.
INFO  [org.xnio] XNIO version 3.6.5.Final
INFO  [org.xnio.nio] XNIO NIO Implementation Version 3.6.5.Final
INFO  [org.jboss.remoting] JBoss Remoting version 5.0.8.Final
INFO  [org.jboss.threads] JBoss Threads version 2.3.2.Final
INFO  [org.wildfly.security] ELY00001: WildFly Elytron version 1.6.0.Final
```

**Comment by tristantarrant** [comment]
Fixed @ryanemerson

**Comment by ryanemerson** [comment]
@tristantarrant I'm still getting the following log warning:

```
WARN: can't find jboss-cli.xml. Using default configuration values.
```

**Comment by tristantarrant** [comment]
@ryanemerson the missing jboss-cli.xml file was already an issue before this PR (it was being pruned by the trimming process). I have fixed that now.

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
