### PR TITLE
ISPN-9076 SearchException when indexing entities in persistent caches

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-9076

### CODE REVIEW

**Comment by anistor** [comment]
Looks good.

**Comment by anistor** [comment]
I'll backport this to 9.2.x too

**Comment by anistor** [comment]
Integrated in master and 9.2.x. Thanks @gustavonalle !

**Comment by anistor** [comment]
@gustavonalle Do we want this backported to 82x and to the product? Are they affected?

**Comment by gustavonalle** [comment]
No need to backport to 8.2 and product

**Pull request merged**
