### PR TITLE
[9.3.x] ISPN-9409 NPE and CCE when using filters/convertes with events with o…

### PR DESCRIPTION
**Pull request by gustavonalle**
…lder clients

https://issues.jboss.org/browse/ISPN-9409

### CODE REVIEW

**Comment by anistor** [comment]
@gustavonalle So we only need this for 9.3.x and not for master?

**Comment by gustavonalle** [comment]
@anistor master should be fine. Once Vittorio verifies this PR, I will add the test to master as well

**Comment by gustavonalle** [comment]
@rigazilla I was going to ask you to test after my last push, but got sidetracked with linkage errors in the server that apparently are not related. Let's see what CI thinks

**Comment by gustavonalle** [comment]
CI finally completed a build after the 7th try. 

Branch ```9.3.x.``` is not stable as well, it may be due to intermittent Linkage errors (https://github.com/infinispan/infinispan/pull/6187 may fix it) and/or build timeouts

**Comment by galderz** [comment]
There are failures, could be related?

```
org.infinispan.server.hotrod.HotRodMergeTest.testNewTopologySentAfterOverlappingMerge[DIST_SYNC, DENY_READ_WRITES]
org.infinispan.server.hotrod.HotRodMergeTest.testNewTopologySentAfterCleanMerge[DIST_SYNC, DENY_READ_WRITES]
```

**Comment by gustavonalle** [comment]
They don't seem related I remember seen those tests fail before, let me rebase

**Comment by gustavonalle** [comment]
Failure not related

**Pull request merged**
