### PR TITLE
ISPN-14360 Create Hibernate 2LC implementation for Hibernate 6.1.x.

### PR DESCRIPTION
**Pull request by jabolina**
https://issues.redhat.com/browse/ISPN-14360

### CODE REVIEW

**Comment by jabolina** [comment]
Only on version `6.1.5.Final` the test fails. Looking closer I found that the `CacheKeyImplementation` changed, specifically the [id assignment](https://github.com/hibernate/hibernate-orm/blob/6596389e5544e4ab9822c02e9d60be75e31e8833/hibernate-core/src/main/java/org/hibernate/cache/internal/CacheKeyImplementation.java#L51).

In our test, we check the id used during the construction of the entity against the entity id, which is now different.  Linking the [CI failure](https://ci.infinispan.org/blue/organizations/jenkins/Infinispan/detail/PR-10513/1/tests).


For comparison, a debug sample in version `6.1.5.Final`:

```
id = {Object[1]@6105} 
 0 = {Long@6106} 1
entityOrRoleName = "org.infinispan.test.hibernate.cache.commons.functional.entities.WithEmbeddedId"
tenantId = null
hashCode = 19530
```

Against `6.1.4.Final`:

```
id = {PK@3901} 
 id = {Long@6101} 1
cacheKeyValueDescriptor = {ComponentCacheKeyValueDescriptor@6100} 
entityOrRoleName = "org.infinispan.test.hibernate.cache.commons.functional.entities.WithEmbeddedId"
tenantId = null
hashCode = 19530
```

/cc @wburns

**Comment by tristantarrant** [comment]
@pferraro has closed the issue, so I'm closing this PR

**Comment by pferraro** [comment]
@jabolina That said, we will still want to fix the test logic to account for the CacheKeyImplementation changes that you encountered.

**Comment by wburns** [comment]
Looking more closely we just need to update our tests as inner hibernate workings have changed

https://github.com/hibernate/hibernate-orm/commit/149da829cdf8ab74f4b4459e2351858278158cb0#diff-51f845c158d2ab702b556adb8e3b101a153485feae2adecfb612f774fd34bf60R97-R110

**Pull request closed without merging**
