### PR TITLE
ISPN-5182 Run tests against the EE 7 APIs so that we pick up JTA 1.2

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5182

### CODE REVIEW

**Comment by slaskawi** [comment]
Hey @tristantarrant! 
Shouldn't we also update some dependencies in BOM? For example:
* `<version.cdi>1.0-SP4</version.cdi>` to `<version.cdi>1.2</version.cdi>`
* `<artifactId>jboss-transaction-api_1.1_spec</artifactId>` to `<artifactId>jboss-transaction-api_1.2_spec</artifactId>`

**Comment by tristantarrant** [comment]
No, we base on those deps. The upgrade is only for test deps

**Comment by slaskawi** [comment]
Ok, thanks for clarification!

**Comment by pruivo** [comment]
the tests are passing but I have the console with exceptions like this:

```
java.lang.IllegalStateException: Cannot log transactions as TransactionXaAdapter{localTransaction=LocalXaTransaction{xid=[Xid:globalId=cc2a2c4b1006f72672e6170616368652e61726965732e7472616e73616374696f6e0000000000000000000000000000,length=64,branchId=1000ffffffa6a2a2c4b1006170616368652e61726965732e7472616e73616374696f6e0000000000000000000000000000,length=64]} LocalTransaction{remoteLockedNodes=[TransactionsSpanningReplicatedCachesTest-NodeA-42662, TransactionsSpanningReplicatedCachesTest-NodeB-23890], isMarkedForRollback=false, lockedKeys=[a], backupKeyLocks=null, topologyId=2, stateTransferFlag=null} org.infinispan.transaction.xa.LocalXaTransaction@167} is not a NamedXAResource.
```

**Comment by tristantarrant** [comment]
Well, since it resolves a ton of failures in the CDI tests, I believe it's a great improvement

**Comment by pruivo** [comment]
ok... pushing :)

**Comment by pruivo** [comment]
integrated! thanks @tristantarrant !

**Pull request closed without merging**
