### PR TITLE
ISPN-5338 Extend JSR-107 tests

### PR DESCRIPTION
**Pull request by mcimbora**
Not being able to reopen the previous PR [1] after force push, I'm creating a new PR with tests for clustered JCache scenarios. I switched back to using TestNG & tried to utilize test support classes as suggested.

[1] https://github.com/infinispan/infinispan/pull/3350

### CODE REVIEW

**Comment by mcimbora** [comment]
Rebased. Looks like JCacheTwoCachesExpirationTest.testExpiration is still not passing.

**Comment by gustavonalle** [comment]
It always passes for me, what errors are you getting?

**Comment by mcimbora** [comment]
It's passing as it's overriden in child class (see remote module, JCacheTwoCachesExpirationTest:35). As for the outcome of the test, I'm getting the following failure:

JCacheTwoCachesExpirationTest>AbstractTwoCachesExpirationTest.testExpiration:37 expected [0] but found [1]

Looks like expired listener is not notified after an entry has expired. It's test with 2 clustered caches.

**Comment by mcimbora** [comment]
I'll have to flip expected/actual values.

**Comment by gustavonalle** [comment]
@mcimbora fair enough, I actually did not look at the code :smile: 
Will check....

**Comment by gustavonalle** [comment]
@galderz can confirm, but I don't think expiration notification was ever supported in JCache. Even for the embedded test, removing ```assert cache1.get("key1") == null;``` would cause it to fail as well since the expiration event is fabricated in a custom interceptor ```org.infinispan.jcache.embedded.interceptor.ExpirationTrackingInterceptor```, and requires the entry to be accessed

**Comment by galderz** [comment]
Indeed @gustavonalle is right, expiration events are not currently supported. This was an oversight, probably due to the fact that the TCK does not test those. @mcimbora Can you create a JIRA for this? Feel free to have a go as well if you fancy :)

**Comment by mcimbora** [comment]
@galderz @gustavonalle Thanks for feedback. I created JIRA for this (ISPN-5482). Indeed, I was looking at some ways how to contribute and JCache stuff seems to be a good candidate (especially things not covered by TCK, as they're probably not top-priority, e.g. ISPN-5326, ISPN-5318). What about the expiration test? Should I exclude it from this PR for now, or leave as it is? I prefer the second option, at least it'll be obvious what should/shouldn't be working.

**Comment by gustavonalle** [comment]
@mcimbora please @Ignore the expiration event tests from the remote JCache for the moment. 
With relation to ISPN-5482, it will be doable for both remote and embedded after https://issues.jboss.org/browse/ISPN-694 , which is not far away
Thanks!  :+1:

**Comment by mcimbora** [comment]
@gustavonalle Fixed & rebased.

**Comment by galderz** [comment]
Integrated, thanks @mcimbora :D

**Pull request closed without merging**
