### PR TITLE
ISPN-5264 Optimize PutAll operations (library mode)

### PR DESCRIPTION
**Pull request by wburns**
* Added some additional changes per comments
* Added back in waiting for future which was causing test failures

https://issues.jboss.org/browse/ISPN-5264

### CODE REVIEW

**Comment by wburns** [comment]
Marked urgent since it fixes the core test failures.

**Comment by pruivo** [comment]
looks good. testing...

**Comment by pruivo** [comment]
core test suite passed. can I push it @wburns?

**Comment by wburns** [comment]
Yeah, if there any other changes we can put it in a different PR even.  At least this way the suite should be better off.

**Comment by pruivo** [comment]
integrated! thanks @wburns !

**Comment by danberindei** [comment]
HotRodRemoteCacheIT looks good too :)

**Comment by danberindei** [comment]
EmbeddedHotRotCacheListenerTest.testLoadingAndStoringEventsHotRod2 and  ExpirationIT.testRESTExpiration are still failing.

http://ci.infinispan.org/viewLog.html?buildId=25065&tab=buildResultsDiv&buildTypeId=bt8#testNameId4239847058529583383

**Comment by wburns** [comment]
Those failures aren't related to this issue.  It seems it may be caused by https://github.com/infinispan/infinispan/pull/3352 instead.  Only thing that possibly stands out is encoder changes.

**Comment by wburns** [comment]
Actually they are intertwined :)  Should be fixing soon.

**Comment by wburns** [comment]
I created https://issues.jboss.org/browse/ISPN-5371.  This was actually an existing issue, but the new changes exposed it :+1:

**Pull request closed without merging**
