### PR TITLE
[14.0] ISPN-14466 Correctly report cache update errors in the REST API

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14466

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#2](https://ci.infinispan.org/job/Infinispan/job/PR-10587/2/):
```
quay.io/infinispan-test/server:PR-10587
```

**Comment by tristantarrant** [comment]
@ryanemerson this should fix the test failures

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#3](https://ci.infinispan.org/job/Infinispan/job/PR-10587/3/):
```
quay.io/infinispan-test/server:PR-10587
```

**Comment by ryanemerson** [comment]
Is the `CacheResourceTest[security=true, protocol=HTTP_11, ssl=true]` failure related? I don't think I've seen that before.

**Pull request merged**
