### PR TITLE
ISPN-13910 Update JGroups to 5.2.2.Final

### PR DESCRIPTION
**Pull request by jabolina**
https://issues.redhat.com/browse/ISPN-13910

* Updating JGroups version and applying all necessary fixes.

### CODE REVIEW

**Comment by tristantarrant** [comment]
Many failures caused by the presence of the `FD` protocol in the stack which was removed in JGroups 5.2.x. I've added a commit to remove it from the Hibernate 2LC tests

**Comment by tristantarrant** [comment]
Please remove the `org.infinispan.test.integration.security.embedded.NodeAuthorization*` tests since the `SASL` protocol was removed from JGroups 5.x

**Comment by jabolina** [comment]
@tristantarrant  Removed the integrations using SASL, the configuration files, and custom handlers. Noticed that the `KeyStoreConfigurationTest` was flaky, fixed it by copying the setup from the `ServerConfigurationParserTest` up to the abstract class, this is not really related to jgroups at all.

Waiting CI now.

**Comment by rhusar** [comment]
@tristantarrant CI might be good but unfortunately it doesn't test any cloud discovery protocols which all need to be bumped with versions compatible with JGroups 5.x which had a signature change. Opened https://github.com/infinispan/infinispan/pull/10145 to address that.

**Pull request merged**
