### PR TITLE
[12.1.x] ISPN-13090 Bump Wildfly version to 23

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.redhat.com/browse/ISPN-13090

### CODE REVIEW

**Comment by pruivo** [comment]
ps. needs update based on master feedback

**Comment by ryanemerson** [comment]
@pruivo Should be good to update now.

**Comment by pruivo** [comment]
updated

**Comment by pruivo** [comment]
on hold for now. found some issues in main

**Comment by pruivo** [comment]
dropped. it breaks because WF uses microprofile-metrics-api 3.0 and it is not compatible with version 2.0. I don't want to break things in a micro update :)

**Pull request closed without merging**
