### PR TITLE
[10.1.x] ISPN-11819 Prevent ContainerInfinispanServerDriver erroneous state with provided server directory

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.redhat.com/browse/ISPN-11819
Master: https://github.com/infinispan/infinispan/pull/8312

### CODE REVIEW

**Comment by diegolovison** [comment]
Waiting for the master PR get merged than I will update the source code

**Comment by ryanemerson** [comment]
@diegolovison Master is in, please update

**Comment by diegolovison** [comment]
@ryanemerson Done. Let's wait for CI.
Thanks

**Comment by ryanemerson** [comment]
Thanks @diegolovison

**Pull request merged**
