### PR TITLE
ISPN-11345 Introduce integration tests for serverNG

### PR DESCRIPTION
**Pull request by diegolovison**
The goal of this PR is:

- Create a Hello World for upstream integration tests in Arquillian containers
- Allow by command line change the profile that will target dynamic the Arquillian container
- Use InfinispanServerDriver in EMBEDDED mode. It is for debugging. Just add a breakpoint
- Allow target ( -DjbossHome=/path/to/eap ) product instead of project

### CODE REVIEW

**Comment by diegolovison** [comment]
When running `mvn test -pl server/integration -Dtest=HotRodRemoteCacheIT -Pwildfly`

```
17:09:09,369 INFO  [org.infinispan.HOTROD] (HotRod-client-async-pool-1-1) ISPN004006: Server sent new topology view (id=1, age=0) containing 1 addresses: [127.0.0.1:11222]
[OK:     0, KO:     1, SKIP:     0] Test failed: org.infinispan.server.integration.HotRodRemoteCacheIT.testReplaceWithVersionWithLifespan
java.lang.NoClassDefFoundError: sun/reflect/ReflectionFactory
        at deployment.infinispan-server-integration.war//org.jboss.marshalling.river.Protocol.getConstructorForSetWihtUnmodifiableMapEntry(Protocol.java:323)
        at deployment.infinispan-server-integration.war//org.jboss.marshalling.river.Protocol.<clinit>(Protocol.java:315)
        at deployment.infinispan-server-integration.war//org.jboss.marshalling.river.RiverMarshaller.<clinit>(RiverMarshaller.java:1333)
        at deployment.infinispan-server-integration.war//org.infinispan.jboss.marshalling.commons.JBossMarshallerFactory.createMarshaller(JBossMarshallerFactory.java:49)
        at deployment.infinispan-server-integration.war//org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller$PerThreadInstanceHolder.getMarshaller(AbstractJBossMarshaller.java:310)
        at deployment.infinispan-server-integration.war//org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.startObjectOutput(AbstractJBossMarshaller.java:92)
        at deployment.infinispan-server-integration.war//org.infinispan.jboss.marshalling.commons.AbstractJBossMarshaller.objectToBuffer(AbstractJBossMarshaller.java:80)
```

**Comment by diegolovison** [comment]
I am going to follow `integrationtests/wildfly-modules`. Hold on

**Comment by gustavonalle** [comment]
-1 for Arquillian

**Comment by alanfx** [comment]
@gustavonalle you have any other suggestions for tools that allow running tests from within a web container?

**Pull request closed without merging**
