### PR TITLE
ISPN-6021 COUNT and AVG aggregations for fields of embedded entities doesn't work

### PR DESCRIPTION
**Pull request by anistor**
Jira: https://issues.jboss.org/browse/ISPN-6021

### CODE REVIEW

**Comment by gustavonalle** [comment]
There's on test failure

**Comment by anistor** [comment]
fixed.

**Comment by gustavonalle** [comment]
@anistor there are two commits that do not seem related to the issue, should they go as well?

**Comment by anistor** [comment]
Yes please, those are some trivial additions so I skipped jira :)

**Comment by gustavonalle** [comment]
merged, thanks!

**Pull request merged**
