### PR TITLE
[10.1] ISPN-10310 Drop state transfer pool from the infinispan WF subsystem

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-10310

Fixes failure in InfinispanExtensionIT

### CODE REVIEW

**Comment by danberindei** [comment]
JIRA reference should be ISPN-11109 Deprecate and remove usages of state transfer executor

**Comment by danberindei** [comment]
Oh well, I already integrated the master PR with the reference to ISPN-10310, so I'm integrating this one as is.

**Comment by johnou** [comment]
Heads up I believe the recent changes to state transfer have caused this regression https://issues.redhat.com/projects/ISPN/issues/ISPN-11227?filter=reportedbyme

**Comment by danberindei** [comment]
Thanks @johnou, I'll investigate.

**Comment by johnou** [comment]
> Thanks @johnou, I'll investigate.

@danberindei I added a reproducer project, just poke me if you need additional information!

**Comment by danberindei** [comment]
@johnou sorry it took so long for me to investigate, but it's not a new problem, and it's definitely not related to the state transfer pool changes:
https://issues.redhat.com/browse/ISPN-4996

**Comment by johnou** [comment]
@danberindei good to know, thanks for taking a look and the workaround.

**Pull request merged**
