### PR TITLE
ISPN-10463 Server uses disabled features

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-10463

Use the infinispan-commons classloader to look up the features
properties file.

### CODE REVIEW

**Comment by danberindei** [comment]
Test failures are unrelated

**Comment by gustavonalle** [comment]
The changes looks good, but I cannot verify them :)
Could you add a test (or hijack an existing one) to verify the server actually has the features disabled?

**Comment by danberindei** [comment]
@gustavonalle unfortunately testing is tricky, because the bug is specifically about ignoring the `META-INF/infinispan-features.properties` in `infinispan-commons.jar`, which is only added during productization. If I wrote a test that launched a server with `-Dinfinispan.feature.data-segmentation=false`, it would pass with or without my changes.

To manually test the change, rebase my commit on a product tag, build the server, and add these lines to `standalone/configuration/standalone.xml`:

            <logger category="org.infinispan.commons.util.Features">
                    <level name="DEBUG"/>
            </logger>

Start the server with `bin/standalone.sh`, and check `standalone/log/server.log` for

```
2019-08-14 14:02:42,597 DEBUG [org.infinispan.commons.util.Features] (MSC service thread 1-5) Feature org.infinispan.feature.data-segmentation=false
```

The log message will not appear at all when running the server without the patch, which makes it hard to tell whether the server picked up the logging configuration changes (sometimes it seems only the 2nd start uses the new logging config).

**Comment by gustavonalle** [comment]
Integrated, thanks @danberindei

**Pull request merged**
