### PR TITLE
[11.0] ISPN-12498 Check authorization on server management ops

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-12498

### CODE REVIEW

**Comment by tristantarrant** [comment]
@pruivo I backported everything from master except the search and backup stuff

**Comment by pruivo** [comment]
why not everything?

**Comment by tristantarrant** [comment]
Silly me: I also needed the search stuff. Backup is master only

**Comment by pruivo** [comment]
@tristantarrant 100 failures in CI :fearful:

**Comment by pruivo** [comment]
not all related :)

**Comment by pruivo** [comment]
@tristantarrant the `ServerConfigurationParserTest` is failing with `java.security.KeyStoreException: ELY02035: KeyStore type could not be detected`. I don't think it is related. Can you confirm?

**Comment by pruivo** [comment]
integrated! thanks @tristantarrant !

**Pull request merged**
