### PR TITLE
ISPN-7074 Provide a copier for indexed entities

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-7074

Apply to both master and 8.2.x please

### CODE REVIEW

**Comment by tristantarrant** [comment]
The CI failure is unrelated.

**Comment by gustavonalle** [comment]
Looks good, but I can't access CI to see the build result

**Comment by gustavonalle** [comment]
integrated in master, thanks @tristantarrant

**Comment by gustavonalle** [comment]
PR for 8.2.x after fixing the configuration file: https://github.com/infinispan/infinispan/pull/4610

**Pull request closed without merging**
