### PR TITLE
ISPN-13713 Update Hibernate Search to 6.0.8

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-13713

### CODE REVIEW

**Comment by tristantarrant** [comment]
CI failure
```
 05:40:08.212 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project infinispan-query: Compilation failure: Compilation failure: 
11:40:08  05:40:08.213 [ERROR] /home/infinispan/workspace/Infinispan_PR-9898/query/src/main/java/org/infinispan/search/mapper/impl/InfinispanEntityTypeContributor.java:[28,18] error: cannot find symbol
11:40:08  05:40:08.213 [ERROR]   symbol:   method failureCollector()
11:40:08  05:40:08.213 [ERROR]   location: variable collector of type PojoAdditionalMetadataCollectorTypeNode
11:40:08  05:40:08.214 [ERROR] /home/infinispan/workspace/Infinispan_PR-9898/query/src/main/java/org/infinispan/search/mapper/model/impl/InfinispanRuntimeIntrospector.java:[6,7] error: InfinispanRuntimeIntrospector is not abstract and does not override abstract method isIgnorableDataAccessThrowable(Throwable) in PojoRuntimeIntrospector
11:40:08  05:40:08.214 [ERROR] -> [Help 1]
```

**Comment by fax4ever** [comment]
Thanks @tristantarrant, I pushed the fixes here and on backport PRs.
I didn't remember that there have been some changes on the way Search handles exceptions, basically now propagating instead of caching... 
I don't know if @yrodiere can look at this PR.

**Review by yrodiere — APPROVED** [review]
> I didn't remember that there have been some changes on the way Search handles exceptions, basically it propagates more instead of catching...

Yes: https://github.com/hibernate/hibernate-search/commit/6c1704f11f224077e9b9032afdf8f16c6015bdf8

>  I don't know if @yrodiere can have a look at this PR.

LGTM. If tests pass :)

**Comment by fax4ever** [comment]
> > I didn't remember that there have been some changes on the way Search handles exceptions, basically it propagates more instead of catching...
> 
> Yes: [hibernate/hibernate-search@6c1704f](https://github.com/hibernate/hibernate-search/commit/6c1704f11f224077e9b9032afdf8f16c6015bdf8)
> 
> > I don't know if @yrodiere can have a look at this PR.
> 
> LGTM. If tests pass :)

Thanks for the feedback @yrodiere!

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
