### PR TITLE
ISPN-10199 Netty 4.1.36

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-10199

### CODE REVIEW

**Comment by wburns** [comment]
We have to make sure our version of netty stays the same as vert.x. I still can't seem to find where they define the actual version, but it appears they are only on 4.1.34 https://github.com/eclipse-vertx/vert.x/commit/1a7af0ca00a97d400d6ec03355ec614e351acde4

**Comment by wburns** [comment]
https://github.com/vert-x3/vertx-dependencies/blob/master/pom.xml#L51

**Comment by wburns** [comment]
To complicate matters more quarkus is currently on vert.x 3.63 which is using 4.1.30 https://github.com/vert-x3/vertx-dependencies/blob/1d860225c94da853dd9cd6bd1f922a363b930a7e/pom.xml#L51

**Comment by wburns** [comment]
So we can leave quarkus as is, but if upgrade netty here we can't upgrade our quarkus plugin until vert.x has updated as well.

**Comment by ryanemerson** [comment]
Closing for now, we should create a new PR/re-open this one when the time is right

**Pull request closed without merging**
