### PR TITLE
ISPN-6542: Backport to 8.2.x

### PR DESCRIPTION
**Pull request by ksobolew**

### CODE REVIEW

**Comment by slaskawi** [comment]
@tristantarrant @rvansa Do we want this change in `8.2.3`?

**Comment by rvansa** [comment]
@slaskawi I think we should incorporate it. 9.0 is still behind the horizon and we want to encourage users to experiment with the functional API.

**Comment by slaskawi** [comment]
In that case, @ksobolew Could you please rebase it?

**Comment by ksobolew** [comment]
@slaskawi @rvansa Actually, this has already been integrated as part of #4303 (ISPN-6576). I completely forgot that I made a separare PR for this one :) Closing.

**Pull request closed without merging**
