### PR TITLE
ISPN-11924 Protostream Processor Dependency XML is incorrect

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-11924

### CODE REVIEW

**Comment by oraNod** [comment]
integrated. thanks @ryanemerson

**Comment by anistor** [comment]
Why was ```<scope>provided</scope>``` removed ? @ryanemerson

**Comment by ryanemerson** [comment]
> Why was `<scope>provided</scope>` removed ? @ryanemerson

The example xml is referenced in a section that is talking about how to use protostream in general, so removing `provided` means that the dependency will work without `infinispan-commons` or `infinispan-core`. As we're already importing the `infinispan-bom` there won't be an issue with a incompatible version being used. Saying that, I don't have strong views on this, so if you think that it should remain `provided` feel free to change it back.

**Comment by anistor** [comment]
We don't want such a dependency (an AP needed just at build time) to be needlessly propagated transitively. I believe ```provided``` was a clumsy way to prevent that. Maven has weird ways to achieve very common things. Are there other ways ? If not, let's keep ```provided``` and add a one line note on why it has ```provided``` scope

**Pull request merged**
