### PR TITLE
[14.x] ISPN-14448 Updates Maven surefire plugin version to 3.0.0-M8

### PR DESCRIPTION
**Pull request by karesti**
Backport of #10573

### CODE REVIEW

**Comment by pruivo** [comment]
why a different JIRA for the backport?

**Comment by karesti** [comment]
@pruivo I opened by mistake and did upstream and backport without seeing Tristan had done upstream for version M8. I forgot the commit and issue message update

**Comment by tristantarrant** [comment]
Also, Surefire M6 and M7 suffer from a severe bug which breaks our testsuite: https://issues.redhat.com/browse/ISPN-14165

**Comment by karesti** [comment]
@tristantarrant at first I was doing the update only in spring 6 preview. thanks!

**Comment by pruivo** [comment]
merged! thanks @karesti !

**Pull request merged**
