### PR TITLE
Feature Packs

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-8689

I have created the following feature-packs so far:

- `infinispan-feature-pack-common`
  - Modules common to client and other packs
- `infinispan-feature-pack-client`
  - Remote modules
- `infinispan-feature-pack-embedded`
- `infinispan-feature-pack-embeded-query`
  - Same as above but with hibernate search etc
- `infinispan-feature-pack-server`
  - Currently this contains the various server bits plus the wildfly extension modules. This should be split into two feature-packs eventually.
- `infinispan-feature-pack-wf-modules`
  - Essentially the server, but with tree, jcache, jpa and cdi modules.

I still need to convert the integrationtests to utilise the `wildfly-server-provisioning-maven-plugin` instead of extracting the `wildfly-modules.zip`, but I want to ensure no failures with the old approach.

### CODE REVIEW

**Comment by ryanemerson** [comment]
Failures are not related.

**Comment by tristantarrant** [comment]
One failure is related I believe: java.lang.LinkageError: org/jboss/marshalling/MarshallingConfiguration
	at org.infinispan.server.test.query.RemoteQueryCompatModeIT$CustomCompatModeMarshaller.<init>(RemoteQueryCompatModeIT.java:114)

**Comment by tristantarrant** [comment]
Green !

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
