### PR TITLE
ISPN-10085 - Hibernate51 and Hibernate53 should not report the same test name

### PR DESCRIPTION
**Pull request by diegolovison**
I decided to remove the entire surefire configuration after generating the effective maven pom and applying only what was different

https://issues.jboss.org/browse/ISPN-10085

### CODE REVIEW

**Comment by diegolovison** [comment]
artifact/hibernate/cache-v51/target/surefire-reports/testng-native-results/TEST-infinispan-hibernate-cache-v51.xml/*view*/ are returning a file with no tests there. I need to check

**Comment by diegolovison** [comment]
We cannot move forward until ISPN-10161 has been fixed.

**Comment by diegolovison** [comment]
It is ready for review.

**Comment by danberindei** [comment]
https://ci.infinispan.org/job/Infinispan/job/PR-6864/11/artifact/hibernate/cache-v51/target/surefire-reports/testng-native-results/TEST-infinispan-hibernate-cache-v51.xml is empty

**Comment by diegolovison** [comment]
@danberindei because of ISPN-10161
You should look at https://ci.infinispan.org/job/Infinispan/job/PR-6864/8/artifact/hibernate/cache-v51/target/surefire-reports/testng-junit-results/TEST-infinispan-hibernate-cache-v51.xml/*view*/
In this build, it generated the file. For the others, no.

**Comment by danberindei** [comment]
Needs rebase @diegolovison

**Comment by ryanemerson** [comment]
@diegolovison Do you have time to address the comments on this PR any time soon? Otherwise we should close as the PR queue is pretty huge atm.

**Comment by diegolovison** [comment]
Hi, we need the following PR to be merged first:

1. https://github.com/infinispan/infinispan/pull/7378
1. https://github.com/infinispan/infinispan/pull/7215

And then I will work on this one.
Tks

**Comment by ryanemerson** [comment]
@diegolovison Ok, closing for now. Please re-open when it's possible to make progress.

**Pull request closed without merging**
