### PR TITLE
ISPN-9562 Remote Exec hangs with hotrod 2.[4567] ver and cache name is provided

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-9562

### CODE REVIEW

**Comment by gustavonalle** [comment]
@rigazilla If it's all good for you, could you integrate this?

**Comment by rigazilla** [comment]
@gustavonalle I can merge, but ci is red (org.infinispan.client.hotrod.event.ClientEventsOOMTest.testOOM). Is that ok?

**Comment by gustavonalle** [comment]
This test is failing on master as well

**Comment by rigazilla** [comment]
merged thanks!

**Pull request merged**
