### PR TITLE
Upgrade to Hibernate search 6's next version

### PR DESCRIPTION
**Pull request by yrodiere**
Just opening this as a draft to facilitate discussion with @gustavonalle.

### CODE REVIEW

**Comment by anistor** [comment]
Needs rebase.

[Note to self, this PR is based on https://github.com/infinispan/infinispan/pull/8692 ]

**Comment by yrodiere** [comment]
Done

**Comment by gustavonalle** [comment]
@yrodiere There are test failures

**Comment by yrodiere** [comment]
@gustavonalle Yes. I'm on it.

**Comment by yrodiere** [comment]
I fixed what could be fixed. I think the remaining failures are unrelated?

**Comment by anistor** [comment]
Seems that my previous PR made a bit of noise that takes 5 mins to rebase. I've rebased it and pushed my copy here :  https://github.com/anistor/infinispan/tree/t_yrodiere_hsearch6-next_m

**Comment by yrodiere** [comment]
@anistor Thanks. I force-pushed your rebase to this branch.
I also added a commit to simplify configuration.
Let's see how CI likes that; please ping me if I forget to fix it.

**Comment by yrodiere** [comment]
Hibernate Search Beta11 has been released; will open a new PR for the upgrade.

**Comment by yrodiere** [comment]
Done: https://github.com/infinispan/infinispan/pull/8757

**Pull request closed without merging**
