### PR TITLE
ISPN-10268 Cluster Resource

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-10268

This should provide enough info to support the [two](https://github.com/jboss-dockerfiles/infinispan/blob/master/server/is_healthy.sh) [healthchecks](https://github.com/jboss-dockerfiles/infinispan/blob/master/server/is_running.sh) in the docker image.

### CODE REVIEW

**Comment by galderz** [comment]
So, for the is-running check we'd just call HEAD and for is-healthy call GET and inspect status?

**Comment by galderz** [comment]
Looks good otherwise. Any comments @crumby?

**Comment by gustavonalle** [comment]
@galderz Yes. There is one catch: you need to pass on credential to the curl command. It is usually in the ENV. Is there a situation where no APP_USER is created ?

**Comment by Crumby** [comment]
LGTM

**Comment by ryanemerson** [comment]
> Is there a situation where no APP_USER is created ?

Not when using our templates/operator. Merging, thanks @gustavonalle

**Pull request merged**
