### PR TITLE
ISPN-5402 Group entry-related client events under a single interface

### PR DESCRIPTION
**Pull request by isavin**
https://issues.jboss.org/browse/ISPN-5402

### CODE REVIEW

**Comment by galderz** [comment]
Not so sure this is so trivial, I might be wrong but won't this create binary compatibilities with clients which have compiled their applications with 7.1 and run with 7.2?

**Comment by galderz** [comment]
Also, I'm not sure there's a real need to do this at all. The way it is right now it works just fine. What's the problem you are trying to solve?

**Comment by isavin** [comment]
It's related to camel-infinispan work. I have a method which handles all event types and I'm trying to avoid casting to the more specific CacheEntryEvent{Created,Modified,Removed} types to obtain the entry key but probably it will break in the case you've mentioned.

**Comment by isavin** [comment]
Closing. I'll just use multiple casts.

**Pull request closed without merging**
