### PR TITLE
ISPN-13532 Cache store properties shouldn't be changed

### PR DESCRIPTION
**Pull request by wburns**
* Make sure store properties case is not changed upon read or write

https://issues.redhat.com/browse/ISPN-13532

### CODE REVIEW

**Comment by wburns** [comment]
Rebased

**Comment by danberindei** [comment]
@wburns the changes seem to cause some test failures:
https://ci.infinispan.org/job/Infinispan/job/PR-9695/3/testReport/junit/org.infinispan.configuration/XmlFileParsingTest/testDummyInMemoryStore/
https://ci.infinispan.org/job/Infinispan/job/PR-9695/3/testReport/junit/org.infinispan.configuration/XmlFileParsingTest/testStoreWithNoConfigureBy/
https://ci.infinispan.org/job/Infinispan/job/PR-9695/3/testReport/junit/org.infinispan.persistence.jdbc.configuration/ConfigurationTest/testTableProperties/

**Comment by wburns** [comment]
Checking failures.

**Comment by wburns** [comment]
Updated to add in dummy parser so it can update attributes as well as fixed test failures and updated upgrading since the attributes mapping with properties is only going to be in 14.

**Comment by pruivo** [comment]
@wburns is `ServerConfigurationSerializerTest.testConfigurationSerialization` related?

**Review by pruivo — APPROVED** [review]
LGTM if CI failure isn't related :)

**Comment by wburns** [comment]
> @wburns is `ServerConfigurationSerializerTest.testConfigurationSerialization` related?

Checking..

**Comment by tristantarrant** [comment]
> > @wburns is `ServerConfigurationSerializerTest.testConfigurationSerialization` related?
> 
> Checking..

No, it is unrelated

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
