### PR TITLE
ISPN-5438 Filter out example jgroups configurations from uber jar

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5438

### CODE REVIEW

**Comment by danberindei** [comment]
New test failures in EmbeddedAllTest:

org.infinispan.commons.CacheException: Unable to invoke method public void org.infinispan.remoting.transport.jgroups.JGroupsTransport.start() on object of type JGroupsTransport
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jgroups.conf.ClassConfigurator

http://ci.infinispan.org/viewLog.html?buildId=26238&buildTypeId=bt9&guest=1

**Comment by tristantarrant** [comment]
Fixed the shade silliness

**Comment by anistor** [comment]
Looking ...

**Comment by anistor** [comment]
Integrated in master. Thanks @tristantarrant !

**Pull request closed without merging**
