### PR TITLE
ISPN-10432 Upgrade Protostream to 4.3.0.Alpha9

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-10432

### CODE REVIEW

**Comment by anistor** [comment]
Updated.

**Comment by ryanemerson** [comment]
@anistor It looks like the two failures are related:

```java
org.infinispan.lucene.Key2StringMapperTest.testChunkCacheKeyInitWithNllFileName
org.infinispan.server.test.query.IndexFlushingIT.testIndexFlushing
```

**Comment by anistor** [comment]
> @anistor It looks like the two failures are related:
> 
> ```java
> org.infinispan.lucene.Key2StringMapperTest.testChunkCacheKeyInitWithNllFileName
> org.infinispan.server.test.query.IndexFlushingIT.testIndexFlushing
> ```

Fixed!

**Comment by anistor** [comment]
just one (unrelated) failure. re-triggering.

**Comment by ryanemerson** [comment]
@anistor The `testIndexFlushing` is still being reported by CI on the latest build https://ci.infinispan.org/job/Infinispan/job/PR-7180/6/testReport/

```java
testIndexFlushingjava.lang.IllegalStateException: Method parameter names are not present in compiled class file! at org.infinispan.server.test.query.IndexFlushingIT.before(IndexFlushingIT.java:61)
--



```

**Comment by anistor** [comment]
Updated @ryanemerson . CI run #8 should hopefully show it fixed.

**Pull request merged**
