### PR TITLE
ISPN-16417 Fix maxOccurs in XSD schema for index-sharding

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-16417

### CODE REVIEW

**Comment by tristantarrant** [comment]
The actual fix is https://github.com/infinispan/infinispan/pull/12766/files#diff-9456ba8256c16859b00c8bf588480c95f20574dcf9ee57bc14189d1afa683b7aL1148
The rest is cleaning up some ambiguity

**Review by fax4ever — APPROVED** [review]
LGTM, thanks Tristan.
Let's wait the CI and merge it!

**Comment by dalbani** [comment]
In case you didn't see, I described a couple of other issues in the XSD in https://issues.redhat.com/browse/ISPN-16417.

**Comment by tristantarrant** [comment]
Thanks @dalbani , I've addressed the other issues

**Comment by tristantarrant** [comment]
Failures are unrelated

**Comment by fax4ever** [comment]
Merged, thanks!

**Pull request merged**
