### PR TITLE
ISPN-6038 Asymmetric remote caches not supported

### PR DESCRIPTION
**Pull request by galderz**
* Asymmetric clusters where some nodes might have some caches and others
  don't is not really a supported scenarion.
* Ever since ping on startup was enabled by default, there is the
  possibility that under such scenarios, if the target for where the
  ping will be directed is a node that has not a cache, the returned
  cache will be null.

### CODE REVIEW

**Comment by tristantarrant** [comment]
the server testsuite also has some asymmetric tests too: server/integration/testsuite/src/test/java/org/infinispan/server/test/asymmetric/AsymmetricClusterIT.java

**Comment by galderz** [comment]
Sorted @tristantarrant

**Comment by tristantarrant** [comment]
Some more places:
https://github.com/infinispan/infinispan/blob/master/server/integration/testsuite/build-testsuite.xml#L188
https://github.com/infinispan/infinispan/blob/master/server/integration/testsuite/src/test/resources/config/infinispan/asymmetric-1.xml
https://github.com/infinispan/infinispan/blob/master/server/integration/testsuite/src/test/resources/config/infinispan/asymmetric-2.xml

**Comment by galderz** [comment]
@tristantarrant Fixed

**Pull request merged**
