### PR TITLE
ISPN-6557 Obtain the Matcher eagerly in QueryEngine and avoid further costs to look it up

### PR DESCRIPTION
**Pull request by anistor**
Also add a test to measure perf impact of query parameters.

https://issues.jboss.org/browse/ISPN-6557
https://issues.jboss.org/browse/ISPN-6578

### CODE REVIEW

**Comment by anistor** [comment]
@mcimbora This PR has a minor perf improvement for query parsing times. And I've also added a slightly modified form of the perf test you wrote (see NamedParamsPerfTest). The difference is this one runs multiple iterations and averages the results. The query cache is cleared before each iteration so they do not interfere. Running multiple iterations is absolutely necessary to ensure warm-up.

I get these timings on this branch:
NamedParamsPerfTest.testNamedParamPerfComparison t1 (avg, us) = 753.439766
NamedParamsPerfTest.testNamedParamPerfComparison t2 (avg, us) = 589.218402
NamedParamsPerfTest.testNamedParamPerfComparison t3 (avg, us) = 554.143199

If I run the same test on the previous commit before the named param refactorings (750564a5e44405ae47db9ade4399f5a24d1b2215) I get:
NamedParamsPerfTest.testNamedParamPerfComparison t1 (avg, us) = 1436.376647
NamedParamsPerfTest.testNamedParamPerfComparison t2 (avg, us) = 1228.3272339999999
NamedParamsPerfTest.testNamedParamPerfComparison t3 (avg, us) = 1210.666804

Please note the times as in microseconds not millisecond.

**Comment by anistor** [comment]
And here are the timings on 8.2.x:
NamedParamsPerfTest.testNamedParamPerfComparison t1 (avg, us) = 1512.078813
NamedParamsPerfTest.testNamedParamPerfComparison t2 (avg, us) = 1287.570161
NamedParamsPerfTest.testNamedParamPerfComparison t3 (avg, us) = 1256.965347

**Comment by slaskawi** [comment]
Those numbers look very promising! The code also looks fine but as usually I'm picky about commits without JIRA reference...

Could you please squash them or simply add some JIRAs for them? Once this is done I can pull it.

**Comment by anistor** [comment]
I've created and added a jira ref to the perf test commit. The 3 commits are not related so I do not feel like squashing them. The other one ("Initialisation of arrays of literals ...") is really something not worth a jira.

**Comment by slaskawi** [comment]
Ok sounds good. Let's give CI time to process it.

**Comment by tristantarrant** [comment]
Pushed to master, thanks

**Pull request closed without merging**
