### PR TITLE
ISPN-10692 WildFly 18.0.0.Beta1

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-10692

### CODE REVIEW

**Comment by tristantarrant** [comment]
@anistor @gustavonalle there is a Hibernate Search micro upgrade in here which required a code change.

Failures are unrelated

**Comment by anistor** [comment]
> a Hibernate Search micro upgrade in here which required a code change.
That is seriously strange, although we do use some non-API there.

**Comment by pruivo** [comment]
is there anything pending? can I push the button? @tristantarrant

**Comment by tristantarrant** [comment]
Sure

**Comment by pruivo** [comment]
integrated! thanks @tristantarrant !

**Pull request merged**
