### PR TITLE
ISPN-13482 WrappedByteArray logging entire values

### PR DESCRIPTION
**Pull request by pruivo**
* hexDump() should respect the HEX_DUMP_LIMIT

https://issues.redhat.com/browse/ISPN-13482

### CODE REVIEW

**Comment by tristantarrant** [comment]
LGTM

**Comment by tristantarrant** [comment]
Merged.

**Comment by tristantarrant** [comment]
Pushed to 13.0.x too

**Comment by pruivo** [comment]
if a PR for 12.1 is required: https://github.com/infinispan/infinispan/pull/9666

**Pull request merged**
