### PR TITLE
ISPN-11083 Replace TestContainers::withFileSystemBind with withCopyFileToContainer

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.redhat.com/browse/ISPN-11083

### CODE REVIEW

**Comment by danberindei** [comment]
The change sounds reasonable @diegolovison, but the server didn't start in the wildfly modules integration tests, so I triggered a new build.

**Comment by tristantarrant** [comment]
Merged.

**Comment by tristantarrant** [comment]
I should never have merged this, since it completely screws up the whole concept of storing persistent data in host volumes. Working on fixing it in ISPN-11172

**Comment by diegolovison** [comment]
@tristantarrant if you revert this fix, it will start failing in our CI. It will be nice if before merging your PR, we do a test. Thanks

**Comment by tristantarrant** [comment]
@diegolovison it's failing upstream anyway. The proper fix is to change the uid/gid of the jboss user inside the container so that the files it creates on the bound volumes have the correct permissions. Your "fix" just copies files to the container, which breaks the test.

**Pull request merged**
