### PR TITLE
ISPN-10870 Rename schemas for version 10.1

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-10870

### CODE REVIEW

**Comment by ryanemerson** [comment]
@danberindei This seems to have broken spring and wildfly integraton.

**Comment by danberindei** [comment]
Updated

* Created `_10_1.xml` test configurations for the Wildfly subsystem tests
* Added `xsd.path` property to enable validation of latest test configuration against the latest schema
* Fixed `Server.CacheContainerCountersResource.num-owners` reference in the schema
* Changed schema location from `https://www.infinispan.org/...` to `https://infinispan.org/...` in Spring test configurations, because `www.infinispan.org` doesn't have the right certificate
* Changed all the XMLs that were still referencing the schemas at `http://www.infinispan.org/...` to use `https://infinispan.org/...` as well

**Comment by danberindei** [comment]
Oops, I went a bit overboard with the https URL change and I also changed the infinispan-spring schema's namespace to `http://infinispan.org/schemas/spring`. Since we don't version the infinispan-spring schema, Spring is using the online version with the old namespace for validation, and my namespace broke all the tests again. Sorry about that, should be fixed now @ryanemerson

**Comment by ryanemerson** [comment]
Thanks @danberindei

**Pull request merged**
