### PR TITLE
ISPN-6226 Deprecate InfinispanCollections.emptySet/Map/List

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-6226

### CODE REVIEW

**Comment by Sanne** [comment]
I think we should avoid importing

    import java.util.*;

**Comment by anistor** [comment]
I usually avoid all * imports, but this one slipped through.

**Comment by anistor** [comment]
Fixed! It seems intellij was kind and collapsed those imports for me.

**Comment by Sanne** [comment]
thanks, merged!

**Pull request merged**
