### PR TITLE
ISPN-13821 Wrong proto schema will cause put operation failure without clear error message

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-13821

### CODE REVIEW

**Comment by fax4ever** [comment]
In the CI there are some failures related to the test instance `IndexedRestSearchTest`, I cannot reproduced them locally.

**Comment by fax4ever** [comment]
Hi @wburns, thanks for the review.
What can we change here?

**Comment by wburns** [comment]
The CI failures need to be sorted out before we can merge. https://ci.infinispan.org/job/Infinispan/job/PR-10048/1/testReport/

**Comment by wburns** [comment]
Actually it looks like it might be the same failures at https://ci.infinispan.org/job/Infinispan/job/main/434/#showFailuresLink. Can you confirm that this PR indeed doesn't affect any of those tests @fax4ever ? Thanks!

**Comment by fax4ever** [comment]
> Actually it looks like it might be the same failures at https://ci.infinispan.org/job/Infinispan/job/main/434/#showFailuresLink. Can you confirm that this PR indeed doesn't affect any of those tests @fax4ever ? Thanks!

I don't think this PR may affect those tests. Thanks

**Comment by fax4ever** [comment]
Forse pushed, rebasing on top of main

**Comment by wburns** [comment]
Integrated into main, thanks @fax4ever !

**Comment by fax4ever** [comment]
Thanks Will!

**Pull request merged**
