### PR TITLE
ISPN-9657 Make multimap/counter/lock jars OSGi compliant 

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9657
https://issues.jboss.org/browse/ISPN-10386

OGGi integration tests will only run in the `java8-test` profile, I haven't managed to get pax-exam working on Java 11 yet.

### CODE REVIEW

**Comment by danberindei** [comment]
@karesti I think during a rebase I missed the `<packaging>bundle</packaging>` in the extended-statistics POM. I removed it and kept extended-statistics a basic jar.

**Comment by danberindei** [comment]
Forgot to remove the label...

**Comment by karesti** [comment]
@danberindei I merge Dan ?

**Comment by danberindei** [comment]
@karesti now it's ready :)

I ran the tests with `-Pjava8-test` one more time and updated `OsgiKarafFeaturesTest` to remove the tests for some features that have been removed in master since I opened the PR.

**Pull request merged**
