### PR TITLE
ISPN-13559 Fix SQL cachestore schema

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-13559

### CODE REVIEW

**Review by oraNod — COMMENTED** [review]
Great work @tristantarrant Building the distribution, "mvn clean install -s maven-settings.xml -Pdistribution -DskipTests", and the SQL store schema and all the others are there as expected.

However it looks like `infinispan-cachestore-jdbc-common-config` is still empty.

**Comment by tristantarrant** [comment]
It's empty, because it is full of abstract definitions used by the jdbc and sql store configs

**Comment by oraNod** [comment]
> It's empty, because it is full of abstract definitions used by the jdbc and sql store configs

Yeah, I was just taking another look and about to update my previous comment. I can see that the JDBC and SQL schemas include JDBC-common. Perhaps it's not necessary to include `infinispan-cachestore-jdbc-common-config.html` in the index.html but it's no big deal.

**Review by oraNod — APPROVED** [review]
LGTM. Thanks @tristantarrant

**Pull request merged**
