### PR TITLE
ISPN-7840 Indexing should happen on owners

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-7840

### CODE REVIEW

**Comment by gustavonalle** [comment]
Should be ready to review, let's get a few CI runs before merging

**Comment by karesti** [comment]
@gustavonalle LGFM but some functional related tests seem ko, aren't they ?

**Comment by gustavonalle** [comment]
@karesti There is one random failure that could be related: 
```
org.infinispan.query.it.ClusteredCacheWithElasticsearchIndexManagerIT.testClear
```

looking into it

**Comment by gustavonalle** [comment]
Test should be fixed now

**Comment by karesti** [comment]
🙏

**Comment by gustavonalle** [comment]
CI looks OK

**Comment by tristantarrant** [comment]
Merged, thanks !

**Pull request merged**
