### PR TITLE
ISPN-12256 InfinispanServerExtensionContainerTest fails to start

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-12256

* Make InfinispanServerExtensionContainerTest use custom configuration
* Add test-tcp and test-udp stacks to custom configuration
* Remove surefire <argLine> element and use args from parent POM
* Define infinispan.cluster.stack=test-tcp in all testdriver modules

### CODE REVIEW

**Comment by karesti** [comment]
@danberindei checkstyle :(

**Review by karesti — CHANGES_REQUESTED** [review]
checkstyle. maybe this PR should help fixing Actuator JUnit 5 test in the other PR you did? we should talk about all this

for 11.x if we want to fix the allow list, this needs to be changed in the infinispan-sb repo

**Comment by danberindei** [comment]
Which Actuator JUnit 5 test @karesti ?

I'm not really interested in 11.x at this point

**Comment by danberindei** [comment]
I have another PR for RemoteCacheMetricBinderTest, #8655

**Review by karesti — APPROVED** [review]

**Pull request merged**
