### PR TITLE
JGroups config changes

### PR DESCRIPTION
**Pull request by diegolovison**

### CODE REVIEW

**Comment by diegolovison** [comment]
run performance tests please
library
cs

**Comment by diegolovison** [comment]
run performance tests please
library
cs

**Comment by diegolovison** [comment]
run performance tests please
library
cs

**Comment by diegolovison** [comment]
run performance tests please
library
cs

**Comment by diegolovison** [comment]
run performance tests please
library

**Comment by diegolovison** [comment]
run performance tests please
cs

**Comment by diegolovison** [comment]
run performance tests please
cs

**Comment by diegolovison** [comment]
run performance tests please
cs

**Comment by diegolovison** [comment]
run performance tests please
cs

**Comment by diegolovison** [comment]
run performance tests please
cs

**Comment by diegolovison** [comment]
cc @tristantarrant

**Comment by danberindei** [comment]
I'll open a new PR/JIRA for switching back to UFC

**Pull request closed without merging**
