### PR TITLE
ISPN-14477 Concurrent Spring session access results in lost session attributes

### PR DESCRIPTION
**Pull request by thelateperseus**
Updated SessionRepository implementation based on the `HazelcastIndexedSessionRepository` implementation in Spring Session. The implementation returns an instance of `InfinispanSession` which is backed by a `MapSession` instance. The `InfinispanSession` tracks changes to the session attributes and only saves attributes which have changed.

I haven't copied any tests from the Hazelcast implementation because I wanted to get feedback on the general idea first.

### CODE REVIEW

**Comment by tristantarrant** [comment]
I should make you aware of https://github.com/wildfly-clustering/wildfly-clustering-spring-session which we wanted to make our default Spring Session implementation as it is much more robust.

**Comment by thelateperseus** [comment]
@tristantarrant thanks - I hadn't heard of wildfly-clustering-spring-session before. Does this mean that the Spring Session implementation in the Infinispan repository is now deprecated in favour of wildfly-clustering-spring-session? What does this mean for this pull request?

**Comment by tristantarrant** [comment]
For now let's keep working on this component. Can you address:
```
[ERROR] /home/infinispan/workspace/Infinispan_PR-10604/spring/spring5/spring5-embedded/src/main/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepository.java:8:8: Unused import - org.infinispan.AdvancedCache. [UnusedImports]
```

**Comment by thelateperseus** [comment]
@tristantarrant I've fixed that issue, but now some tests are failing. As far as I can see, they're not related to the Spring Session implementation. Can you confirm?

**Comment by karesti** [comment]
@thelateperseus yes, failures are unrelated

**Review by karesti — APPROVED** [review]

**Comment by thelateperseus** [comment]
@tristantarrant, @karesti, there wasn't much test coverage of the code I submitted. I'd like to add a few more tests. Should I do that as a separate pull request under the same Jira issue?

**Comment by tristantarrant** [comment]
Yes, that's fine

**Comment by karesti** [comment]
@thelateperseus I can help with that. I'd like those tests in the spring 6 and boot 3 modules

**Comment by karesti** [comment]
@thelateperseus and thanks a lot for this contribution!

**Pull request merged**
