### PR TITLE
ISPN-9599 Require ADMIN permission for getGlobalComponentRegistry

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-9599

* Deprecate getGlobalComponentRegistry and getComponentRegistry
* Require ADMIN permission for both
* Require ADMIN permission for configuration getters
  (getCacheManagerConfiguration, getDefaultCacheConfiguration,
  getCacheConfiguration)
* Remove some internal usages of the configuration getters

### CODE REVIEW

**Comment by tristantarrant** [comment]
Unused imports

**Comment by danberindei** [comment]
I fixed the import and fixed some failures caused by new features, let's see how it goes this time.

**Comment by tristantarrant** [comment]
@danberindei conflicts

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
