### PR TITLE
ISPN-12564 Remove support for property "infinispan.query.lucene.max-boolean-clauses" from the index config

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.redhat.com/browse/ISPN-12564

Should fix ```HotRodCacheQueries``` failures.

### CODE REVIEW

**Comment by wburns** [comment]
Integrated into master, thanks @gustavonalle !

**Comment by wburns** [comment]
So this PR looks like it only solves the failures. I don't see any code regarding the actual remove of the support from the cache config or at least deprecation/warning in parser. Once that is added I can close ISPN-12563 and I will only close ISPN-12564 for now.

**Comment by wburns** [comment]
Actually didn't realize it was just a string property, so I guess it is fine @gustavonalle ? Or should we detect this one with old xml configurations?

**Comment by gustavonalle** [comment]
The whole <properties> from the indexing config is going away. I'd normally deprecate this, but the issue with this config is that it cannot be applied on a per-cache basis, it affects the whole JMV, so better to remove it once and for all from the config

**Pull request merged**
