### PR TITLE
ISPN-12192 Data Distribution endpoint for caches

### PR DESCRIPTION
**Pull request by jabolina**
https://issues.redhat.com/browse/ISPN-12192

Could not use the `caches/{cacheName}/distribution` endpoint, since it clashes with the `caches/{cacheName}/{cacheKey}`. Created the endpoint as `caches/{cacheName}?action=distribution`, which returns:

```json
[{
  "node_name": "CacheResourceV2Test-NodeA",
  "node_addresses":[
    "127.0.0.1:44175"
  ],
  "memory_entries": 0,
  "total_entries": 0
},
...
]
```

### CODE REVIEW

**Comment by tristantarrant** [comment]
Wouldn't we want to collect information from all the nodes ?

**Comment by karesti** [comment]
Yes we want an endpoint that allows displaying all the nodes and the data distribution for a cache on that node.
And globally as well knowing all the memory used per node at cluster level (if possible)

The designs are https://marvelapp.com/prototype/e0f1e1a/screen/67971790

**Comment by jabolina** [comment]
Updated.

**Review by karesti — CHANGES_REQUESTED** [review]
the payload looks good to me, but is there a way to know the total number of entries "in memory" ? We can start with just 2 of the metrics if the one I mention does not make sense in all cases too.

Docs are needed as well

**Comment by karesti** [comment]
@tristantarrant the prorostream dependency change is validated from your side?

**Comment by jabolina** [comment]
> the payload looks good to me, but is there a way to know the total number of entries "in memory" ? We can start with just 2 of the metrics if the one I mention does not make sense in all cases too.
> 
> Docs are needed as well

Currently I am using this one to count in-memory entries, the JSON `memory_entries` holds this value.

https://github.com/infinispan/infinispan/blob/c8e3df8784f8b9d6d9c6351a10716130d2103d37/core/src/main/java/org/infinispan/stats/Stats.java#L35-L38

And this one for the total entries, the JSON `total_entries` is holding this one.

https://github.com/infinispan/infinispan/blob/c8e3df8784f8b9d6d9c6351a10716130d2103d37/core/src/main/java/org/infinispan/stats/Stats.java#L23-L33

Do you think these are ok? Going to work on the docs meantime.

**Pull request merged**
