### PR TITLE
ISPN-6957 Enhance query DSL to support java.time.Instant

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-6957
https://issues.jboss.org/browse/ISPN-7436
https://issues.jboss.org/browse/ISPN-7481

### CODE REVIEW

**Comment by tristantarrant** [comment]
CI has a few failures related to Instant tests.

**Comment by anistor** [comment]
Should be fine now.

**Comment by tristantarrant** [comment]
A couple of related failures in CI: 
org.infinispan.server.test.query (2)
RemoteQueryDMRRegisterIT.testProjections  	
ProtobufMetadataManagerDMROperationsIT.testOperations

**Comment by anistor** [comment]
It seems ProtobufMetadataManagerDMROperationsIT can interfere with almost any other test in that suite. This problem should have appeared earlier. I'll fix it now.

**Comment by anistor** [comment]
Should be fine now.

**Comment by tristantarrant** [comment]
Merged, thanks @anistor

**Pull request merged**
