### PR TITLE
ISPN-7379 AffinityRpcTest random failures

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-7379

### CODE REVIEW

**Comment by danberindei** [comment]
Need more details @gustavonalle, trying to open HSEARCH-2522 I get "This issue can't be viewed"

**Comment by gustavonalle** [comment]
@danberindei https://hibernate.atlassian.net/browse/HSEARCH-2522

**Comment by danberindei** [comment]
@gustavonalle Aha, the problem was I was looking for it in issues.jboss.org :)

**Comment by gustavonalle** [comment]
Ops, hold on, I left a System out in the test....

**Comment by gustavonalle** [comment]
Ready to go now

**Comment by galderz** [comment]
Cool, thx @gustavonalle

**Pull request merged**
