### PR TITLE
[8.2.x] ISPN-6680 InterruptedException during PutAll from Hot Rod client prevents failover

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-6680
https://issues.jboss.org/browse/ISPN-6692

### CODE REVIEW

**Comment by slaskawi** [comment]
Looks good to me. But the changes are really tiny, so I would squash those commits.

**Comment by gustavonalle** [comment]
@slaskawi I'd rather keep commits from different JIRAs separated, are you suggesting squashing the two commits from ISPN-6680?

**Comment by slaskawi** [comment]
@gustavonalle Yes exactly. Sorry for not being precise.

**Comment by gustavonalle** [comment]
@slaskawi I think it's better to not squash them since they weren't on master (this is a backport)

**Comment by slaskawi** [comment]
@gustavonalle ok, pulling

**Comment by slaskawi** [comment]
Integrated thanks @gustavonalle !

**Pull request closed without merging**
