### PR TITLE
Update the RESP commands and format them as a table

### PR DESCRIPTION
**Pull request by tristantarrant**

### CODE REVIEW

**Review by karesti — COMMENTED** [review]
I would do a table per groupe of commands 
but we can do that in further PR

**Comment by tristantarrant** [comment]
I thought of doing that, but the Redis command page doesn't group them like that, so I went with the same approach

**Comment by tristantarrant** [comment]
In any case, we should merge it now and ensure that all open Resp command PRs add their row there

**Comment by karesti** [comment]
if we can add a way to filter them as here would be great
but this can be done after
https://redis.io/commands/

**Pull request merged**
