### PR TITLE
[9.4.x] ISPN-10070 DefaultCacheManager should stop components after start failure

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-10070

Backport of #6806

### CODE REVIEW

**Comment by tristantarrant** [comment]
@danberindei can you rebase this ? I'd like a fresh run

**Comment by danberindei** [comment]
Rebased

**Comment by danberindei** [comment]
https://ci.infinispan.org/job/Infinispan/job/PR-6807/5 looks good except for the unrelated thread leaks

I rebased again to get one more build.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
