### PR TITLE
ISPN-14495 RESP endpoint cannot parse request larger than packet size

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-14495
https://issues.redhat.com/browse/ISPN-14496

### CODE REVIEW

**Comment by jabolina** [comment]
There are some test failures. Also, the doc says something about `CONFIG GET *` to get the list of config options. For comparison, we have :

```text
127.0.0.1:11222> CONFIG GET *
1) *
2)
```

With redis-server:

```text
127.0.0.1:6379> CONFIG GET *
  1) "dbfilename"
  2) "dump.rdb"
  3) "requirepass"
  4) ""
...
```

Should we return an error or something? Or maybe that is not an issue?

**Comment by wburns** [comment]
> There are some test failures.

That is fixed, just needed to update 20 to 21.

>Also, the doc says something about `CONFIG GET *` to get the list of config options. For comparison, we have :
> 
> ```
> 127.0.0.1:11222> CONFIG GET *
> 1) *
> 2)
> ```
> 
> With redis-server:
> 
> ```
> 127.0.0.1:6379> CONFIG GET *
>   1) "dbfilename"
>   2) "dump.rdb"
>   3) "requirepass"
>   4) ""
> ...
> ```
> 
> Should we return an error or something? Or maybe that is not an issue?

I saw that in the doc, I don't know if we want to try to implement CONFIG completely. Unfortunately, almost all of options don't make much sense to us. I guess I could implement `CONFIG GET *` to just return `appendonly` for now though since it actually returns a value (required by redis-benchmark btw)

**Comment by wburns** [comment]
The more I think about it I don't think it is worth at this stage to implement glob pattern matching CONFIG. We literally have a single config option that won't return as "" and this is only done for the redis-benchmark tool so it doesn't complain.

**Comment by jabolina** [comment]
I think at this stage would be OK for us to return an error of not implemented for users querying with a glob.

**Comment by wburns** [comment]
Updated to return an ERR if * or ? are found in the name to prevent glob matching from being used.

**Review by jabolina — APPROVED** [review]
LGTM, waiting for CI.

**Comment by jabolina** [comment]
Merged, thanks @wburns

**Pull request merged**
