### PR TITLE
ISPN-7599 Jolokia support

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/ISPN-7599

This PR is a proposed approach for enabling Jolokia in the server. It uses Agent Bond, which provides a single Java agent for Jolokia (OpenShift) and Prometheus (Kubernetes). 

Highlights:

* Agent Bond was put into the modules (it would look weird it had been placed elsewhere).
* Jolokia bootstrap script is placed in a separate file. It may be also reused in domain mode.
* The agent is turned off by default and in order to enable it, one needs to supply `--jmx` parameter.

Questions and open issues:

* [x] Shall we use it in domain mode? Or are we good with DMR?
* [x] Do we want to bootstrap it with additional parameter? Or should we leave it enabled by default (allocates yet another port in the host).
* [x] Windows script needs to be ironed out (but probably *after* we agree whether this approach is something that we want or not).
* [x] In Docker bootstrap script there is a clash with `--jmx` parameter. It just needs to be debugged and fixed.
* [ ] `agent.conf` needs to be altered for Kubernetes/OpenShift. It needs to have the following content: `jolokia=port=8778,protocol=https,caCert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt,clientPrincipal=cn=system:master-proxy,useSslClientAuthentication=true,extraClientCheck=true,host=0.0.0.0,discoveryEnabled=false`. The question where do we want to do the substitution? In a separate conf file? In Docker image? Or maybe put this on users (they can use ConfigMap to override this file on their own).
* [ ] With the above point in mind, the Management Console should operate also on https.

//cc @vblagoje @ryanemerson @tristantarrant @gustavonalle @galderz

### CODE REVIEW

**Comment by vblagoje** [comment]
Very cool @slaskawi Looking into details!

**Comment by ryanemerson** [comment]
@slaskawi LGTM. A few points/questions:

- What's the plan for Jolokia and embedded? As we're modifying the console to utilise Jolokia, enabling it in embedded will enable the console to work in this context with no additional effort (AFAIK). 
- Regarding agent.conf, should we just allow an optional file parameter after `--jmx`? If no file is specified then just utilise the default agent.conf.
- If possible we should output something to the server log detailing stating what port Jolokia is operating on. Currently we have "Http management interface listening on ...", it would be nice to have the same for Jolokia (especially when the user hasn't specified their own agent.conf file).

**Comment by slaskawi** [comment]
@ryanemerson Thank Ryan. Answering questions:

> What's the plan for Jolokia and embedded? As we're modifying the console to utilise Jolokia, enabling it in embedded will enable the console to work in this context with no additional effort (AFAIK).

This one is very tricky since we don't control the deployment. Users can use Infinispan embedded in Vert.x, Spring Boot, WF or any other container. Each of them might require different types of actions. Just to give you some examples - in Spring Boot one might use Jolokia Java agent (or Agent Bond) whereas on WF one might use Jolokia deployed as WAR.

I honestly don't have any good idea how to solve this apart from documenting it. Maybe @tristantarrant or @galderz will chime in with some good idea.

> Regarding agent.conf, should we just allow an optional file parameter after --jmx? If no file is specified then just utilise the default agent.conf.

I didn't mention it but it's already done this way. Just type './standalone.sh --jmx my-config.properties' and Agent Bond will pick it up.

> If possible we should output something to the server log detailing stating what port Jolokia is operating on. Currently we have "Http management interface listening on ...", it would be nice to have the same for Jolokia (especially when the user hasn't specified their own agent.conf file).

This one is also tricky. Jolokia prints a small information by itself:

```
13:15:59,935 INFO  [org.jboss.modules] (main) JBoss Modules version 1.5.2.Final
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL http://127.0.0.1:8778/jolokia/
13:16:00,066 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
...
```

But I'm not sure how to access Java agent from server modules. I will need to ask some WF folks whether it's possible.

**Comment by slaskawi** [comment]
Answering my own questions:

* We should bootstrap it separately since any Java Agent might affect performance in some way
* I didn't enable Jolokia for Domain Mode. I think we should leave it in DMR mode. Of course we might change our mind in any period of time.

**Comment by vblagoje** [comment]
I looked through the PR and I agree with your proposal @slaskawi . I also agree that we should not have Jolokia enabled for domain mode because functionality provided by domain controller can not be easily replicated in some JMX Bean or wrapper and we'll only confuse everyone who is using Infinispan in a particular deployment setup. Let's do one thing at a time and leave domain mode to DMR for now.

**Comment by vblagoje** [comment]
Integrated with 9e65d83 and ac25f43 Thanks @slaskawi

**Comment by tristantarrant** [comment]
I did not want this merged in 9.1. I'll revert it.

**Comment by vblagoje** [comment]
Ok @tristantarrant cc @slaskawi

**Comment by slaskawi** [comment]
@tristantarrant Why not? I would really appreciate it from OpenShift side of things. With this I could enable Jolokia stuff directly from OSE console. It's pretty nice, have a look: https://developers.redhat.com/blog/2016/03/30/jolokia-jvm-monitoring-in-openshift/

**Comment by tristantarrant** [comment]
Let us not introduce new dependencies/features in the last few days before the release. Additionally this needs amending of the license.xml file.

**Comment by slaskawi** [comment]
@tristantarrant Ok, thanks.

**Comment by tristantarrant** [comment]
Temporarily closing because of CI overload

**Pull request closed without merging**
