### PR TITLE
[#13477] Git commit message template and validation

### LINKED ISSUE #13477: Standard git commit message and validation hook
### Description

To ensure homogeneity in our commit message, we should introduce a validation hook

### Implementation ideas

This is my proposed format for the message:

```
[#01234] Title, summary, imperative, start upper, max 50

* Item 1 wrap at 72 characters
  wrapped text
* Item 2
```

There are two places where we can run this validation: either locally, as a `commit-msg` git hook or server-side, as a `pre-receive` git hook.
The former would let us skip the validation for exceptional situations via the `git commit --no-verify` switch, and is my preference

The following regex should work for the above format
```
^\[#[0-9]+\]\s[A-Z].*\n(\n(\*\s.*\n( .+\n)*)+)?$
```
although it doesn't validate line length

### PR DESCRIPTION
**Pull request by tristantarrant**
Closes #13477

### CODE REVIEW

**Review by ryanemerson — COMMENTED** [review]
When doing `mvn verify -pl .`, I'm getting the following error:

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'profiles.profile[root-dir0].plugins.plugin.[org.codehaus.mojo:exec-maven-plugin].executions.execution.id' must be unique but found duplicate execution with id gitmessage @ line 2902, column 29
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.infinispan:infinispan-parent:15.1.1-SNAPSHOT (/home/remerson/workspace/RedHat/infinispan/infinispan/pom.xml) has 1 error
[ERROR]     'profiles.profile[root-dir0].plugins.plugin.[org.codehaus.mojo:exec-maven-plugin].executions.execution.id' must be unique but found duplicate execution with id gitmessage @ line 2902, column 29
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

**Comment by tristantarrant** [comment]
Yeah, I believe I've fixed it

**Comment by pruivo** [comment]
Does the Jenkins release script need to be updated? The release commit message will not match the validation. (I think)

**Comment by tristantarrant** [comment]
Yes, we need to add `--no-verify` where appropriate

**Pull request merged**
