### PR TITLE
ISPN-6162 Deprecate Query.getResultSize() method

### PR DESCRIPTION
**Pull request by anistor**
Please do not close the jira. This PR only deprecates the method in question.
https://issues.redhat.com/browse/ISPN-6162

### CODE REVIEW

**Comment by tristantarrant** [comment]
Merged

**Comment by gustavonalle** [comment]
-1
Indexed queries can compute the result size cheaply and has pagination built in, should we remove this because of non-indexed query (which is not really for production)?

**Comment by anistor** [comment]
We can undeprecate it any time @gustavonalle :)

**Comment by danberindei** [comment]
@gustavonalle I imagine even for indexed query it's cheaper to return just a few results without counting all of them. Not sure how it works out in Lucene, but back when I was working with databases, we had a large dataset where it took < 10ms to get the first 10 results that we actually needed to display, and > 500ms on top of it to fetch the count so we could display the number of pages.

**Comment by gustavonalle** [comment]
@danberindei Only a few documents are returned, the default is 10. But the total count is essential so that you can know how many results matched, and to paginate among them. When you have an index, you don't have to scroll thought all the results to do the count. In Lucene specifically, there's a data structure called 'inverted index' which is akin to a map keyed by lookup term with a list of document ids, so the query count is cheap to obtain

**Pull request merged**
