### PR TITLE
ISPN-7088 Interceptors should not access TransactionManager

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-7088

Should fix the PessimisticTxPartitionAndMergeDuringRuntimeTest failures.

### CODE REVIEW

**Comment by slaskawi** [comment]
Note, it's still there: http://ci.infinispan.org/viewLog.html?buildId=43271&buildTypeId=bt9

**Comment by rvansa** [comment]
@slaskawi I would merge this PR anyway, I've already ran into a failure that is caused by touching TM directly.

**Comment by slaskawi** [comment]
@rvansa @danberindei Ok, the code looks fine, so let's give it a go.

**Comment by slaskawi** [comment]
Integrated, thanks @danberindei

**Comment by danberindei** [comment]
@slaskawi I haven't seen the failures locally yet, but the stack traces look very similar to https://issues.jboss.org/browse/ISPN-6977. Now I just need to find out what's causing the functional test failures in the #4538 build...

**Pull request merged**
