### PR TITLE
[9.4.x] ISPN-9611 Error executing command PutMapCommand

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-9611

### CODE REVIEW

**Comment by galderz** [comment]
Also, why preview?

**Comment by gustavonalle** [comment]
@galderz was not able to reproduce it. The only info we have about this is the stack trace unfortunately.
Preview is because the CI did not finish.

**Comment by gustavonalle** [comment]
CI was supposed to be green, but it became red in the end because of 
```
groovy.lang.MissingPropertyException: No such property: changed for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
```

**Comment by gustavonalle** [comment]
Should be ready now

**Comment by tristantarrant** [comment]
Merged

**Pull request merged**
