### PR TITLE
ISPN-12186 Update to Hibernate Search 6.0.0.Beta9

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.redhat.com/browse/ISPN-12186

~~Depends on https://github.com/infinispan/infinispan/pull/8604~~

Untangled

### CODE REVIEW

**Comment by gustavonalle** [comment]
rebased

**Comment by anistor** [comment]
LGTM. Waiting for CI

**Comment by anistor** [comment]
Merged in master. Thanks @gustavonalle !

**Comment by anistor** [comment]
Should we also close https://issues.redhat.com/browse/ISPN-12170 @gustavonalle ?

**Pull request merged**
