### PR TITLE
ISPN-10544 Remove dependencies on java.beans module

### PR DESCRIPTION
**Pull request by anistor**
no more java.beans or java.desktop module

https://issues.jboss.org/browse/ISPN-10544

### CODE REVIEW

**Comment by anistor** [comment]
I CI we trust. Let's wait

**Comment by anistor** [comment]
I'll jira this at some point. Don;t know what happens with CI yet ....

**Comment by tristantarrant** [comment]
CI says it is perfect !

**Comment by anistor** [comment]
Amazing!!!1

**Comment by ryanemerson** [comment]
Lets add a Jira and then we're good to go :slightly_smiling_face:

**Comment by anistor** [comment]
Not sure, do we need to backport this @ryanemerson , @tristantarrant ?

**Comment by anistor** [comment]
I merged this myself in master, with your blessing.

**Comment by ryanemerson** [comment]
> Not sure, do we need to backport this

I don't think it's worth the effort as we're just trying to reduce unnecessary mod dependencies going forward. We don't have anyone asking for this in the `9.4.x` stream.

**Comment by anistor** [comment]
Ok, master is fine then.

**Pull request merged**
