### PR TITLE
ISPN-6311 - ExecTest.testRemoteMapReduceWithStreams test is  failing

### PR DESCRIPTION
**Pull request by andyuk1986**
Disabled as the test depends on bug ISPN-6173

### CODE REVIEW

**Comment by anistor** [comment]
@andyuk1986 ISPN-6311 was created just to disable a test?

**Comment by wburns** [comment]
Also to note @andyuk1986 is that REPL will be the same once #4066 is integrated.

**Comment by andyuk1986** [comment]
@anistor at the moment yes, as that test was failing in CI, and I didn't know another pretty way for performing this pull request. But seems that, as soon as #4066 is integrated I would need to disable more tests until the bug ISPN-6173 is fixed.

**Comment by anistor** [comment]
In such cases creating a PR linked to the issue in question (ISPN-6173) is enough, provided there's a note that this PR just disables the failing test rather than fixing it, so the integrator would not mistakenly close the issue. No need to create a separate jira just for disabling a test.

**Comment by anistor** [comment]
Integrated in master. Thanks @andyuk1986 !

**Comment by andyuk1986** [comment]
@anistor OK, got it! Thanks a lot :)

**Pull request closed without merging**
