### PR TITLE
Ispn 7865 Distributed Iterator Reactive Streams

### PR DESCRIPTION
**Pull request by wburns**
https://issues.jboss.org/browse/ISPN-7865

The big new change is in ClusterStreamManager which now exposes a Publisher that will go through all available node targets one by one.

I also refactored a lot of code to utilize IntSet instead of Set<Integer> to avoid boxing if possible (this still needs work after this PR).

### CODE REVIEW

**Comment by wburns** [comment]
There are still 2 things that need to be done

1. Need to add close iterator method for when an iterator is closed early: https://github.com/infinispan/infinispan/pull/5283/files#diff-6b3e6f1e0c88b946f09bf6b426491873R669
2. Need to update tests to use new ClusterStreamManagerImpl: https://github.com/infinispan/infinispan/pull/5283/files#diff-417ff1e82ad1429d18f0630a94a34751R74

**Comment by wburns** [comment]
This should be pretty much completed, barring rework comments. I hope someone can help complete this while I am gone :)

**Comment by wburns** [comment]
Unfortunately CI pukes later on [1], it passes core fine for me. My guess is because I am missing dependencies on the server parts, sorry! I am hoping just adding those in should fix these.

http://ci.infinispan.org/job/Infinispan/job/PR-5283/10/

**Comment by tristantarrant** [comment]
Closed in favor of #5314

**Pull request closed without merging**
