### PR TITLE
ISPN-15372 infinispan-tools artifact is included in BOM but not publi…

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-15372

### CODE REVIEW

**Comment by pruivo** [comment]
if I'm not asking too much, the property can be removed from the `infinispan-parent`
```xml
      <module.skipSupportModuleDeployment>true</module.skipSupportModuleDeployment>
```

**Comment by ryanemerson** [comment]
Updated

**Review by pruivo — APPROVED** [review]

**Comment by pruivo** [comment]
@ryanemerson the native build failed. If it is not related, I can merge this right away!

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
