### PR TITLE
[15.0.x] ISPN-16682 Null DIFF return empty array

### PR DESCRIPTION
**Pull request by infinispanrelease**
**Backport:** https://github.com/infinispan/infinispan/pull/13057

https://issues.redhat.com/browse/ISPN-16682

### CODE REVIEW

**Review by karesti — APPROVED** [review]

**Comment by jabolina** [comment]
There is a failure because the changes I've made to serialization aren't backported yet.

**Comment by karesti** [comment]
@jabolina ping me when the PR of the backport is ready please

**Comment by jabolina** [comment]
@karesti the backport is in :smiley:

**Comment by karesti** [comment]
@jabolina needs rebase

**Pull request merged**
