### PR TITLE
ISPN-5128

### PR DESCRIPTION
**Pull request by Sanne**
https://issues.jboss.org/browse/ISPN-5128

### CODE REVIEW

**Comment by anistor** [comment]
Looks good so far, but I'll have another look in the morning :)

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8249/Sanne:ISPN-5128](http://ci.infinispan.org/viewLog.html?buildId=22665&buildTypeId=bt9&guest=1) for 9206b8977002732aa853f197de74b751674e777c
Tests: 11217, 1 failed (1 new), 23 ignored. Build time: 01:51:20

Failed tests detected
* (new) org.infinispan.server.test.query.ManualIndexingIT.testManualIndexing



Error message is logged

Build duration (secs) is too large: 6668

**Comment by gustavonalle** [comment]
Looks good

**Comment by gustavonalle** [comment]
pulling...

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8259/Sanne:ISPN-5128](http://ci.infinispan.org/viewLog.html?buildId=22685&buildTypeId=bt9&guest=1) for 9206b8977002732aa853f197de74b751674e777c
Tests: 11232, 2 failed (2 new), 23 ignored. Build time: 02:08:25

Failed tests detected
* (new) TestSuite: org.infinispan.client.hotrod.DistTopologyChangeUnderLoadTest.testPutsSucceedWhileTopologyChanges


* (new) TestSuite: org.infinispan.xsite.statetransfer.failures.SiteProviderTopologyChangeTest.testXSiteSTDuringSiteMasterLeave



Error message is logged

Process exited with code 1

Build duration (secs) is too large: 7672

**Pull request closed without merging**
