### PR TITLE
ISPN-11564 UnsupportedOperationException while putting attribute into…

### PR DESCRIPTION
**Pull request by wburns**
… HTTP Session

https://issues.redhat.com/browse/ISPN-11564

### CODE REVIEW

**Comment by gustavonalle** [comment]
86 failures in the Hot Rod client?

**Comment by wburns** [comment]
Most likely a test I forgot to update. Will take care of it today.

**Comment by wburns** [comment]
Actually these test failures seem unrelated... This should have only changed compute, most of these tests don't even use it.

**Comment by gustavonalle** [comment]
LGTM, but puzzled about the test failures: it only seem to happen in your PRs

**Comment by wburns** [comment]
Hrmm, yeah it is quite perplexing. I was unable to reproduce the thread leaks locally. But 2 runs in a row with it is not something to disregard.

**Comment by wburns** [comment]
Ah it looks like all the failures is masking `Class org.infinispan.client.hotrod.APITest has an invalid testName: client.hotrod.tx.APITxTest`

**Comment by wburns** [comment]
It should hopefully be fixed now that I fixed the test name.

**Comment by wburns** [comment]
Tests seem to be back in order now :)

**Comment by gustavonalle** [comment]
Merged, thanks @wburns !

**Pull request merged**
