### PR TITLE
9.1.x offheap

### PR DESCRIPTION
**Pull request by wburns**
This is backports for https://github.com/infinispan/infinispan/pull/5469

https://issues.jboss.org/browse/ISPN-8348
https://issues.jboss.org/browse/ISPN-8359
https://issues.jboss.org/browse/ISPN-8355

### CODE REVIEW

**Comment by wburns** [comment]
Have to wait for CI to verify it works all the way down the modules.

**Comment by gustavonalle** [comment]
Needs rebase to be able to run CI

**Comment by wburns** [comment]
Rebased, waiting on CI again.

**Comment by anistor** [comment]
Actually no, this does not need manual rebase. I had a compile error but it was my fault. All fine now.

**Comment by wburns** [comment]
Now that encoder changes are on 9.1.x the PR integrates cleanly. Have to still wait on CI though.

**Comment by wburns** [comment]
CI all passed http://ci.infinispan.org/job/Infinispan/job/PR-5490/5/

**Pull request merged**
