### PR TITLE
ISPN-12257 RemoteSpringSessionTest.testCreatingSessionWhenUsingREST

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-12257

Use both the "allowlist" and the "whitelist" properties in
AbstractRemoteCacheManagerFactory.initializeMarshallingProperties()

### CODE REVIEW

**Review by karesti — APPROVED** [review]

**Comment by karesti** [comment]
@danberindei spring tests are failing

**Comment by danberindei** [comment]
I shouldn't have committed the `ClassAllowList` change, I was probably trying to switch between IntelliJ windows with Alt+` but typed only ` and it ended up in the file. I pushed an update that should fix the commons tests and the spring tests.

**Comment by karesti** [comment]
@danberindei these two tests started failing with the change, didn't they ?
SpringRemoteCacheManagerFactoryBeanTest
InfinispanRemoteCacheManagerFactoryBeanTest

**Review by karesti — CHANGES_REQUESTED** [review]
changes fix the test but impact other tests

**Comment by danberindei** [comment]
@karesti yeah, the existing code had a special case to avoid using a `HashSet` when there was no user customization. I removed the special case and the `HashSet` changed the order of the regular expressions. Fixed by using a `LinkedHashSet` instead.

The thread leaks were not separate failures, the test just doesn't clean up properly after a failure. I didn't try to fix that.

**Pull request merged**
