### PR TITLE
ISPN-5327 Increase socket timeout to avoid random test failures

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.jboss.org/browse/ISPN-5327

### CODE REVIEW

**Comment by vjuranek** [comment]
Just found out this is being solved in PR #3325

**Comment by galderz** [comment]
Yeah, and increasing timeouts would have no effect here.

**Comment by vjuranek** [comment]
@galderz it does - basically it waits for the thread to be wake up and thus avoid timeout

**Comment by galderz** [comment]
@vjuranek It might have worked in your tests but eventually it would fail again no matter how big the timeout was because the issue has nothing to do with the timeout length. The issue was caused because the `cache.put` after receiving timeout would never be processed as a result of not having enough threads to deal with the issue. I've added some TRACE logs to [ISPN-5314](https://issues.jboss.org/browse/ISPN-5314) that show the issue clearly.

**Comment by vjuranek** [comment]
got it - thanks for explanation @galderz !

**Pull request closed without merging**
