### PR TITLE
ISPN-10787 Xstream WARNING printed when starting the server

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-10787

### CODE REVIEW

**Comment by ryanemerson** [comment]
@gustavonalle I just built locally and I'm still getting:

```java
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/remerson/workspace/RedHat/infinispan/infinispan/server/runtime/target/infinispan-server-10.0.0-SNAPSHOT/lib/xstream-1.4.11.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

**Comment by gustavonalle** [comment]
Let me check

**Comment by gustavonalle** [comment]
Let's wait CI

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
