### PR TITLE
ISPN-11573 Remove CacheContainerAdmin.AdminFlag.PERMANENT

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-11573

### CODE REVIEW

**Comment by karesti** [comment]
ops I merged without seeing that you requested Tristan

**Comment by ryanemerson** [comment]
No worries that's what `git revert` is for :smile:

**Comment by tristantarrant** [comment]
Ehm, this was not ready for removal

**Comment by ryanemerson** [comment]
> Ehm, this was not ready for removal

Why? It was deprecated in 10.0

**Comment by karesti** [comment]
oops

**Pull request merged**
