### PR TITLE
ISPN-6152 Move the jdk8backported package down one level

### PR DESCRIPTION
**Pull request by wburns**
* Removed the package entirely
* Added upgrade documentation

https://issues.jboss.org/browse/ISPN-6152

### CODE REVIEW

**Comment by pruivo** [comment]
@wburns error in checkstyle:
```
[06:01:33][Step 2/5] /opt/buildAgent/work/e7918bceb48c007e/commons/src/main/java/org/infinispan/commons/util/AbstractEntrySizeCalculatorHelper.java:3:1: error: Redundant import from the same package - org.infinispan.commons.util.EntrySizeCalculator.
```

**Comment by wburns** [comment]
Sad that IntelliJ refactoring didn't do that :/

**Comment by wburns** [comment]
Removed import

**Comment by pruivo** [comment]
CI looks good. integrated! thanks @wburns

**Pull request merged**
