### PR TITLE
ISPN-7525 Fixed PreferConsistencyStrategyTest

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/ISPN-7525

See https://github.com/infinispan/infinispan/pull/4871#discussion_r102774407 for more info.

### CODE REVIEW

**Comment by danberindei** [comment]
Integrated, thanks Sebastian!

**Comment by danberindei** [comment]
@slaskawi This looks good, but looking at the JIRA description I don't think it tests the scenario when the coordinator has a newer topology...

**Comment by ryanemerson** [comment]
@danberindei Are we keeping this PR open so that @slaskawi can push an additional commit? I see that the original commit is already in maser https://github.com/infinispan/infinispan/commit/2e38a210bbcdeb58d2555330071aa9a49cec43b5

**Comment by slaskawi** [comment]
Yes, I will push additional fix

pt., 10.03.2017, 10:52 użytkownik Ryan Emerson <notifications@github.com>
napisał:

**Comment by slaskawi** [comment]
hahahha I think @danberindei accidentally pushed it :) Let me close this one and open another PR :)

**Pull request closed without merging**
