### PR TITLE
Ignore randomly failing Hibernate Cache tests

### PR DESCRIPTION
**Pull request by galderz**
https://issues.jboss.org/browse/ISPN-8026
https://issues.jboss.org/browse/ISPN-8027
~https://issues.jboss.org/browse/ISPN-8107~
~https://issues.jboss.org/browse/ISPN-8108~
https://issues.jboss.org/browse/ISPN-8114

### CODE REVIEW

**Comment by tristantarrant** [comment]
I just saw a couple more in this build org.infinispan.test.hibernate.cache.functional.cluster.NaturalIdInvalidationTest.testAll[transactional, INVALIDATION_SYNC]
org.infinispan.test.hibernate.cache.functional.cluster.NaturalIdInvalidationTest.testAll[read-only, INVALIDATION_SYNC]

**Comment by tristantarrant** [comment]
And yet another http://ci.infinispan.org/job/Infinispan/job/PR-5293/15/testReport/junit/org.infinispan.test.hibernate.cache.collection/CollectionRegionAccessStrategyTest/testRemove_JTA__DIST_SYNC_AccessType_read_write__/

**Comment by galderz** [comment]
One more here: http://ci.infinispan.org/job/Infinispan/job/PR-5299/11/testReport/junit/org.infinispan.test.hibernate.cache.query/QueryRegionImplTest/testEvict_non_JTA__INVALIDATION_SYNC_AccessType_transactional__/

**Comment by galderz** [comment]
@tristantarrant Updated PR

**Comment by tristantarrant** [comment]
Thanks @galderz

**Pull request merged**
