### PR TITLE
ISPN-5606 Add a dependency to the web management console

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5606

### CODE REVIEW

**Comment by wburns** [comment]
@vblagoje this seems all good to you?

**Comment by danberindei** [comment]
@tristantarrant Looks like I'm not qualified to review this, I've built server/integration/build but for some reason the welcome page looks the same as before :)

**Comment by tristantarrant** [comment]
Port 9990?

**Comment by tristantarrant** [comment]
You need to connect to http://localhost:9990 and it will show the page instructing you to create an admin user. Once that is done it should show the main console login page. The console itself only works for domain mode atm.

**Comment by danberindei** [comment]
Integrated, thanks Tristan!

Looks like I was doing the right steps, just in the wrong build directory (and with an old version of the server) :)

**Pull request closed without merging**
