### PR TITLE
ISPN-5258 Upgrade to Hibernate Search 5.1.1.Final, Apache Lucene 4.10.4

### PR DESCRIPTION
**Pull request by Sanne**
- https://issues.jboss.org/browse/ISPN-5258

### CODE REVIEW

**Comment by danberindei** [comment]
@Sanne I take it this should go in 7.2.0.Beta1?

**Comment by tristantarrant** [comment]
Yes, @sanne told me that was his intention

**Comment by Sanne** [comment]
Yes please merge it before the release!

**Comment by Sanne** [comment]
FYI, we're in synch now:
https://issues.jboss.org/browse/WFLY-4428

**Comment by gustavonalle** [comment]
Looking

**Comment by danberindei** [comment]
New failures in InfinispanQueryIT: http://ci.infinispan.org/viewLog.html?buildId=24327&buildTypeId=bt9&guest=1

**Comment by Sanne** [comment]
@danberindei right, there's an issue in version definitions of the modules. @gustavonalle just identified it, a fix is coming in some minutes.

**Comment by gustavonalle** [comment]
Fixed module alias and pushed, thanks @Sanne !

**Comment by Sanne** [comment]
great :+1: thanks!

**Pull request closed without merging**
