### PR TITLE
ISPN-7947  Remove META-INF/services resource files from server wherever possible and replace them with @MetaInfServices annotation

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-7947

### CODE REVIEW

**Comment by tristantarrant** [comment]
@anistor what's still missing here ?

**Comment by tristantarrant** [comment]
Rebase please

**Comment by rvansa** [comment]
+1, besides the test failures.

**Comment by slaskawi** [comment]
+1 from me also. Please tidy it up, squash whatever needs squashing and let's get it in.

**Comment by rvansa** [comment]
@anistor how's this going?

**Comment by tristantarrant** [comment]
Closing this. Please reopen when it's ready

**Pull request closed without merging**
