### PR TITLE
ISPN-4797 Use getAll for retrieving query results - fix tests

### PR DESCRIPTION
**Pull request by anistor**
Jira: https://issues.jboss.org/browse/ISPN-4797

All test failures should be gone now.

### CODE REVIEW

**Comment by wburns** [comment]
I believe this will work for local mode, but for a remote cache I am more than certain the LinkedHashMap

**Comment by wburns** [comment]
Whoops wrong button

**Comment by wburns** [comment]
The CI has a bunch of failures in hotrod client (not quite sure they are legit though).  Interestingly though when I ran this locally I got a ton in the query module (ran master just before and didn't get them).  It seems like a sorting issue though.

```
QueryPhrasesTest.testBooleanQueriesShouldNot:147 null
  CompatModeQueryDslConditionsTest>QueryDslConditionsTest.testContainsAny1:761 expected:<1> but was:<2>
  CompatModeQueryDslConditionsTest>QueryDslConditionsTest.testNot9:616 expected:<[M]an> but was:<[Wom]an>
  CompatModeQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery1:855 expected:<[John]> but was:<[Spider]>
  CompatModeQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery16:1139 expected:<Expensive shoes 2[0]> but was:<Expensive shoes 2[2]>
  CompatModeQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery18:1173 expected:<[Birthday pres]ent> but was:<[Feb. rent paym]ent>
  CompatModeQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery2:871 expected:<[John]> but was:<[Spider]>
  CompatModeQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery28:1332 expected:<2> but was:<3>
  CompatModeQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery3:913 expected:<[John]> but was:<[Spider]>
  CompatModeQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery4With2SortingOptions:948 expected:<[M]an> but was:<[Wom]an>
  CompatModeQueryDslConditionsTest>QueryDslConditionsTest.testSortByDate:897 expected:<3> but was:<1>
  QueryDslIterationTest.testOrderByAsc:66->checkNameOrder:174 null
  QueryDslIterationTest.testOrderByDesc:79->checkSurnameOrder:186 null
  IspnDirQueryDslIterationTest>QueryDslIterationTest.testOrderByAsc:66->QueryDslIterationTest.checkNameOrder:174 null
  IspnDirQueryDslIterationTest>QueryDslIterationTest.testOrderByDesc:79->QueryDslIterationTest.checkSurnameOrder:186 null
  IspnDirQueryDslConditionsTest>QueryDslConditionsTest.testContainsAny1:761 expected:<1> but was:<2>
  IspnDirQueryDslConditionsTest>QueryDslConditionsTest.testNot9:616 expected:<[M]an> but was:<[Wom]an>
  IspnDirQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery1:855 expected:<[John]> but was:<[Spider]>
  IspnDirQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery16:1139 expected:<Expensive shoes 2[0]> but was:<Expensive shoes 2[2]>
  IspnDirQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery18:1173 expected:<[Birthday pres]ent> but was:<[Feb. rent paym]ent>
  IspnDirQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery2:871 expected:<[John]> but was:<[Spider]>
  IspnDirQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery28:1332 expected:<2> but was:<3>
  IspnDirQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery3:913 expected:<[John]> but was:<[Spider]>
  IspnDirQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery4With2SortingOptions:948 expected:<[M]an> but was:<[Wom]an>
  IspnDirQueryDslConditionsTest>QueryDslConditionsTest.testSortByDate:897 expected:<3> but was:<1>
  ClusteredQueryDslConditionsTest>QueryDslConditionsTest.testContainsAny1:761 expected:<1> but was:<2>
  ClusteredQueryDslConditionsTest>QueryDslConditionsTest.testNot9:616 expected:<[M]an> but was:<[Wom]an>
  ClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery1:855 expected:<[John]> but was:<[Spider]>
  ClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery16:1139 expected:<Expensive shoes 2[0]> but was:<Expensive shoes 2[2]>
  QueryDslConditionsTest.testContainsAny1:761 expected:<1> but was:<2>
  ClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery18:1173 expected:<[Birthday pres]ent> but was:<[Feb. rent paym]ent>
  ClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery2:871 expected:<[John]> but was:<[Spider]>
  ClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery28:1332 expected:<2> but was:<3>
  ClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery3:913 expected:<[John]> but was:<[Spider]>
  ClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery4With2SortingOptions:948 expected:<[M]an> but was:<[Wom]an>
  ClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSortByDate:897 expected:<3> but was:<1>
  QueryDslConditionsTest.testNot9:616 expected:<[M]an> but was:<[Wom]an>
  QueryDslConditionsTest.testSampleDomainQuery1:855 expected:<[John]> but was:<[Spider]>
  FilesystemQueryDslIterationTest>QueryDslIterationTest.testOrderByAsc:66->QueryDslIterationTest.checkNameOrder:174 null
  QueryDslConditionsTest.testSampleDomainQuery16:1139 expected:<Expensive shoes 2[0]> but was:<Expensive shoes 2[2]>
  FilesystemQueryDslIterationTest>QueryDslIterationTest.testOrderByDesc:79->QueryDslIterationTest.checkSurnameOrder:186 null
  QueryDslConditionsTest.testSampleDomainQuery18:1173 expected:<[Birthday pres]ent> but was:<[Feb. rent paym]ent>
  QueryDslConditionsTest.testSampleDomainQuery2:871 expected:<[John]> but was:<[Spider]>
  QueryDslConditionsTest.testSampleDomainQuery28:1332 expected:<2> but was:<3>
  QueryDslConditionsTest.testSampleDomainQuery3:913 expected:<[John]> but was:<[Spider]>
  QueryDslConditionsTest.testSampleDomainQuery4With2SortingOptions:948 expected:<[M]an> but was:<[Wom]an>
  QueryDslConditionsTest.testSortByDate:897 expected:<3> but was:<1>
  TxClusteredQueryDslConditionsTest>QueryDslConditionsTest.testContainsAny1:761 expected:<1> but was:<2>
  TxClusteredQueryDslConditionsTest>QueryDslConditionsTest.testNot9:616 expected:<[M]an> but was:<[Wom]an>
  TxClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery1:855 expected:<[John]> but was:<[Spider]>
  TxClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery16:1139 expected:<Expensive shoes 2[0]> but was:<Expensive shoes 2[2]>
  TxClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery18:1173 expected:<[Birthday pres]ent> but was:<[Feb. rent paym]ent>
  TxClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery2:871 expected:<[John]> but was:<[Spider]>
  TxClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery28:1332 expected:<2> but was:<3>
  TxClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery3:913 expected:<[John]> but was:<[Spider]>
  TxClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery4With2SortingOptions:948 expected:<[M]an> but was:<[Wom]an>
  TxClusteredQueryDslConditionsTest>QueryDslConditionsTest.testSortByDate:897 expected:<3> but was:<1>
  CompatModeLocalCacheTest>LocalCacheTest.testSetSort:303 null
  LocalCacheTest.testSetSort:303 null
  LocalCachePerfIspnDirConfTest>LocalCacheTest.testSetSort:303 null
  LocalCachePerfProgrammaticConfTest>LocalCacheTest.testSetSort:303 null
  MarshalledValueQueryTest>LocalCacheTest.testSetSort:303 null
  LocalCacheAsyncCacheStoreTest>LocalCacheTest.testSetSort:303 null
  FilesystemQueryDslConditionsTest>QueryDslConditionsTest.testContainsAny1:761 expected:<1> but was:<2>
  FilesystemQueryDslConditionsTest>QueryDslConditionsTest.testNot9:616 expected:<[M]an> but was:<[Wom]an>
  FilesystemQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery1:855 expected:<[John]> but was:<[Spider]>
  FilesystemQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery16:1139 expected:<Expensive shoes 2[0]> but was:<Expensive shoes 2[2]>
  FilesystemQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery18:1173 expected:<[Birthday pres]ent> but was:<[Feb. rent paym]ent>
  FilesystemQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery2:871 expected:<[John]> but was:<[Spider]>
  FilesystemQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery28:1332 expected:<2> but was:<3>
  FilesystemQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery3:913 expected:<[John]> but was:<[Spider]>
  FilesystemQueryDslConditionsTest>QueryDslConditionsTest.testSampleDomainQuery4With2SortingOptions:948 expected:<[M]an> but was:<[Wom]an>
  FilesystemQueryDslConditionsTest>QueryDslConditionsTest.testSortByDate:897 expected:<3> but was:<1>
  LocalCacheFSDirectoryTest>LocalCacheTest.testSetSort:303 null
  LocalCachePerformantConfTest>LocalCacheTest.testSetSort:303 null
```

**Comment by anistor** [comment]
Those failures happen on master too. May have been introduced by Sanne's module refactoring.

**Comment by wburns** [comment]
Ah i must have missed the update before i ran.

**Comment by tristantarrant** [comment]
Could it be fixed by https://github.com/infinispan/infinispan/pull/3429?

**Comment by anistor** [comment]
Yes, vjuranek's pr fixes it.

**Comment by wburns** [comment]
According to @Sanne & @gustavonalle the nulls were supposed to be ignored.  Also I am not quite sure how https://github.com/infinispan/infinispan/pull/3429 was supposed to fix failures in the query module when those are in the server module, unless query module runs a server in it, which seems very odd that it would.  I will try running it locally here again, maybe I am missing something on my own machine.

**Comment by wburns** [comment]
Pulling...

**Comment by anistor** [comment]
Not sure why you had test failures in query module when running locally. CI only had failures in hot rod client and server integration tests. These were indeed caused by the missing jandex.

**Comment by wburns** [comment]
Integrated into master, thanks @anistor.

Yeah I was unable to reproduce the query issues again today, may have been a compilation issue when switching branches, not quite sure.

**Pull request closed without merging**
