### PR TITLE
ISPN-5306 Eviction should allow for long size configuration

### PR DESCRIPTION
**Pull request by wburns**
* Changed eviction to use long instead of int

https://issues.jboss.org/browse/ISPN-5306

### CODE REVIEW

**Comment by tristantarrant** [comment]
This is missing the server counterpart

**Comment by pruivo** [comment]
@wburns is it safe for our size operation? I mean, if you put more the ```Integer.MAX_INT``` elements in the cache and you invoke ```size()```, it will work?

**Comment by tristantarrant** [comment]
According to the ConcurrentHashMap contract:  If the map contains more than Integer.MAX_VALUE elements, returns Integer.MAX_VALUE.

**Comment by wburns** [comment]
@pruivo @tristantarrant Yes that is what the contract states and it is currently what we do https://github.com/infinispan/infinispan/blob/master/core/src/main/java/org/infinispan/commands/read/SizeCommand.java#L52

**Comment by wburns** [comment]
@tristantarrant Thanks for catching the server part, let me look into it.

**Comment by wburns** [comment]
Added in server components

**Comment by tristantarrant** [comment]
Pushed

**Pull request closed without merging**
