### PR TITLE
ISPN-15061 JDK 17 Baseline

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-15061

### CODE REVIEW

**Comment by wburns** [comment]
CI failed.. looks like it is using graalvm for 11 instead of 17 or 21? /cc @ryanemerson

**Comment by tristantarrant** [comment]
I have fixed the issue with the CLI module: it was using the default `java` executable found in the path instead of the one selected by the `Jenkinsfile` rules

**Comment by tristantarrant** [comment]
This is ready to be merged

**Comment by wburns** [comment]
Integrated into main, thanks @tristantarrant !

**Pull request merged**
