### PR TITLE
ISPN-13260 Docs - remove redundant backslash from formulas in the tuning guide

### PR DESCRIPTION
**Pull request by dvagnero**
Minor fix, remove redundant backslash from formulas in the tuning doc. (The characters aren't converted into symbols, escaping isn't necessary)

### CODE REVIEW

**Review by oraNod — COMMENTED** [review]
Thanks @dvagnero This is a weird one. In the Query docs you need to escape `<=` or asciidoctor treats it as a symbol. Here's the topic: https://raw.githubusercontent.com/infinispan/infinispan/main/documentation/src/main/asciidoc/topics/ref_query_ickle_syntax.adoc

You can see it in the table. I think that's why I added the escape here too but I think the difference is the codeblock.

Anyway, could you please update your commit message to include the associated Jira issue? 

ISPN-13260 - It's such a minor thing I don't think we need a dedicated Jira issue but we should follow the format like "ISPN-XXXX <meaningful change summary>" FYI, we'll also need to backport to 13.x.

Thanks!

**Comment by oraNod** [comment]
I also updated the review title to include that Jira issue for the PR queue.

**Comment by dvagnero** [comment]
Thanks @oraNod

**Review by oraNod — APPROVED** [review]
LGTM, thanks @dvagnero

**Pull request merged**
