### PR TITLE
ISPN-14987 SIGSEGV and memory corruption with persistent cache backed…

### PR DESCRIPTION
**Pull request by jabolina**
… by RocksDB

https://issues.redhat.com/browse/ISPN-14987

The bug was intricate, and I am unsure how we can reliably reproduce it in the tests. The issue boils down to the fact the close in the Flowable was invoked concurrently with the next in the RocksEntryIterator. Any operation in the RocksIterator after the close would crash the JVM.

The fix was to synchronize access to the iterator, and make checking if the iterator is valid and read the entry atomic.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#2](https://ci.infinispan.org/job/Infinispan/job/PR-11112/2/):
```
quay.io/infinispan-test/server:PR-11112
```

**Comment by jabolina** [comment]
Updated.

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !

**Comment by wburns** [comment]
@jabolina Think we want a 14.0.x branch as well.

**Pull request merged**
