### PR TITLE
ISPN-15079 Remove old code from CommandAckCollector

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.redhat.com/browse/ISPN-15079

### CODE REVIEW

**Review by karesti — APPROVED** [review]

**Comment by tristantarrant** [comment]
I think there is one related failure:
```
java.lang.AssertionError
	at org.infinispan.util.concurrent.CommandAckCollector$SegmentBasedCollector.backupAck(CommandAckCollector.java:390)
	at org.infinispan.util.concurrent.CommandAckCollector.backupAck(CommandAckCollector.java:144)
	at org.infinispan.remoting.inboundhandler.TrianglePerCacheInboundInvocationHandler.sendBackupAck(TrianglePerCacheInboundInvocationHandler.java:193)
	at org.infinispan.remoting.inboundhandler.TrianglePerCacheInboundInvocationHandler$1.afterInvoke(TrianglePerCacheInboundInvocationHandler.java:226)
	at org.infinispan.remoting.inboundhandler.BaseBlockingRunnable.invokedComplete(BaseBlockingRunnable.java:133)
	at org.infinispan.remoting.inboundhandler.BaseBlockingRunnable.invoke(BaseBlockingRunnable.java:122)
	at org.infinispan.remoting.inboundhandler.BaseBlockingRunnable.runAsync(BaseBlockingRunnable.java:79)
	at org.infinispan.remoting.inboundhandler.BaseBlockingRunnable.run(BaseBlockingRunnable.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by pruivo** [comment]
@tristantarrant weird, it does not fail locally. I have already run it 3 times and nothing... let me dig into it.

**Comment by karesti** [comment]
@pruivo needs rebase to be built

**Review by wburns — APPROVED** [review]
LGTM

**Comment by wburns** [comment]
Integrated into main, thanks @pruivo !

**Pull request merged**
