### PR TITLE
ISPN-11736 Add blockhound to counter module

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-11736

### CODE REVIEW

**Comment by wburns** [comment]
No failures when I ran it.

**Comment by karesti** [comment]
@wburns could be related ?
https://ci.infinispan.org/job/Infinispan/job/PR-8251/2/testReport/junit/org.infinispan.counter/RestartCounterTest/Blocking/

**Comment by wburns** [comment]
Yes, that is related. Odd I didn't get it in my local run. Guessing it happens sporadically. I will fix it though.

**Comment by wburns** [comment]
Should be fixed now.

**Pull request merged**
