### PR TITLE
ISPN-5683 Fix some checkstyle violations

### PR DESCRIPTION
**Pull request by anistor**
* no empty statements
* no StringBuffer usages

Please do not close the issue yet.

### CODE REVIEW

**Comment by slaskawi** [comment]
LGTM, waiting for CI and integrating.

**Comment by anistor** [comment]
Rebased + more fixes. The scala removal introiduced some more violations but are fixed now.

**Comment by anistor** [comment]
Green!!! The perfect alignment of planets.

**Comment by slaskawi** [comment]
Pulling

**Comment by slaskawi** [comment]
Integrated. Thanks!

**Pull request merged**
