### PR TITLE
ISPN-11317 Increase Time To Live for UDP protocol

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.redhat.com/browse/ISPN-11317

### CODE REVIEW

**Comment by diegolovison** [comment]
run performance tests please
library
cs

**Comment by diegolovison** [comment]
run performance tests please
library

**Comment by diegolovison** [comment]
run performance tests please
cs

**Comment by diegolovison** [comment]
run performance tests please
cs

**Comment by danberindei** [comment]
@diegolovison we do not recommend running an Infinispan cluster over a WAN with UDP, so I'm not sure why this configuration change is needed. It definitely won't make a difference in our test cluster, where all the machines are just 1 hop away.

**Comment by diegolovison** [comment]
@danberindei got the point. Thanks

**Pull request closed without merging**
