### PR TITLE
ISPN-5500 direct init of tmpDirs in LevelDB tests, removed @BeforeClass

### PR DESCRIPTION
**Pull request by tsykora**
There is more info in JIRA desc.

https://issues.jboss.org/browse/ISPN-5500

### CODE REVIEW

**Comment by danberindei** [comment]
@tsykora Are you sure the problem wasn't the missing `alwaysRun = true` from some of these `@BeforeClass` annotations?

**Comment by tsykora** [comment]
@danberindei thank you for a suggestion! I will definitely give it a shot if I find machine where this is failing (more constrantly) -- to se whether this is our issue. I will let you know.

But what I remember from last time, I was trying that, built my own ispn snapshot and it didn't help. I want to retry to make sure there wasn't some mistake at different place.

**Comment by tsykora** [comment]
@danberindei I have found a machine where this is failing constantly. Added alwaysRun=true on respective places but unfortunately it didn't help. 

Direct initialization in parent/original test classes PR works perfectly though. Re-verified right now using my own snapshot and on dedicated machine.

**Comment by danberindei** [comment]
@tsykora I didn't need convincing that your fix works... I just wanted to find why `@BeforeClass/Method` don't work for you, as we use them a lot in our tests.

**Comment by danberindei** [comment]
@tsykora Integrating, there's a bug for this in TestNG: https://github.com/cbeust/testng/issues/420

**Comment by danberindei** [comment]
Integrated, thanks Tomas!

**Pull request closed without merging**
