### PR TITLE
ISPN-12688 Support spring session embedded with protostream

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-12688

Depends on #9031 

* Create MapSession protostream adapter.
* Allow session attribute values to be marshalled
  either with Protostream or with Java Serialization.
* Use a raw marshaller to handle the serialization.
* Add Spring classes to allow list.
* Add spring-session test using protostream encoding
  (EmbeddedProtostreamSpringSessionTest).

### CODE REVIEW

**Review by karesti — CHANGES_REQUESTED** [review]
needs rebase but LGTM!!

**Comment by danberindei** [comment]
Rebased

**Comment by ryanemerson** [comment]
@danberindei Overall LGTM but something isn't right with classloading and the marshallers.

```
Caused by: java.lang.NoClassDefFoundError: org/springframework/session/MapSession
	at org.infinispan.spring.common.session.MapSessionProtoAdapter$___Marshaller_48803e1f63a1a9e51a9233b15e4119cb175205331f293f7d77e3cdbdf04f092b.getJavaClass(MapSessionProtoAdapter$___Marshaller_48803e1f63a1a9e51a9233b15e4119cb175205331f293f7d77e3cdbdf04f092b.java:27)
	at org.infinispan.protostream.impl.SerializationContextImpl.makeMarshallerDelegate(SerializationContextImpl.java:215)
	at org.infinispan.protostream.impl.SerializationContextImpl.registerMarshaller(SerializationContextImpl.java:203)
	at org.infinispan.spring.common.PersistenceContextInitializerImpl.registerMarshallers(PersistenceContextInitializerImpl.java:56)
	at org.infinispan.marshall.protostream.impl.SerializationContextRegistryImpl$MarshallerContext.lambda$update$0(SerializationContextRegistryImpl.java:148)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.infinispan.marshall.protostream.impl.SerializationContextRegistryImpl$MarshallerContext.update(SerializationContextRegistryImpl.java:146)
	at org.infinispan.marshall.protostream.impl.SerializationContextRegistryImpl.lambda$addContextInitializer$3(SerializationContextRegistryImpl.java:85)
	at org.infinispan.marshall.protostream.impl.SerializationContextRegistryImpl.update(SerializationContextRegistryImpl.java:105)
	at org.infinispan.marshall.protostream.impl.SerializationContextRegistryImpl.addContextInitializer(SerializationContextRegistryImpl.java:85)
	at org.infinispan.spring.embedded.SpringEmbeddedModule.cacheManagerStarting(SpringEmbeddedModule.java:35)
	at org.infinispan.factories.GlobalComponentRegistry.modulesManagerStarting(GlobalComponentRegistry.java:270)
	at org.infinispan.factories.GlobalComponentRegistry.access$000(GlobalComponentRegistry.java:63)
	at org.infinispan.factories.GlobalComponentRegistry$ModuleInitializer.start(GlobalComponentRegistry.java:360)
	at org.infinispan.factories.CorePackageImpl$11.start(CorePackageImpl.java:173)
	at org.infinispan.factories.CorePackageImpl$11.start(CorePackageImpl.java:171)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:604)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:595)
	at org.infinispan.
```

**Comment by karesti** [comment]
> @danberindei Overall LGTM but something isn't right with classloading and the marshallers which is breaking the testsuite.
> 
> ```
> Caused by: java.lang.NoClassDefFoundError: org/springframework/session/MapSession
> 	at org.infinispan.spring.common.session.MapSessionProtoAdapter$___Marshaller_48803e1f63a1a9e51a9233b15e4119cb175205331f293f7d77e3cdbdf04f092b.getJavaClass(MapSessionProtoAdapter$___Marshaller_48803e1f63a1a9e51a9233b15e4119cb175205331f293f7d77e3cdbdf04f092b.java:27)
> 	at org.infinispan.protostream.impl.SerializationContextImpl.makeMarshallerDelegate(SerializationContextImpl.java:215)
> 	at org.infinispan.protostream.impl.SerializationContextImpl.registerMarshaller(SerializationContextImpl.java:203)
> 	at org.infinispan.spring.common.PersistenceContextInitializerImpl.registerMarshallers(PersistenceContextInitializerImpl.java:56)
> 	at org.infinispan.marshall.protostream.impl.SerializationContextRegistryImpl$MarshallerContext.lambda$update$0(SerializationContextRegistryImpl.java:148)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> 	at org.infinispan.marshall.protostream.impl.SerializationContextRegistryImpl$MarshallerContext.update(SerializationContextRegistryImpl.java:146)
> 	at org.infinispan.marshall.protostream.impl.SerializationContextRegistryImpl.lambda$addContextInitializer$3(SerializationContextRegistryImpl.java:85)
> 	at org.infinispan.marshall.protostream.impl.SerializationContextRegistryImpl.update(SerializationContextRegistryImpl.java:105)
> 	at org.infinispan.marshall.protostream.impl.SerializationContextRegistryImpl.addContextInitializer(SerializationContextRegistryImpl.java:85)
> 	at org.infinispan.spring.embedded.SpringEmbeddedModule.cacheManagerStarting(SpringEmbeddedModule.java:35)
> 	at org.infinispan.factories.GlobalComponentRegistry.modulesManagerStarting(GlobalComponentRegistry.java:270)
> 	at org.infinispan.factories.GlobalComponentRegistry.access$000(GlobalComponentRegistry.java:63)
> 	at org.infinispan.factories.GlobalComponentRegistry$ModuleInitializer.start(GlobalComponentRegistry.java:360)
> 	at org.infinispan.factories.CorePackageImpl$11.start(CorePackageImpl.java:173)
> 	at org.infinispan.factories.CorePackageImpl$11.start(CorePackageImpl.java:171)
> 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:604)
> 	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:595)
> 	at org.infinispan.
> ```

yep, we discussed it off github!

**Comment by karesti** [comment]
@danberindei still failing just in case

**Review by karesti — APPROVED** [review]

**Comment by karesti** [comment]
@danberindei nice work, you are the best!

**Pull request merged**
