### PR TITLE
ISPN-5036 Embedded and remote uber-jar tests

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.jboss.org/browse/ISPN-5036

Remote uber-jar CDI test fails due to https://issues.jboss.org/browse/ISPN-5092
Surpasses PR #3152, the commit in PR #3152 is included in this PR.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8178/vjuranek:ISPN-5036](http://ci.infinispan.org/viewLog.html?buildId=22529&buildTypeId=bt9&guest=1) for 7de301e24808421338e72009cacd0fa8661d0635
Tests: 11230, 4 failed (2 new), 23 ignored. Build time: 01:53:05

Failed tests detected
* (new) TestSuite: org.infinispan.statetransfer.StateTransferReplicationQueueTest.testStateTransferWithNodeRestartedAndBusyNonTx


* (new) org.infinispan.server.test.query.ManualIndexingIT.testManualIndexing


* (since 17-Dec-2014) org.infinispan.all.remote.RemoteCacheCDITest.testDefaultCache


* (since 17-Dec-2014) org.infinispan.all.remote.RemoteCacheCDITest.testRemoteCacheManager

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8200/vjuranek:ISPN-5036](http://ci.infinispan.org/viewLog.html?buildId=22562&buildTypeId=bt9&guest=1) for 7de301e24808421338e72009cacd0fa8661d0635
Tests: 11230, 3 failed (1 new), 23 ignored. Build time: 02:37:27

Failed tests detected
* (new) TestSuite: org.infinispan.notifications.cachelistener.cluster.ClusterListenerReplTest.testPrimaryOwnerGoesDownAfterBackupRaisesEvent


* (since 17-Dec-2014) org.infinispan.all.remote.RemoteCacheCDITest.testDefaultCache


* (since 17-Dec-2014) org.infinispan.all.remote.RemoteCacheCDITest.testRemoteCacheManager

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8213/vjuranek:ISPN-5036](http://ci.infinispan.org/viewLog.html?buildId=22580&buildTypeId=bt9&guest=1) for 7de301e24808421338e72009cacd0fa8661d0635
Tests: 11229, 66 failed (64 new), 23 ignored. Build time: 02:29:40

Failed tests detected
* (new) TestSuite: org.infinispan.partitionhandling.NumOwnersNodeStopInSequenceTest.testNodeCrashedBeforeStFinished7


* (new) TestSuite: org.infinispan.client.hotrod.query.MultiHotRodServerIspnDirReplQueryTest.testAttributeQuery


* (new) TestSuite: org.infinispan.client.hotrod.query.MultiHotRodServerIspnDirReplQueryTest.testEmbeddedAttributeQuery


* (new) TestSuite: org.infinispan.client.hotrod.query.MultiHotRodServerIspnDirReplQueryTest.testProjections


* (new) TestSuite: org.infinispan.xsite.statetransfer.DistSyncTwoPhasesWriteSkewTxStateTransferTest.testReplaceOperationAfterState


* (new) TestSuite: org.infinispan.xsite.statetransfer.failures.SiteConsumerTopologyChangeTest.testJoinDuringXSiteST


* (new) TestSuite: org.infinispan.xsite.statetransfer.failures.SiteConsumerTopologyChangeTest.testSiteMasterLeaveDuringXSiteST


* (new) TestSuite: org.infinispan.xsite.statetransfer.failures.SiteConsumerTopologyChangeTest.testXSiteDuringJoin


* (new) TestSuite: org.infinispan.xsite.statetransfer.failures.StateTransferLinkFailuresTest.testLinkBrokenDuringStateTransfer


* (new) TestSuite: org.infinispan.xsite.statetransfer.failures.SiteProviderTopologyChangeTest.testCoordinatorLeaveAfterXSiteST


* (new) TestSuite: org.infinispan.xsite.statetransfer.failures.SiteProviderTopologyChangeTest.testCoordinatorLeaveDuringXSiteST

... 56 more


Error message is logged

Process exited with code 1

Build duration (secs) is too large: 8957

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8253/vjuranek:ISPN-5036](http://ci.infinispan.org/viewLog.html?buildId=22678&buildTypeId=bt9&guest=1) for 7de301e24808421338e72009cacd0fa8661d0635
Tests: 11232, 3 failed (1 new), 23 ignored. Build time: 01:41:53

Failed tests detected
* (new) TestSuite: org.infinispan.statetransfer.ClusterTopologyManagerTest.testClusterRecoveryWithRebalance


* (since 17-Dec-2014) org.infinispan.all.remote.RemoteCacheCDITest.testDefaultCache


* (since 17-Dec-2014) org.infinispan.all.remote.RemoteCacheCDITest.testRemoteCacheManager

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8265/vjuranek:ISPN-5036](http://ci.infinispan.org/viewLog.html?buildId=22697&buildTypeId=bt9&guest=1) for 7de301e24808421338e72009cacd0fa8661d0635
Tests: 11245, 8 failed (6 new), 23 ignored. Build time: 01:42:05

Failed tests detected
* (new) TestSuite: org.infinispan.distexec.DistributedExecutorFailoverTest.testBasicTargetRemoteDistributedCallable


* (new) TestSuite: org.infinispan.interceptors.ConcurrentInterceptorVisibilityTest.testSizeVisibility


* (new) TestSuite: org.infinispan.client.hotrod.near.EagerNearCacheTest.testGetNearCache


* (new) TestSuite: org.infinispan.client.hotrod.near.EagerNearCacheTest.testGetUpdatesNearCache


* (new) TestSuite: org.infinispan.client.hotrod.near.EagerNearCacheTest.testGetVersionedNearCache


* (new) TestSuite: org.infinispan.client.hotrod.near.EagerNearCacheTest.testUpdateNearCache


* (since 17-Dec-2014) org.infinispan.all.remote.RemoteCacheCDITest.testDefaultCache


* (since 17-Dec-2014) org.infinispan.all.remote.RemoteCacheCDITest.testRemoteCacheManager

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8284/vjuranek:ISPN-5036](http://ci.infinispan.org/viewLog.html?buildId=22769&buildTypeId=bt9&guest=1) for 7de301e24808421338e72009cacd0fa8661d0635
Tests: 11247, 4 failed (2 new), 23 ignored. Build time: 02:10:22

Failed tests detected
* (new) TestSuite: org.infinispan.client.hotrod.near.LazyNearCacheTest.testGetVersionedNearCache


* (new) TestSuite: org.infinispan.client.hotrod.near.LazyNearCacheTest.testUpdateNearCache


* (since 17-Dec-2014) org.infinispan.all.remote.RemoteCacheCDITest.testDefaultCache


* (since 17-Dec-2014) org.infinispan.all.remote.RemoteCacheCDITest.testRemoteCacheManager



Error message is logged

Build duration (secs) is too large: 7809

**Comment by galderz** [comment]
@vjuranek Thoughts on @mgencur's comments?

**Comment by tsykora** [comment]
Making this thread live again -- it looks like we are waiting for @tristantarrant to answer @vjuranek comment from 2nd January.

**Comment by tristantarrant** [comment]
The reason why I don't want infinispan-parent as a dependency is that it pulls in a bunch of default test dependencies and their transitives which would pollute the classpath (unless you're extremely careful with the exclusions)

**Comment by vjuranek** [comment]
After discussion with @mgencur and @tsykora we agreed that we shouldn't inherit from parent `pom.xml` and rather keep version directly in this `pom.xml` (not a big risk, as there are basically testing tools dependencies). I've polished `pom.xml` little bit, now is IMHO ready for merge.

**Comment by galderz** [comment]
Two newly added tests are failing:

```
[19:39:59] :		 [org.infinispan:infinispan-remote-it]   testDefaultCache(org.infinispan.all.remote.RemoteCacheCDITest): Exception List with 1 exceptions:(..)
[19:39:59] :		 [org.infinispan:infinispan-remote-it]   testRemoteCacheManager(org.infinispan.all.remote.RemoteCacheCDITest): Exception List with 1 exceptions:(..)
```

**Comment by galderz** [comment]
Closing for the time being

**Comment by tsykora** [comment]
This was failing because of some ambiguous dependencies in infinispan-embedded AND infinispan-remote jars. Digging more deeply...

**Comment by tsykora** [comment]
I see now. Tests are failing because of rejected: https://issues.jboss.org/browse/ISPN-5096 and won't fix: https://issues.jboss.org/browse/ISPN-5092

IIRC remote cache store use case needs both uber-jars at class path. Any ideas?

**Pull request closed without merging**
