### PR TITLE
ISPN-8157 Upgrade maven-surefire-plugin to 2.20

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-8157

### CODE REVIEW

**Comment by danberindei** [comment]
Subject + commit message are wrong, should be 2.20

**Comment by danberindei** [comment]
There are some more direct references to version 2.18.1, e.g. https://github.com/infinispan/infinispan/blob/master/parent/pom.xml#L1561

**Comment by ryanemerson** [comment]
@danberindei I think I have all instances of it now. I'm blaming the naming malfunction it being the end of the day :sleeping:

**Comment by danberindei** [comment]
Integrated, thanks Ryan!

**Pull request merged**
