### PR TITLE
ISPN-15277 Default ConcurrentMap methods should ensure they close Ite…

### PR DESCRIPTION
**Pull request by wburns**
…rators

https://issues.redhat.com/browse/ISPN-15277

Note all methods changed will close the iterator if fully iterated upon, this only ensures it is closed if there was an exception in processing somewhere.

### CODE REVIEW

**Comment by tristantarrant** [comment]
I assume we'll want a backport ?

**Comment by wburns** [comment]
> I assume we'll want a backport ?

I was debating, it only happens on an exception while iterating, so I would say it isn't a huge chance. But I see no harm in doing so.

**Comment by ryanemerson** [comment]
Restarting CI as the last run failed due to a hung SIFS test:

```
[2023-10-27T16:01:58.888Z] [TestSuiteProgress] Test failed: org.infinispan.persistence.sifs.SoftIndexFileStoreRestartTest.clearContent
[2023-10-27T16:01:58.888Z] Dumping threads of process 4121961 to /home/infinispan/workspace/Infinispan_PR-11443/core/threaddump-SoftIndexFileStoreRestartTest-20231027-1201-4121961.log
[2023-10-27T16:01:58.888Z] Interrupted thread testng-SoftIndexFileStoreRestartTest (50).
[2023-10-27T16:02:00.355Z] Killed processes 4121961
```

**Comment by ryanemerson** [comment]
Thanks @wburns

**Pull request merged**
