### PR TITLE
ISPN-12124 OracleTableManager is overly conservative with object name…

### PR DESCRIPTION
**Pull request by wburns**
… max length

https://issues.redhat.com/browse/ISPN-12124
https://issues.redhat.com/browse/ISPN-13973

### CODE REVIEW

**Comment by wburns** [comment]
Put on hold until I think about migration side effects.

**Comment by wburns** [comment]
Looks like the only migration side effect is that there may be an extra index for both segment and timestamp index.

**Comment by tristantarrant** [comment]
One related failure:
```
Error
expected [null] but found [1]
Stacktrace
java.lang.AssertionError: expected [null] but found [1]
	at org.infinispan.tools.store.migrator.MigratorConfigurationTest.testDbPropertiesLoaded(MigratorConfigurationTest.java:222)
	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 23 stack frames
```

**Comment by wburns** [comment]
> One related failure:
> 
> ```
> Error
> expected [null] but found [1]
> Stacktrace
> java.lang.AssertionError: expected [null] but found [1]
> 	at org.infinispan.tools.store.migrator.MigratorConfigurationTest.testDbPropertiesLoaded(MigratorConfigurationTest.java:222)
> 	at org.infinispan.commons.test.TestNGLongTestsHook.run(TestNGLongTestsHook.java:24)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> ... Removed 23 stack frames
> ```

Checking

**Comment by wburns** [comment]
Test should be updated now to ignore the min/max db properties

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
