### PR TITLE
Various upgrades

### PR DESCRIPTION
**Pull request by tristantarrant**
[ISPN-12740](https://issues.redhat.com/browse/ISPN-12740) Netty 4.1.59
[ISPN-12741](https://issues.redhat.com/browse/ISPN-12741) Log4j 2.14.0
[ISPN-12742](https://issues.redhat.com/browse/ISPN-12742) JGroups 4.2.11
[ISPN-12743](https://issues.redhat.com/browse/ISPN-12743) Jackson 2.12.1
[ISPN-12745](https://issues.redhat.com/browse/ISPN-12745) Elytron 1.14.2

### CODE REVIEW

**Review by karesti — APPROVED** [review]

**Comment by karesti** [comment]
@tristantarrant btw, the quarkus issue was not related to the version, but missing dependencies in the quarkus bom

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Comment by pruivo** [comment]
integrated! thanks @tristantarrant !

**Pull request merged**
