### PR TITLE
ISPN-14177 Netty 4.1.82.Final

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14177

### CODE REVIEW

**Comment by ryanemerson** [comment]
Running a second build with "Image Required" so that I can easily test the changes in Openshift.

**Comment by tristantarrant** [comment]
The HTTP/2 issue is verifiable even locally: just uncomment the server identity in `infinispan.xml` and connect with Firefox or Chrome.

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#2](https://ci.infinispan.org/job/Infinispan/job/PR-10351/2/):
```
quay.io/infinispan-test/server:PR-10351
```

**Comment by ryanemerson** [comment]
It fixes the issue :+1:

**Pull request merged**
