### PR TITLE
[14.0.x] ISPN-14816 Replacing Protobuf schema does not report validation errors

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-14816
https://issues.redhat.com/browse/JDG-6228

Backport of https://github.com/infinispan/infinispan/pull/10867

### CODE REVIEW

**Comment by tristantarrant** [comment]
There is a related failure

**Comment by fax4ever** [comment]
Right! There was a missing file, required by the test, added by a 15 branch commit not present on 14. Fixed it. Thanks @tristantarrant

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by fax4ever** [comment]
Thank you

**Pull request merged**
