### PR TITLE
ISPN-6434 Remove namedCache from clustered config test

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.jboss.org/browse/ISPN-6434

### CODE REVIEW

**Comment by slaskawi** [comment]
Those [2 failures](http://ci.infinispan.org/viewLog.html?buildId=37887&buildTypeId=bt9&guest=1) seems unrelated but retriggering CI to be sure.

**Comment by slaskawi** [comment]
The change looks good to me

**Comment by danberindei** [comment]
Integrated, thanks Vojtech!

However, the test wasn't failing, so I'm wondering how useful it is...

**Comment by vjuranek** [comment]
@danberindei It's an issue for JDG, see [JDG-124](https://issues.jboss.org/browse/JDG-124). In ISPN it's not an issue as it still has older dependency on RestEasy (better to say this is just my suspicion which I didn't investigate much). I hope dependency update in ISPN will be done correctly and this issue won't pop up, but anyway, test delete from non-exiting cache in this place is confusing (at least for me :smile: ). I moved test for delete from non-existing place into (IMHO) better place as part of PR #4179.

**Comment by danberindei** [comment]
@vjuranek You're right, it was confusing to me as well :)

**Pull request closed without merging**
