### PR TITLE
ISPN-14994 JGroups 5.2.15.Final

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-14994

### CODE REVIEW

**Comment by pruivo** [comment]
Cross-site is broken JGRP 5.2.15.Final and 5.2.16.Final. I'll have a look next week.

**Comment by ryanemerson** [comment]
Thanks @pruivo, I'll close this for now

**Comment by ryanemerson** [comment]
@trixpan FYI

**Comment by pruivo** [comment]
@rhusar thanks. I found an issue here: https://issues.redhat.com/browse/JGRP-2710. However, it didn't fix everything since I'm now seeing [1] in our test suite.
I'll plan to take a look by the end of the week (hopefully tomorrow) or starting next week at the latest. 

[1] `Timed out waiting for bridge view [NYC-2, LON-1] on AsyncBackupTest-NodeA after 10 SECONDS. Current bridge view is [NYC-2]`

**Pull request closed without merging**
