### PR TITLE
Jenkinsfile: Remove the deploy stage and run git clean

### PR DESCRIPTION
**Pull request by danberindei**

### CODE REVIEW

**Comment by pruivo** [comment]
so no more snapshots are deployed? should we add a daily snapshot deployment?

**Comment by tristantarrant** [comment]
Once I have the "fatci" EC2 machine properly configured to only run when necessary, I want to deploy snapshots nightly from that.

**Comment by danberindei** [comment]
@pruivo If nobody comes up and says they need the CI snapshots, I'd rather not publish them.

@tristantarrant If it's just a nightly snapshot, we can do it from the existing `ci-slave-fast-1`. Unless you mean it should happen once per day *and* after a successful build...

**Comment by tristantarrant** [comment]
"should happen once per day and after a successful build." < that was my intention

**Comment by pruivo** [comment]
ack.  
@danberindei, I guess it can be integrated or do you want to test/change something else?

**Comment by tristantarrant** [comment]
Merged to master

**Pull request merged**
