### PR TITLE
ISPN-15272 Deadlock during expiration of entries with local cache and…

### PR DESCRIPTION
**Pull request by wburns**
… jdbc store

https://issues.redhat.com/browse/ISPN-15272

### CODE REVIEW

**Comment by ryanemerson** [comment]
The `ThreadLeakChecker` is not happy with the changes

**Comment by wburns** [comment]
ThreadLeaker is only failing due to other failures. I only targeted the nontx case. I will take a look at the other tests.

**Comment by wburns** [comment]
Updated to prevent running on stores that don't support expiration or are clustered (test only works with LOCAL caches). Also RemoteStore EXPIRATION is special so the test doesn't work there either.

**Comment by ryanemerson** [comment]
It looks like there's still related issues:

[org.infinispan.persistence.jdbc.stringbased.JdbcStringBasedStoreFunctionalTest.ThreadLeakChecker](https://ci.infinispan.org/job/Infinispan/job/PR-11471/2/testReport/junit/org.infinispan.persistence.jdbc.stringbased/JdbcStringBasedStoreFunctionalTest/ThreadLeakChecker/)
[org.infinispan.persistence.remote.RemoteStoreConfigWithContainersTest.startUp](https://ci.infinispan.org/job/Infinispan/job/PR-11471/2/testReport/junit/org.infinispan.persistence.remote/RemoteStoreConfigWithContainersTest/startUp/)
[org.infinispan.persistence.jdbc.stringbased.JdbcStringBasedStoreTxFunctionalTest.ThreadLeakChecker](https://ci.infinispan.org/job/Infinispan/job/PR-11471/2/testReport/junit/org.infinispan.persistence.jdbc.stringbased/JdbcStringBasedStoreTxFunctionalTest/ThreadLeakChecker/)
[org.infinispan.persistence.jdbc.stringbased.JdbcStringBasedStoreTxFunctionalTest.ThreadLeakChecker](https://ci.infinispan.org/job/Infinispan/job/PR-11471/2/testReport/junit/org.infinispan.persistence.jdbc.stringbased/JdbcStringBasedStoreTxFunctionalTest/ThreadLeakChecker_2/)

**Comment by wburns** [comment]
> Thanks for persevering with this @wburns. Unfortunately the replacement PersistenceManager is now causing the RocksDB test to fail.

At least it is down to 1 failure now... :D

**Comment by wburns** [comment]
Updated to stop the PersistenceManager directly as it would cause RocksDB to be reopened again.

**Comment by ryanemerson** [comment]
Thanks @wburns

**Pull request merged**
