### PR TITLE
ISPN-6029 DDL for JDBC store tables should never allow null

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-6029

### CODE REVIEW

**Comment by wburns** [comment]
Hrmm it seems a lot of tests are only failing in this branch, which seems quite odd to me [1].

[1] http://ci.infinispan.org/viewLog.html?buildId=53415&buildTypeId=bt9

Going to force another run of this PR.

**Comment by danberindei** [comment]
@wburns it's not just this branch, it's all the 8.2.x pull requests. The 8.2.x branch is in a pretty bad shape...

**Comment by wburns** [comment]
Ah yes 👎

**Comment by wburns** [comment]
Pulling... failures are unrelated.

**Comment by wburns** [comment]
Integrated into 8.2.x, thanks @ryanemerson and @pferraro

**Pull request merged**
