### PR TITLE
ISPN-11583 Server Testsuite: parametric transport

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-11583

### CODE REVIEW

**Comment by gustavonalle** [comment]
I tried running 
```mvn verify -Dit.test=HotRodCacheQueries -Dorg.infinispan.test.server.cluster.stack=test-udp```
but it seems to be using TCP still

**Comment by gustavonalle** [comment]
I also tried the command in the JIRA, and the logs only show TCP, how can I verify it is picking the right stack?

**Comment by tristantarrant** [comment]
@gustavonalle can you try now ?

**Comment by gustavonalle** [comment]
It is working now, but it needs rebase

**Comment by tristantarrant** [comment]
Rebased @gustavonalle

**Comment by gustavonalle** [comment]
Merged, thanks @tristantarrant

**Comment by gustavonalle** [comment]
I will leave the JIRA open until this is backported to ```10.1```

**Pull request merged**
