### PR TITLE
ISPN-13670 Error When Use Schema in Oracle

### PR DESCRIPTION
**Pull request by fbrissi**
[ISPN-13670](https://issues.redhat.com/browse/ISPN-13670)

### CODE REVIEW

**Comment by fbrissi** [comment]
Hi @tristantarrant.
I need to do something else before the review?

**Comment by tristantarrant** [comment]
@gustavolira can you verify this please ?

**Comment by gustavolira** [comment]
@fbrissi thank you! At this point I'm trying to reproduce it. Is it possible to add some test case for it?

**Comment by fbrissi** [comment]
@gustavolira you need to add a schema in your cache configuration. 
I do that add a dot in the prefix field of string-keyed-table. 
When called [TableName. normalized](https://github.com/infinispan/infinispan/blob/82b7c4a4808eb86e4f87f7e5b94cd2b0478108e3/persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/TableName.java#L58-L73) will be split schema and table.

Example:

```xml
<string-keyed-table create-on-start="true" prefix="YOUR_SCHEMA.CACHE">
  <id-column name="ID" type="VARCHAR(255)"/>
  <data-column name="DATA_COLUMN" type="BLOB"/>
  <timestamp-column name="TIMESTAMP" type="INT"/>
  <segment-column name="SEG" type="INT"/>
</string-keyed-table>
```

Without this PR you received an error:

```
infinispan_1       | 2022-01-27 21:57:12,434 DEBUG (main) [org.infinispan.persistence.manager.PersistenceManagerImpl] PersistenceManagerImpl encountered an exception during startup of stores java.util.concurrent.CompletionException: org.infinispan.persistence.spi.PersistenceException: java.sql.SQLException: Invalid argument(s) in call
infinispan_1       |    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
infinispan_1       |    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
infinispan_1       |    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
infinispan_1       |    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
infinispan_1       |    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
infinispan_1       |    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
infinispan_1       |    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
infinispan_1       |    at java.base/java.lang.Thread.run(Thread.java:829)
infinispan_1       | Caused by: org.infinispan.persistence.spi.PersistenceException: java.sql.SQLException: Invalid argument(s) in call
infinispan_1       |    at org.infinispan.persistence.jdbc.impl.table.OracleTableManager.indexExists(OracleTableManager.java:64)
infinispan_1       |    at org.infinispan.persistence.jdbc.impl.table.AbstractTableManager.createIndex(AbstractTableManager.java:158)
infinispan_1       |    at org.infinispan.persistence.jdbc.impl.table.AbstractTableManager.start(AbstractTableManager.java:90)
infinispan_1       |    at org.infinispan.persistence.jdbc.stringbased.JdbcStringBasedStore.initializeConnectionFactory(JdbcStringBasedStore.java:188)
infinispan_1       |    at org.infinispan.persistence.jdbc.stringbased.JdbcStringBasedStore.start(JdbcStringBasedStore.java:124)
infinispan_1       |    at org.infinispan.persistence.support.NonBlockingStoreAdapter.lambda$start$0(NonBlockingStoreAdapter.java:108)
infinispan_1       |    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
infinispan_1       |    ... 5 more
infinispan_1       | Caused by: java.sql.SQLException: Invalid argument(s) in call
infinispan_1       |    at oracle.jdbc.OracleDatabaseMetaData.getIndexInfo(OracleDatabaseMetaData.java:3792)
infinispan_1       |    at org.infinispan.persistence.jdbc.impl.table.OracleTableManager.indexExists(OracleTableManager.java:56)
infinispan_1       |    ... 11 more 
```

**Comment by gustavolira** [comment]
@tristantarrant looks good to me

**Comment by ryanemerson** [comment]
Thanks @fbrissi

**Pull request merged**
