### PR TITLE
ISPN-5675 asyncThreadPool is missing in GlobalConfigurationBuilder#re…

### PR DESCRIPTION
**Pull request by rhusar**
…ad, validate, toString, equals, hashCode

Looks like some of this stuff should be enumerated instead so that bugs like this would not happen.

Jira
https://issues.jboss.org/browse/ISPN-5675

### CODE REVIEW

**Comment by rhusar** [comment]
Unrelated failures.

**Comment by wburns** [comment]
Pulling...

**Comment by rhusar** [comment]
Cool!

**Comment by wburns** [comment]
Integrated into master, thanks @rhusar !

**Comment by rhusar** [comment]
Great thanks!

**Pull request closed without merging**
