### PR TITLE
ISPN-10450 Improve the initial ServerNG experience (and other assorted stuff)

### PR DESCRIPTION
**Pull request by tristantarrant**
ISPN-10450 Improve the initial ServerNG experience
    * Localizable help messages for server and user-tool
    * Stack selection via the command-line (-j)
    * Port binding via the command-line (-p)
    * Make default configuration (infinispan.xml) clustered
    * Add non-clustered configuration infinispan-local.xml
    * Disable TLS/keystore and memcached connector in default config
    * Refactor shells scripts extracting common logic to common.sh
    * Ensure that it is possible to start the server from paths with spaces
    * Add a README.md file to get users started
https://issues.jboss.org/browse/ISPN-10450
https://issues.jboss.org/browse/ISPN-10434

ISPN-10449 Detect empty properties realm    
    * Refactor security realm configuration
https://issues.jboss.org/browse/ISPN-10449

ISPN-10448 ServerNG Licenses
https://issues.jboss.org/browse/ISPN-10448

### CODE REVIEW

**Comment by tristantarrant** [comment]
Failures are unrelated

**Comment by ryanemerson** [comment]
Also, the licenses aren't included in the distribution so the html's "Local License" column links always result in a 404.

**Comment by tristantarrant** [comment]
@ryanemerson the actual licenses should be added in the distribution module, but I cannot test the thing because it is currently broken by the javadoc / protostream interaction

**Comment by tristantarrant** [comment]
@ryanemerson I have added filtering for the server resources.

**Comment by ryanemerson** [comment]
> @ryanemerson the actual licenses should be added in the distribution module, but I cannot test the thing because it is currently broken by the javadoc / protostream interaction

Ok, the protostream PR needs more tweaks still, so merging as is and we can revisit if required.

**Pull request merged**
