### PR TITLE
ISPN-14809 RESP backpressure support

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-14809

Basic changes boil down to publishing a value to the out List so the ByteToMessageDecoder knows that if auto read is disabled it can actually disable it. This allows us to remove the workaround code that was done before where it would replay the internal buffer when auto read was reenabled on our side. Unfortunately, this means the internal buffer could grow unbounded if a client kept writing to the socket.

### CODE REVIEW

**Comment by wburns** [comment]
This requires a new build of protocol parser and update to that version.

**Comment by wburns** [comment]
The decoder is very slightly slower than before, but that is to expected as its hot path got a little longer having to be passed down the netty pipeline. There isn't much here can do to change that. The auto read path however is much simpler than before, not to mention that we don't have to replay the BytetoMessage internal buffer anymore.

MAIN
```
Benchmark                        (decoder)  (messageCount)  Mode  Cnt  Score   Error  Units
MyBenchmark.testGetPerf            CURRENT             N/A  avgt    5  0.756 ± 0.026  us/op
MyBenchmark.testGetPipelinePerf    CURRENT               2  avgt    5  1.155 ± 0.040  us/op
MyBenchmark.testGetPipelinePerf    CURRENT              25  avgt    5  6.474 ± 0.038  us/op
MyBenchmark.testSetPerf            CURRENT             N/A  avgt    5  0.797 ± 0.025  us/op
MyBenchmark.testSetPipelinePerf    CURRENT               2  avgt    5  1.252 ± 0.023  us/op
MyBenchmark.testSetPipelinePerf    CURRENT              25  avgt    5  7.006 ± 0.127  us/op
```
NEW
```
Benchmark                        (decoder)  (messageCount)  Mode  Cnt  Score   Error  Units
MyBenchmark.testGetPerf            CURRENT             N/A  avgt    5  0.803 ± 0.012  us/op
MyBenchmark.testGetPipelinePerf    CURRENT               2  avgt    5  1.294 ± 0.016  us/op
MyBenchmark.testGetPipelinePerf    CURRENT              25  avgt    5  7.342 ± 0.101  us/op
MyBenchmark.testSetPerf            CURRENT             N/A  avgt    5  0.819 ± 0.005  us/op
MyBenchmark.testSetPipelinePerf    CURRENT               2  avgt    5  1.339 ± 0.023  us/op
MyBenchmark.testSetPipelinePerf    CURRENT              25  avgt    5  7.816 ± 0.026  us/op
```

**Comment by wburns** [comment]
This needs a new build of the protocol parser before it can be integrated.

**Review by jabolina — APPROVED** [review]
Looking good, just waiting for the plugin release. I want to give it a try locally, too.

**Comment by wburns** [comment]
Updated to use 1.0.4.Final for the protocol generator.

**Pull request merged**
