### PR TITLE
[8.2.x] ISPN-6996 Update to Netty 4.1.5.Final

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-6996

### CODE REVIEW

**Comment by tristantarrant** [comment]
Pushed to 8.2.x, thanks

**Comment by johnou** [comment]
Why not stick with Netty 4.0.x (still maintained!) in 8.2.x branch and keep Netty 4.1.x in master? Netty is used in a lot of third party libraries so updating the Netty library by a major version in an Infinispan patch version might come as an unpleasant surprise to developers.

**Comment by gustavonalle** [comment]
Netty is an internal library of the Infinispan server and should be "invisible" to users, and going for 4.0 to 4.1 is updating by a minor version, not a major. Do you have any issues with the upgrade?

**Comment by johnou** [comment]
oops, I had meant minor version. Regardless, it is not backwards compatible which is why I added the comment here. That said, given it is internal and I do not see it exposed in any of the infinispan pom.xmls that I use I think it's ok to leave it as is. Thanks for replying and the explanation!

**Comment by rvansa** [comment]
@johnou Does Netty use a different versioning semantics? (since you say that minor versions are not backwards compatible)

**Comment by gustavonalle** [comment]
This is the official statement from Netty:
```
Although we did our best to keep the backward compatibility from 4.0, 4.1 contains
multiple additions  which might not be fully backward-compatible with 4.0. 
Please make sure to recompile your application against the new version.
```

**Comment by johnou** [comment]
@rvansa yes there are breaking changes moving from 4.0 to 4.1.

**Pull request closed without merging**
