### PR TITLE
ISPN-12869 Correctly handle HTTP failures in CLI benchmark

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-12869

### CODE REVIEW

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Comment by danberindei** [comment]
@tristantarrant it appears `CliIT.testCliHttpBenchmark` introduced a thread leak, because `RestCacheClientOkHttp` has no `close()` method.

**Comment by ryanemerson** [comment]
@danberindei I wonder why that didn't show on the [PR job](https://ci.infinispan.org/job/Infinispan/job/PR-9167/2/#showFailuresLink)

**Comment by danberindei** [comment]
@ryanemerson the leaks did appear in the [first PR build](https://ci.infinispan.org/job/Infinispan/job/PR-9167/1/#showFailuresLink), I'm not sure why they didn't appear in the 2nd as well.

**Pull request merged**
