### PR TITLE
ISPN-11304 Scaling up without state transfer improvements

### PR DESCRIPTION
**Pull request by danberindei**
Includes extra fix for ISPN-11981 Stale immortal entry metadata

https://issues.redhat.com/browse/ISPN-11304
https://issues.redhat.com/browse/ISPN-11981

### CODE REVIEW

**Comment by tristantarrant** [comment]
Conflict

**Comment by danberindei** [comment]
I shouldn't have included that change... rebased.

**Comment by tristantarrant** [comment]
Running locally I see quite a few failures in core (over 260)

**Comment by danberindei** [comment]
Wow, somehow I didn't even consider the possibility that existing code could be affected by the fix for ISPN-11981 Stale immortal entry metadata :facepalm: 

There were two problems:
1. `VersionInterceptor` was adding a version to non-tx `ReplaceCommand`s. The version was no longer needed and in fact `InternalEntryFactoryImpl` was discarding it when committing, but my fix kept the version in the data container and some tests were not expecting it. 
2. Scattered cache entries always have a version, so they need a `MetadataImmortalCacheEntry`. Tests, however, were expecting a `ImmortalCacheEntry`, and they broke when I changed `MetadataImmortalCacheEntry` to not extend `ImmortalCacheEntry`.

I removed `VersionInterceptor` and I updated the scattered tests.

**Comment by tristantarrant** [comment]
Still a lot of failures

**Comment by tristantarrant** [comment]
Still some failures :)

**Comment by danberindei** [comment]
Updated, CI looks good now.

**Comment by danberindei** [comment]
Updated to fix putAll(). The REST test failures are gone now @tristantarrant

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
