### PR TITLE
ISPN-9557 Align 3rd party deps

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-9557

### CODE REVIEW

**Comment by pruivo** [comment]
`versionx.org.jboss.spec.javax.jms.jboss-jms-api_2.0_spec` can be updated to 1.0.2.Final

**Comment by pruivo** [comment]
and these can be aligned as well

`versionx.org.jboss.spec.javax.resource.jboss-connector-api_1.7_spec` => 1.0.1.Final
`versionx.org.jboss.spec.javax.servlet.jboss-servlet-api_3.1_spec` => 1.0.2.Final
`versionx.org.jboss.spec.javax.transaction.jboss-transaction-api_1.2_spec` => 1.1.1.Final

in `build-configuration/pom.xml`
`version.cdi` => 2.0
`version.mockito_dep.bytebuddy` => 1.8.12
`version.reactivestreams` => 1.0.2

**Comment by tristantarrant** [comment]
Done

**Comment by pruivo** [comment]
failures unrelated. integrated!
thanks @tristantarrant !

**Pull request merged**
