### PR TITLE
ISPN-13611 REST server invokes potentially blocking operations

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-13611

* Always call isRunning(cacheName) before getCache(cacheName)
  on non-blocking threads
* Enforce the rule with BlockHound
* Use getNamedComponentRegistry() instead of getCache() when possible
* Start caches eagerly in REST tests
* Log unexpected exceptions in BaseHttpRequestHandler

### CODE REVIEW

**Review by wburns — APPROVED** [review]
Seems fine to me, waiting on CI

**Comment by wburns** [comment]
@danberindei looks like a lot of the health check tests have failed now https://ci.infinispan.org/job/Infinispan/job/PR-9784/1/testReport/junit/org.infinispan.health.impl/ClusterHealthImplTest/testRebalancingStatusWhenUserCacheIsRebalancing/

**Comment by danberindei** [comment]
Tests should pass now. Initially I thought it was just a matter of putting the closing `)` in the wrong place, but then I realized I had to get rid of the mocks in ClusterHealthImplTest altogether, as they were over-complicating the tests.

**Comment by wburns** [comment]
Are we sure the failures here are okay? https://ci.infinispan.org/job/Infinispan/job/PR-9784/3/#showFailuresLink It doesn't look good that they have failed a couple times in a row now.

**Comment by danberindei** [comment]
No, I'm not sure... it's just a PITA to find out what was causing those BackupManagerIT failures, so I was hoping they'd go away silently :)

The ThreeNodeScatteredGlobalStateRestartTest failure is fixed by https://github.com/infinispan/infinispan/pull/9768

**Comment by wburns** [comment]
Integrated into main, thanks @danberindei !

**Pull request merged**
