### PR TITLE
ISPN-5422 Deprecated the old Lifecycle in favour of the one in commons

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5422

### CODE REVIEW

**Comment by pruivo** [comment]
there are 9 reference to the old ```Lifecycle``` (all in javadoc comments)

**Comment by tristantarrant** [comment]
@pruivo fixed

**Comment by pruivo** [comment]
I don't wanna get fired @tristantarrant , but the spring module still references the deprecated lifecycle :)

**Comment by tristantarrant** [comment]
Silly me. NOW it is fixed

**Comment by pruivo** [comment]
testing and pushing...

**Comment by pruivo** [comment]
integrated! thanks @tristantarrant !

**Pull request closed without merging**
