### PR TITLE
ISPN-8982 Hibernate ORM 5.3 2LC implementation

### PR DESCRIPTION
**Pull request by rvansa**
* Includes infinispan-hibernate-cache-spi (and related changes) by Paul Ferraro
* Regions moved from commons to version-specific modules.
* infinispan-hibernate-cache is now merely a copy-paste of v51 with
necessary SPI changes, and this module won't be in Infinispan 9.3
* v53 drops support for transactional caches completely.

### CODE REVIEW

**Comment by rvansa** [comment]
This is a backport of #5900

**Comment by rvansa** [comment]
@galderz Since it is not introduced, I wouldn't block this PR because of it: the purpose is adapting to SPI, not changing the implementation (much).

I got the impression that these rare random failures are likely a test problem (unexpected ordering), not an impl flaw - and if it's the latter, I don't think we've have another week to fix it.

**Comment by galderz** [comment]
Fair enough @rvansa

**Comment by galderz** [comment]
@rvansa Leave that random failure to me. After Summit I'll get back to it :)

**Comment by rvansa** [comment]
@tristantarrant Care to try the shiny release scripts?

**Pull request merged**
