### PR TITLE
ISPN-5434 ClusteringConfigurationBuilder.l1() does not enable L1

### PR DESCRIPTION
**Pull request by dpospisil**
https://issues.jboss.org/browse/ISPN-5434

### CODE REVIEW

**Comment by wburns** [comment]
I personally think the fix should be to change the javadoc so it doesn't state this.  But I also prefer a more proactive approach to enabling things.  @tristantarrant WDYT?

**Comment by dpospisil** [comment]
Just noting that WF and EAP6s assume that the javadoc is correct. In any case we would need to have the fix in ISPN or WF/EAP6.

**Comment by tristantarrant** [comment]
I'd rather change the javadoc and fix WF. All other "boolean" components use explicit methods and I don't want to make L1 special.

**Comment by dpospisil** [comment]
OK, I am closing the PR based on above comments.

**Comment by wburns** [comment]
Thanks @dpospisil for pointing out the discrepancy though :+1:

**Pull request closed without merging**
