### PR TITLE
[13.0] ISPN-14053 Use WildFly OpenSSL 2.2.5

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14053

### CODE REVIEW

**Comment by pruivo** [comment]
@tristantarrant is causing some failure with 
```
Caused by: java.lang.UnsatisfiedLinkError: /home/infinispan/workspace/Infinispan_PR-10453/server/router/target/tmp-18165555667644039469openssl/libwfssl.so: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/infinispan/workspace/Infinispan_PR-10453/server/router/target/tmp-18165555667644039469openssl/libwfssl.so)
```

**Comment by tristantarrant** [comment]
Lovely

**Comment by tristantarrant** [comment]
Fixed

**Comment by tristantarrant** [comment]
No. it's unrelated

**Comment by pruivo** [comment]
merged! thanks @tristantarrant !

**Pull request merged**
