### PR TITLE
New default values for test

### PR DESCRIPTION
**Pull request by diegolovison**

### CODE REVIEW

**Comment by diegolovison** [comment]
run performance tests please
library repl reads
cs-hotrod repl reads

**Comment by diegolovison** [comment]
run performance tests please
library repl reads
cs-hotrod repl reads

**Comment by diegolovison** [comment]
run performance tests please
library repl reads
cs-hotrod repl reads

**Comment by danberindei** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Pull request closed without merging**
