### PR TITLE
[14.x] ISPN-14994 JGroups 5.2.15.Final

### PR DESCRIPTION
**Pull request by trixpan**

### CODE REVIEW

**Comment by trixpan** [comment]
more context is available here:

https://issues.redhat.com/browse/JGRP-2707
https://github.com/keycloak/keycloak/issues/21092

**Comment by trixpan** [comment]
@karesti the CI doesn't make it clear if the issue is caused by the bumped version. Would you have any insight?

**Comment by ryanemerson** [comment]
Thanks for the PR @trixpan. We need this in `main` first, I've created https://github.com/infinispan/infinispan/pull/11059.

I'll re-run CI and take a closer look at the failure to see if it's related.

**Comment by trixpan** [comment]
> Thanks for the PR @trixpan. We need this in `main` first, I've created #11059.
> 
> I'll re-run CI and take a closer look at the failure to see if it's related.
> 
> https://issues.redhat.com/browse/ISPN-14994

thanks. I wasn't sure if your flow was main then backport, or direct backport. :-) 

appreciated.

**Comment by ryanemerson** [comment]
Closing as JGroups 5.2.17.Final is required. @pruivo is going to handle this.

**Comment by pruivo** [comment]
@trixpan I talked to Martin Bartos (internally) yesterday and the RELAY2 JGroups protocol is not working properly due to recent changes. I think Keycloak can overwrite the JGroups version if you are not using RELAY2 in your test suite.

**Pull request closed without merging**
