### PR TITLE
ISPN-5061 Cross site state transfer - NPE on consumer site when backup c...

### PR DESCRIPTION
**Pull request by pruivo**
...ache is local

* Created BackupReceiver implementation to handle the local-mode caches

https://issues.jboss.org/browse/ISPN-5061

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8190/pruivo:ISPN-5061/xsite-st-npe-local-cache](http://ci.infinispan.org/viewLog.html?buildId=22552&buildTypeId=bt9&guest=1) for 6ff0e2338a2d653479ea4fb47603e376be342b66
Tests: 11215, 1 failed (1 new), 23 ignored. Build time: 02:08:41

Failed tests detected
* (new) TestSuite: org.infinispan.statetransfer.ClusterTopologyManagerTest.testClusterRecoveryWithRebalance



Error message is logged

Build duration (secs) is too large: 7701

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8229/pruivo:ISPN-5061/xsite-st-npe-local-cache](http://ci.infinispan.org/viewLog.html?buildId=22619&buildTypeId=bt9&guest=1) for 6ff0e2338a2d653479ea4fb47603e376be342b66
Tests: 11218, 3 failed (3 new), 23 ignored. Build time: 02:09:22

Failed tests detected
* (new) TestSuite: org.infinispan.statetransfer.RebalancePolicyJmxTest.testJoinAndLeaveWithRebalanceSuspended


* (new) TestSuite: org.infinispan.atomic.DistWriteSkewAtomicMapAPITest.testConcurrentWritesAndIteration


* (new) TestSuite: org.infinispan.distexec.DistributedExecutorWithCacheLoaderTest.testInvokeAnyWithTimeout



Error message is logged

Build duration (secs) is too large: 7734

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8245/pruivo:ISPN-5061/xsite-st-npe-local-cache](http://ci.infinispan.org/viewLog.html?buildId=22660&buildTypeId=bt9&guest=1) for 6ff0e2338a2d653479ea4fb47603e376be342b66
Tests: 11217, 5 failed (5 new), 23 ignored. Build time: 01:55:48

Failed tests detected
* (new) TestSuite: org.infinispan.notifications.cachelistener.cluster.ClusterListenerReplInitialStateTest.testPrimaryOwnerGoesDownAfterBackupRaisesEvent


* (new) TestSuite: org.infinispan.atomic.AtomicHashMapPessimisticConcurrencyTest.testLockTimeout


* (new) TestSuite: org.infinispan.atomic.DistAtomicMapAPITest.testConcurrentWritesOnExistingMap


* (new) TestSuite: org.infinispan.atomic.RepeatableReadFineGrainedAtomicMapAPITest.testConcurrentWritesOnExistingMap


* (new) org.infinispan.server.test.query.ManualIndexingIT.testManualIndexing



Error message is logged

Build duration (secs) is too large: 6993

**Comment by tristantarrant** [comment]
Pulled, thanks

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8273/pruivo:ISPN-5061/xsite-st-npe-local-cache](http://ci.infinispan.org/viewLog.html?buildId=22724&buildTypeId=bt9&guest=1) for 6ff0e2338a2d653479ea4fb47603e376be342b66
Tests: 11232, 4 failed (3 new), 23 ignored. Build time: 01:52:52

Failed tests detected
* (new) TestSuite: org.infinispan.client.hotrod.query.MultiHotRodServerIspnDirReplQueryTest.testAttributeQuery


* (new) TestSuite: org.infinispan.client.hotrod.query.MultiHotRodServerIspnDirReplQueryTest.testEmbeddedAttributeQuery


* (new) TestSuite: org.infinispan.client.hotrod.query.MultiHotRodServerIspnDirReplQueryTest.testProjections


* (since 08-Jan-2015) org.infinispan.server.test.query.ManualIndexingIT.testManualIndexing



Error message is logged

Build duration (secs) is too large: 6754

**Pull request closed without merging**
