### PR TITLE
Uberjar osgi fixes

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-5116

### CODE REVIEW

**Comment by anistor** [comment]
First of all relocating com.google.protobuf to infinispan.com.google.protobuf breaks clients that need to use com.google.protobuf.RawProtobufMarshaller, namely the marshallers generated via annotations.

And if infinispan-remote does not export com.google.protobuf and leaves it for the client code to provide it then you'll get the split package error anyway.

I think exporting com.google.protobuf is the lesser evil, although ideally we should remove the com.google.protobuf dependecy from scratch. Protostream only uses about 4 classes from protobuf jar, so it is very doable.

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8227/anistor:uberjar_osgi_fixes_anistor](http://ci.infinispan.org/viewLog.html?buildId=22656&buildTypeId=bt9&guest=1) for 4374c6143e7e74819babdc5cb32cdf78db3dbab9
Tests: 11154, 4 failed (3 new), 22 ignored. Build time: 02:31:05

Failed tests detected
* (new) TestSuite: org.infinispan.statetransfer.ClusterTopologyManagerTest.testClusterRecoveryAfterThreeWaySplit


* (new) TestSuite: org.infinispan.client.hotrod.DistTopologyChangeUnderLoadTest.testPutsSucceedWhileTopologyChanges


* (new) org.infinispan.server.test.query.ManualIndexingIT.testManualIndexing


* (since 22-Dec-2014) org.infinispan.test.integration.as.InfinispanLuceneDirectoryIT



Error message is logged

Build duration (secs) is too large: 9226

**Comment by anistor** [comment]
@Isavin I refactored protostream to no longer expose com.google.protobuf.* in its API, so exporting com.google.protobuf from infinispan-remote is no longer needed.

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8257/anistor:uberjar_osgi_fixes_anistor](http://ci.infinispan.org/viewLog.html?buildId=22719&buildTypeId=bt9&guest=1) for 4c96f81e57d4fa0a63e8f72eedabc28605a368ab
Tests: 11232, 1 failed (1 new), 23 ignored. Build time: 01:41:36

Failed tests detected
* (new) TestSuite: org.infinispan.interceptors.ConcurrentInterceptorVisibilityTest.testSizeVisibility

**Comment by anistor** [comment]
@isavin None of the failures in CI are related. I think it's fine to integrate this. Should I do it?

**Comment by isavin** [comment]
Integrated. Thanks @anistor!

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8283/anistor:uberjar_osgi_fixes_anistor](http://ci.infinispan.org/viewLog.html?buildId=22768&buildTypeId=bt9&guest=1) for 4c96f81e57d4fa0a63e8f72eedabc28605a368ab
Tests: 11232, 0 failed (0 new), 23 ignored. Build time: 02:08:59

Error message is logged

Build duration (secs) is too large: 7720

**Pull request closed without merging**
