### PR TITLE
ISPN-15489 ProtoStream 5.0.1.Final

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-15849

### CODE REVIEW

**Comment by ryanemerson** [comment]
@tristantarrant Please wait for my approval before merging. I want to use the image with the Operator to make sure the indexing issue is resolved.

**Comment by tristantarrant** [comment]
I might be doing a 5.0.1 today, so this will be updated accordingly

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#4](https://ci.infinispan.org/job/Infinispan/job/PR-12120/4/):
```
quay.io/infinispan-test/server:PR-12120
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#5](https://ci.infinispan.org/job/Infinispan/job/PR-12120/5/):
```
quay.io/infinispan-test/server:PR-12120
```

**Comment by infinispanrelease** [comment]
Image pushed for Jenkins build [#6](https://ci.infinispan.org/job/Infinispan/job/PR-12120/6/):
```
quay.io/infinispan-test/server:PR-12120
```

**Review by ryanemerson — APPROVED** [review]
The Operator tests are fixed as expected :+1:

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
