### PR TITLE
ISPN-14189 Wrong numbers are shown after clear/rebuild index action

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-14189

### CODE REVIEW

**Comment by fax4ever** [comment]
@yrodiere I don't know if you want to have a look at it

**Comment by yrodiere** [comment]
> @yrodiere I don't know if you want to have a look at it

I'm surprised, does this actually fix the problem? Does your test really fail before the fix?

I don't doubt there is a problem, I'm just not sure it is easily and reliably reproduced.

Anyway, I'll answer on the Jira issue directly.

**Comment by fax4ever** [comment]
> > @yrodiere I don't know if you want to have a look at it
> 
> I'm surprised, does this actually fix the problem? Does your test really fail before the fix?
> 
> I don't doubt there is a problem, I'm just not sure it is easily and reliably reproduced.
> 
> Anyway, I'll answer on the Jira issue directly.

@yrodiere thanks for the help.
Yes if I run the test (https://github.com/infinispan/infinispan/pull/10823/commits/aa06ca0812733e5cf1cb94ca318ce3a4d47668f0) (on my local environment at least)  without the patch (https://github.com/infinispan/infinispan/pull/10823/commits/8c0be7d3a04f185f21116aac66670c29df0fd195) it fails. Other tests done by other people would seem to bear that out.

Almost certainly there is no issue on the Hibernate Search side, but this is probably the normal Apache Lucene async behavior as you said.

Anyway the goal here I think is to provide statistics. According to my tests the query count would force Lucene to produce a more consistent result and here the solution would be simply compute the size after the count.

**Comment by yrodiere** [comment]
> According to my tests the query count would force Lucene to produce a more consistent result and here the solution would be simply compute the size after the count

Maybe... sometimes. Bear in mind this might also just be a timing issue, like if the time of executing the query is enough for the merge to happen in the background and thus your test passes... until the query gets executed too fast and the test will start failing.

Personally I'd rather go with forcing segment merging just after a purge, that should give you a more reliable behavior.

Also, FWIW you don't necessarily need to use the blocking version of `computeSizeInBytes` to chain operations in a certain order; `CompletionStage#thenCompose(...)` could work as well. As far as I know there's no reason for the synchronous version to work better than the async version.

**Comment by fax4ever** [comment]
> until the query gets executed too fast and the test will start failing

According to the tests I and other people did no matter how much time passes between the purge and the compute of the size, the result is always non consistent, it becomes consistent seems to be the query count.

**Comment by fax4ever** [comment]
> Also, FWIW you don't necessarily need to use the blocking version of computeSizeInBytes to chain operations in a certain order; CompletionStage#thenCompose(...) could work as well. As far as I know there's no reason for the synchronous version to work better than the async version.

This looks a nice idea. I'm going to apply. Thanks

**Comment by yrodiere** [comment]
> > Personally I'd rather go with forcing segment merging just after a purge, that should give you a more reliable behavior.
> 
> I wound not introduce a segment merging to get statistics

Neither would I, that would be crazy. I said to merge after a purge, not before getting statistics.

**Comment by fax4ever** [comment]
> Neither would I, that would be crazy. I said to merge after a purge, not before getting statistics.

Merging after a purge looks to me quite strange. 
Translated to the Java memory world it would be as we compact the memory after we empty the memory.
The solution I’m proposing to compute the size after the count remains the best option, of course IMO, to provide a consistent size value to the final user.

On the other hand I would like to explore your suggestion of using the async version of `computeSizeInBytes`.

**Comment by yrodiere** [comment]
> Merging after a purge looks to me quite strange.
> Translated to the Java memory world it would be as we compact the memory after we empty the memory.

It's more similar to de-fragmenting your filesystem after you deleted most of your files. It does make sense if you think about it. I'm also pretty sure it happens automatically anyway, just not immediately (hence the seemingly incorrect index size for a few milliseconds/seconds after the purge).

It's also literally the default in Hibernate Search's mass indexer after the initial purge.

Anyway, do what you will.

**Comment by fax4ever** [comment]
> It's more similar to de-fragmenting your filesystem after you deleted most of your files.

I don't think so, the scope here would be de-fragmenting some files after you deleted the same files (and not the entire filesystem), always IMO, since both the purge and the merge segments are scoped on a single index. 

> It's also literally the default in Hibernate Search's mass indexer after the initial purge.

To be honest, I don't know if it helps somehow. Maybe its actual usefulness should be tested.

In any case I would like to do no change on the purge commands to provide better statistics.

**Comment by fax4ever** [comment]
Thank @yrodiere. I applied the suggestion to use the `thenCompose` and `computeSizeInBytesAsync`.

**Comment by fax4ever** [comment]
Thank @ryanemerson!

**Pull request merged**
