### PR TITLE
[DO NOT INTEGRATE] ISPN-6494 Investigate bundler performance

### PR DESCRIPTION
**Pull request by danberindei**
First step, try `transfer-queue`

### CODE REVIEW

**Comment by danberindei** [comment]
run performance tests please

**Comment by danberindei** [comment]
Closing for now

**Comment by danberindei** [comment]
run performance tests please

**Comment by danberindei** [comment]
run performance tests please

**Comment by danberindei** [comment]
run performance tests please
library cs
[UDP 1kB]

**Comment by danberindei** [comment]
run performance tests please
library cs
[UDP 1kB]

**Comment by danberindei** [comment]
run performance tests please
library cs
[UDP 1kB]

**Comment by danberindei** [comment]
run performance tests please
library cs
[UDP 1kB]

**Comment by danberindei** [comment]
run performance tests please
library cs
[UDP 1kB]

**Comment by danberindei** [comment]
run performance tests please
library
[UDP 1kB]

**Comment by danberindei** [comment]
@diegolovison sorry if you had to delete a bunch of perfack jobs, github was a bit of a mess yesterday

**Comment by diegolovison** [comment]
run performance tests please
library repl writes
[UDP 1kB]

**Comment by diegolovison** [comment]
run performance tests please
library repl writes
[UDP 1kB]

**Comment by diegolovison** [comment]
run performance tests please
library repl writes
[UDP 1kB]

**Comment by danberindei** [comment]
run performance tests please
library repl writes
[UDP 1kB]

**Comment by danberindei** [comment]
run performance tests please
library
cs

**Comment by diegolovison** [comment]
run performance tests please

**Comment by danberindei** [comment]
run performance tests please
library
[UDP 1kB]

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Comment by diegolovison** [comment]
run performance tests please

**Pull request closed without merging**
