### PR TITLE
ISPN-5673 Observation attribute is ignored for listeners with indexed DSL filters

### PR DESCRIPTION
**Pull request by anistor**
jira: https://issues.jboss.org/browse/ISPN-5673,
https://issues.jboss.org/browse/ISPN-5669

### CODE REVIEW

**Comment by anistor** [comment]
CI failures are not related.

**Comment by anistor** [comment]
Updated.

**Comment by anistor** [comment]
Updated.

**Comment by wburns** [comment]
Pulling..

**Comment by wburns** [comment]
Integrated into 7.2.x, thanks @anistor !

**Pull request closed without merging**
