### PR TITLE
ISPN-7324 DDAsyncInterceptor indirection slows down replicated reads

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-7324

### CODE REVIEW

**Comment by rvansa** [comment]
+0.1
I've heard `instanceof` checks could be tricky, because the type from the class hierarchy is cached. Do you know about some good read on this topic?

**Comment by danberindei** [comment]
I'm using https://shipilev.net/blog/2015/black-magic-method-dispatch/ as a reference. One of the experiments he tries is to "peel off the hottest type with manual checks" to improve performance for megamorphic calls.

**Comment by rvansa** [comment]
That's about megamorphic calls, but manual `instanceof` improves perf by caching the hierarchy, and that's where my knowledge is below freezing point. See https://issues.apache.org/jira/secure/attachment/12833228/reduce_instanceof_typechecking.pdf

**Comment by danberindei** [comment]
@rvansa Yeah, that link doesn't sound very encouraging... the theory is that C2 will have better information on the `else` branch, e.g. when you have 66% reads, 33% writes, 1% "other". 

And it actually worked beautifully for reads without transactions and with implicit transactions. But it actually made things much worse with explicit transactions, because there we have 33.3% read, 33.3% prepare, 33.3% commit, so I'm closing the PR.

**Pull request closed without merging**
