### PR TITLE
ISPN-16058 Include simple redis-compatbile configuration

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-16058

### CODE REVIEW

**Comment by ryanemerson** [comment]
Docs or it didn't happen :slightly_smiling_face:

**Comment by tristantarrant** [comment]
Not only have I added docs, but I've done the same for memcached too :)

**Comment by ryanemerson** [comment]
Thanks @tristantarrant. We should blog about this!

**Comment by tristantarrant** [comment]
We should also include something in the image docs

**Comment by ryanemerson** [comment]
Good idea. I've made a note to add bits to the README once 15.0.4.Final is released

**Pull request merged**
