### PR TITLE
ISPN-13918 Upgrade external cloud discovery protocols to versions compatible with JGroups 5.x

### PR DESCRIPTION
**Pull request by rhusar**
https://issues.redhat.com/browse/ISPN-13918

### CODE REVIEW

**Comment by pruivo** [comment]
@tristantarrant yes, it is shipped with the WF module: https://github.com/infinispan/infinispan/blob/feb8bf202d46d990982f8adea6a9cc2e514972b4/wildfly/feature-pack/src/main/resources/modules/org/infinispan/slot/module.xml#L33

**Comment by rhusar** [comment]
> Maven failure: on project infinispan-feature-pack: Could not resolve dependencies for project org.infinispan:infinispan-feature-pack:pom:14.0.0-SNAPSHOT: Could not find artifact org.jgroups.aws.s3:native-s3-ping:jar:2.0.0.Final in redhat-earlyaccess-repository-group (https://maven.repository.redhat.com/earlyaccess/all/) -> [Help 1]

Looks like @belaban botched a release there. :-)

**Comment by tristantarrant** [comment]
I see mostly SNAPSHOTS here: https://repository.jboss.org/org/jgroups/aws/s3/native-s3-ping/

**Comment by rhusar** [comment]
Rebased after Pedro's changes.

**Review by pruivo — APPROVED** [review]
LGTM

**Comment by tristantarrant** [comment]
Pushed manually. Thanks !

**Pull request closed without merging**
