### PR TITLE
Revert "ISPN-7426 Upgrade to Hibernate Search 5.7.0.CR1 and Hibernate…

### PR DESCRIPTION
**Pull request by galderz**
… ORM 5.2.7.Final"

This reverts commit 602fb0aa055ec4b1d382fbbe4886922d12538767.

### CODE REVIEW

**Comment by galderz** [comment]
Reasons for reverting explained in [ISPN-7426](https://issues.jboss.org/browse/ISPN-7426)

**Comment by galderz** [comment]
I've manually triggered build for this PR.

**Comment by Sanne** [comment]
Don't do this please.

**Comment by tristantarrant** [comment]
Fix it then :)

**Pull request closed without merging**
