### PR TITLE
ISPN-7822 Move transaction classes to commons

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.jboss.org/browse/ISPN-7822

### CODE REVIEW

**Comment by tristantarrant** [comment]
Compilation failures...

**Comment by pruivo** [comment]
fixed the compile error and the test failure. Also, I deprecated the SerializedXid.

**Comment by tristantarrant** [comment]
Looks good to me. @danberindei  ?

**Comment by ryanemerson** [comment]
@pruivo The OSGI failure below appears to be related:

```
java.lang.IllegalStateException: Can't install feature infinispan-commons/9.1.0-SNAPSHOT: 	
Could not start bundle mvn:org.infinispan/infinispan-commons/9.1.0-SNAPSHOT in feature(s) infinispan-commons-9.1.0-SNAPSHOT: Unresolved constraint in bundle org.infinispan.commons [87]: Unable to resolve 87.0: missing requirement [87.0] osgi.wiring.package; (&(osgi.wiring.package=javax.transaction)(version>=1.1.0)(!(version>=2.0.0)))
```

**Comment by pruivo** [comment]
Updated! I think I fixed it (and it seems to work) but I'm not sure. File changed: commons/src/main/resources/features.xml

**Pull request merged**
