### PR TITLE
ISPN-14653 LCS

### PR DESCRIPTION
**Pull request by jabolina**
https://issues.redhat.com/browse/ISPN-14653

No tests because Lettuce doesn't have an API for LCS.

### CODE REVIEW

**Review by rigazilla — COMMENTED** [review]
overall looks good to me, if you think it worth you can try to add custom command to test LCS, I did something similar [here](https://github.com/rigazilla/infinispan/blob/b6efeed2d78ac7e96bed92723a8a95fb571dddb9/server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java#L544-L563)

**Comment by jabolina** [comment]
Thanks, I wasn't aware of that. Going to add some tests.

**Comment by jabolina** [comment]
Updated adding a simple test. I am not sure how to make the interface with custom commands to return a more complex data structure.

**Review by rigazilla — APPROVED** [review]
lgtm, I've rerun a failed check just to see if we can full green. let's see

**Comment by rigazilla** [comment]
merged, thanks @jabolina !

**Pull request merged**
