### PR TITLE
ISPN-15132 Updates to protostream 4.6.4.Final

### PR DESCRIPTION
**Pull request by karesti**
https://issues.redhat.com/browse/ISPN-15132

### CODE REVIEW

**Comment by pruivo** [comment]
@karesti there are tests failing.

**Comment by karesti** [comment]
@pruivo I didn't see those when I did the run locally

**Comment by karesti** [comment]
@pruivo I've built protostream and test seem failing since IPROTO-264 Remove stream buffer when unmarshalling objects

**Comment by wburns** [comment]
https://issues.redhat.com/browse/IPROTO-276 should remedy this

**Review by pruivo — APPROVED** [review]

**Comment by pruivo** [comment]
merged! thanks @karesti @wburns

**Pull request merged**
