### PR TITLE
ISPN-10354 Separate jboss-marshalling from core

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-10354

WIP branch of separating jboss-marshalling from `infinispan-core`. Some core failures cannot be addressed until the below protostream Jiras are resolved, however opening this PR now to allow early review and see what impact on other modules the changes have.

## Expected failures:
```java
org.infinispan.xsite.*
org.infinispan.stream.DistributedStreamIteratorWithStoreAsBinaryTest.testFilterWithStoreAsBinary*
RocksDBStoreTest
```

## Blocking protostream issues:
- https://issues.jboss.org/browse/IPROTO-100
  - Prevents resolution of `org.infinispan.stream.*` failures
- https://issues.jboss.org/browse/IPROTO-101
  - Prevents resolution of `org.infinispan.xsite.*` failures
- https://issues.jboss.org/browse/IPROTO-103
  - Prevents resolution of `RocksDB` failures
  - Fix which currently prevents compilation of rocksdb module due to IPROTO-103 available https://github.com/ryanemerson/infinispan/commit/853cf0a4d496216725f37d1fa15a4c793fb7b605

## Summary of changes:
- Externalizers no longer use `org.jboss.marshalling.util.IdentityIntMap`
- `ExternalJBossMarshaller` and `JBossUserMarshaller` moved to new `infinispan-jboss-marshalling` module
  - If module is on the classpath, then embedded mode will utilise the `ExternalJBossMarshaller` within the GlobalMarshaller as before. As well as the `JBossUserMarshaller`, unless a SerializationContextInitializer has been provided, in which case the `ProtostreamUserMarshaller` is always used.
- GlobalMarshaller can now serialize Lambdas directly.
- ProtostreamMarshaller moved to commons
- ProtostreamUserMarshaller created as the default user marshaller.
  - `SerializationContextInitializer` for user marshaller can now be provided as part of `SerializationConfiguration`.
- Core testsuite updated to utilise protostream annotated Pojos for user types and explicitly providing externalizers for internal/streaming tests.
- Server and query now have `org.infinispan:infinispan-jboss-marshalling` as a dependency to enable previous behaviour.
- Feature-packs updated to reflect ^, with embedded exporting an optional dependency on  the `org.infinispan.jboss-marshalling` module which is only defined in the `embedded-query` feature-pack

### CODE REVIEW

**Comment by ryanemerson** [comment]
A big part of the changes to the core testsuite are due to moving from `JbossUserMarshaller` to `ProtostreamUserMarshaller` and an object implementing Serializable no longer being enough for an object to be marshalled.  However, if a user still wishes to just use java Serialization for their user types, it's possible for them to specify `org.infinispan.commons.JavaSerializationMarshaller` as the marshaller without having to introduce the `infinispan-jboss-marshalling` artifact as a dependency.

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/46fef8bcdc9388c1f202fa2b5f1933c8/raw/c344a4082228abc317070a4ac71c126467baea42/gistfile1.txt
jdg_config https://gist.githubusercontent.com/diegolovison/f2c9ccda35e161a7b1f8f77b6d69b7c6/raw/8e277fc52b154a6c82b0840c93a83f1537eefc0e/gistfile1.txt
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/46fef8bcdc9388c1f202fa2b5f1933c8/raw/c344a4082228abc317070a4ac71c126467baea42/gistfile1.txt
jdg_config https://gist.githubusercontent.com/diegolovison/f2c9ccda35e161a7b1f8f77b6d69b7c6/raw/8e277fc52b154a6c82b0840c93a83f1537eefc0e/gistfile1.txt
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/46fef8bcdc9388c1f202fa2b5f1933c8/raw/c344a4082228abc317070a4ac71c126467baea42/gistfile1.txt
jdg_config https://gist.githubusercontent.com/diegolovison/f2c9ccda35e161a7b1f8f77b6d69b7c6/raw/8e277fc52b154a6c82b0840c93a83f1537eefc0e/gistfile1.txt
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/46fef8bcdc9388c1f202fa2b5f1933c8/raw/c344a4082228abc317070a4ac71c126467baea42/gistfile1.txt
jdg_config https://gist.githubusercontent.com/diegolovison/f2c9ccda35e161a7b1f8f77b6d69b7c6/raw/8e277fc52b154a6c82b0840c93a83f1537eefc0e/gistfile1.txt
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/46fef8bcdc9388c1f202fa2b5f1933c8/raw/c344a4082228abc317070a4ac71c126467baea42/gistfile1.txt
jdg_config https://gist.githubusercontent.com/diegolovison/f2c9ccda35e161a7b1f8f77b6d69b7c6/raw/8e277fc52b154a6c82b0840c93a83f1537eefc0e/gistfile1.txt
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/46fef8bcdc9388c1f202fa2b5f1933c8/raw/c344a4082228abc317070a4ac71c126467baea42/gistfile1.txt
jdg_config https://gist.githubusercontent.com/diegolovison/f2c9ccda35e161a7b1f8f77b6d69b7c6/raw/8e277fc52b154a6c82b0840c93a83f1537eefc0e/gistfile1.txt
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/46fef8bcdc9388c1f202fa2b5f1933c8/raw/c344a4082228abc317070a4ac71c126467baea42/gistfile1.txt
jdg_config https://gist.githubusercontent.com/diegolovison/f2c9ccda35e161a7b1f8f77b6d69b7c6/raw/8e277fc52b154a6c82b0840c93a83f1537eefc0e/gistfile1.txt
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/46fef8bcdc9388c1f202fa2b5f1933c8/raw/c344a4082228abc317070a4ac71c126467baea42/gistfile1.txt
jdg_config https://gist.githubusercontent.com/diegolovison/f2c9ccda35e161a7b1f8f77b6d69b7c6/raw/8e277fc52b154a6c82b0840c93a83f1537eefc0e/gistfile1.txt
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/46fef8bcdc9388c1f202fa2b5f1933c8/raw/c344a4082228abc317070a4ac71c126467baea42/gistfile1.txt
jdg_config https://gist.githubusercontent.com/diegolovison/f2c9ccda35e161a7b1f8f77b6d69b7c6/raw/8e277fc52b154a6c82b0840c93a83f1537eefc0e/gistfile1.txt
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/46fef8bcdc9388c1f202fa2b5f1933c8/raw/c344a4082228abc317070a4ac71c126467baea42/gistfile1.txt
jdg_config https://gist.githubusercontent.com/diegolovison/f2c9ccda35e161a7b1f8f77b6d69b7c6/raw/8e277fc52b154a6c82b0840c93a83f1537eefc0e/gistfile1.txt
custom_library

**Comment by diegolovison** [comment]
run custom performance tests please
ispn_config https://gist.githubusercontent.com/diegolovison/46fef8bcdc9388c1f202fa2b5f1933c8/raw/c344a4082228abc317070a4ac71c126467baea42/gistfile1.txt
jdg_config https://gist.githubusercontent.com/diegolovison/f2c9ccda35e161a7b1f8f77b6d69b7c6/raw/8e277fc52b154a6c82b0840c93a83f1537eefc0e/gistfile1.txt
custom_library

**Comment by wburns** [comment]
So the first thing I see is that JBossMarshalling is still a dependency of commons, which we don't want. I thought the original intent of this issue was to abstract jboss marshalling dependency out to a separate optional module. Then if desired we could plug in any module we wanted to do the marshalling for us, such as protostream, kryo, java serialization or whichever we wanted. I feel taking only this first step should be much easier than this PR has made it seem. And we can later plug in another provider as needed.

**Comment by ryanemerson** [comment]
@wburns I kept `jboss-marshalling` as a dependency on commons, because removing it would have meant more incompatible changes and for the Quarkus use case I knew you had already implemented the required workarounds for the client. I'm all for removing it from commons as well, if we want todo that.

> Then if desired we could plug in any module we wanted to do the marshalling for us, such as protostream, kryo, java serialization or whichever we wanted.

So this PR allows that, you just need to define the marshaller impl class via SerializationConfiguration and obviously add any additional dependencies that are required.

**Comment by wburns** [comment]
Unfortunately Substrate will still be able to find these classes - almost guaranteed (they are only protected by as single if statement. We need to if possible completely cleanse any jboss marshalling from all of our existing modules and only have it referenced in a new module. This is the only way to guarantee it is inaccessible and should allow us to easy replace it with any other module.

**Comment by ryanemerson** [comment]
Closing in favour of https://github.com/infinispan/infinispan/pull/7175

**Pull request closed without merging**
