### PR TITLE
fix link in performance documentation

### PR DESCRIPTION
**Pull request by jbtrystram**
A simple typo fix :)

### CODE REVIEW

**Comment by ryanemerson** [comment]
@jbtrystram Hello! It's been a while. Thanks for the contribution, but I think in this case we need to update the actual anchor to be "store_as_binary" as we have multiple links to #store_as_binary in our docs.

**Comment by oraNod** [comment]
> @jbtrystram Hello! It's been a while. Thanks for the contribution, but I think in this case we need to update the actual anchor to be "store_as_binary" as we have multiple links to #store_as_binary in our docs and that is the name of the feature.
> 
> WDYT @oraNod?

@jbtrystram I've discussed this with @ryanemerson. I think my review comment might be somewhat contradictory to what Ryan said. please go ahead and make the change I requested to update the link. I'll create a separate Jira task to change the anchor and update all the instances after your change is merged. cheers.

**Comment by jbtrystram** [comment]
@ryanemerson  hey there :smile: 

@oraNod  I updated with the anchor you provided. I did a lazy edit on github so I'll let you squash and merge :) 

Cheers !

**Comment by oraNod** [comment]
@jbtrystram [Merged with this commit](https://github.com/infinispan/infinispan/commit/e148ca4dc9c37c1582d6e086c2d7d88c5b4b2eac ). Thank you!

**Pull request closed without merging**
