### PR TITLE
Uberjar osgi fixes

### PR DESCRIPTION
**Pull request by isavin**
https://issues.jboss.org/browse/ISPN-5116

### CODE REVIEW

**Comment by anistor** [comment]
Looking...

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity Infinispan :: Pull requests monitor [Build 8201/isavin:uberjar_osgi_fixes](http://ci.infinispan.org/viewLog.html?buildId=22563&buildTypeId=bt9&guest=1) for 036153d634380e633acdbf2adc6b20404f6178a5
Tests: 11215, 0 failed (0 new), 23 ignored. Build time: 01:40:07

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8211/isavin:uberjar_osgi_fixes](http://ci.infinispan.org/viewLog.html?buildId=22578&buildTypeId=bt9&guest=1) for 036153d634380e633acdbf2adc6b20404f6178a5
Tests: 11154, 3 failed (2 new), 22 ignored. Build time: 02:31:07

Failed tests detected
* (new) TestSuite: org.infinispan.statetransfer.ClusterTopologyManagerTest.testAbruptLeaveAfterGetStatus2


* (new) org.infinispan.server.test.query.ManualIndexingIT.testManualIndexing


* (since 22-Dec-2014) org.infinispan.test.integration.as.InfinispanLuceneDirectoryIT



Error message is logged

Build duration (secs) is too large: 9051

**Comment by anistor** [comment]
@isavin , I've just rebased your PR and added an extra commit that fixes RemoteCacheOsgiIT here https://github.com/anistor/infinispan/tree/uberjar_osgi_fixes_anistor

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8237/isavin:uberjar_osgi_fixes](http://ci.infinispan.org/viewLog.html?buildId=22630&buildTypeId=bt9&guest=1) for 036153d634380e633acdbf2adc6b20404f6178a5
Tests: 11216, 2 failed (2 new), 23 ignored. Build time: 01:40:58

Failed tests detected
* (new) TestSuite: org.infinispan.distexec.DistributedExecutorFailoverTest.testBasicTargetRemoteDistributedCallable


* (new) TestSuite: org.infinispan.partitionhandling.EntryRetrieverReplPartitionHandlingTest.testRetrievalWhenPartitionIsDegrated

**Comment by isavin** [comment]
Closing. The changes are now included in:
https://github.com/infinispan/infinispan/pull/3189

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8276/isavin:uberjar_osgi_fixes](http://ci.infinispan.org/viewLog.html?buildId=22753&buildTypeId=bt9&guest=1) for 036153d634380e633acdbf2adc6b20404f6178a5
Tests: 11232, 1 failed (1 new), 23 ignored. Build time: 02:10:28

Failed tests detected
* (new) org.infinispan.test.integration.security.embedded.NodeAuthenticationMD5PassIT.testReadItemOnJoiningNode



Error message is logged

Build duration (secs) is too large: 7931

**Pull request closed without merging**
