### PR TITLE
ISPN-14760 Infinispan thirdparty integration tests failure with JDK17

### PR DESCRIPTION
**Pull request by jabolina**
https://issues.redhat.com/browse/ISPN-14760

### CODE REVIEW

**Comment by jabolina** [comment]
The IT tests are consistently failing to execute the command to install tar. Looking into it now.

**Comment by tristantarrant** [comment]
@jabolina I've made changes to the server image in https://github.com/infinispan/infinispan/pull/10720
Maybe you should rebase on top of that once its merged

**Comment by jabolina** [comment]
Rebased. Failures are unrelated.

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by tristantarrant** [comment]
backport please

**Pull request merged**
