### PR TITLE
ISPN-8259 Test field @Analyzer for Protobuf

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.jboss.org/browse/ISPN-8259

### CODE REVIEW

**Comment by anistor** [comment]
Looking ...

**Comment by anistor** [comment]
The test fails: http://ci.infinispan.org/job/Infinispan/job/PR-5407/1/testReport/junit/org.infinispan.client.hotrod.query/RemoteNonIndexedQueryStringTest/testCustomFieldAnalyzer/

**Comment by anistor** [comment]
This test should be disabled in the non-indexed suites that inherit from this one.

**Comment by mgencur** [comment]
Oops. Let me fix it.

**Comment by mgencur** [comment]
Fixed.

**Comment by anistor** [comment]
Integrated in master. Thanks @mgencur !

**Pull request merged**
