### PR TITLE
ISPN-6599 PutMapCommand only partially completed during topology changes

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.jboss.org/browse/ISPN-6599

### CODE REVIEW

**Comment by gustavonalle** [comment]
@pruivo LGTM, cannot reproduce the data loss anymore. Waiting for CI to integrate...

**Comment by gustavonalle** [comment]
@pruivo It has failures on ``` PutMapCommandNonTxTest```

**Comment by pruivo** [comment]
@gustavonalle https://github.com/infinispan/infinispan/pull/4772 fixes that test.

**Comment by galderz** [comment]
The PR has been integrated, so this is ready to go in too.

**Pull request merged**
