### PR TITLE
ISPN-7420 Hot Rod enhancements for transcoding

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.jboss.org/browse/ISPN-7420

Adds similar capabilities to the REST endpoint when it comes to send and receive data in different formats given by a ```MediaType```. 

The API changes can be seen [here](https://github.com/infinispan/infinispan/compare/master...gustavonalle:HotRod-Transcoding?expand=1#diff-7de81536b3e502192f30f16d1e833eaeR108).

### CODE REVIEW

**Comment by gustavonalle** [comment]
Rebased

**Comment by tristantarrant** [comment]
This looks great. Are you already on to the docs ? We also need a demo/quickstart/tutorial

**Comment by gustavonalle** [comment]
@tristantarrant I will add the docs

**Comment by gustavonalle** [comment]
Rebased and added documentation

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
