### PR TITLE
ISPN-14532 Multimap failing with huge value

### PR DESCRIPTION
**Pull request by jabolina**
https://issues.redhat.com/browse/ISPN-14532
https://issues.redhat.com/browse/ISPN-14535
https://issues.redhat.com/browse/ISPN-14536

### CODE REVIEW

**Review by wburns — CHANGES_REQUESTED** [review]
The test changes are not needed. What we need to do instead is change the multi map hotrod tests to use the proper HotRodTestingUtil method to create the server. If not able to then we need to add the single frame decoder to the pipeline like it is done in TestHandlersChannelInitializer.

This will find any issue with a command used by hot rod server that has stuff like this and will be determinstic.

**Comment by jabolina** [comment]
Updated adding the `FixedLengthFrameDecoder(1)` to the client tests, now all commands should be verified for replayability. And added ISPN-14535 as an additional commit.

Let's see if we find more commands with the same issue.

**Review by wburns — CHANGES_REQUESTED** [review]
Changes look good, however we need the `client/hotrod` module to be updated.

**Comment by jabolina** [comment]
Sorry, I keep forgetting about that. Updated.

**Comment by jabolina** [comment]
It seems that all test failures in the previous CI run were because of the `IterationNextOperation`. Now we might have an issue with `ClientEventsOOMTest` because it might take a long time to complete. Let's see how CI goes with the changes.

**Comment by jabolina** [comment]
Let's see how it goes. The `ClientEventsOOMTest` now **does not** check for replayability.

**Comment by jabolina** [comment]
Well, CI needed a few attempts to have a complete run. It should be good for now.

**Comment by wburns** [comment]
Integrated into main, thanks @jabolina !

**Pull request merged**
