### PR TITLE
ISPN-10695 Standardize the transport stack for the test suite

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.jboss.org/browse/ISPN-10695

### CODE REVIEW

**Comment by diegolovison** [comment]
@tristantarrant I would like to let you know that, once this PR is merged. ServerNG is using TCP as default and will be tested with UDP.
IMO, I do prefer have a "default" transport across configuration and test suite.
Tks

**Comment by tristantarrant** [comment]
Can you rebase please?

**Comment by diegolovison** [comment]
@tristantarrant rebased. tks

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
