### PR TITLE
ISPN-16735 New client operation registration can be optimized

### PR DESCRIPTION
**Pull request by wburns**
* Add ArrayRingBuffer to store operations

https://issues.redhat.com/browse/ISPN-16735

### CODE REVIEW

**Comment by wburns** [comment]
ArrayRingBuffer is copied from https://github.com/jgroups-extras/jgroups-raft/blob/master/src/org/jgroups/raft/util/ArrayRingBuffer.java and modified to not allow `headSequence` to point to a non null value when it is non empty.

**Comment by wburns** [comment]
This completely removes the 2 hashmap puts and allocation and removing the netty timeout task for every operation when a custom timeout is not used.

I also fixed the operation old age read consistency issue as the Map was not read from the event loop, which could miss some values or even get a ConcurrentModificationException in others.

**Comment by tristantarrant** [comment]
Merged, thanks

**Comment by jabolina** [comment]
Looking very good :heavy_check_mark: The timeout scheduling is pretty nice!

**Pull request merged**
