### PR TITLE
ISPN-14680 Reuse server image as a base for all tests

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-14680

### CODE REVIEW

**Review by ryanemerson — APPROVED** [review]

**Comment by tristantarrant** [comment]
I'm getting a permission error that is not happening locally. Taking the agent offline and investigating

**Comment by tristantarrant** [comment]
Failures are unrelated. Build time went from 2h 12m to 1h 20m

**Review by pruivo — APPROVED** [review]

**Comment by pruivo** [comment]
merged! thanks @tristantarrant !

**Comment by tristantarrant** [comment]
I should backport this :)

**Pull request merged**
