### PR TITLE
ISPN-13264 Hot Rod client cluster switch never happens if max-retries < cluster size

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.redhat.com/browse/ISPN-13264
https://issues.redhat.com/browse/ISPN-13220

* Keep track of failed servers in ChannelFactory
  A server is failed if it has no connected channels
  and the last connection attempt failed
* When a new connection fails, check the status of the initial servers
* If all initial servers are down, try to switch to another cluster
* If not, but some caches have no live servers, reset those caches to
  the initial server list
* Retried operations wait for the cluster switch to finish
* Manual cluster switch overrides any running automatic switch
* Reject server topologies with an old topology age
* Update the request topology age only after updating the topology age
  to check for all the caches

### CODE REVIEW

**Comment by danberindei** [comment]
Note that `SiteDownFailoverTest` may fail a little more often here than on main, at least until we upgrade to a version of JGroups that includes the JGRP-2570 fix.

**Comment by tristantarrant** [comment]
Quite a few failures related to Rolling upgrades

**Comment by danberindei** [comment]
Fixed @tristantarrant. Not sure why they only started failing now, but the immediate cause is that ChannelFactory uses a write lock for lots of things. 

I tried to move the opening/closing of channels out of the lock but it didn't look great in the tests so I reverted it. Eventually I realized I wasn't handling the scenario in `CompleteShutdownDistRetryTest` correctly and I wasn't resetting the caches when I should have, so I added another fix for that.

**Comment by tristantarrant** [comment]
Aside from the fix, this is a marked improvement in readability.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
