### PR TITLE
ISPN-4994 MultiHotRodServerIspnDirReplQueryTest fails

### PR DESCRIPTION
**Pull request by anistor**
Wait on lucene dir caches to start before the test.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8220/anistor:t_4994_m](http://ci.infinispan.org/viewLog.html?buildId=22594&buildTypeId=bt9&guest=1) for 55541da67cb43b2e1dbb8eef5997b1f08ea44191
Tests: 11216, 1 failed (1 new), 23 ignored. Build time: 01:40:09

Failed tests detected
* (new) TestSuite: org.infinispan.tx.LockAfterNodesLeftTest.test



Error message is logged

Build duration (secs) is too large: 5997

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8238/anistor:t_4994_m](http://ci.infinispan.org/viewLog.html?buildId=22633&buildTypeId=bt9&guest=1) for 55541da67cb43b2e1dbb8eef5997b1f08ea44191
Tests: 11216, 0 failed (0 new), 23 ignored. Build time: 02:08:13

Error message is logged

Build duration (secs) is too large: 7673

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8264/anistor:t_4994_m](http://ci.infinispan.org/viewLog.html?buildId=22696&buildTypeId=bt9&guest=1) for 55541da67cb43b2e1dbb8eef5997b1f08ea44191
Tests: 11232, 1 failed (1 new), 23 ignored. Build time: 02:10:10

Failed tests detected
* (new) TestSuite: org.infinispan.client.hotrod.near.EagerNearCacheTest.testUpdateNearCache



Error message is logged

Build duration (secs) is too large: 7789

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity Infinispan :: Pull requests monitor [Build 8281/anistor:t_4994_m](http://ci.infinispan.org/viewLog.html?buildId=22766&buildTypeId=bt9&guest=1) for 55541da67cb43b2e1dbb8eef5997b1f08ea44191
Tests: 11232, 1 failed (1 new), 23 ignored. Build time: 01:52:46

Failed tests detected
* (new) org.infinispan.server.test.query.ManualIndexingIT.testManualIndexing



Error message is logged

Build duration (secs) is too large: 7014

**Comment by gustavonalle** [comment]
Looking

**Comment by gustavonalle** [comment]
@anistor  Your workaround avoids the issue in my env., but the test setup is a bit strange (as you pointed out on IRC). 
It uses a shared index on top of REPL caches without any specific IndexManager, meaning each node is competing to write to the index. We already have a test for local Infinispan indexes at ```MultiHotRodServerIspnDirQueryTest```, so I will re-purpose this test to use a proper index manager

**Comment by gustavonalle** [comment]
Changing the config to:
```
ConfigurationBuilder builder = hotRodCacheConfiguration(getDefaultClusteredCacheConfig(CacheMode.REPL_SYNC, false));
builder.indexing()
            .index(Index.LOCAL)
            .addProperty("default.indexmanager", "org.infinispan.query.indexmanager.InfinispanIndexManager");
```
 does not cause intermittent failures any more in my env.

**Comment by anistor** [comment]
Changes done

**Comment by gustavonalle** [comment]
Integrated, thanks!

**Pull request closed without merging**
