### PR TITLE
ISPN-11513 ComposedSegmentedLoadWriteStore should not iterate over se…

### PR DESCRIPTION
**Pull request by wburns**
…gments in parallel

https://issues.redhat.com/browse/ISPN-11513

### CODE REVIEW

**Comment by danberindei** [comment]
@wburns the changes look ok to me, but the RocksDBStore tests disagree :)

**Comment by wburns** [comment]
Whoops accidentally wiped away the null check in the RocksDBStore code.

**Comment by wburns** [comment]
Should be fixed now.

**Comment by danberindei** [comment]
Merged, thanks Will!

**Pull request merged**
