### PR TITLE
ISPN-5322 Support replicated cache for PH in a read-only mode

### PR DESCRIPTION
**Pull request by danberindei**
https://issues.jboss.org/browse/ISPN-5322

### CODE REVIEW

**Comment by wburns** [comment]
I would say we might as well rename the JIRA so the commit message makes a little more sense :)

**Comment by danberindei** [comment]
@wburns I just changed the commit message, I think the JIRA can stay as is.

**Comment by wburns** [comment]
Sounds good, pulling...

**Comment by wburns** [comment]
Integrated into master & 7.2.x, thanks @danberindei !

**Pull request closed without merging**
