### PR TITLE
ISPN-11731 Add blockhound to query module

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.redhat.com/browse/ISPN-11731

### CODE REVIEW

**Comment by gustavonalle** [comment]
@wburns I wonder why Blockhound does not complain about this:

 https://github.com/infinispan/infinispan/blob/5d0bf286d76bda64ddb918ec31872ea9f54070d6/query/src/main/java/org/infinispan/query/clustered/ClusteredQueryInvoker.java#L72

I'd expect it to fail the tests

**Comment by wburns** [comment]
> @wburns I wonder why Blockhound does not complain about this:
> 
> https://github.com/infinispan/infinispan/blob/5d0bf286d76bda64ddb918ec31872ea9f54070d6/query/src/main/java/org/infinispan/query/clustered/ClusteredQueryInvoker.java#L72
> 
> I'd expect it to fail the tests

My guess is maybe it is invoked on a blocking thread. I would recommend running with `-Dmaven.surefire.debug` on the command line and add a breakpoint to see for sure.

**Comment by gustavonalle** [comment]
@wburns in library mode it blocks in the surefire thread while in server mode, both REST and HotRod perform queries in a separated executor. I've added a new commit to remote the 'isBlockingWrite' check from HotRod, the rest of the work to remove other blocks on query will come later

**Comment by wburns** [comment]
Integrated into master, thanks @gustavonalle !

**Pull request merged**
