### PR TITLE
ISPN-8714 Don't send acks for async-triangle

### PR DESCRIPTION
**Pull request by pruivo**
https://issues.jboss.org/browse/ISPN-8714

### CODE REVIEW

**Comment by pruivo** [comment]
@rvansa I don't think it is needed. If I'm not sending the ack and it is needed, some test would fail. If I send the ack and it isn't needed, it doesn't hurt :+1:

**Comment by gustavonalle** [comment]
@pruivo Can you rebase to retrigger CI?

**Comment by pruivo** [comment]
@gustavonalle sure

**Comment by gustavonalle** [comment]
@pruivo There are some test failures. Some of them are on master, could you double check?

**Comment by pruivo** [comment]
@gustavonalle I don't think they are related. I run the test suite locally a couple of times and I got no failures.

**Comment by gustavonalle** [comment]
merged, thanks @pruivo !

**Pull request merged**
