### PR TITLE
ISPN-9137 Add SHA-1 checksums to zip distributions

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-9137
https://issues.jboss.org/browse/ISPN-9138

Also fixes some issues with the distribution build

### CODE REVIEW

**Comment by gustavonalle** [comment]
looking

**Comment by gustavonalle** [comment]
I run ```mvn clean install -s maven-settings.xml -Pdistribution``` but could not find a sha1, am I missing something?

**Comment by tristantarrant** [comment]
cd distribution
mvn deploy
interrupt it as soon as it starts uploading and then look in target/distribution

**Comment by gustavonalle** [comment]
Merged, thanks @tristantarrant !

**Pull request merged**
