### PR TITLE
ISPN-7426 Upgrade to Hibernate Search 5.7.0.CR1 and Hibernate ORM 5.2…

### PR DESCRIPTION
**Pull request by Sanne**
….7.Final

 - https://issues.jboss.org/browse/ISPN-7426

### CODE REVIEW

**Comment by gustavonalle** [comment]
There are test failures in the JPA persistence

**Comment by Sanne** [comment]
@gustavonalle thanks, I updated the commit. Should be fixed..

**Comment by anistor** [comment]
LGTM. But let's wait for CI

**Comment by anistor** [comment]
Integrated in master. Thanks @Sanne !

**Comment by gustavonalle** [comment]
CI is broken:
```
[12:39:16]Failed to execute goal on project infinispan-server-feature-pack: Could not resolve 
dependencies for project org.infinispan.server:infinispan-server-feature-pack:pom:9.0.0-SNAPSHOT: 
Failure to find org.infinispan:infinispan-management-console:jar:9.0.0.Beta2 in 
http://maven.repository.redhat.com/earlyaccess/all/ was cached in the local repository, resolution 
will not be reattempted until the update interval of redhat-earlyaccess-repository-group has 
elapsed or updates are forced
```

It seems it cached a wrong artifact probably when the address of repository.jboss.org was hard coded
and now it needs manual intervention

**Pull request closed without merging**
