### PR TITLE
ISPN-5512, fix wrong/old code sample in chapter 5.1

### PR DESCRIPTION
**Pull request by mvrabel**

### CODE REVIEW

**Comment by galderz** [comment]
I don't think the correct changes have been applied here. It's true that the code discussed is supposed to match what's in the tutorial, but in this subsection, it simply talks about different caches sharing the same JGroups channel. The text refers to caches "1, 2 and 3", but it should be "replSyncCache, replAsyncCache and invalidationSyncCache".

I would then move the `TIP` section above to be within "Running Infinispan in a cluster" section.

**Comment by slaskawi** [comment]
I totally agree with @galderz. This switch adds additional noise to the documentation. 

But there is one thing what is worth correcting - cache names:
* `cache1` -> `replSyncCache`
* `cache2` -> `replAsyncCache`
* `cache3` -> `invalidationSyncCache`

**Comment by slaskawi** [comment]
@mvrabel Hey! Any update on this?

**Comment by mvrabel** [comment]
I'm very sorry for my late answer.  @slaskawi 
I agree with you, it would add unnecessary noise.
Should I revert my change and change the cache names and make another pull request ? 

    cache1 -> replSyncCache
    cache2 -> replAsyncCache
    cache3 -> invalidationSyncCache

**Comment by slaskawi** [comment]
@mvrabel I think putting everything into a single commit might be a good idea (you need to force push amended commit to your branch).

**Comment by tristantarrant** [comment]
Any news on this ?

**Comment by pruivo** [comment]
this is already committed in master. can it be closed?

**Comment by mvrabel** [comment]
yes it can be closed  - https://github.com/infinispan/infinispan/pull/3731

**Pull request closed without merging**
