### PR TITLE
ISPN-9263 Segmented Off Heap Data Container

### PR DESCRIPTION
**Pull request by wburns**
* Add off heap concurrent map to be used by segmented container

https://issues.jboss.org/browse/ISPN-9263
https://issues.jboss.org/browse/ISPN-8380

### CODE REVIEW

**Comment by wburns** [comment]
There are some related CI failures, but I was unable to reproduce them locally. I will have to keep trying.

https://ci.infinispan.org/job/Infinispan/job/PR-6217/3/#showFailuresLink

**Comment by wburns** [comment]
Think I fixed the ExceptionEvictionTest, it wasn't using the underlying storage key to do the peek. Not sure why it didn't fail locally.

Also the rest off heap appears to assume the entries are returned in a specific order, however there is no guarantee in which order the entries would be returned. Will have to make the test a bit more resilient to this.

**Comment by wburns** [comment]
Tests all pass now. Just need to clean up code a little bit.

**Comment by wburns** [comment]
CI passed with https://ci.infinispan.org/view/Infinispan/job/Infinispan/view/change-requests/job/PR-6217/5/ I refactored the entryStream a bit to be more OOM friendly, should still be fine though.

**Comment by wburns** [comment]
This also fixed https://issues.jboss.org/browse/ISPN-8380 since the new off heap containers use composition instead and remove expired entries. Tests have been updated to reflect that for off heap.

**Comment by wburns** [comment]
Performance for iteration/size results are pretty good. I am especially surprised that iteration is that much faster, as it still has to overcome the network overhead for returning all entries.

This is using https://github.com/infinispan/infinispan-benchmarks/tree/master/iteration configured to just use off heap with default settings with the following command

java -jar benchmark.jar -pvalueObjectSize=1024 -pkeyObjectSize=64 -pentryAmount=100000 -pbatchSize=16384 -puseIdentityCache=false

MASTER

Benchmark | (batchSize) | (entryAmount) | (keyObjectSize) | (nodes) | (useIdentityCache) | (useStrings) | (valueObjectSize) | Mode | Cnt | Score |   | Error | Units
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
JMHBenchmarks.iteratorParallel | 16384 | 100000 | 64 | 6 | FALSE | FALSE | 1024 | thrpt | 20 | 2.932 | ± | 0.073 | ops/s
JMHBenchmarks.iteratorSequential | 16384 | 100000 | 64 | 6 | FALSE | FALSE | 1024 | thrpt | 20 | 1.405 | ± | 0.034 | ops/s
JMHBenchmarks.noRehashIteratorParallel | 16384 | 100000 | 64 | 6 | FALSE | FALSE | 1024 | thrpt | 20 | 3.154 | ± | 0.125 | ops/s
JMHBenchmarks.noRehashIteratorSequential | 16384 | 100000 | 64 | 6 | FALSE | FALSE | 1024 | thrpt | 20 | 1.65 | ± | 0.03 | ops/s
JMHBenchmarks.sizeParallel | 16384 | 100000 | 64 | 6 | FALSE | FALSE | 1024 | thrpt | 20 | 7.698 | ± | 0.299 | ops/s
JMHBenchmarks.sizeSequential | 16384 | 100000 | 64 | 6 | FALSE | FALSE | 1024 | thrpt | 20 | 2.406 | ± | 0.569 | ops/s

NEW

Benchmark | (batchSize) | (entryAmount) | (keyObjectSize) | (nodes) | (useIdentityCache) | (useStrings) | (valueObjectSize) | Mode | Cnt | Score |   | Error | Units
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
JMHBenchmarks.iteratorParallel | 16384 | 100000 | 64 | 6 | FALSE | FALSE | 1024 | thrpt | 20 | 4.418 | ± | 0.093 | ops/s
JMHBenchmarks.iteratorSequential | 16384 | 100000 | 64 | 6 | FALSE | FALSE | 1024 | thrpt | 20 | 2.3 | ± | 0.056 | ops/s
JMHBenchmarks.noRehashIteratorParallel | 16384 | 100000 | 64 | 6 | FALSE | FALSE | 1024 | thrpt | 20 | 4.655 | ± | 0.307 | ops/s
JMHBenchmarks.noRehashIteratorSequential | 16384 | 100000 | 64 | 6 | FALSE | FALSE | 1024 | thrpt | 20 | 2.626 | ± | 0.042 | ops/s
JMHBenchmarks.sizeParallel | 16384 | 100000 | 64 | 6 | FALSE | FALSE | 1024 | thrpt | 20 | 41.527 | ± | 0.45 | ops/s
JMHBenchmarks.sizeSequential | 16384 | 100000 | 64 | 6 | FALSE | FALSE | 1024 | thrpt | 20 | 18.951 | ± | 0.119 | ops/s

Performance Increase

Benchmark | Percent Increase
-- | --
JMHBenchmarks.iteratorParallel | 50.68%
JMHBenchmarks.iteratorSequential | 63.70%
JMHBenchmarks.noRehashIteratorParallel | 47.59%
JMHBenchmarks.noRehashIteratorSequential | 59.15%
JMHBenchmarks.sizeParallel | 439.45%
JMHBenchmarks.sizeSequential | 687.66%

**Comment by wburns** [comment]
iirc I didn't implement a couple of the methods on the OffHeapConcurrentMap, but they aren't used at all currently - I can do that async to this though

**Comment by wburns** [comment]
Can confirm that bounded off heap iteration has the same perf essentially as unbounded. The difference will be in read/write perf which I will test to make sure the new bounded container doesn't have a regression there.

**Comment by wburns** [comment]
Testing put and get

Unbounded is comparable to master, with gets being a bit faster.

UNBOUNDED

Benchmark | Percent Increase
-- | --
JMHBenchmarks.iteratorParallel | 3.36%
JMHBenchmarks.iteratorSequential | 3.71%
JMHBenchmarks.noRehashIteratorParallel | 0.14%
JMHBenchmarks.noRehashIteratorSequential | 15.86%
JMHBenchmarks.sizeParallel | 1.07%

However bounded is a bit slower for all ops

BOUNDED

Benchmark | Percent Increase
-- | --
JMHBenchmarks.iteratorParallel | -3.20%
JMHBenchmarks.iteratorSequential | -3.06%
JMHBenchmarks.noRehashIteratorParallel | -4.62%
JMHBenchmarks.noRehashIteratorSequential | -5.20%
JMHBenchmarks.sizeParallel | -4.28%

I will try to see if there is anything I can do to speed the bounded variants, but I am not optimistic.

**Comment by wburns** [comment]
I ran it a second time and the numbers changed quite a bit, both were faster and under heavier concurrency the new bounded segmented container was faster, however individual read/writes were slower.


Benchmark | Percent Difference
-- | --
JMHBenchmarks.iteratorParallel | 2.65%
JMHBenchmarks.iteratorSequential | 2.73%
JMHBenchmarks.noRehashIteratorParallel | 1.91%
JMHBenchmarks.noRehashIteratorSequential | -8.34%
JMHBenchmarks.sizeParallel | -4.62%

I will try to see if I can find any way to improve performance more, but no changes so far have yielded anything and the code is very similar to before.

**Comment by wburns** [comment]
Added in replace implementations as well.

**Comment by wburns** [comment]
@danberindei these test failures are the ones related to jgroups update ? 
https://ci.infinispan.org/job/Infinispan/job/PR-6217/9/#showFailuresLink

Just curious because my PR had no failures before rebase to master.

**Comment by wburns** [comment]
Pretty sure the jgroups update caused the failures on CI, rebasing just to make sure they pass now though.

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request merged**
