### PR TITLE
ISPN-10380 QueryKnownClasses throws NotSerializableException

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.jboss.org/browse/ISPN-10380

### CODE REVIEW

**Comment by gustavonalle** [comment]
This is strange. What about the KeyValuePair externalizer?  https://github.com/infinispan/infinispan/blob/313b19301055c6267c6f2ea9065a7ab1b68099fe/core/src/main/java/org/infinispan/util/KeyValuePair.java#L37

**Comment by ryanemerson** [comment]
@gustavonalle This is due to the separation of the internal and persistence marshaller https://issues.jboss.org/browse/ISPN-9620

It has an Externalizer, but that's only for internal use i.e. not persistent. Whereas the KnownClasses cache is persistent, so when the key is delegated to the user marshaller via the PersistenceMarshaller, it has no notion of the KeyValuePair externalizer and hence the exception is thrown.

**Comment by ryanemerson** [comment]
Actually, thinking about it some more I should make `KnowClassKey` known to the PersistenceMarshaller.

**Comment by ryanemerson** [comment]
PersistenceContextInitializer added for the query module and `KnownClassesKey` converted

**Comment by gustavonalle** [comment]
There are some failures in query tests, are they happening on master as well?

**Comment by ryanemerson** [comment]
No, it seems my changes introduced them somehow

**Comment by ryanemerson** [comment]
@gustavonalle Failures fixed

**Comment by gustavonalle** [comment]
Merged, thanks @ryanemerson

**Pull request merged**
