### PR TITLE
ISPN-7153 AbstractClusteredWriteSkewTest can fail randomly still

### PR DESCRIPTION
**Pull request by wburns**
* Just do simple evict

https://issues.jboss.org/browse/ISPN-7153

### CODE REVIEW

**Comment by pruivo** [comment]
@wburns the title say "add documentation" but I didn't see any documentation modified :)

**Comment by wburns** [comment]
Lol, darn copy paste :)

**Comment by wburns** [comment]
Updated

**Comment by pruivo** [comment]
@wburns can you clean the unused imports?

**Comment by wburns** [comment]
sure

**Comment by wburns** [comment]
Fixed imports.

**Comment by pruivo** [comment]
thanks @wburns

**Comment by danberindei** [comment]
I guess I managed to push the commit without the imports fix before you @pruivo :)

**Comment by pruivo** [comment]
lol

**Comment by wburns** [comment]
@pruivo @danberindei more commits for me yay! :)

**Pull request merged**
