### PR TITLE
ISPN-16776 Cache org.infinispan.ROLES should wait initial state transfer

### PR DESCRIPTION
**Pull request by jabolina**
https://issues.redhat.com/browse/ISPN-16776

### CODE REVIEW

**Comment by tristantarrant** [comment]
I think we want this in the ClusterPermissionMapper too

**Comment by jabolina** [comment]
Update, thanks

**Review by wburns — APPROVED** [review]
LGTM

**Comment by wburns** [comment]
Looks like have to pass `globalConfiguration.isClustered()` instead of true as it breaks tests as we can't set it to true for a LOCAL cache.

**Comment by jabolina** [comment]
Updated.

**Pull request merged**
