### PR TITLE
 ISPN-9477 Remove unused infinispan-module.properties from query module 

### PR DESCRIPTION
**Pull request by anistor**
... and other query related internal enhancements

https://issues.jboss.org/browse/ISPN-9477
https://issues.jboss.org/browse/ISPN-9502
https://issues.jboss.org/browse/ISPN-9503
https://issues.jboss.org/browse/ISPN-9504

### CODE REVIEW

**Comment by anistor** [comment]
A series of small trivial cleanups :)

**Comment by tristantarrant** [comment]
These all look fine, but I'd rather see them grouped under one or two "cleanup" Jiras. Most commits can stay individual, however some should be squashed together, e.g. "A note for self"  :-)

**Comment by tristantarrant** [comment]
The only requirement is that commit messages are descriptive.

**Comment by tristantarrant** [comment]
Merged. Thanks

**Pull request merged**
