### PR TITLE
[9.4.x] - ISPN-11303 Local non-blocking get breaks hit/miss statistics

### PR DESCRIPTION
**Pull request by diegolovison**
https://issues.redhat.com/browse/ISPN-11303

### CODE REVIEW

**Comment by diegolovison** [comment]
@danberindei 

Before opening the PR to `master` I would like to ask a few questions:
* Is https://github.com/infinispan/infinispan/pull/8170/files#diff-fd0ea85b78c466195741c21051ff4fedR166 the right way to validate ISPN-11303?
* Why when I change https://github.com/infinispan/infinispan/pull/8170/files#diff-fd0ea85b78c466195741c21051ff4fedR37 to 2, the tests start failing?

**Comment by danberindei** [comment]
> @danberindei
> 
> Before opening the PR to `master` I would like to ask a few questions:
> 
>     * Is https://github.com/infinispan/infinispan/pull/8170/files#diff-fd0ea85b78c466195741c21051ff4fedR166 the right way to validate ISPN-11303?

That method by itself looks ok, but the setup is wrong.

A test for ISPN-11303 would have to send N read requests to the same server, and check that the server computes the hits and misses correctly even if it is not primary/backup owner for all the keys.

The cache is local, so there is no primary owner. The test needs a cluster with 3 nodes, a dist-cache with numOwners=2, and a client with `ClientIntelligence.BASIC`, so that the server receiving the requests can be either a primary owner, a backup owner, or a non-owner.

> 
>     * Why when I change https://github.com/infinispan/infinispan/pull/8170/files#diff-fd0ea85b78c466195741c21051ff4fedR37 to `2`, the tests start failing?

The client has all the servers in its [initial server list](https://github.com/infinispan/infinispan/pull/8170/files#diff-fd0ea85b78c466195741c21051ff4fedR52). Because there is no hash awareness for LOCAL caches, the client will send requests to all servers in a round-robin fashion, and the test only checks the number of hits/misses in one server.
Most likely because the cache is local, but

**Comment by diegolovison** [comment]
I fixed the test and now we have:
```
final int numServers = 3;
cfg.clustering().cacheMode(CacheMode.DIST_SYNC).hash().numOwners(2);
clientBuilder.clientIntelligence(ClientIntelligence.BASIC);
```
but it will fail.

**Comment by danberindei** [comment]
I opened a PR with a new test class: https://github.com/infinispan/infinispan/pull/8514

**Pull request closed without merging**
