### PR TITLE
[FIX] ISPN-6802 Micro-optimizations for read operations

### PR DESCRIPTION
**Pull request by pruivo**
* AbstractDataCommand shouldn't implement AbstractTopologyCommand

### CODE REVIEW

**Comment by pruivo** [comment]
run performance tests
library

**Comment by pruivo** [comment]
run performance tests please
library

**Comment by alanfx** [comment]
@pruivo currently I'm trying to run a performance test for @tristantarrant with a value size of 1kb for PR 4846

**Comment by alanfx** [comment]
@pruivo looks like this PR is getting tested first, but with 1KB values. Hope that's ok. @tristantarrant I'll try again when this one finishes

**Comment by pruivo** [comment]
@alanfx you can kill and run your test first if you want :)

**Comment by alanfx** [comment]
run performance tests please
library

**Comment by alanfx** [comment]
@pruivo I killed the job again, because I didn't run the other job correctly

**Comment by alanfx** [comment]
run performance tests please
library

**Comment by Holmistr** [comment]
run performance tests please
library

**Comment by Holmistr** [comment]
run performance tests please
library

**Comment by tristantarrant** [comment]
Merged

**Pull request merged**
