### PR TITLE
ISPN-5779 Add java.time.Instant support to the TimeService

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-5779

### CODE REVIEW

**Comment by anistor** [comment]
Looking ..

**Comment by anistor** [comment]
Looks good. @tristantarrant Do you need @pruivo to have a look too?

**Comment by pruivo** [comment]
@anistor looks good to me... the testsuite is still running in my laptop but so far so good.

**Comment by pruivo** [comment]
integrated! thanks @tristantarrant !

**Pull request closed without merging**
