### PR TITLE
ISPN-11489 TransactionCoordinator updated for non blocking

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-11489

### CODE REVIEW

**Comment by danberindei** [comment]
I see some new core failures, including a hanged teardown method:

https://ci.infinispan.org/job/Infinispan/job/PR-8087/1/testReport/

**Comment by wburns** [comment]
Weird most of the new ones don't even use transactions, which shouldn't
even be affected by these changes. I will look more closely tomorrow though.

**Comment by wburns** [comment]
I can't seem to reproduce any of these failures locally, even with `taskset -c 0`.

**Comment by wburns** [comment]
The test failures are unrelated and I have found some either on master or other PRs.

**Comment by wburns** [comment]
This fixes at least two random test failures. I would love to stop seeing
them on CI if someone could integrate this. 🙏

**Comment by danberindei** [comment]
Merged, thanks Will!

**Pull request merged**
