### PR TITLE
ISPN-9594 Update server trim list to WF14 components

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss.org/browse/ISPN-9594

Before: zipped=187M unzipped=214M
After: zipped=138M unzipped=160M

### CODE REVIEW

**Comment by ryanemerson** [comment]
@tristantarrant Nice work! It seems that one too many things may have been removed though: `HSEARCH000275: SerializationProvider service not found on the classpath`

**Comment by tristantarrant** [comment]
Yes, got that, still working on it.

**Comment by tristantarrant** [comment]
Readded avro and removed a bunch of other stuff. New sizes:
After: zipped=130M unzipped=150M

**Comment by tristantarrant** [comment]
@ryanemerson 'tis green

**Pull request merged**
