### PR TITLE
ISPN-7714

### PR DESCRIPTION
**Pull request by anistor**
https://issues.jboss.org/browse/ISPN-7714

### CODE REVIEW

**Comment by anistor** [comment]
This PR (temporarily) modifies the 9.1 schema, although it should first bump schemas to 9.2 and then modify that. I'll fix this once we have 9.2 work started on master.

**Comment by gustavonalle** [comment]
Depends on https://github.com/infinispan/infinispan/pull/5311

**Comment by tristantarrant** [comment]
Temporarily closing because of CI overload

**Comment by anistor** [comment]
Waiting for the 9.1.x branching to happen before re-issuing this.

**Comment by anistor** [comment]
Re-opened here: https://github.com/infinispan/infinispan/pull/5535

**Pull request closed without merging**
