### PR TITLE
ISPN-11301 SIFS tests should clear /tmp files per method call

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-11301

### CODE REVIEW

**Comment by danberindei** [comment]
This will work, but IMO `SoftIndexFileStore` not clearing the log files on `clear()` is a bug.

**Comment by ryanemerson** [comment]
@danberindei `LogAppender::clearAndPause` is called in the `clear()` method, however we don't call clear on cache shutdown so we need to remove the directories in the tests.

**Comment by danberindei** [comment]
@ryanemerson we do call `cl.clear()` in `BaseStoreTest::tearDown`, which is called after each method.

However, I see `BaseStoreFunctionalTest` uses `cleanup = CleanupPhase.AFTER_METHOD`, and `SingleCacheManagerTest` does not clear the caches before killing the cache manager. `MultipleCacheManagerTest` does it, so I suggest modifying `SingleCacheManagerTest.teardown()` to

```
      TestingUtil.clearContent(cacheManager);
      TestingUtil.killCacheManagers(cacheManager);
```

**Comment by ryanemerson** [comment]
@danberindei Updated to use `TestingUtil::clearContent`. In the stress test I have to manually remove the `tmpDirectory` as the mock-cache used to create a context is not cleared otherwise.

**Comment by danberindei** [comment]
Integrated, thanks Ryan!

**Pull request merged**
