### PR TITLE
ISPN-15287 Support Hibernate ORM 6.3

### PR DESCRIPTION
**Pull request by wburns**
https://issues.redhat.com/browse/ISPN-15287

### CODE REVIEW

**Comment by wburns** [comment]
I have manually confirmed this works with Hibernate 6.2, however, it would be nice to have some way to run with both versions automatically in CI. If anyone has any suggestions of the best way to do that, it would be great. I have tried setting the dependencies in a separate plugin execution and a different maven profile with no luck. :(

**Comment by tristantarrant** [comment]
Working on a possible fix

**Comment by tristantarrant** [comment]
@wburns just pushed my commit

**Comment by tristantarrant** [comment]
Jenkins is not grouping them properly by package

**Comment by tristantarrant** [comment]
@wburns added a commit that changes the report suffix, avoiding `.` characters. Let's see how Jenkins works.

**Comment by wburns** [comment]
Looks okay to me, although I would suggest squashing the suffix change assuming it works 🤞

**Comment by wburns** [comment]
Looks like the tests are now separated 🎉

**Comment by ryanemerson** [comment]
Thanks @tristantarrant and @wburns

**Pull request merged**
