### PR TITLE
[9.2.x] ISPN-9174 and ISPN-9205

### PR DESCRIPTION
**Pull request by gbadner**
This includes the commits from https://github.com/infinispan/infinispan/pull/6006.

https://issues.jboss.org/browse/ISPN-9174
https://issues.jboss.org/browse/ISPN-9205

### CODE REVIEW

**Comment by Sanne** [comment]
add to whitelist

**Comment by rvansa** [comment]
Could you please include only ISPN-9205 here?

**Comment by tristantarrant** [comment]
@gbadner can you rebase by removing the ISPN-9174 commit ?

**Comment by tristantarrant** [comment]
I created a PR with the individual commit: https://github.com/infinispan/infinispan/pull/6014

**Pull request closed without merging**
