### PR TITLE
ISPN-13082 Improper marshalling in caches without encoding

### PR DESCRIPTION
**Pull request by gustavonalle**
https://issues.redhat.com/browse/ISPN-13082

### CODE REVIEW

**Comment by ryanemerson** [comment]
LGTM, just waiting on a second CI run to make sure one of the failures isn't related.

**Comment by gustavonalle** [comment]
Triggered another couple of runs

**Comment by ryanemerson** [comment]
`XSiteMBeanTest.testRequestsSent` seems related.

If you rebase on the latest `main` the EventLogger failures should be resolved.

**Comment by gustavonalle** [comment]
@ryanemerson this test has been failing elsewhere, e.g. https://ci.infinispan.org/job/Infinispan/job/PR-9337/14/#showFailuresLink

**Comment by ryanemerson** [comment]
:+1: Merging then, thanks @gustavonalle

**Pull request merged**
