### PR TITLE
[14.0] ISPN-14977 Log ProtoStream entities on reindexing operations

### PR DESCRIPTION
**Pull request by fax4ever**
https://issues.redhat.com/browse/ISPN-14977
https://issues.redhat.com/browse/JDG-5994

Backport of #11044

### CODE REVIEW

**Comment by fax4ever** [comment]
Applied the last changes also here

**Comment by fax4ever** [comment]
Rebased

**Comment by ryanemerson** [comment]
Thanks @fax4ever

**Comment by fax4ever** [comment]
Thank you @ryanemerson

**Pull request merged**
