### PR TITLE
Revert "ISPN-5876 Invalidate keys on commit if 2-phase"

### PR DESCRIPTION
**Pull request by bmaxwell**
This reverts commit 4f9556ca8d9c8c136be721de778e7a277c7d7b59.

Need to revert as this causes a change in default behavior, we need to rethink it, make an option to enable the new behavior
https://bugzilla.redhat.com/show_bug.cgi?id=1273147

### CODE REVIEW

**Comment by slaskawi** [comment]
Hey @galderz! Could you please look into this? It seems you have broader knowledge in this area.

**Comment by slaskawi** [comment]
Comments from me - it would be nice to have some JIRA + description what is the desired behavior.

**Comment by galderz** [comment]
@bmaxwell Right, we could revert this but is the option to enable it needed at all? Did you verify that this change, in spite of changing the default, works as expected for the problem you had?

**Comment by galderz** [comment]
We have agreed to revert this change and instead fix it by adding an system property to enable this behaviour.

**Comment by galderz** [comment]
Integrated

**Pull request closed without merging**
