### PR TITLE
ISPN-8616 DistAsyncFuncTest.testMergeFromNonOwner random failures

### PR DESCRIPTION
**Pull request by rvansa**
https://issues.jboss.org/browse/ISPN-8616?jql=text%20~%20%22DistAsyncFuncTest%22

### CODE REVIEW

**Comment by danberindei** [comment]
I sense a lot of conflicts with https://github.com/infinispan/infinispan/pull/5691 :)

**Comment by rvansa** [comment]
@danberindei Then merge it and deal with the conflicts :)

**Comment by rvansa** [comment]
@danberindei Okay, you've rewritten that part as well; will you claim the JIRA in #5691 and should I close this one?

**Comment by danberindei** [comment]
Closing this.

**Pull request closed without merging**
